### DISCUSSION TITLE
pipeline results  with a `failed` pipelineRun

### DISCUSSION THREAD

**Discussion by pritidesai** [tektoncd/pipeline#4279] [General]
The pipeline results are not published when a pipelineRun fails. The pipeline results could have a reference to a successful task with a task result but any subsequent task failure stops publishing the pipeline results.

This is addressing the comment [here](https://github.com/tektoncd/pipeline/issues/3749#issuecomment-846032516) and part of issue #3749.

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipelinerun-result-
spec:
  pipelineSpec:
    results:
      - name: image-a
        value: $(tasks.task-a.results.image)
    tasks:
      - name: task-a
        taskSpec:
          results:
            - name: image
          steps:
            - name: success
              image: alpine
              script: |
                echo -n "my-image-a" > $(results.image.path)
      - name: task-b
        taskSpec:
          results:
            - name: image
          steps:
            - name: failure
              image: alpine
              script: |
                exit 1
```

This pipeline has a result reference `image-a` to a task result `image` of the first task but since `task-b` results in failure, the pipeline results are not published. The taskRun for the first task does have a task result initialized.

pipeline result is empty:

```shell
  kubectl get pr pipelinerun-result-k6drq -o json | jq .status.pipelineResults
  null
```

task result is initialized:

```shell
  kubectl get tr pipelinerun-result-k6drq-task-a-f628v -o json | jq .status.taskResults
  [
    {
      "name": "image",
      "value": "my-image-a"
    }
  ]

```

The concern here is the result is initialized in the taskRun but not propagated to the pipelineRun status. I have pinged @ppitonak for more real world use case to share.

I think its safe here to unblock pipeline result if the task result is initialized in the taskRun.

EDIT: This task result `$(tasks.task-a.results.image)` is allowed to be consumed by any subsequent task until a failure is hit and at the same time the same task result does not make it to the pipeline result which is inconsistent.

**Comment by ppitonak** [comment]
My use-case is following:
1. We archive various artifacts from our pipeline runs on an external service
2. The very first task generates the future URL of directory for this particular pipeline run, e.g. https://artifacts.mycompany.com/mypipelinerun/210908-111711/, publishes it as a result
3. Then we run multiple test suites, each in its own taskrun, they upload test reports, screnshots, logs etc to the URL from step 2
4. In finally, we do cleanup
5. Pipeline publishes this URL, OpenShift Console shows this URL in pipeline run view so it's very convenient to find all artifacts and review test results etc.

![pipeline-results](https://user-images.githubusercontent.com/445100/136161956-c6f69863-15bc-4411-be00-5ab4ff30d642.png)

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-result
spec:
  tasks:
  - name: generate
    taskSpec:
      results:
      - name: url
      steps:
      - name: generate
        image: registry.access.redhat.com/ubi8/ubi-minimal
        script: |
          # in real world this task would have a param that we would set to $(context.pipelineRun.name)
          # the script would then remove the generated suffix from pipeline run name and would construct the string with current timestamp
          echo "https://artifacts.mycompany.com/mypipelinerun/210908-111711/" > $(results.url.path)
          echo "Done"
  - name: test-suite-1
    runAfter:
    - generate
    taskSpec:
      steps:
      - name: test
        image: registry.access.redhat.com/ubi8/ubi-minimal
        script: |
           # in real world this task would have a param with result of the first task
          echo "Done"
  - name: test-suite-2
    runAfter:
    - generate
    taskSpec:
      steps:
      - name: test
        image: registry.access.redhat.com/ubi8/ubi-minimal
        script: |
          # in real world this task would have a param with result of the first task
          echo "Done"
  finally:
  - name: cleanup
    taskSpec:
      steps:
      - name: cleanup
        image: registry.access.redhat.com/ubi8/ubi-minimal
        script: |
          echo "Done"
  results:
  - name: artifacts-url
    value: $(tasks.generate.results.url)
```
