### DISCUSSION TITLE
Different values of the same parameter for different Tasks in the Pipeline

### DISCUSSION THREAD

**Discussion by KIRY4** [tektoncd/pipeline#4917] [Q&A]
Hello everyone!

https://tekton.dev/docs/pipelines/pipelineruns/#specifying-parameters - You can specify Parameters that you want to pass to the Pipeline during execution, **including different values of the same parameter for different Tasks in the Pipeline**

Can someone provide me example? I have two gradle tasks (https://hub.tekton.dev/tekton/task/gradle) in my pipeline. Let's say they have following names: gradle_1, gradle_2 running one by one.

How can I pass for task gradle_1 value for parameter TASK = build, and for gradle_2 TASK=something else? 

Or maybe it is possible to create only one gradle task in pipeline and it will be executed so many times how many I provide values for TASKS parameter? Is it possible?

**Comment by dibyom** [comment]
you can have two tasks in a pipeline each of which can reference the same gradle task but pass in different parameters

**Reply by marniks7** [reply]
Assumed you have `gradle` task with params `param`.
In pipeline you can create two parameters `gradle-param-1` and `gradle-param-2` and you can map those params to the `param`
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: example
spec:
  params:
    - name: gradle-param-1
      type: string
      default: "300s"
    - name: gradle-param-2
      type: string
      default: "60s"
  tasks:
    - name: gradle-1
      taskRef:
        name: gradle
      params:
        - name: param
            value: $(params.gradle-param-1)
    - name: gradle-2
      taskRef:
        name: gradle
      params:
        - name: param
          value: $(params.gradle-param-2)
```
