### DISCUSSION TITLE
How to trigger pipeline when pull request opened in Bitbucket

### DISCUSSION THREAD

**Discussion by KIRY4** [tektoncd/pipeline#5340] [Q&A] [answered]
Hello everyone! 

Need some help! I can't figure what I'm doing wrong or what I'm missing. I have Tekton Pipeline and all related objects which are successfully triggering pipeline after code push to one of repo branches, also I have Webhook in Bitbucket which at least can capture code push to one of repo branches. So this part works fine. 

** Also I need to trigger pipeline and run some tasks every time when Pull Request is opened**. The problem that when I create/open Pull Request nothing is happening. So I need help with figuring out what's wrong... Will really appreciate any suggestions/advices how to force it to work.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/42247943/185435663-9364c83a-2013-44ec-8dd8-65f8de0faa4f.png">
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/42247943/185435992-67923ef2-7a9e-45cc-b53c-ef51548924af.png">

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mrc-new-pipeline
spec:
  params:
    - name: GIT_URL
      type: string
      description: the context directory from where to build the application
    - name: revision
      type: string
      description: git revision to push
    - name: git-repo-name
      type: string
      description: Name of application to build
  workspaces:
    - name: source
  tasks:
    - name: git-clone
      retries: 2
      params:
        - name: GIT_URL
          value: "$(params.GIT_URL)"
        - name: revision
          value: "$(params.revision)"
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: source

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: mrc-new-bitbucket-listener
spec:
  serviceAccountName: tekton-triggers
  triggers:
    - triggerRef: mrc-new-trigger

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: mrc-new-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "bitbucket"
      params:
        - name: secretRef
          value:
            secretName: bitbucket-interceptor
            secretKey: secretToken
        - name: eventTypes
          value:
            - repo:refs_changed
            - pr:opened
  bindings:
    - ref: mrc-new-trigger-binding
  template:
    ref: mrc-new-trigger-template

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: mrc-new-trigger-binding
spec:
  params:
  - name: git-repo-url
    value: ssh://git@code.myrepo.com:7999/$(body.repository.project.key)/$(body.repository.name).git
  - name: git-revision
    value: $(body.changes[0].ref.displayId)
  - name: git-repo-name
    value: $(body.repository.name)

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: mrc-new-trigger-template
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
  - name: git-repo-name
    description: The name of the deployment to be created / patched

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: $(tt.params.git-repo-name)-$(tt.params.git-revision)-
    spec:
      serviceAccountName: mrc-pipeline
      pipelineRef:
        name: mrc-new-pipeline
      params:
        - name: GIT_URL
          value: $(tt.params.git-repo-url)
        - name: revision
          value: $(tt.params.git-revision) #development
        - name: git-repo-name
          value: $(tt.params.git-repo-name)
      workspaces:
        - name: source
          persistentVolumeClaim:
            claimName: pipeline-pvc
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-mrc-new
  annotations:
  labels:
    app.kubernetes.io/instance: tekton-triggers
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: mrc-new-bitbucket-listener
spec:
  host: el-mrc-new-cicd.apps.blabla.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-mrc-new-bitbucket-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    certificate: |
...
```

**Comment by KIRY4** [comment, marked as answer]
Here is answer! To make this pipeline work with Pull Request, it was necessary to rewrite everything in accordance with Bitbucket Pull Request event payload.
https://confluence.atlassian.com/bitbucketserver0721/event-payload-1115665959.html?utm_campaign=in-app-help&utm_medium=in-app-help&utm_source=stash#Eventpayload-pullrequest

```
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: mrc-new-trigger-binding
spec:
  params:
  # - name: git-repo-url
  #   value: ssh://git@code.myrepo.com:7999/$(body.repository.project.key)/$(body.repository.name).git
  # - name: git-revision
  #   value: $(body.changes[0].ref.displayId)
  # - name: git-repo-name
  #   value: $(body.repository.name)
  - name: git-repo-name-pr
    value: $(body.pullRequest.fromRef.repository.name)
  - name: git-repo-url-pr
    value: ssh://git@code.myrepo.com:7999/$(body.pullRequest.fromRef.repository.project.key)/$(body.pullRequest.fromRef.repository.name).git
  - name: git-revision-pr
    value: $(body.pullRequest.fromRef.displayId)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: mrc-new-trigger-template
spec:
  params:
  # - name: git-repo-url
  #   description: The git repository url
  # - name: git-revision
  #   description: The git revision
  # - name: git-repo-name
  #   description: The name of the deployment to be created / patched
  - name: git-repo-url-pr
  - name: git-revision-pr
  - name: git-repo-name-pr

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: $(tt.params.git-repo-name-pr)-$(tt.params.git-revision-pr)-
    spec:
      serviceAccountName: mrc-pipeline
      pipelineRef:
        name: mrc-new-pipeline
      params:
        # - name: GIT_URL
        #   value: $(tt.params.git-repo-url)
        # - name: revision
        #   value: $(tt.params.git-revision) #development
        # - name: git-repo-name
        #   value: $(tt.params.git-repo-name)
        - name: GIT_URL
          value: $(tt.params.git-repo-url-pr)
        - name: revision
          value: $(tt.params.git-revision-pr)
        - name: git-repo-name
          value: $(tt.params.git-repo-name-pr)
      workspaces:
        - name: source
          persistentVolumeClaim:
            claimName: pipeline-pvc
```
