### DISCUSSION TITLE
Usage of finally: in PipelineRun with pipelineRef git resolver

### DISCUSSION THREAD

**Discussion by brunocascio** [tektoncd/pipeline#5926] [Q&A]
Hi folks,

I'm trying to use `finally:` as following in my `PipelineRun` which use pipelineRef with git resolver feature.

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: bitbucket-pipeline-
spec:
  params:
    - ...
  workspaces:
    - ...
  pipelineRef:
    resolver: git
    params:
      - ...
    # ---- this does not work ---
    finally:
      - name: notify-failure
        when:
          - input: "$(tasks.status)"
            operator: in
            values: ["Failure"]
        taskSpec:
          steps:
            - name: send-notification
              image: curlimages/curl:7.87.0
              args:
                - -X 
                - POST
                - -H 
                - 'Content-Type: application/json' 
                - --data 
                - '{"state": "INPROGRESS", "key": "1", "name": "test", "url": "example.com", "description": "hello"}'
                - "https://bitbucket.example.com/rest/build-status/1.0/commits/$(params.git_commit_sha)"
```

The idea behind it is to be able to mark commits as `succeded` or `failed` depending on the result of the "delegated" pipeline. It means, developer are in charge of writing pipelines, but not in charge of notifying bitbucket about their pipeline results.

it it possible to use `finally:` block on pipelineRef with git resolver?

Thanks
