### DISCUSSION TITLE
How to know which task failed and get stacktrace in finally block?

### DISCUSSION THREAD

**Discussion by XiaosongWen** [tektoncd/pipeline#5956] [Q&A]
Hi I am building a pipeline to do some ops on github, currently my finally block is like this:
```
finally:
    - name: report-pipeline-failed-to-ghe
      when:
        - input: $(tasks.status)
          operator: in
          values: [ "Failed", "None" ]
      taskRef:
        name: github-set-status
```
I suppose this will be triggered when any of the task failed, but is there a way to know which specific task fail and get it's log (or maybe tracestack)?
