### DISCUSSION TITLE
Task Volume vs TaskRun PodTemplate Volume

### DISCUSSION THREAD

**Discussion by sunyeongchoi** [tektoncd/pipeline#6482] [Q&A]
I'm curious about the priority of `Task's Volume` and `TaskRun's PodTemplate Volume`
My expectation is that `podTemplate` will have higher priority.  
Am I correct in my expectation that `podTemplate` will have higher priority?  

Below are examples `TaskRun's PodTemplate Volume` and `Task's Volume`

```yaml
# TaskRun PodTemplate Volume Example
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: mytaskrun
  namespace: default
spec:
  taskRef:
    name: mytask
  podTemplate:
    ...
    volumes:
      - name: my-cache
        persistentVolumeClaim:
          claimName: my-volume-claim
```  
```yaml
# Task Volume Example
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: example-task-name
spec:
  params:
    ..
  steps:
   ..
    - name: dockerfile-pushexample
      image: gcr.io/example-builders/push-example
      args: ["push", "$(resources.outputs.builtImage.url)"]
      volumeMounts:
        - name: docker-socket-example
          mountPath: /var/run/docker.sock
  volumes:
    - name: example-volume
      emptyDir: {}
```
