### DISCUSSION TITLE
Resolver - cluster resolver inside a Pipeline ?

### DISCUSSION THREAD

**Discussion by darktempla** [tektoncd/pipeline#6811] [Q&A]
`tekton version = v0.48.0`

Previously I was making use exclusively of `ClusterTask` objects to share and reference tasks inside my cluster. 

For example
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pypi-poetry-publish
spec:
  tasks:
    - name: build-and-publish
      taskRef:
        kind: ClusterTask
        name: poetry-publish
      params:
        - name: image
          value: "$(params.poetry-image)"
        - name: poetry-version-patch-type
          value: "$(params.poetry-version-patch-type)"
```
After converting this pipeline to the "resolver" way of doing things.
```yaml
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pypi-poetry-publish
spec:
  tasks:
    - name: build-and-publish
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: namespace
            value: tekton-shared
          - name: name
            value: poetry-publish
     params:
        - name: image
          value: "$(params.poetry-image)"
        - name: poetry-version-patch-type
          value: "$(params.poetry-version-patch-type)"
```
I get this error when trying to create the pipeline on my cluster.

```bash
Error from server (BadRequest): 
error when creating "pipelines/pypi-poetry-publish/0.1/pypi-poetry-publish.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: must not set the field(s):
spec.tasks[0].taskref.params, spec.tasks[0].taskref.resolver, spec.tasks[1].taskref.params, spec.tasks[1].taskref.resolver
```
The task definitely exists as can be seen below:
```bash
$ k get tasks -A
NAMESPACE       NAME             AGE
tekton-shared   git-tag          109m
tekton-shared   poetry-test      108m
tekton-shared   poetry-publish   108m
tekton-shared   java-task        108m
```

Any help about best practice around the NEW resolver way of doing things would be appreciated.

_To be fair the documentation on the tekton website doesn't really have good clear examples around how this should work and I saw nothing that says you cannot use resolvers in pipelines :(_
