### DISCUSSION TITLE
How to pass params to a remote (git) pipeline?

### DISCUSSION THREAD

**Discussion by james-callahan** [tektoncd/pipeline#7066] [Q&A] [answered]
e.g. using the `git` resolver, I'd like to pass parameters to my pipeline.

The `params` field inside of a `TriggerTemplate` is the parameters for the resolver itself:

```yaml
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        # namespace: tekton-ci
        generateName: github-run-
      spec:
        pipelineRef:
          resolver: git
          params:
            - name: org
              value: $(tt.params.githuborg)
            - name: repo
              value: $(tt.params.githubrepository)
            - name: revision
              value: $(tt.params.gitrevision)
            - name: pathInRepo
              value: /tekton-pipeline.yaml
```

So how can I pass params to my pipeline? e.g. if this was saved at `/tekton-pipeline.yaml` in my repository:
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mycoolpipeline
spec:
  params:
    - name: hello
      type: string
  description: much tekton
  tasks:
    - name: hello
      taskSpec:
        steps:
          - image: archlinux:base@sha256:b29dab0d5f362cfe2ed4662c46f27855681d56fb548fd2f6d927fd573131178a
            script: echo "hello $(params.hello)"
```

**Comment by vdemeester** [comment, marked as answer]
@james-callahan the same way as you pass it using "in-cluster" pipeline references. Something like the following.

```
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        # namespace: tekton-ci
        generateName: github-run-
      spec:
        params:
            - name: hello
              value: world
        pipelineRef:
          resolver: git
          params:
            - name: org
              value: $(tt.params.githuborg)
            - name: repo
              value: $(tt.params.githubrepository)
            - name: revision
              value: $(tt.params.gitrevision)
            - name: pathInRepo
              value: /tekton-pipeline.yaml
```
