### DISCUSSION TITLE
Shared PVC for all pipeline

### DISCUSSION THREAD

**Discussion by julienroy50** [tektoncd/pipeline#8755] [Q&A]
We are trying to minimize the execution time of our pipelines and also the network footprint. We want to have a share PVC across all pipelines that will contains m2 directory for maven. We did not succeed in doing so. Need your help. 

Are are some information on our configuration:
In feature-flags we have
```
coschedule: pipelineruns
disable-affinity-assistant: "true"
```
Our Share PVC is declared such as this
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-maven-m2-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "ocs-storagecluster-cephfs"
  resources:
    requests:
      storage: 3Gi
```
The errors encounter are
```
STEP-MVN-GOALS
2025-05-07T18:31:28.440315969Z [ERROR] Could not create local repository at /workspace/maven-local-repo/.m2 -> [Help 1]
2025-05-07T18:31:28.441528242Z [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException
```
The same solution works fine with a single execution. The error only occurs when multiple pipeline are running and trying to access the volume at the same time.
