### ISSUE TITLE
Task input "from" requires inputs to have the same name

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/pipeline#1002]
When providing the output of one task as an input to another task in a `Pipeline`, the `source-copy` step fails if the resource names are not the same. For example:

Task 1:
```yaml
kind: Task
metadata:
  name: mvn-build
spec:
  inputs:
    resources:
    - name: build-source
      targetPath: /
      type: git
  outputs:
    resources:
    - name: build-source
      type: git
```

Task 2:
```yaml
kind: Task
metadata:
  name: mvn-test
spec:
  inputs:
    resources:
    - name: test-source
      targetPath: /
      type: git
```

An the pipeline:
```yaml
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  resources:
  - name: app-git
    type: git
  tasks:
  - name: build
    taskRef:
      name: mvn-build
    resources:
      inputs:
      - name: build-source
        resource: app-git
      outputs:
      - name: build-source
        resource: app-git
  - name: test
    taskRef:
      name: mvn-test
    resources:
      inputs:
      - name: test-source
        resource: app-git
        from: [build]
```

Then the pipelinerun fails with 
```json
{"level":"error","ts":1561367722.1517646,"logger":"fallback-logger","caller":"bash/main.go:62","msg":"Error executing command \"cp -r /pvc/build/test-source/. /workspace\" with arguments cp: can't stat '/pvc/build/test-source/.': No such file or directory\n","stacktrace":"main.main\n\t/Users/ssadeghi/go/src/github.com/tektoncd/pipeline/cmd/bash/main.go:62\nruntime.main\n\t/usr/local/Cellar/go/1.12.6/libexec/src/runtime/proc.go:200"}
```

The git sources are copied to `/pvc/build/build-source` in the first task while the second task looks for them in `/pvc/build/test-source`.

This is particularly problematic when importing tasks that the user has not created themselves.
