### ISSUE TITLE
Unable to use docker secrets to push image to dockerhub

### ISSUE THREAD

**Issue by StrongMonkey** [tektoncd/pipeline#1005]
# Expected Behavior
When using docker secrets to build and push image, I should be able to reference the secret, build and push my build image by following https://github.com/tektoncd/pipeline/blob/master/docs/auth.md.
# Actual Behavior
Unable to push image.
# Steps to Reproduce the Problem

1. Create a clusterTask:
```
apiVersion: tekton.dev/v1alpha1
    kind: ClusterTask
    metadata:
      name: buildkit
    spec:
      inputs:
        resources:
        - name: source
          type: git
        params:
        - name: image
          description: Where to publish the resulting image
        - name: dockerfile
          description: The name of the Dockerfile
        - name: docker-context
          description: The context of the build
        - name: push
          description: Whether push or not
          default: "true"
        - name: workingdir
          description: The directory containing the app
          default: "/workspace"
        - name: buildkit-client-image
          description: The name of the BuildKit client (buildctl) image
          default: "moby/buildkit:master"
        - name: buildkit-server-address
          description: The address of the BuildKit daemon (buildkitd) service
        - name: insecure-registry
          description: Whether to use insecure registry
      outputs:
        resources:
        - name: output-image
          type: image
      volumes:
      - name: buildkit-cache
        hostPath:
          path: /var/lib/buildkit/runc-overlayfs/content
          type: DirectoryOrCreate
      steps:
      - name: build-and-push
        image: $${inputs.params.buildkit-client-image}
        command: ["buildctl-daemonless.sh"]
        workingDir: /workspace/source
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/buildkit/runc-overlayfs/content
          name: buildkit-cache
        args: ["build",
                  "--progress=plain",
                  "--frontend=dockerfile.v0",
                  "--frontend-opt", "filename=$${inputs.params.dockerfile}",
                  "--local", "context=$${inputs.params.docker-context}", "--local", "dockerfile=.",
                  "--output", "type=image,name=$${inputs.params.image},push=true,registry.insecure=$${inputs.params.insecure-registry}"]
```
2. Create a secret, service account, using service in taskRun
```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  labels:
    service-name: optimistic-wright2
    service-namespace: default
    tekton.dev/task: buildkit
  name: optimistic-wright2-7b5a5-e6af3
  namespace: default
spec:
  inputs:
    params:
    - name: image
      value: index.docker.io/strongmonkey1992/default-optimistic-wright2:2cc4018aa26188f2f29c3adb32154d3fcdd3be5e
    - name: buildkit-server-address
      value: tcp://buildkit.rio-system:9001
    - name: insecure-registry
      value: "false"
    - name: dockerfile
      value: Dockerfile
    - name: docker-context
      value: .
    resources:
    - name: source
      resourceRef: {}
      resourceSpec:
        params:
        - name: url
          value: https://github.com/StrongMonkey/priv-repo
        - name: revision
          value: 2cc4018aa26188f2f29c3adb32154d3fcdd3be5e
        type: git
  outputs:
    resources:
    - name: output-image
      resourceRef: {}
      resourceSpec:
        params:
        - name: url
          value: index.docker.io/strongmonkey1992/default-optimistic-wright2:2cc4018aa26188f2f29c3adb32154d3fcdd3be5e
        type: image
  serviceAccount: optimistic-wright2-7b5a5-2cc4018aa26188f2f29c3adb32154d3f-4e8ca
  taskRef:
    kind: ClusterTask
    name: buildkit
```
3. Image was built successfully within buildkit, but failed to push with the following error:
```
error: failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed
```

# Additional Info
Found that in cred-init, there is no user-agent header when mounting docker secrets into file. I noticed this difference https://github.com/tektoncd/pipeline/blob/master/pkg/credentials/dockercreds/creds.go#L90 when comparing with my own config file generated from docker login:
docker login generated:
```
{
    "auths": {
        "https://index.docker.io/v1/": {
            "auth": "redacted"
        }
    },
    "HttpHeaders": {
        "User-Agent": "Docker-Client/18.09.5-ce (linux)"
    }
}
```
cred-init generated:
```
{
	"auths": {
		"https://index.docker.io/v1": {
			"password": "redacted",
			"username": "redacted",
			"auth": "redacted",
			"email": "not@val.id"
		}
	}
}
```

When add HttpHeaders, buildkit was able to push the image successfully.
