### ISSUE TITLE
Unable to combine params

### ISSUE THREAD

**Issue by kameshsampath** [tektoncd/pipeline#1008]
Task params with combination of two or more params is not getting expanded.

# Expected Behavior
The parameters should be expanded

# Actual Behavior
Some weird wrong value getting expanded. 

# Steps to Reproduce the Problem

1.  Create a task like 

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kubectl-task
spec:
 inputs:
  resources:
    - name: git-source
      type: git
    - name: containerImage
      type: image
  params:
    - name: contextDir
      default: /workspace/git-source
      description: The Docker build context Dir
    - name: resourceDir
      default: "kubernetes"
      description: "xx"     
    - name: resourceFile
      description: The Kubernetes resource file
      default: "deployment.yaml"
    - name: yamlPath
      description: The YAML image path i.e. the container image that is built as part of the build
      default: "spec.template.spec.containers[0].image"
    - name: docs
      description: The YAML documents where to apply 
      default: "-d0"
    - name: namespace
      description: The Kubernetes Namespace
      default: "demos"
 steps:
    - name: run-yq
      image: quay.io/rhdevelopers/tutorial-tools
      imagePullPolicy: IfNotPresent
      command: 
       - "yq"
      args:
        - "w"
        - "-i"
        - "${inputs.params.resourceDir}/${inputs.params.resourceFile}"
        - "${inputs.params.yamlPath}"
        - "${inputs.resources.containerImage.url}"
        - "${inputs.params.docs}"
      workingDir: "${inputs.params.contextDir}"
    - name: run-kubectl
      image: quay.io/rhdevelopers/tutorial-tools
      imagePullPolicy: IfNotPresent
      command: 
       - "kubectl"
      args:
        - "apply"
        - "--namespace"
        - "${inputs.params.namespace}"
        - "--recursive"
        - "--filename"
        - "${inputs.params.resourceDir}"
      workingDir: "${inputs.params.contextDir}"
```
2. Create a task run like 
```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: update-and-apply
spec:
  taskRef:
    name: kubectl-task
  inputs:
    resources:
      - name: git-source
        resourceRef:
          name: demo-git-source
      - name: containerImage
        resourceRef:
          name: greeter-local-image-jvm
    params:
    - name: namespace
      value: demos
    - name: resourceDir
      default: "knative"
    - name: resourceFile
      default: "service.yaml"
  outputs: {}
```
3. when you apply the task and taskrun above you will see a error like:

```
[run-yq] Error: Error reading document at index 0, yaml: input error: read /: is a directory: yaml: input error: read /: is a directory
[run-yq] 16:05:47 safelyRenameFile [ERRO] Failed copying from /tmp/temp347995269 to /
[run-yq] 16:05:47 safelyRenameFile [ERRO] open /: is a directory
[run-yq] Usage:
[run-yq]   yq write [yaml_file] [path] [value] [flags]
[run-yq]
[run-yq] Aliases:
[run-yq]   write, w
[run-yq]
[run-yq] Examples:
[run-yq]
[run-yq] yq write things.yaml a.b.c cat
[run-yq] yq write --inplace -- things.yaml a.b.c --cat
[run-yq] yq w -i things.yaml a.b.c cat
[run-yq] yq w --script update_script.yaml things.yaml
[run-yq] yq w -i -s update_script.yaml things.yaml
[run-yq] yq w --doc 2 things.yaml a.b.d[+] foo
[run-yq] yq w -d2 things.yaml a.b.d[+] foo
[run-yq]
[run-yq]
[run-yq] Flags:
[run-yq]   -d, --doc string      process document index number (0 based, * for all documents) (default "0")
[run-yq]   -h, --help            help for write
[run-yq]   -i, --inplace         update the yaml file inplace
[run-yq]   -s, --script string   yaml script for updating yaml
[run-yq]
[run-yq] Global Flags:
[run-yq]   -t, --trim      trim yaml output (default true)
[run-yq]   -v, --verbose   verbose mode
[run-yq]
[run-yq] 16:05:47 main [ERRO] Error reading document at index 0, yaml: input error: read /: is a directory: yaml: input error: read /: is a directory
```

# Additional Info

PipelineResources:

```yaml
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: demo-git-source
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/redhat-developer-demos/quarkus-pipeline-demo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: greeter-local-image-jvm
spec:
  type: image
  params:
    - name: url
      # need to enable registry add-on in minikube via minikube addon enable registry
      value: dev.local/rhdevelopers/pipeline-greeter:jvm
```
