### ISSUE TITLE
Expose pipeline run metadata to Tasks and Conditions

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#1020]
Condition containers need access to metadata about the pipeline run. The metadata will be in the form of  a `pr-metadata.json` file that is present in the `workspace` directory.

Part of implementation of #27

ref: https://github.com/tektoncd/pipeline/issues/1137

**Comment by bobcatfish** [comment]
@dibyom are you still working on this or can we throw it back in the backlog?

**Comment by dibyom** [comment]
> @dibyom are you still working on this or can we throw it back in the backlog?

Thanks for the reminder. Moved to backlog -- here's why:

1. There is a workaround that @akihikokuroda mentioned in the design doc: https://github.com/tektoncd/pipeline/issues/1016#issuecomment-542388985

2. The injected pipelinerun status is likely to be stale if there are parallel taskruns -- to counter the user would have to resort to the workaound above

3. Probably not going to be useful until we have #1376 as well.

I think we should take another look at this post #1376

**Comment by pritidesai** [comment]
This feature is essential for `finally`,  final tasks are executed after all Pipeline Tasks are finished executing with success or after a single Pipeline Task fails. The scope of this design goes beyond just conditional containers, and applies to all final task containers and possibly all pipeline task containers.

[Design Doc](https://docs.google.com/document/d/1lxpYQHppiWOxsn4arqbwAFDo4T0-LCqpNa6p-TJdHrw/edit?disco=AAAAJcDWe48)

@dibyom I would like to collaborate on the design, planning on working on it after core `finally` functionality is merged (PR #2650 and PR #2661). Looking at the design right now 👀 

/assign

**Comment by dibyom** [comment]
Excellent!! 😃 
I had a old [proposal](https://docs.google.com/document/d/1eJBb2VHuSTbrIWfPE3TGdRRfdbJsRCOBIqfTwx9M3H8/edit#heading=h.2f7asw3l4lo9) though I am not sure how much of that is still relevant especially with finally containers! Feel free to suggest something different it that makes more sense!

**Comment by bobcatfish** [comment]
I think @dibyom 's proposal to provide this info via json file is a great first step toward what we need for both conditions + finally. We can always follow that up with more power around variable interpolation if needed.

**Comment by pritidesai** [comment]
@popcor255 do you have any particular use case or story you would like to be supported with this feature request?

**Comment by popcor255** [comment]
@pritidesai Yes, as a user I would like to log my pipelines with something with logDNA/ELK. However, [this](https://github.com/tektoncd/pipeline/issues/1016#issuecomment-542388985) work around looks like I should be able to get the name of the pipelinerun I am under. This should let me kubctl against the params. :smile:

**Comment by sbwsg** [comment]
not sure if this has been discussed elsewhere but the pipeline run's name is also available as a context variable in Pipelines which you can then pass to Tasks as a param. see the using_context_variables example: https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/using_context_variables.yaml#L30-L34

**Comment by pritidesai** [comment]
I am narrowing down the scope here:

## Goal

Access to execution status of other `taskRuns` within the same `Pipeline`.

## Proposal

Introduce execution status as a context variable (thanks @sbwsg for pointing out about context variables) in the form of `$(context.pipelineRun.Tasks.<pipelineTaskName>)"`. This variable can have one of the following values:

1. Started: taskRun for that pipelineTask has just started
2. Running: taskRun for that pipelineTask is running
3. Succeeded: taskRun for that pipelineTask completed successfully
4. Failed: taskRun for that pipelineTask completed with a failure
5. TaskRunCancelled: taskRun for that pipelineTask is cancelled by the user
6. TaskRunTimeout: taskRun for that pipelineTask has timed out
7. Unknown: no information available on that pipelineTask execution

## Usage  

```
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: test-pipelinerun-
spec:
  serviceAccountName: 'default'
  pipelineSpec:
    tasks:
    - name: task1
      params:
      taskSpec:
        steps:
        - image: ubuntu
          name: hello
          script: |
            echo "Hello World!"
    - name: task2
      runAfter: [ "task1" ]
      params:
        - name: pipelineRun-pipelineTask-task1
          value: "$(context.pipelineRun.Tasks.task1)"
      taskSpec:
        params:
          - name: pipelineRun-pipelineTask-task1
        steps:
          - image: ubuntu
            name: print-task1-execution-status-and-fail
            script: |
              echo "Pipeline Task Status Task1: $(params.pipelineRun-pipelineTask-task1)"
              exit 1
    - name: task3
      runAfter: [ "task2" ]
      params:
        - name: pipelineRun-pipelineTask-task1
          value: "$(context.pipelineRun.Tasks.task1)"
      taskSpec:
        params:
          - name: pipelineRun-pipelineTask-task1
        steps:
          - image: ubuntu
            name: print-task1-execution-status
            script: |
              echo "Pipeline Task Status Task1: $(params.pipelineRun-pipelineTask-task1)"
    finally:
    - name: task4
      params:
        - name: pipelineRun-pipelineTask-task2
          value: "$(context.pipelineRun.Tasks.task2)"
      taskSpec:
        params:
          - name: pipelineRun-pipelineTask-task2
        steps:
          - image: ubuntu
            name: print-failed-task-status
            script: |
              echo "Pipeline Task Status: Task2:  $(params.pipelineRun-pipelineTask-task2)"
```

Will add more details but before that, wanted to get feedback if this proposal is heading in right direction and would solve the use case we have today.

**Comment by jrcast** [comment]
@pritidesai what do you think about adding a status field for the pipelinerun itself? That way we can easily check for the pipelinerun state as part of a _generic_ `finally` task which we can reuse across pipelines regardless of which tasks we reference. Maybe you can follow the "True", "False", "Unknown" approach as seen [here](https://tekton.dev/docs/pipelines/pipelineruns/#monitoring-execution-status) or spell out the `Reason` or both 🤷 

Imagine, something like: 
```yaml
    finally:
    - name: notify-results
      params:
        - name: pipelineRunStatus
          value: "$(context.pipelineRun.status)"  
        - name: pipelineRunStatusReason
          value: "$(context.pipelineRun.reason)" 
      taskSpec:
        params:
          - name: pipelineRunStatus
        steps:
          - image: ubuntu
            name: notify-status
            script: |
              if [ $(params.pipelineRunStatus) == "True" ]
              then
                echo "PipelineRun was successful. Status was marked as  $(params.pipelineRunStatusReason)"
              else
                echo "PipelineRun Failed. Status was marked as  $(params.pipelineRunStatusReason)"
              fi
```
