### ISSUE TITLE
Conditionals: Support chaining conditions 

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#1022]
# Expected Behavior
Users should be able to specify multiple conditions to gate a task and chain them using a type: "AND", "OR"
Part of implementation for #27 
# Additional Info
Strawperson of the potential API: https://gist.github.com/dibyom/557c9abc50f607e3e0cf5a8125adcb62 based on https://docs.google.com/a/google.com/document/d/1iTb0rDDlgQcPbiYIGJ-atkaML8aCyPCyhfucCPJmNLs/edit?disco=AAAADFnE658 

ref: https://github.com/tektoncd/pipeline/issues/1137

**Comment by vincent-pli** [comment]
@dibyom 
Do we plan to support nested conditions:
```
conditions:
  - type: AND
    checks:
      - type: OR
        checks: 
          - conditinRef: foo
          - conditinRef: foo_1
      - conditionRef: stringsEqual
        params: 
          - name: expected
            value: master
          - name: actual
            value: ${input.workspace.revision}

      - conditionRef: stringsEqual
        params:
          - name: expected
            value: foo
          - name: actual
value: ${input.workspace.somethingElse}
```
If yes, I think it's will be a big topic 😄
