### ISSUE TITLE
Conditionals:  Configure what happens when a task is skipped due to condition failure

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#1023]
# Expected Behavior
Users can decide to either run or skip tasks that are dependent on the task that was skipped due to a condition check failure.

# Actual Behavior
Tasks that are dependent on a skipped task are always skipped

# Steps to Reproduce the Problem

1. Create a pipeline like similar to this:
```
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: two-tasks-one-condition
spec:
  tasks:
  - name: conditional-task
    taskRef:
      name: task1
    conditions:
      - conditionRef: always-fail
  - name: run-if-1-or-1-skipped
    taskRef:
      name: task2
    runAfter:
      - conditional-task
```
2. Run the pipeline through a PipelineRun
3. task2 is not executed

# Additional Info
1. Might be worth enumerating the use cases for this feature before implementing this.
2. Based on discussion from #27: https://docs.google.com/a/google.com/document/d/1iTb0rDDlgQcPbiYIGJ-atkaML8aCyPCyhfucCPJmNLs/edit?disco=AAAADD1TnxU

**Comment by dibyom** [comment]
ref: https://github.com/tektoncd/pipeline/issues/1137

**Comment by bobcatfish** [comment]
One thought after looking at #1137 : 

- If a Task is getting a resource `from` a Task that has a failing condition, I'm not sure it makes any sense to run that dependent Task: e.g. if a Task is building an image as an output, and another task wants to get the built image (digest) `from` that Task, it wouldn't make sense to run it anyway
- `runAfter` is fuzzier - if it's just a matter of ordering, it feels like the user could potentially choose whether the tasks "after" should be skipped or not

**Comment by dibyom** [comment]
From @afrittoli in #1264:

> In the example pipeline I used runAfter but I believe the behaviour would be the same if the dependency was introduced using from on a resource.

**Comment by afrittoli** [comment]
> If a Task is getting a resource `from` a Task that has a failing condition, I'm not sure it makes any sense to run that dependent Task: e.g. if a Task is building an image as an output, and another task wants to get the built image (digest) `from` that Task, it wouldn't make sense to run it anyway

I'm not sure we have a good solution for this case specifically. I've been trying to build a pipeline that builds a docker image only if needed - which I encoded in a condition. The build task has the condition attached and the next Task deploys a cloud function that uses that image plus some code on top.
As long as I don't rely on the image digest, and I use a tag e.g. "latest", the second task can run 
even if the first one did not.

**Comment by dibyom** [comment]
The proposal in #1684 has a solution to this using the `runOn` syntax. So, if a task's condition failed its state is "skip":

```
# 1. change execution graph i.e. onSuccess do something onFailure do something else: 
- name: task1
  conditions:
    conditionRef: "condition-that-sometime-fails"
  taskRef: { name: "my-task" }

- name: runIfTask1Fails 
  runAfter: task1
  runOn: ["failure"]

- name: runIfTask1Succeeds
  runAfter: task1
  runOn: ["success"]

- name: runIfTask1IsSkipped
  runAfter: task1
  runOn: ["skip"]
```

**Comment by afrittoli** [comment]
https://github.com/tektoncd/pipeline/pull/2094#discussion_r392661699

**Comment by afrittoli** [comment]
What happens though in this use case? Is `runIfTask2IsSkipped` executed when `task1` is skipped because its condition fails?

```
- name: task1
  conditions:
    conditionRef: "condition-that-sometime-fails"
  taskRef: { name: "my-task" }

- name: runIfTask1IsSkipped
  runAfter: task1
  runOn: ["skip"]

- name: task2
  runAfter: task1
  conditions:
    conditionRef: "condition-that-sometime-fails"
  taskRef: { name: "my-task2" }

- name: runIfTask2IsSkipped
  runAfter: task2
  runOn: ["skip"]
```

What I want to say is that a runOn: ["skip"] would cover more cases than an `else` logic, so we still would need a way to specify that we only want the `else` in some cases.
