### ISSUE TITLE
Simple helloworld pipeline fails with: can't open 'echo': No such file or directory

### ISSUE THREAD

**Issue by howardjohn** [tektoncd/pipeline#1035]
I created this config:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-task
spec:
  inputs:
  steps:
    - name: alpine
      image: alpine
      args: ["echo", "hello world"]
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: echo
      taskRef:
        name: echo-task
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: test-run
spec:
  pipelineRef:
    name: pipeline
```

And it fails.

```
Name:         test-run-echo-9rl89
Namespace:    tektn
Labels:       tekton.dev/pipeline=pipeline
              tekton.dev/pipelineRun=test-run
              tekton.dev/task=echo-task
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"tekton.dev/v1alpha1","kind":"Task","metadata":{"annotations":{},"name":"echo-task","namespace":"tektn"},"spec":{"inputs":nu...
API Version:  tekton.dev/v1alpha1
Kind:         TaskRun
Metadata:
  Creation Timestamp:  2019-07-02T00:00:22Z
  Generation:          1
  Owner References:
    API Version:           tekton.dev/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  PipelineRun
    Name:                  test-run
    UID:                   62d19976-9c5c-11e9-adc3-42010a800048
  Resource Version:        3833178
  Self Link:               /apis/tekton.dev/v1alpha1/namespaces/tektn/taskruns/test-run-echo-9rl89
  UID:                     62d6c332-9c5c-11e9-adc3-42010a800048
Spec:
  Inputs:
  Outputs:
  Task Ref:
    Kind:  Task
    Name:  echo-task
Status:
  Completion Time:  2019-07-02T00:00:26Z
  Conditions:
    Last Transition Time:  2019-07-02T00:00:26Z
    Message:               "build-step-alpine" exited with code 2 (image: "docker-pullable://alpine@sha256:97a042bf09f1bf78c8cf3dcebef94614f2b95fa2f988a5c07314031bc2570c7a"); for logs run: kubectl -n tektn logs test-run-echo-9rl89-pod-64b616 -c build-step-alpine
    Status:                False
    Type:                  Succeeded
  Pod Name:                test-run-echo-9rl89-pod-64b616
  Start Time:              2019-07-02T00:00:22Z
  Steps:
    Name:  alpine
    Terminated:
      Container ID:  docker://0322fc30c0a493727dc110e1ac2fb073e78b7cade8d73b10ef2bc469b5e68e34
      Exit Code:     2
      Finished At:   2019-07-02T00:00:25Z
      Reason:        Error
      Started At:    2019-07-02T00:00:25Z
    Name:            nop
    Terminated:
      Container ID:  docker://2da80b9c2cba2d28fc1384f055556d0ae5d5c6a760f1cb1eef5097afabf8c753
      Exit Code:     0
      Finished At:   2019-07-02T00:00:25Z
      Reason:        Completed
      Started At:    2019-07-02T00:00:25Z
Events:
  Type     Reason  Age    From                Message
  ----     ------  ----   ----                -------
  Warning  Failed  2m19s  taskrun-controller  "build-step-alpine" exited with code 2 (image: "docker-pullable://alpine@sha256:97a042bf09f1bf78c8cf3dcebef94614f2b95fa2f988a5c07314031bc2570c7a"); for logs run: kubectl -n tektn logs test-run-echo-9rl89-pod-64b616 -c build-step-alpine
```

Pod logs shows
```
/bin/sh: can't open 'echo': No such file or directory
```

As a sanity check:
```
$ docker run alpine echo hello world
hello world
$ docker run alpine sh -c "echo hello world"
hello world
```

It seems tekton is messing with the images in some way that maybe mangles the PATH?

**Comment by howardjohn** [comment]
Changing the image to ubuntu gives me `/bin/echo: cannot execute binary file` instead.

**Comment by howardjohn** [comment]
I did not RTD,
```yaml
    - name: alpine
      image: debian
      command:
      - echo
      args:
      - "hello world"
```
works.

The tests were actually running `/bin/sh echo hello world` not `/bin/sh -c echo hello world` like I thought.

This is already documented at https://github.com/tektoncd/pipeline/blob/master/docs/container-contract.md so I don't think any action needed
