### ISSUE TITLE
Buildah push step is failing due to unauthorized

### ISSUE THREAD

**Issue by cmoulliard** [tektoncd/pipeline#1052]
## Issue

Version : tekton v0.3.1
Cluster: ocp 3.11

### Description

A buildah login against the internal docker registry running within the `default` namespace is working fine using the following task

```
    - name: login
      env:
        - name: REGISTRY_AUTH_FILE
          value: /home/builder/.docker/config.json
      args:
        - login
        - --tls-verify=${inputs.params.verifyTLS}
        - docker-registry.default.svc:5000
      command:
        - buildah
      image: quay.io/buildah/stable
      #image: quay.io/openshift-pipeline/buildah
      securityContext:
        privileged: true
```

Result:
```

Authenticating with existing credentials...
--
  | Existing credentials are valid. Already logged in to docker-registry.default.svc:5000
```

but not when we try with the next taks to perform a `buildah push`

```
    - name: push
      env:
      - name: REGISTRY_AUTH_FILE
        value: /home/builder/.docker/config.json
      args:
        - push
        - --tls-verify=${inputs.params.verifyTLS}
        - docker://${outputs.resources.image.url}
      command:
        - buildah
      image: quay.io/buildah/stable
      #image: quay.io/openshift-pipeline/buildah
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: libcontainers
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
```

Result
```
unauthorized: authentication required
```

### How to reproduce

```
export NS=test
oc new-project $NS
oc adm policy add-scc-to-user privileged system:serviceaccount:$NS:build-bot
oc adm policy add-role-to-user edit system:serviceaccount:$NS:build-bot

oc apply -n $NS -f https://raw.githubusercontent.com/snowdrop/component-operator/master/demo/scripts/tekton/buildah/sa.yml
oc apply -n $NS -f https://raw.githubusercontent.com/snowdrop/component-operator/master/demo/scripts/tekton/buildah/task.yml
oc apply -n $NS -f https://raw.githubusercontent.com/snowdrop/component-operator/master/demo/scripts/tekton/buildah/taskrun.yml
```

**Remark**: Even if the imagestream is created before to push using buildah, we still get an authentication failure

```
cat <<EOF | kubectl apply -n ${NS} -f -
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: dummy-test
spec:
  lookupPolicy:
EOF
```
