### ISSUE TITLE
Privilege escalation: unable to run docker commands in a task.

### ISSUE THREAD

**Issue by lafh** [tektoncd/pipeline#1065]
I need outputs(logs) of running an image and save them to `/workspace/` later. Regardless of safety, how can I run a docker command in a task?

For example, running the following task will result in `docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.`

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run-image
spec:
  inputs:
    resources:
      - name: image-source
        type: image
  steps:
    - name: run-docker-image
      image: gcr.io/cloud-builders/docker
      command: ["docker"]
      args: ["run", "hello-world"]
```

This is a typical error message if you don't have the permission. I usually solve this by `sudo` if it's on a local machine (i.e. `sudo docker run ...`)

Is there a way to achieve privilege escalation to run docker or is there a similar tool to run images inside a task? (`kaniko` is for build only afaik) 

Thanks in advance!
