### ISSUE TITLE
SIGSEGV in Reconciler

### ISSUE THREAD

**Issue by abergmeier** [tektoncd/pipeline#1075]
# Expected Behavior
Should run fine

# Actual Behavior
Leads to a _segmentation violation_.

# Steps to Reproduce the Problem

1. Created `TaskRun` on OpenShift 3.11
```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: git-mirror-run
spec:
  serviceAccount: git-mirror
  taskRef:
    name: git-mirror-task
  inputs:
    params:
      - name: srcRepo
        value: ssh://git@bitbucket.foo.bar/foo/bar.git
      - name: destRepo
        value: git@github.com:foo/bar_common.git
```

# Additional Info
Logs print:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x134621b]

goroutine 204 [running]:
github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun.(*Reconciler).checkTimeout(0xc0004956c0, 0xc00037a280, 0xc000940c30, 0xc0009012f8, 0xc00090f820, 0x0, 0x69e489)
	/workspace/go/src/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun/taskrun.go:536 +0x9b
github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun.(*Reconciler).reconcile(0xc0004956c0, 0x19aa620, 0xc0007f1d10, 0xc00037a280, 0xed4be7aee, 0x27a75a0)
	/workspace/go/src/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun/taskrun.go:264 +0x3fd
github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun.(*Reconciler).Reconcile(0xc0004956c0, 0x19aa620, 0xc0007f1d10, 0xc000bdc780, 0x1f, 0xc00097e8a8, 0x19aa620)
	/workspace/go/src/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun/taskrun.go:171 +0x58b
github.com/tektoncd/pipeline/vendor/github.com/knative/pkg/controller.(*Impl).processNextWorkItem(0xc00059d200, 0x175be00)
	/workspace/go/src/github.com/tektoncd/pipeline/vendor/github.com/knative/pkg/controller/controller.go:330 +0x514
github.com/tektoncd/pipeline/vendor/github.com/knative/pkg/controller.(*Impl).Run.func1(0xc00089c7f4, 0xc00059d200)
	/workspace/go/src/github.com/tektoncd/pipeline/vendor/github.com/knative/pkg/controller/controller.go:282 +0x51
created by github.com/tektoncd/pipeline/vendor/github.com/knative/pkg/controller.(*Impl).Run
	/workspace/go/src/github.com/tektoncd/pipeline/vendor/github.com/knative/pkg/controller/controller.go:280 +0x1a5
```
