### ISSUE TITLE
Is there a way to authenticate with an image resource's registry?

### ISSUE THREAD

**Issue by lance** [tektoncd/pipeline#1106]
# Expected Behavior
I am attempting to use an image as an input resource, and it actually seems as though it might work, however I am running into problems due to the fact that the registry requires authentication.

My use case is that I have another process outside of the Tekton pipeline purview which creates an image and pushes it to a registry. My `Task` then needs to access this image from the registry and copy some data from the running container to a volume mount.

Here is a simple example showing just the input.

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-webapp
spec:
  inputs:
    resources:
      - name: source-image
        type: image
    params:
      - name: SOURCE_PATH
        description: The location of the build output
        default: build
  steps:
    - name: copy-source
      image: ${inputs.resources.source-image.url}
      workingdir: /opt/app-root/source
      command: ['cp', '-Rp', '${inputs.params.SOURCE_PATH}', '/gen-source/']
      volumeMounts:
        - name: gen-source
          mountPath: /gen-source
      securityContext:
        privileged: true
```

I would like a way to specify authentication credentials for the pipeline when accessing the `source-image` in this example. Is this possible? 

# Actual Behavior

When running a `Task` for this I get an error message on the `deploy-webapp-task-run` container.

> ```Failed to pull image "example-webapp": rpc error: code = Unknown desc = Error reading manifest latest in docker.io/library/example-webapp: errors: denied: requested access to the resource is denied unauthorized: authentication required```

# Steps to Reproduce the Problem

1. Apply the above `Task` to a cluster
2. Create a `TaskRun` that specifies a `source-image` on a registry requiring authentication
3. Apply the `TaskRun` to a cluster

# Additional Info

While looking for a way to achieve this, I stumbled on this issue https://github.com/tektoncd/pipeline/issues/260 which is related. Given that I am getting authentication errors when the `TaskRun` executes, I think maybe that issue is resolved, but it is not clear since I have never made it past the authentication requirement.

**Comment by vdemeester** [comment]
hey @lance 

Did you try with what's described in `auth.md`](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md) : [here](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#basic-authentication-docker) and [here](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#kubernetess-docker-registrys-secret) (preferred imho).

**Comment by lance** [comment]
@vdemeester so I have been trying to get this to work for a while now, but am still not successful. Let me provide a little more detail and perhaps you can tell me if I'm trying to do something that's just not possible yet.

A process external to pipelines ([nodeshift](https://github.com/nodeshift/nodeshift)) generates an `ImageStream` using `s2i`, resulting in an image in the internal repository at `image-registry.openshift-image-registry.svc:5000/example-webapp`. I would like to use a `TaskRun` which uses this image as input. My `TaskRun` looks like this.

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: deploy-webapp-taskrun
spec:
  # Use service account with git and image repo credentials
  serviceAccount: pipeline
  taskRef:
    name: deploy-webapp
  inputs:
    resources:
      - name: source-image
        resourceSpec:
          type: image
          params:
            - name: url
              value: https://image-registry.openshift-image-registry.svc:5000/example-webapp
  outputs:
    resources:
      - name: runtime-image
        resourceSpec:
          type: image
          params:
            - name: url
              value: quay.io/lanceball/example-webapp-runtime
```
The `pipelines` service account has been grated the proper roles for accessing the registry per the [documentation](https://docs.openshift.com/container-platform/4.1/registry/accessing-the-registry.html), and I have added the login secret per the instructions [here](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#basic-authentication-docker). Do you think that this is possible and I have just done something wrong? Or am I pushing the boundaries of what pipelines can do at the moment?
