### ISSUE TITLE
No event for PipelineValidationFailed

### ISSUE THREAD

**Issue by Letty5411** [tektoncd/pipeline#1201]
# Expected Behavior
When try to run a pipelinerun, it failed with the following condition:
```
status:
  completionTime: 2019-08-16T06:07:38Z
  conditions:
  - lastTransitionTime: 2019-08-16T06:07:38Z
    message: 'invalid input params: missing values for these params which have no
      default values: [TESTCASE]'
    reason: PipelineValidationFailed
    status: "False"
    type: Succeeded
  startTime: 2019-08-16T06:07:38Z
```
In this situation, I expect that there may be event about this failure.

# Actual Behavior
No event in this situation.

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info
