### ISSUE TITLE
timeout: 0 will fail the pipeline immediately

### ISSUE THREAD

**Issue by lafh** [tektoncd/pipeline#1303]
# Expected Behavior
`timeout: "0"` sets no timeout for PipelineRun or TaskRun.

# Actual Behavior
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipelin-run
spec:
  ...
  timeout: "0"
```
failed immediately on the HEAD release.
