### ISSUE TITLE
ClusterResource validation for CAData

### ISSUE THREAD

**Issue by pradeepitm12** [tektoncd/pipeline#1314]
# Expected:
If the insecure parameter is set as  true ideally it should not force the user to provide CAData

# Actual: 
Creating the `ClusterResource` with `insecure` `true` and CAData as an empty,
returns a validation error saying `missing field(s): CAData param`

# Steps to Reproduce the Problem

Executed following command

```
cat << EOF | kubectl create -f -
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: test-cluster
spec:
  type: cluster
  params:
    - name: name
      value: some-cluster
    - name: url
      value: https://10.10.10.10 # url to the cluster master node
    - name: username
      value: ad
    - name: insecure
      value: 'true'
    - name: token
      value: ZXlKaGJHY2lPaU
EOF
```
