### ISSUE TITLE
Cancelled TaskRun and PipelineRun Steps keep an invalid status

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/pipeline#1368]
Came across some slight inconsistency in cancelled resources. The steps in a PipelineRun or TaskRun which has been cancelled keep their status' and reason messages. 

# Expected Behavior

Steps should reflect their state. 
`running` and cancelled -> `cancelled` 
`terminated` and cancelled -> `terminated` (which is the case)
`waiting` and cancelled -> `not run` (or cancelled ?) 

# Actual Behavior

These step states do not get updated on cancel.

# Steps to Reproduce the Problem

1. Run a pipelineRun
2. Cancel
3. See the status of the steps in the pipelineRun and taskRun Resources

# Additional Info

Relevant piece of a cancelled taskRun which was a part of a cancelled pipelineRun
```
spec:
  inputs: {}
  outputs: {}
  podTemplate: {}
  serviceAccount: default
  status: TaskRunCancelled
  taskRef:
    kind: Task
    name: task7
  timeout: 1h0m0s
status:
  conditions:
  - lastTransitionTime: "2019-09-30T16:31:02Z"
    message: TaskRun "gone-runnin-999-cancel-me2-task7-lgbtf" was cancelled
    reason: TaskRunCancelled
    status: "False"
    type: Succeeded
  podName: gone-runnin-999-cancel-me2-task7-lgbtf-pod-5db557
  startTime: "2019-09-30T16:30:24Z"
  steps:
  - container: step-task7step1
    name: task7step1
    waiting:
      reason: PodInitializing
  - container: step-task7step2
    name: task7step2
    waiting:
      reason: PodInitializing
  - container: step-task7step3
    name: task7step3
    waiting:
      reason: PodInitializing
  - container: step-task7step4
    name: task7step4
    waiting:
      reason: PodInitializing
  - container: step-task7step5
    name: task7step5
    waiting:
      reason: PodInitializing
```

The same from the pipelineRun

```
status:
  completionTime: "2019-09-30T16:31:02Z"
  conditions:
  - lastTransitionTime: "2019-09-30T16:31:01Z"
    message: PipelineRun "gone-runnin-999-cancel-me2" was cancelled
    reason: PipelineRunCancelled
    status: "False"
    type: Succeeded
  startTime: "2019-09-30T16:30:23Z"
  taskRuns:
    gone-runnin-999-cancel-me2-task1-2wwgs:
      pipelineTaskName: task1
      status:
        conditions:
        - lastTransitionTime: "2019-09-30T16:31:01Z"
          message: TaskRun "gone-runnin-999-cancel-me2-task1-2wwgs" was cancelled
          reason: TaskRunCancelled
          status: "False"
          type: Succeeded
        podName: gone-runnin-999-cancel-me2-task1-2wwgs-pod-3e124f
        startTime: "2019-09-30T16:30:24Z"
        steps:
        - container: step-task-one-step-one
          imageID: docker-pullable://ubuntu@sha256:b88f8848e9a1a4e4558ba7cfc4acc5879e1d0e7ac06401409062ad2627e6fb58
          name: task-one-step-one
          running:
            startedAt: "2019-09-30T16:30:41Z"
        - container: step-task-one-step-two
          imageID: docker-pullable://ubuntu@sha256:b88f8848e9a1a4e4558ba7cfc4acc5879e1d0e7ac06401409062ad2627e6fb58
          name: task-one-step-two
          running:
            startedAt: "2019-09-30T16:30:53Z"
```

It is possible to work out what has completed or will not run of course so this might be expected, if so feel free to close. If not I'd be happy to take this on.
