### ISSUE TITLE
`release.yaml` needs to be updated

### ISSUE THREAD

**Issue by XiaohanLiang** [tektoncd/pipeline#1373]
# Expected Behavior
I was following the tutorial, just found a small issue. [Here](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#accessing-local-path-to-resource) it says `path` is an pre-defined variable. It is expected to return the location of my git-repository

```
$(inputs.resources.repo.path)

# Expected to return repo location, e.g /workspace/my-repo
```

# Actual Behavior
However when I try to reference to it I got:
``` yaml
# my code
  steps:
    - name: hello
      image: golang
      command: [echo]
      args:
        - $(inputs.resources.repo.path)

# actual behavior
> $(inputs.resources.repo.path)
```

# Steps to Reproduce the Problem

Then I found the problem was already fixed in #626 in June/2019. By reviewing the `release.yaml` in [installation guide](https://github.com/tektoncd/pipeline/blob/master/docs/install.md#installing-tekton-pipelines-1). Components defined in this file correspond to v0.2.0, which this problem is not yet been fixed. 

This problem was fixed by changing image versions from `0.2.0` to `latest` :)
```
# From
 gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter@sha256:8f8aee782bb47d7436c40e5b10a19966b21d00e1d35d2f3cd8713e206ce24841
# To
 gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:latest
```

# Additional Info
