### ISSUE TITLE
unknown field "trigger"

### ISSUE THREAD

**Issue by gireeshpunathil** [tektoncd/pipeline#1380]
# Expected Behavior

Pipeline run `pipeline.tekton.dev/l-txt-pipeline-run` created

# Actual Behavior

Error from server (InternalError): error when creating "l.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "trigger"

# Steps to Reproduce the Problem

```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: l-txt-pipeline-run
spec:
  serviceAccount: core
  timeout: 1h0m0s
  pipelineRef:
    name: l-txt-pipeline
  trigger:
    type: manual
  resources:
  - name: input
    resourceref:
      name: input
```

apply this on an Openshift 4.1 cluster.

# Additional Info

Openshift version: 4.1

kubernets version:
```
{Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+8560dd6", GitCommit:"8560dd6", GitTreeState:"clean", BuildDate:"2019-07-31T21:30:54Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
```

thanks!
