### ISSUE TITLE
Several git resources for task

### ISSUE THREAD

**Issue by chrono2002** [tektoncd/pipeline#1386]
Add support for several git resources as input for task. E.g.:

  inputs:
    resources:
      - name: source1
        resourceRef:
          name: git-source-1
      - name: source2
        resourceRef:
          name: git-source-2

Tekton fetches everything into single dir (the second one overwrite same files from the first one) and then pack into image.

**Comment by vdemeester** [comment]
/kind bug

@chrono2002 which version of Tekton pipeline are you running ? By design, it should clone the repository in two separate folder under `/workspace`, so this definitely feels like a bug..

**Comment by dlorenc** [comment]
I'm not able to repro this. Could you share a Task definition that shows this happening?

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: git-resource-tag-
spec:
  taskSpec:
    inputs:
      resources:
      - name: repo1
        type: git
      - name: repo2
        type: git
    steps:
    - name: read
      image: ubuntu
      command: ['ls', '/workspace']
  inputs:
    resources:
    - name: repo1
      resourceSpec:
        type: git
        params:
          - name: url
            value: https://github.com/GoogleContainerTools/skaffold
    - name: repo2
      resourceSpec:
        type: git
        params:
          - name: url
            value: https://github.com/GoogleContainerTools/kaniko
```

and the output:

```shell
repo1
repo2
```
