### ISSUE TITLE
Add description field to Resources in Tasks

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#1389]
# Expected Behavior

It should be easy to tell from looking at a `Task` what the intended usage is of any `PipelineResources` the `Task` requires.

# Actual Behavior

We have description fields for `params` but not for `input` or `output` `PipelineResources`, for exmaple [the kaniko Task from the catalog](https://github.com/tektoncd/catalog/blob/14d38f2041312b0ad17bc079cfa9c0d66895cc7a/kaniko/kaniko.yaml#L14-L21):

```yaml
  inputs:
    params:
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: The build context used by Kaniko.
      default: ./
    resources:
    - name: source
      type: git
  outputs:
    resources:
    - name: image
      type: image
```

# Additional Info

Related issue about creating a tool to display documentation (which would need fields like this): https://github.com/tektoncd/catalog/issues/7
