### ISSUE TITLE
Bucket resource folder initialization

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#1395]
# Expected Behavior
When using the bucket resource I find that sometime I'm going to create a new folder and only write in there. Ideally the the bucket resource could point to the new folder already, to minimize the risk of my Task writing where it should not. To do so however I need an extra bit of automation to run somewhere and create the folder for me.
It would be handy if the bucket resource, when used as an output, could (optionally) create the folder in the bucket for me.

I'm aware that this breaks the model where input resources are only a representation of something that already exists, however this would only be for output resources.

The resulting resource/task would be something like this:
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: mybucket
spec:
  type: storage
  params:
   - name: type
     value: gcs
   - name: location
     value: gs://mybucket/my-test-run-id-folder
   - name: dir
     value: "y"
   - name: create-folders
     value: "y"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: e2e-tests
spec:
  inputs:
  outputs:
    resources:
    - name: results-bucket
      type: storage
  steps:
    - name: run-e2e-tests
      image: gcr.io/tekton-releases/tests/test-runner
      - name: ARTIFACTS
        value: $(outputs.resources.results-bucket.path)
      command:
      - /bin/bash
      args:
      - -ce
      - |
        # Setup
        source $(inputs.resources.plumbing-library.path)/scripts/library.sh
        e2e_failed=0
        (...)
        echo ${e2e_failed} > ${ARTIFACTS}/e2e.result
```
