### ISSUE TITLE
PipelineRun should fail if they don't pass validation.

### ISSUE THREAD

**Issue by chhsia0** [tektoncd/pipeline#1407]
# Expected Behavior

When validation fails for a pipeline run, `kubectl get pipelinerun <name>` should return an error status.

# Actual Behavior

Right now `kubectl get pipelinerun <name>` returns the pipelinerun object with no status.

# Steps to Reproduce the Problem

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: docker-build-ci-r7fkz
spec:
  inputs:
    resources:
    - name: src-git
      type: git
  outputs:
    resources:
    - name: mesosphere-dex-controller-ci
      type: image
  steps:
  - args:
    - --destination=<some_docker_repo>
    - --context=/workspace/src-git/
    env:
    image: chhsiao/kaniko-executor
    name: docker-build
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: ci-958ddda-sqqch
spec:
  resources:
  - name: src-git
    type: git
  - name: ci-image
    type: image
  tasks:
  - name: docker-build (ci)
    resources:
      inputs:
      - name: src-git
        resource: src-git
      outputs:
      - name: ci-image
        resource: ci-image
    taskRef:
      name: docker-build-ci-r7fkz
```
Note that the task name in the pipeline is invalid. When submitting a pipeline run for it, the following error will be triggered:
```
{"level":"error","logger":"controller.pipeline-controller","caller":"pipelinerun/pipelinerun.go:169","msg":"Reconcile error: error creating TaskRun called pr-27-2e98033-ct2gr-docker-buil-n46fv for PipelineTask docker-build (ci) from PipelineRun pr-27-2e98033-ct2gr: TaskRun.tekton.dev \"pr-27-2e98033-ct2gr-docker-build-n46fv\" is invalid: metadata.labels: Invalid value: \"docker-build (ci)\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')","knative.dev/controller":"pipeline-controller","stacktrace":"github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).Reconcile\n\t/home/justin/usr/src/github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:169\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/home/justin/usr/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:330\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).Run.func1\n\t/home/justin/usr/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:282"}
```
Then the pipelinerun will never have any status. This would further cause https://github.com/tektoncd/dashboard/issues/635.
