### ISSUE TITLE
TaskRef: refer to a Task from another namespace

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#1409]
# Expected Behavior

It would be nice to be able to refer a Task from another namespace. Something like the following.

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: standard-go-pipeline
spec:
  params:
  - name: foo
    description: repository to clone
  tasks:
  - name: task-a
    taskRef: 
      name: foo
      from:
        namespace: another-namespace
```

or

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: standard-go-pipeline
spec:
  params:
  - name: foo
    description: repository to clone
  tasks:
  - name: task-a
    taskRef: 
      name: foo
      namespace: another-namespace
```

The security aspect of this should be simple, we let kubernetes RBAC handle this (aka if the user can't access `Task` from the other namespace, then we fail and report an error :angel:

# Actual Behavior

To refer a `Task` in `taskRef`, today you need to have this `Task` in the same namespace.

# Additional Info

Related to https://github.com/tektoncd/pipeline/issues/964 (and https://docs.google.com/document/d/1O8VHZ-7tNuuRjPNjPfdo8bD--WDrkcz-lbtJ3P8Wugs/edit#)

/kind feature

**Comment by dibyom** [comment]
Should we allow this for Pipelines/Conditions as well? Related: we have a feature request for Cluster scoped Conditions and Pipelines: https://github.com/tektoncd/pipeline/issues/1266

**Comment by vdemeester** [comment]
@dibyom right, this is something we need to discuss then. My gut feeling is yes, but maybe this means we don't need `ClusterTask` and other cluster scoped objects then :angel:

**Comment by skaegi** [comment]
One concern I have with this is that at least currently the Tekton Controller is doing the taskref lookup with elevated privilege. This might be a real problem in a multi-tenant environment where we want to prevent lookup of private Tasks that might inadvertently contain secret-ish materials.

**Comment by josephlewis42** [comment]
I'm concerned about the statement in the proposal:

> The security aspect of this should be simple, we let kubernetes RBAC handle this (aka if the user can't access Task from the other namespace, then we fail and report an error :angel:

I don't think it's clear what would happen later on if the permissions changed. If any garbage collection scenarios would be changed with this (I don't believe owner references work across namespaces). Or what it would mean to have an instance of this `TaskRun` by someone who didn't have permission to see the other namespace (should it fail? should it succeed?); if it succeeds is there possibility of privilege escalation? Tasks can also reference things like volumes, service accounts, secrets and config maps. How do you reference those across namespaces ensuring permissions are maintained?

Also, I think there are side-channel attacks that open up if you start referencing things across namespaces. Unless you're very careful about error messages, you could probe for Tasks in other spaces by submitting pipelines and looking at the results.

**Comment by hrishin** [comment]
We need to consider the overlap with `ClusterTask` and we are approaching the beta release soon. If we support both it and `ClusterTask` if goes into beta then do we need to support both in the long term?

Yes as @skaegi mentioned on other hand we need to handle the permission or authorization issue.

**Comment by hrishin** [comment]
> One concern I have with this is that at least currently the Tekton Controller is doing the taskref lookup with elevated privilege. This might be a real problem in a multi-tenant environment where we want to prevent lookup of private Tasks that might inadvertently contain secret-ish materials.

One way to address the permission issue by either placing the authorization checks in the tekton pipeline webhook based on the user's token/`ServiceAccount` provided `PipelineRun/TaskRun` or impersonate the request to resolve the `TaskRef` with `ServiceAccount` mentioned in `PipelineRun(Pipeline)/TaskRun` definition.

**Comment by ahpook** [comment]
FWIW I'm neutral to -1 on this, but our use case (this was echoed by @rakhbari on the WG call) is that we use namespaces as a mechanism for isolation and some security guarantees, so if it were implemented we couldn't use it.

**Comment by bobcatfish** [comment]
Slight preference for design 2:

```yaml
  - name: task-a
    taskRef: 
      name: foo
      namespace: another-namespace
```

Re. service account issues - could we initially assume the controller service account has the permissions it needs, and ask users to add more permissions to that account if needed?
