### ISSUE TITLE
Task Ouputs examples in the docs looks wrong

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/pipeline#1458]
In `docs/tasks.md`, in the examples about Outputs, we can see things like this :

```yaml
resources:
  outputs:
    name: storage-gcs
    type: gcs
....
```

I'm new to tekton and from my understanding it's not the correct syntax.
Shouldn't it be something like this instead ?
```yaml
outputs:
  resources:
    name: storage-gcs
    type: gcs
....
```

Also, i'm trying to use a git repository as input, perform some parckage install in it (composer install for instance) and use the result as output.
My task works well, but the output is empty, any example on the syntax to achieve something like this would be great as it's something pretty common.
