### ISSUE TITLE
Add Hooks into Pipeline Lifecycle

### ISSUE THREAD

**Issue by vtereso** [tektoncd/pipeline#1460]
# Expected Behavior
Tekton `Pipeline`s have hooks into the execution of tasks. This way, an additional system/resource is not needed to monitor the internal status. Put another way, `Task`s do not need to concern themselves with updating an external system about their results.
# Actual Behavior
Currently, there is no way for `Task`s to report their results unless done so explicitly within a step. This makes what should be "composable" units more specified. `PipelineResources` address this in some capacity by allowing steps to be prepended/appended to `Task` (a hook of sorts), but fall short because their execution is a contract that constricts the `Task` and are highly specified, which will not address all use cases. Instead, expose a `before`/`after` or `beforeAll`/`afterAll` field in the `PipelineSpec` (the internals of this tag would be analogous to a step). With this shift of responsibility, the `Pipeline` becomes the more specified unit that can internally resolve the general `Task` lifecycle.

Regarding implementation, the `PipelineRun` could create unique `TaskRun` to resolve this lifecycle or the steps could be injected (as current with `PipelineResources`), where this could be to the benefit of data locality. To summarize and clarify, the `Pipeline` would explicitly define the "injection" behavior and it would be implicit to the `Task`.

As an example, a Pipeline can have a `beforeAll`/`afterAll` hook on multiple `Task` where each of these is a CI/CD step that will have a corresponding status in a pull request. This ties nicely with the recent addition of https://github.com/tektoncd/pipeline/commit/9873614dc14733a00f98f096150b75c6752f200f so that users can simply specify a `Task` that is a script and easily add it to a `Pipeline` definition to improve their CI/CD experience.

**Comment by ImJasonH** [comment]
Can you motivate this a bit more with a concrete example? What workflow is unnecessarily hard to describe today, that this makes better? Maybe include an outline of a Pipeline YAML before + after this change.

**Comment by bobcatfish** [comment]
Couple of related ideas:
* https://github.com/tektoncd/pipeline/issues/1376 <-- taking actions in failure scenarios (finally clause)
* https://github.com/tektoncd/pipeline/issues/49 <-- notifications
* We've also talked about emitting cloudevents throughout execution (cant find an issue about it tho!!) which might be one way to implement this
* PipelineResources can execute before and after steps in a Task (tho not currently in a failure scenario), so in some ways they are a way of hooking into execution

One fear: i dont want us to end up in a scenario like apache we end up with many many different kinds of hooks such as `HOOK_REALLY_FIRST` and `HOOK_REALLY_LAST` 😅

**Comment by vtereso** [comment]
I have something like the following in mind for a possible implementation:
```yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pull-request-pipeline
spec:
  params:
  - name: repositoryUrl
    description: The url of the GitHub repository
  - name: revision
    description: The revision of the repository
  - name: pullRequestUrl
    description: The url of the pull request
  - name: secretName
    description: The secret to be used to authenticate against GitHub
  - name: secretKey
    description: The key with the secret (specified by secretName) that stores the authentication information for GitHub
  beforeAll:
    steps:
    - name: pull-request-set-status
      image: github.com/tektoncd/pipeline/cmd/pullrequest-init
      command: 
      - /ko-app/pullrequest-init
      env:
      - name: GITHUBTOKEN
        valueFrom:
          secretKeyRef:
            name: $(params.secretName)
            key: $(params.secretKey)
      args:
      - -url
      - ${inputs.params.pullRequestUrl}
      - -path
      - /workspace2
      - -mode
      - download
  afterAll:
    steps:
    - name: pull-request-set-status
      image: github.com/tektoncd/pipeline/cmd/pullrequest-init
      command: 
      - /ko-app/pullrequest-init
      env:
      - name: GITHUBTOKEN
        valueFrom:
          secretKeyRef:
            name: $(params.secretName)
            key: $(params.secretKey)
      args:
      - -url
      - ${inputs.params.pullRequestUrl}
      - -path
      - /workspace2
      - -mode
      - upload
  tasks:
  # This task will clone the repository to some volume that will be reused by the next steps
  - name: git-clone-repo
    taskRef:
      name: git-clone
    params:
    - name: repositoryUrl
      value: $(params.repositoryUrl)
    - name: revision
      value: $(params.revision)
  - name: build-repo
    runAfter:
    - git-clone-repo
    taskRef:
      name: go-build-repo
  - name: lint-repo
    runAfter:
    - git-clone-repo
    taskRef:
      name: go-lint-repo
  - name: test-repo
    runAfter:
    - build-repo
    taskRef:
      name: go-test-repo
```
To add an additional "notification" step, you would just have to add another `afterAll` step, where this could be something like a slack notification. While making the above, I recognize that the status and some other meta data will likely have to be fed into these injected steps. Also as mentioned in the community call, we would want to ensure the start of execution for these hooks whether the underlying `TaskRun` failed or not (in the case that the steps are injected rather than being in their own `TaskRun`).

What this does is allows the `Task` to be extremely simplistic, which would make generating pipelines easier. The `go-lint-repo` might look as follows:
```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: go-lint-repo
spec:
  volumes:
  - name: clone-dir
    persistentVolumeClaim:
      claimName: host-path-pvc
  steps:
  - image: golang # contains bash
    script: |
      #!/usr/bin/env bash
      go build /repo
    volumeMounts:
    - mountPath: /repo
      name: clone-dir
```
