### ISSUE TITLE
Question:  A way to pass variables between task steps.

### ISSUE THREAD

**Issue by adjavaherian** [tektoncd/pipeline#1476]
Is there a way set an env variable in one task step and then have the subsequent task step be able to read that in or interpolate it in an arg?  Admittedly, I don't fully understand if env variables are shared between multiple images / steps in the same task.  

What I want to do is have a little script in one task step read a file and set env variables, so that the subsequent task step (kaniko) can get things dynamically from env variables set in the container, rather than passed in as params to the task run eg. I won't know the name of Dockerfile or path to context until I read the file from git source.

Here's my question on SO, which also appears to be the first Tekton tag 🎉 .

Very cool stuff, thanks!

https://stackoverflow.com/questions/58561514/pass-env-vars-from-one-tekton-task-step-to-the-next

rough example of what I want to do.
```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: example-task-name
spec:
  inputs:
    resources:
      - name: workspace
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/workspace/Dockerfile
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: ubuntu-example
      image: ubuntu
      args: "export FOO=bar"
    - image: gcr.io/example-builders/build-example
      command: ["echo $FOO"]
```

**Comment by sbwsg** [comment]
> Is there a way set an env variable in one task step and then have the subsequent task step be able to read that in or interpolate it in an arg?

There isn't a way to export environment variables from one step into another.

A different possible approach would be to use files on disk for a similar purpose. All steps in a Task share a workspace volume. This allows the following:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: example-task-name
spec:
  inputs:
    resources:
      - name: workspace
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/workspace/Dockerfile
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: write-to-workspace
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo "bar" > /workspace/FOO
    - name: read-from-workspace
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        export FOO=$(cat /workspace/FOO)
        echo $FOO
```

(I'm using the `script` field here which won't be released until 0.9 but makes writing shell scripts in steps much clearer).
