### ISSUE TITLE
envFrom not working in Task, but it works in step

### ISSUE THREAD

**Issue by csantanapr** [tektoncd/pipeline#1485]
# Expected Behavior

For `envFrom` to work when defined in `Task` resource for configMap or Secrets.

I would like to define a group of environment variables that are required by multiple steps within the same task.

# Actual Behavior
The `envFrom` gets ignore if defined at the `Task` level, but it works if defined at the `step` level.

# Steps to Reproduce the Problem

Define task that uses `envFrom` using a configMap for example.
The configMap `pactbroker-config` contains the key, value `PACTBROKER_URL=http://example.com`
```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: node-react-task-tmp
spec:
  envFrom:
    - configMapRef:
      name: pactbroker-config
  steps:
    - name: test1
      image: ubuntu
      command: ["/bin/bash"]
      args:
        - -c
        - |
          echo "PACTBROKER_URL=${PACTBROKER_URL}" 
    - name: test2
      image: ubuntu
      command: ["/bin/bash"]
      args:
        - -c
        - |
          echo "PACTBROKER_URL=${PACTBROKER_URL}" 
```
run a task via a pipeline.

# Additional Info
