### ISSUE TITLE
Invalid Kubernetes Service Account prints unhelpful error

### ISSUE THREAD

**Issue by joonlim** [tektoncd/pipeline#1507]
# Expected Behavior

I expect an error like:
`Provided service account 'bad-sa' does not exist. Please follow the steps ... to create a service account.`

# Actual Behavior

The error I see is:
`Error: task Task 0 failed: resource name may not be empty`

# Steps to Reproduce the Problem

1. Create file `echo-hi.yaml` with contents:
```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: echo-hi
spec:
  serviceAccountName: bad-sa  # SA does not exist. I see the same error with the deprecated(?) serviceAccount field
  taskSpec:
    steps:
    - name: echo
      image: ubuntu
      command: ['echo']
      args: ['hi']
```
2.
```
➜  kubectl apply -f echo-hi.yaml   
taskrun.tekton.dev/echo-hi created
```
3.
```
➜  tkn taskrun logs echo-hi --follow
Error: task Task 0 failed: resource name may not be empty
```

If I remove the service account field OR have a valid service account, I see:
```
➜  tkn taskrun logs bad-sa --follow
[echo] hi
```

# Additional Info

I saw a similar issue here: https://github.com/tektoncd/pipeline/issues/1096 that I believe was not resolved.
