### ISSUE TITLE
tekton pipeline git resource should init and update submodules recursively.

### ISSUE THREAD

**Issue by NicolasRouquette** [tektoncd/pipeline#1523]
# Expected Behavior

Suppose we have a git pipeline resource as described in the doc:
https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#git-resource

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: wizzbang-git
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/wizzbangcorp/wizzbang.git
    - name: revision
      value: master
```

Suppose that `https://github.com/wizzbangcorp/wizzbang.git` has `.gitmodules` with one or more git submodules.

When the git resource is cloned, the behavior should be equivalent to this:

```
git init <dir>
cd <dir>
git remote add origin <remote url>
git fetch --depth=1 --recurse-submodules=yes origin <revision>
git submodule init
git submodule update --recursive
```

where `<remote url>` would be `https://github.com/wizzbangcorp/wizzbang.git`

# Actual Behavior

Based on the latest commit of `pkg/git/git.go` here: https://github.com/tektoncd/pipeline/blob/ea94852c3aa046d9c898cd63eabc3440a4bf63b3/pkg/git/git.go#L47

This is equivalent to the following:

```
git init <dir>
cd <dir>
git remote add origin <remote url>
git fetch --depth=1 --recurse-submodules=yes origin <revision>
```

In other words, the submodules have not been initialized nor updated recursively.

# Steps to Reproduce the Problem

1. Execute a pipeline or task run that depends on submodule resources.

# Additional Info
