### ISSUE TITLE
tekton pipeline - parameters are not getting replaced recursively

### ISSUE THREAD

**Issue by maheshwarishikha** [tektoncd/pipeline#1524]
# Expected Behavior
After running pipeline-run, parameters value provided in pipeline-run should substitute parameters in Pipeline, then in task and so on.

# Actual Behavior
No value is being substituted, hence it is failing with message "$(input.params.pathToYamlFile): No such file or directory"

What could be the reason of this? Is there a way that I can check if there is any syntax error in yaml files.
Kindly help.
Thanks.

**Comment by vdemeester** [comment]
Hi @maheshwarishikha, thanks for the issue. Can you share the yamls for your PipelineRun, Pipeline and Tasks ?

**Comment by maheshwarishikha** [comment]
@vdemeester , Thanks for the prompt response.
Files are attached here.

[files.zip](https://github.com/tektoncd/pipeline/files/3808369/files.zip)

**Comment by maheshwarishikha** [comment]
Hi @vdemeester , did you get a chance to look at files...? Please do check ...it is like blocker for me and I have tried many things...but no luck yet. Thanks in advance.

**Comment by vdemeester** [comment]
@maheshwarishikha I took a look. This is by design "so far". You have to pass params explicitely to your Task when referencing it. From your file, you need to update your Pipeline to something like the following.

```
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: create-pipeline
spec:
  resources:
    - name: git-source
      type: git
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: configuration.yaml
    - name: imageUrl
      description: Url of image repository
      default: deploy_target
    - name: imageTag
      description: Tag to apply to the built image
      default: latest
  tasks:
  - name: deploy-application
    taskRef:
      name: deploy-application
    params:
    - name: pathToYamlFile
      value: $(params.pathToYamlFile)
    - name: "imageUrl"
      value: $(params.imageUrl)
    - name: "imageTag"
      value: "$(params.imageTag)
    resources:
      inputs:
        - name: git-source
          resource: git-source
```

The issue #1484 is tracking discussion wether we should automatically pass parameters (and resources) from pipeline to task if the have the same name.
