### ISSUE TITLE
Define timeout or times for Condition

### ISSUE THREAD

**Issue by zhangtbj** [tektoncd/pipeline#1534]
Base on the Condition example:
https://github.com/tektoncd/pipeline/blob/master/examples/pipelineruns/conditional-pipelinerun.yaml#L53

# Expected Behavior
I think there should be a timeout or times for Condition to allow user set Condition timeout

# Actual Behavior
For example, after 5mins, if the `check` is not satisfied, then fail the Condition

# Additional spec example:
```
kind: Condition
metadata:
  name: file-exists
spec:
  params:
    - name: "path"
  resources:
    - name: workspace
      type: git
  check:
    image: alpine
    timeout: 300s
    command: ["/bin/sh"]
    args: ['-c', 'test -f $(resources.workspace.path)/$(params.path)']
```
