### ISSUE TITLE
Buildpacks task doesnt have steps when using pipelinerun

### ISSUE THREAD

**Issue by wei-qiang** [tektoncd/pipeline#1555]
# Expected Behavior
pipeline creates a taskrun of task "buildpacks-v3" with its steps.
![image](https://user-images.githubusercontent.com/18074984/68653434-05aac900-052c-11ea-8cea-aea3556d2120.png)

# Actual Behavior
![image](https://user-images.githubusercontent.com/18074984/68653477-2115d400-052c-11ea-8a62-8b1a66f76927.png)

# Steps to Reproduce the Problem

1.create pipelinerun using task buildpacks-v3 (https://github.com/tektoncd/catalog/blob/master/buildpacks/buildpacks-v3.yaml)

# Additional Info

```
#apiVersion: tekton.dev/v1alpha1
#kind: TaskRun
#metadata:
#  name: hello-springboot-mvn-build
#spec:
#  serviceAccountName: tutorial-service
#  taskRef:
#    name: buildpacks-v3
#  podTemplate:
#    volumes:
#    - name: my-cache
#  inputs:
#    resources:
#      - name: source
#        resourceRef:
#         name: source1
#    params:
#    - name: BUILDER_IMAGE
#      value: heroku/buildpacks
#    - name: USE_CRED_HELPERS
#      value: "false"
#    - name: CACHE
#      value: my-cache
#  outputs:
#    resources:
#      - name: image
#        resourceRef:
#          name: image1
#---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-with-parameters
spec:
   resources:
       - name: source-repo
         type: git
       - name: web-image
         type: image
   tasks:
    - name: build
      taskRef:
        name: buildpacks-v3
      params:
        - name: BUILDER_IMAGE
          value: heroku/buildpacks
        - name: USE_CRED_HELPERS
          value: "false"
      resources:
        inputs:
            - name: source
              resource: source-repo
        outputs:
            - name: image
              resource: web-image
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: my-pipelinerun
spec:
  serviceAccountName: tutorial-service
  pipelineRef:
    name: pipeline-with-parameters
  resources:
    - name: source-repo
      resourceRef:
        name: source1
    - name: web-image
      resourceRef:
        name: image1    
```
