### ISSUE TITLE
custom parameter in resource

### ISSUE THREAD

**Issue by vas-dev-ops** [tektoncd/pipeline#1567]
# Expected Behavior

Adding a custom parameter on a docker resource i would expect to be able to read it in a task where the resource is used.

# Actual Behavior

I can't read it.

# Steps to Reproduce the Problem

1. Create a docker resource with a custom parameter "deployment":

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-image
spec:
  type: image
  params:
    - name: url
      value: issue/pipeline-test
    - name: deployment
      value: dev
```

2. Create a task and access the parameters of the resource:

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: env-test
spec:
  inputs:
    resources:
    - name: builtImage
      type: image
  steps:
  - name: set
    image: node:12-alpine
    command: ["sh"]
    args: ["-c","echo $(inputs.resources.builtImage.url) ; echo '---' ; echo $(inputs.resources.builtImage.deployment) "] 
```

3. run the task with a taskrun:

```
kind: TaskRun
metadata:
  name: env-test-run-resource
spec:
  serviceAccountName: build-bot2
  taskRef:
    name: env-test
  inputs:
    resources:
    - name: builtImage
      resourceRef:
        name: docker-image
```
4. read the output:

`issue/pipeline-test --- sh: inputs.resources.builtImage.deployment: not found`

# Additional Info

**Comment by sbwsg** [comment]
Would adding an input param to the Task be suitable here?

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: env-test
spec:
  inputs:
    params:
    - name: deployment
      type: string
    resources:
    - name: builtImage
      type: image
  steps:
  - name: set
    image: node:12-alpine
    command: ["sh"]
    args: ["-c","echo $(inputs.resources.builtImage.url) ; echo '---' ; echo $(inputs.params.deployment) "]
```

If that's not suitable for your use case could you go in to a little detail about why not? It strikes me as a little counterintuitive that you could bundle additional arbitrary fields in a PipelineResource since the params it expects are specific to the work that it does.
