### ISSUE TITLE
Need a way to specify a timeout for a pipeline task

### ISSUE THREAD

**Issue by NicolasRouquette** [tektoncd/pipeline#1568]
# Actual Behavior

I configured a Tekton trigger event listener + trigger + pipeline for building some complex software that happens to exceeds the global task run timeout configuration.

With `tkn pr describe <pipeline run id>`, I see that several task runs failed with `TaskRunTimeout`.
Since these `TaskRuns` are generated by the tekton trigger event listener, I can't specify a timeout.

# Expected Behavior

Proposal to augment the `Pipeline` syntax such that a `PipelineTask` could specify a timeout.

For example, adapting the [pipeline doc example](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#usage):

```
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-with-parameters
spec:
  params:
    - name: context
      type: string
      description: Path to context
      default: /some/where/or/other
  tasks:
    - name: build-skaffold-web
      taskRef:
        name: build-push
      # Same syntax as TaskRunSpec.timeout: https://golang.org/pkg/time/#ParseDuration
      timeout: 5m
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: "$(params.context)"
```

The proposal is that running this pipeline would pass the `PipelineTask.timeout` as a `TaskRunSpec.timeout`. In the adapted example above, it would mean that the `TaskRun` for `build-skaffold-web` would timeout after 5 minutes regardless of the global default task run timeout configuration setting.

# Steps to Reproduce the Problem

1. A tekton trigger event listener with a trigger for a pipeline that executes a task that exceeds the default task run timeout.

# Additional Info
