### ISSUE TITLE
pipeline support  authentication mutiple username and password in Secret?

### ISSUE THREAD

**Issue by withlin** [tektoncd/pipeline#1585]
## Actual Behavior
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://github.com
    tekton.dev/git-1: https://gitlab.com
    tekton.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
stringData:
  username: <cleartext non-encoded>
  password: <cleartext non-encoded>
```

## Expected Behavior
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://github.com
    tekton.dev/git-1: https://gitlab.com
    tekton.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
stringData:
    git-0：{"username":"", "password": ""}
    git-1：{"username":"", "password": ""}
    docker-0：{"username":"", "password": ""}
```
