### ISSUE TITLE
Script task : Error from server (InternalError): error when applying patch

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/pipeline#1592]
This task is rejected by the admission webhook :
```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: helm-delete
spec:
  inputs:
    resources:
      - name: cluster
        type: cluster
    params:
      - name: release
        type: string
  steps:
    - name: helm
      image: alpine/helm:2.16.1
      workingDir: /workspace/src
      script: |
        #!/usr/bin/env sh
        helm delete --purge $(inputs.params.release) --kubeconfig /workspace/$(inputs.resources.cluster.name)/kubeconfig
```

I receive the following log :
```
Error from server (InternalError): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"tekton.dev/v1alpha1\",\"kind\":\"Task\",\"metadata\":{\"annotations\":{},\"name\":\"helm-delete\",\"namespace\":\"prow\"},\"spec\":{\"inputs\":{\"params\":[{\"name\":\"release\",\"type\":\"string\"}],\"resources\":[{\"name\":\"cluster\",\"type\":\"cluster\"}]},\"steps\":[{\"image\":\"alpine/helm:2.16.1\",\"name\":\"helm\",\"script\":\"#!/usr/bin/env sh\\n\\nhelm delete --purge $(inputs.params.release) --kubeconfig /workspace/$(inputs.resources.cluster.name)/kubeconfig\\n\",\"workingDir\":\"/workspace/src\"}]}}\n"}},"spec":{"steps":[{"image":"alpine/helm:2.16.1","name":"helm","script":"#!/usr/bin/env sh\n\nhelm delete --purge $(inputs.params.release) --kubeconfig /workspace/$(inputs.resources.cluster.name)/kubeconfig\n","workingDir":"/workspace/src"}]}}
to:
Resource: "tekton.dev/v1alpha1, Resource=tasks", GroupVersionKind: "tekton.dev/v1alpha1, Kind=Task"
Name: "helm-delete", Namespace: "prow"
Object: &{map["apiVersion":"tekton.dev/v1alpha1" "kind":"Task" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"tekton.dev/v1alpha1\",\"kind\":\"Task\",\"metadata\":{\"annotations\":{},\"name\":\"helm-delete\",\"namespace\":\"prow\"},\"spec\":{\"inputs\":{\"params\":[{\"name\":\"release\",\"type\":\"string\"}],\"resources\":[{\"name\":\"cluster\",\"type\":\"cluster\"}]},\"steps\":[{\"args\":[\"-c\",\"helm delete --purge $(inputs.params.release) --kubeconfig /workspace/$(inputs.resources.cluster.name)/kubeconfig\"],\"command\":[\"sh\"],\"image\":\"alpine/helm:2.16.1\",\"name\":\"helm\",\"workingDir\":\"/workspace/src\"}]}}\n"] "creationTimestamp":"2019-11-19T14:53:15Z" "generation":'\x02' "name":"helm-delete" "namespace":"prow" "resourceVersion":"4073809" "selfLink":"/apis/tekton.dev/v1alpha1/namespaces/prow/tasks/helm-delete" "uid":"50efd885-0adc-11ea-b46e-06f120679b50"] "spec":map["inputs":map["params":[map["name":"release" "type":"string"]] "resources":[map["name":"cluster" "type":"cluster"]]] "steps":[map["args":["-c" "helm delete --purge $(inputs.params.release) --kubeconfig /workspace/$(inputs.resources.cluster.name)/kubeconfig"] "command":["sh"] "image":"alpine/helm:2.16.1" "name":"helm" "resources":map[] "workingDir":"/workspace/src"]]]]}
for: "/workspace/src/tasks/helm-delete.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "script"
```

Is this a known issue ?
It looks like the script task is not working anymore ?
