### ISSUE TITLE
Question : How manage temp output artifacts ?

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/pipeline#1602]
I would like to create a pipeline with three tasks.

The first task builds a package, the second task generates a configuration.
After that, the third task takes the package and the configuration and deploys the application.

Outputs from tasks 1 & 2 are somewhat temporary as they are to be used by the third task.

I configured my pipeline to work with s3, i would expect outputs from task 1 & 2 to be uploaded to s3 automatically, and downloaded automatically to be used in task 3.

Am i right thinking it should be handled automatically by the pipeline ?
How should i write these tasks ?

Below is an example of resources that compose such a pipeline with comments where i'm locked.

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build
spec:
  inputs:
    resources:
      - name: src
        type: git
  outputs:
    resources:
      - name: package
        type: ??? # what type should i put here ? (git, storage, something else)
  steps:
    - name: npm or whatever...
    - name: zip
      image: alpine
      workingDir: /workspace/src
      command:
        - sh
      args:
        - -c
        - "apk update && apk add zip && zip --symlinks -r -q /workspace/output/package/package.zip ..."
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: config
spec:
  inputs:
    resources:
      - name: src
        type: git
  outputs:
    resources:
      - name: config
        type: ??? # what type should i put here ? (git, storage, something else)
  steps:
    - name: zip
      image: alpine
      workingDir: /workspace/src
      command:
        - sh
      args:
        - -c
        - "apk update && apk add zip && zip --symlinks -r -q /workspace/output/config/config.zip ..."
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy
spec:
  inputs:
    resources:
      - name: package
        type: ??? # what type should i put here ? (git, storage, something else)
      - name: config
        type: ??? # what type should i put here ? (git, storage, something else)
  steps:
     - ...
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pull-install
spec:
  resources:
    - name: src
      type: git
    - name: cluster
      type: cluster
    # should i declare something here for my outputs ?
  tasks:
    - name: build
      taskRef:
        name: build
      resources:
        inputs:
          - name: src
            resource: src
        outputs:
          - name: package
            resource: src # here i put the same resource as input but is it correct ? (it's git type, not really a storage)
    - name: config
      taskRef:
        name: config
      resources:
        inputs:
          - name: src
            resource: src
        outputs:
          - name: config
            resource: src # here i put the same resource as input but is it correct ?(it's git type, not really a storage)
    - name: deploy
      taskRef:
        name: deploy
      resources:
        inputs:
          - name: package
            resource: package
            from:
              - build
          - name: config
            resource: config
            from:
              - config
```
