### ISSUE TITLE
Permission denied when checking out source to /workspace

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#1608]
# Expected Behavior

When checking out a `PipelineResource` with a Git resource checking it out in `/workspace` which run as *user* (as for example by default on OpenShift) the Git repository would probably be checked out in `/workspace/src`.

# Actual Behavior

This would be denied and can't create directory in `/workspace` 

```
mkdir: can't create directory '/workspace/source': Permission denied
```

# Steps to Reproduce the Problem

This is maybe an OpenShift specific issue or a K8s with a hardened policy to force running the pods as random user instead of privileged.

Running this on OpenShift4.2 with a simple Task with a PipelineResource of Git will do, i.e: 

```yaml
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: waitforever-with-src
spec:
  inputs:
    resources:
      - name: source
        type: git
        targetPath: src
  steps:
    - name: waitforever
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      workingdir: /workspace/src
      command: ["sleep", "infinity"]
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/rogertinsley/golang-k8s-helloworld
```

and run it with :

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: waitforever-with-src-run-
spec:
  inputs:
    resources:
    - name: source
      resourceRef:
        name: source
  taskRef:
    kind: Task
    name: waitforever-with-src
```

# Additional Info

Weirdly enough this only appeared *lately* like for the last two weeks or so but can't find anything obvious in the git logs (perhaps that's an OpenShift 4.2 specific bug too).

Debugging a bit into this, this would fail into the `initContainers` that initialize the `/workspace` directories.

The first container which does the `credsInit` run fine and adding some debugs I can see that I have the [sticky bit](https://en.wikipedia.org/wiki/Sticky_bit) set to be able to write into `/workspace` : 

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/98980/69475587-51346100-0dcf-11ea-9ff3-b3c892bc0797.png">

While the second `initContainer` which does the `dir-init` step would fail, adding a `ls -l` just before doing the `mkdir -p` I can see that the the sticky bit has dropped in there and `mkdir` would fail because we are running as user and directory is set as root : 

<img width="723" alt="image" src="https://user-images.githubusercontent.com/98980/69475696-6fe72780-0dd0-11ea-8417-17b8c9451542.png">

/kind bug
