### ISSUE TITLE
Params in multiple Condition of one task will overwrite by the last one 

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#1619]
I have a `Pipeline` defined with multiple `Condition`s in one `Task` like this:
```
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: list-files-pipeline
spec:
  resources:
    - name: source-repo
      type: git
  params:
    - name: path
      default: "README.md"
    - name: test-path
      default: "README.mdxxx"
    - name: image
      default: "alpine"
  tasks:
    - name: list-files-1
      taskRef:
        name: list-files
      conditions:
        - conditionRef: "file-exists"
          params:
            - name: path
              value: "$(params.path)"
            - name: image
              value: "$(params.image)"
          resources:
            - name: workspace
              resource: source-repo
        - conditionRef: "file-exists"
          params:
            - name: path
              value: "$(params.test-path)"
            - name: image
              value: "$(params.image)"
          resources:
            - name: workspace
              resource: source-repo
```
I expect the first condition which check "README.md" will be success and the second one for "README.mdxxx" will failed, but all of them are failed.

I checked the `Taskrun`s generated, found  `inputs.params` is all about "README.mdxxx"
like this:
```
spec:
  inputs:
    params:
    - name: path
      value: README.mdxxx
```

# Expected Behavior
The first `condition` for "README.md" will success,
The second one for "README.mdxxx" will failed
# Actual Behavior
All the two generated `Taskrun` are failed.

# Additional Info
