### ISSUE TITLE
Where to define the PVC type when a task declare to use it?

### ISSUE THREAD

**Issue by zhangtbj** [tektoncd/pipeline#1629]
# Expected Behavior
The public cloud provider may provide many PVC types, such as standard or GLACIER, etc..... but just only one.
I can choose which PVC type I use.

# Actual Behavior
But in the current tekton taskrun config:
```
spec:
  inputs:
    params:
    - name: text
      value: how to ci/cd?
    resources:
    - name: repo
      resourceRef:
        name: repo
  outputs:
    resources:
    - name: repo
      paths:
      - /pvc/pipeline-task-1/repo
```

It only config the `paths`, and it used a storage class type which is not good for me.

Is there any way that I can choose which storage class type I used for the task output?

The wrong storage class makes my task fail because PVC is pending ....

Thanks!

**Comment by vdemeester** [comment]
@zhangtbj thanks for the issue. There is no way as of today, but #1438 might help to tackle that (and later on the new design of PipelineResource should build on top of #1438)

/kind question

**Comment by bobcatfish** [comment]
Hey @zhangtbj - do you mean the PVC that is used for passing data from the output of one task to the input of another? If so [you actually can configure the underlying PVC's storage class](https://github.com/tektoncd/pipeline/blob/master/docs/install.md#how-are-resources-shared-between-tasks) via configmap, you can see an example of what this could look like [in this configmap yaml](https://github.com/tektoncd/pipeline/blob/master/config/config-artifact-pvc.yaml).

**Comment by zhangtbj** [comment]
Hi @bobcatfish ,

Actually, it is not a new requirement. It is because I got two failures when I ran the Tekton integration tests:
TestDAGPipelineRun and TestDAGPipelineRun test:

When I debug the taskrun pod, I found the task fail because the PVC is pending.

And the default PVC which taskrun used on my cloud is full. So that I cannot pass my tests.

And from the taskrun:
```
spec:
  inputs:
    params:
    - name: text
      value: how to ci/cd?
    resources:
    - name: repo
      resourceRef:
        name: repo
  outputs:
    resources:
    - name: repo
      paths:
      - /pvc/pipeline-task-1/repo
```

I didn't found where to configure the PVC (storage type). That is why I opened this issue.

Thanks!
