### ISSUE TITLE
Folders for output resource not created in multiple scenario 

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#1630]
I have a `task` with more than one `output resource`, like this:
```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-push
spec:
  outputs:
    resources:
    - name: builtImage
      type: image
    - name: builtImage1
      type: image
  steps:
  - name: build-and-push
    image: docker
    args: ["touch", "$(outputs.resources.builtImage.path)/README.md"]
  - name: build-and-push-1
    image: docker
    args: ["touch", "$(outputs.resources.builtImage1.path)/README.md"]
```
Base on the document, folders named: `/workspace/output/resource_name/` should be created.

The fact is the `/workspace/output/builtImage` is created and `step: build-and-push` is success but the `step: build-and-push-1` is failed, since `/workspace/output/builtImage1` is not existed, found logs: `touch: /workspace/output/builtImage1/README.md: No such file or directory`
# Expected Behavior
`Taskrun` success
# Actual Behavior
`Taskrun` failed
# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info
