### ISSUE TITLE
"/workspace" in the path of "output resource"

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#1642]
I'm confuse, maybe missing something.
I have a `task` with `output resource` and `targetpath`, like this:
```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-push
spec:
  outputs:
    resources:
    - name: builtImage
      type: image
      targetPath: /pengli/builtImage
  steps:
  - name: build-and-push
    image: docker
    args: ["touch", "$(outputs.resources.builtImage.path)/README.md"]
```
Simple, but get error: `touch: /workspace/pengli/builtImage/README.md: No such file or directory`
I checked the env, actually `/pengli/builtImage/` is created.

I have no idea if it's a mistake, but I think `/workspace/*` should be the correct one,  since `container`s in pod shared file system only with several mount points, `/workspace/*` is one of them. we expect sharing in containers.

# Expected Behavior
`Taskrun` sucess
# Actual Behavior
Failed
# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info
