### ISSUE TITLE
Allow existing persistentvolume in config-artifact-pvc

### ISSUE THREAD

**Issue by jomeier** [tektoncd/pipeline#1645]
Hi,

in my OpenShift setup I don't use a cloud provider, have no default storage class. But I can create PersistentVolumes from manually created Azure File shares.

Is it possible to use an existing PersistentVolume (in my case it hase the name azurefile2) so Tekton creates a shared volume like this:

```
...
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: azurefile2
  volumeMode: Filesystem
```

(you see the ``volumeName`` property?)

Thanks and greetings,

Josef
