### ISSUE TITLE
Refining status when Condition failed

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#1692]
With a one task `pipeline`, and the `task` will not executed since the `condition` will checked failed.
That's means the `pipeline` not execute any `task` after running.
But the `pipelinerun` still express its success and emit event `All Tasks have completed executing`.

I understand the real mean is "all the tasks has been touched" but it mislead people, could we introduce new state to express this, for example: `Succeeded with condition failed` or whatever.

# Expected Behavior
The `state` of `pipelinerun` should express the situation of `condition failed`
# Actual Behavior
Always shows `success`

**Comment by dibyom** [comment]
Yeah, a pipeline with a single conditional task with a condition failure is an interesting edge case. Right now the behavior is by design though like you said, it can be confusing. 
```
  conditions:                                                                                                                               
  - lastTransitionTime: "2019-11-05T19:57:04Z"                                                                                              
    message: All Tasks have completed executing                                                                                             
    reason: Succeeded                                                                                                                       
    status: "True"                                                                                                                          
    type: Succeeded   
```
It  should be simple enough to set the `message` or the `reason` to something like `Successful but with Condition failure` or something like that. Though the type `status` field  for the condition with `type: Succeeded` is still going to be `True`.
