### ISSUE TITLE
Question: How to build custom tekton-releases pipeline yaml?

### ISSUE THREAD

**Issue by adjavaherian** [tektoncd/pipeline#1745]
I'm looking at the docs for custom releases and it seems to be either over my head, or not exactly what I'm interested in doing.  

Currently, we bootstrap our cluster with the release yaml from your latest builds as per quickstart.

`kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml`

This is great, and working well, but I want to customize the namespace to contain a `PodNodSelector` annotation, so that the AdmissionController can ensure that all the `tekton-pipelines` namespaced pods are deployed to a single node pool.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: main-pool
```

see: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector

As far I understand, this needs to happen at namespace creation and before the kubeapi attempts to assign the new tekton-pipelines pods.

That being said, do I use [Custom Releases]  (https://github.com/tektoncd/pipeline/blob/master/docs/install.md#custom-releases) to do that?  Or is that reserved for official releases?

Thanks!
