### ISSUE TITLE
Feature to disable a task in a Pipeline

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#1797]
# Expected Behavior

It would be nice if it was possible to have a way to disable a task in a Pipline, like so:

```
disable: bool
```

to disable a task in a Pipeline be it temporary  or for other reasons.

# Actual Behavior

Sometime while developing some long Pipeline I have to comment some long running tasks, and being able to just disable them would be nicer.

# Additional Info

Maybe that's something that can be achieve with `Conditionals`? But that seems to be more complexity for a simple directive.

**Comment by vdemeester** [comment]
@chmouel Yeah, I think it should be possible with `Conditionals` and a *always false* condition.

/cc @dibyom 
/kind question

**Comment by dibyom** [comment]
Yeah an always false should work. Though there are a couple of gotchas:
1. Tasks that are dependent on that "skipped" task using `runAfter` or `from` are also not run.
2. This could be premature optimization -- but conditionals run in their own pods. Initially we had the idea of some "built-in" conditionals that we can optimize. `always-false` seems to be a good candidate for this.

**Comment by pritidesai** [comment]
> 1. Tasks that are dependent on that "skipped" task using `runAfter` or `from` are also not run.

I think its a valid behavior even in case of disabling a task with `disable: true` (if we add such support). If a task is disabled either by conditions or by explicit disable key, all the dependent tasks should not be executed unless otherwise failure strategies are specified (see #1684)

**Comment by bobcatfish** [comment]
Being able to disable Tasks via the PipelineRun sounds reasonable to me! Like @pritidesai was saying it should cancel the entire branch though, i.e. anything depending on that Task

The downside of using Conditionals for this as far as I can tell is that you'd have to make the changes in the Pipeline definition itself to toggle on and off, I think? I like the idea of doing it at runtime.

**Comment by dibyom** [comment]
If the field is called `disable: bool` it'd have to be in the pipeline task not the pipeline run. 
If we want to do this at the pipelinerun level, we'd probably want a list of tasks to disable.

> The downside of using Conditionals for this as far as I can tell is that you'd have to make the changes in the Pipeline definition itself to toggle on and off, I think? I like the idea of doing it at runtime.

One solution (or workaround rather :grin: ) would be to embed the pipeline spec inside the pipeline run

**Comment by bobcatfish** [comment]
Maybe this would be something we can add into the PipelineRun?

**Comment by pritidesai** [comment]
thanks @jerop for taking this up, happy to help if needed 🥰

**Comment by jerop** [comment]
thanks @pritidesai 😄 

we can collaborate on this a [design doc](https://docs.google.com/document/d/1rleshixafJy4n1CwFlfbAJuZjBL1PQSm3b0Q9s1B_T8/edit?usp=sharing) I just started

**Comment by jerop** [comment]
will be solved using [when expressions](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md#efficiency-1) in conditions beta (ongoing work)

**Comment by pritidesai** [comment]
This is now possible with When Expressions using Pipeline param, set a pipeline param `runMyTask` to `true` and check that variable in the Pipeline Task.

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-to-skip-task
spec:
  params:
    - name: runMyTask
      value: "false"
  pipelineSpec:
    params:
      - name: runMyTask
        default: "true"
    tasks:
      - name: skip-this-task
        when:
          - input: $(params.runMyTask)
            operator: in
            values: ["true"]
        taskSpec:
          steps:
            - name: echo
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "Good Morning!"
      - name: execute-this-task
        taskSpec:
          steps:
            - name: echo
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "Good Night!"
```

**Comment by bobcatfish** [comment]
hey all! i want to reopen this to discuss further down the line: when expressions will allow you to disable particular tasks via a parameter, however to take advantage of this you need to add the when expressions

imo the feature request here is about getting this functionality out of the box; e.g. even without when expressions or conditionals, commenting out tasks in a pipeline is another way to achieve the same goal, the ask here is to have a way to do this at runtime that doesn't require changing the pipeline definition

**Comment by pritidesai** [comment]
have to explore `pipelineRun` to support it, something like @jerop's proposal on a list of disabled/skipped `pipelineTasks`

**Comment by pritidesai** [comment]
another possible way is to introduce `status` in `pipelineRun` CRD which can have a `pipelinetask` name and desired status (skipped), can extend it in future to include other states.

**Comment by bobcatfish** [comment]
The biggest blocker for this one is convincing ourselves the functionality is worth adding - I happen to think it is but some folks don't, which is why we put this on hold. I want to revisit it at some point but understand why folks are reluctant to add it - it might make more sense for post v1 unless we have some strong use cases now (was talking to @coryrc about a potential use case with prow also)

**Comment by vdemeester** [comment]
Naive question, does the following work ?

```
        when:
          - input: false
            operator: in
            values: ["true"]
```

Coupled with the `continueOnSkip` feature, this would be *the* way to skip temporarily a task in a pipeline. It's not a one-liner, but it would exist.

Anyway, I would like to gather samples on uses cases for this :angel:
