### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#1826]
This issue tracks work needed to make Tekton run on a Kubernetes cluster with Windows nodes. Please contribute your use cases, ideas and experience.

First, some assumptions I've been operating under:

1. Tekton controller components themselves don't need to run on Windows nodes. The cluster could have N Linux nodes and M Windows nodes, run the controller on one of the Linux nodes, and run requested workloads on Windows nodes. If we decide full-Windows clusters are the goal, then we'll need to expand this work to cover getting controller components built and running for Windows.
1. The user has to explicitly specify they want a TaskRun to execute on a Windows node, using `nodeSelector` -- Tekton isn't responsible for somehow detecting that a TaskRun should run on a Windows node. We might change how a TaskRun's Pod is generated based on the user's specification, but ideally we wouldn't have to, for simplicity.

If either of these are contentious, or you have more to add, please comment.

Next, some things I'm fairly sure will break without trying:

1. **Building Images**: Entrypoint binary injection is done today by prepending a step containing the entrypoint binary, which copies that binary to `/tekton/entrypoint` -- to support Windows, that binary will have to be built to run on Windows, and will have to be based on some minimal Windows image (i.e., not `distroless` as it is today). This is doable with manifest lists, which `ko` has some support for. Likewise, internal support images used to implement resources (`git-init`, `creds-init`, `google/cloud-sdk`, etc., will need to be able to be built for Windows)

1. **File Paths**: Step ordering works by looking for files to exist at some predetermined path, and those paths are specified using `/`-separated paths (`/tekton/tools`, `/tekton/downward/ready`, etc.) -- this is likewise true for `/workspace`, `/tekton/home`, etc. If we decide in the future to use fsnotify to watch files instead of polling, we'll have to make sure that works for Windows too (or fallback to polling).

1. **Script Mode**: Script mode is implemented today by writing an executable file to `/tekton/scripts/something`, then invoking it as the `Command` in the step container. Writing this file and making it executable, as well as where it exists, will require work to support Windows.

Sources:
* https://cloud.google.com/blog/products/containers-kubernetes/how-to-deploy-a-windows-container-on-google-kubernetes-engine

**Comment by afrittoli** [comment]
@ImJasonH any special reason for this to be on the priority list? I will remove it for now, feel free to bring it back to the API WG if needed

**Comment by lukehb** [comment]
@ImJasonH In the spirit of your "please contribute your use cases, ideas and experience" statement above, I'd like to chime in here. We are building out a CI/CD product on top of Tekton, specifically for building Unreal Engine projects. We are quite close to getting something in the hands of users; however, Windows support is a blocker for adoption of our product so we are highly motivated to see Windows support land in Tekton. I have been following this issue basically since it was opened and was wondering how things are going internally on this front?

If it is a matter of putting in the legwork, we may be able to help by collaborating with the Tekton maintainers to make it happen and get it upstreamed.

**Comment by ImJasonH** [comment]
> If it is a matter of putting in the legwork, we may be able to help by collaborating with the Tekton maintainers to make it happen and get it upstreamed.

Thanks @lukehb that's really helpful. I'm not aware of any active effort to work on this, so your help will be useful. :) 

I think the first step would be figuring out what doesn't work currently. What happens when a TaskRun pod executes on a Windows node? What happens when the controller and webhook components run on a Windows node? I suspect basically nothing will work at first, but having an idea exactly what breaks will help us move forward.

The entrypoint binary we inject into each TaskRun pod is not currently built for Windows, but I believe it could be relatively easily. Same for the controller components. I suspect this will end up being the first work, and likely far from the last. :)

**Comment by lukehb** [comment]
> I'm not aware of any active effort to work on this, so your help will be useful. :)

Okay, in the case we will have some internal discussions about prioritising this on our roadmap. We will likely have a lot of questions to make sure we are on the right track, what is the best place to riff back and forth? The Tekton slack?

**Comment by vdemeester** [comment]
This is slightly related to https://github.com/tektoncd/pipeline/issues/856 although more complicated 😅. Following up on @ImJasonH thougts, we also need to discuss what would be the minimum viable first iteration of supporting windows ; I would guess being able to run `TaskRun` on Windows (with having the controller & co on Linux) would be a good start but we can discuss this.

@lukehb there is different *medium*. For short discussion, slack or the tekton-dev mailing would be appropriate. To start designing the feature and dig into why we want this and detail how we could do this, there is the [`TEP` process](https://github.com/tektoncd/community/tree/master/teps#tekton-enhancement-proposals-teps). An example related to other architectures is [TEP-0019](https://github.com/tektoncd/community/blob/master/teps/0019-other-arch-support.md). We can bootstrap this by having discussion on the [working groups](https://github.com/tektoncd/community/blob/master/working-groups.md) (the [main WG](https://github.com/tektoncd/community/blob/master/working-groups.md#general) or the [API](https://github.com/tektoncd/community/blob/master/working-groups.md#api) one).

**Comment by DrWadsy** [comment]
I work with @lukehb, and we've been discussing our need for Windows support in Tekton for several weeks now. We've prioritised this in our development roadmap, and have put together a draft TEP to get this process started. I'll be posting it on the main WG for feedback before starting the formal TEP process. We would appreciate any and all advice on getting the proposal to a state where we can start working on this issue.

**Comment by lippertmarkus** [comment]
@DrWadsy @lukehb Thanks a lot for your involvement, I'm really excited and looking forward to it!

**Comment by vdemeester** [comment]
/lifecycle frozen
This is something we want at some point, so let's just make sure it does not stale and gets auto-close 😛

**Comment by imjasonh** [comment]
Aside from ko not being able to build runnable Windows containers, there's the problem of what base image would we configure for Tekton-built images that would have support for both Linux and Windows.

For that, I hacked up http://github.com/imjasonh/combine which combines two manifest lists into one, assuming they don't have overlapping platforms. When we get ko working to build for Windows, we can use the result of this tool as a base image that ko can build on top of.

**Comment by aiden-deloryn** [comment]
@imjasonh Do you think it would also be desirable to use manifest lists for Tekton's container images (entrypoint, nop, etc.)?

This would avoid having to add any platform specific logic to the controller, and would be scalable for adding more platforms and architectures in the future. The only potential downside I see is that, as far as I know, you cannot reference a manifest list by digest the way that Tekton currently does.

**Comment by vdemeester** [comment]
> @imjasonh Do you think it would also be desirable to use manifest lists for Tekton's container images (entrypoint, nop, etc.)?

Don't we already do that ? `ko` with multi-platform should already do that (so that it works on amd64, arm64, …)

**Comment by imjasonh** [comment]
> Don't we already do that ? `ko` with multi-platform should already do that (so that it works on amd64, arm64, …)

Yep, we already use manifest lists for multi-architecture images (amd64, arm64, s390x, ppc64le), they just so happen to all have the same OS right now (linux), and there's some work needed to make the entrypoint code work with Windows, and for `ko` to be able to build multi-platform (including multi-OS) images.

**Comment by imjasonh** [comment]
I made more progress on my ko windows branch this morning, and managed to successfully build an image that runs on Linux and Windows 🎉 

Follow https://github.com/google/ko/pull/374 for updates on that front.

**Comment by vdemeester** [comment]
> > Don't we already do that ? `ko` with multi-platform should already do that (so that it works on amd64, arm64, …)
> 
> Yep, we already use manifest lists for multi-architecture images (amd64, arm64, s390x, ppc64le), they just so happen to all have the same OS right now (linux), and there's some work needed to make the entrypoint code work with Windows, and for `ko` to be able to build multi-platform (including multi-OS) images.

Right 👍🏼

**Comment by imjasonh** [comment]
I've built an entrypoint image using ko's WIP Windows support, based on a base image combined from distroless and Windows nanoserver. That image is here:

```
gcr.io/imjasonh/github.com/tektoncd/pipeline/cmd/entrypoint@sha256:5f02d0f56ec08c029c2ae29416a0397dc2c40e4a695c62da2712056955a7a667
```

If anybody has an opportunity to try out this image on Windows that would be helpful for identifying the next blockers.

**Comment by aiden-deloryn** [comment]
@imjasonh Thanks for sharing this. I will do some testing on my Windows node and record any problems I find here.

**Comment by aiden-deloryn** [comment]
I have just tested a simple Windows task which clones https://github.com/google/ko.git and builds it as an executable for Windows. See `windows-task.yaml` below.

<details>
  <summary>windows-task.yaml</summary>

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: windows-task
spec:
  steps:
  - name: clone-repo
    image: aidendeloryn/windows-base-example:latest
    command: ["git"]
    args:
      - "clone"
      - "--depth"
      - "1"
      - "--single-branch"
      - "https://github.com/google/ko.git"
      - "C:\\workspace"
  - name: build-binary
    image: aidendeloryn/windows-base-example:latest
    command: ["go"]
    args:
      - "build"
      - "-a"
      - "-v"
      - "-o"
      - "ko.exe"
      - "main.go"
  - name: print-version
    image: aidendeloryn/windows-base-example:latest
    command: ["ko"]
    args:
      - "version"
  - name: print-help
    image: aidendeloryn/windows-base-example:latest
    command: ["ko"]
    args:
      - "--help"
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: windows-taskrun
spec:
  taskRef:
    name: windows-task
  podTemplate:
    nodeSelector:
      kubernetes.io/os: windows
```
</details>

When I run this the `place-tools` Init Container fails during execution:

```
Init Containers:
  place-tools:
    Container ID:  docker://71ec16a5f25d4a9deccc8dc0e2ceea50c18094a81dc4f1ed556c66b93fdd3330
    Image:         gcr.io/imjasonh/github.com/tektoncd/pipeline/cmd/entrypoint@sha256:5f02d0f56ec08c029c2ae29416a0397dc2c40e4a695c62da2712056955a7a667
    Image ID:      docker-pullable://gcr.io/imjasonh/github.com/tektoncd/pipeline/cmd/entrypoint@sha256:5f02d0f56ec08c029c2ae29416a0397dc2c40e4a695c62da2712056955a7a667
    Port:          <none>
    Host Port:     <none>
    Command:
      /ko-app/entrypoint
      cp
      /ko-app/entrypoint
      /tekton/tools/entrypoint
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 23 Jun 2021 09:48:00 +1000
      Finished:     Wed, 23 Jun 2021 09:48:00 +1000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /tekton/tools from tekton-internal-tools (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ntqrf (ro)
```

Checking the logs for the `place-tools` container reveals the error: 

```
2021/06/23 09:48:00 cp error: open /ko-app/entrypoint: The system cannot find the file specified.
```

When I run the entrypoint container using docker `docker run --rm -ti --entrypoint cmd gcr.io/imjasonh/github.com/tektoncd/pipeline/cmd/entrypoint`, it looks like it could be a permissions problem:
```
C:\>dir
 Volume in drive C has no label.
 Volume Serial Number is 78B6-200B

 Directory of C:\

01/01/1970  10:00 AM    <DIR>          ko-app
05/07/2021  10:37 PM             5,510 License.txt
05/07/2021  10:38 PM    <DIR>          Users
06/23/2021  10:01 AM    <DIR>          Windows
               1 File(s)          5,510 bytes
               3 Dir(s)  21,295,140,864 bytes free

C:\>cd ko-app
Access is denied.

C:\>echo %USERNAME%  
ContainerUser
```

For comparison I ran the same Windows task using an entrypoint I built with https://github.com/tektoncd/pipeline/blob/main/images/windows/entrypoint/Dockerfile which you can find here https://hub.docker.com/repository/docker/aidendeloryn/entrypoint. This one seems to be working so it might be useful for comparison.

```
$ kubectl get pods -o wide
NAME                        READY   STATUS              RESTARTS   AGE   IP            NODE             NOMINATED NODE   READINESS GATES
windows-taskrun-pod-x7547   0/4     Completed           0          28m   10.244.1.37   microk8s-win     <none>           <none>

$ kubectl logs windows-taskrun-pod-x7547 -c step-clone-repo
Cloning into 'C:\workspace'...
Updating files: 100% (2890/2890), done.

$ kubectl logs windows-taskrun-pod-x7547 -c step-print-version
(devel)
```

Checking permissions on the working entrypoint image:

```
C:\>dir
 Volume in drive C has no label.
 Volume Serial Number is D6BF-8A39

 Directory of C:\

06/08/2021  02:46 PM    <DIR>          ko-app
04/09/2021  02:27 AM             5,510 License.txt
04/09/2021  02:27 AM    <DIR>          Users
06/23/2021  10:03 AM    <DIR>          Windows
               1 File(s)          5,510 bytes
               3 Dir(s)  21,295,198,208 bytes free

C:\>cd ko-app

C:\ko-app>echo %USERNAME%  
ContainerUser
```

**Comment by aiden-deloryn** [comment]
Looking inside `C:\ko-app\` as `ContainerAdministrator` I can see the executable names are different (one has `.exe`). This might actually be the issue rather than file permissions...

`docker run --rm -ti --entrypoint cmd --user ContainerAdministrator gcr.io/imjasonh/github.com/tekto
ncd/pipeline/cmd/entrypoint`
```
C:\ko-app>dir  
 Volume in drive C has no label.
 Volume Serial Number is 78B6-200B

 Directory of C:\ko-app

01/01/1970  10:00 AM    <DIR>          .
01/01/1970  10:00 AM    <DIR>          ..
01/01/1970  10:00 AM        26,845,184 entrypoint.exe
               1 File(s)     26,845,184 bytes
               2 Dir(s)  21,295,140,864 bytes free
```

`docker run --rm -ti --entrypoint cmd aidendeloryn/entrypoint:multi-platform`
```
C:\>cd ko-app

C:\ko-app>dir  
 Volume in drive C has no label.
 Volume Serial Number is D6BF-8A39

 Directory of C:\ko-app

06/08/2021  02:46 PM    <DIR>          .
06/08/2021  02:46 PM    <DIR>          ..
06/08/2021  02:46 PM        26,836,992 entrypoint
               1 File(s)     26,836,992 bytes
               2 Dir(s)  21,295,140,864 bytes free
```

**Comment by imjasonh** [comment]
Thanks @aiden-deloryn that's really helpful!

So what's happening is that the first thing the Pod does, in an initContainer, is to copy the entrypoint binary from the entrypoint image to a shared volume, `/tekton/tools`, which is mounted into each subsequent step container. It does this by invoking the entrypoint binary itself, to copy itself to `/tekton/tools`, then exit.

Code for that is here: https://github.com/tektoncd/pipeline/blob/v0.25.0/pkg/pod/entrypoint.go#L104

You can see it's calling `/ko-app/entrypoint cp /ko-app/entrypoint /tekton/tools/entrypoint`, which works fine for Linux, but fails miserably on Windows. 🤦‍♂️ 

1. On Windows, the binary will be at `c:\ko-app\entrypoint.exe`
2. On Windows, the binary should get copied to `c:\tekton\tools\entrypoint.exe`

Since we don't want to alter the Pod definition based on whether it's going to be scheduled to Windows or Linux, we should try to see if we can get the entrypoint to do the right thing on Linux vs Windows itself.

So if we have the initContainer do something like:

```
initContainers:
- name: place-tools
  image: gcr.io/.../cmd/entrypoint
  args: ['cp']  # invoke the entrypoint binary in `cp` mode
```

Then the entrypoint logic can be platform-aware using Go build tags:

- on Linux, `cp` mode means "copy `/ko-app/entrypoint` to `/tekton/tools`
- on Windows, `cp` mode means "copy `c:\ko-app\entrypoint.exe` to `c:\tekton\tools\entrypoint.exe`

What might complicate this is that steps mount that volume with the `mountPath: /tekton/tools` today, and might need to mount it with `mountPath: c:\tekton\tools` and `entrypoint: c:\tekton\tools\entrypoint.exe` on Windows, unless there's some way to be OS-agnostic in those paths that I'm unaware of.

**Comment by TBBle** [comment]
`mountPath: /tekton/tools` should work, as [k8s will convert it if needed](https://github.com/kubernetes/kubernetes/blob/v1.21.2/pkg/kubelet/kubelet_pods.go#L241-L244). It will [prepend `C:` to an otherwise absolute path](https://github.com/kubernetes/kubernetes/blob/v1.21.2/pkg/volume/util/util.go#L488-L504), and `/` works fine on Windows.

Clearly the `copy` is already working based on the existing output, so you should only need to get the executable extension correct. If this works, then it'd be simplest:

```
/ko-app/entrypoint cp /ko-app/entrypoint* /tekton/tools/
```

I assume but haven't checked that, similarly, `entrypoint: /tekton/tools/entrypoint` would work on Windows to execute `C:\tekton\tools\entrypoint.exe` by usual Windows executable-lookup rules.

**Comment by aiden-deloryn** [comment]
@imjasonh Is there any way I can help out with the entrypoint issue to keep this moving forward? I'd be happy to make some tweaks and test the options discussed here if needed.

**Comment by aiden-deloryn** [comment]
I was able to get ko to build a valid entrypoint image by removing the file extension `.exe` on: [pkg/build/gobuild.go#L440](https://github.com/imjasonh/ko/blob/380b0a4afe9fc038424e3dc9dd8be11fee6e0ea0/pkg/build/gobuild.go#L440) and [pkg/build/gobuild.go#L700](https://github.com/imjasonh/ko/blob/380b0a4afe9fc038424e3dc9dd8be11fee6e0ea0/pkg/build/gobuild.go#L700) which means that the file extension is not needed. 

With this change the entrypoint is working and we don't need to modify the current behaviour of Tekton. I did notice though that I can't pull the image if it includes files from `kodata`. I haven't figured out why that is yet...

The error I'm getting with `kodata` included is:
```
failed to register layer: re-exec error: exit status 1: output: open \\?\C:\ProgramData\docker\tmp\hcs370407523\Files\var\run\ko\refs\heads\controller-windows-images: The system cannot find the path specified.
```

I've checked the image layer on disk and the files do exist.

**Comment by TBBle** [comment]
If you [run dockerd with the `DOCKER_WINDOWSFILTER_NOREEXEC` env-var set non-empty](https://github.com/moby/moby/blob/v20.10.7/daemon/graphdriver/windows/windows.go#L56-L67), you should get more information about that failure in the logs.

My immediate guess is that the file or one of the elements of the path is actually a link to an earlier layer, but the target is missing for some reason. It also could be a symlink with no target, which _should_ work, but possibly something in the import process is trying to follow the link when it shouldn't be.

**Comment by imjasonh** [comment]
The [`ko` Windows PR](https://github.com/google/ko/pull/374) is merged! 🎉 

> I was able to get ko to build a valid entrypoint image by removing the file extension `.exe` on: [pkg/build/gobuild.go#L440](https://github.com/imjasonh/ko/blob/380b0a4afe9fc038424e3dc9dd8be11fee6e0ea0/pkg/build/gobuild.go#L440) and [pkg/build/gobuild.go#L700](https://github.com/imjasonh/ko/blob/380b0a4afe9fc038424e3dc9dd8be11fee6e0ea0/pkg/build/gobuild.go#L700) which means that the file extension is not needed.

Oh the .exe suffix isn't needed? That simplifies things, I'll make that change to ko then (https://github.com/google/ko/pull/400) -- thanks!

I've rebuilt the gcr.io/imjasonh/combined base image, and entrypoint with the exe-dropping change, please try them out and see what else breaks 😆 

```
gcr.io/imjasonh/github.com/tektoncd/pipeline/cmd/entrypoint@sha256:7f6d879ca7b359324121e0196c55f5185173bad75ca0b3f0a2e9201a00981c09
```

> 
> With this change the entrypoint is working and we don't need to modify the current behaviour of Tekton. I did notice though that I can't pull the image if it includes files from `kodata`. I haven't figured out why that is yet...

Yeah, while I was working on the ko PR I had quite a lot of trouble with the kodata part. The PR as merged should support kodata now, with the exception of files in kodata that are symlinks, which will just be ignored for Windows images. If this is something we think we need we can investigate re-adding it, I don't think it should block entrypoint work at least.

**Comment by aiden-deloryn** [comment]
@imjasonh Good job on the ko PR. I've done some testing with the ko built images you provided and it appears everything is working! :smile: :tada: 

The only outstanding problem for Windows that I am aware of is support for *script mode* which is being addressed by https://github.com/tektoncd/pipeline/pull/4128. 

<details>
  <summary>windows-task.yaml</summary>
  
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: windows-task
spec:
  workspaces:
    - name: output-workspace
      mountPath: c:/output
  steps:
  - name: clone-repo
    image: aidendeloryn/windows-base-example:latest
    command: ["git"]
    args:
      - "clone"
      - "--depth"
      - "1"
      - "--single-branch"
      - "https://github.com/google/ko.git"
      - "C:\\workspace"
  - name: build-binary
    image: aidendeloryn/windows-base-example:latest
    command: ["go"]
    args:
      - "build"
      - "-a"
      - "-v"
      - "-o"
      - "ko.exe"
      - "main.go"
  - name: print-version
    image: aidendeloryn/windows-base-example:latest
    command: ["ko"]
    args:
      - "version"
  - name: print-help
    image: aidendeloryn/windows-base-example:latest
    command: ["ko"]
    args:
      - "--help"
  - name: copy-bin
    image: aidendeloryn/windows-base-example:latest
    command: ["cmd"]
    args:
      - "/c"
      - "copy"
      - "C:\\workspace\\ko.exe"
      - "C:\\output\\ko.exe"
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: windows-taskrun
spec:
  workspaces:
    - name: output-workspace
      persistentVolumeClaim:
        claimName: local-workspace-pvc
  taskRef:
    name: windows-task
  podTemplate:
    nodeSelector:
      kubernetes.io/os: windows
```
</details>

```
$ tkn taskrun list
NAME              STARTED         DURATION   STATUS
windows-taskrun   8 minutes ago   1 minute   Succeeded

$ kubectl get pod windows-taskrun-pod-tfwvq
NAME                        READY   STATUS      RESTARTS   AGE
windows-taskrun-pod-tfwvq   0/5     Completed   0          2m26s

$ kubectl describe pod windows-taskrun-pod-tfwvq
Name:         windows-taskrun-pod-tfwvq
Namespace:    default
Priority:     0
Node:         k8s-windows/10.115.11.52
Start Time:   Mon, 02 Aug 2021 11:34:24 +1000
Labels:       app.kubernetes.io/managed-by=tekton-pipelines
              tekton.dev/task=windows-task
              tekton.dev/taskRun=windows-taskrun
Annotations:  pipeline.tekton.dev/release: devel
              tekton.dev/ready: READY
Status:       Succeeded
IP:           10.244.1.132
IPs:
  IP:           10.244.1.132
Controlled By:  TaskRun/windows-taskrun
Init Containers:
  place-tools:
    Container ID:  docker://275d296316b81c314e069daad78989dbe243af9777c16e76224560cd55cf84f3
    Image:         gcr.io/imjasonh/github.com/tektoncd/pipeline/cmd/entrypoint@sha256:7f6d879ca7b359324121e0196c55f5185173bad75ca0b3f0a2e9201a00981c09
    Image ID:      docker-pullable://gcr.io/imjasonh/github.com/tektoncd/pipeline/cmd/entrypoint@sha256:7f6d879ca7b359324121e0196c55f5185173bad75ca0b3f0a2e9201a00981c09
    Port:          <none>
    Host Port:     <none>
    Command:
      /ko-app/entrypoint
      cp
      /ko-app/entrypoint
      /tekton/tools/entrypoint
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 02 Aug 2021 11:34:26 +1000
      Finished:     Mon, 02 Aug 2021 11:34:27 +1000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /tekton/tools from tekton-internal-tools (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ndjzr (ro)
...
```

**Comment by lippertmarkus** [comment]
I just tried out hybrid workflows:
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mypipeline
spec:
  tasks:
    - name: task-win
      taskSpec:
        steps:
          - name: hello-windows
            image: mcr.microsoft.com/windows/nanoserver:1809
            command: ["cmd", "/c"]
            args: ["echo", "Hello from Windows Container!"]
    - name: task-lin
      taskSpec:
        steps:
          - name: hello-linux
            image: alpine
            command: ["echo"]
            args: ["Hello from Linux Container!"]        
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: mypipelinerun
spec:
  pipelineRef:
    name: mypipeline
  taskRunSpecs:
    - pipelineTaskName: task-win
      taskPodTemplate:
        nodeSelector:
          kubernetes.io/os: windows
        securityContext:
          # without this I get the error: Creating a symlink "/tekton/steps/0": symlink \tekton\steps\step-hello-windows /tekton/steps/0: A required privilege is not held by the client.
          windowsOptions:
            runAsUserName: "ContainerAdministrator"
    - pipelineTaskName: task-lin
      taskPodTemplate:
        nodeSelector:
          kubernetes.io/os: linux
```

I found that running the Windows container with `ContainerAdministrator` user is mandatory (see comment within yaml). Is there a way we can work around that? Like with Linux containers, running Windows containers with full privileges isn't a good practice.

Apart from that it works great, awesome work!
