### ISSUE TITLE
The provided example for `Task` and `TaskRun` doesn't work

### ISSUE THREAD

**Issue by Dimss** [tektoncd/pipeline#1855]
# Expected Behavior
Example will work
# Actual Behavior
Example doesn't work
# Steps to Reproduce the Problem

`kubectl apply -f <on-the-file-below>.yaml`

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: read-task
spec:
  inputs:
    resources:
      - name: workspace
        type: git
  steps:
    - name: readme
      image: ubuntu
      command:
        - /bin/bash
      args:
        - "cat README.md"
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: go-example-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/pivotal-nader-ziada/gohelloworld
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: read-repo-run
spec:
  taskRef:
    name: read-task
  inputs:
    resources:
      - name: workspace
        resourceRef:
          name: go-example-git
```
Getting 
```
/bin/bash: cat README.md: No such file or directory
```
# Additional Info
