### ISSUE TITLE
Script support for sidecar

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#1856]
# Expected Behavior

Same as main steps, `script` working on `sidecars` steps

# Actual Behavior

Not supported

```
Error from server (InternalError): error when creating "sidecar.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "script"
```

# Steps to Reproduce the Problem

```yaml
  sidecars:
    - image: centos
      name: uploader
      script: |
        #!/usr/bin/env bash
        while :;do
            ls /workspace/output
            sleep 5
        done
```

# Additional Info
