### ISSUE TITLE
generateName for ClusterTask TaskRun Not Setting TaskRun Name 

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/pipeline#1859]
# Expected Behavior

Using `generateName` with TaskRun for ClusterTask generates a unique TaskRun name.

# Actual Behavior

`generateName` does not set the name for the TaskRun: `resource name may not be empty`

# Steps to Reproduce the Problem

1. Use https://github.com/tektoncd/pipeline/blob/7ff3f78858d898b3717811b89b184fe3fd4c8c2d/examples/taskruns/clustertask.yaml
2. `kubectl apply -f https://github.com/tektoncd/pipeline/blob/7ff3f78858d898b3717811b89b184fe3fd4c8c2d/examples/taskruns/clustertask.yaml`

# Additional Info

You'll need to change `ClusterTask` definition to:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: clustertask
spec:
  steps:
  - image: ubuntu
    script: |
      #!/usr/bin/env bash
      echo "Hello"
```

Also, changing `generateName` to `name` resolves the issue for the TaskRun definition
