### ISSUE TITLE
Git "depth" value is ignored

### ISSUE THREAD

**Issue by CSTDev** [tektoncd/pipeline#1871]
# Expected Behavior
Git repository is checked out to the same depth as specified in the Resource definition.

# Actual Behavior
Repository is checked out with a depth of 1 regardless

# Steps to Reproduce the Problem

1. Create the following Task and TaskRun:
```
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: show-git-depth
spec:
  inputs:
    resources:
      - name: source-repo
        type: git
        targetPath: .
  steps:
    - name: show-git-log
      image: alpine/git
      script: |
        #!/usr/bin/env sh
        git log
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: taskrun
spec:
  taskRef:
    name: show-git-depth
  inputs:
    resources:
      - name: source-repo
        resourceSpec:
          type: git
          params:
            - name: url
              value: https://github.com/tektoncd/pipeline.git
            - name: depth
              value: '2'
```
2. View logs, see that the git log command returned only the last commit, expected the last few commits

# Additional Info
Same thing happens with:
- a depth of 0
- the value in ""
- running it on something other than alpine
