### ISSUE TITLE
Add Cluster scope pipeline support

### ISSUE THREAD

**Issue by zhangtbj** [tektoncd/pipeline#1876]
# Expected Behavior
We can also define Cluster scope pipeline as ClusterTask

Right now, Tekton has Cluster scope task ClusterTask, but If I also want to run a Cluster scope pipeline which include that ClusterTask.

So that people can define Cluster scope pipeline for all cluster-level users

# Actual Behavior
Something like:

```
apiVersion: tekton.dev/v1alpha1
kind: ClusterPipeline
metadata:
  name: clusterpipeline
  name: demo-pipeline
spec:
  resources:
  - name: source-repo
    type: git
  tasks:
  - name: skaffold-unit-tests
    taskRef:
      name: unit-tests
...
```
