### ISSUE TITLE
Directly access Pipeline Params from taskSpec

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#1879]
With the PR #1554, we added support to specify `taskSpec` along with `pipelineSpec` so that we can embed `task` and `pipeline` specifications instead of referencing them. But, there is one caveat that it leads to when it comes to accessing pipeline params since its modeled based on the way `task` and `pipeline` are referenced. Ideally, we would like to directly access pipeline parameters directly instead of defining a param under `taskSpec` and then use that param. For example, task param `MESSAGE` is bound to pipeline param `MESSAGE` before referring to it inside the task script as `$(inputs.params.MESSAGE)`:   

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun-with-taskspec-to-echo-message
spec:
  pipelineSpec:
    params:
      - name: MESSAGE
        description: "Message, default is Hello World!"
        type: string
        default: "Hello World!"
    tasks:
      - name: echo-message
        taskSpec:
          inputs:
            params:
              - name: MESSAGE
                type: string
                default: "Hello World!"
          steps:
            - name: echo
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "$(inputs.params.MESSAGE)"
        params:
          - name: MESSAGE
            value: $(params.MESSAGE)
  params:
    - name: MESSAGE
      value: "Good Morning!"
```

Can we simplify this approach and instead of declaring task parameters, allow task authors to directly use pipeline params?

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun-with-taskspec-to-echo-message
spec:
  pipelineSpec:
    params:
      - name: MESSAGE
        description: "Message, default is Hello World!"
        type: string
        default: "Hello World!"
    tasks:
      - name: echo-message
        taskSpec:
          steps:
            - name: echo
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "$(params.MESSAGE)"
  params:
    - name: MESSAGE
      value: "Good Morning!"
```
