### ISSUE TITLE
Conditional build of subproject within a monorepo depending on modified files/directories

### ISSUE THREAD

**Issue by acim** [tektoncd/pipeline#1922]
Use cases:

1. You have monorepo containing backend and frontend for your application. You probably want to test and build just frontend if no files inside backend directory are modified and opposite.
2. You have repo with ton of Ansible roles. You probably want to test just modified ones, not all.
3. You modified just readme.md and don't want to test/build everything.

Jenkins has something called [changeset](https://jenkins.io/doc/book/pipeline/syntax/).

/kind feature

**Comment by sbwsg** [comment]
Could you elaborate a bit more here - would you want a Trigger to only fire a Pipeline on the condition that a specific subproject's files changed?  A Task in a Pipeline to be executed only if a subproject had changed?  Or maybe just a Step inside a Task to be run conditionally?

This can be hacked together today with some bash but it's ugly:

```yaml
# inside a task
steps:
    - name: test-subproject
      image: my-test-image-with-git
      script: |
        cd my_monorepo_checkout
        # count number of changed files in subproject
        subproject_changes=$(git log --format= -n 1 --name-only | egrep "^subproject_subdir" | wc -l)
        if [[ $subproject_changes -ne 0 ]] ; then
          # run tests!
        fi
```

Interesting feature request - would love to hear more about what stage in the life of a pipeline you'd like to see this kind of check happen.

**Comment by acim** [comment]
Well, my use case is the first one. I have Golang backend and Svelte frontend in separate repositories, but I would actually like to merge them together in one monorepo because they are tight related, they should be deployed togher using the same Helm chart, etc. So, I would like to find out if something has changed in directory frontend and in this case build just Svelte application image, push it to registry and release. Same for the backend.

But I have seen similar discussion related to drone.io and Jenkins and there are people having above mentioned problems like having plenty of Ansible roles which takes a long time to test all of them, but should really test just the modified ones.

Or for example Helm charts, it is huge monorepo with hundred or so charts, so it would be useful to find out really what subproject to build.

I know this is possible to do with shell script but like you said, it is ugly. So it would be nice if you can find out some nice and easy way to achieve this with Tekton as I really think it is going to replace most of the other CI/CD's.

I am not in rush with this, but maybe you put this into long term planning and make us all happy with such a feature in some of the new releases. Thank you in advance.

**Comment by dibyom** [comment]
I think Conditional Tasks in a pipeline should work for this...you can have multiple task(s) e.g. build golang, build frontend etc. Each task can have a condition that determines if it should be run. The condition can e.g. look into the git resource/PR resource and see if go files were modified etc.
(I think @pritidesai had an example for this -- conditional builds depending on the type of source files)

```
tasks:
- name: build-go
  conditions:
  - conditionRef: "commit-contains-go-files"
- name: build-frontend
  conditions:
  - conditionRef: "commit-contains-js-files"
```
