### ISSUE TITLE
Can't run Task including multiple steps with different resources requests/limits values

### ISSUE THREAD

**Issue by mgreau** [tektoncd/pipeline#1933]
# Expected Behavior

A `Task` can have multiple `steps` with different resources requests/limits values, where the n-1 `step` gets higher values than the latest step.

# Actual Behavior

While it works with Tekton Pipelines **0.8.0** and **0.9.2**, since the **0.10.0** it is not possible to deploy a `Task` which defines a `step` 2 with higher values than the latest step. 
An error message like below is thrown (in that case the `spec.containers[2].resources.limit` value is `512Mi` but the `spec.containers[3].resources.limit`is `128Mi`)

```
Message
Invalid TaskSpec: Pod "resource-request-bug-mi-pod-db877" is invalid: spec.containers[2].resources.requests: Invalid value: "256Mi": must be less than or equal to memory limit
```

# Steps to Reproduce the Problem

The [following `TaskRun`](https://gist.githubusercontent.com/mgreau/2e34b5e535134ee97e3a0aa3b1e3b248/raw/2a43ad6d023aa838a8e869b73f049cec0ef413e1/tekton-resource-request-issue.yaml)  is used to reproduce the problem:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: resource-request-issue
spec:
  taskSpec:
    steps:
    - name: minimal-resources-values
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail
        echo "Hello from Bash using memory request 64Mi and limit to 128Mi!"
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
    - name: maximal-resources-values
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail
        echo "Hello from Bash using memory request 256Mi and limit to 512Mi!"
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"
    - name: re-minimal-resources-values
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail
        echo "Hello from Bash using memory request 64Mi and limit to 128Mi!"
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
```
1. Install Tekton Pipelines 0.10.0
```
kubectl apply -f https://github.com/tektoncd/pipeline/releases/download/v0.10.0/release.yaml
```
2. Apply the TaskRun
```
kubectl apply -f https://gist.githubusercontent.com/mgreau/2e34b5e535134ee97e3a0aa3b1e3b248/raw/2a43ad6d023aa838a8e869b73f049cec0ef413e1/tekton-resource-request-issue.yaml
taskrun.tekton.dev/resource-request-issue created
```
3. Check the output
```
tkn taskrun describe resource-request-issue                                                                                                                                                     
Name:        resource-request-issue
Namespace:   default

Status
STARTED          DURATION    STATUS
35 seconds ago   ---         Failed(CouldntGetTask)

Message
Invalid TaskSpec: Pod "resource-request-issue-pod-lmh64" is invalid: spec.containers[2].resources.requests: Invalid value: "256Mi": must be less than or equal to memory limit

Input Resources
No resources

Output Resources
No resources

Params
No params

Steps
No steps
```
4. Delete Tekton Pipelines 0.10.0 and the TaskRun
```
$ kubectl delete namespace tekton-pipelines
namespace "tekton-pipelines" deleted

$ tkn taskrun delete resource-request-issue                                                                                                                                                       
Are you sure you want to delete taskrun "resource-request-issue" (y/n): y
TaskRun deleted: resource-request-issue
```
5. Install Tekton Pipelines 0.9.2
```
kubectl apply -f https://github.com/tektoncd/pipeline/releases/download/v0.9.2/release.yaml
```
6. Apply the TaskRun
```
kubectl apply -f https://gist.githubusercontent.com/mgreau/2e34b5e535134ee97e3a0aa3b1e3b248/raw/2a43ad6d023aa838a8e869b73f049cec0ef413e1/tekton-resource-request-issue.yaml
taskrun.tekton.dev/resource-request-issue created
```
7. Check the output and logs
```
tkn taskrun describe resource-request-issue
Name:        resource-request-issue
Namespace:   default

Status
STARTED          DURATION     STATUS
12 seconds ago   12 seconds   Succeeded

Input Resources
No resources

Output Resources
No resources

Params
No params

Steps
NAME                          STATUS
minimal-resources-values      Completed
maximal-resources-values      Completed
re-minimal-resources-values   Complete

tkn taskrun logs resource-request-issue
[minimal-resources-values] + echo 'Hello from Bash using memory request 64Mi and limit to 128Mi!'
[minimal-resources-values] Hello from Bash using memory request 64Mi and limit to 128Mi!

[maximal-resources-values] Hello from Bash using memory request 256Mi and limit to 512Mi!
[maximal-resources-values] + echo 'Hello from Bash using memory request 256Mi and limit to 512Mi!'

[re-minimal-resources-values] Hello from Bash using memory request 64Mi and limit to 128Mi!
[re-minimal-resources-values] + echo 'Hello from Bash using memory request 64Mi and limit to 128Mi!'
```

# Additional Info

it might be related to this update https://github.com/tektoncd/pipeline/pull/1655 but I'm not sure.
