### ISSUE TITLE
Handle non-printable characters/binary data in task results

### ISSUE THREAD

**Issue by eddie4941** [tektoncd/pipeline#1939]
# Abstract

In the current design of Task Results, values that are output by a task
are read  from the result files (`/tekton/results/<resultName>`)
and stored in the TaskRun.Status as is. This means that result values
with non-printable characters/binary data can end up in the
`taskrun.status.taskResults` making it look awkward when fetching it
via k8 api.

For example, here's a task that outputs a result with and without a
newline. The result with the new line is formatted differently than
the one without. The output would be even worse if there were more
new lines/other binary data and might pose problems when as pass
the data to subsequent tasks.

```yaml
apiVersion: tekton.dev/v1alpha1
 kind: TaskRun
 ...
 status:
 ...
    taskResults:
    - name: current-date-newline
      value: |
        1579891332
    - name: current-date-no-newline
      value: "1579891331"
```

# Potential solutions
One approach to avoid this would be to encode the result in base64.
We could do the following:

1. Read results from the result files (`/tekton/results/<resultName>`)
2. Store the content of the result file as a base64 string in the termination log
3. Store the base64 encoded value in the `taskrun.status.taskResults[].value`

This would mean that all `taskrun.status.taskResults[].value` would be
base64 encoded. Therefore we may need to adjust how the controller 
passes data along to subsequent task to potentially decode the data.

Another approach is to add a `type` field to the
`task.spec.results[]` to indicate the type of date the result is meant
to hold. The `type` field would have at least two values: `string` and
`bytes`.

e.g.

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
...
spec:
  results:
    - name: my-string-result
      type: string
    - name: my-bytes-results
      type: bytes
```

results of type `string` would be handled as they are today, but results
of type `bytes` would be base64 encoded as described above and passed
to subsequent tasks as base64 encoded strings to avoid decoding issues.
