### ISSUE TITLE
Pipeline Results

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#1950]
# Expected Behavior

A Pipeline should be able to declare a list of results that should be emitted by any executed Tasks of that Pipeline.

# Actual Behavior

At the moment the results of Tasks in a Pipeline will be buried in the TaskRuns' Status fields.

# Steps to Reproduce the Problem

1. Run a Pipeline that uses Tasks that emit results.
2. Notice that the created PipelineRun does not include any of those tasks' results in its Status.

# Additional Info

Task Results were introduced in issue https://github.com/tektoncd/pipeline/issues/1273

Here's an example of the kind of YAML we'd like to be able to support, as proposed by @skaegi in #1273.  Notice that the Pipeline declares the results that it will emit and uses variable substitution to indicate which tasks those pipeline results come from:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: add
spec:
  params:
    - name: first
      description: the first operand
    - name: second
      description: the second operand
  results:
    - name: sum
      description: the sum of the first and second operand
  steps:
    - name: add
      image: alpine
      env:
        - name: OP1
          value: $(params.first)
        - name: OP2
          value: $(params.second)        
      command: ["/bin/sh", "-c"]
      args:
        - echo $((${OP1}+${OP2})) | tee /workspace/results/sum;
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sum-three 
spec:
  params:
    - name: first
      description: the first operand
    - name: second
      description: the second operand
    - name: third
      description: the third operand      
  tasks:
    - name: first-add
      taskRef:
        name: add-task
      params:
        - name: first
          value: $(params.first)
        - name: second
          value: $(params.second)
    - name: second-add
      runAfter: [first-add]
      taskRef:
        name: add-task
      params:
        - name: first
          value: $(tasks.first-add.results.sum)
        - name: second
          value: $(params.third)
  results:
    - name: sum
      description: the sum of all three operands
      value: $(tasks.second-add.results.sum)
```
