### ISSUE TITLE
git resource: Host key verification failed. How to debug this?

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/pipeline#1953]
# Expected Behavior

I can use the Git pipeline resource

# Actual Behavior
```
kubectl logs build-app-image-from-git-source-pod-3a71ce  step-git-source-app-git-j842g
```
```
{"level":"error","ts":1580161755.2518187,"logger":"fallback-logger","caller":"git/git.go:40","msg":"Error running git [fetch --depth=1 --recurse-submodules=yes origin 9.9.9-1--1-3]: exit status 128\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:40\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:69\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:40\nruntime.main\n\truntime/proc.go:203"}
```

# Additional Info

I've tested this git ssh private key + `known_hosts` on my command line and I can clone the git repo with no issues. However the step keeps failing w/ the error above and I need some direction on how to get more info out of tekton to see what I'm missing

```
apiVersion: v1
kind: Secret
metadata:
  name: myapps-azurepipelines-dog-ssh-key 
  annotations:
    tekton.dev/git-0: ssh.dev.azure.com
data:
  ssh-privatekey: omitted=
  known_hosts: c3NoLmRldi5henVyZS5jb20gc3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDN0hyMW9UV3FOcU9sekdKT2ZHSjROYWtWeUl6ZjFyWFlkNGQ3d282akJsa0x2Q0E0b2RCbEwwbURVeVowL1FVZlRUcWV1K3RtMjJnT3N2K1ZyVlRNazZ2d1JVNzVnWS95OXV0NU1iM2JSNUJWNThkS1h5cTlBOVVlQjVDYWtlaG41WmdtNngxbUtvVnlmK0ZGbjI2aVlxWEpSZ3pJWlpjWjVWNmhyRTBRZzM5a1ptNGF6NDhvMEFVYmY2U3A0U0xkdm51TWEyc1ZOd0hCYm9TN0VKa201N1hRUFZVMy9RcHlOTEhiV0Rkend0cmxTK2V6MzBTM0FkWWhMS0VPeEFHOHdlT255cnRMSkFVZW45bVRrb2w4b0lJMWVkZjdtV1diV1ZmMG5CbWx5MjErblpjbUNUSVNRQnRkY3lQYUVubzdmRlFNREQyNi9zMGxmS29iNEt3OEgK
  
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-builder
secrets:
  - name: myapps-azurepipelines-dog-ssh-key 
  - name: dockerhub-dog # NOTE this docker registry secret was created separately and I is to be used for the 'image' pipelineresource

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-git
spec:
  type: git
  params:
    - name: revision
      value: 9.9.9-1--1-3
    - name: url
      value: git@ssh.dev.azure.com:v3/my-apps/zero-apps-docker/test-app

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-image
spec:
  type: image
  params:
    - name: url
      value: dockerhub.dog.com/test/test-app:9.9.9-1--1-3

---

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-app-image-from-git-source
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/docker-source/dockerfiles/202001271549043N-9.9.9-1--1-3/202001271549043N-9.9.9-1--1-3.Dockerfile
      - name: pathToContext
        type: string
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/docker-source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.15.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage.url)
        - --context=$(inputs.params.pathToContext)

---

apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-app-image-from-git-source
spec:
  serviceAccountName: app-builder
  taskRef:
    name: build-app-image-from-git-source
  inputs:
    resources:
      - name: docker-source
        resourceRef:
          name: app-git
    params:
      - name: pathToDockerFile
        value: dockerfiles/202001271549043N-9.9.9-1--1-3/202001271549043N-9.9.9-1--1-3.Dockerfile
      - name: pathToContext
        value: /workspace/docker-source 
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: app-image
```

Any other tips for how to run this maybe in a "debug mode"? or so I can go look at the filesystem for what is going on in this step?

**Comment by bitsofinfo** [comment]
I tried doing this in the `Task` prior the `build-and-push` step to no avail.. it won't run because the git checkout failed. 

```
    - name: pre-build-and-push
      image: ubuntu
      command:
      - /bin/bash
      args:
      - -c
      - |
        set -ex
        find /workspace
```

```
2020/01/28 13:45:59 Skipping step because a previous step failed
```

I also looked at your debugging doc and it mentions a pause Task...but I don't see how to use this w/ this Task when the actual Git PipelineResource itself is generating a Step that is failing... how can I triage whats going on here?
