### ISSUE TITLE
task: json: unknown field "optional"

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/pipeline#1958]
# Expected Behavior

That this would work:

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-my-app-image-from-git-source
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
        optional: true
...
...
```
# Actual Behavior

```
Error from server (InternalError): error when creating "all.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "optional"
```
