### ISSUE TITLE
Task Result path should be available as a variable

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#1977]
# Expected Behavior

The path for a task result should be available as a variable that can be interpolated into scripts.  Example YAML we'd like to support:

```yaml
  # Task Spec
  results:
    - name: current-date-unix-timestamp
      description: The date in unix timestamp format.
  steps:
    - name: print-date-unix-timestamp
      image: bash:latest
      script: date +%s | tee $(results.current-date-unix-timestamp.path)
```

In the above example we'd like `$(results.current-date-unix-timestamp.path)` to resolve to `/tekton/results/current-date-unix-timestamp`.

# Actual Behavior

At the moment the user has to hard-code the task result path into their Task's script.  In other words, if a user wants their Step Container to emit a task result then they need to physically write out `/tekton/results/result-name` in their code.

# Additional Info

Suggested by @afrittoli [here](https://github.com/tektoncd/pipeline/issues/1273#issuecomment-579702296).
