### ISSUE TITLE
.ssh configs etc are not available when running manual git commands in other steps.

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/pipeline#1990]
I have a `PipelineResource` of type `git`

When properly configured this yields all the required ssh components under `/tekton/home/.ssh` and my git repo is cloned under `/workspace`

I then proceeded to add a `step` in my `Task` such as 

```
 - name: pre-build-and-push
      image: ubuntu
      command:
      - /bin/bash
      args:
      - -c
      - |
         cd /workspace/my-git-source
         git pull
```

This led me down hours of looking into why I kept getting `Host key verification failed.` errors despite the current user `root` yielding `/home/tekton` when having the shell state that `~` is indeed `/tekton/home`... that contains a legit `.ssh` dir with all the proper configs/known_hosts etc.

My `git pull` only worked finally after copying `/tekton/home/.ssh` to `/root/.ssh`....

# Additional Info

https://github.com/tektoncd/pipeline/issues/1836#issuecomment-575741808

https://tektoncd.slack.com/archives/CJ62C1555/p1580479063149600

**Comment by afrittoli** [comment]
Thank you for your bug report.

One thing that we need to do for sure is to update the documentation in https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#ssh-authentication-git where it talks about `~/.ssh/config` - it should say `/tekton/home/.ssh` instead.

Apart from that, I'm not sure there's much more we can do. The location where the ssh config is expected to be depends very much on the docker image (and thus on the OS user) that is used in the step - the only thing we can do it to ensure the configuration is available somewhere that can be consumed by steps.

We could also add an example in the docs of how to point git to the correct configuration without the need of an extra step, I believe something like this should work:
```
steps:
- image: ubuntu
  name: some-git-script
  workingDir: $(outputs.resources.<git-resource-name>.path)
  env:
    name: GIT_SSH_COMMAND
    value: "/usr/bin/ssh -F /home/tekton/.ssh/config"
  script: |
      #!/usr/bin/env sh
      # Access a private git repo
      git pull
```
