### ISSUE TITLE
Add documentation for top level environment on Task

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#1994]
It doesn't' seem that we have documentation or example for top level environments feature 

Here is a snipped of a yaml test that would covers it  :

```yaml
spec:
  env:
   - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: secret
          key: key
   steps:
     - name: step1
     - script: "set -eu;echo ${SECRET_KEY}"
```

/kind feature
