### ISSUE TITLE
Link workspaces together through a pipeline. 

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2017]
# Expected Behavior

It should be possible to express in a pipeline that "this task's workspace is shared with that other task, and it should write to it before I read from it". And from this declaration Tekton should be able to infer that one task should execute before the other one.  We implemented / prototyped this using a "from" clause similar to that of `PipelineResources` but there was some pushback related to the syntax as well as the perceived need for the clause. So instead of merging that I'm capturing the issue here and we can revisit it either when there's clear demand or it otherwise becomes obvious that it's a necessary addition.

The [first implementation's](https://github.com/tektoncd/pipeline/pull/1936) syntax looked like this:

```yaml
# in a pipeline spec
  tasks:
    - name: task1
      taskRef:
        name: write-to-workspace
      workspaces:
        - name: output
          workspace: pipeline-ws1
    - name: task2
      taskRef:
        name: read-from-workspace
      workspaces:
        - name: src
          from:
            task: task1
            name: output
```

The important part to note is the "from" clause in the second task that points at the prior task's workspace. The PR that implemented this used that information to order the tasks such that task1 would execute before task2 could.  A PVC could then be threaded from one to the other through a workspace binding.

This issue doesn't mandate that we should continue to use that design. We can introduce any other syntax we want if the feature becomes necessary. We could potentially use variable substitution here but it's unclear precisely which value would be substituted into which other field. However the nice thing about using a variable would be that it has parity with [the task results linking that is being worked on](https://github.com/tektoncd/pipeline/issues/1978).
