### ISSUE TITLE
How to use build-arg, that takes value from param of a task?

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#2027]

**Comment by dibyom** [comment]
Can you provide some more details on what you are trying to accomplish? A minimal example of the task you are trying to run will help. Thanks!

**Comment by zeromsi** [comment]
Hi dibyom,
This is my task 
```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
  namespace: tekton
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/docker-source/Dockerfile
      - name: pathToContext
        type: string
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/docker-source
      - name: abc
        type: string
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.14.0

      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage.url)
        - --context=$(inputs.params.pathToContext)
        - --build-arg=`abc=$(inputs.params.abc)`
```
I'm trying to send key-value through args and get those from my dockerfile. 
Hope it is clear now.

**Comment by zeromsi** [comment]
Hi @dibyom ,
I got a solution,
 
```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
  namespace: tekton
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/docker-source/Dockerfile
      - name: pathToContext
        type: string
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/docker-source
      - name: nexususer
        type: string
      - name: nexuspassword
        type: string
      - name: nexus-public-url
        type: string
      - name: nexus-releases-url
        type: string
      - name: nexus-snapshots-url
        type: string
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.14.0

      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage.url)
        - --context=$(inputs.params.pathToContext)
        - --build-arg=nexususer=$(inputs.params.nexususer)
        - --build-arg=nexuspassword=$(inputs.params.nexuspassword)
        - --build-arg=nexus-public-url=$(inputs.params.nexus-public-url)
        - --build-arg=nexus-releases-url=$(inputs.params.nexus-releases-url)
        - --build-arg=nexus-snapshots-url=$(inputs.params.nexus-snapshots-url)
```
