### ISSUE TITLE
Hidden order dependency between volumes and workspaces

### ISSUE THREAD

**Issue by TheodorAtBud** [tektoncd/pipeline#2049]
# Expected Behavior

I expect volumes and workspaces to be defined in whatever order in a task's spec.

# Actual Behavior

Workspaces have to be defined after volumes, otherwise the workspace does not get mounted. 

# Steps to Reproduce the Problem
```
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: bug
spec:
  steps:
     - name: tag
      image: busybox
      volumeMounts:
        - name: one-volume
          mountPath: /somewhere
      script: |
        # This is fine
        ls /somewhere
        # This is not
        ls $(workspaces.input.path)
  volumes:
    - name: one-volume
      emptyDir: {}
  workspaces:
    - name: input
```
# Additional Info

Swapping volumes with workspaces around, would fix the issue and mount correctly. 
All of this can be verified if one described the pod of the TaskRun.

**Comment by bobcatfish** [comment]
Bizarre!!

@TheodorAtBud could you also provide the TaskRuns you are using for this? And if it's at all possible to include what the resulting pods look like that would be super helpful too.

This really surprises me because I didn't think that this kind of ordering was actually preserved on the server side :thinking:

**Comment by bobcatfish** [comment]
Hey @TheodorAtBud I tried to reproduce this but I'm afraid I couldn't!

I tried making this TaskRun to reproduce it (modified version of https://github.com/tektoncd/pipeline/blob/master/examples/taskruns/workspace-volume.yaml):

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: workspace-volume-
spec:
  taskSpec:
    steps:
    - name: write-volume
      image: ubuntu
      script: echo some stuff > /workspace/stuff
    - name: read-volume
      image: ubuntu
      script: cat /workspace/stuff | grep stuff

    - name: override-volume
      image: ubuntu
      # /workspace/stuff *doesn't* exist.
      script: |
        #!/usr/bin/env bash
        [[ ! -f /workspace/stuff ]]
      volumeMounts:
      - name: empty
        mountPath: /workspace

    - name: write-workspace
      image: ubuntu
      script: echo some moar-stuff > $(workspaces.custom.path)
    - name: read-workspace
      image: ubuntu
      script: cat $(workspaces.custom.path) | grep moar-stuff

    volumes:
    - name: empty
      emptyDir: {}
    
    # Use of workspaces is suggested instead of explicitly
    # specifying volumes, since you don't have to provide the
    # volume until runtime.
    workspaces:
    - name: custom
```

I moved the `workspaces` declaration around but it didn't make any difference. I'm also pretty sure that the content is sent to the API server, and later to the Tekton controller, in a way that doesn't preserve the order you declare these fields in anyway.

Maybe something was going wrong with the volumes you are using? I think to go further with this the next step would be to take a look at the TaskRun that provides the workspace, and maybe the pod, and the logs.
