### ISSUE TITLE
Support Task looping syntax inside Pipelines

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#2050]
# Desired behaviour

In some cases we are provided a parameter that is an array of values where we want to run a particular Task against each element of the array, when we don't know in advance the length of the array.

You could also imagine a Pipeline that operates on some value, such as the source code for and destination of, an image, and you want to be able to run the same Pipeline for 1+ images, when you only know at runtime how many images you'll be operating on.

# Current behaviour

To support this we currently have to dynamically write a Pipeline that has the appropriate Tasks.

In addition, there are variations that we might want to think of here like parallel vs. sequential, conditional execution, early termination, and likely more.

**Comment by bobcatfish** [comment]
As long as we don't have Tekton dynamically creating Pipelines I'm all for this. 

I'd like to see this more like a Python "list comprehension" vs. a looping construct that allows for parts of Pipelines to execute in loops.

**Comment by skaegi** [comment]
re: comprehension -- yes,  that's where my head is at too

**Comment by n3wscott** [comment]
I also would like a feature like this but at the Task Step level where the input is an array, and for each element in the array it explodes out into n steps.

**Comment by dbazhal** [comment]
To me ansible loops syntax look pretty nice. As very weak, but example, it could be used to run task for multiple cluster resources.
```
tasks:
  - name: run-deploy
    pipelineRef:
      name: deploy
    params:
      - name: cluster
        value: {{item.name}}
    for_each:
      - name: testing
      - name: fake_production
      - name: production
    when: !strings.Contains(item.name, "fake")
```

**Comment by afrittoli** [comment]
This type of fan-out tasks will also require syntax / logic for tasks to:
- access the task result / output resources of any of the tasks
- express workflow rules like `runAfter` against the collection of tasks

Conditions may be attached to the task. Do we run the condition N times? Ideally if we had a way to determine whether the condition depends on the param that generates the fan-out - we could run the condition one, but in general we will need to run it once for each instance of the task.

**Comment by jcmcken** [comment]
In my use case, I don't need access to the results or outputs, I'm just relying on the success or failure of the task. So maybe there's room for a first iteration of this facility that doesn't have all the bells and whistles, but allows a simple fan out

**Comment by skaegi** [comment]
Even though there are cases that do not require results, I think it would be good to have support as part of the general solution since  it makes it consistent with the Task interface.

Another decision we have to make here is around supporting parallel vs sequential task running. It might make a lot of sense here if we adopted the semantics of `map` (tasks run in parallel and produce an array of 'results') and `reduce` (tasks run sequentially accumulating the previous with the current value to create a final result). We might also consider adding a `filter` (tasks run in parallel to return true/false to return a filtered version of the original array input) but that could be done later.

```
tasks:
-  name: my-map-task
    map:
       array: [$(params.myArray[*])]
    taskRef:
      name: someParallelTask
    params: # map params have the variables: currentValue, index, and array in scope
      - name: param1
         value: $(currentValue)
      - name: param2
         value: $(index)
      - name: param3
         value: $(array)
    #results is an array of the individual task results
-  name: my-reduce-task
    reduce:
       array: [$(params.myArray[*])]
       initialValue: 0
    taskRef:
      name: someSequentialTask
    params: # reduce params have the variables: accumulator, currentValue, index, and array in scope
      - name: param0
         value: $(accumulator)
      - name: param1
         value: $(currentValue)
      - name: param2
         value: $(index)
      - name: param3
         value: $(array)
      #results is the final result of the last sequentially run task
```
This is borrowing a lot from what was spec'ed in Javascript [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) and [Reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce) which in turn borrowed heavily from the ideas in [Python](https://www.learnpython.org/en/Map,_Filter,_Reduce).
