### ISSUE TITLE
GitHub status upload/download should use a combined status instead of a list of all statuses

### ISSUE THREAD

**Issue by tomgeorge** [tektoncd/pipeline#2062]
# Expected Behavior

When using a PullRequest resource, I expect to have the most recent check statuses available to me in a pipeline

# Actual Behavior

A ref can have multiple statuses with the same label,  and `Download`/`toDisk` writes the last occurence of the returned statuses to disk, which is not always the most recent one.  Using `FindCombinedStatus` instead of `ListStatuses` fixes this problem.  A combined status contains the latest version of the checks.


# Steps to Reproduce the Problem

1.  Open a PR and set a check to success/failure back and forth a few times
2.  Run a pipeline that takes a GitHub PR as a resource, and cat out the statuses
```yaml
- name: check-status   
   image: busybox                                                                                                                                                                                                        
   script: |                                                                                                                                                                                                                     
     cat $(outputs.resources.pr.path)/status/*                                                                                                                                                                                   
```
3.  The `state` of the check is not always the most recent one

A full example of the trigger/pipeline is available [here](https://github.com/tomgeorge/plumbing/blob/check-pr-has-kind-label/tekton/resources/checks/check-pr-has-kind-label.yaml)

# Additional Info
