### ISSUE TITLE
Secret example for Gitlab and oauth;!basic-auth

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#2063]
kind/question

**Comment by dibyom** [comment]
Can you please describe in more detail what you are looking for?

**Comment by zeromsi** [comment]
Hi @dibyom 
I got the solution,
In case of gitlab, instead of user name as username, we need to pass oauth as username. This is fishy. 
``` 
apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  annotations:
    tekton.dev/git-0: https://gitlab.com # Described below
type: kubernetes.io/basic-auth
stringData:
  username: oauth
  password: git-pass
```
