### ISSUE TITLE
Webhook error when creating a Pipeline without a taskSpec or taskRef

### ISSUE THREAD

**Issue by bioball** [tektoncd/pipeline#2077]
# Expected Behavior

Creating a pipeline whose tasks are missing a taskSpec or taskRef should fail with a validation error.

# Actual Behavior

This is the result:
```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.tekton.dev": Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/?timeout=30s: EOF
```

# Steps to Reproduce the Problem

1. Create a pipeline whose tasks are missing `taskRef` or `taskSpec`:
    ```sh
    cat << EOF | kubectl apply -f - 
    apiVersion: tekton.dev/v1alpha1
    kind: Pipeline
    metadata:
      name: my-simple-pipeline
    spec:
      tasks:
        - name: some-task
    EOF
    ```

**Comment by sbwsg** [comment]
Hrm.  We do have some validation around missing both taskRef and taskSpec.  The error message looks more like the webhook hasn't started up yet or there is some kind of routing error to the webhook service.

> failed calling webhook "webhook.tekton.dev": Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/?timeout=30s: EOF

**Comment by sbwsg** [comment]
@bioball Could you check on the status of the webhook?  You should be able to do this with `kubectl get -o yaml -n tekton-pipelines deployment tekton-pipelines-webhook`

And then if there's a webhook pod as well can you grab the logs from it with `kubectl logs -n tekton-pipelines -l app=tekton-pipelines-webhook`?

**Comment by bioball** [comment]
I don't think this is an error around networking or deployment of the webhook; it actually creates the pipeline successfully if I change the yaml to include a `taskRef`.

Here's the status of my deployment:

```yaml
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-13T23:56:26Z"
    lastUpdateTime: "2020-01-13T23:56:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-11-14T00:13:30Z"
    lastUpdateTime: "2020-01-27T21:50:39Z"
    message: ReplicaSet "tekton-pipelines-webhook-6676956486" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 19
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

Here's the logs:

```
github.com/tektoncd/pipeline/vendor/knative.dev/pkg/webhook.(*Webhook).ServeHTTP(0xc000212580, 0x19b5740, 0xc0006a6048, 0xc001bca100)
	github.com/tektoncd/pipeline/vendor/knative.dev/pkg/webhook/webhook.go:233 +0xcb0
net/http.serverHandler.ServeHTTP(0xc0006982a0, 0x19b5740, 0xc0006a6048, 0xc001bca100)
	net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0x19bc140, 0xc000dcaf90, 0xc000156000, 0xc0006982a0, 0x19b5740, 0xc0006a6048, 0xc001bca100)
	net/http/server.go:3374 +0x8d
net/http.(*http2serverConn).runHandler(0xc000549800, 0xc0006a6048, 0xc001bca100, 0xc001ba0020)
	net/http/h2_bundle.go:5713 +0x9f
created by net/http.(*http2serverConn).processHeaders
	net/http/h2_bundle.go:5447 +0x4eb
```

FYI: this is running off the v0.10.0 release.
