### ISSUE TITLE
Optionally emit events during execution

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#2082]
# Expected Behavior

Although a user can use [the CloudEvent PipelineResource](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#cloud-event-resource) to emit events during a TaskRun or PipelineRun, some folks may want this to happen by default, for significant events such as:

* Starting execution
* Finishing execution
* Condition skipped
* ....?

# Actual Behavior

[The CloudEvent PipelineResource](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#cloud-event-resource)  is the only option for this right now, but even that needs #1684 before it can be relied on (see #2053)

# Additional info

* One open question is _where_ it would be emitting events _to_, e.g. does the Run provide an endpoint address that CloudEvents are sent to via HTTP, or do the events go to some kind of message bus, or something else?
* Note that the keptn.sh folks are interested in creating standards around these kinds of events https://github.com/keptn/keptn/issues/1259

**Comment by afrittoli** [comment]
@bobcatfish I've been thinking about this for a bit, and I think it would be great to have the ability to specify a sink in the `Task|PipelineRun` so that cloud events could be sent by a task without the need of altering the task to add the pipeline resource. This would greatly improve the re-usability of tasks, e.g. when using Tasks as CI Jobs.

It gets a bit more complicated than just a sink though, since we might need to:
1. send the event to multiple sinks
1. send the event to different sinks depending on the event
1. send the event to different sinks depending on the task in a pipeline

A lot of those might be avoided when using tekton triggers by using a single EventListener with multiple triggers and CEL filters to select the right thing to select.

This is highly related to the notification work too, as I think the basic infrastructure required in the controller to make this happen is the same as that needed for notifications.

**Comment by afrittoli** [comment]
As a starting point, I think it's a fair assumption to let receivers / channels filter events, and err on the side of sending too many events, in favour of a lean syntax on Tekton side.
In practice this means that a `PipelineRun` and a `TaskRun` will get a new field that allows specifying a list of sinks. If sinks are specified, a cloud event will be sent for all events to all sinks.

Options for the field name: `sinks`, `cloudEvents`, `cloudEventSinks`, `notify`

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-with-sinks
spec:
  serviceAccountName: bot
  cloudEvents:
    - http://my-event-listener
    - https://another-event-listener
     - https://some-external-service
  pipelineRef:
    name: my-pipeline
  params:
    - name: p1
      value: v1
  resources:
  - name: source
    resourceRef:
      name: git-resource
```

Similar syntax for `TaskRuns`. When set on `PipelineRun` level, all siniks would apply to all `TaskRuns`.
