### ISSUE TITLE
Tekton variable expansion seems to have issues.

### ISSUE THREAD

**Issue by n3wscott** [tektoncd/pipeline#2093]
Found two things:

Given, 

```
params:
    - name: FOO
      value: foo
    - name: FOOBAR
      value: $(params.FOO)-bar
    - name: FOOBARBAZ
      value: $(params.FOOBAR)-baz
```

1. Templates that have nested refs do not fully resolve.

ie, the value of FOOBARBAZ will not fully resolve some times, and will be `$(params.FOOBAR)-baz`

2. Order seems to matter. Sometimes a run will have the value of FOOBAR as `foo-bar` and other times it will be `$(params.FOO)-bar` like `params.FOO` has not been processed yet.
