### ISSUE TITLE
PipelineTask Names Can Be Created That Violate TaskRun Naming Rules

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/pipeline#2095]
When creating a Pipeline that has PipelineTasks, you can give each PipelineTask a name that differs from a TaskRef's name:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sleep-pipeline
  labels:
    app: tekton-workshop
spec:
  tasks:
  - name: pipelineTask1
    taskRef:
      kind: Task
      name: sleep1s
  - name: pipelineTask2
    taskRef:
      kind: Task
      name: sleep10s
```

The PipelineTask names can include capital letters, such as in the example above. If someone does this, the TaskRuns associated with the PipelineRun for the Pipeline above will get the following error:

```
Warning  TaskRunCreationFailed  109s                pipeline-controller  Failed to create TaskRun "sleep-pipeline-run-pvs5c-pipelineTask1-6wjd6": TaskRun.tekton.dev "sleep-pipeline-run-pvs5c-pipelineTask1-6wjd6" is invalid: metadata.name: Invalid value: "sleep-pipeline-run-pvs5c-pipelineTask1-6wjd6": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
  Warning  TaskRunCreationFailed  109s
```

This error above occurs since TaskRun names must be lowercase, but PipelineTasks are allowed to be capitalized. 

This will actually cause the PipelineRun to continue running until it times out after an hour. 

# Expected Behavior

Similar to what is done for Tasks, the Pipeline above should be rejected since the PipelineTask names don't follow the rules of how TaskRun names are specified:

```
The Task "sleeP10s" is invalid: metadata.name: Invalid value: "sleeP10s": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

# Actual Behavior

The error above.

# Steps to Reproduce the Problem

1. Create a Pipeline with PipelineTask names with capital letters
2. Try to run the Pipeline
