### ISSUE TITLE
mutation failed: cannot decode incoming new object: json: unknown field "results"

### ISSUE THREAD

**Issue by ssvinoth22** [tektoncd/pipeline#2107]
# Expected Behavior
        Tasks with results are suposed to be reused..
# Actual Behavior

Error from server (InternalError): error when creating "task/datetime.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "results"

# Steps to Reproduce the Problem

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: print-date
  annotations:
    description: |
      A simple task that prints the date
spec:
  results:
    - name: current-date-unix-timestamp
      description: The current date in unix timestamp format
    - name: current-date-human-readable
      description: The current date in human readable format
  steps:
    - name: print-date-unix-timestamp
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        date +%s | tee /tekton/results/current-date-unix-timestamp
    - name: print-date-humman-readable
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        date | tee /tekton/results/current-date-human-readable
```

# Additional Info
