### ISSUE TITLE
Add support for Task Step looping

### ISSUE THREAD

**Issue by n3wscott** [tektoncd/pipeline#2112]
It would be interesting if I could create [0, n] steps inside a Task based on parameters:

Something like this Task spec:

```
inputs:
  params:
    foos: 
      - foo
      - bar
      - baz
steps:
  - image: ubuntu
    command: [echo]
    args: ["start"]
  - forEach: $(param.foos) 
    image: ubuntu
    command: [echo]
    args: ["at $(step)"]
  - image: ubuntu
    command: [echo]
    args: ["end"]
```

would result in a Task run with output like:

```
start
at foo
at bar
at baz
end
```

**Comment by vdemeester** [comment]
It's a little bit linked to #2050

/kind feature

**Comment by n3wscott** [comment]
The real use case here is I wrote a tool that does a single thing (mutates a file) and I wrote a task to use that tool. But I found no way to call that tool for each usage I need inside of Tekton directly. I would have to either 1- create a task with a known # of steps, or 2- wrap it in a bash script.

I avoid the bash script because I am not trying to write bash here, I can use tekton and other tools directly. It would be backwards for me to take a dep on a bash script. And I would have to rethink all of my images... (cli tools built in go, shipped with ko)

**Comment by ImJasonH** [comment]
This might also be an opportunity to invest in a DSL that supports syntactic sugar for loops and compiles down to unrolled steps/tasks. Nobody wants to be programming in Turing complete YAML. Even Bash is better than that.

**Comment by bobcatfish** [comment]
This is an interesting idea @n3wscott ! One thing that might help is to ground us in a use case, do you have an example of a Task that you'd create if you had the ability to loop with steps?

**Comment by booninite** [comment]
Something like this example would represent what we would like to do with the ability: https://github.com/argoproj/argo/blob/master/examples/loops-param-argument.yaml

There are other looping examples that are more/less real world related than that in the same repository.

**Comment by bobcatfish** [comment]
hmmm that's an interesting example @booninite ! I know this is gonna disagree with @ImJasonH but I really could see that making sense for Tekton Pipelines 🤔  - I'm not sure I'd want it to be quite as automagical as the argo example, where the looping is implied.

@booninite @n3wscott are you sure you absolutely want this at the level of the steps in the Task? As mentioned in https://github.com/tektoncd/pipeline/issues/2050 we've discussed adding a list comprehension type syntax at the pipeline level, making the above example something like:

```yaml
kind: Pipeline
spec:
    params:
    - name: os-list
      type: #hand-waving here
       value:  
        [
          { "image": "debian", "tag": "9.1" },
          { "image": "debian", "tag": "8.9" },
          { "image": "alpine", "tag": "3.6" },
          { "image": "ubuntu", "tag": "17.10" }
        ]
  tasks:
  - name: loop-param-arg-example
    taskRef: cat-os-release
    forEach: # i like the idea of making this explicit, but we keep going back and forth on that wiht our `from` syntax so i guess it could be implicit like argo is too
      param: os-list
      params:
      - name: image
         value: os-list[*].image
      - name: tag
         value: os-list[*].tag
```

(Or literally any other syntax that looks better than that, just trying to get the basic idea across)

Looking at https://github.com/argoproj/argo/blob/master/examples/loops-param-argument.yaml it looks like the steps themselves have a template, which in Tekton feels somewhat analogous to Tasks.
