### ISSUE TITLE
Cant run multistep TaskRuns

### ISSUE THREAD

**Issue by hectotruj** [tektoncd/pipeline#2114]
# Expected Behavior
For the following example, there should be two logs, one saying _Hello from Bash!_ and one saying _Hello from Python!_

# Actual Behavior
```sh
➜  Tekton git:(master) ✗ kb logs multistep-task-run-pod-8jbfg -f
error: a container name must be specified for pod multistep-task-run-pod-8jbfg, choose one of: [step-ubuntu-echo step-python-echo] or one of the init containers: [place-scripts place-tools]
```
# Steps to Reproduce the Problem

1. Create `multistep-tas-run.yml` with the following code:
```yml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: multistep-task-run
spec:
  taskSpec:
    steps:
    - name: ubuntu-echo
      image: ubuntu  # contains bash
      script: |
        #!/usr/bin/env bash
        echo "Hello from Bash!"
    - name: python-echo
      image: python  # contains python
      script: |
        #!/usr/bin/env python3
        print("Hello from Python!")
```
2. Apply `multistep-tas-run.yml` by running ` kubectl apply -f bluefringe-task-run.yml`
3. Log the TaskRun pod by running  `kubectl logs multistep-task-run-pod-<pod name> -f`

# Additional Info
Installed version was latest release with
```sh
kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
```
