### ISSUE TITLE
The conditions with multiple same condition intermittently doesn't fail when one of the conditions fails

### ISSUE THREAD

**Issue by akihikokuroda** [tektoncd/pipeline#2124]
# Expected Behavior

When one of the condition in the conditions in pipeline fails, the task associated with the conditions is not executed.

# Actual Behavior

When one of the condition in the conditions in pipeline fails, the task associated with the conditions is intermittently  executed.

This happens intermittently if the conditions has multiple conditions referencing the same condition.

# Steps to Reproduce the Problem

1. create condition / task / pipeline
```
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: is-equal
  namespace: tekton-pipelines
spec:
  params:
  - name: left
    type: string
  - name: right
    type: string
  check:
    image: alpine
    script: |
      #!/bin/sh
      if [ $(params.left) = $(params.right) ]; then
        echo "$(params.left) == $(params.right)"
        exit 0
      else
        echo "$(params.left) != $(params.right)"
        exit 1
      fi
---

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: issue-pipeline
  namespace: tekton-pipelines
spec:
  params:
  - name: one
    type: string
  - name: two
    type: string
  tasks:
  - name: process
    conditions:
    - conditionRef: is-equal
      params:
       - name: left
         value: "1"
       - name: right
         value: $(params.one)
    - conditionRef: is-equal
      params:
       - name: left
         value: "1"
       - name: right
         value: $(params.two)
    taskRef:
      kind: Task
      name: run

---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run
  namespace: tekton-pipelines
spec:
  steps:
    - name: echo
      image: ubuntu
      script: 'echo hello'
```
2. execute the following pipelineruns in the random order.
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: issue1-pipelinerun
  namespace: tekton-pipelines
spec:
  params:
  - name: one
    value: "1"
  - name: two
    value: "1"
  pipelineRef:
    name: issue-pipeline
```
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: issue2-pipelinerun
  namespace: tekton-pipelines
spec:
  params:
  - name: one
    value: "2"
  - name: two
    value: "1"
  pipelineRef:
    name: issue-pipeline
```
```
apiVersion: tekton.dev/v1alpha1                                                                                                                                                                  
kind: PipelineRun                                                                                                                                                                                
metadata:                                                                                                                                                                                        
  name: issue3-pipelinerun                                                                                                                                                                       
  namespace: tekton-pipelines                                                                                                                                                                    
spec:                                                                                                                                                                                            
  params:                                                                                                                                                                                        
  - name: one
    value: "1"
  - name: two
    value: "2"
  pipelineRef:
    name: issue-pipeline
```
3. The `run` task is intermittently executed for issuerun2 or issuerun3

# Additional Info

This issue is probably caused by:

`ConditionCheckName` is used as the key in `ConditionChecks` map  in PipelineRunTaskRunStatus.  The `ConditionCheckName` is same for the conditions referring the same condition.
