### ISSUE TITLE
Validation on Embedded PipelineSpec different from stand-alone Pipeline spec

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#2157]
# Expected Behavior

Whether I am embedding a Pipeline in a PipelineRun, or I am referencing an existing Pipeline with a pipelineRef, the same validation should be applied to the spec of the Pipeline.

# Actual Behavior

When I create an embedded Pipeline spec in a PipelineRun, it is required that I specify `string` as the type for any params I declare (i.e. they do not default to string).

# Steps to Reproduce the Problem

(I'm using 0.11-rc1)

Using `kubectl create -f` with these guys (where the Pipeline exists separately from the PipelineRun) works just fine:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-sample-add-comment-
spec:
  params:
  - name: url
    value: https://github.com/bobcatfish/catservice/pull/20
  - name: secret-key-ref
    value: webhook-secret

  pipelineRef:
    name: my-pipeline
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  params:
  - name: url
  - name: secret-key-ref
```

(The fact that I can create PipelineRuns using Pipelines that have no Tasks, i.e. do nothing, is another story!)

But if I try to do the same thing with an embedded Pipeline:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-sample-add-comment-
spec:
  params:
  - name: url
    value: https://github.com/bobcatfish/catservice/pull/20
  - name: secret-key-ref
    value: webhook-secret

  pipelineSpec:
    params:
    - name: url
    - name: secret-key-ref
```

I get this error:

```
Error from server (BadRequest): error when creating "pullrequest/sample/add-comment.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value: : spec.params.url.type
```

But if I explicitly specify "string" as the type, all is well:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-sample-add-comment-
spec:
  params:
  - name: url
    value: https://github.com/bobcatfish/catservice/pull/20
  - name: secret-key-ref
    value: webhook-secret

  pipelineSpec:
    params:
    - name: url
      type: string
    - name: secret-key-ref
      type: string
```

# Additional Info

[Our example is explicitly specifying "string"](https://github.com/tektoncd/pipeline/blob/34e40226971720c45516bc36c2058ec9df73f4c5/examples/v1beta1/pipelineruns/pipelinerun-with-pipelinespec.yaml#L28) which is why we haven't caught this before - as part of fixing this, we should remove the explicit type specification from the example.

p.s. thanks for debugging this with me @sbwsg !
