### ISSUE TITLE
Support for Tasks that require manual  "approval"

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#2159]
In a Pipeline I'd like to be able to declare a Task that requires "approval" that may or may not contains a taskRef. When started,  it immediately moves into a "suspend" state until an external API call changes its state to "running". The "approval" Task should have a "timeout" that causes the Task to fail after a set period of time.

Something like this...
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: craves-approval
spec:
  tasks:
  - name: approve-me
    requiresApproval: true
    timeOut: 3600
    taskRef:
      name: optional-task-ref
```
