### ISSUE TITLE
Add Image Output Resources

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#216]
## Expected Behavior
If a Task declares that it produces an image output:

1. The TaskRun controller should verify that the promised image was actually created and pushed to where it was supposed to be pushed to. If the Task does not push the image, the TaskRun should fail.
2. The Image resource should be updated with the digest of the image created

This should leverage the design already fleshed out in [knative build artifact design](https://docs.google.com/document/d/1FUn9LZXUAJQb8atoTeRxmsdjxpstOyegHF7ieJEblNs/edit) and the work being added to `go-containerregistry` in https://github.com/google/go-containerregistry/pull/209 and https://github.com/google/go-containerregistry/pull/261 (+ @jonjohnsonjr )

## Actual Behavior

* Currently there is no handling of outputs (only used as part of templating)
* After #124 there should be hooks added to validate resources generically, and "file" resources will be validated, but no other types

### Success case

1. Create a Pipeline that has 2 Tasks, one that builds an image and another that does something with that image using the digest of the image just built, e.g. (based on [this example](https://github.com/knative/build-pipeline/blob/master/examples/pipelineruns/pipelinerun.yaml)).

Tasks:
```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-push
spec:
  inputs:
    resources:
    - name: workspace
      type: git
    params:
    - name: pathToDockerFile
      description: The path to the dockerfile to build
      default: /workspace/workspace/Dockerfile
    - name: pathToContext
      description: The build context used by Kaniko (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: /workspace/workspace
  outputs:
    resources:
    - name: builtImage
      type: image
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor
    command:
    - /kaniko/executor
    args:
    - --dockerfile=${inputs.params.pathToDockerFile}
    - --destination=${outputs.resources.builtImage.url}
    - --context=${inputs.params.pathToContext}

---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: demo-deploy-kubectl
spec:
  inputs:
    resources:
    - name: workspace
      type: git
    - name: image
      type: image
    params:
    - name: path
      description: Path to the manifest to apply
    - name: yqArg
      description: Okay this is a hack, but I didn't feel right hard-codeing `-d1` down below
    - name: yamlPathToImage
      description: The path to the image to replace in the yaml manifest (arg to yq)
    clusters:
    - name: targetCluster
      description: Not yet used, kubectl command below should use this cluster
  steps:
  - name: replace-image
    image: mikefarah/yq
    command: ['yq']
    args:
    - "w"
    - "-i"
    - "${inputs.params.yqArg}"
    - "${inputs.params.path}"
    - "${inputs.params.yamlPathToImage}"
    - "${inputs.resources.image.url}@${inputs.resources.image.digest}" # This is the change relevant to this issue
  - name: run-kubectl
    image: lachlanevenson/k8s-kubectl
    command: ['kubectl']
    args:
    - 'apply'
    - '-f'
    - '${inputs.params.path}'
```

Pipeline:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  resources:
  - name: source-repo
    type: git
  - name: web-image
    type: image
  tasks:
  - name: build-skaffold-web
    taskRef:
      name: build-push
    params:
    - name: pathToDockerFile
      value: Dockerfile
    - name: pathToContext
      value: /workspace/workspace/examples/microservices/leeroy-web
    resources:
      inputs:
      - name: workspace
        resource: source-repo
      outputs:
      - name: builtImage
        resource: web-image
  - name: deploy-web
    taskRef:
      name: demo-deploy-kubectl
    resources:
      inputs:
      - name: workspace
        resource: source-repo
      - name: image
        resource: web-image
        from:
        - build-skaffold-web
    params:
    - name: path
      value: /workspace/workspace/examples/microservices/leeroy-web/kubernetes/deployment.yaml
    - name: yqArg
      value: "-d1"
    - name: yamlPathToImage
      value: "spec.template.spec.containers[0].image"
```

2. Create a PipelineRun and PipelineResources to run it:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-image-leeroy-web
spec:
  type: image
  params:
  - name: url
    value: gcr.io/christiewilson-catfactory/leeroy-web
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-git
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/GoogleContainerTools/skaffold
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: demo-pipeline-run-1
spec:
  pipelineRef:
    name: demo-pipeline
  trigger:
    type: manual
  resources:
  - name: source-repo
    resourceRef:
      name: skaffold-git
  - name: web-image
    resourceRef:
      name: skaffold-image-leeroy-web
```

3. You won't be able to use the digest - the field will be blank! So this will fail b/c it will try to deploy an image called `"${inputs.resources.image.url}@${inputs.resources.image.digest}"` but the digest will be empty so it will be `gcr.io/christiewilson-catfactory/leeroy-web@` (instead of `gcr.io/christiewilson-catfactory/leeroy-web@123456somedigest789`)

### Error case

  1. Create a Task that declares an image as an output, but don't actually create the image (e.g. it just runs echo), e.g. (based on [a working example](https://github.com/knative/build-pipeline/blob/master/examples/taskruns/taskrun.yaml#L40)):

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-push-kaniko
spec:
  inputs:
    resources:
    - name: workspace
      type: git
  outputs:
    resources:
    - name: builtImage
      type: image
  steps:
  - name: build-and-push
    image: ubuntu
    command:
    - echo
    args:
    - "I said I would build an image but I did noooothing"
```

  2. Create a TaskRun that uses that task
  3. Notice there is no error!

This means if you were relying on your pipeline to produce the image, but you made a mistake and the image was never published, you may never notice!

## Additional Info

* [knative build artifact design](https://docs.google.com/document/d/1FUn9LZXUAJQb8atoTeRxmsdjxpstOyegHF7ieJEblNs/edit)
* This issue involves getting information _from_ an invocation of a Task (on disk) back to the controller (and into a Run status) - this is the same functionality  needed for #552 so whatever design and implementation we have for that component should work for both
