### ISSUE TITLE
PipelineResources git sslVerify parameter causing issues

### ISSUE THREAD

**Issue by BostjanBozic** [tektoncd/pipeline#2164]
# Expected Behavior
Adding `sslVerify` parameter to `PipelineResource` type `git` does not break `TaskRun`

# Actual Behavior
If `sslVerify` parameter is added to `git` type of `PipelineResource`, `TaskRun` fails to run, claiming that specific `PipeineResource` is not availab.e

# Steps to Reproduce the Problem

1. Create `PipelineResource`:
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/GoogleContainerTools/skaffold.git
    - name: sslVerify
      value: true
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-image-leeroy-web
spec:
  type: image
  params:
    - name: url
      value: mydockerhub/leeroy-web

```
2. Create `Task`:
```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/docker-source/Dockerfile
      - name: pathToContext
        type: string
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/docker-source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.15.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage.url)
        - --context=$(inputs.params.pathToContext)
```
3. Create `TaskRun`
```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-docker-image-from-git-source-task-run
spec:
  taskRef:
    name: build-docker-image-from-git-source
  inputs:
    resources:
      - name: docker-source
        resourceRef:
          name: skaffold-git
    params:
      - name: pathToDockerFile
        value: Dockerfile
      - name: pathToContext
        value: /workspace/docker-source/examples/microservices/leeroy-web #configure: may change according to your source
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: skaffold-image-leeroy-web
```

# Additional Info
* Platform: OpenShift v3.11.0+0cbc58b
* Tekton version: v0.10.1

As soon as `sslVerify` parameter is added to `PipelineResource` (true or false), `TaskRun` claims that specific resource does not exit:
```
Message

couldn't retrieve referenced input PipelineResource: pipelineresource.tekton.dev "skaffold-git" not found
```

If `PipelineResources` are checked, they are available:
```
NAME                        AGE
skaffold-git                4m
skaffold-image-leeroy-web   4m
```

I also tried to use quotation on parameter ("false"), in which case `TaskRun` recognizes `PipelineResource` and runs, but does not consider parameter, as connectivity fails:
`Failed to connect to github.com port 443: Connection refused` (I checked connectivity and there is no issue there).

**Comment by pritidesai** [comment]
🤔 try this:

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/GoogleContainerTools/skaffold.git
    - name: sslVerify
      value: "true"
---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-image-leeroy-web
spec:
  type: image
  params:
    - name: url
      value: mydockerhub/leeroy-web

---

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: /workspace/docker-source/Dockerfile
    - name: pathToContext
      type: string
      description:
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: /workspace/docker-source
  resources:
    inputs:
      - name: docker-source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.15.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage.url)
        - --context=$(inputs.params.pathToContext)

---

apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-docker-image-from-git-source-task-run
spec:
  taskRef:
    name: build-docker-image-from-git-source
  params:
    - name: pathToDockerFile
      value: Dockerfile
    - name: pathToContext
      value: /workspace/docker-source/examples/microservices/leeroy-web #configure: may change according to your source
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: skaffold-git
    outputs:
      - name: builtImage
        resourceRef:
          name: skaffold-image-leeroy-web
```

taking `params` out of `resources` ...

**Comment by BostjanBozic** [comment]
Thanks for feedback. Should not `params` field be under `input` (at least based on [this](https://github.com/tektoncd/pipeline/blob/v0.10.1/docs/taskruns.md#input-parameters))?

In any case, I tried it with getting `params` out of `resources`, but now nothing is specified in `taskRun` (ommited some metadata fields):
```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
    tekton.dev/task: build-docker-image-from-git-source
  name: build-docker-image-from-git-source-task-run
  namespace: default
spec:
  inputs: {}
  outputs: {}
  serviceAccountName: ""
  taskRef:
    name: build-docker-image-from-git-source
```
