### ISSUE TITLE
Python print statement output is shown in logs after the complete execution of script

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/pipeline#2171]
# Expected Behavior
The print statement output should be shown Immediately in the logs when the print line is executed

# Actual Behavior
The print statement output is shown in the logs after the execution of complete script

# Steps to Reproduce the Problem

1. Create a simple task which consists of python script
```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: check-python-script
spec:
  steps:
    - name: python-example
      image: python  # contains python
      script: |
        #!/usr/bin/env python3
        import time
        for i in range(100):
          time.sleep(1)
          print('Sleeping for 1 second')
```
2. Start the task using command `tkn task start check-python-script`
3. check the logs of the task using the command `tkn taskrun logs -f`

# Additional Info
Tested similar scenario with shell script using the `echo` command, the echo output were shown immediately in the logs
