### ISSUE TITLE
TaskRun validation with duplicate params is incorrect

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#2192]
For this TaskRun and Task...
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  params:
    - name: hi
      default: world
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello $(params.hi)"
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: echo-hello-world-task-run
spec:
  params:
    - name: hi
      value: first
    - name: hi
      value: second
  taskRef:
    name: echo-hello-world
```
The admission webhook returns the error - `validation failed: expected exactly one, got both: spec.inputs.params`.

It's good that the error is caught in 0.11 (it was not in 0.10) however it is catching it for the wrong reason. The problem is not that input.params and params were both used, the problem is that a duplicate param was provided.
