### ISSUE TITLE
Task Workspaces do not serialize to json correctly

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#2199]
I was just looking at the YAML for a basic hello world Task and noticed...
```
spec:
  Workspaces: null
  params:
  - default: world
    name: hi
    type: string
```
I believe we just need to add `json:"workspaces,omitempty"` to the Workspaces declaration in TaskSpec
