### ISSUE TITLE
Pipeline Task using from with multiple entries causes permission denied errors on resource copying

### ISSUE THREAD

**Issue by booninite** [tektoncd/pipeline#2228]
# Expected Behavior
Using `from` on a Pipeline Task input resource with multiple values would cause both resources to be copied, since it is an array.

# Actual Behavior
Doing something like this:

```
  - name: jkcfg-generate
    params:
    - name: flags
      value:
      - -v
      - -i
      - $(params.inputDir)
      - -o
      - $(params.outputDir)
    - name: script
      value: $(params.script)
    resources:
      inputs:
      - from:
        - delete-generated-manifests
        - build-typescript
        name: source
        resource: source
      outputs:
      - name: source
        resource: source
    taskRef:
      kind: Task
      name: jkcfg-generate
```

Will result in errors like:

```
[jkcfg-generate : source-copy-source-7hmk2] {"level":"info","ts":1584135199.468602,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
[jkcfg-generate : source-copy-source-7hmk2] cp: cannot create regular file '/workspace/source/./.git/objects/pack/pack-2f5da47568f60c264b482c5155235dd4187e9b33.pack': Permission denied
[jkcfg-generate : source-copy-source-7hmk2] cp: cannot create regular file '/workspace/source/./.git/objects/pack/pack-2f5da47568f60c264b482c5155235dd4187e9b33.idx': Permission denied
```

# Steps to Reproduce the Problem

1. Have two tasks output a Git resource with the same name.
2. Have a third task declare the same Git resource and specify the first two tasks in `from`
3. Run Pipeline

# Additional Info

- Kubernetes version: `1.15`

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version: `v0.10.1`

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
