### ISSUE TITLE
PipelineRun doesn't use specified serviceAccountName

### ISSUE THREAD

**Issue by jace-ys** [tektoncd/pipeline#2236]
# Expected Behavior

Creating a `PipelineRun` resource via a CRD manifest should use the specified `serviceAccountName`.

# Actual Behavior

Been trying to setup a sample Tekton Pipeline, together with Tekton Dashboard. It seems that creating a `PipelineRun` resource via a CRD manifest uses the `default` service account even if you specify a `serviceAccountName`, causing the PipelineRun to fail unexpectedly. On the other hand, using the Dashboard to create a new PipelineRun and selecting the same service account sets it correctly and the PipelineRun then succeeds.

Top PipelineRun was created using Dashboard, bottom was created by applying the CRD manifest:

![image](https://user-images.githubusercontent.com/33024429/76810693-e1673d80-67e6-11ea-9bf7-016586ec43e3.png)

I can't seem to see what I'm missing in the PipelineRun CRD manifest.

Partial output of `$ kubectl --namespace tekton-pipelines get pipelineruns.tekton.dev deploy-pipeline-run-qf4c4 -o yaml`:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: deploy-pipeline-run-qf4c4
  namespace: tekton-pipelines
spec:
  # missing serviceAccountName
  pipelineRef:
    name: deploy-pipeline
  timeout: 1h0m0s
...
```

# Manifests

```yaml
# tekton/deploy-task.yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kubectl-apply
spec:
  inputs:
    params:
      - name: path
        type: string
        description: Path to manifest
      - name: environment
        type: string
        description: Deployment environment
  steps:
    - name: kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "--namespace"
        - "$(inputs.params.environment)"
        - "-f"
        - "$(inputs.params.path)"
```

```yaml
# tekton/deploy-pipeline.yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  tasks:
    - name: deploy
      taskRef:
        name: kubectl-apply
      params:
        - name: path
          value: https://raw.githubusercontent.com/argoproj/argocd-example-apps/master/guestbook/guestbook-ui-deployment.yaml
        - name: environment
          value: staging
```

```yaml
# tekton/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelines
```

```yaml
# tekton/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-pipelines
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
```

```yaml
# tekton/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: tekton-pipelines
  namespace: tekton-pipelines
```

```yaml
# tekton/deploy-pipelinerun.yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: deploy
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-pipelines # this doesn't seem to take effect
  pipelineRef:
    name: deploy-pipeline
```

# Steps to Reproduce the Problem

1. Apply above manifests in folder: `kubectl --namespace tekton-pipelines -f tekton`
2. Start a new PipelineRun using `tkn --namespace tekton-pipelines pipeline start deploy-pipeline`.

This should fail with the following error:

```
from server for: "https://raw.githubusercontent.com/argoproj/argocd-example-apps/master/guestbook/guestbook-ui-deployment.yaml": deployments.apps "guestbook-ui" is forbidden: User "system:serviceaccount:tekton-pipelines:default" cannot get resource "deployments" in API group "apps" in the namespace "staging"
```

3. Create a new `PipelineRun` via the Dashboard, selecting `tekton-pipelines` as service account - this should succeed.

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.8.0
Pipeline version: v0.10.1
```

- [Tekton Dashboard](https://github.com/tektoncd/dashboard) version: v0.5.2
