### ISSUE TITLE
Applying directory of manifests results in failure of newly created PipelineRun

### ISSUE THREAD

**Issue by jace-ys** [tektoncd/pipeline#2237]
# Expected Behavior

Created `PipelineRun` by applying a directory of manifests via `kubectl` should be able to find its associated `Pipeline`s and `Task`s.

# Actual Behavior

Applying a directory of CRD manifests containing associated `PipelineRun`s, `Pipeline`s and `Task`s causes a race condition where the `PipelineRun` boots and fails as it can't find the associated `Pipeline`s and `Task`s:

```shell
$ tkn --namespace tekton-pipelines pr logs deploy
Pipeline tekton-pipelines/deploy-pipeline can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "kubectl-apply": task.tekton.dev "kubectl-apply" not found
```

On the other hand, when I apply the below manifests 1-by-1, in the order of `tekton/deploy-task.yaml -> tekton/deploy-pipeline.yaml -> tekton/deploy-pipelinerun.yaml`, the PipelineRun starts properly.

# Manifests

```yaml
# tekton/deploy-task.yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kubectl-apply
spec:
  inputs:
    params:
      - name: path
        type: string
        description: Path to manifest
      - name: environment
        type: string
        description: Deployment environment
  steps:
    - name: kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "--namespace"
        - "$(inputs.params.environment)"
        - "-f"
        - "$(inputs.params.path)"
```

```yaml
# tekton/deploy-pipeline.yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  tasks:
    - name: deploy
      taskRef:
        name: kubectl-apply
      params:
        - name: path
          value: https://raw.githubusercontent.com/argoproj/argocd-example-apps/master/guestbook/guestbook-ui-deployment.yaml
        - name: environment
          value: staging
```

```yaml
# tekton/deploy-pipelinerun.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-pipelines
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: tekton-pipelines
  namespace: tekton-pipelines
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: deploy
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-pipelines
  pipelineRef:
    name: deploy-pipeline
```

# Steps to Reproduce the Problem

1. Apply manifest directory all at once: `kubectl --namespace tekton-pipelines apply -f tekton`

2. Check logs of the created `PipelineRun`:

```shell
$ tkn --namespace tekton-pipelines pr logs deploy
Pipeline tekton-pipelines/deploy-pipeline can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "kubectl-apply": task.tekton.dev "kubectl-apply" not found
```

3. Rerunning the `Pipeline` using `tkn --namespace tekton-pipelines pipelinerun start deploy-pipeline --last` should result in the `PipelineRun` succeeding.

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.8.0
Pipeline version: v0.10.1
```
