### ISSUE TITLE
PipelineRun status does not accurately reflect the state of the runtime

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/pipeline#2268]
# Expected Behavior

PipelineRuns and TaskRuns status should reflect the state of the runtimes that make up a pipeline.

# Actual Behavior

There are some cases where a pod will not run but the pipelineRun and taskRun status does not entirely reflect this (although the information is in there). This may be by design given the pods are recoverable but worth raising as a question at least.

For example

### Sample resources with missing config map
```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
  - name: task-one-step-one
    env:
      - name: ENV
        valueFrom:
          configMapKeyRef:
            name: environment-properties
            key: environment
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'echo $ENV']
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: bad-map-ref-pipe
spec:
  tasks:
  - name: task1
    taskRef:
      name: task1
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: bad-map-ref-run
spec:
  pipelineRef:
    name: bad-map-ref-pipe
```

We end up with a pipeline run which appears to be running but on inspecting the taskRun message we see is stuck with the message `Message: build step "step-task-one-step-one" is pending with reason "configmap \"environment-properties\" not found"`and reason `Reason: CreateContainerConfigError` (standalone taskRun message and pipelineRun -> taskRun message both show this)

```
NAME              SUCCEEDED   REASON    STARTTIME   COMPLETIONTIME
bad-map-ref-run   Unknown     Running   19s
```

This does mean observing the pipelineRun you don't get an accurate view of its state given it will never complete. However, if the configmap was to be created the pod would recover and run.

### PipelineRun
```
Name:         bad-map-ref-run
Namespace:    default
Labels:       tekton.dev/pipeline=bad-map-ref-pipe
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"tekton.dev/v1alpha1","kind":"Pipeline","metadata":{"annotations":{},"name":"bad-map-ref-pipe","namespace":"default"},"spec"...
API Version:  tekton.dev/v1alpha1
Kind:         PipelineRun
Metadata:
  Creation Timestamp:  2020-03-23T17:40:26Z
  Generation:          1
  Resource Version:    227000
  Self Link:           /apis/tekton.dev/v1alpha1/namespaces/default/pipelineruns/bad-map-ref-run
  UID:                 359d58c3-ca76-4607-90fc-bfce4f802139
Spec:
  Pipeline Ref:
    Name:   bad-map-ref-pipe
  Timeout:  24h0m0s
Status:
  Conditions:
    Last Transition Time:  2020-03-23T17:40:26Z
    Message:               Not all Tasks in the Pipeline have finished executing
    Reason:                Running
    Status:                Unknown
    Type:                  Succeeded
  Start Time:              2020-03-23T17:40:26Z
  Task Runs:
    bad-map-ref-run-task1-lnt28:
      Pipeline Task Name:  task1
      Status:
        Conditions:
          Last Transition Time:  2020-03-23T17:40:31Z
          Message:               build step "step-task-one-step-one" is pending with reason "configmap \"environment-properties\" not found"
          Reason:                CreateContainerConfigError
          Status:                Unknown
          Type:                  Succeeded
        Pod Name:                bad-map-ref-run-task1-lnt28-pod-xtxnr
        Start Time:              2020-03-23T17:40:26Z
        Steps:
          Container:  step-task-one-step-one
          Name:       task-one-step-one
          Waiting:
            Message:  configmap "environment-properties" not found
            Reason:   CreateContainerConfigError
Events:               <none>
```

Similar if a pvc is missing.

### Sample missing pvc resources

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1-pvc
spec:
  steps:
  - name: task-one-step-one
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'echo running']
    volumeMounts:
      - mountPath: /artifacts
        name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: missing-claim
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: missing-pvc-pipe
spec:
  tasks:
  - name: task1-pvc
    taskRef:
      name: task1-pvc
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: missing-pvc-run
spec:
  pipelineRef:
    name: missing-pvc-pipe
```

The taskRun/pod relationship is the same as above for the config map example.

```
Name:         missing-pvc-run
Namespace:    default
Labels:       tekton.dev/pipeline=missing-pvc-pipe
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"tekton.dev/v1alpha1","kind":"Pipeline","metadata":{"annotations":{},"name":"missing-pvc-pipe","namespace":"default"},"spec"...
API Version:  tekton.dev/v1alpha1
Kind:         PipelineRun
Metadata:
  Creation Timestamp:  2020-03-23T17:46:55Z
  Generation:          1
  Resource Version:    227552
  Self Link:           /apis/tekton.dev/v1alpha1/namespaces/default/pipelineruns/missing-pvc-run
  UID:                 e70a7537-1f5d-4540-830e-5ce6db40cbf6
Spec:
  Pipeline Ref:
    Name:   missing-pvc-pipe
  Timeout:  24h0m0s
Status:
  Conditions:
    Last Transition Time:  2020-03-23T17:46:55Z
    Message:               Not all Tasks in the Pipeline have finished executing
    Reason:                Running
    Status:                Unknown
    Type:                  Succeeded
  Start Time:              2020-03-23T17:46:55Z
  Task Runs:
    missing-pvc-run-task1-pvc-xfpw6:
      Pipeline Task Name:  task1-pvc
      Status:
        Conditions:
          Last Transition Time:  2020-03-23T17:46:55Z
          Message:               pod status "PodScheduled":"False"; message: "persistentvolumeclaim \"missing-claim\" not found"
          Reason:                Pending
          Status:                Unknown
          Type:                  Succeeded
        Pod Name:                missing-pvc-run-task1-pvc-xfpw6-pod-gbkxt
        Start Time:              2020-03-23T17:46:55Z
Events:
  Type     Reason             Age   From                 Message
  ----     ------             ----  ----                 -------
  Warning  PipelineRunFailed  26s   pipeline-controller  PipelineRun failed to update labels/annotations
```

There are other cases where a pod will fail to schedule and the pipelineRun will be ambiguous around the state of the run, for example taints or resource limits stopping the pod from scheduling.

# Steps to Reproduce the Problem

1. Run the above sample resources
2. Check the status of the pipelineRun

# Additional Info

- Kubernetes version:
v1.16

- Tekton Pipeline version:
v0.10.1

I'm not sure this is a legitimate issue given all these states are recoverable and this recovery is handled at the pod level, it does mean that at a given point for a pipelineRun to say its running is not accurate. It may also tie into https://github.com/tektoncd/pipeline/issues/1684 given we are considering creating dependencies on the status of these resources.

EDIT: Should have spotted this, the pvc case looks like a legitimate issue given theres an event indicating it failed
