### ISSUE TITLE
Allow workspaces use any volume type

### ISSUE THREAD

**Issue by dbazhal** [tektoncd/pipeline#2272]
# Expected Behavior

I expect to be able to set up workspaces on any volume kind, not only pvc/emptydir/cm/secret.
Workspace spec body is very similar to VolumeV1Core(https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#volume-v1-core), so it seems natural to expect that workspace can use any kind of volume.

# Actual Behavior

When I try to use cheapest volumes in kubernetes(flexVolume), I get an error:
```
Message

binding "custom" is invalid: expected exactly one, got neither: workspace.configmap, workspace.emptydir, workspace.persistentvolumeclaim, workspace.secret
```

# Steps to Reproduce the Problem

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test1
spec:
  workspaces:
    - name: custom
      flexVolume:
        driver: ceph.rook.io/rook
        fsType: ceph
        options:
          fsName: myfs # name of the filesystem specified in the filesystem CRD.
          clusterNamespace: rook-ceph # namespace where the Rook cluster is deployed
      subPath: my-subdir
```

# Additional Info

- Kubernetes version: 1.11
- Tekton Pipeline version: 0.11.0
