### ISSUE TITLE
Git Resources are always on "master" branch.

### ISSUE THREAD

**Issue by booninite** [tektoncd/pipeline#2282]
# Expected Behavior
If I provide a branch or commit to a Git PipelineResource, running `git status` would indicate that I am not on the master branch.

# Actual Behavior
The branch is always master, even if the revision provided was not the master branch.

# Steps to Reproduce the Problem

1. Create a task which takes in a git resource and a param which is a target branch to push any changes made by the task to.
2. Pass a Git resource to the Task created from `$branch` and also pass `$branch` to the param.
3. The TaskRun will fail because of branch mismatch.

I also ran a Task that executes `git rev-parse --abbrev-ref HEAD` against a non-master revision, which indicate that it was on the `master` branch.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

Client version: 0.7.1

**Comment by popcor255** [comment]
Yeah, I had the same problem. I was gonna elaborate with an issue about the git history in the pipeline resource being a bit off. You seemed to beat me to it. I was going to give screenshot of my git history, but im not sure if that will help solve the problem.

My really sloppy fix: I just ended just making version of buildah with git and cloned the repo.

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build
spec:
  inputs:
    params:
      - name: BUILDER_IMAGE
        description: The location of the buildah builder image.
        default: docker.io/popcor255/buildah-git:v0.1.0
      - name: DOCKERFILE
        description: Path to the Dockerfile to build.
        default: ./dockerfile
      - name: CONTEXT
        description: Path to the directory to use as context.
        default: .
      - name: TLSVERIFY
        description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
        default: "false"
    resources:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - name: build
      image: $(inputs.params.BUILDER_IMAGE)
      workingDir: /workspace/source
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          mkdir ../copy
          git clone https://github.com/cpat-blog-team/blog-client ../copy
          cd ../copy/
          git checkout master
          MASTER_HASH="$(git rev-parse HEAD)"
          cd /workspace/source
          REPO_HASH="$(git rev-parse HEAD)"
          echo "$MASTER_HASH = $REPO_HASH"
          if [ "$REPO_HASH" = "$MASTER_HASH" ]
          then 
            SHORT_GIT_HASH="$(cat .git/FETCH_HEAD | awk '{print substr($1,0,7)}')"
            NEW_IMAGE_ID="$(inputs.resources.image.url):$SHORT_GIT_HASH"
            NEW_IMAGE_ID="$(echo $NEW_IMAGE_ID | sed s/\$NAMESPACE/$NAMESPACE/)"
            echo "SHORT_GIT_HASH = $SHORT_GIT_HASH"
            echo "Building Image $NEW_IMAGE_ID"
            buildah bud --tls-verify="$(inputs.params.TLSVERIFY)" --layers -f "$(inputs.params.DOCKERFILE)" -t "$NEW_IMAGE_ID" "$(inputs.params.CONTEXT)"
            echo "Pushing Image $NEW_IMAGE_ID"
            buildah push --tls-verify="$(inputs.params.TLSVERIFY)" "$NEW_IMAGE_ID" "docker://$NEW_IMAGE_ID"
            echo "NEW_IMAGE_ID=$NEW_IMAGE_ID" >> /workspace/env-config
          else
            echo "Error! Can not build image from branch other than master!" >&2
            exit 1
          fi
      securityContext:
        privileged: true
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
  volumes:
    - name: varlibcontainers
      emptyDir: {}
    - name: m2-repository
      emptyDir: {}
```

**Comment by vdemeester** [comment]
@booninite thanks for the issue

Can you share the yaml of the `PipelineResource` you used ?

**Comment by booninite** [comment]
@vdemeester np 👋 

It is inline since I am scheduling it via a TriggerTemplate, here is the relevant portion:

```yaml
resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      annotations:
        pull-request-url: $(params.pullrequesturl)
      generateName: k8s-manifests-presubmit-
      labels:
        branch: $(params.gitbranch)
        pull-request: $(params.pullrequestnum)
    spec:
      params:
      - name: branch
        value: $(params.gitbranch)
      pipelineRef:
        name: k8s-manifests-presubmit
      resources:
      - name: source
        resourceSpec:
          params:
          - name: revision
            value: $(params.gitbranch)
          - name: url
            value: $(params.gitrepourl)
          type: git
      serviceAccountName: default
```

**Comment by vdemeester** [comment]
/kind question
/kind bug 

:thinking:

**Comment by sbwsg** [comment]
@booninite Can you confirm the version of Tekton that you are using?  You mentioned in your initial post that it was 0.7.1 but I don't think we ever released a Tekton 0.7.1.

There is some default behaviour in the Git PipelineResource that sets the branch to "master" if it receives an empty string as the revision parameter.  But other than this I wasn't able to reproduce the issue - I'll paste below the simple Task that I used to try and reproduce the problem.  Could you try the task I provide and see if it works for you?  If so I'm thinking that there is an empty string coming from either your Trigger Template or somewhere else in the workflow.  I suggest starting with a simple example and then working backwards from there to try and find where the incorrect behaviour is occurring.

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: mytask
spec:
  taskSpec:
    resources:
      inputs:
      - name: git-resource
        type: git
    params:
    - name: branch
    steps:
    - image: ubuntu
      script: cat git-resource/README.md
  params:
  - name: branch
    value: release/v0.36.0
  resources:
    inputs:
    - name: git-resource
      resourceSpec:
        type: git
        params:
          - name: revision
            value: $(params.branch)
          - name: url
            value: https://github.com/GoogleContainerTools/skaffold
```

After running the above TaskRun w/ Task, I received the cloned commit SHA of "1c054d4", which matches that of the `release/v0.36.0` branch in https://github.com/GoogleContainerTools/skaffold

**Comment by booninite** [comment]
@sbwsg I am using Tekton v0.10.1 release.  The 0.7.1 information came from the issue template instructions, which were to run `tkn version`, which seems to provide a different result than the `kubectl` command provided.

I will try out your TaskRun later today and get back to you, thank you.

**Comment by booninite** [comment]
@sbwsg that TaskRun doesn't work on version 0.10.1.  v1beta1 isn't recognized, and v1alpha1 returns a validation error:

```
Error from server (BadRequest): error when creating "test-github-resource-taskrun.yaml": admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "params"
```

**Comment by sbwsg** [comment]
Here, try this one:

```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: mytask
spec:
  taskSpec:
    inputs:
      resources:
      - name: git-resource
        type: git
      params:
      - name: branch
    steps:
    - image: ubuntu
      script: cat git-resource/README.md
  inputs:
    params:
    - name: branch
      value: release/v0.36.0
    resources:
    - name: git-resource
      resourceSpec:
        type: git
        params:
          - name: revision
            value: $(params.branch)
          - name: url
            value: https://github.com/GoogleContainerTools/skaffold
```
