### ISSUE TITLE
Allow resourceSpec within Pipeline definitions

### ISSUE THREAD

**Issue by adrianRiobo** [tektoncd/pipeline#2284]
# Expected Behavior

Allow using resourceSpec within pipeline definitions. The use case is related to [runtime params](https://github.com/tektoncd/pipeline/pull/1186), it is expected to use as a task input resource (git) with a parameter resulting from a previous task within the pipeline.

Example:

```
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-dev
spec:
  ...
  tasks:
    - name: get-servingrepository
      taskRef:
        name: get-servingrepository
      resources:
        inputs:
          - name: repository
            resource: source-repository
    - name: deploy-to-develop
      taskRef:
        name: kubectl-exec
      runAfter: ["get-servingrepository" , "build-and-push-image"]
      params:
        - name: kubectl-args
          value: ["apply", "-f", ".", "-n", "dev"]
      resources:
        inputs:
          - name: repository
            resourceSpec:
               type: git
               params:
                 - name: revision
                   value: develop
                 - name: url
                   value: $(tasks.get-servingrepository.results.serving-repository)
```
# Actual Behavior

Get an error when creating the pipeline:

```
Error from server (InternalError): error when creating "pipeline/pipeline-dev_no_func.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "resourceSpec"
```

# Additional Info
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
 ```
- Tekton Pipeline version:
0.10.1
