### ISSUE TITLE
Lists of key-value parameters should be yaml key-values

### ISSUE THREAD

**Issue by coryrc** [tektoncd/pipeline#2292]
Multiple places have things like:

```
  params:
    - name: revision
      value: master
    - name: url
      value: http://...
```

and

```
  resources:
    inputs:
      - name: docker-source
        type: git
```

Where key-value parameters are emulated using lists, when yaml easily supports arbitrary key-value mapping. The above should be:

```
  params:
    revision:
      value: master
    url:
      value: http://...
```

and

```
  resources:
    inputs:
      docker-source:
        type: git
```

Yaml supports arbitrary key names, so there's no string you can put in the value field you can't use in the name field.
