### ISSUE TITLE
Pipeline results and array parameters

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#2296]
# Expected Behavior

Given the following resources

```yaml
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cli-release-pipeline
spec:
  resources:
  - name: source-repo
    type: git
  tasks:
    - name: get-versions
      resources:
        inputs:
        - name: source
          resource: source-repo
      taskSpec:
        resources:
          inputs:
          - name: source
            type: git
        steps:
        - name: pull
          image: goreleaser/goreleaser
          workingDir: /workspace/source
          script: |
            git status; git fetch -p --all
        - name: get-versions
          image: goreleaser/goreleaser # because it has git
          workingDir: /workspace/source
          script: |
            echo $(git tag --points-at HEAD) > /tekton/results/version
            echo $(git tag --points-at HEAD | sed 's/^.//' | awk -F '[.]' '{ print $1}') > /tekton/results/major
            echo $(git tag --points-at HEAD | sed 's/^.//' | awk -F '[.]' '{ print $2}') > /tekton/results/minor
        results:
        - name: version
        - name: major
        - name: minor
    - name: publish
      # runAfter: [build, unit-tests]
      runAfter: [get-versions]
      taskRef:
        name: kaniko-build-and-push
      params:
      - name: EXTRA_ARGS
        value:
        - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:latest
        - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:v$(tasks.get-versions.results.version)
        - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:v$(tasks.get-versions.results.major)
        - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:v$(tasks.get-versions.results.major).$(tasks.get-versions.results.minor)
        - --destination=gcr.io/tekton-releases/tkn:latest
        - --destination=gcr.io/tekton-releases/tkn:v$(tasks.get-versions.results.version)
        - --destination=gcr.io/tekton-releases/tkn:v$(tasks.get-versions.results.major)
        - --destination=gcr.io/tekton-releases/tkn:v$(tasks.get-versions.results.major).$(tasks.get-versions.results.minor)
      resources:
        inputs:
        - name: source
          resource: source-repo
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build-and-push
spec:
  params:
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: ./Dockerfile
  - name: CONTEXT
    description: The build context used by Kaniko.
    default: ./
  - name: EXTRA_ARGS
    type: array
  - name: BUILDER_IMAGE
    description: The image on which builds will run
    default: gcr.io/kaniko-project/executor:latest
  resources:
    inputs:
    - name: source
      type: git
  steps:
  - name: build-and-push
    workingDir: /workspace/source
    image: $(params.BUILDER_IMAGE)
    # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
    # https://github.com/tektoncd/pipeline/pull/706
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - --dockerfile=$(params.DOCKERFILE)
    - --context=/workspace/source/$(params.CONTEXT)  # The user does not need to care the workspace and the source.
    - $(params.EXTRA_ARGS)
    securityContext:
      runAsUser: 0
```

I would "guess" it has the resolved results interpolated

```yaml
# […]
  - args:
    - -wait_file
    - /tekton/tools/0
    - -post_file
    - /tekton/tools/1
    - -termination_path
    - /tekton/termination
    - -entrypoint
    - /kaniko/executor
    - --
    - --dockerfile=./Dockerfile
    - --context=/workspace/source/./
    - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:latest
    - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:v0.8.0
    - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:v0
    - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:v0.8
    - --destination=gcr.io/tekton-releases/tkn:latest
    - --destination=gcr.io/tekton-releases/tkn:v0.8.0
    - --destination=gcr.io/tekton-releases/tkn:v0
    - --destination=gcr.io/tekton-releases/tkn:v0.8
    command:
    - /tekton/tools/entrypoint
    env:
    - name: HOME
      value: /tekton/home
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    image: gcr.io/kaniko-project/executor:latest
# […]
```

# Actual Behavior

Running this, result with a pod that doesn't get the arguments interpolated

```yaml
# […]
  - args:
    - -wait_file
    - /tekton/tools/0
    - -post_file
    - /tekton/tools/1
    - -termination_path
    - /tekton/termination
    - -entrypoint
    - /kaniko/executor
    - --
    - --dockerfile=./Dockerfile
    - --context=/workspace/source/./
    - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:latest
    - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:v$(tasks.get-versions.results.version)
    - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:v$(tasks.get-versions.results.major)
    - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:v$(tasks.get-versions.results.major).$(tasks.get-versions.results.minor)
    - --destination=gcr.io/tekton-releases/tkn:latest
    - --destination=gcr.io/tekton-releases/tkn:v$(tasks.get-versions.results.version)
    - --destination=gcr.io/tekton-releases/tkn:v$(tasks.get-versions.results.major)
    - --destination=gcr.io/tekton-releases/tkn:v$(tasks.get-versions.results.major).$(tasks.get-versions.results.minor)
    command:
    - /tekton/tools/entrypoint
    env:
    - name: HOME
      value: /tekton/home
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    image: gcr.io/kaniko-project/executor:latest
# […]
```

# Steps to Reproduce the Problem

1. Apply the yaml above
2. Pass it a git resource with a tag
3. See it fail

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
  Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.22", GitCommit:"9bae7fcacb520dfee658b26cc1a9643bf787dfc3", GitTreeState:"clean", BuildDate:"2020-02-27T18:43:37Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.8.0
Pipeline version: v0.11.0-rc3
```

/kind bug

/cc @sbwsg @skaegi @othomann
