### ISSUE TITLE
Running a service image

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/pipeline#2316]
# Expected Behavior
Hi, I have Tekton installed on Kubernetes on-premise cluster. I have a Task and TaskRun yamls to deploy my service in Kubernetes using Tekton. 
No errors on Task and TaskRun.
# Actual Behavior
Getting an error while deploying TaskRun.
# Steps to Reproduce the Problem
When I run TaskRun, I'm getting an error. The error is below.
Failed to create build pod "service-task-run": translating Build to Pod: error getting image manifest: MANIFEST_UNKNOWN: The named manifest is not known to the registry.; map[manifest:test/java-app]

# Additional Info

1. Run Task yaml for the Service Image . yaml file content below.
```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: service-deploy-task
spec:
  steps:
    - name: deploy-service
      image: <replace with service docker image in the docker registry>
```
 
2. Run TaskRun yaml for the Task. yaml file content  below.
```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: service-task-run
spec:
  taskRef:
    name: service-deploy-task
```
- Kubernetes version:

- Tekton Pipeline version:

Client version: 0.8.0
Pipeline version: v0.10.1

(Edited by sbwsg to add backticks around the yaml)

**Comment by sbwsg** [comment]
This error occurs when Tekton is unable to read the image you are using from the registry.  See here: https://github.com/tektoncd/pipeline/blob/master/pkg/pod/entrypoint_lookup_impl.go#L72

So I'm not entirely sure what's going on here but it might be worth double checking that the service account attached to the TaskRun is correctly configured and has permissions it needs to request images.

A workaround, though not a fix, would be to specify a command in your steps.  When a step specifies a command, we don't make a request to the registry to try and figure out the entrypoint.  This is not a great long term solution though I don't think.

**Comment by 2020testuser** [comment]
Thanks Much! Adding the command works. I mean I don't get the jar error anymore.
One step forward  now.

**Comment by wlynch** [comment]
Adding on to this, I encountered a similar problem when enabling workload identity on a GKE cluster.

# Expected Behavior

Tekton GKE clusters configured with [workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) can't pull images using workload identity auth.

# Actual Behavior

Tasks can only be started if `command` is specified, else fails with:

```
message: 'Invalid TaskSpec: translating TaskSpec to Pod: error getting image manifest:
      UNAUTHORIZED: You don''t have the needed permissions to perform this operation,
      and you may have invalid credentials. To authenticate your request, follow the
      steps in: https://cloud.google.com/container-registry/docs/advanced-authentication'
```

# Steps to Reproduce the Problem

1. Set up a cluster with [workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity).
2. Submit a task run with a private GCR image. e.g.
```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: workload-identity-pull-
spec:
  serviceAccountName: build-robot
  taskSpec:
    steps:
      - name: hello
        image: gcr.io/wlynch-test/test-c764cc26288059fef2e5784ac3abb31b
```
This **fails**. (image isn't important, this is a hello world image built from https://github.com/wlynch/test)
3. Submit same task run with `command` specified.
```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: workload-identity-pull-
spec:
  serviceAccountName: build-robot
  taskSpec:
    steps:
      - name: hello
        image: gcr.io/wlynch-test/test-c764cc26288059fef2e5784ac3abb31b
        command: ["test"]
```
This succeeds.

# Additional Info

This looks related to https://github.com/tektoncd/pipeline/issues/2316, but specific to GKE workload identity (not sure if we should dupe or not).

- Kubernetes version: 1.15.11-gke.9
- Tekton Pipeline version: v0.11.2
