### ISSUE TITLE
default-timeout-minutes Not Being Applied to PipelineRuns/TaskRuns

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/pipeline#2324]
# Expected Behavior

When `default-timeout-minutes` is set via a ConfigMap in the `tekton-pipelines` namespace, the timeouts of all TaskRuns/PipelineRuns should be set to the value of `default-timeout-minutes`.

# Actual Behavior

An hour timeout is used regardless if `default-timeout-minutes` is specified. 

# Steps to Reproduce the Problem

1. Create a ConfigMap with the following values:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
  namespace: tekton-pipelines
data:
  default-timeout-minutes: "180"
```

2. Start a PipelineRun or TaskRun
3. Check the value of timeout set for the PipelineRun or TaskRun using `kubectl describe pipelinerun` or `kubectl describe taskrun`.

# Additional Info

- Kubernetes version:

 ```
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

```
Client version: 0.8.0
Pipeline version: v0.11.0
```

# Additional Info

I have verified that everything works as expected in `v0.10.1`. 

/kind bug
