### ISSUE TITLE
TaskRun emits no event when it fails on timeout

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#2328]
# Expected Behavior
When the task finishes, even in case of timeout, an event is emitted.

# Actual Behavior
There's no event generated

```
Status:
  Completion Time:  2020-04-05T09:21:31Z
  Conditions:
    Last Transition Time:  2020-04-05T09:21:31Z
    Message:               TaskRun "taskrun-that-runs-for-longz4wqz" failed to finish within "30s"
    Reason:                TaskRunTimeout
    Status:                False
    Type:                  Succeeded
  Pod Name:                taskrun-that-runs-for-longz4wqz-pod-lm8lx
  Start Time:              2020-04-05T09:21:01Z
  Steps:
    Container:  step-this-step-does-something-it-sleeps-30-seconds
    Image ID:   docker.io/library/busybox@sha256:b26cd013274a657b86e706210ddd5cc1f82f50155791199d29b9e86e935ce135
    Name:       this-step-does-something-it-sleeps-30-seconds
    Running:
      Started At:  2020-04-05T09:21:06Z
    Container:     step-fail
    Image ID:      docker.io/library/busybox@sha256:b26cd013274a657b86e706210ddd5cc1f82f50155791199d29b9e86e935ce135
    Name:          fail
    Running:
      Started At:  2020-04-05T09:21:07Z
    Container:     step-never-runs
    Image ID:      docker.io/library/busybox@sha256:b26cd013274a657b86e706210ddd5cc1f82f50155791199d29b9e86e935ce135
    Name:          never-runs
    Running:
      Started At:  2020-04-05T09:21:07Z
Events:
  Type    Reason   Age   From                Message
  ----    ------   ----  ----                -------
  Normal  Started  110s  taskrun-controller
```

# Steps to Reproduce the Problem

1. `TaskRun`:

```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: taskrun-that-runs-for-long
spec:
  timeout: 30s
  taskSpec:
    steps:
    - name: this-step-sleeps-for-10m
      image: busybox
      script: |
        #!/bin/sh
        set -ex
        echo "Wait for a bit"
        sleep 600
```

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11+IKS", GitCommit:"0562ba8a2dfdd05f7f8721ab4952c02fe1605860", GitTreeState:"clean", BuildDate:"2020-03-13T14:45:42Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

`master`,  after `v0.11.0`
