### ISSUE TITLE
default-timeout-minutes Design Considerations

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/pipeline#2334]
## Format of Default Timeout

Via the config-defaults ConfigMap, a property called `default-timeout-minutes` can be set to [apply a timeout to every TaskRun/PipelineRun](https://github.com/tektoncd/pipeline/blob/00194731669ca5a279ca92b2d94cfb85f6ae7f6d/docs/taskruns.md#configuring-default-timeout) that does not specify a timeout. I think it would be helpful to be able to specify this default in a duration format (e.g., `1h30m2s`). This would allow users to specify timeouts in a more granular way as opposed to only using minutes:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
  namespace: tekton-pipelines
data:
  default-timeout: "1h30m2s"
```

This would also be more consistent with all the examples of timeouts used by pipeline/how `tkn` is allowing users to specify timeouts.

## TaskRun Versus PipelineRun Timeout Defaults

The other suggestion would be to have a way to set timeout defaults for TaskRuns versus PipelineRuns as a default timeout for a TaskRun should more than likely differ from that of an entire PipelineRun.

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
  namespace: tekton-pipelines
data:
  default-taskrun-timeout: "10m"
  default-pipelinerun-timeout: "30m"
```

## Additional Info

Assuming this makes sense, there would need to be some considerations on what the best approach would be to make this backwards compatible with `default-timeout-minutes`.

/kind feature
