### ISSUE TITLE
Task "script" blocks do not support array types for parameters

### ISSUE THREAD

**Issue by ad22** [tektoncd/pipeline#2374]
# Expected Behavior
$params.arrayVar[*] is expanded when referenced in the script
# Actual Behavior
```Error from server (BadRequest): error when creating "my-task.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: variable type invalid in "\echo \"$(params.arrayVar[*])\"\n" for step script: taskspec.steps.script```
# Steps to Reproduce the Problem
Task
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  params:
  - name: arrayVar
    description: my array
    type: array
  steps:
  - name: test
    image: alpine:latest
    script: |
      echo "$(params.arrayVar[*])"
```

TaskRun
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: run
spec:
  taskRef:
    name: test
  params:
    - name: arrayVar
      value:
        - "a"
        - "b"
```

**Comment by sbwsg** [comment]
Thanks for the report!  We do document this though it's a little bit buried: https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#substituting-array-parameters

> You must reference parameters of type array in a completely isolated string within a larger string array.

The `script` field is just a string rather than an array, so the substitution doesn't work here.  Will keep this issue open as a feature request to support it though.

**Comment by ad22** [comment]
>The script field is just a string rather than an array, so the substitution doesn't work here. Will keep this issue open as a feature request to support it though.

@sbwsg That makes sense, I didn't immediately make the connection when going through that line. I will open a PR to call out the script field explicitly in the docs, if that's ok.

This will be good to have if it can be implemented safely. As a workaround for my current task, I've create a space separated string type, which is almost equivalent since I'd guess the array expansion would be into a space separated string anyway.

**Comment by sbwsg** [comment]
> the array expansion would be into a space separated string anyway

Interestingly this is one of the reasons that we don't support array expansion in strings - different use-cases expect different joining strings.  In some cases space-separated is good, in others comma-separated would be preferable.

If you do decide to pursue this then I'd recommend soliciting feedback in [one of our Working Group meetings](https://github.com/tektoncd/community/blob/master/working-groups.md#general).

Also, paging @skaegi here as well who looked into implementing JSONPath for our variable interpolation, which might have built-in syntax for this or otherwise provide a longer-term solution to this problem?

**Comment by skaegi** [comment]
See #1463 -- sorry this is a pretty typical use-case and I'm really late on getting back to working on this after the beta.

**Comment by bobcatfish** [comment]
As @sbwsg explained this was by design (https://github.com/tektoncd/pipeline/issues/2374#issuecomment-612867415) if we want to change this, maybe we can open a separate issue to explore it?

**Comment by joaosilva15** [comment]
I found a workaround for anyone that stumbles on this. You can pass the array in the args section and then use the args in the script. In the above case, it would look something like
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  params:
  - name: arrayVar
    description: my array
    type: array
  steps:
  - name: test
    image: alpine:latest
    args: ["$(params.arrayVar[*])"]
    script: |
      echo "$@"
```
As per tekton documentation 
> A step can specify a script field, which contains the body of a script. That script is invoked as if it were stored inside the container image, and any args are passed directly to it.
