### ISSUE TITLE
Got persistentvolumeclaim "pipelinerun-pvc" not found when running pipelineRun

### ISSUE THREAD

**Issue by fabioluciano** [tektoncd/pipeline#2382]
# Expected Behavior

A pipelineRun executed. 

# Actual Behavior
In my script there is no mention of `pipelinerun-pvc`.
```
  Warning  FailedScheduling  <unknown>  default-scheduler  persistentvolumeclaim "pipelinerun-pvc" not found
  Warning  FailedScheduling  <unknown>  default-scheduler  persistentvolumeclaim "pipelinerun-pvc" not found
```

# Steps to Reproduce the Problem

1. Create a cluster using k3s distribuition. I used this script, [that](https://gist.github.com/fabioluciano/a11088b3145e91d2d4d766b49ebe0d81) i made;
2. Apply the follow resources..

``` yaml
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-builds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton
  namespace: tekton-builds
secrets:
- name: dockerhub-auth-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tekton
  namespace: tekton-builds
---
apiVersion: v1
data:
  password: :P
  username: :P
kind: Secret
metadata:
  annotations:
    note: generated
  labels:
    type: generated
  name: dockerhub-auth-credentials
  namespace: tekton-builds
type: kubernetes.io/basic-auth
---
apiVersion: v1
data:
  GH_TOKEN: :P
kind: Secret
metadata:
  annotations:
    note: generated
  labels:
    type: generated
  name: github-token
  namespace: tekton-builds
type: Opaque
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: dockerhub-repository
  namespace: tekton-builds
spec:
  params:
  - name: url
    value: fabioluciano/fabioluciano.github.io
  type: image
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: github-repository
  namespace: tekton-builds
spec:
  params:
  - name: url
    value: https://github.com/fabioluciano/fabioluciano.github.io
  - name: revision
    value: development
  type: git
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-github-data-tables
  namespace: tekton-builds
spec:
  resources:
    inputs:
    - name: repository
      type: git
    outputs:
    - name: repository
      type: git
  steps:
  - args:
    - install
    - -r
    - $(resources.inputs.repository.path)/src/python/requirements.txt
    - --user
    command:
    - pip3
    env:
    - name: PYTHONUSERBASE
      value: $(resources.inputs.repository.path)/pipcache
    image: python:alpine
    name: install-python-dependencies
  - args:
    - $(resources.inputs.repository.path)/src/python/main.py
    command:
    - python
    env:
    - name: PYTHONPATH
      value: $(resources.inputs.repository.path)/pipcache/lib/python3.8/site-packages/
    - name: GH_TOKEN
      valueFrom:
        secretKeyRef:
          key: GH_TOKEN
          name: github-token
    image: python:alpine
    name: generate-github-tables
    workingDir: $(resources.inputs.repository.path)
  workspaces:
  - name: storage
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: output-pipeline
  namespace: tekton-builds
spec:
  resources:
  - name: git_repository
  - name: image_repository
  tasks:
  - name: generate-github-tables
    resources:
      inputs:
      - name: repository
        resource: git_repository
      outputs:
      - name: repository
        resource: git_repository
    taskRef:
      name: build-github-data-tables
    workspaces:
    - name: storage
      workspace: shared-data
  workspaces:
  - name: shared-data
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun
  namespace: tekton-builds
spec:
  pipelineRef:
    name: output-pipeline
  resources:
  - name: git_repository
    resourceRef:
      name: github-repository
  - name: image_repository
    resourceRef:
      name: dockerhub-repository
  serviceAccountName: tekton
  workspaces:
  - name: shared-data
    persistentVolumeClaim:
      claimName: shared-data-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-volume-claim
  namespace: tekton-builds
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-27T12:32:23Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+k3s1", GitCommit:"3eee8ac3a1cf0a216c8a660571329d4bda3bdf77", GitTreeState:"clean", BuildDate:"2020-03-25T16:13:25Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
v0.11.1
