### ISSUE TITLE
Condition cannot access results from previous task

### ISSUE THREAD

**Issue by r0bj** [tektoncd/pipeline#2385]
# Expected Behavior

Condition can access results from previous task.

# Actual Behavior

Condition cannot access results from previous task.

# Steps to Reproduce the Problem

pipelinerun.yaml:
```
---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: test-dirs
spec:
  params:
  - name: dirs
  check:
    image: bash:5.0
    script: |
      #!/usr/bin/env bash
      set -xe

      if [[ "$(params.dirs)" == "" ]]; then
        exit 1
      fi

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-
spec:
  pipelineSpec:
    tasks:
    - name: list-dirs
      taskSpec:
        results:
        - name: dirs
        steps:
        - name: list-dirs
          image: alpine
          script: |
            echo "dir1 dir2" > $(results.dirs.path)
    - name: echo-dirs
      conditions:
      - conditionRef: test-dirs
        params:
        - name: dirs
          value: $(tasks.list-dirs.results.dirs)
      runAfter:
      - list-dirs
      taskSpec:
        params:
        - name: dirs
        steps:
        - name: echo-dirs
          image: alpine
          script: |
            echo "$(params.dirs)"
      params:
      - name: dirs
        value: $(tasks.list-dirs.results.dirs)
```

Logs from `test-dirs` pod:
```
++ tasks.list-dirs.results.dirs
/tekton/scripts/script-0-gdvzt: line 4: tasks.list-dirs.results.dirs: command not found
+ [[ '' == '' ]]
+ exit 1
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

 ```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.1", GitCommit:"aa93664bafe74f3c051e021b27a64e28ac34ab40", GitTreeState:"clean", BuildDate:"2020-03-18T22:49:35Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
 ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
```
Client version: 0.8.0
Pipeline version: v0.11.1
```
