### ISSUE TITLE
Make emptyDir the default volume source for workspaces in TaskRun

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/pipeline#2398]
In the case when we have a `Task` with a workspace, e.g.

```
piVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task
spec:
      steps:
      - name: write
        image: ubuntu
        script: echo $(workspaces.task-ws.volume) > $(workspaces.task-ws.path)/foo
      workspaces:
      - name: task-ws
```
# Expected Behavior

That Tekton could provide me with good default values when possible and the convention is a good fit for the problem.

When I create a `TaskRun` _without_ defining a workspace volume, I can get a working solution by convention.

Example (YAML) but use case is useful for e.g. **cli** as well:

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: tr
spec:
  taskRef:
    name: task
  workspaces:
  - name: task-ws
```

And the TaskRun should successfully run.

# Actual Behavior

A volume for the workspace _must_ be specified.

```
kubectl create -f tr.yaml 
Error from server (BadRequest): error when creating "tr.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: expected exactly one, got neither: workspace.configmap, workspace.emptydir, workspace.persistentvolumeclaim, workspace.secret, workspace.volumeclaimtemplate
```

A user can solve it by adding `emptyDir{}` for the workspace in the `TaskRun`

Example:

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: tr
spec:
  taskRef:
    name: task
  workspaces:
  - name: task-ws
    emptyDir: {}
```

# Proposed solution

For a `TaskRun` an `emptyDir{}` is almost always possbile to use in most clusters (as what I know) and it is a fair use case, _if the workspace is used for passing files between steps_

However, for `PipelineRun` an `emptyDir{}` is less useful as a workspace since it is combined of multiple pods.

Providing an `emptyDir{}` volume as default was [suggested](https://github.com/tektoncd/pipeline/issues/1986#issuecomment-604971446) in the discussion about "Auto workspace"

When e.g. debugging a task in an existing pipeline, this is a useful, quick way to run a task.
