### ISSUE TITLE
git basic authentication fail

### ISSUE THREAD

**Issue by r0bj** [tektoncd/pipeline#2409]
# Expected Behavior

Tekton generates valid `/tekton/home/.git-credentials` file and git basic authentication works.

# Actual Behavior

Tekton generates invalid `/tekton/home/.git-credentials` file and git basic authentication fails.

# Steps to Reproduce the Problem

taskrun.yaml:
```
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-test
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/basic-auth
stringData:
  username: user
  password: seecretpass

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-image-test
secrets:
- name: basic-auth-test

---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test
spec:
  serviceAccountName: build-image-test
  taskSpec:
    steps:
    - name: test
      image: alpine
      script: |
        cat /tekton/home/.git-credentials
```

output:
```
+ cat /tekton/home/.git-credentials
//user:seecretpass@github.com
```

Note: instead of proper line:
```
https//user:seecretpass@github.com
```
there is:
```
//user:seecretpass@github.com
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
Client version: 0.8.0
Pipeline version: v0.11.1
```
