### ISSUE TITLE
Memory requirement increase for the same pipeline using beta

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/pipeline#2417]
# Expected Behavior
I shouldn't be requiring so much more memory for the same Tekton Pipeline - in my case I had to both expand my cluster's memory settings (from 2 GB to 12 GB) and introduce LimitRange

Update: see my post involving the Prometheus graphs, the increase isn't so big as I figured actually, and in my case using the LimitRanges wasn't helpful

# Actual Behavior
As part of https://github.com/tektoncd/dashboard/pull/1265#issuecomment-614719583 I noticed consistent out of memory problems running the `webpack` stage of our release pipeline used to publish the Tekton Dashboard

I had a 2 GB Docker Desktop cluster at the time, with no LimitRange set

I then added a LimitRange trying 1 GB limits, 1.5 GB limits, and then 2 GB limits - all but the 2 GB limit settings resulted in the same out of memory problems, requiring me to expand my cluster memory allocation limit to 12 GB

Here are my LimitRange settings when it worked - lemme know if I'm doing something crazy here because I'd love to be wrong! 

With 1.5Gi for every `memory` mention, or `1Gi`, my Task went OoM (so specifically you get an error 137 from the above mentioned webpack command used in a step).

```
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
  - max:
      cpu: "800m"
      memory: "2Gi"
    min:
      cpu: "100m"
      memory: "2Gi"
    default:
      cpu: "700m"
      memory: "2Gi"
    defaultRequest:
      cpu: "110m"
      memory: "2Gi"
    type: Container
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dashboard-release
spec:
  params:
    - name: package
      description: package to release
      default: github.com/tektoncd/dashboard
    - name: imageRegistry
      default: gcr.io/tekton-releases
    - name: versionTag
      description: The X.Y.Z version that the artifacts should be tagged with
    - name: bucketName
      description: The name of the bucket to use
  resources:
    - name: dashboard-source-repo
      type: git
    - name: bucket-for-dashboard
      type: storage
    - name: builtDashboardImage
      type: image
  tasks:
    - name: build
      taskRef:
        name: build-tekton-dashboard
      resources:
        inputs:
          - name: dashboard-source-repo
            resource: dashboard-source-repo
        outputs:
          - name: dashboard-source-repo
            resource: dashboard-source-repo
    - name: publish-images
      runAfter: [build]
      taskRef:
        name: publish-tekton-dashboard
      params:
        - name: pathToProject
          value: $(params.package)
        - name: versionTag
          value: $(params.versionTag)
        - name: imageRegistry
          value: $(params.imageRegistry)
        - name: bucketName
          value: $(params.bucketName)
      resources:
        inputs:
          - name: dashboard-source-repo
            resource: dashboard-source-repo
            from: [build]
          - name: bucket-for-dashboard
            resource: bucket-for-dashboard
        outputs:
          - name: bucket-for-dashboard
            resource: bucket-for-dashboard
          - name: builtDashboardImage
            resource: builtDashboardImage
```

# Steps to Reproduce the Problem

1. Run the Tekton Dashboard release process using the existing (checked in) v1alpha1 based pipeline (done by applying the `tekton` folder and following the readme in there). Observe no failing build.
2. Reset your Kubernetes cluster so you can apply v1beta1 of Tekton Pipelines
3. Apply the PR from @AlanGreene (https://github.com/tektoncd/dashboard/pull/1265) - which switches to using v1beta1 resources

# Additional Info

- Kubernetes version:
1.15.5

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

Between 0.10.1 and 0.11.1

🤞 it's just me, otherwise the increase is huuuge!

**Comment by vdemeester** [comment]
One "guess" might be the entrypoint "logging" methods.. maybe ?
Looking at the [changes](https://github.com/tektoncd/pipeline/compare/v0.10.2...v0.11.1), the only change related to the entrypoint is https://github.com/tektoncd/pipeline/commit/d7820215df7132b168c84a3b03a586f079eb098e#diff-4dbf8b042dd60907e07ee142e3c31b40

/kind bug

**Comment by danielhelfand** [comment]
Just wanted to add here that specifying a LimitRange minimum for containers applies that much memory to each container part of a TaskRun/entire PipelineRun. So that is most likely the cause. Would it perhaps make more sense to not specify a minimum? 

In that case, the max memory values for CPU, storage, and memory specified by a container would be the total amount of memory specified and then utilized by each containers as part of TaskRun. 

So maybe try specifying resources to allocate directly on the step defined via your Task.

**Comment by a-roberts** [comment]
> Just wanted to add here that specifying a LimitRange minimum for containers applies that much memory to each container part of a TaskRun/entire PipelineRun. So that is most likely the cause. Would it perhaps make more sense to not specify a minimum?
> 
> In that case, the max memory values for CPU, storage, and memory specified by a container would be the total amount of memory specified and then utilized by each containers as part of TaskRun.
> 
> So maybe try specifying resources to allocate directly on the step defined via your Task.

Yeah definitely, and I'm gonna play with the numbers some more today, I bet I can narrow it down to just needing 2 GB max for the one container and not however much the default was so I can add more information here then (so perhaps it's gone from needing a maximum of 1 GB to 2 GB, while that's a 2x jump at least it wouldn't be 6x!). Thanks for the suggestion

**Comment by a-roberts** [comment]
Done another experiment that's a little more fine-grained.

So I set my max amount as per @danielhelfand's suggestion to 2 GB, instead of 1 GB, LimitRange now resembles:

```
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
  - max:
      cpu: "800m"
      memory: "2Gi"
    min:
      cpu: "100m"
      memory: "1Gi"
    default:
      cpu: "700m"
      memory: "1Gi"
    defaultRequest:
      cpu: "110m"
      memory: "1Gi"
    type: Container
---
```


I get the same out of memory problem though, I'm wondering if it's not growing in time - if this worked I planned to then start shifting the memory amount lower and lower to see what the threshold is. 

For not setting minimums, I first had to delete my existing Tekton resources (kinda weird, so `kubectl delete` on my `tekton` resources folder), then I applied this and ran my Pipeline again:

```
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
  - max:
      cpu: "800m"
      memory: "2Gi"
    type: Container
```

I spotted something watching `docker stats`

```
...        k8s_step-build-static_dashboard-release-run-5s92f-build-82hxr-pod-wzxpl_default_c87243b2-c8f2-4804-9ad0-61c67e0166aa_0                              89.88%              496.5MiB / 2GiB       24.24%              0B / 0B             0B / 0B             73
```

this keeps growing at a rate of 3 MB per second, It's the `npm ci` step in our Task.

It becomes

```
...   k8s_step-build-static_dashboard-release-run-5s92f-build-82hxr-pod-wzxpl_default_c87243b2-c8f2-4804-9ad0-61c67e0166aa_0                              90.51%              595.5MiB / 2GiB       29.08% 
```

then stabilises and completes at
```
... k8s_step-build-static_dashboard-release-run-5s92f-build-82hxr-pod-wzxpl_default_c87243b2-c8f2-4804-9ad0-61c67e0166aa_0                              85.21%              670.1MiB / 2GiB       32.72%  
```

This appears in the Task's output:

```
[build : build-static] (node:319) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
```

and then job fails due to a `missing script` problem, when it is defined in our `package.json`:

```
[build : build-static] npm ERR! missing script: bootstrap:ci
[build : build-static] npm ERR! 
[build : build-static] npm ERR! Did you mean this?
[build : build-static] npm ERR!     bootstrap
[build : build-static] 
```

I think for our case (the release pipeline) I need to chat with @AlanGreene about what's happening here. 

For this particular issue from a pure Tekton Pipelines perspective, I'm wondering what a simpler test case would be and if we'd benefit from something like `kubectl top` with heapster installed, just using `docker stats` is too crude by the looks of it.
