### ISSUE TITLE
TaskRuns Part of a PipelineRun Do Not Have Condition Name as Part of PipelineRun.Status.TaskRuns 

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/pipeline#2419]
This issue was originally opened in the CLI repo: https://github.com/tektoncd/cli/issues/882

When TaskRuns have conditions, the name of the condition becomes part of the TaskRun name. However, it appears that TaskRuns stored as part of the list of TaskRuns under PipelineRun.Status.TaskRuns don't have the condition name as part of the TaskRun name.

In the case of the CLI, this causes a panic for the `tkn pipelinerun describe` command as documented in the issue above. This occurs because the CLI uses the following to get TaskRuns from a PipelineRun object: https://github.com/tektoncd/cli/blob/5055993a3d3664440d68cf6e049d117fea1b130d/pkg/pipelinerun/description/description.go#L146

Debugging the scenario above with the CLI, what I found is that a TaskRun is created with a condition that fails and has the following name: `hello-hello-third-hello-4lm88-do-extra-hello-74dhm`

The TaskRun returned using a `tkn pr desc` command is named: `hello-hello-third-hello-4lm88`. This causes the TaskRun returned to have no status, which then causes the panic.

This is confirmed via doing a `kubectl describe` on the PipelineRun:

```yaml
Name:         hello-hello
Namespace:    default
Labels:       tekton.dev/pipeline=hello-hello
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{},"name":"hello-hello","namespace":"default"},"spec":{"par...
API Version:  tekton.dev/v1beta1
Kind:         PipelineRun
Metadata:
  Creation Timestamp:  2020-04-16T15:32:52Z
  Generation:          1
  Resource Version:    20574
  Self Link:           /apis/tekton.dev/v1beta1/namespaces/default/pipelineruns/hello-hello
  UID:                 dd37f21c-8e71-4566-aabf-f52859be4ea0
Spec:
  Params:
    Name:   first-hello
    Value:  asdf
    Name:   second-hello
    Value:  zxcv
    Name:   do-extra-hello
    Value:  true
  Pipeline Ref:
    Name:   hello-hello
  Timeout:  1h0m0s
Status:
  Completion Time:  2020-04-16T15:32:59Z
  Conditions:
    Last Transition Time:  2020-04-16T15:32:57Z
    Message:               TaskRun hello-hello-pause-after-first-22c2m has failed
    Reason:                Failed
    Status:                False
    Type:                  Succeeded
  Start Time:              2020-04-16T15:32:52Z
  Task Runs:
    Hello - Hello - First - Hello - G 4 Hvw:
      Pipeline Task Name:  first-hello
      Status:
        Completion Time:  2020-04-16T15:32:55Z
        Conditions:
          Last Transition Time:  2020-04-16T15:32:55Z
          Message:               All Steps have completed executing
          Reason:                Succeeded
          Status:                True
          Type:                  Succeeded
        Pod Name:                hello-hello-first-hello-g4hvw-pod-r467b
        Start Time:              2020-04-16T15:32:52Z
        Steps:
          Container:  step-echo
          Image ID:   docker-pullable://debian@sha256:1b8a66f829a3563f98f941f4e0e2ecc619ad12f22331d297d2a9d1e2f18dc257
          Name:       echo
          Terminated:
            Container ID:  docker://6006589b11d32a82fa0455ac624af7f488e371d35583f686f27ed38aea2aac7a
            Exit Code:     0
            Finished At:   2020-04-16T15:32:54Z
            Reason:        Completed
            Started At:    2020-04-16T15:32:54Z
    Hello - Hello - Pause - After - First - 22 C 2 M:
      Pipeline Task Name:  pause-after-first
      Status:
        Completion Time:  2020-04-16T15:32:57Z
        Conditions:
          Last Transition Time:  2020-04-16T15:32:57Z
          Message:               "step-sleep" exited with code 1 (image: "docker-pullable://debian@sha256:1b8a66f829a3563f98f941f4e0e2ecc619ad12f22331d297d2a9d1e2f18dc257"); for logs run: kubectl -n default logs hello-hello-pause-after-first-22c2m-pod-v5wdp -c step-sleep
          Reason:                Failed
          Status:                False
          Type:                  Succeeded
        Pod Name:                hello-hello-pause-after-first-22c2m-pod-v5wdp
        Start Time:              2020-04-16T15:32:52Z
        Steps:
          Container:  step-echo
          Image ID:   docker-pullable://debian@sha256:1b8a66f829a3563f98f941f4e0e2ecc619ad12f22331d297d2a9d1e2f18dc257
          Name:       echo
          Terminated:
            Container ID:  docker://488c859e589c5aea5e2314e5e8781aba6201129ecfe09c2453029d91d8820b33
            Exit Code:     0
            Finished At:   2020-04-16T15:32:56Z
            Reason:        Completed
            Started At:    2020-04-16T15:32:56Z
          Container:       step-sleep
          Image ID:        docker-pullable://debian@sha256:1b8a66f829a3563f98f941f4e0e2ecc619ad12f22331d297d2a9d1e2f18dc257
          Name:            sleep
          Terminated:
            Container ID:  docker://cb6d7efbbe36bfaea09f7f57b69eb224d85cc3f26c0db3d25095837105d8a6bf
            Exit Code:     1
            Finished At:   2020-04-16T15:32:56Z
            Reason:        Error
            Started At:    2020-04-16T15:32:56Z
    Hello - Hello - Second - Hello - Qlzdg:
      Pipeline Task Name:  second-hello
      Status:
        Completion Time:  2020-04-16T15:32:59Z
        Conditions:
          Last Transition Time:  2020-04-16T15:32:59Z
          Message:               All Steps have completed executing
          Reason:                Succeeded
          Status:                True
          Type:                  Succeeded
        Pod Name:                hello-hello-second-hello-qlzdg-pod-6pmtt
        Start Time:              2020-04-16T15:32:55Z
        Steps:
          Container:  step-echo
          Image ID:   docker-pullable://debian@sha256:1b8a66f829a3563f98f941f4e0e2ecc619ad12f22331d297d2a9d1e2f18dc257
          Name:       echo
          Terminated:
            Container ID:  docker://3ce2234817b11dcd4456555578e678aee312ea63a6543db078e47d05529da222
            Exit Code:     0
            Finished At:   2020-04-16T15:32:58Z
            Reason:        Completed
            Started At:    2020-04-16T15:32:58Z
    Hello - Hello - Third - Hello - 4 Lm 88:
      Condition Checks:
        Hello - Hello - Third - Hello - 4 Lm 88 - Do - Extra - Hello - 74 Dhm:
          Condition Name:  do-extra-hello
          Status:
            Check:
              Waiting:
                Reason:  PodInitializing
            Conditions:
              Last Transition Time:  2020-04-16T15:32:57Z
              Message:               pod status "Initialized":"False"; message: "containers with incomplete status: [place-tools]"
              Reason:                Pending
              Status:                Unknown
              Type:                  Succeeded
            Pod Name:                hello-hello-third-hello-4lm88-do-extra-hello-74dhm-pod-wjm2s
            Start Time:              2020-04-16T15:32:55Z
      Pipeline Task Name:            third-hello
Events: 
```

However, the TaskRun is actually named as follows and shown via a `kubectl describe`:

```yaml
Name:         hello-hello-third-hello-4lm88-do-extra-hello-74dhm
Namespace:    default
Labels:       app.kubernetes.io/managed-by=tekton-pipelines
              tekton.dev/conditionCheck=hello-hello-third-hello-4lm88-do-extra-hello-74dhm
              tekton.dev/pipeline=hello-hello
              tekton.dev/pipelineRun=hello-hello
              tekton.dev/pipelineTask=third-hello
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{},"name":"hello-hello","namespace":"default"},"spec":{"par...
API Version:  tekton.dev/v1beta1
Kind:         TaskRun
Metadata:
  Creation Timestamp:  2020-04-16T15:32:55Z
  Generation:          1
  Owner References:
    API Version:           tekton.dev/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  PipelineRun
    Name:                  hello-hello
    UID:                   dd37f21c-8e71-4566-aabf-f52859be4ea0
  Resource Version:        20586
  Self Link:               /apis/tekton.dev/v1beta1/namespaces/default/taskruns/hello-hello-third-hello-4lm88-do-extra-hello-74dhm
  UID:                     8b40299d-a096-4fed-b3cd-73c093ab1540
Spec:
  Params:
    Name:   do-extra-hello
    Value:  true
  Resources:
  Service Account Name:  
  Task Spec:
    Params:
      Name:  do-extra-hello
      Type:  string
    Steps:
      Image:  debian:buster-slim
      Name:   condition-check-do-extra-hello
      Resources:
      Script:  [ "$(inputs.params.do-extra-hello)" = "true" ]
  Timeout:     1h0m0s
Status:
  Completion Time:  2020-04-16T15:33:02Z
  Conditions:
    Last Transition Time:  2020-04-16T15:33:02Z
    Message:               All Steps have completed executing
    Reason:                Succeeded
    Status:                True
    Type:                  Succeeded
  Pod Name:                hello-hello-third-hello-4lm88-do-extra-hello-74dhm-pod-wjm2s
  Start Time:              2020-04-16T15:32:55Z
  Steps:
    Container:  step-condition-check-do-extra-hello
    Image ID:   docker-pullable://debian@sha256:1b8a66f829a3563f98f941f4e0e2ecc619ad12f22331d297d2a9d1e2f18dc257
    Name:       condition-check-do-extra-hello
    Terminated:
      Container ID:  docker://87e27db72cec3512d1a441043d345b4ddcf143ce2765b3065f1b439606ef1e4d
      Exit Code:     0
      Finished At:   2020-04-16T15:33:01Z
      Reason:        Completed
      Started At:    2020-04-16T15:33:01Z
Events:              <none>
```

# Steps to Reproduce the Problem

1. Follow the scenario outlined in https://github.com/tektoncd/cli/issues/882

# Additional Info

- Kubernetes version:

```
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.8.0
Pipeline version: v0.11.1
```
