### ISSUE TITLE
One too many in resource in Task resources inputs - tutorial?

### ISSUE THREAD

**Issue by JCzz** [tektoncd/pipeline#2439]
In this [tutorial](https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#configuring-pipeline-execution-credentials)

Is there not one too many inputs in this "Task" for deployment. logically there should not be any git in this task - still learning so I am probably wrong but check this:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-using-kubectl
spec:
  params:
    - name: path
      type: string
      description: Path to the manifest to apply
    - name: yamlPathToImage
      type: string
      description: |
        The path to the image to replace in the yaml manifest (arg to yq)
  resources:
    inputs:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - name: replace-image
      image: mikefarah/yq
      command: ["yq"]
      args:
        - "w"
        - "-i"
        - "$(params.path)"
        - "$(params.yamlPathToImage)"
        - "$(resources.inputs.image.url)"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(params.path)"
```

To me there should not be any:
```

    inputs:
      - name: source
        type: git
```

But only:
```
    inputs:
      - name: image
        type: image
```
