### ISSUE TITLE
How to pass a variable/parameter from PipelineRun to Pipeline

### ISSUE THREAD

**Issue by vikas027** [tektoncd/pipeline#2442]
# Expected Behavior
`PipelineRun` parameter `myimagetag ` should be passed to `Pipeline`

# Actual Behavior
`PipelineRun` parameter `myimagetag ` does not pass to `Pipeline`, the default value of latest is used instead

# Steps to Reproduce the Problem
Apply the below yaml after creating other resources

```yaml
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-build-push-docker-image
spec:
  serviceAccountName: pipeline-sa
  pipelineRef:
    name: pipeline-build-push-docker-image
  params:
  - name: image-tag
    value: myimagetag
  resources:
  - name: source-repo
    resourceRef:
      name: git
  - name: image-name
    resourceRef:
      name: image

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-push-docker-image
spec:
  params:
    - name: imageTag
      description: Tag to apply to the built image
      default: latest # this gets passed to the task, I want to pass myimagetag (from Pipelinerun)

  resources:
  - name: source-repo
    type: git
  - name: image-name
    type: image

  tasks:
  - name: build-push-image
    taskRef:
      name: task-build-push
    params:
    - name: imageTag
      value: $(params.imageTag)
    resources:
      inputs:
      - name: workspace
        resource: source-repo
      outputs:
      - name: builtImage
        resource: image-name
```

# Additional Info

- Kubernetes version:

```
🍺 ~ $ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
🍺 ~ $
```

- Tekton Pipeline version:

```
🍺 ~ $ tkn version
Client version: 0.8.0
Pipeline version: v0.11.2
🍺 ~ $
```

**Comment by bobcatfish** [comment]
( @vikas027 i changed the wording in the issue a bit based on the comment in your example! )

**Comment by bobcatfish** [comment]
@vikas027 in your example it looks like the name of the parameter in the pipelinerun doesn't quite match the pipeline (i'm wondering if this isnt exactly what you're running though since validation should catch this?)

In your pipelinerun:

```
  params:
  - name: image-tag
    value: myimagetag
```

In your Pipeline:
```
  params:
    - name: imageTag
      description: Tag to apply to the built image
      default: latest
```

In your pipeline you would need to pass a variable called `imageTag` instead of `image-tag`
