### ISSUE TITLE
Design: "Finally" Steps in Tasks

### ISSUE THREAD

**Issue by chhsia0** [tektoncd/pipeline#2448]
Related issue: #1559

# Motivating Use Cases

* A unit test step fails but a subsequent step in the same Task should upload the results to a bucket regardless of that failure.
* A Pull Request pipeline resource should update a PR with a comment reflecting the status of a failed build. The build happens in one step and then the PR resource could inject a step at the end which runs regardless of the error and knows how to update github/gitlab/etc with the status comment.

# Proposed User-Facing Changes

Add a new `Finally` field to specify a list of sequential steps that run regardless of whether previous steps have succeeded or not. Example:
```
kind: Task
metadata:
  name: hello-world-finally-steps
spec:
  steps:
  - name: hello
    image: busybox
    command: ["echo", "hello"]
  - name: fail
    image: busybox
    command: ["false"]
  finally:
  - name: world
    image: busybox
    command: ["echo", "world"]
```

# Design Doc

https://docs.google.com/document/d/1e1fagYDErliLnIwU1g_N3YKVyAProhs1l14UyPIoZuM/edit?usp=sharing

# Alternative Design

Error Strategy in Task Steps (#1573)

**Comment by dibyom** [comment]
/kind feature
/area api

Also related to #1684

**Comment by NikeNano** [comment]
The [design doc](https://docs.google.com/document/d/1e1fagYDErliLnIwU1g_N3YKVyAProhs1l14UyPIoZuM/edit?usp=sharing). Is behind restricted access :( Should I apply for access through the google docs link or should the document be made public @dibyom?

**Comment by bobcatfish** [comment]
Hi @NikeNano ! Joining our mailing list should give you access: https://github.com/tektoncd/community/blob/master/contact.md#mailing-list

**Comment by NikeNano** [comment]
Thanks @bobcatfish :)

**Comment by afrittoli** [comment]
@chhsia0 Are you still looking into this?

This may be rendered unnecessary by the pipeline resource redesign. If you feel this is high prio still feel free to bring it back at the API WG

**Comment by jerop** [comment]
The use cases described here could be better solved using [Pipelines in Pipelines](https://github.com/tektoncd/community/issues/330) because it:
- allows us to reuse Finally Tasks instead of introducing Finally Steps
- encourages writing Tasks with singular concerns then allowing them to be composed together as a unit of execution

> * A unit test step fails but a subsequent step in the same Task should upload the results to a bucket regardless of that failure.

This use case can be solved using a `unit-test-and-upload` Pipeline which has a `unit-test` Task and a `upload` Finally Task, and the `unit-test-and-upload` Pipeline is passed in as a Task in the main Pipeline

```yaml 
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: unit-test-and-upload
spec:
  tasks:
    - name: unit-test
      taskRef:
        name: unit-test
  finally:  
    - name: upload
      taskRef:
        name: upload

---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: unit-test-and-upload
      taskRef:
        apiVersion: tekton.dev/v1beta1
        kind: Pipeline
        name: unit-test-and-upload
... 
```

> * A Pull Request pipeline resource should update a PR with a comment reflecting the status of a failed build. The build happens in one step and then the PR resource could inject a step at the end which runs regardless of the error and knows how to update github/gitlab/etc with the status comment.

This use case can be solved using a `build-and-notify` Pipeline which has a `build` Task and a guarded `notify` Finally Task, and the `build-and-notify` Pipeline is passed in as a Task in the main Pipeline

```yaml 
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-notify
spec:
  tasks:
    - name: build
      taskRef:
        name: build
  finally:  
    - name: notify
      when:
        - input: $(tasks.build.status)
          operator: in
          values: [ "Failed" ] 
      taskRef:
        name: notify

---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: build-and-notify
      taskRef:
        apiVersion: tekton.dev/v1beta1
        kind: Pipeline
        name: build-and-notify
... 
```

So I propose going forward with Pipelines in Pipelines to solve these use cases, and this still leaves Finally Steps as an option we can explore in the future if needed, please let me know what you think @chhsia0 

/cc @ImJasonH @pritidesai @bobcatfish @afrittoli
