### ISSUE TITLE
Doc: Specifying execution Conditions - where is "conditionRef: my-condition"

### ISSUE THREAD

**Issue by JCzz** [tektoncd/pipeline#2449]
In this: https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#specifying-execution-conditions

```
tasks:
  - name: conditional-task
    taskRef:
      name: build-push
    conditions:
      - conditionRef: my-condition
        params:
          - name: my-param
            value: my-value
        resources:
          - name: workspace
            resource: source-repo
```

Where is my-condition `conditionRef: my-condition`?
