### ISSUE TITLE
There are multiple items in "Taskrun.status.taskResults"

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#2466]
# Expected Behavior
 Correct display the `result` item one by one and unique.
# Actual Behavior
With multiple items.
# Steps to Reproduce the Problem
Apply https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/taskruns/task-result.yaml

Like this:
```
  taskResults:
  - name: current-date-human-readable
    value: |
      Wed Apr 22 03:27:57 UTC 2020
  - name: current-date-unix-timestamp
    value: |
      1587526077
  - name: current-date-unix-timestamp
    value: |
      1587526077
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- Tekton Pipeline version:
master

I checked the code, we parse `result` from `terminated.message` one by one from `pod.containerStatuses` 
1. but without sort. That will cause problem if more than one `step` modify the same `result`.
2. Not check duplicate, that's why multiple appear.
