### ISSUE TITLE
Task Steps with Knative Service definition

### ISSUE THREAD

**Issue by brindasanth** [tektoncd/pipeline#2476]
Team,

I see Task -> Steps have containers, This will create new container for each request.

How do I point to existing Knative services, send request and wait for response completion ?
By this I can reuse the available services, avoid latency ( Starting up and Destroying of containers).

This will open up lot of use cases achieved with tektoncd.

**Comment by dibyom** [comment]
> I see Task -> Steps have containers, This will create new container for each request.

This is by design since for most CI/CD use cases (building/testing) the latency of spinning up a new Pod is little compared to to the time it takes to run the build/test.

> How do I point to existing Knative services, send request and wait for response completion ?

If you have an existing Knative service, you should be able to hit it directly....not sure how Tekton is involved here. Could you describe your use case in more detail?

**Comment by brindasanth** [comment]
We have Software Defined Network (SDN) automation process, which has sequenced of tasks, i.e mix and match of using Serverless functions and already hosted Knative/fixed scaled services. We are trying to reuse Tektoncd Pipeline runner / Argo workflow for that. For me TekonCD is getting popular, cloud native and it achieves the purpose we need. but always launching new containers for specific scenerio is not affordable with respect to latency in network automations.

**Comment by brindasanth** [comment]
Adding to the point, It will simplify pipeline and task definitions with only input parameters and service endpoint definitions, no need to configure other things such as mounts etc. Because that can be handled in service container spec definitions one time.

**Comment by vincent-pli** [comment]
@brindasanth 
So, do you expect the existing KSVC as a step of your `Pipeline` or just want to invoke and get replay from your step to the KSVC?

**Comment by brindasanth** [comment]
I just want to invoke KSCV with defined input parameters on that task and wait for response, so that it can kick on next tasks in pipeline with that task output.

Example flow:
[Knative Service Task]  -> [Build task]  ->[Knative Service Task] ->[Server less function Task] -> [END]

**Comment by vincent-pli** [comment]
@brindasanth 
I guess we need add `cloudevent` send/receive stuff to https://github.com/tektoncd/catalog

**Comment by sbwsg** [comment]
There has been a fair amount of abstract discussion about removing Pods / Containers backing Tasks  See https://github.com/tektoncd/pipeline/issues/215 for the earliest suggestion of this idea (that I can find).

@ImJasonH has definitely had thoughts around this and made moves to reduce Tekton's reliance on Pods / Kubernetes-isms as well: https://github.com/tektoncd/pipeline/issues/1689 

On the other hand we've had requests to actually increase the "kubernetes-ness" too: https://github.com/tektoncd/pipeline/issues/2327

Essentially I think there are _ideas_ around this but very little actual concrete work.  Tasks are backed by Pods and Steps are Containers and that's just how it works right now.  Would love to see more concrete design, proposal and implementation around this area though.

**Comment by brindasanth** [comment]
Knative  Container Source already uses the sink concept. for one way communication. I think, we shall have sink in task definitions as below. Some time injectable custom task implementation will solve the issue.
```
apiVersion: sources.knative.dev/v1alpha2
kind: ContainerSource
metadata:
  name: test-heartbeats
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
      url : /xxx/xxx
```

would be:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: example-task-name
spec:
  params:
    - input: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: /workspace/workspace/Dockerfile
    - output: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: /workspace/workspace/Dockerfile
  steps:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
      url : /xxx/xxx
```
