### ISSUE TITLE
Feature discussion - `tkn pipeline resolve` mode that works like `ko resolve`

### ISSUE THREAD

**Issue by cameronbraid** [tektoncd/pipeline#2493]
I have recently discovered ko and I think the idea of piping my yaml through `ko resolve` before applying it to the cluster is a great idea.

I think the same idea could be implemented by tkn where the URL of the image defines enough metadata to identify a pipeline to run.

e.g. tkn://staging-ns/nodejs-pipeline?version=1.2.3

tkn would trigger the pipelines to run, wait until complete, extract the built image url and replace it into the yaml.

Some things that would need to be thought through

- always be strict and expect a url prefix like tkn://. ?
- what would the url look like ?
- how would additional things like workspace bindings work ?
- would need a standard output name for the built image tag to replace in the yaml

Would introducing a new CRD PartialPipelineRun solve some of the above ?  The idea here is to support all the fields of a PipelineRun but allowing any of them to be overriden - therefore its easy to implement workspace binding, param defaults etc..  then the tkn:// url could point to the namespace/partialName and pass params as query string arg. tkn://staging/nodejsWebApp?version=1.2.3 

e.g.

```
apiVersion: tekton.dev/v1beta1
kind: PartialPipelineRun
metadata:
  namespace: staging
  name: nodejsWebApp
spec:
  serviceAccountName: tekton-builder

  pipelineRef:
    name: docker-build

  workspaces:
    
  - name: src
    volumeClaimTemplate:
    spec:
      storageClassName: ephemeral-ssd
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

```

would be submitted to tkn as 

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: staging
  name: nodejsWebApp-hfih4d
spec:
  serviceAccountName: tekton-builder

  pipelineRef:
    name: docker-build

  workspaces:
    
  - name: src
    volumeClaimTemplate:
    spec:
      storageClassName: ephemeral-ssd
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  params:
     - name: version
        value: 1.2.3
```

**Comment by ImJasonH** [comment]
Cool idea! 

This might be worth prototyping out first to get hands-on feel for how it works. It should be relatively straightforward to write a separate CLI to achieve that, then if it's compelling and we decide we'd like to support it we can forklift it into tkn. We'd also probably need a more thorough design doc, but that can happen after a prototype/demo.

Let me know if you need any help, or pointers to code. `ko resolve` walks the YAML looking for strings that are valid importpaths or start with ko://, so only supporting tkn:// actually makes things quite a bit simpler.

**Comment by ImJasonH** [comment]
@mattmoor in case he has any ideas or feedback

**Comment by cameronbraid** [comment]
I thin at a minimum the image repo and tag will needed to be provided up front so see if the image already exists and if so, just extract the sha - ,otherwise each time resolve is run the pipeline will be run :(

So two ideas come to mind

a) image repo based 

`tkn://harbor-dev.drivenow.com.au/project/image:tag?pipeline=pipelinename&param1=yyy`

`tkn://harbor-dev.drivenow.com.au/project/image:tag?pipeline=namespace/pipelinename&param1=yyy`

b) pipeline namespace/name based

`tkn://namespace/pipelinename?param1=yyy#registry/user/project:tag`

in either case the repo and tag can be auto converted into pipeline params as well to avoid specifying them twice

i.e. 
image_repo=registry/user/project
image_tag=tag

and these could be bound to PipelinRun params if the pipeline defines them

then for a typical build (given the partial example above) where the image tag matches the git ref you can do

`tkn://drivenow-build/nodejsWebApp#harbor-dev.drivenow.com.au/drivenow/nodejsWebApp:1.2.3`

to generate
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: drivenow-build
  name: nodejsWebApp-hfih4d
spec:
  serviceAccountName: tekton-builder

  pipelineRef:
    name: docker-build

  workspaces:
    
  - name: src
    volumeClaimTemplate:
    spec:
      storageClassName: ephemeral-ssd
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  params:
     - name: image_tag
        value: 1.2.3
```

then the pipeline will checkout from git ref 1.2.3
