### ISSUE TITLE
Git PipelineResource fails when disable-home-env-overwrite=true and UID is non-zero

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2523]
# Expected Behavior

When `disable-home-env-overwrite` is "true" and UID is non-zero PipelineResources should continue to operate just as well as when UID is 0.

# Actual Behavior

PipelineResources fail copying credentials.  This happens because:

1. HOME is no longer `/tekton/home` (because feature flag).
2. PipelineResources don't have any HOME fallback.
3. So PipelineResources try to copy creds from `/tekton/creds` into `/`
    - more accurately, the entrypointer does this but it happens in PipelineResource injected steps.
4. UID is non-zero, non-root. Copying into `/` fails.  This is actually a non-fatal error but...
5. Git PipelineResource fails to lock `//.gitconfig`. This is a fatal error.  Task dies.

# Steps to Reproduce the Problem

Set `disable-home-env-overwrite` feature flag to "true". Redeploy tekton.  Apply taskrun:

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test
spec:
  resources:
    inputs:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/tektoncd/pipeline
  taskSpec:
    resources:
      inputs:
      - name: source
        type: git
    steps:
    - name: check-dirs
      image: ubuntu
      env:
      - name: HOME
        value: /workspace
      script: |
        # This script is never reached. TaskRun dies in PipelineResource injected steps.
        id
        echo $HOME
  podTemplate:
    securityContext:
      runAsUser: 1111
      runAsGroup: 2222
      fsGroup: 3333
```

See non-fatal error in logs.  Example: `unsuccessful cred copy: ".ssh" from "/tekton/creds" to "/": unable to create destination directory: mkdir /.ssh: permission denied`

See fatal error in logs: `"msg":"Error running git [config --global http.sslVerify true]: exit status 255\nerror: could not lock config file //.gitconfig: Permission denied\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:82\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:203"`

# Additional Info

Originally discussed here: https://github.com/tektoncd/pipeline/issues/2165
