### ISSUE TITLE
Steps can't use creds-init credentials when their UID is different from creds-init UID and disable-home-env-overwrite=true

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2524]
# Expected Behavior

When a Step has its own non-root `UID` which is different from `creds-init` any credentials should still be usable by that Step.

# Actual Behavior

The Step will fail to utilize credentials.

When `disable-home-env-overwrite` is "true" the Step's `entrypointer` tries to copy credentials out of `/tekton/creds` into `$HOME`.  But the UID of the Step is different from `creds-init`.  The files inside of `/tekton/creds` are owned by whatever user `creds-init` ran as.  The Step is disallowed from reading those files as it tries to copy them out.

# Steps to Reproduce the Problem

Set `disable-home-env-overwrite` feature flag to "true". Redeploy tekton. Apply taskrun:

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test
spec:
  taskSpec:
    steps:
    - name: check-dirs
      image: ubuntu
      env:
      - name: HOME
        value: /myhome
      securityContext:
        runAsUser: 1111
        runAsGroup: 2222
      script: |
        id
        echo $HOME
        ls -lahR /tekton/creds
```

See errors in step logs.  Example: `unsuccessful cred copy: ".ssh" from "/tekton/creds" to "/workspace": unable to open source: open /tekton/creds/.ssh/known_hosts: permission denied`

# Additional Info

Originally discussed here: https://github.com/tektoncd/pipeline/issues/2165
