### ISSUE TITLE
Add support for defining Task-wide environment variables

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#254]
## Expected Behavior

In some triggering systems (e.g. Jenkins X) a lot of contextual information is provided via environment variables, for example:

```yaml
    env:
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
    - name: TILLER_NAMESPACE
      value: kube-system
    - name: DOCKER_CONFIG
      value: /home/jenkins/.docker/
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    - name: XDG_CONFIG_HOME
      value: /home/jenkins
    - name: _JAVA_OPTIONS
      value: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true
        -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4
        -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
    - name: PIPELINE_KIND
      value: release
    - name: REPO_OWNER
      value: abayer
    - name: REPO_NAME
      value: jx-demo-qs
    - name: JOB_NAME
      value: abayer/jx-demo-qs/master
    - name: BRANCH_NAME
      value: master
    - name: JX_BATCH_MODE
      value: "true"
```

It should be possible to provide all of this information to a PipelineRun and all Tasks ( / TaskRuns) and all of their steps that are invoked by a triggering system that wants to provide this information.

## Actual Behavior

Environment variables can only be defined per step, which means that every single step of every single Task that is invoked needs to be explicitly provided with these values.

## Additional Info

This is a fine line we tread! If we make global environment variables, then users can use these variables inside of their containers and we will have no idea what they are using and what they aren't.

On the other hand, if we don't, things can become painfully verbose.

:thinking:
