### ISSUE TITLE
Idea: Tekton Generators

### ISSUE THREAD

**Issue by wlynch** [tektoncd/pipeline#2590]
/kind feature
/kind design

Creating in pipelines, since I think this is more of a discussion on our approach to Pipeline and Task configuration.

# Problem

Currently it's not an easy for users to bootstrap common workflows. e.g. "run a simple build and test workflow on this GitHub repo".

# Feedback I'm looking for

- Is this a good/useful idea?
- How else (if at all) can we encourage users to use and contribute catalog tasks?
  - Should we enforce any type of schema on generator configuration?
- Link to any prior art of DSLs / alternative Tekton configurations you're aware of.
- Any other ideas / improvements / critiques

# Ideas

Goals:
- Provide a DSL spec for pipeline generators to automate pipeline set up for users.
- Don't make Tekton directly aware of integration types (e.g. GitHub)
- Make it easy for users to make their own.
- Encourage users to reuse existing Tekton concepts.

## Simplified spec for common workflows

Ideally, it should be very easy for users to get started with only their repo and build steps. e.g. imagine a world where you configure just the following:

```yaml
kind: GitHub
metadata:
  name: github-build
spec:
  url: "https://github.com/wlynch/test"
  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - --context=dir://$(workspaces.input.path)/src
        - --destination=gcr.io/wlynch-test/kaniko-test
        - --verbosity=debug
```

(Note: this looks CRD-y, since this is how the idea started out, but I switched to a CLI approach based on feedback from Scott and other Googlers. API Version / Kind / Metadata still seem like useful identifiers, so I left this in.)

A CLI tool (likely tkn, but doesn't need to be) should be able to take this spec and when applied, should generate:

- Wrap `steps` in a Task
- Wrap Task in Pipeline
- Wire up workspaces for Git repo.
- Attach credentials (if necessary)
- Prepend Git clone Task at the start of the Pipeline
- Add GitHub status task to end of Pipeline / `finally`
- Create Trigger / EventListener for GitHub events to kick off pipeline on pushes.

All resources created should be labeled with the generator that created it, to facilitate bulk queries / deletion / modification.

Users should be able to specify the runtime configuration however they want. This means generators should support users providing one of:
- steps
- taskSpec
- taskRef
- pipelineSpec
- pipelineRef

## Extensibility

To allow users to provide their own generators, I think the easiest approach would be to follow the model of [Git credential helpers](https://git-scm.com/docs/gitcredentials#_custom_helpers).

tl;dr of this approach is when given a configuration, we should look for a binary on the user's path matching `tekton-generator-<generator kind>`, i.e. `tekton-generator-github`. The generator configuration is piped in to the binary via STDIN, and the generated response is provided from STDOUT.

This allows users to define their own generators, or even invoke the generator directly to expose the underlying pipeline to modify the contents.

## Ease of use

We should probably have some utilities to help interacting with generators. Some that come to mind:

- `show`: Print generated configuration.
- `write`: Write generated configuration to disk.
- `apply`: Apply generated configuration to Kubernetes (based on local k8s context).
- `delete`: Delete generated resources.

## Example

I've been hacking on a **really rough** concept of this at https://github.com/wlynch/tekton-demo/tree/master/bundle.
