### ISSUE TITLE
Default workspace types for PipelineRuns and TaskRuns

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2595]
# Expected Behavior

Following up on https://github.com/tektoncd/pipeline/issues/2398

It would be useful to be able to specify default `Workspace` types. The idea would be that users don't need to specify `workspaces` they don't care about (or whose configuration should be entirely in the hands of admins) and Tekton could just inject a default bit of `volume` configuration when it launches a `TaskRun` or `PipelineRun`.

It seems like one approach to this would be to introduce a `ConfigMap` (maybe per-namespace for different tenants?) that allows a user to set the default `WorkspaceBinding`. It probably makes sense to have separate configuration for `PipelineRun` and `TaskRun` since `TaskRuns` can execute happily with an `emptyDir` but `PipelineRuns` would probably want the option to use something like a `volumeClaimTemplate` by default.

If we were to also introduce [optional `Workspaces`](https://github.com/tektoncd/pipeline/issues/2119) then I'm not sure what the most desirable behaviour would be - would a default `WorkspaceBinding` be injected for optional `Workspaces` or would they be left empty?

# Actual Behavior

At the moment users have to completely specify `WorkspaceBindings` in their Runs.

Also relates to [the existing config-artifact-pvc](https://github.com/tektoncd/pipeline/issues/2330) which are used by PipelineResources.

**Comment by sbwsg** [comment]
Here's an example ConfigMap syntax that might suit. TaskRuns would received `emptyDir` WorkspaceBindings by default and PipelineRuns would receive `volumeClaimTemplates` by default:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: 
data:
  defaultTaskRunWorkspaceBinding: # Field Name TBD
    emptyDir: {}
  defaultPipelineRunWorkspaceBinding:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```

And then, given a Task that looks just like one of our existing examples:

```yaml
spec:
  workspaces:
  - name: custom
  - name: custom2
    mountPath: /foo/bar/baz
  - name: custom3
  - name: custom4
    mountPath: /baz/bar/quux
  - name: custom5
    mountPath: /my/secret/volume
  steps:
  - name: write
    image: ubuntu
    script: echo $(workspaces.custom.volume) > $(workspaces.custom.path)/foo
  - name: read
    image: ubuntu
    script: cat $(workspaces.custom.path)/foo | grep $(workspaces.custom.volume)
  - name: write2
    image: ubuntu
    script: echo $(workspaces.custom2.path) > $(workspaces.custom2.path)/foo
  - name: read2
    image: ubuntu
    script: cat $(workspaces.custom2.path)/foo | grep $(workspaces.custom2.path)
  - name: write3
    image: ubuntu
    script: echo $(workspaces.custom3.path) > $(workspaces.custom3.path)/foo
  - name: read3
    image: ubuntu
    script: cat $(workspaces.custom3.path)/foo | grep $(workspaces.custom3.path)
  - name: readconfigmap
    image: ubuntu
    script: cat $(workspaces.custom4.path)/my-message.txt | grep "hello world"
  - name: readsecret
    image: ubuntu
    script: |
      #!/usr/bin/env bash
      set -xe
      cat $(workspaces.custom5.path)/username | grep "user"
      cat $(workspaces.custom5.path)/message | grep "hello secret"
```

A user could choose to only provide the secret and configuration workspaces:

```yaml
kind: TaskRun
spec:
  workspaces:
    - name: custom4
      configMap:
        name: my-configmap
        items:
          - key: message
            path: my-message.txt
    - name: custom5
      secret:
        secretName: my-secret
```

All of the other workspaces would be automatically set to `emptyDir` volumes.

**Comment by jlpettersson** [comment]
This is also related to https://github.com/tektoncd/pipeline/issues/2586
since, you currently have to _carefully_ think how you use PVCs in a Pipeline at least when you have any _parallelism_ of tasks or if you have a _regional_ cluster.

Remember https://github.com/tektoncd/pipeline/pull/2546

fan-out: one task followed by multiple parallel - is difficult with PVC workspaces
fan-in: multiple parallel tasks to be converge in a single task - is difficult with PVC workspaces

**Comment by sbwsg** [comment]
Ah yeah, good point; it may be that default workspaces for PipelineRuns are much trickier to use correctly.

**Comment by siamaksade** [comment]
The parallelism issues are related to use of a PVC in parallel tasks, regardless of if it was provided via a default workspace mechanism or if user provided the PVC in the PipelineRun. 

Default workspace is useful IMO for removing the burden or defining a workspace PVC for each PipelineRun. The parallelism issues need to get addresses separately from this and are not really the target of default workspaces to resolve.

**Comment by jlpettersson** [comment]
>removing the _burden_ or defining a workspace PVC for each PipelineRun

A realistic and proper `PipelineRun` will most likely be extensive, where "defining PVC workspace" is a _small_ but _declarative_ piece. This should be done _once_ in e.g. a `TriggerTemplate` and stored in _version control_ with _code reviewed_ PR for every change, as recommended in [Accelerate](https://www.amazon.com/Accelerate-Software-Performing-Technology-Organizations-ebook/dp/B07B9F83WM/ref=sr_1_1?crid=U7IT82IX8DHX&dchild=1) and [Continuous Delivery](https://www.amazon.com/Continuous-Delivery-Deployment-Automation-Addison-Wesley-ebook-dp-B003YMNVC0/dp/B003YMNVC0/ref=mt_kindle?_encoding=UTF8).

[Kubernetes Declarative Config Management](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/), similar to the _declarative_ format of Terraform is a _successfactor_. _Immutable Infrastructure_ and _Declarative Config_ is also a reason to interest of [GitOps](https://www.weave.works/technologies/gitops/).

We should focus on _user experience_ but not give up _declarative config_ - it is a strength compared to previous CI-systems.

This is one example of a more realistic `PipelineRun`:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: continuous-delivery-pipeline-
spec:
  params:
  - name: git-url
    value: git@github.com:jlpettersson/myapp.git
  - name: branch-name
    value: master
  - name: committer
    value: jlpettersson
  pipelineRef:
    name: pipeline-with-git-clone
  taskRunSpecs:
  - pipelineTaskName: git-clone
    taskPodTemplate:
      volumes:
      - name: ssh-auth
        projected:
          defaultMode: 0400
          sources:
          - secret:
              name: github-known-hosts
          - secret:
              name: github-private-key
  - pipelineTaskName: build-and-push-image
    taskPodTemplate:
      volumes:
      - name: service-account-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200
              audience: image-registry
  - pipelineTaskName: integration-test
    taskPodTemplate:
      volumes:
      - name: service-account-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200
  - pipelineTaskName: deploy-to-staging
    taskPodTemplate:
      volumes:
      - name: service-account-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200
              audience: staging-cluster
  - pipelineTaskName: deploy-to-prod
    taskPodTemplate:
      imagePullSecret: prod-image-pull-secret
      volumes:
      - name: service-account-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200
              audience: prod-cluster
  workspaces:
  - name: ws
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
```
