### ISSUE TITLE
Duplicate ways to specify ServiceAccountName for tasks in a PipelineRun

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/pipeline#2614]
# Expected Behavior

A consistent way to declare `ServiceAccountNames` for tasks in a `PipelineRun`

# Actual Behavior

There is now two ways, almost identical to specify `ServiceAccountName` for tasks in a `PipelineRun`. It is a bit confusing. What happens if I specify both fields but with different values?

```
spec:

  # existing way
  serviceAccountNames:
    - taskName: build-task
      serviceAccountName: sa-for-build
   
  # newly introduced
  taskRunSpecs:
    - taskName: build-task
      taskServiceAccountName: sa-for-build
```

The latter alternative seem to have been merged yesterday with #2389
/kind bug
