### ISSUE TITLE
Passing parameters to pipelineresource

### ISSUE THREAD

**Issue by holoGDM** [tektoncd/pipeline#2622]
Is there possibility to pass runtime parameters to pipelineresources from task/pipeline?

Something like that:

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: wizzbang-git
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/wizzbangcorp/wizzbang.git
    - name: revision
      value: $(parms.stringparameter)
```
I need to choose during pipeline start from which branch application need to be builded. I found:
[issue](https://github.com/tektoncd/pipeline/pull/1186)

but it looks like it is not merged. Is there any other possibility to handle such thing?

/kind question
