### ISSUE TITLE
spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true

### ISSUE THREAD

**Issue by jlewi** [tektoncd/pipeline#2667]
I'm trying to deploy Tekton using ACM/Nomos which is Google Cloud GitOps tooling.

When I try to install with ACM I get the following validation error

```
kf-ci-management   KNV2010: unable to create resource: KNV2010: failed to create "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition", "/clustertasks.tekton.dev": CustomResourceDefinition.apiextensions.k8s.io "clustertasks.tekton.dev" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true
```

The confusing bit here is that if we look at the Tekton spec its setting preserveUnknownFields to false but then has some comment about overriding that. 

```
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      # One can use x-kubernetes-preserve-unknown-fields: true
      # at the root of the schema (and inside any properties, additionalProperties)
      # to get the traditional CRD behaviour that nothing is pruned, despite
      # setting spec.preserveUnknownProperties: false.
      #
      # See https://kubernetes.io/blog/2019/06/20/crd-structural-schema/
      # See issue: https://github.com/knative/serving/issues/912
      x-kubernetes-preserve-unknown-fields: true
```

Could someone please clarify the intended behavior for Tekton conversions with respect to field preservation?
