### ISSUE TITLE
TaskRun creation fails, created from PipelineRun with TaskRunSpec

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/pipeline#2682]
# Expected Behavior

That I can declare `TaskRunSpecs` in the `PipelineRun` and `TaskRun` with the given spec is created.

Example:

```
piVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: git-clone-ssh-
spec:
  params:
  - name: git-url
    value: git@github.com:jlpettersson/myapp.git
  pipelineRef:
    name: pipeline-with-git-clone
  taskRunSpecs:
  - pipelineTaskName: git-clone
    taskPodTemplate:
      volumes:
      - name: ssh-auth
        projected:
          defaultMode: 0400
          sources:
          - secret:
              name: github-known-hosts
          - secret:
              name: github-private-key
```

As described in [documentation about TaskRunSpec](https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#specifying-task-run-specs) (However, there were errors in doc also, fixed in https://github.com/tektoncd/pipeline/pull/2681)

# Actual Behavior

TaskRun creation fails with:

```
status:
        conditions:
        - lastTransitionTime: "2020-05-23T17:03:00Z"
          message: 'failed to create task run pod "git-clone-ssh-n2lc8-git-clone-jrbjf":
            Pod "git-clone-ssh-n2lc8-git-clone-jrbjf-pod-hdww2" is invalid: spec.containers[0].volumeMounts[0].name:
            Not found: "ssh-auth". Maybe missing or invalid Task g/git-clone-ssh'
          reason: CouldntGetTask
```

/kind bug
