### ISSUE TITLE
Fields specified multiple times overwrite each other

### ISSUE THREAD

**Issue by wlynch** [tektoncd/pipeline#2700]
I did something dumb, but it turns out this poked at some unexpected behavior. 😃 

Given this Task spec:

```yaml
  - name: git
    taskRef:
      name: git-clone
    params:
    - name: url
      value: "https://github.com/tektoncd/pipeline"
    - name: revision
      value: "master"
    workspaces:
    - name: output
      workspace: source
    params: 
```

(`params` is specified 2x by mistake)

# Expected Behavior

Pipeline controller rejects the config with an error.

# Actual Behavior

Pipeline controller accepts the config, overwriting the first `params` field with the second empty `params` field, resulting in:

```yaml
  - name: git
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: source
```

This was particularly confusing because it looked like the params field was ignored.

# Steps to Reproduce the Problem

See example config above.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`**:

  ```
  Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", 
  GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", 
  BuildDate:"2020-01-18T23:33:14Z", GoVersion:"go1.12.12", Compiler:"gc", 
  Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.3", 
  GitCommit:"71631703d37fb1b4b333abd427deae839aeb2032", GitTreeState:"clean", 
  BuildDate:"2020-03-24T18:54:48Z", GoVersion:"go1.12.17b4", Compiler:"gc", 
  Platform:"linux/amd64"}
  ```

- Tekton Pipeline version: v0.12.1

Not sure if there is anything we can actually do about this - this seems like it might be a property of how k8s handles CRDs by default, but figured I'd file an issue so we can look into it just in case.
