### ISSUE TITLE
Taskrun gives error while pulling image from ECR

### ISSUE THREAD

**Issue by shunsubramanian** [tektoncd/pipeline#2707]
# Expected Behavior
Running the task and taskrun on the EKS cluster and pulling the image from ECR.

# Actual Behavior
When I view the taskrun logs, I am seeing the below error message:
```
task test has failed: failed to create task run pod "image": translating TaskSpec to Pod: error getting image manifest: unsupported status code 401; body: Not Authorized. Maybe missing or invalid Task default/image
Error: pod for taskrun irxep-ui not available yet
```
# Steps to Reproduce the Problem

1. Run the below yaml
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  steps:
    - name: image
      image: Account#.dkr.ecr.us-east-1.amazonaws.com/image:latest
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: testtask
spec:
  taskRef:
    name: test
```

# Additional Info

The below test deployment using the nginx is working just fine.

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nginx
spec:
  steps:
    - name: nginx
      image: nginx:latest
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: nginx
spec:
  taskRef:
    name: nginx
```

- Kubernetes version:
EKS 1.16

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

v0.12.1
--

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
Client version: 0.9.0
Pipeline version: v0.12.1

**Comment by MarcusNoble** [comment]
See here for a workaround: https://github.com/tektoncd/pipeline/issues/1539#issuecomment-640457021

**Comment by ghfalcon7** [comment]
I'm having the same issue, @MarcusNoble tried the WA but it didn't work for me.

**Comment by hudac** [comment]
Issue still exists in Tekton v0.29.0:
```
  steps:
    - name: test
      image: 123456789.dkr.ecr.some-region.amazonaws.com/some/image:1.2
```

Fails with:
`  Warning  Failed   11s (x2 over 11s)  TaskRun  failed to create task run pod "test-task-s6847": translating TaskSpec to Pod: error getting image manifest: GET https://123456789.dkr.ecr.some-region.amazonaws.com/v2/some/image/manifests/1.2: unexpected status code 401 Unauthorized: Not Authorized`

**Workaround:**
It works when you provide a command (args only are not sufficient):
```
  steps:
    - name: test
      image: 123456789.dkr.ecr.some-region.amazonaws.com/some/image:1.2
      command: ["python3", "test.py"]
```
Though the command duplicates the already defined `ENTRYPOINT` within the image, it at least prevents Tekton from trying to fetch the manifest from ECR.

Had this issue on v0.27.2 first. Just upgraded to v0.29.0, same error.
