### ISSUE TITLE
support from in finally tasks

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#2711]
Similar to `tasks`, `finally` tasks can have [PipelineResources](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#specifying-resources) as inputs and outputs for in the Pipeline. 

The only difference here is, final tasks with an input resource can not have a `from` clause
like a `PipelineTask` from `tasks` section. For example:

```yaml
spec:
  tasks:
    - name: tests
      taskRef:
        Name: integration-test
      resources:
        inputs:
          - name: source
            resource: tektoncd-pipeline-repo
        outputs:
          - name: workspace
            resource: my-repo
  finally:
    - name: clear-workspace
      taskRef:
        Name: clear-workspace
      resources:
        inputs:
          - name: workspace
            resource: my-repo
            from: #invalid
              - tests
```

Design and implement how can we specify `from` clause in `finally` tasks.

References:

[finally Design Doc](https://docs.google.com/document/d/1lxpYQHppiWOxsn4arqbwAFDo4T0-LCqpNa6p-TJdHrw)
[finally type PR](https://github.com/tektoncd/pipeline/pull/2650)
[finally functionality PR](https://github.com/tektoncd/pipeline/pull/2661)
