### ISSUE TITLE
Expose retries to the the Task/TaskRun

### ISSUE THREAD

**Issue by IdanAdar** [tektoncd/pipeline#2725]
# Expected Behavior
For the value of `retries` to be available at runtime so I could track it and potentially run different code flows depending in the current retry counter.

# Actual Behavior
Currently not exposed.

**Comment by wlynch** [comment]
/kind feature

Hi! Thanks for the feature request!

Can you describe in a little more detail what your use case is? e.g. are you looking for retry information to be exposed to running step containers, or the Tekton controller itself to be used with [Conditions](https://tekton.dev/docs/pipelines/pipelines/#guard-task-execution-using-conditions)?

Thanks! :D

**Comment by IdanAdar** [comment]
I would like to use it in steps, yes. I did not think about exposing it in Conditions, but I don't see why not...

We have some tasks (with a single step) that will be retried on failure. In this case though, depending on the number of attempts done I may want to dispatch a different notification, so knowing the current attempt # will help me accomplish that.

**Comment by IdanAdar** [comment]
@wlynch why?

**Comment by ImJasonH** [comment]
Just to clarify, is the end goal to enable something like this Pipeline?

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: retry-param
spec:
  tasks:
  - name: retry-me
    retries: 5
    taskSpec:
      steps:
      - image: busybox
        script: echo 'I am attempt number $(context.retry-count) of $(context.retries)' && exit 1
```

In this example, when the Pipeline is run, it should run 5 TaskRuns, the first one printing `I am attempt 1 of 5`, the last one printing `I am attempt 5 of 5` -- is that roughly the feature you're looking for @IdanAdar ?

(In the example above, the names of the placeholders are made up, we'd probably find a better name for both of them)
