### ISSUE TITLE
Support controller leader election in tekton-pipeline

### ISSUE THREAD

**Issue by xiujuan95** [tektoncd/pipeline#2735]
# Expected Behavior

I want to support high availability (HA) for tekton-pipeline. Not sure whether tekton-pipeline has supported or not, now? 

I mean HA is like leader-election, not the self-healing properties of kubernetes native.

Because, if I just depend on self-healing properties of kubernetes, it will cause some downtime for my services. This is not expected.

So if above question is yes, then I want to know which HA mode is being supported? If no, then if you guys have any plan about it? Thanks in advance!

# Actual Behavior

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by xiujuan95** [comment]
Just now, I do an experiment. I setup 3 tekton controller:
```
xiangxiulis-MacBook-Pro:samples xiangxiuli$ k get pod -n tekton-pipelines
NAME                                          READY   STATUS    RESTARTS   AGE
tekton-pipelines-controller-c5db6cb65-5mkgz   1/1     Running   0          31m
tekton-pipelines-controller-c5db6cb65-mc2w7   1/1     Running   0          31m
tekton-pipelines-controller-c5db6cb65-pzfzx   1/1     Running   0          20h
```
And apply 1 task and 1 taskRun using your sample:
```
xiangxiulis-MacBook-Pro:buildpack-sample xiangxiuli$ k get task
NAME                 AGE
buildpacks-v3-test   44m
xiangxiulis-MacBook-Pro:buildpack-sample xiangxiuli$ k get tr
NAME                                   SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
buildpacks-run                         False       Failed      40m         39m
```
I found there will have 3 taskrun pods come up, but only one is working. The other two are alway `running`:
```
xiangxiulis-MacBook-Pro:buildpack-sample xiangxiuli$ k get pod
NAME                                             READY   STATUS             RESTARTS   AGE
buildpacks-run-pod-q685f                         0/9     Completed          0          40m
buildpacks-run-pod-qp4hv                         9/9     Running            0          40m
buildpacks-run-pod-wq64j                         9/9     Running            0          40m
```

So I think current tekton-pipeline doesn't support HA. If my understanding is wrong, pls correct me, thanks a lot!

**Comment by eddycharly** [comment]
I tried the same setup a while ago and observed the same behaviour.

I don’t think it’s supported yet, though there is a leader election config map, I am not sure if this is possible at all.

**Comment by xiujuan95** [comment]
@eddycharly Does it have a leader election configMap?  Which one?
```
xiangxiulis-MacBook-Pro:buildpack-sample xiangxiuli$ k get cm -n tekton-pipelines
NAME                            DATA   AGE
config-artifact-bucket          0      75d
config-artifact-pvc             0      75d
config-defaults                 1      75d
config-logging                  3      75d
config-logging-triggers         4      75d
config-observability            1      75d
config-observability-triggers   1      75d
feature-flags                   2      75d
```
Could you tell me which one is for the leader-election, pls? Thanks!

**Comment by eddycharly** [comment]
Looks like you don’t have it. Look here https://github.com/tektoncd/pipeline/blob/master/config/config-leader-election.yaml

**Comment by eddycharly** [comment]
Also, controller down doesn’t mean a downtime.
As long as your etcd is up, you will be able to register new jobs, they just won’t be processed without the controller but requests won’t be rejected.

**Comment by xiujuan95** [comment]
@eddycharly  Thanks a lot! For above mention election configmap, if I apply it, then would the leader-election be processed?

**Comment by eddycharly** [comment]
Hopefully... worth a try.
Let me know, I’m interested to know the answer ;)

**Comment by xiujuan95** [comment]
@eddycharly I create above election configMap, and add it into the tekton controller deployment, but it still doesn't work as expected. Namely, it still sets up three taskRun pods.

**Comment by eddycharly** [comment]
@xiujuan95 does your RBAC rules allow access to the config map ?

**Comment by xiujuan95** [comment]
@eddycharly Maybe not. I am trying to modify my RBAC and I want to use this image `github.com/tektoncd/pipeline/cmd/controller:latest`, but it failed:
```
 Normal   Pulling    51s (x4 over 2m18s)  kubelet, 10.93.177.70  Pulling image "github.com/tektoncd/pipeline/cmd/controller"
  Warning  Failed     50s (x4 over 2m17s)  kubelet, 10.93.177.70  Failed to pull image "github.com/tektoncd/pipeline/cmd/controller": rpc error: code = NotFound desc = failed to pull and unpack image "github.com/tektoncd/pipeline/cmd/controller:latest": failed to resolve reference "github.com/tektoncd/pipeline/cmd/controller:latest": github.com/tektoncd/pipeline/cmd/controller:latest: not found
  Warning  Failed     50s (x4 over 2m17s)  kubelet, 10.93.177.70  Error: ErrImagePull
  Warning  Failed     36s (x6 over 2m17s)  kubelet, 10.93.177.70  Error: ImagePullBackOff
  Normal   BackOff    21s (x7 over 2m17s)  kubelet, 10.93.177.70  Back-off pulling image "github.com/tektoncd/pipeline/cmd/controller"
```

**Comment by eddycharly** [comment]
`github.com/tektoncd/pipeline/cmd/controller` is not a docker image.
It's the github repository, the image is replaced by `ko` when `ko apply` is invoked.
I don't think you need to change the image, the leader election should come with knative. I suspect that if you have the leader election config map setup correctly and accessible it should work.

**Comment by xiujuan95** [comment]
@eddycharly I think now, my RBAC rules allow access to the election config map.
```
xiangxiulis-mbp:buildpack-sample xiangxiuli$ k get role -n tekton-pipelines -o yaml
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-pipelines"},"name":"tekton-pipelines-controller","namespace":"tekton-pipelines"},"rules":[{"apiGroups":[""],"resources":["configmaps"],"verbs":["list","watch"]},{"apiGroups":[""],"resourceNames":["config-logging","config-observability","config-artifact-bucket","config-artifact-pvc","feature-flags","config-leader-election"],"resources":["configmaps"],"verbs":["get"]}]}
    creationTimestamp: "2020-06-03T08:39:14Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-pipelines
    name: tekton-pipelines-controller
    namespace: tekton-pipelines
    resourceVersion: "4434681"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/tekton-pipelines/roles/tekton-pipelines-controller
    uid: 490b322e-4f5e-43e4-8f03-e23bc1cd339f
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - list
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - config-logging
    - config-observability
    - config-artifact-bucket
    - config-artifact-pvc
    - feature-flags
    - config-leader-election
    resources:
    - configmaps
    verbs:
    - get
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
But, it still doesn't work.
Could you try it in your side, pls?

**Comment by afrittoli** [comment]
The leader election is something that was recently added by the knative team in `knative/pkg`.
We inherited the configmap but we did not really do any integration work on Tekton side.

Background: https://github.com/knative/pkg/issues/1181.
@mattmoor may have more context to share.

@xiujuan95 @eddycharly looking forward to the results of your experiments.

**Comment by mattmoor** [comment]
I have some changes brewing that will change how this works a bit.  Those changes will enable reconcilers to be sharded across replicas and should help us scale reconcilers horizontally.  However, I want to get y'all onto `// +genreconciler` first so it's ~free.

**Comment by xiujuan95** [comment]
Any updates for HA?

**Comment by xiujuan95** [comment]
@mattmoor 

Just now, I did some experiments, I enabled leader-election for tekton-pipeline-controller. Yes, it works. 
```
kubectl logs tekton-pipelines-controller-6564ff7589-cjdqw -n tekton-pipelines
2020/09/14 05:03:16 Registering 4 clients
2020/09/14 05:03:16 Registering 4 informer factories
2020/09/14 05:03:16 Registering 8 informers
2020/09/14 05:03:16 Registering 2 controllers
{"level":"info","caller":"logging/config.go:111","msg":"Successfully created the logger."}
{"level":"info","caller":"logging/config.go:112","msg":"Logging level set to info"}
{"level":"info","logger":"tekton","caller":"profiling/server.go:59","msg":"Profiling enabled: false","commit":"20da4cf"}
I0914 05:03:16.819066       1 leaderelection.go:241] attempting to acquire leader lease  tekton-pipelines/tekton...
{"level":"info","logger":"tekton","caller":"sharedmain/main.go:447","msg":"tekton will run in leader-elected mode with id tekton-pipelines-controller-6564ff7589-cjdqw_d768ec9f-8ee3-400b-b3fa-2c023caa6e0f","commit":"20da4cf"}
I0914 05:03:40.146129       1 leaderelection.go:251] successfully acquired lease tekton-pipelines/tekton
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:274","msg":"Event(v1.ObjectReference{Kind:\"Lease\", Namespace:\"tekton-pipelines\", Name:\"tekton\", UID:\"d7c8536f-802f-4633-bc71-266711a43958\", APIVersion:\"coordination.k8s.io/v1\", ResourceVersion:\"90631532\", FieldPath:\"\"}): type: 'Normal' reason: 'LeaderElection' tekton-pipelines-controller-6564ff7589-cjdqw_d768ec9f-8ee3-400b-b3fa-2c023caa6e0f became leader","commit":"20da4cf"}
```
But when I tried to enter each pod and curl `https://localhost:9090/metrics`, only the active pod can return values. Other passive pod failed because below error:
```
sh-4.4# curl http://localhost:9090/metrics
curl: (7) Failed to connect to localhost port 9090: Connection refused
```
Is it only the active one that opens the Prometheus metrics port? I went through the code, but I don't find where can I confirm this? Could you pls help me about this? Thanks in advance!

**Comment by xiujuan95** [comment]
Under the help of my colleague @qu1queee, thanks! Yes, metrics for prometheus only works on the active pod. 

Then this causes another problem for me. If I configure the tekton controller deployment to do liveness and readiness check like below:
```
livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```
Under this situation, only the active pod can be running, all passive pods will be `CrashLoopBackOff` because:
```
 Warning  Unhealthy  117s (x6 over 2m47s)  kubelet, 10.242.64.5  Readiness probe failed: Get http://172.30.83.152:9090/metrics: dial tcp 172.30.83.152:9090: connect: connection refused
  Warning  Unhealthy  117s (x6 over 2m47s)  kubelet, 10.242.64.5  Liveness probe failed: Get http://172.30.83.152:9090/metrics: dial tcp 172.30.83.152:9090: connect: connection refused
```
That's bad for me. So not sure if your guys can provide a better way to do liveness and readiness probes or not? Thanks in advance!

**Comment by xiujuan95** [comment]
Any updates about this issue?

**Comment by gejunqiang** [comment]
@xiujuan95  I met the same issue this days,  Can u explain how to enable leader-election for tekton-pipeline-controller, pls? I can not find any documents about this. Thanks in advance.

**Comment by afrittoli** [comment]
Leader election should work now (on master branch) but it still needs to be verified, documented and tested.
I  tried in my local cluster and it seemed to behave nicely, but you'll have to use master branch.

**Comment by xiujuan95** [comment]
@gejunqiang I just modify `config-leader-election` configMap and add this filed. My final configMay is:
```
apiVersion: v1
data:
  enabledComponents: tekton
  leaseDuration: 15s
  renewDeadline: 10s
  resourceLock: leases
  retryPeriod: 2s
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"leaseDuration":"15s","renewDeadline":"10s","resourceLock":"leases","retryPeriod":"2s"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-pipelines"},"name":"config-leader-election","namespace":"tekton-pipelines"}}
  creationTimestamp: "2020-06-03T07:31:26Z"
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
  name: config-leader-election
  namespace: tekton-pipelines
  resourceVersion: "107669459"
  selfLink: /api/v1/namespaces/tekton-pipelines/configmaps/config-leader-election
  uid: 8e5706ee-2e84-40b1-88fa-be79b21868fe
```
BTW, I am using `0.14.2` tekton-pipeline release. Maybe now, something is changed. You can see these two parts:
https://github.com/tektoncd/pipeline/blob/v0.14.2/vendor/knative.dev/pkg/leaderelection/config.go#L49
https://github.com/tektoncd/pipeline/blob/v0.14.2/vendor/knative.dev/pkg/injection/sharedmain/main.go#L447

**Comment by gejunqiang** [comment]
@xiujuan95 I'm using v1.16.3 tekton-pipeline release, and I tried your way, it works well, thank u!

**Comment by gejunqiang** [comment]
> Leader election should work now (on master branch) but it still needs to be verified, documented and tested.
> I tried in my local cluster and it seemed to behave nicely, but you'll have to use master branch.

 @afrittoli Yeah, I saw that the v1.17.0 release code support the Leader Election, I will upgrade my tekton-pipelines to v1.17.0 and do some experiments, thank u!

**Comment by afrittoli** [comment]
Well, on v0.17.0 the enable flag is broken, v0.17.1 will fix that as soon as it's released.
So either use master, or a nightly build, or you can use v0.17.0 but you need to set the disable-ha flag is true to *enable* HA

**Comment by xiujuan95** [comment]
> Well, on v0.17.0 the enable flag is broken, v0.17.1 will fix that as soon as it's released.
> So either use master, or a nightly build, or you can use v0.17.0 but you need to set the disable-ha flag is true to _enable_ HA

@afrittoli How can I set `disable-ha` flag, also set it in the `config-leader-election` configMap?

**Comment by gejunqiang** [comment]
@xiujuan95  set `disable-ha` flag in container args of tekton-pipelines-controller deployment,  according to https://github.com/tektoncd/pipeline/blob/v0.17.0/cmd/controller/main.go#L56.

I'll try this later, but actually I was confused by this flag's name at first. According to @afrittoli , this flag in v0.17.0 does the opposite of what it should,  we need to set the disable-ha flag is true to enable HA.

**Comment by xiujuan95** [comment]
@gejunqiang Thanks!  If you have some results about `disable-ha` flag, please let me know, thanks in advance! Also I will verify it.

**Comment by xiujuan95** [comment]
@gejunqiang Sad! I can't set it in tekton-pipeline-controller deployment:
```
# deployments.apps "tekton-pipelines-controller" was not valid:
# * patch: Invalid value: "map[spec:map[template:map[spec:map[]]]]": unrecognized type: string
```
Also can't set it in `config-leader-election` configMap.
```
# configmaps "config-leader-election" was not valid:
# * patch: Invalid value: "map[data:map[disable-ha:true]]": unrecognized type: string
```

**Comment by gejunqiang** [comment]
@xiujuan95 How do u set this `disable-ha` flag,  I tried this just now , the container args of `tekton-pipelines-controller` deployment looks like this:
```yaml
    spec:
      containers:
      - args:
        - (...omit other args)
        - -disable-ha
        - "true"
        name: tekton-pipelines-controller
```
It works well.

**Comment by xiujuan95** [comment]
@gejunqiang I first set them like below:
```
spec:
      containers:
      - args:
        - (...omit other args)
        - -disable-ha
        - true
        name: tekton-pipelines-controller
```
I didn't add the double quotation marks. Now, although I can configure it like your method, my tekton-pipeline-controller pod can't come up and alway crash:
```
xiangxiulis-MacBook-Pro:spark xiangxiuli$ k logs tekton-pipelines-controller-74d8c98c44-hnbqc -n tekton-pipelines
2020/10/13 07:55:44 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
2020/10/13 07:55:44 found unset image flags: [build-gcs-fetcher creds entrypoint git gsutil imagedigest-exporter kubeconfig-writer nop pr shell]
xiangxiulis-MacBook-Pro:spark xiangxiuli$ k get pod -n tekton-pipelines
NAME                                           READY   STATUS             RESTARTS   AGE
tekton-pipelines-controller-74d8c98c44-hnbqc   0/1     CrashLoopBackOff   4          2m28s
tekton-pipelines-webhook-8b4798587-wh89z       1/1     Running            0          22h
```
Do you have this issue?

**Comment by gejunqiang** [comment]
@xiujuan95 I didn't have this issue. From the log `found unset image flags: [build-gcs-fetcher creds entrypoint git gsutil imagedigest-exporter kubeconfig-writer nop pr shell]`,  maybe you have removed other args? Can you show your complete container args.

**Comment by xiujuan95** [comment]
@gejunqiang Sure! I don't remove anything, below is my spec:
```
spec:
  containers:
  - args:
    - -disable-ha
    - "true"
    - -version
    - devel
    - -kubeconfig-writer-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.17.0@sha256:fbb27573e13c2a54cd0c1c8cb094b164e2d6b713b62348822fc16952a398386d
    - -creds-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init:v0.17.0@sha256:e8504b6c4dfa5374cfa97d51e7b56dc5b8980b42c67120c527c9738124b5b687
    - -git-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.17.0@sha256:e3b125e80654d33b4a3d2a29d8a9b0d155185dcddad91ade0ac7b85c71b43c95
    - -entrypoint-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.17.0@sha256:3566c77d313eba5dc5ca1c015007205fc78a4141de2caa97ae5f01665cb00b42
    - -nop-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.17.0@sha256:b475fa8ccbf010775395c5556f6aa8205b288b3e1c6640d9e0dab58378de93e5
    - -imagedigest-exporter-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.17.0@sha256:cb4dcc7ea5c31643c59058b5d60f7f43a0a7789e3e001497e711773a06bac01c
    - -pr-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.17.0@sha256:7d2820af331c349ee6eb9f187fac469c2b1eab65ea6d505adc15396df8ebde1f
    - -build-gcs-fetcher-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher:v0.17.0@sha256:32a963ad5dd4c0cb1b0499762b6ec9e9ba0fc876ed72f1280e538f8771c2f846
    - -gsutil-image
    - gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:27b2c22bf259d9bc1a291e99c63791ba0c27a04d2db0a43241ba0f1f20f4067f
    - -shell-image
    - gcr.io/distroless/base@sha256:60f5ffe6fc481e9102747b043b3873a01893a5a8138f970c5f5fc06fb7494656
```

**Comment by gejunqiang** [comment]
@xiujuan95  Oh..It's so weird! I don't know what's wrong. But it works well for me.

**Comment by afrittoli** [comment]
> @gejunqiang I first set them like below:
> 
> ```
> spec:
>       containers:
>       - args:
>         - (...omit other args)
>         - -disable-ha
>         - true
>         name: tekton-pipelines-controller
> ```
> 
> I didn't add the double quotation marks. 

You need the double quotation marks.

> Now, although I can configure it like your method, my tekton-pipeline-controller pod can't come up and alway crash:
> 
> ```
> xiangxiulis-MacBook-Pro:spark xiangxiuli$ k logs tekton-pipelines-controller-74d8c98c44-hnbqc -n tekton-pipelines
> 2020/10/13 07:55:44 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
> 2020/10/13 07:55:44 found unset image flags: [build-gcs-fetcher creds entrypoint git gsutil imagedigest-exporter kubeconfig-writer nop pr shell]
> xiangxiulis-MacBook-Pro:spark xiangxiuli$ k get pod -n tekton-pipelines
> NAME                                           READY   STATUS             RESTARTS   AGE
> tekton-pipelines-controller-74d8c98c44-hnbqc   0/1     CrashLoopBackOff   4          2m28s
> tekton-pipelines-webhook-8b4798587-wh89z       1/1     Running            0          22h
> ```
> 
> Do you have this issue?

This happens because you have the `disable-ha` set to true with no quotation marks on the top, so the rest of the args are not passed to the controller which then fails on missing flags.

**Comment by xiujuan95** [comment]
@afrittoli I have double quotation mark. But the pod still is in crash status!

**Comment by xiujuan95** [comment]
I found why the pod can't come up. 'disable-ha' should be added at the end rather than at the beginning:
```
spec:
      containers:
      - args:
        - (...omit other args)
        - -disable-ha
        - "true"
        name: tekton-pipelines-controller
```
If I change it to below, it will be fail:
```
spec:
      containers:
      - args:
        - -disable-ha
        - "true"
        - (...omit other args)
        name: tekton-pipelines-controller
```
The behavior is weird for me! Why？

**Comment by afrittoli** [comment]
Uhm, this sounds like a bug to me

**Comment by xiujuan95** [comment]
@afrittoli I found the following settings for `disable-ha` flag is incorrect:
```
spec:
      containers:
      - args:
        - (...omit other args)
        - -disable-ha
        - "false"
        name: tekton-pipelines-controller
```
We can't set it like above. Because above setting treats the value of `disable-ha` to be a string type, then this judge:https://github.com/tektoncd/pipeline/blob/v0.17.1/cmd/controller/main.go#L87 will be alway true whatever we set it to be `"true"` or `"false"`. Only there has a value, then it will be alway `true`. 

The correct setting is:
```
spec:
      containers:
      - args:
        - (...omit other args)
        - -disable-ha=false
        name: tekton-pipelines-controller
```
I am not sure if this is a bug or not for your side. If it's yes, pls help fix it. Thanks in advance!

BTW, I think there should have a doc to guide how to set these flags:https://github.com/tektoncd/pipeline/blob/v0.17.1/cmd/controller/main.go#L40-L56, otherwise, users maybe refer to some existed parameters, such as `version`, `kubeconfig-writer-image` etc, to set needed flags.  This will cause some errors like I mentioned. FYI, @gejunqiang ^^
