### ISSUE TITLE
v0.13.0: FailedCreate Pod affinity-assistant: must be no more than 63 characters

### ISSUE THREAD

**Issue by r0bj** [tektoncd/pipeline#2766]
# Expected Behavior

Pod affinity-assistant is created successfully.

# Actual Behavior

Pod affinity-assistant fail to create so the whole pipelinerun fail.

# Steps to Reproduce the Problem

1. My workspace definition in `TriggerBinding`:
```
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-image
[...]
      workspaces:
      - name: build-images-workspace
        volumeClaimTemplate:
          metadata:
            name: build-images
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
```

2. PipelineRun starts with name `build-images-75hz8`
3. PipelineRun creates PVC with name: `build-images-build-images-workspace-build-images-75hz8`
4. Creating Pod affinity-assistant failing with:
```
  Warning  FailedCreate  54s (x16 over 3m38s)  statefulset-controller  create Pod affinity-assistant-build-images-workspace-build-images-75hz8-0 in StatefulSet affinity-assistant-build-images-workspace-build-images-75hz8 failed error: Pod "affinity-assistant-build-images-workspace-build-images-75hz8-0" is invalid: metadata.labels: Invalid value: "affinity-assistant-build-images-workspace-build-images-75hz8-66f4857895": must be no more than 63 characters
```

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version: v0.13.0

**Comment by jlpettersson** [comment]
@r0bj Thanks for reporting this!

It appears as the new version is more sensitive to long names for Workspaces+PipelineRuns, because of the introduction of an "Affinity Assistant" that is a `StatefulSet` and seem to be more sensitive to long names.

In your example

```
      workspaces:
      - name: build-images-workspace
        volumeClaimTemplate:
          metadata:
            name: build-images
```

I would recommend to remove `name: build-images` in the `volumeClaimTemplate`, since the PVC will be named from the Workspace Name (`build-images-workspace` in your case)  in addition to the PipelineRun Name.
