### ISSUE TITLE
v0.13.0: unsuccessful cred copy: ".ssh" from "/tekton/creds" to "/root"

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/pipeline#2791]
# Expected Behavior

I should be able to **opt-out of the auto seeding of tekton creds** into each step and just mount my own secrets via workspaces under `/root`. Let the user have complete control and disable some of the automatic stuff tekton does around this. For steps which use images that rely on specific things in the user's home dir (in this case `/root`) I need to craft this directory in a specific way and this tekton cred stuff gets in the way.

# Actual Behavior

Task goes into `Error` state after 1st step. Each step in my task that does this ends up w/ this in logs. NOTE the serviceAccount this is running as has NO bound secrets.

```
2020/06/09 13:47:33 unsuccessful cred copy: ".ssh" from "/tekton/creds" to "/root": unable to open destination: open /root/.ssh/known_hosts: read-only file system
```

Overall in the tekton dashboard, the task just appears to be in a hung state.

![image](https://user-images.githubusercontent.com/1743646/84158226-df4cfd80-aa28-11ea-9f02-90947c8aa779.png)

# Steps to Reproduce the Problem

Note I have `"disable-home-env-overwrite":"true","disable-working-directory-overwrite":"true"`

1. Mount a secret backed workspace to a task at `/root/.ssh`
2. Start a pipelinerun for that task

My trigger workspaces:
```
        workspaces:
          - name: ssh-secrets
            secret:
              secretName: my-ssh-config 
              items:
                - key: ssh-privatekey
                  path: id_rsa
                  mode: 256
                - key: known_hosts
                  path: known_hosts
                - key: ssh-config
                  path: config
```

The task def workspaces:
```
    - name: ssh-secrets
      description: The workspace where we can find ssh secrets
      mountPath: /root/.ssh
      readOnly: true
```

# Additional Info

The `serviceAccount` that the pipelinerun uses, has no `secrets` attatched to it.

- Kubernetes version:

1.16.9

- Tekton Pipeline version: 0.13.0
