### ISSUE TITLE
Regression with PVCs and node affinity

### ISSUE THREAD

**Issue by jpds** [tektoncd/pipeline#2796]
# Expected Behavior

I have a pipeline that works fine in 0.12.1 but fails on 0.13.0.

# Actual Behavior

Pod for pipeline fails with:

```
Events:
  Type     Reason             Age                From                Message
  ----     ------             ----               ----                -------
  Normal   NotTriggerScaleUp  72s                cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't match pod affinity rules, 1 node(s) didn't match node selector
  Warning  FailedScheduling   70s (x4 over 75s)  default-scheduler   0/1 nodes are available: 1 node(s) didn't match node selector.
```

# Steps to Reproduce the Problem

1. Deploy 0.13.0:

```
kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.13.0/release.yaml
```

2. Apply this pipeline:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  steps:
    - name: test
      image: alpine:3.11.6
      script: |
        #!/bin/sh
        set -e
        echo "$(date -R): Test"
  workspaces:
  - name: test-dir
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: volume-pipeline
spec:
  tasks:
    - name: test
      taskRef:
        name: test-task
      workspaces:
        - name: test-dir
          workspace: volume-workspace
  workspaces:
  - name: volume-workspace
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: volume-pipelinerun
spec:
  pipelineRef:
    name: volume-pipeline
  podTemplate:
    nodeSelector:
      cloud.google.com/gke-nodepool: test-pool
    volumes:
    - name: volume-storage
  timeout: 2h
  workspaces:
    - name: volume-workspace
      volumeClaimTemplate:
        metadata:
          name: mypvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
```

3. Pod fails to start with above error.

4. Remove 0.13.0.

5. Install 0.12.1

6. Apply above pipeline.

7. Autoscaling succeeds:

```
Events:
  Type     Reason            Age                From                Message
  ----     ------            ----               ----                -------
  Warning  FailedScheduling  11s (x3 over 15s)  default-scheduler   0/1 nodes are available: 1 node(s) didn't match node selector.
  Normal   TriggeredScaleUp  11s                cluster-autoscaler  pod triggered scale-up: [{https://content.googleapis.com/compute/v1/projects/project-jklasdfk334/zones/us-west1-a/instanceGroups/gke-test-regression-test-pool-48f4fc0a-grp 0->1 (max: 1)}]
```

# Additional Info

- Kubernetes version: 1.16.8-gke.15

- Tekton Pipeline version: 0.13.0
