### ISSUE TITLE
Consolidate Result spec/status types across Pipeline/Task

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/pipeline#2825]
This is relevant to duck typed tasks, but I hit this in the context of trying to write some library code that deals with results (both spec/status) in a common way.

Right now the result types are identical, and the spec types only differ in this Value field:

```
// PipelineResult used to describe the results of a pipeline
type PipelineResult struct {
	// Name the given name
	Name string `json:"name"`
	// Description is a human-readable description of the result
	// +optional
	Description string `json:"description"`
	// Value the expression used to retrieve the value
	Value string `json:"value"`
}
```

We will want a common type for these to live in our duck type anyways, so we should think about consolidating these shapes.

/assign @ImJasonH

**Comment by ImJasonH** [comment]
Some context I didn't have before this bug: `PipelineResult`'s `Value` field exists to be able to express some derived result value of the Pipeline, as derived from some of its constituent Tasks' results.

[This example](https://github.com/tektoncd/pipeline/blob/648cff3dfe1330c5035492437adee6bf1670d941/examples/v1beta1/pipelineruns/pipelinerun-results.yaml) for instance:

```
  ...
  results:
    - name: sum
      description: the sum of all three operands
      value: $(tasks.second-add.results.sum)
    - name: partial-sum
      description: the sum of first two operands
      value: $(tasks.first-add.results.sum)
    - name: all-sum
      description: the sum of everything
      value: $(tasks.second-add.results.sum)-$(tasks.first-add.results.sum)
```

So when this Pipeline is run, its `PipelineRunResult`s will have values derived from the values of some of its TaskRuns.
