### ISSUE TITLE
task run not getting launched 

### ISSUE THREAD

**Issue by shashipratap** [tektoncd/pipeline#2863]
# Expected Behavior
task run should start 
# Actual Behavior
tkn tr logs echo-hello-world-run-p7mnb
Error: task echo-hello-world has not started yet

# Steps to Reproduce the Problem

1. Install tekton CD on a ubuntu machine having a single node kubernetes cluster(v1.16.7) tk version v0.13.2
2. create task with below yaml 
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World"
```
kubectl apply -f <name-of-task-file.yaml>

3. Run task with below yaml

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: echo-hello-world-task-run
spec:
  taskRef:
    name: echo-hello-world

```

kubectl apply -f <name-of-taskrun-file.yaml>
# Additional Info

- Kubernetes version: v1.16.7

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

v0.13.2

following error in tekton-pipelines-webhook pod
2020/06/25 10:01:33 Error reading/parsing logging configuration: timed out waiting for the condition
