### ISSUE TITLE
Tekton, Internal error occurred: context deadline exceeded

### ISSUE THREAD

**Issue by Mage-Sky** [tektoncd/pipeline#2877]
# Expected Behavior

# Actual Behavior

[root@master tekton]# kubectl apply -f taskrun1.yaml
Error from server (InternalError): error when creating "taskrun1.yaml": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=30s: context deadline exceeded

# Steps to Reproduce the Problem

[root@master tekton]# cat taskrun1.yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: run-with-parameters
spec:
  taskRef:
    name: task-with-parameters
  inputs:
    params:
      - name: flags
        value: "--set"
      - name: someURL
        value: "https://github.com/knative-sample"

# Additional Info

tekton-pipelines   tekton-dashboard-584fc79989-rxv5b                         1/1     Running                 4          20h
tekton-pipelines   tekton-pipelines-controller-85496b94dd-tmnk5              1/1     Running                 0          20h
tekton-pipelines   tekton-pipelines-webhook-7cd58cd7cb-t569j                 1/1     Running                 0          20h

**Comment by vdemeester** [comment]
/kind question

@Mage-Sky thanks for the issue. It seems like there is a network issue on your cluster somehow (between the k8s api-server and the webhook). Can you share more detail on your setup ? (kubernetes version ? OpenShift ? Running "services" (like knative, … ) ?)

**Comment by Mage-Sky** [comment]
> /kind question
> 
> @Mage-Sky thanks for the issue. It seems like there is a network issue on your cluster somehow (between the k8s api-server and the webhook). Can you share more detail on your setup ? (kubernetes version ? OpenShift ? Running "services" (like knative, … ) ?)

Thank you for your reply.

[root@master ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

Don't have too many services in this kubernetes.

NAMESPACE          NAME                                                      READY   STATUS
gitlab-runner      gitlab-runner-1578882389-gitlab-runner-54cc596c66-s4ltb   1/1     Running 
kube-system        coredns-9d85f5447-mdcdv                                   1/1     Running
kube-system        coredns-9d85f5447-xnn5n                                   1/1     Running 
kube-system        etcd-master                                               1/1     Running
kube-system        kube-apiserver-master                                     1/1     Running
kube-system        kube-controller-manager-master                            1/1     Running
kube-system        kube-flannel-ds-amd64-4hfbz                               1/1     Running
kube-system        kube-flannel-ds-amd64-gt2ls                               0/1     Init:ErrImagePull
kube-system        kube-flannel-ds-amd64-jbgqt                               0/1     Init:ImagePullBackOff
kube-system        kube-proxy-cshvj                                          1/1     Running
kube-system        kube-proxy-nk77f                                          1/1     Running
kube-system        kube-proxy-scc2v                                          1/1     Running
kube-system        kube-scheduler-master                                     1/1     Running
tekton-pipelines   tekton-dashboard-584fc79989-rxv5b                         1/1     Running
tekton-pipelines   tekton-pipelines-controller-85496b94dd-tmnk5              1/1     Running
tekton-pipelines   tekton-pipelines-webhook-7cd58cd7cb-t569j                 1/1     Running 


I guess it is the problem about network, but how can I check it? 
(Pretty sorry that I didn't show enough details about the issue. I just started to learn kubernets and tekton.)

**Comment by vdemeester** [comment]
It seems there is something wrong with `flannel` (which is the network part). Not sure how to go from there though, except through the doc and issues of flannel.

```
kube-system kube-flannel-ds-amd64-gt2ls 0/1 Init:ErrImagePull
kube-system kube-flannel-ds-amd64-jbgqt 0/1 Init:ImagePullBackOff
```

**Comment by Mage-Sky** [comment]
> It seems there is something wrong with `flannel` (which is the network part). Not sure how to go from there though, except through the doc and issues of flannel.
> 
> ```
> kube-system kube-flannel-ds-amd64-gt2ls 0/1 Init:ErrImagePull
> kube-system kube-flannel-ds-amd64-jbgqt 0/1 Init:ImagePullBackOff
> ```

Thank you very much. Maybe I will solve the issue about flannel at first.

**Comment by Mage-Sky** [comment]
> It seems there is something wrong with `flannel` (which is the network part). Not sure how to go from there though, except through the doc and issues of flannel.
> 
> ```
> kube-system kube-flannel-ds-amd64-gt2ls 0/1 Init:ErrImagePull
> kube-system kube-flannel-ds-amd64-jbgqt 0/1 Init:ImagePullBackOff
> ```

After all pods run well, the error was 

[root@master tekton]# kubectl apply -f hello-world.yaml
Error from server (InternalError): error when creating "hello-world.yaml": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=30s: dial tcp 10.96.85.188:443: connect: no route to host

**Comment by Mage-Sky** [comment]
About the flannel status,

● flanneld.service - Flanneld overlay address etcd agent
   Loaded: loaded (/usr/lib/systemd/system/flanneld.service; enabled; vendor preset: disabled)
   Active: activating (start) since Fri 2020-07-03 13:27:43 CST; 1min 25s ago
 Main PID: 9706 (flanneld)
    Tasks: 8
   Memory: 17.0M
   CGroup: /system.slice/flanneld.service
           └─9706 /usr/bin/flanneld -etcd-endpoints=http://127.0.0.1:2379 -etcd-prefix=/atomic.io/network

Jul 03 13:28:59 master flanneld-start[9706]: E0703 13:28:59.453387    9706 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured; error #0: EOF
Jul 03 13:29:00 master flanneld-start[9706]: E0703 13:29:00.455154    9706 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured; error #0: EOF
Jul 03 13:29:01 master flanneld-start[9706]: E0703 13:29:01.459147    9706 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured; error #0: EOF
Jul 03 13:29:02 master flanneld-start[9706]: E0703 13:29:02.462091    9706 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured; error #0: EOF
Jul 03 13:29:03 master flanneld-start[9706]: E0703 13:29:03.463819    9706 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured; error #0: EOF
Jul 03 13:29:04 master flanneld-start[9706]: E0703 13:29:04.465513    9706 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured; error #0: EOF
Jul 03 13:29:05 master flanneld-start[9706]: E0703 13:29:05.470064    9706 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured; error #0: EOF
Jul 03 13:29:06 master flanneld-start[9706]: E0703 13:29:06.471932    9706 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured; error #0: EOF
Jul 03 13:29:07 master flanneld-start[9706]: E0703 13:29:07.473524    9706 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured; error #0: EOF
Jul 03 13:29:08 master flanneld-start[9706]: E0703 13:29:08.475512    9706 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured; error #0: EOF

**Comment by Mage-Sky** [comment]
[root@master ~]# kubectl get all -n tekton-pipelines
NAME                                               READY   STATUS    RESTARTS   AGE
pod/tekton-dashboard-584fc79989-8lczm              1/1     Running   0          4d23h
pod/tekton-pipelines-controller-85496b94dd-tmnk5   1/1     Running   0          7d23h
pod/tekton-pipelines-webhook-7cd58cd7cb-t569j      1/1     Running   0          7d23h

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                     AGE
service/tekton-dashboard              NodePort    10.96.225.206   <none>        9097:30097/TCP              7d23h
service/tekton-pipelines-controller   ClusterIP   10.96.209.117   <none>        9090/TCP                    7d23h
service/tekton-pipelines-webhook      ClusterIP   10.96.85.188    <none>        9090/TCP,8008/TCP,443/TCP   7d23h

NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/tekton-dashboard              0/1     1            0           7d23h
deployment.apps/tekton-pipelines-controller   0/1     1            0           7d23h
deployment.apps/tekton-pipelines-webhook      0/1     1            0           7d23h

NAME                                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/tekton-dashboard-584fc79989              1         1         0       7d23h
replicaset.apps/tekton-pipelines-controller-85496b94dd   1         1         0       7d23h
replicaset.apps/tekton-pipelines-webhook-7cd58cd7cb      1         1         0       7d23h

**Comment by JianleiZhang** [comment]
edit `/etc/kubernetes/manifests/kube-apiserver.yaml` fie in master, add this argument:
```
--enable-aggregator-routing=true
```
it works for me.

**Comment by sbwsg** [comment]
Thanks @JianleiZhang ! @Mage-Sky let us know if this helps.  It appears there's some problem with using Tekton and flannel, at least this other issue also hit similar problems using flannel for network: https://github.com/tektoncd/pipeline/issues/2831

**Comment by Mage-Sky** [comment]
> --enable-aggregator-routing=true

Thank you for your help, but it still has error for me.

Error from server (InternalError): error when creating "task-hello-world.yaml": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=30s: no endpoints available for service "tekton-pipelines-webhook"

**Comment by Mage-Sky** [comment]
The error may be not about flannel.
I'm thinking about the issue: Internal error occurred: failed calling webhook. Wrong cert-manager hook ID. #2419

'Issues like this are ultimately caused by a mismatch between the webhook's service name configured on the CRD resources (which are not templated as part of the Helm chart, and thus are not updated automatically if the release name is set to something other than cert-manager or if the namespace is also not cert-manager).'

**Comment by c5haw** [comment]
I have also found this issue, but I am running on GKE cluster on Shared VPC.

### Steps to reproduce:
```
kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
kustomize build base | kubectl apply -f -
```

*base/kustomization.yaml*
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines
resources:
  - task.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: config-artifact-pvc
    literals:
      - size=5Gi
      - storageClassName=standard
```

*base/manifest.yaml*
```
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: git-clone
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: url
      type: string
      description: the url to the project git repository to clone
    - name: subdirectory
      type: string
      description: the subdirectory within the workspace to clone the project within
      default: /
    - name: revision
      type: string
      description: the revision/branch within the project to checkout
  stepTemplate:
    image: alpine/git
  steps:
    - name: git-clone
      args:
        - clone $(params.url) $(workspaces.shared-workspace.path)$(params.subdirectory)
    - name: git-checkout
      args:
        - checkout $(params.revision)

---

apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: checkout
spec:
  taskRef:
    name: git-clone
    kind: ClusterTask
  params:
    - name: url
      value: git@github.com:sauce-consortia/zookeeper.git
    - name: revision
      value: master
  workspaces:
    - name: shared-workspace
      emptyDir: {}
```
