### ISSUE TITLE
Make it possible to extract results from a container's stdout

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#2925]
### Feature request

I'd like to be able to create a Task which provides results with come from the output of a container, without having to capture that input and parse it in my Task.

Initially we could do this only when output is json formatted maybe?

For example do something like this:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: boskos-acquire
spec:
    steps:
    - name: boskosctl
      image: gcr.io/k8s-staging-boskos/boskosctl@sha256:a7fc984732c5dd0b4e0fe0a92e2730fa4b6bddecd0f6f6c7c6b5501abe4ab105 
      args:
      - "acquire"
      - "--server-url=http://boskos.test-pods.svc.cluster.local"
      - "--owner-name=christie-test-boskos"
      - "--type=gke-project"
      - "--state=free"
      - "--target-state=busy"
     results:
     - name: project-id
       description: The name of the project acquired
       fromStep:
       - name: boskosctl
          jsonPath: .name
```

The `fromStep` above would express the jsonpath to the desired value to use as the result, which is expected to be in the stdout of the command.

### Use case

I'm working on a boskos Task as part of the catalog test infrastructure. This is what I'm playing around with now:

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: boskosctl-test-
spec:
  taskSpec:
    steps:
    - image: gcr.io/k8s-staging-boskos/boskosctl@sha256:a7fc984732c5dd0b4e0fe0a92e2730fa4b6bddecd0f6f6c7c6b5501abe4ab105 
      args:
      - "acquire"
      - "--server-url=http://boskos.test-pods.svc.cluster.local"
      - "--owner-name=christie-test-boskos"
      - "--type=gke-project"
      - "--state=free"
      - "--target-state=busy"
```

This lets me acquire a boskos project which is great, but the only way to tell what project I've acquired is to look at the container logs, e.g.:

```
[build-step-unnamed-1] {"type":"gke-project","name":"tekton-prow-6","state":"busy","owner":"christie-test-boskos","lastupdate":"2020-07-09T20:02:41.730506184Z","userdata":{}}
```

So even tho the boskos folks provided this sweet `boskosctl` image with a reasonable `cmd` default, im gonna end up having to override the entrypoint and write a script (and hope that the image has bash in it!)

**Comment by bobcatfish** [comment]
OR another idea that might be much better:

If a step could access the stdout of the previous step, then I could easily have a second container in my task that parses out the project name, e.g. something like:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: boskos-acquire
spec:
    steps:
    - name: boskosctl
      image: gcr.io/k8s-staging-boskos/boskosctl@sha256:a7fc984732c5dd0b4e0fe0a92e2730fa4b6bddecd0f6f6c7c6b5501abe4ab105 
      args:
      - "acquire"
      - "--server-url=http://boskos.test-pods.svc.cluster.local"
      - "--owner-name=christie-test-boskos"
      - "--type=gke-project"
      - "--state=free"
      - "--target-state=busy"
    - name: grab-project-id
      image: ubuntu
      script: |
        echo $(boskosctl.stdout) | jq -r ".name" > /tekton/results/project-id
     results:
    - name: project-id
      description: The name of the project acquired
```

A couple of ways this could work:
- Indicate via variable interpolation when a step would like to be provided with the stdout of a previous step
- Always save the stdout of all steps on disk in a known location

**Comment by vdemeester** [comment]
> So even tho the boskos folks provided this sweet `boskosctl` image with a reasonable `cmd` default, im gonna end up having to override the entrypoint and write a script (and hope that the image has bash in it!)

If `boskosctl` was able to write the result to a file, you could do that and have an extra step (using whatever image you feel like using) to extract some information from that file *to* the results file. (checked the image, there is `/bin/sh` and `bash` too.).

>     * Indicate via variable interpolation when a step would like to be provided with the stdout of a previous step

This could be done the other way, aka specify *for a step* that you want the output to be written to a file so that any next step in that task can do whatever with it. Using variable interpolation to guess that *would* work too, I wonder which approach is the saner, but I lean towards having an explicit way to say "I want the output of this step to be written somewhere" (especially because this doesn't have any implication on the variable interpolation part, it's simple for the user to understand what it is doing).

>     * Always save the stdout of all steps on disk in a known location

I would definitely not want that :upside_down_face: This could create a lot of I/O for all task/step execution where it will not be needed.

**Comment by vdemeester** [comment]
I think we also need to gauge the number of cases where this is required *and* where it would be a pain to do it otherwise (aka when you don't have a wait to write to a file in the image, using a shell or something else).

**Comment by bobcatfish** [comment]
Oh yeah, that's a good point, I guess it is a convention for a lot of tools to output to a file based on a flag 🤔 

However I'd say it's even _more_ common for tools to output to stdout and call it a day - aka relying on ["text streams"](https://en.wikipedia.org/wiki/Unix_philosophy) so it feels to me like there are probably a lot of cases where capturing stdout will be the only way to get the output.

> I would definitely not want that 🙃 This could create a lot of I/O for all task/step execution where it will not be needed.

Maybe a way we could adjust this would be to allow steps to opt into this.

Personally the option I currently like the best is to go the variable substitution route :D

**Comment by sbwsg** [comment]
I actually really really like both the initial proposal - `generate results from a docker image that I don't control but I know where the interesting data is` - and the subsequent proposal - `access stdout from previous steps so I can do cool stuff with it`.  I think these might be worth separating into two issues and pursuing both?

After reading through I think there might also be an alternative for accessing the stdout inspired by the `fromStep` idea: What if Step 2 specified a filter expression for Step 1 to run over its stdout and pass the matches along?  That way we avoid writing _all_ of Step 1 stdout to disk unless the user explicitly supplies like `.*` as a regex filter or something.

**Comment by dlorenc** [comment]
One more possible ux: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter

GitHub actions does something similar with special tokens in the output to denote a value. Probably a bit simpler than json, unless your tool already happens to output things in json. So maybe a tossup?

**Comment by chhsia0** [comment]
@bobcatfish Would you mind reopening this issue?

**Comment by stuarthu** [comment]
maybe you can do sth like:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: boskos-acquire
spec:
    volumes:
      - name: <mountname>
         emptyDir: {}
    steps:
    - name: boskosctl
      image: gcr.io/k8s-staging-boskos/boskosctl@sha256:a7fc984732c5dd0b4e0fe0a92e2730fa4b6bddecd0f6f6c7c6b5501abe4ab105 
      command: [sh]
      args:
      - -c
      - <boskosctl command> > <mountpath/redirectfile>
     volumeMounts:
       - name: <mountname>
          mountPath: <mountpath>
     results:
     - name: project-id
       description: The name of the project acquired
       fromStep:
       - name: boskosctl
          jsonPath: .name
```
