### ISSUE TITLE
precedence order for labels and annotations

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#2934]
When the same label/annotation exists in `Task` and `TaskRun` (with different values), `TaskRun` CRD is created with the values from `Task`. Is this by design? or Should labels from `TaskRun` take higher precedence over `Task`? 

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-hello
  labels:
    foo: task
 spec:
....
---

apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-print-hello
  labels:
    foo: taskrun
spec:
  taskRef:
    name: print-hello

```

=>

```
kubectl get tr -o json | jq .items[].metadata.labels
{
  "app.kubernetes.io/managed-by": "tekton-pipelines",
  "foo": "task",
  "tekton.dev/task": "print-hello"
}
```

Same is happening with `Pipeline` and `PipelineRun`, labels from `PipelineRun` are being overwritten with the labels from `Pipeline`.

/kind question
