### ISSUE TITLE
volumeClaimTemplates do not work if the workspace name has capital letters

### ISSUE THREAD

**Issue by bioball** [tektoncd/pipeline#2941]
# Expected Behavior

It should be possible to use a workspace that has capital letters with volumeClaimTemplates

# Actual Behavior

The run fails because Tekton attempts to create a PVC that has capital letters

# Steps to Reproduce the Problem

1. Use this TaskRun:
    ```yaml
    ---
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      name: test-vct
    spec:
      taskRef:
        name: write-hello
      workspaces:
      - name: myVolumeTemplate
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 100m
            accessModes:
            - ReadWriteOnce
    ---
    apiVersion: tekton.dev/v1beta1
    kind: Task
    metadata:
      name: write-hello
    spec:
      steps:
      - image: ubuntu:latest
        name: hello-0
        script: cat hello > $(workspaces.myVolumeTemplate.path)/hello
      workspaces:
      - name: myVolumeTemplate
    ```
2. Apply it
3. Observe this message in the status:
    ```
    Failed to create PVC for TaskRun default/test-vct workspaces correctly: failed to create PVC myVolumeTemplate-test-vct: PersistentVolumeClaim \"myVolumeTemplate-test-vct\" is invalid: metadata.name: Invalid value: \"myVolumeTemplate-test-vct\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
    ```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-27T11:30:02Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.10.0
Pipeline version: v0.13.0-apple.1
Triggers version: unknown
```

This looks like the source of the error. Seems like there should be some logic here to kebab-case the workspace name when determining the PVC name:

https://github.com/tektoncd/pipeline/blob/7a2bc9cef9f9a2255132aeca8fdbef275d12f89e/pkg/reconciler/volumeclaim/pvchandler.go#L92..L97
