### ISSUE TITLE
Unable to specify SSH port number in Git PipelineResource

### ISSUE THREAD

**Issue by andydude** [tektoncd/pipeline#2949]
# Expected Behavior
```
kind: PipelineResource
spec:
  type: git
  params:
    - name: port
      value: "2222"
```

# Actual Behavior
```
Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository
```
I was also unable to supply a `~/.ssh/config` file via a volume or secret, because I was unable to determine where to put the volume config.
