### ISSUE TITLE
Do not allow extra fields when validating CRDs

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#297]
## Expected Behavior

If I typo a field in an optional field in a CRD (i.e. provide an extra field), the validation webhook (or worst case, runtime check) should tell me the CRD is invalid.

## Actual Behavior

"Extra" fields are ignored, for example in the demo pipeline, there was a bug where one of the instances of `inputSourceBindings` was not renamed to `resources`:

https://github.com/knative/build-pipeline/blob/c9341e7f0e5dae53a4c5b1638401b4d65401f1b3/examples/pipeline.yaml#L24-L44

This was ignored (and everything still worked b/c at that time the Pipeline executed in the order it was declared in).

## Steps to Reproduce the Problem

1. Add an extra invalid field to a CRD, for example you can modify [the build-push.yaml example spec](https://github.com/knative/build-pipeline/blob/master/examples/build-task.yaml) to have the extra field `helloIDoNotBelong: foo`:

```yaml
apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: build-push
  namespace: default
spec:
  helloIDoNotBelong: foo
  inputs:
...
```

2. Apply the CRD:

```bash
kubectl apply -f examples/build-push.yaml
```

3. Notice that it applies just fine and the extra field is ignored!
