### ISSUE TITLE
Improve UX of Step Resource Requests

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/pipeline#2986]
### Feature request

Currently, users have the ability to define resource requests as part of a step for a Task for each step:

```yaml
    steps:
    - name: step1
      image: ...
      command: ...
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi
    - name: step2
      image: ...
      command: ...
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi
```

This is misleading in my opinion because it makes it seem like the user has control of setting the requests for each step. However, only the max requests from all steps are ever used as documented [here](https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#specifying-limitrange-values).

So a user should only have to, at most, define resource requests (the max values needed for a container) once for steps. Maybe it makes sense to allow users to define CPU, memory, and ephemeral storage once as part of a TaskRun and allow this to be configurable for PipelineRuns via taskRunSpecs?

### Use case

Discussed in #2984: https://github.com/tektoncd/pipeline/issues/2984#issuecomment-662402725
Discussed in #2931: https://github.com/tektoncd/pipeline/issues/2931#issuecomment-660245310

The idea has come up a couple times in issues where the experience of requests is confusing for users, and it might help to provide this option and clearly document with better examples.
