### ISSUE TITLE
Allow finally tasks to execute after pipeline timeout

### ISSUE THREAD

**Issue by gpaul** [tektoncd/pipeline#2989]
### Feature request

Tekton recently introduced "Finally Tasks" that execute once a Pipeline succeeds or fails. The [design document](https://docs.google.com/document/d/1lxpYQHppiWOxsn4arqbwAFDo4T0-LCqpNa6p-TJdHrw/) lists the following use cases:

* Cleanup cluster resources after finishing (with success/failure) integration tests (Dogfooding Scenario)
* Update Pull Request with what happened overall in the pipeline (pipeline level)
* Report Test Results at the end of the test pipeline (Notifications Scenario)

These are all legitimate use cases that show the value of the "Finally Tasks at the Pipeline Level" feature.

However, these tasks will not execute in the event that a Pipeline's execution duration exceeds its Timeout value. Pipelines can have unpredictable or highly variable execution times for various reasons: network transfers, access to third-party services, or delayed execution due to resource contention can all lead to a Pipeline unexpectedly exceeding its configured Timeout.

For this reason, it is currently not possible to rely on Finally tasks for any of the aforementioned use cases. They are an elegant optimisation, but do not provide a contract that can be relied upon in general.

This feature request is to extend the existing Finally Task functionality to allow Finally Tasks to execute even if the enclosing PipelineRun times out. This rounds out the Finally Task feature by addressing the common "PipelineRun timeout" edge case.

### Use case

Every reason that one wants Finally Tasks, with the added confidence that they will execute regardless of PipelineRun timeout.

**Comment by dlorenc** [comment]
This is an interesting one - I agree there should be a way to guarantee "finally" runs, but should there be a timeout for that as well?

**Comment by pritidesai** [comment]
This is an interesting indeed and I agree, we should be able to guarantee that `finally` tasks run even the `Pipeline` (that they part of) timeout. This can be configurable and disabled by default.

Today, `pipelineRun` timeout takes the highest precedence and exits with failure if its tasks not able to finish in time.

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-with-timeout
spec:
  timeout: "0h0m3s"
  pipelineSpec:
    tasks:
      - name: echo-good-morning
        timeout: "0h0m30s"
        taskSpec:
          steps:
            - name: echo
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "Good Morning!"
                sleep 60
---
```

PipelineRun failure:

```
 tkn pr describe pipelinerun-with-timeout
Name:        pipelinerun-with-timeout
Namespace:   default
Timeout:     3s
Labels:
 tekton.dev/pipeline=pipelinerun-with-timeout

🌡️  Status

STARTED        DURATION    STATUS
1 minute ago   3 seconds   Failed(PipelineRunTimeout)

💌 Message

PipelineRun "pipelinerun-with-timeout" failed to finish within "3s" (TaskRun "pipelinerun-with-timeout-echo-good-morning-4ksv8" failed to finish within "30s")

📦 Resources

 No resources

⚓ Params

 No params

🗂  Taskruns

 NAME                                                 TASK NAME           STARTED        DURATION     STATUS
 ∙ pipelinerun-with-timeout-echo-good-morning-4ksv8   echo-good-morning   1 minute ago   30 seconds   Failed(TaskRunTimeout)
```

We can have `finally` task take higher precedence (if specified) and overwrite `pipelineRun` timeout (default is 1 hour). `finally` task without any timeout would honor `pipelineRun` timeout (just like today).
