### ISSUE TITLE
Propagate securityContext to Affinity Assistant

### ISSUE THREAD

**Issue by gosharplite** [tektoncd/pipeline#3020]
# Expected Behavior
Affinity Assistant pod should work in a cluster with psp setting.

# Actual Behavior
Affinity Assistant pod won't start since it is trying to run as root.

# Steps to Reproduce the Problem

1. Set a cluster with restricted psp.
2. Start pipelinerun with pv/pvc.
3. Affinity Assistant pod won't start.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: v1.16.6
  Server Version: v1.17.4
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  Client version: 0.11.0
  Pipeline version: v0.14.0
  Triggers version: v0.6.0
  ```

In a cluster with psp enforcement, Affinity Assistant pod will not start unless there is a way to set securityContext.

Below pipelinerun yaml used to work, if the securityContext section can be propagated to Affinity Assistant, it should just work.

I can't find a way to set the securityContext of Affinity Assistant, the workaround seems to use `disable-affinity-assistant`.

```
apiVersion: tekton.dev/v1beta1 
kind: PipelineRun              
metadata:
  name: kpt-fn-porting         
spec:
  serviceAccountName: porting  
  pipelineRef:                 
    name: kpt-fn-porting
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: tekton-porting
  podTemplate:
    nodeSelector:              
      cloudnative.com/district: hk-able
    securityContext:           
      runAsNonRoot: true
      runAsUser: 1001
```
