### ISSUE TITLE
Substitute params by index

### ISSUE THREAD

**Issue by popcor255** [tektoncd/pipeline#3044]
### Feature request
Currently prams can be substituted by key (string substitute). However, params is an array of type param. I would like to reference a parameter by the index in the params array rather than the key.

**TLDR;** `Array of Type Params` is not the same as `Param that is Type Array`. We should probably fix this.

(how array access would look)
Request:
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-task
spec:
  params:
    - name: param
      type: string
  steps:
  - name: alpine
    image: alpine
    command: [ "echo" ]
    args: [ "$(params[0])" ]
```
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-task
spec:
  params:
    - name: param
      type: array
  steps:
  - name: alpine
    image: alpine
    command: [ "echo" ]
    args: [ "$(params[0][*])" ]
```

The above tasks should produce the same result as these tasks:
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-task
spec:
  params:
    - name: param
      type: string
  steps:
  - name: alpine
    image: alpine
    command: [ "echo" ]
    args: [ "$(params.param)" ]
```
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-task
spec:
  params:
    - name: param
      type: array
  steps:
  - name: alpine
    image: alpine
    command: [ "echo" ]
    args: [ "$(params.param[*])" ]
```

These two tasks should produce the same result.
**Note** : This implementation requires indexes to be declared before runtime.

**Comment by bobcatfish** [comment]
Related issue: https://github.com/tektoncd/pipeline/issues/1393 <-- in that issue I believe @skaegi is suggesting a broader syntax for accessing param values (i think jsonpath based?)

I think we could totally tackle the features one at a time if that's easiest, as long as they are all headed in the same direction - and afaik the syntax above _is_ how array access would look?

might be worth bringing up in the API wg too: https://github.com/tektoncd/community/blob/master/working-groups.md#api

**Comment by popcor255** [comment]
I added the example with array types. It is just using bracket annotation instead of dot annotation. However, with bracket annotation we can use the type to distinguish index(int)/key(string).

**Comment by popcor255** [comment]
Quick and Dirty POC: https://github.com/popcor255/pipeline/tree/replace-by-index-without-validation
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-task
spec:
  params:
    - name: param
      type: string
  steps:
  - name: alpine
    image: alpine
    command: [ "echo" ]
    args: [ "$(params.1)" ]
```

**Comment by popcor255** [comment]
The main issue I am trying to highlight is that an `Array of Type Params` is not the same as `Param that is Type Array`. I think there should be a discussion on if there should be some effort on keeping them the same or at the very least have a clear distinction.
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sleepy-with-nested-params
spec:
  params:
    - name: myParams
      type: array
  steps:
  - name: alpine
    image: alpine
    command: [ "echo" ]
    args: [ "$(params.myParams[*])" ]
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: run-with-sleepy-with-nested-params
spec:
  taskRef:
    name: sleepy-with-nested-params
  params:
    - name: myParams
      value:
        - "test=testing"
        - "env=test"
```
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sleepy-with-psuedo-params
spec:
  params:
    - name: test
    - name: env
  steps:
  - name: alpine
    image: alpine
    command: [ "echo" ]
    args: [ "$(params[*])" ]
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: run-with-sleepy-with-psuedo-params
spec:
  taskRef:
    name: sleepy-with-psuedo-params
  params:
    - name: test
      value: testing
    - name: env
      value: testing
```
