### ISSUE TITLE
Tekton should work with  alpine images 

### ISSUE THREAD

**Issue by TheYkk** [tektoncd/pipeline#3057]
# Expected Behavior
Tekton should work with golang alpine image but it won't

# Actual Behavior
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: run-test
      image: golang:1.14-alpine
      workingDir: /workspace/repo
      command: ["go"]
      args: ["test"]
```
```
# runtime/cgo
exec: "gcc": executable file not found in $PATH
FAIL	_/workspace/repo [build failed]
```

When I remove the alpine tag tekton task running

- Kubernetes version:

  **Output of `kubectl version`:**

 ``` Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T14:19:25Z", GoVersion:"go1.13.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6+k3s1", GitCommit:"6f56fa1d68a5a48b8b6fdefa8eb7ead2015a4b3a", GitTreeState:"clean", BuildDate:"2020-07-16T20:46:15Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
```
v0.14.0
```

**Comment by sbwsg** [comment]
```
# runtime/cgo
exec: "gcc": executable file not found in $PATH
FAIL	_/workspace/repo [build failed]
```

This error means you need to run with `CGO_ENABLED=0`.  Update your Task as follows:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: run-test
      image: golang:1.14-alpine
      env:
      - name: CGO_ENABLED # Must include this
        value: "0" # Must include this
      workingDir: /workspace/repo
      command: ["go"]
      args: ["test"]
```
