### ISSUE TITLE
[Performance] Why create dir container takes so long time to finish

### ISSUE THREAD

**Issue by LiYa-Xu** [tektoncd/pipeline#3059]
When I run 100 taskruns together,  the container step_create_dir cost the most  time.
Below is the chart for the container excution time 
<img width="1670" alt="图片" src="https://user-images.githubusercontent.com/35325376/89368465-34964a00-d70e-11ea-997c-c6caae3d4767.png">
I read the doc https://github.com/tektoncd/pipeline/blob/dfb06661f5ef06f32bd44eaa7e0e8878c4c85a45/cmd/entrypoint/README.md, noticed the whole command is 
```
entrypoint \
 -wait_file /tekton/downward/ready \
 -post_file /tekton/tools/0" \
 -wait_file_content  \
 -entrypoint /ko-app/bash -- -args mkdir -p /workspace/git-resource
```
When I run 1 taskrun , the create_dir step just take about 7s, but it's cost more time when run most of taskrun together .
How to cacluate the create_dir conatiner excution time :
```
          container_create_dir_finish_t=$(< ${POD_FILE} jq '.items[] | select(.metadata.name|contains("'"${pod_name}"'")) | .status.containerStatuses[] | select (.name |contains ("step-create-dir-image")) | .state.terminated.finishedAt' | awk -F '"' '{print $2}')
          container_create_dir_start_t=$(< ${POD_FILE} jq '.items[] | select(.metadata.name|contains("'"${pod_name}"'")) | .status.containerStatuses[] | select (.name |contains ("step-create-dir-image")) | .state.terminated.startedAt' | awk -F '"' '{print $2}')
container_dir_t=$container_create_dir_finish_t - $container_create_dir_start_t
```

**Comment by dlorenc** [comment]
@LiYa-Xu could you share the TaskRun you're using?

**Comment by dlorenc** [comment]
Ah, I took a look at your jq query. I think there might be a problem there. The entrypoint binary waits to start until the previous steps are done, so the `containerStatuses.startedAt` and `finishedAt` values are not quite correct. You should look at the `TaskRun.status.steps[].startedAt` and `TaskRun.status.steps[].finishedAt` values instead.

**Comment by LiYa-Xu** [comment]
@dlorenc Thanks for your response. And sorry I am not really understand about this container works,so could you please tell me how create dir container works? Why I  should use the TaskRun.status.steps[].startedAt and TaskRun.status.steps[].finishedAt values instead? 
Below the part of the create conatienr  yaml in  pod  yaml .That's why I  use the containerStatuses.startedAt and finishedAt values to get create dir container  excution time .

```
    name: step-create-dir-image-6s6tp
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://1a92c12926019fe8d933da75b5110aa45e0a03c9b0771c495a6a5f977ffb19e5
        exitCode: 0
        finishedAt: "2020-08-05T03:17:18Z"
        message: '[{"key":"StartedAt","value":"2020-08-05T03:17:18.329Z","resourceRef":{}}]'
        reason: Completed
        startedAt: "2020-08-05T03:16:30Z"
  - containerID: containerd://0c0172cdaac62f97bc52a151eef8f4c493aeed3aa8028f79c37a270ba013fc98
    image: sha256:dd55bafa6d24da6e53a7d755465dbc465ac07accb6fb6e44028944e7f6b3ee9e
    imageID: icr.io/obs/codeengine/tekton-pipeline/git-init-4874978a9786b6625dd8b6ef2a21aa70@sha256:b9bff381188fe222fc4e05b831ccc3847eb384579f177d94e7f4331aa734c523
    lastState: {}
    name: step-git-source-source-67dvj
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://0c0172cdaac62f97bc52a151eef8f4c493aeed3aa8028f79c37a270ba013fc98
        exitCode: 0
        finishedAt: "2020-08-05T03:17:19Z"
        message: '[{"key":"commit","value":"28d7639d4e78fb1185a2ee8534f9c5957e14f0ee","resourceName":"source","resourceRef":{"name":"source"}},{"key":"StartedAt","value":"2020-08-05T03:17:18.569Z","resourceRef":{}}]'
        reason: Completed
        startedAt: "2020-08-05T03:16:30Z"
  - containerID: containerd://10659151580b87289e2dfd0b595893ac9195cd190821c9ceaa1a555f65d034ea
    image: sha256:02911004993b825fc0ddf0df20f133b3b7ce5f185b5adb8c32e84e4ffa2bf13e
    imageID: icr.io/obs/codeengine/tekton-pipeline/imagedigestexporter-6e7c518e6125f31761ebe0b96cc63971@sha256:c1f32ae9cfba9830b8486ee0febc0d1cd94456973010c6eb16e35428786831cf
    lastState: {}
```

**Comment by LiYa-Xu** [comment]
Checked the Taskrun json file , noticed the create dir container finished quickly, but it's cost some senconds in pod json . Do you know why ?  
below is taskrun josn for create_dir step  :
```
            {
                "container": "step-create-dir-image-h9l2h",
                "imageID": "gcr.io/distroless/base@sha256:f79e093f9ba639c957ee857b1ad57ae5046c328998bf8f72b30081db4d8edbe4",
                "name": "create-dir-image-h9l2h",
                "terminated": {
                    "containerID": "containerd://a8d03206c11d7edf1cb098ab84b4c5d8167b411936cfe2ad9d1b51be245369d4",
                    "exitCode": 0,
                    "finishedAt": "2020-08-05T10:41:51Z",
                    "reason": "Completed",
                    "startedAt": "2020-08-05T10:41:51Z"
                }
            }
        ],
```

below is pod json for create_dir step : 
```
            {
                "containerID": "containerd://a8d03206c11d7edf1cb098ab84b4c5d8167b411936cfe2ad9d1b51be245369d4",
                "image": "sha256:4a6f2dfa03471bdef939c3946c8f657a0c7dc69a1d0fe7042c8af8084762dde0",
                "imageID": "gcr.io/distroless/base@sha256:f79e093f9ba639c957ee857b1ad57ae5046c328998bf8f72b30081db4d8edbe4",
                "lastState": {},
                "name": "step-create-dir-image-h9l2h",
                "ready": false,
                "restartCount": 0,
                "started": false,
                "state": {
                    "terminated": {
                        "containerID": "containerd://a8d03206c11d7edf1cb098ab84b4c5d8167b411936cfe2ad9d1b51be245369d4",
                        "exitCode": 0,
                        "finishedAt": "2020-08-05T10:41:51Z",
                        "message": "[{\"key\":\"StartedAt\",\"value\":\"2020-08-05T10:41:51.054Z\",\"resourceRef\":{}}]",
                        "reason": "Completed",
                        "startedAt": "2020-08-05T10:41:47Z"
                    }
                }
            },
```

**Comment by LiYa-Xu** [comment]
@dlorenc  BTW, this just occurred on buildpack ,kaniko has no this issue. And I tried some test, like add steps and remove steps in buildstrategy , found the create dir time is depends on steps number in buildstratyge . When I just define 1 step that's prepare in buildstrategy ,the create dir cost a little time, when I define 6 steps in in buildstrategy,the create dir will cost most of time . So do you know why ? So for create_dir container,It's there any status need to wait for all container ?

**Comment by sbwsg** [comment]
> Why I should use the TaskRun.status.steps[].startedAt and TaskRun.status.steps[].finishedAt values instead?

The way Tekton works is that it spins up all the containers for the TaskRun at the same time.  This is intentional - a Pod can't be updated with extra containers after it starts.

So the problem becomes: if all the containers start at the same time, how do we detect when each "step" actually started and finished?  To do that Tekton records the start time and end time of the step's contents executing.  We do this using Tekton's special "entrypoint" binary that wraps your Step.  The code for the StartedAt time is here: https://github.com/tektoncd/pipeline/blob/3a7a693429c605a67e30efa5b74675e403be79bb/pkg/entrypoint/entrypointer.go#L104-L107 and there's similar code for FinishedAt as well.

**Comment by LiYa-Xu** [comment]
@sbwsg  I see .Thanks for your help . 

Have other questions that have a pod.yaml like below:
```
 kind: Pod
 apiVersion: v1
 metadata:
   generateName: test-pod-
   namespace: test
 spec:
   containers:
     - name: test-pod1
       image: ubuntu:focal-20200720
       command: [ "/bin/bash", "-c", "--" ]
       args: [ "echo 123" ]
     - name: test-pod2
       image: ubuntu:focal-20200720
       command: [ "/bin/bash", "-c", "--" ]
       args: [ "echo 123" ]
     - name: test-pod3
       image: ubuntu:focal-20200720
       command: [ "/bin/bash", "-c", "--" ]
       args: [ "echo 123" ]
     - name: test-pod4
       image: ubuntu:focal-20200720
       command: [ "/bin/bash", "-c", "--" ]
       args: [ "echo 123" ]
     - name: test-pod5
       image: ubuntu:focal-20200720
       command: [ "/bin/bash", "-c", "--" ]
       args: [ "echo 123" ]
     - name: test-pod6
       image: ubuntu:focal-20200720
       command: [ "/bin/bash", "-c", "--" ]
       args: [ "echo 123" ]
     - name: test-pod7
       image: ubuntu:focal-20200720
       command: [ "/bin/bash", "-c", "--" ]
       args: [ "echo 123" ]
     - name: test-pod8
       image: ubuntu:focal-20200720
       command: [ "/bin/bash", "-c", "--" ]
       args: [ "echo 123" ]
   initContainers:
   - name: init-myservice
     image: busybox:1.32.0-glibc
     command: ['sh', '-c', 'echo init;']
   - name: init-mydb
     image: busybox:1.32.0-glibc
     command: ['sh', '-c', 'echo init2;']
```
Then I appiled the 100 pod together with above yaml file , `k get pod -n test -w`  , one of the pod excution timestamp like below : 
```
test-pod-7dq6t   0/8     Pending            0          72s
test-pod-7dq6t   0/8     Pending            0          72s
test-pod-7dq6t   0/8     Init:0/2           0          72s
test-pod-7dq6t   0/8     Init:0/2           0          81s
test-pod-7dq6t   0/8     Init:1/2           0          85s
test-pod-7dq6t   0/8     Init:1/2           0          85s
test-pod-7dq6t   0/8     PodInitializing    0          85s
test-pod-7dq6t   0/8     Completed          0          91s
```
you can see from pod init to all contianer Completed just take 6s.

But when I apply 100 trs with tr.yaml that has 8 steps of it as below ,
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: helloworld-
  namespace: liya-test
spec:
  taskSpec:
    steps:
      - name: helloworld1
        image: ubuntu:focal-20200720
        resources:
          limits:
            cpu: 10m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
        script: echo "123"

     .....
     - name: helloworld8
        image: ubuntu:focal-20200720
        resources:
          limits:
            cpu: 10m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
        script: echo "123"

``` 

 the pod init to first contianer running takes more time 
```
helloworld-cpscb-pod-6ccz6   0/8   Pending   0     0s
helloworld-cpscb-pod-6ccz6   0/8   Pending   0     0s
helloworld-cpscb-pod-6ccz6   0/8   Init:0/3   0     1s
helloworld-cpscb-pod-6ccz6   0/8   Init:0/3   0     1s
helloworld-cpscb-pod-6ccz6   0/8   Init:1/3   0     7s
helloworld-cpscb-pod-6ccz6   0/8   Init:2/3   0     9s
helloworld-cpscb-pod-6ccz6   0/8   PodInitializing   0     12s
helloworld-cpscb-pod-6ccz6   8/8   Running   0     35s
helloworld-cpscb-pod-6ccz6   8/8   Running   0     60s
helloworld-cpscb-pod-6ccz6   6/8   Running   0     62s
helloworld-cpscb-pod-6ccz6   5/8   Running   0     66s
helloworld-cpscb-pod-6ccz6   0/8   Completed   0     67s
```
So I want to know is there have something that the first container waitting for ?I did the test on the same env, that's on IKS cluster with 9  worker nodes(16 cpu, 64 memory),for pod init to first container running excution time , why the pod created by tr takes more time?

**Comment by sbwsg** [comment]
Very interesting results, thankyou!  I don't know the precise answer but it would be worth investigating.

One factor I'm aware of is that the first Step's container waits for a [downward API volume to be populated from an annotation](https://github.com/tektoncd/pipeline/blob/7d7119a583f48fff817f0ccff17cdb949799bb7c/pkg/pod/entrypoint.go#L161-L181). So maybe there is a delay in that annotation being set?  You can check if this is the problem by disabling the downward API requirement.  Change the [running-in-environment-with-injected-sidecars feature flag to "false"](https://github.com/tektoncd/pipeline/blob/7d7119a583f48fff817f0ccff17cdb949799bb7c/config/config-feature-flags.yaml#L53-L60) and apply this to your tekton-pipelines namespace. After the flag is set you can see if this affects startup time.

**Comment by LiYa-Xu** [comment]
@sbwsg Thanks for your response . Yes ,very interesting results. And also the number of the steps in tr.yaml will impact the pod init to first contianer running excution time . 

below is just one step in tr.yaml
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: helloworld-
  namespace: liya-test
spec:
  taskSpec:
    steps:
      - name: helloworld1
        image: ubuntu:focal-20200720
        resources:
          limits:
            cpu: 10m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
        script: echo "123"
```
And below is one of the pod timestamp that created by tr 

```
helloworld-v4s4j-pod-b7q69   0/1   Pending   0     1s
helloworld-v4s4j-pod-b7q69   0/1   Pending   0     2s
helloworld-v4s4j-pod-b7q69   0/1   Init:0/3   0     2s
helloworld-v4s4j-pod-b7q69   0/1   Init:0/3   0     6s
helloworld-v4s4j-pod-b7q69   0/1   Init:1/3   0     7s
helloworld-v4s4j-pod-b7q69   0/1   Init:2/3   0     9s
helloworld-v4s4j-pod-b7q69   0/1   Init:2/3   0     11s
helloworld-v4s4j-pod-b7q69   0/1   PodInitializing   0     12s
helloworld-v4s4j-pod-b7q69   1/1   Running   0     14s
helloworld-v4s4j-pod-b7q69   1/1   Running   0     28s
helloworld-v4s4j-pod-b7q69   0/1   Completed   0     30s
```
