### ISSUE TITLE
branch of submodule option --force is always master?

### ISSUE THREAD

**Issue by GwonsooLee** [tektoncd/pipeline#3080]
In my triggerTemplate, I set resourcetemplates and add a git resource (base-git). An I ran with depth = 0
This works well if my default branch of repository is master. 
But It did not work if I changed default branch to something else and deleted master branch from origin. I recently tend to change default branch of repositories from master to main. 

I am not sure that I missed something to figure this out.. 
Is the branch of submodule always set to master ?
```
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: $(tt.params.NAME)-buildonly-
      namespace: $(tt.params.NAMESPACE)
    spec:
      pipelineRef:
        name: base-pipeline-buildonly
      resources:
      - name: base-git
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.BRANCH)
          - name: url
            value: $(tt.params.REPOSITORY_URL)
          - name: depth
            value: "0"
```

This occurred an error
`git fetch --recurse-submodules=yes origin --update-head-ok --force master`

But this works.
`git fetch --recurse-submodules=yes origin --update-head-ok --force main`
