### ISSUE TITLE
0.15.0:  "TaskRun mounts more than one PersistentVolumeClaim" despite single PVC w/ workspace subDirs

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/pipeline#3085]
I have a task `theTask` with 2 named workspaces:
```
...
  workspaces:

    - name: app-source
      description: The workspace where the app source code resides
      mountPath: /workspace/app-source
      readOnly: false

    - name: secondary-source
      description: The workspace where the secondary source code resides
      mountPath: /workspace/secondary-source
      readOnly: false
...
```

I have a pipeline with 1 workspace that is mapped to the 2 task workspaces via the diffentiating `subPath` flag:
```
    - name: theTask
      taskRef:
        name: theTask

      runAfter: 
        - init

      workspaces:
        - name: secondary-source
          workspace: build-ops
          subPath: secondary-source
        - name: app-source
          workspace: build-ops
          subPath: app-source
    
```

This worked totally fine up to 0.14.3 but now fails with this error in 0.15.0 and broke several functioning pipelines

```
 TaskRun mounts more than one PersistentVolumeClaim - that is forbidden
      when the Affinity Assistant is enabled
```

Related I assume: https://github.com/tektoncd/pipeline/pull/2885

Seems one should still be above to mount a single PVC, which is what this is, its just logically divided by the different subPaths, vs truly separate PVCs which I am not attempting to do.
