### ISSUE TITLE
Able to start pipelinerun from pipelinerun spec without providing value for workspace and the pipelinerun stays is `Running(Started)` state

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/pipeline#3089]
# Expected Behavior
Pipelinerun should fail with some validation error

# Actual Behavior
Pipelinerun starts and stays in `Running(Started)` state

# Steps to Reproduce the Problem

1. Create a task with workspace
2. Create a pipeline with workspace using the above task
3. Create pipelinerun spec file to start the pipelinerun for above pipeline and don't provide any value for the workspace
4. start the pipelinerun using `kubectl apply -f`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b3b92b2", GitCommit:"b3b92b2", GitTreeState:"clean", BuildDate:"2020-07-15T09:27:21Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+012b3ec", GitCommit:"012b3ec", GitTreeState:"clean", BuildDate:"2020-07-24T07:23:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
  ```
  $ tkn version
  Client version: 0.11.0
  Pipeline version: v0.14.3
  Triggers version: v0.6.1
  ```

**Command logs**
```
[varadhya@localhost workspace-testing]$ cat workspace-pipelinerun.yaml 
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-workspace-pipeline-run-7
spec:
  params:
  - name: first-param
    value: simple value
  pipelineRef:
    name: test-workspace-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: shared-workspace
[varadhya@localhost workspace-testing]$ 
[varadhya@localhost workspace-testing]$ oc apply -f workspace-pipelinerun.yaml 
pipelinerun.tekton.dev/test-workspace-pipeline-run-7 created
[varadhya@localhost workspace-testing]$ tkn pr ls --limit 1
NAME                            STARTED          DURATION   STATUS
test-workspace-pipeline-run-7   36 seconds ago   ---        Running(Started)
[varadhya@localhost workspace-testing]$ 
[varadhya@localhost workspace-testing]$ tkn pr describe test-workspace-pipeline-run-7
Name:              test-workspace-pipeline-run-7
Namespace:         veeresh-testing
Pipeline Ref:      test-workspace-pipeline
Service Account:   pipeline
Timeout:           1h0m0s
Labels:
 tekton.dev/pipeline=test-workspace-pipeline

🌡️  Status

STARTED          DURATION   STATUS
49 seconds ago   ---        Running(Started)

📦 Resources

 No resources

⚓ Params

 NAME            VALUE
 ∙ first-param   simple value

🗂  Taskruns

 No taskruns
[varadhya@localhost workspace-testing]$ 
```

**Spec files**
```
[varadhya@localhost workspace-testing]$ cat workspace-task.yml 
apiVersion: tekton.dev/v1beta1 
kind: ClusterTask 
metadata:
  name: test-workspace-clustetask
spec:
  steps:
  - name: write-message
    image: ubuntu
    script: |
      #!/usr/bin/env bash
      set -xe
      echo hello! > $(workspaces.messages.path)/message
      cat $(workspaces.messages.path)/message
  workspaces:
  - name: messages
    description: The folder where we write the message to
[varadhya@localhost workspace-testing]$ 
[varadhya@localhost workspace-testing]$ cat workspace-pipeline.yaml 
apiVersion: tekton.dev/v1beta1 
kind: Pipeline 
metadata:
  name: test-workspace-pipeline
spec:
  params:
    - name: first-param
      description: this is the first param for Pipeline
  workspaces:
    - name: shared-workspace
      description: this is a shared workspace
  tasks:
    - name: first-task
      taskRef:
        name: test-workspace-clustetask
        kind: ClusterTask
      workspaces:
        - name: messages
          workspace: shared-workspace
[varadhya@localhost workspace-testing]$ 
[varadhya@localhost workspace-testing]$ cat workspace-pipelinerun.yaml 
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-workspace-pipeline-run-7
spec:
  params:
  - name: first-param
    value: simple value
  pipelineRef:
    name: test-workspace-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: shared-workspace
[varadhya@localhost workspace-testing]$ 

```

**Comment by bobcatfish** [comment]
Hey @VeereshAradhya we recently added a feature where you can specify a default that is controller wide (https://github.com/tektoncd/pipeline/blob/master/docs/workspaces.md#using-workspaces-in-tasks re `default-task-run-workspace-binding`), so maybe that default is being used?

(I do wonder @sbwsg @jerop if it would make sense to make it more obvious when the default is being used, e.g. require "defualt" is provided for a workspace vs just allowing it)

@VeereshAradhya you might get more info about what's going on if you look at the pod, e.g. `kubectl get pod -l tekton.dev/PipelineRun=test-workspace-pipeline-run-7`

**Comment by sbwsg** [comment]
Hm. This is odd.  I definitely see a problem in the syntax of the PipelineRun:

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-workspace-pipeline-run-7
spec:
  params:
  - name: first-param
    value: simple value
  pipelineRef:
    name: test-workspace-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: shared-workspace
```

Here the PipelineRun is "binding" a Workspace with name `shared-workspace` but isn't actually providing the volume configuration to go with it.  We would normally expect something more along the lines of this:

```
workspaces:
- name: shared-workspace
  persistentVolumeClaim: # ... pvc info ...
```

Our code does [check the number of volume configurations in the binding](https://github.com/tektoncd/pipeline/blob/8573a5d6473b7fa5d4f45cf100c1948fd1abf977/pkg/apis/pipeline/v1beta1/workspace_validation.go#L44-L52) so I am a bit surprised this isn't erroring out here. 

Agree with @bobcatfish that it would be useful to see the pod that was created here.  It would also be useful to know the contents of the default configmap (`kubectl get configmap -n tekton-pipelines config-defaults`).

> (I do wonder @sbwsg @jerop if it would make sense to make it more obvious when the default is being used, e.g. require "defualt" is provided for a workspace vs just allowing it)

I'd like to discuss this a bit more before forming an opinion on it.  It seems, at least initially to me, to be a bit counter to the purpose of the feature to require it be opt-in at the Task/TaskRun level.
