### ISSUE TITLE
PipelineFinally bug or loss of function?

### ISSUE THREAD

**Issue by zops** [tektoncd/pipeline#3092]
**PipelineFinally Doc：**
https://tekton.dev/docs/pipelines/pipelines/#specifying-parameters-in-final-tasks

**Issue：**
The support of params is described in the finally document. However, when params is configured in finally, it is found that variable replacement is not supported.
This is not mentioned in the document. I don't know whether variable is not supported or configuration error.

**Example：**
```
spec:
  params:
    - name: a
  tasks:
    - name: tests
      taskRef:
        name: integration-test
      params:
        - name: a
          value: $(params.a)        # valid variable
  finally:
    - name: report-results
      taskRef:
        Name: report-results
      params:
        - name: a
          value: $(params.a)        # invalid variable
```
