### ISSUE TITLE
As a tekton pipeline user, I want to use liveness/readiness probes to check controller pod health

### ISSUE THREAD

**Issue by xiujuan95** [tektoncd/pipeline#3111]
### Feature request

I want to use liveness and readiness probes to detect if my tekton controller pod is healthy or not. However, seem like liveness and readiness field don't be included in controller deployment:https://github.com/tektoncd/pipeline/blob/master/config/controller.yaml

About this request, actually, I have done some experiments. I configure liveness and readiness like below:
```
livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```

And I check the pod event, it tells me the probes failed:
```
Events:
  Type     Reason     Age                From                  Message
  ----     ------     ----               ----                  -------
  Normal   Scheduled  35m                default-scheduler     Successfully assigned tekton-pipelines/tekton-pipelines-controller-7cd74569b7-mm96v to 10.242.0.19
  Normal   Pulled     35m                kubelet, 10.242.0.19  Container image "icr.io/obs/codeengine/tekton-pipeline/controller-10a3e32792f33651396d02b6855a6e36:v0.14.2-rc2@sha256:845358c3bb68e6900b421545ee40352391baccb751ef63915758016c4745bdbe" already present on machine
  Normal   Created    35m                kubelet, 10.242.0.19  Created container tekton-pipelines-controller
  Normal   Started    35m                kubelet, 10.242.0.19  Started container tekton-pipelines-controller
  Warning  Unhealthy  35m (x2 over 35m)  kubelet, 10.242.0.19  Readiness probe failed: Get http://172.30.18.233:9090/metrics: dial tcp 172.30.18.233:9090: connect: connection refused
  Warning  Unhealthy  35m (x2 over 35m)  kubelet, 10.242.0.19  Liveness probe failed: Get http://172.30.18.233:9090/metrics: dial tcp 172.30.18.233:9090: connect: connection refused
```
However, my pod is still running normally:
```
kubectl get pod -n tekton-pipelines -o wide
NAME                                           READY   STATUS    RESTARTS   AGE   IP               NODE            NOMINATED NODE   READINESS GATES
tekton-pipelines-controller-7cd74569b7-mm96v   1/1     Running   0          52m   172.30.18.233    10.242.0.19     <none>           <none>
```
This is not expected.

BTW, I can do `curl http://localhost:9090/metrics` command successfully within tekton controller container:
```
kubectl exec -ti tekton-pipelines-controller-7cd74569b7-mm96v -n tekton-pipelines sh
sh-4.4# curl http://localhost:9090/metrics
# HELP tekton_client_latency How long Kubernetes API requests take
# TYPE tekton_client_latency histogram
tekton_client_latency_bucket{name="",le="1e-05"} 13
tekton_client_latency_bucket{name="",le="0.0001"} 819
tekton_client_latency_bucket{name="",le="0.001"} 820
tekton_client_latency_bucket{name="",le="0.01"} 826
tekton_client_latency_bucket{name="",le="0.1"} 10358
```
