### ISSUE TITLE
Cannot attach to container with TTY in steps

### ISSUE THREAD

**Issue by tragiclifestories** [tektoncd/pipeline#3118]
This is perhaps more of an edge case than anything else, but I've had to spend a good few hours debugging this so thought it was worth writing up. 

# Expected Behavior

Given a running pod like this:

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: sleepy-time-pod
spec:
  containers:
    - image: ruby
      name: rubby
      tty: true
      command:
        - ruby
        - "-e"
        - "0.upto(100).each { |i| puts i; sleep 1; $stdout.flush }"
```

And a TaskRun like this:

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: tekton-attach-test
spec:
  taskSpec:
    steps:
    - image: bitnami/kubectl
      script: "kubectl attach sleepy-time-pod"
```

I expect the step to run correctly and print out its output:

```
+ kubectl attach sleepy-time-pod
Defaulting container name to rubby.
Use 'kubectl describe pod/sleepy-time-pod -n dispatcher' to see all of the containers in this pod.
If you don't see a command prompt, try pressing enter.
1
2
3
```

# Actual Behavior

kubectl attach errors out cryptically:

```
+ kubectl attach sleepy-time-pod
Defaulting container name to rubby.
Use 'kubectl describe pod/sleepy-time-pod -n dispatcher' to see all of the containers in this pod.
If you don't see a command prompt, try pressing enter.
Error from server:
```

That's an empty string as an error from the server, i haven't just messed up my copy-paste.

# Steps to Reproduce the Problem

See above (you will need to run as a service account with pods:list and pods/attach:create).

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T11:09:22Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.11-gke.5", GitCommit:"baccd25d44f1a0d06ad3190eb508784efbb990a5", GitTreeState:"clean", BuildDate:"2020-06-25T22:55:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
Client version: 0.10.0
Pipeline version: v0.12.0
Triggers version: devel
```

I'm currently trying to reproduce on latest pipeline, but am in RBAC hell ... will update the issue later.

Adding `-ti` to the `kubectl attach` does not fix the problem (you get an additional error message and then the same result):

```
+ kubectl attach -ti sleepy-time-pod
Defaulting container name to rubby.
Use 'kubectl describe pod/sleepy-time-pod -n dispatcher' to see all of the containers in this pod.
Unable to use a TTY - input is not a terminal or the right kind of file
If you don't see a command prompt, try pressing enter.
Error from server:
``` 

## But why on earth would anyone do this?

Internally we a service a little like `heroku run`, which allows people to run code in a particular environment and codebase. This allows us to audit what's being done and why, and where it's being done, rather than just giving people arbitrary access to production which would be risky. Under the hood, this creates a job. It sets `tty: true` in the container spec, because the most common use case is an interactive session to run `rails console` or whatever. We also essentially reproduce the `kubectl attach` functionality with code around the place in client-go.

This solution does 90% of what we need for a particular use case we have for tekton (basically running a known command and waiting for the output and success/failure of that command). Reusing it has proven difficult due to Tekton not being fond of TTYs for some reason. Although it's _prima facie_ nonsensical to start a TTY session from an environment like a tekton step where interactivity is impossible, it shouldn't _matter_ if you do. Or if it does, it ought to 'hard error' with a helpful message if possible.
