### ISSUE TITLE
Feature flags to trim tekton results EOF newlines

### ISSUE THREAD

**Issue by Tomcli** [tektoncd/pipeline#3146]
### Feature request
Related https://github.com/tektoncd/pipeline/issues/2936
Some of our users have pre-defined container that doesn't trim the outputs. It is quite troublesome to ask everyone to fix and rebuild their container especially when we are building a pipeline that's depended on each other's work. Is it possible to add a feature flag for Tekton to handle it? Thank you in advance.

Here is an example to reproduce this:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-params
spec:
  params:
  - name: project_name
    value: 'a-project'
  - name: notebook_name
    value: 'a-notebook'
  pipelineSpec:
    params:
    - name: project_name
    - name: notebook_name
    tasks:
    - name: find-project
      params:
      - name: project_name
        value: $(params.project_name)
      taskSpec:
        params:
        - name: project_name
        results:
        - description: /tmp/outputs/project/data
          name: project
        steps:
        - command:
          - sh
          - -ex
          - -c
          - "echo \"$0\" > \"$1\""
          - $(inputs.params.project_name)
          - $(results.project.path)
          image: alpine:3.12
          name: main
    - name: find-asset
      params:
      - name: find-project-project
        value: $(tasks.find-project.results.project)
      - name: notebook_name
        value: $(params.notebook_name)
      taskSpec:
        params:
        - name: find-project-project
        - name: notebook_name
        steps:
        - command:
          - sh
          - -ex
          - -c
          - "echo \"'$0'\"\n echo \"'$1'\""
          - $(inputs.params.find-project-project)
          - $(inputs.params.notebook_name)
          image: alpine:3.12
          name: main
```

Tracking issue on our repo: https://github.com/kubeflow/kfp-tekton/issues/273

/cc @pritidesai @animeshsingh

**Comment by sbwsg** [comment]
Thanks for the issue report.  This has also recently come up in the context of stdout / stderr capture ([comment thread here](https://github.com/tektoncd/community/pull/182#discussion_r473280490)).

I agree I think this would be useful.  Here's the way it might work:

```
# in a TaskSpec
results:
- name: my-result
  description: Foo bar result description.
  trimWhitespace: true
```

I hesitate to add yet more flags to the entrypoint binary so I think right now my preference would be that the Tekton Controller is responsible for performing the trimming after the result is sent back to it but that's an implementation detail.  I'll write a TEP for it.
