### ISSUE TITLE
Add variable expansion in the workspaces.mountPath field of Tasks

### ISSUE THREAD

**Issue by coryrc** [tektoncd/pipeline#3152]
# Expected Behavior

If a Task has `spec.workspaces[].mountPath: "$(params.dest-dir)"` then said workspace should be mounted to the expanded value; i.e. if dest-dir is `/tmp`.

I believe it is supposed to be because I see examples of it used [in the catalog](https://github.com/tektoncd/catalog/blob/a9600e084a52cf54e578a316aff2f11f5731a98c/task/golang-test/0.1/golang-test.yaml#L38).

# Actual Behavior

It gets mounted to the literal directory `/$(params.dest-dir)`, as in this line from `mount`:
`[unit-tests : execute] /dev/sdb on /$(params.dest-dir) type ext4 (rw,relatime)`

# Steps to Reproduce the Problem

I believe it should fail to even be `kubectl create`'d if it is interpreting these right, so `kubectl create -f` on this file should fail if it is working correctly:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: no-mountpath-expansion
spec:
  workspaces:
    - name: source
      mountPath: "$(params.invalid-parameter)"
  params:
    - name: valid-parameter
  steps:
    - image: debian:buster
      workingDir: $(params.valid-parameter)
      script: |
        echo hello world                                                                                                                                         
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

Client version: 0.12.0
Pipeline version: v0.15.2
Triggers version: unknown

**Comment by sbwsg** [comment]
Hey, thanks for the issue report. Tekton Pipelines doesn't support using variables in the workspaces.mountPath field.  We document all the places we do accept variables here: https://github.com/tektoncd/pipeline/blob/master/docs/variables.md#fields-that-accept-variable-substitutions

I'm going to update the label to `kind/feature`.

It looks like you've identified a bug in the golang-test catalog task: it shouldn't be using a variable in the mountpath.  I'll write up an issue over there to capture it and I'll have a quick scan through to see if I can find similar errors.  Thanks again.

/kind feature

**Comment by coryrc** [comment]
@sbwsg In my case, there's an image with an existing GOPATH setup (with bin/, src/...). What I want to do is allow the user to say "mount this and only this module" aka mount `knative.dev/serving` from this workspace into the image's `$GOPATH/src`; if you mount the root to `$GOPATH/src` you clobber whatever is preexisting in the image (which is what I ended up doing), which is exactly what the golang-test Task is trying to do.

**Comment by sbwsg** [comment]
Gotcha, thanks!  Can a symlink work here ala:

```bash
  workspaces:
  - name: source
  steps:
  # ...
    script: |
      ln -s /workspace/source $GOPATH/src/$(params.package)
      cd $GOPATH/src/$(params.package)
      go test $(params.flags) $(params.packages)
```

Similarly in cases where a symlink isn't suitable can `cp` fill the gap instead?

The reason I'm hesitant to implement this today is that the feature request is made much more tricky because our variable resolution process only happens once and `$(workspaces.foo.path)` is already a variable we expose.  What does this mean?  It means that if `mountPath` can itself contain variables then we'll need two iterations of variable resolution: first resolve all the params that might appear in `mountPath`, then resolve any uses of `workspaces.foo.path`.

Having written all that I do think we're going to need recursive or multi-pass variable resolution at some point but I would _much_ prefer that we don't write this ourselves and instead lean on something like [JSONPath](https://github.com/tektoncd/pipeline/issues/1393).

**Comment by khalkie** [comment]
> The reason I'm hesitant to implement this today is that the feature request is made much more tricky because our variable resolution process only happens once and $(workspaces.foo.path) is already a variable we expose. What does this mean? It means that if mountPath can itself contain variables then we'll need two iterations of variable resolution: first resolve all the params that might appear in mountPath, then resolve any uses of workspaces.foo.path.

I think this will work properly with the change as I implemented because `createPod` resolves `ApplyWorkspaces` last, meaning that any mountPath variables would already have been expanded before the value is applied to anywhere that `$(workspaces.foo.path)` is requested

**Comment by coryrc** [comment]
Symlink didn't work pre-Go-modules and I haven't tried since.

Me personally, I mostly care that there aren't any examples or catalog Tasks showing things that don't work.

**Comment by sbwsg** [comment]
> I think this will work properly with the change as I implemented because createPod resolves ApplyWorkspaces last, meaning that any mountPath variables would already have been expanded before the value is applied to anywhere that $(workspaces.foo.path) is requested

Indeed I'm not trying to say it can't be done, more that it gets progressively more brittle the more special-cases and ordering-specific variable replacements we add over time.

I don't feel strongly enough to want to push back any further - I think the use case is totally valid.  Just hesitant about making the current variable replacement logic progressively more complicated.

**Comment by sbwsg** [comment]
> Symlink didn't work pre-Go-modules and I haven't tried since.

Thanks for this feedback - I think I'm going to update the golang tasks in our catalog to mount the workspace at its default path and then `cp -R` the source code from there in to the package's directory.

We also have another workaround starting with version 0.17 for this problem: you can add your own `volumeMount` in a Task that points to a workspace volume.  Then you can give that volumeMount a variable-interpolated `mountPath`.  Here's a snippet of the golang-test task updated to use this method:

```yaml
  workspaces:
  - name: source
  steps:
  - name: unit-test
    image: golang:$(params.version)
    workingDir: /workspace/src/$(params.package)
    volumeMounts:
    - name: $(workspaces.source.volume)
      mountPath: /workspace/src/$(params.package)
```

So the workspace volume gets mounted twice: first it gets mounted to /workspace/source (its default mount point) and then it also gets another mount point at `/workspace/src/path/to/package`.

Even though this works I'm still going to update the golang tasks in the catalog.  They've been in a broken state for far too long and we don't need to wait for a new feature to land to get them working.
