### ISSUE TITLE
admission plugin \"MutatingAdmissionWebhook\" failed to complete mutation in 13s

### ISSUE THREAD

**Issue by grebit** [tektoncd/pipeline#3164]
# Expected Behavior
Creating a task through TKN or OpenShift should be completed without errors

# Actual Behavior
kubectl apply -f task.yml -v=9 ( Sample task )

Output:

```
  "message": "error when applying patch:\n{\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"tekton.dev/v1beta1\\\",\\\"kind\\\":\\\"Task\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"example-task\\\",\\\"namespace\\\":\\\"openshift-pipelines\\\"},\\\"spec\\\":{\\\"params\\\":[{\\\"name\\\":\\\"appName\\\",\\\"type\\\":\\\"string\\\"}],\\\"steps\\\":[{\\\"command\\\":[\\\"/bin/bash\\\",\\\"-c\\\",\\\"echo\\\",\\\"$(inputs.params.appName)\\\"],\\\"image\\\":\\\"registry.redhat.io/ubi7/ubi-minimal\\\"}]}}\\n\"}},\"spec\":{\"steps\":[{\"command\":[\"/bin/bash\",\"-c\",\"echo\",\"$(inputs.params.appName)\"],\"image\":\"registry.redhat.io/ubi7/ubi-minimal\"}]}}\nto:\nResource: \"tekton.dev/v1beta1, Resource=tasks\", GroupVersionKind: \"tekton.dev/v1beta1, Kind=Task\"\nName: \"example-task\", Namespace: \"openshift-pipelines\"\nObject: \u0026{map[\"apiVersion\":\"tekton.dev/v1beta1\" \"kind\":\"Task\" \"metadata\":map[\"creationTimestamp\":\"2020-09-02T18:48:50Z\" \"generation\":'\\x01' \"name\":\"example-task\" \"namespace\":\"openshift-pipelines\" \"resourceVersion\":\"49871974\" \"selfLink\":\"/apis/tekton.dev/v1beta1/namespaces/openshift-pipelines/tasks/example-task\" \"uid\":\"83a37d88-56fb-4040-ac9a-324c6c097bac\"] \"spec\":map[\"params\":[map[\"name\":\"appName\" \"type\":\"string\"]] \"steps\":[map[\"command\":[\"/bin/bash\" \"-c\" \"echo\" \"$(inputs.params.appName)\"] \"image\":\"registry.redhat.io/ubi7/ubi-minimal\" \"name\":\"\" \"resources\":map[]]]]]}\nfor: \"task.yml\": Internal error occurred: admission plugin \"MutatingAdmissionWebhook\" failed to complete mutation in 13s",
  "reason": "InternalError",
  "details": {
    "causes": [
      {
        "message": "admission plugin \"MutatingAdmissionWebhook\" failed to complete mutation in 13s"
      }
    ]
  },
  "code": 500
}]
```

# Steps to Reproduce the Problem

1. kubectl apply -f task.yml -v=9 ( Sample task )
2. creating a task in openshift
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1+9d33dd3", GitCommit:"9d33dd3", GitTreeState:"clean", BuildDate:"2020-06-21T18:17:38Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.9.0
Pipeline version: v0.11.3
```

**Comment by bobcatfish** [comment]
hi @grebit ! Are you able to share the tsk.yaml (or an edited version) that had this problem?

You also might find more useful info in the logs for the webhook controller itself, e.g. you could use a command like `kubectl -n tekton-pipelines logs $(kubectl -n tekton-pipelines get pods -l app=tekton-pipelines-webhook -o name)` to get the logs

**Comment by grebit** [comment]
Hi @bobcatfish,

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: example-task
  namespace: openshift-operators
spec:
  params:
    - name: appName
      type: string
  steps:
    - image: registry.redhat.io/ubi7/ubi-minimal
      command:
        - /bin/bash
        - '-c'
        - echo
        - $(inputs.params.appName)
```

This is the last log after executing:
<img width="1437" alt="Schermafbeelding 2020-09-02 om 22 01 20" src="https://user-images.githubusercontent.com/56537348/92030784-d63da500-ed67-11ea-83f5-6deecd4e9274.png">

**Comment by bobcatfish** [comment]
Thanks @grebit !

You might be having trouble because of `$(inputs.params.appName)` <-- this is the v1alpha1 syntax, [the v1beta1 syntax](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#specifying-parameters) is `$(params.appName)` - hopefully that fixes it but meanwhile it's not great that that would make the admission controller request time out 😬

**Comment by grebit** [comment]
@bobcatfish thank you, but how to fix this? Where should I make this change? 

Thanks!

**Comment by bobcatfish** [comment]
If you change your tsk.yaml to the following and apply it, do you still get the error?

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: example-task
  namespace: openshift-operators
spec:
  params:
    - name: appName
      type: string
  steps:
    - image: registry.redhat.io/ubi7/ubi-minimal
      command:
        - /bin/bash
        - '-c'
        - echo
        - $(params.appName)
```

(note the last line changed from $(inputs.params.appName) to $(params.appName))

**Comment by grebit** [comment]
Ah, sorry. But anyway, still the same error.. 

<img width="1438" alt="Schermafbeelding 2020-09-02 om 23 08 52" src="https://user-images.githubusercontent.com/56537348/92036936-47358a80-ed71-11ea-8fb8-cc191c9ee905.png">

**Comment by bobcatfish** [comment]
Hm that's pretty weird. I didn't see anything useful in those logs, I wonder if:

1. You could find relevant logs with something like `kubectl -n tekton-pipelines logs $(kubectl -n tekton-pipelines get pods -l app=tekton-pipelines-webhook -o name) | grep example-task`
2. Are there any other admission controllers running in your environment?

The other thing I would try is making your Task as simple as possible and seeing if this keeps happening, e.g. something with the bare minimum fields like:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: example-task
  namespace: openshift-operators
spec:
  steps:
    - image: registry.redhat.io/ubi7/ubi-minimal
```

It kind of seems like your webhook controller might be in a bad state - I wonder if this could be an openshift specific thing?

**Comment by grebit** [comment]
Sadly enough still the same story..

```
$ oc get MutatingWebhookConfiguration
NAME                                                   CREATED AT
openshift-operators.servicemesh-resources.maistra.io   2020-07-08T08:08:37Z
webhook.pipeline.tekton.dev                            2020-09-02T19:47:13Z
webhook.triggers.tekton.dev                            2020-09-02T19:47:30Z
```

```
$ oc get ValidatingWebhookConfiguration
NAME                                                   CREATED AT
autoscaling.openshift.io                               2020-06-05T07:03:22Z
config.webhook.pipeline.tekton.dev                     2020-09-02T19:47:13Z
config.webhook.triggers.tekton.dev                     2020-09-02T19:47:30Z
multus.openshift.io                                    2020-06-05T06:47:45Z
openshift-operators.servicemesh-resources.maistra.io   2020-07-08T08:08:37Z
validation.webhook.pipeline.tekton.dev                 2020-09-02T19:47:13Z
validation.webhook.triggers.tekton.dev                 2020-09-02T19:47:30Z
```

**Comment by chmouel** [comment]
humm this is pretty weird as this task is pretty stand and works on openshift, how did you install tekton on openshift? via the operators or via the upstream release.yaml ?

**Comment by grebit** [comment]
We're installing it with Ansible and ArgoCD:

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    app.kubernetes.io/instance: openshift-operators
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
spec:
  channel: ocp-4.5
  installPlanApproval: Manual
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-pipelines-operator.v1.0.1
```

When running the command ```oc get ev``` there are no resources found

**Comment by grebit** [comment]
Could it be a issue in the SVC?

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    manifestival: new
  creationTimestamp: "2020-09-02T19:47:14Z"
  labels:
    app: tekton-pipelines-webhook
    pipeline.tekton.dev/release: v0.11.3
    role: webhook
    version: v0.11.3
  name: tekton-pipelines-webhook
  namespace: openshift-pipelines
  ownerReferences:
  - apiVersion: operator.tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Config
    name: cluster
    uid: 85142baf-7eee-468e-95a5-a14697fad2e1
  resourceVersion: "49899069"
  selfLink: /api/v1/namespaces/openshift-pipelines/services/tekton-pipelines-webhook
  uid: fe37826d-fe4f-4c87-9a49-eea1f16eb7a4
spec:
  clusterIP: 172.30.217.231
  ports:
  - name: http-metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: http-profiling
    port: 8008
    protocol: TCP
    targetPort: 8008
  - name: https-webhook
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: tekton-pipelines-webhook
    role: webhook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by bobcatfish** [comment]
@grebit quick update: it seems like this might be something specific to how tekton is installed and working in the openshift context so i think this will have to be left in the hands of folks with more openshift experience, e.g. @chmouel

**Comment by bobcatfish** [comment]
Okay but before I completely give up I do have one idea/thought: have you upgraded at all or did you install 0.11.3 first?

0.11.0 was our beta release which added a new "api type", v1beta1. I believe the definitions for each CRD actually point to a webhook to use to "convert" between the old version (v1alpha1) and the new version (v1beta1) ( @vdemeester and @jlpettersson and @chhsia0 and some other folks have more expertise here) - i wonder if that could be misconfigured somehow?

For example in the task crd definition:

https://github.com/tektoncd/pipeline/blob/9bc3fd8097e13eecc28f6afe165bfb91bf55f42c/config/300-task.yaml#L57-L61

I wonder if this could be wrong, and/or if you might have an old version of https://github.com/tektoncd/pipeline/blob/master/config/300-task.yaml ?

That's my last guess anyway!

**Comment by grebit** [comment]
@bobcatfish if I'm looking in to the CustomResourceDefinition tasks.tekton.dev I'm seeing this:
```
spec:
  conversion:
    strategy: None
```

Looking at the installed operator I'm seeing this versions:
OpenShift-Pipelines: v0.11.3
OpenShift-Pipelines-Triggers: v0.4.0
OpenShift-Pipelines-ClusterTasks: v0.11

**Comment by chmouel** [comment]
pinging @nikhil-thomas if you are aware of this issue with the operator.

**Comment by Chimney42** [comment]
Hi,
I'm having the same issue on our brand new OCP 4 cluster, running OpenShift 4.5.9 
Tekton/Openshift Pipelines was installed through the Operator (1.0.1 provided by Red Hat) provided by OperatorHub
OpenShift-Pipelines: v0.11.3
OpenShift-Pipelines-Triggers: v0.4.0
OpenShift-Pipelines-ClusterTasks: v0.11

This happens even if I try to apply a tasks through the Openshift Web Console
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: example-task
  namespace: openshift-pipelines
spec:
  steps:
    - image: registry.redhat.io/ubi7/ubi-minimal
      command:
        - /bin/bash
        - '-c'
        - echo
        - "Hello world"
```
An error occurred
Error "admission plugin "MutatingAdmissionWebhook" failed to complete mutation in 13s" for field "undefined".


(I already tried changing inputs.params.appName to params.appName, it doesn't change the error)
I also checked the logs of the tekton-pipelines-webhook pod, to no avail. Nothing about task creation was logged.

I also found this bugreport https://access.redhat.com/solutions/5340011
A temporary solution was to restart the master-controller. Additionally, I restarted the tekton-pipelines-controller and the tekton-pipelines-webhook pods, but this didn't fix it for me either. 
It would be great, to get an update on this asap, as we are completely unable to use Openshift Pipelines atm.

**Comment by vdemeester** [comment]
@Chimney42 do you happen to run a network policy in your cluster ?

**Comment by Chimney42** [comment]
> @Chimney42 do you happen to run a network policy in your cluster ?

Yes indeed. They belong to a differnt service though and shouldn't interefere (theoretically)
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-in-same-namespace
  namespace: openshift-pipelines
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
  policyTypes:
    - Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-to-deployment-status-service
  namespace: openshift-pipelines
spec:
  podSelector:
    matchLabels:
      np/deployment-status-service: provider
  ingress:
    - ports:
        - protocol: TCP
          port: 3000
      from:
        - namespaceSelector:
            matchLabels:
              np/openshift: consumer
  policyTypes:
    - Ingress
```
