### ISSUE TITLE
Tekton pipeline and kubernetes network policy issue. 

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#3172]
After adding  network policy,
``` Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=30s: context deadline exceeded ```

**Comment by sbwsg** [comment]
We will likely need more information in order to help you debug effectively.  What was the content of the network policy?  What platform are you running Tekton on (bare metal / openshift / gke / etc...)?  What versions of Kubernetes and Tekton are you running?  How did you deploy Tekton - using operator or applying YAMLs manually?

/kind question

**Comment by zeromsi** [comment]
Following is my network policy. tekton-pipeline & tekton namespaces have a label role: klovercloud
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allowed-namespaces
  namespace: tekton
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          role: klovercloud
  - from:
    - namespaceSelector:
        matchLabels:
          role: kube-system
  podSelector: {}
  policyTypes:
  - Ingress
 ```

I'm using bare metal cluster. 
Kubernetes version: ```1.17```, tekton: ```0.15```. I deployed tekton by ``` https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml```
