### ISSUE TITLE
Jest Tests fail only when running on Tekton

### ISSUE THREAD

**Issue by nmousouros** [tektoncd/pipeline#3192]
I am using Tekton on Openshift. 

We are trying to migrate from GitHub Actions to Tekton.

When we run our nodejs tests locally they run just fine, when we run it on GitHub Actions or just running the commands in a Dockerfile it works as expected but when running on Tekton with nodejs image or ubuntu or centos I get the same errors. 

Anyone know what could be going wrong? Attached the log file.
[yarn-install.log](https://github.com/tektoncd/pipeline/files/5202192/yarn-install.log)

**Comment by sbwsg** [comment]
From the log I can only really tell that there are syntax errors, which I'd usually attribute to configuration problems.  It's difficult to say how this could be Tekton related without seeing the Tekton resources.  Can you isolate this problem to a single minimal Task & TaskRun and then post those YAMLs?  Remember to remove any sensitive information before posting.

**Comment by nmousouros** [comment]
I'm pretty sure there are not syntax errors, I cannot give the source code to test but when I am running locally this commands it work:

yarn install
yarn bootstrap
yarn compile
yarn test:ci

Also I created this Dockerfile to test, it also does work all the test are finishing succesfully if I run it with docker podman or on openshift


`FROM node:latest
ENV GITHUB_TOKEN *** 
ENV NPM_TOKEN ***
RUN git clone https://***:***@github.com/Marlow-Navigation/zeus.git
WORKDIR zeus
RUN yarn install
RUN yarn bootstrap
RUN yarn compile
RUN yarn test:ci
` 
However when running this task that ( from my understanding) does pretty much the same thing I get all this syntax errors and I am wondering what could the difference be. ( Now the task is using centos but I tried with node:latest and other images as well)

`apiVersion: tekton.dev/v1beta1
kind: Task
  name: yarn-install
spec:
  resources:
    inputs:
      - name: zeus-repo
        type: git
  steps:
    - command:
        - sh
        - '-c'
        - >-
           `cd` /workspace/zeus-repo/ && ls -a && curl --silent --location
          https://rpm.nodesource.com/setup_14.x | bash - && curl --silent
          --location https://dl.yarnpkg.com/rpm/yarn.repo | tee
          /etc/yum.repos.d/yarn.repo  && yum install yarn -y && yarn install &&
          export PATH="$PATH:`yarn global bin`" && yarn bootstrap && yarn
          compile && yarn test:ci
      env:
        - name: NPM_TOKEN
          valueFrom:
            secretKeyRef:
              key: NPM_TOKEN
              name: secure-properties
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: GITHUB_TOKEN
              name: secure-properties
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              key: NODE_ENV
              name: secure-properties
      envFrom:
        - secretRef:
            name: secure-properties
      image: 'centos:latest'
      name: yarninstall
      resources: {}
      securityContext:
        privileged: true
        runAsUser: 0
`

**Comment by sbwsg** [comment]
Yeah, it's difficult to nail down what Tekton could be doing to mess things up here. I think we'd definitely need more info about what's different in the Tekton-run container vs the others.  Couple things I notice:

1. Mixing `env` and `envFrom`.  I think you only need 1 of those?
2. I think you can use the `workingDir` field in the Step to set the directory where you want the commands to run from, eliminating the `cd`
3. Instead of passing `sh` as the command you can use a script block:
```yaml
script: |
  ls -a
  curl --silent --location https://rpm.nodesource.com/setup_14.x | bash -
  curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
  yum install yarn -y
  yarn install
  export PATH="$PATH:`yarn global bin`"
  yarn bootstrap
  yarn compile
  yarn test:ci
```

I would be surprised if any of these fix your problem though.  One thing you can try is to add a `sleep` into the `script` like this:

```yaml
script: |
  ls -a
  curl --silent --location https://rpm.nodesource.com/setup_14.x | bash -
  curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
  yum install yarn -y
  export PATH="$PATH:`yarn global bin`"
  sleep 10000
```

Then use `kubectl exec -it <name of pod> -c <name of Step container> -- /bin/sh` to run a shell in the Step and start poking around trying to find out why things are not working.  e.g. checking `env` returns the values you expect, checking what happens when you run the `yarn` commands manually etc...

One final idea: Have you tried writing a plain Pod with a container that also runs these commands?  Something like this:

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: foo-pod
spec:
  containers:
    - command:
        - sh
        - '-c'
        - >-
           yum install -y git && mkdir /workspace && git clone <repo> /workspace/zeus-repo &&
          `cd` /workspace/zeus-repo/ && ls -a && curl --silent --location
          https://rpm.nodesource.com/setup_14.x | bash - && curl --silent
          --location https://dl.yarnpkg.com/rpm/yarn.repo | tee
          /etc/yum.repos.d/yarn.repo  && yum install yarn -y && yarn install &&
          export PATH="$PATH:`yarn global bin`" && yarn bootstrap && yarn
          compile && yarn test:ci
      env:
        - name: NPM_TOKEN
          valueFrom:
            secretKeyRef:
              key: NPM_TOKEN
              name: secure-properties
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: GITHUB_TOKEN
              name: secure-properties
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              key: NODE_ENV
              name: secure-properties
      envFrom:
        - secretRef:
            name: secure-properties
      image: 'centos:latest'
      name: yarninstall
      resources: {}
      securityContext:
        privileged: true
        runAsUser: 0
```

If this Pod also exhibits the same problem then there's something more general going on, otherwise it does look like Tekton is modifying something that's causing Jest to choke.  If this Pod works then you can compare the Pod that Tekton created for the TaskRun with the Pod you ran and see if there are any obvious differences that might explain the different jest behaviour.
