### ISSUE TITLE
Failed to delete StatefulSet "affinity-assistant-9edfd8d72f" not found

### ISSUE THREAD

**Issue by abudavis** [tektoncd/pipeline#3205]
After a successful Pipelinerun (which references a PVC, see below) on OpenShift 4.5 Tekton Pipelines, I get continuous alerts on the dashboard stating "failed to delete StatefulSet affinity-assistant-9edfd8d72f: statefulsets.apps "affinity-assistant-9edfd8d72f" not found"

Wonder what is causing this, however the Pipelines seem to run OK.

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clonegit-pipelinerun
spec:
  pipelineRef:
    name: clonegit-pipeline
  params:
    - name: gitUrl
      value: https://github.com/xxx.git
    - name: gitRevision
      value: master
  serviceAccountName: pipeline
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: picalc-source-pvc
```
