### ISSUE TITLE
Provide shell-escaped parameters for `script:`

### ISSUE THREAD

**Issue by coryrc** [tektoncd/pipeline#3226]
### Feature request

Provide `$(params.<name>.escaped)` where the value has been escaped à la `printf '%q'` (see [this](https://unix.stackexchange.com/questions/379181/escape-a-variable-for-use-as-content-of-another-script) or [this](https://stackoverflow.com/a/6306730).

It is currently impossible to safely or robustly use variable expansion safely in `script:`; i.e. imagine trying to do 
`echo "$(params.name)"` where someone made their name `"$(rm -fR /)`. 

### Use case

Allow `script:`s to work robustly in the face of special characters.

**Comment by coryrc** [comment]
This could also be accomplished if inputs were available like results i.e. `/tekton/params/var` holds the contents of parameter `var`

**Comment by coryrc** [comment]
My current workaround is using env var:

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: test-substitution-
spec:
  params:
    - name: in
      value: "\"`date`\""
  taskSpec:
    params:
      - name: in
    steps:
      - image: debian:buster
        env:
          - name: DANGER
            value: $(params.in)
        # The first line runs date
        # The second does not
        script: |
          echo "$(params.in)"
          echo "${DANGER}"
```
