### ISSUE TITLE
Task's declared required resources are missing from the TaskRun

### ISSUE THREAD

**Issue by grebit** [tektoncd/pipeline#3245]
Playing around with tasks for a while but it doesn't matter if I change the order of the spec. If keeps saying Task's declared required resources are missing from the TaskRun

# Expected Behavior
Running task without error

# Actual Behavior
Error: ```Task's declared required resources are missing from the TaskRun```

# Steps to Reproduce the Problem

1. tkn task create -f java-gradle-test-task.yml
2. tkn task start java-gradle-test-task --showlog
3.

# Additional Info

java-gradle-test-task.yml
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: java-gradle-test-task
  namespace: helixs-tst
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: gradle-image
        type: string
        default: 'gradle:jdk8'
      - name: pathToContext
        type: string
        default: /workspace/source
  stepTemplate:
    env:
      - name: GRADLE_USER_HOME
        value: $(inputs.resources.source.path)
  steps:
    - args:
        - '-c'
        - |
          set -e
          ./gradlew check
      command:
        - /bin/bash
      image: $(params.gradle-image)
      name: test
      resources: {}
      workingDir: $(inputs.resources.source.path)
```

- Kubernetes version:

  ```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1+9d33dd3", GitCommit:"9d33dd3", GitTreeState:"clean", BuildDate:"2020-06-21T18:17:38Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

```
Client version: 0.9.0
Pipeline version: v0.11.3
```

**Comment by ImJasonH** [comment]
Does this happen because of `resources: {}` ?  Does it stop happening if you remove that line?

**Comment by grebit** [comment]
> Does this happen because of `resources: {}` ? Does it stop happening if you remove that line?

No sadly enough not. When leaving this empty it still creates `resources:{}`

When I create the task with tkn task create -f java-gradle-test-task.yml it adds this automatically.

**Comment by bobcatfish** [comment]
hey @grebit !  a couple things:

* Like @ImJasonH was pointing out, i dont think steps have a "resources" field
* [in v1beta1, there is no "inputs" section](https://github.com/tektoncd/pipeline/blob/master/docs/migrating-v1alpha1-to-v1beta1.md#changes-to-fields)
* if you still have trouble, is it possible to see what the created taskrun looks like? if you are using tkn to create it, i wonder if tkn is not realizing you need the resources since the inputs.params/inputs.resources sections are in v1alpha1 format

**Comment by ImJasonH** [comment]
> Like @ImJasonH was pointing out, i dont think steps have a "resources" field

Steps _do_ have a `resources:` field, to configure the amount of CPU/RAM resources to request/limit each step to.

I didn't realize until this comment that the Task indeed does specify `inputs` which isn't valid in v1beta1. That's likely the cause of the error, though it seems like we could use a better error message in that case 🤔

**Comment by grebit** [comment]
> > Like @ImJasonH was pointing out, i dont think steps have a "resources" field
> 
> Steps _do_ have a `resources:` field, to configure the amount of CPU/RAM resources to request/limit each step to.
> 
> I didn't realize until this comment that the Task indeed does specify `inputs` which isn't valid in v1beta1. That's likely the cause of the error, though it seems like we could use a better error message in that case 🤔

But looking at this, it's the same setup right? Or are I'm looking wrong?

```
# Task.yaml (v1beta1)
spec:
  resources:
    inputs:
    - name: src-repo
      type: git
    outputs:
    - name: baked-image
      type: image
```

**Comment by grebit** [comment]
This is by the way the result of the taskrun:

```
status:
  completionTime: '2020-09-16T14:37:53Z'
  conditions:
    - lastTransitionTime: '2020-09-16T14:37:53Z'
      message: build failed for unspecified reasons.
      reason: Failed
      status: 'False'
      type: Succeeded
```

**Comment by vdemeester** [comment]
@grebit there is a few things:
- `tkn` is 0.9.0. I am not sure if that version of `tkn` asked interactively for resources to bind or not. Does it ? If it doesn't ask for anything when you issue `tkn task start …`, then you either need to specify the resource manually *or* upgrade you `tkn` version (0.12.1 is the latest as of today) to have this interactiveness.
- The task yaml specified shouldn't be accepted *at all* by the webhook, it's not a valid `v1beta1` object.

cc @piyush-garg @pradeepitm12 @danielhelfand on this (for `tkn` version, interactive and all)

**Comment by bobcatfish** [comment]
Hey again @grebit !

Echoing what @vdemeester pointed out, I'm not sure how to repro this b/c like he said:

> The task yaml specified shouldn't be accepted at all by the webhook, it's not a valid v1beta1 object.


I tried to reproduce it with this task definition (slightly different from yours above but I think the same in the important areas):

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: repro-resources
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: gradle-image
        type: string
        default: 'gradle:jdk8'
      - name: pathToContext
        type: string
        default: /workspace/source
  stepTemplate:
    env:
      - name: GRADLE_USER_HOME
        value: $(inputs.resources.source.path)
  steps:
    - args:
        - '-c'
        - |
          echo "hello $(params.gradle-image) $(params.pathToContext) $GRADLE_USER_HOME"
      command:
        - /bin/sh
      image: busybox
      name: test
      resources: {}
      workingDir: $(inputs.resources.source.path)
```
I tried this with both the current HEAD commit (6d8f4513213a0a85f5164e0ed13b8a15c1839f89) and I tried v0.11.3 and both times I got:

```
Error from server (BadRequest): error when creating "foo.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "inputs"
```

I tried changing it to v1alpha1:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: repro-resources
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: gradle-image
        type: string
        default: 'gradle:jdk8'
      - name: pathToContext
        type: string
        default: /workspace/source
  stepTemplate:
    env:
      - name: GRADLE_USER_HOME
        value: $(inputs.resources.source.path)
  steps:
    - args:
        - '-c'
        - |
          echo "hello $(params.gradle-image) $(params.pathToContext) $GRADLE_USER_HOME"
      command:
        - /bin/sh
      image: busybox
      name: test
      resources: {}
      workingDir: $(inputs.resources.source.path)
```

And I was able to run it successfully:

```
tkn task start repro-resources --showlog
? Choose the git resource to use for source: repro-git (https://github.com/tektoncd/pipeline.git)
? Value for param `gradle-image` of type `string`? (Default is `gradle:jdk8`) foo-bar
? Value for param `pathToContext` of type `string`? (Default is `/workspace/source`) /workspace/source
```

I got the logs:

```yaml
[test] hello foo-bar /workspace/source /workspace/source
```

I'm using a newer version of tkn (built from source maybe a month ago?) tho.

Do you have any more info on how we can repro this @grebit ?
