### ISSUE TITLE
Missing Documentation for config-defaults configmap

### ISSUE THREAD

**Issue by cgruver** [tektoncd/pipeline#3249]
I need help defining a default pod template in the `config-defaults` configmap.

I have tried several attempts, but none seem to have any effect on a pipeline run.

Current attempt:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
  name: config-defaults
  namespace: openshift-pipelines
  ownerReferences:
    - apiVersion: operator.tekton.dev/v1alpha1
      kind: Config
      name: cluster
      uid: ac5b1aca-bcfb-4d1e-a6ff-1582da12b4e7
      controller: true
      blockOwnerDeletion: true
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
data:
  default-pod-template: |
    apiVersion: v1
    kind: PodTemplate
    metadata:
      name: tekton-task-pod-template
      labels:
        app: tekton
    template:
      spec:
        securityContext:
          seLinuxOptions:
            level: 's0:c25,c0'
          runAsUser: 1000640000
          fsGroup: 1000640000
  default-service-account: pipeline
```

**Comment by cgruver** [comment]
The following works:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
  name: config-defaults
  namespace: openshift-pipelines
  ownerReferences:
    - apiVersion: operator.tekton.dev/v1alpha1
      kind: Config
      name: cluster
      uid: ac5b1aca-bcfb-4d1e-a6ff-1582da12b4e7
      controller: true
      blockOwnerDeletion: true
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
data:
  default-service-account: pipeline
  default-pod-template: |
    securityContext:
      seLinuxOptions:
        level: 's0:c25,c0'
      runAsUser: 1000640000
      fsGroup: 1000640000
```
