### ISSUE TITLE
Build failed for unspecified reasons and Task's declared required resources are missing from the TaskRun

### ISSUE THREAD

**Issue by grebit** [tektoncd/pipeline#3251]
# Expected Behavior
Running the pipeline without any errors

# Actual Behavior
During the run of the pipeline we are getting unexpected results. At the moment, the most recent problem is this: "build failed for unspecified reasons." 

When the task only get started we are getting the following error:
```
Error: task animal-app-java-gradle-task has failed: invalid input resources: Task's declared required resources are missing from the TaskRun: [source]
```

# Steps to Reproduce the Problem

1. Creating tasks, resources and pipeline
2. Starting the pipeline
3. 

# Additional Info

resources.yml:
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-backend-build-image
  namespace: tst
spec:
  params:
    - name: url
      value: >-
        image-registry.openshift-image-registry.svc:5000/tst/app-backend:latest
  type: image

---------------------------

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-repository
  namespace: tst
spec:
  params:
    - name: url
      value: 'git@bitbucket.org:tst/tst.git'
    - name: revision
      value: feature/tst-254
  type: git
```

task.yml:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace:tst
  name: app-java-gradle-task
  labels:
    app.kubernetes.io/instance: tst
    version: 0.0.0
spec:
  params:
    - default: 'gradle:jdk8'
      name: gradle-image
      type: string
    - default: build
      description: The gradle tasks to run
      name: tasks
      type: string
  resources:
    inputs:
      - name: source
        type: git
  stepTemplate:
    env:
      - name: GRADLE_USER_HOME
        value: $(resources.inputs.source.path)
    name: ''
    resources: {}
  steps:
    - args:
        - |-
          set -e
          echo Running gradle task $(params.tasks)
          ./gradlew $(params.tasks)
      command:
        - /bin/bash
        - '-c'
      image: 'gradle:jdk8'
      name: gradle
      resources: {}
      workingDir: $(resources.inputs.source.path)
```

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1+9d33dd3", GitCommit:"9d33dd3", GitTreeState:"clean", BuildDate:"2020-06-21T18:17:38Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
Client version: 0.9.0
Pipeline version: v0.11.3
```

**Comment by coryrc** [comment]
v1beta1 does not support `resources:`

**Comment by coryrc** [comment]
you cannot have:
```
  resources:
    inputs:
      - name: source
        type: git
```

**Comment by grebit** [comment]
Ok. But how should I define the resources then in the task? Because when I'm running the pipeline we can choose the git repository and image but still getting the error that the resources are missing within the taskrun.

**Comment by coryrc** [comment]
https://tekton.dev/docs/pipelines/migrating-v1alpha1-to-v1beta1/#pipelineresources-and-catalog-tasks

**Comment by grebit** [comment]
I changed a couple of things. But still getting this error: ```invalid input resources: Task's declared required resources are missing from the TaskRun: [animal-app-repository]```


task.yml
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace: tst
  name: app-java-gradle-task
  labels:
    app.kubernetes.io/instance: tst
    version: 0.0.0
spec:
  params:
    - name: gradle-image
      default: 'gradle:jdk8'
      type: string
    - name: tasks
      default: build
      type: string
  resources:
    inputs:
    - name: app-repository
      type: git
    outputs:
    - name: app-backend-build-image
      type: image
  stepTemplate:
    env:
      - name: GRADLE_USER_HOME
        value: $(resources.inputs.app-repository.path)
    name: ''
    resources: {}
  steps:
    - args:
        - |-
          set -e
          echo Running gradle task $(params.tasks)
          ./gradlew $(params.tasks)
      command:
        - /bin/bash
        - '-c'
      image: 'gradle:jdk8'
      name: gradle
      resources: {}
      workingDir: $(resources.inputs.app-repository.path)
```

taskrun.yml
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: animal-app-backend-taskrun
  namespace: helixs-tst
spec:
  taskRef:
    name: animal-app-java-gradle-task
  resources:
    inputs:
    - name: animal-app-repository
      resourceSpec:
        type: git
        params:
          - name: revision
            value: feature/H2C-254
          - name: url
            value: git@bitbucket.org:crv4all/animal.git
    outputs:
    - name: animal-app-backend-build-image
      resourceSpec:
        type: image
        params:
        - name: url
          value: image-registry.openshift-image-registry.svc:5000/helixs-tst/animal-app-backend:latest
```

**Comment by coryrc** [comment]
You are still using PipelineResources with v1beta1

**Comment by grebit** [comment]
> You are still using PipelineResources with v1beta1

What do you exactly mean?

**Comment by grebit** [comment]
When I'm removing the pipeline resources in the task I'm getting the following questions asked as input

```
$ tkn pipeline start app-backend-pipeline --showlog
no PipelineResource of type "image" found in namespace: tst
Please create a new "image" resource for PipelineResource "app-backend-build-image"
? Enter a name for a pipeline resource : 
```

**Comment by coryrc** [comment]
`apiVersion: tekton.dev/v1beta1`

https://tekton.dev/docs/pipelines/migrating-v1alpha1-to-v1beta1/#pipelineresources-and-catalog-tasks

**Comment by grebit** [comment]
Could you please help me out? Because looking at the documentation it looks like it's setup well and how it should be

**Comment by vdemeester** [comment]
@coryrc it's definitely still possible to use `PipelineResource` with `v1beta1`. They are not "supported" in a "we may break you in the future" kinda of way, but you can still use them :wink:.

@grebit so few things:
1. `app-backend-build-image` doesn't seem to be used anywhere (so it might not be needed at all)
2. if you define a `taskrun.yaml`, you don't need to use `tkn task start`, but just applying the `taskrun.yaml`. When you do a `tkn task start` (or `tkn pipeline start`), it will use the flags for the params and resources (and/or ask you question interactively), and will create the `TaskRun` or `PipelineRun` on its own (not reading any `taskrun.yaml` or `pipelinerun.yaml`).
3. you are starting a `pipeline`, can you share the definition with it ? There might be something missing in the pipeline definition.

> ```
> $ tkn pipeline start app-backend-pipeline --showlog
> no PipelineResource of type "image" found in namespace: tst
> Please create a new "image" resource for PipelineResource "app-backend-build-image"
> ? Enter a name for a pipeline resource : 
> ```

This is the interactive feature of `tkn` :wink:

**Comment by grebit** [comment]
@vdemeester thank you for your reaction. 

This is the pipeline:

```
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: app-backend-pipeline
  namespace: tst
spec:
  resources:
    - name: app-backend-build-image
      type: image
    - name: app-repository
      type: git
  tasks:
    - name: java-gradle-pipeline-task
      params:
        - name: tasks
          value: >-
            check -x :animal-client:buildClient -x :animal-client:yarn -x
            :animal-client:check -x app:server-api:asciidoctor --stacktrace
      taskRef:
        kind: Task
        name: app-java-gradle-task
```

**Comment by vdemeester** [comment]
@grebit right, so this seems to be the problem, you need to *pass* the resources to the task when referencing it in `tasks`. Tekton doesn't implicitly pass all pipeline resources to all tasks — one reason is that they don't necessarily share the same name in the pipeline and task definitions.

```
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: app-backend-pipeline
  namespace: tst
spec:
  resources:
    - name: app-backend-build-image
      type: image
    - name: app-repository
      type: git
  tasks:
    - name: java-gradle-pipeline-task
      params:
        - name: tasks
          value: >-
            check -x :animal-client:buildClient -x :animal-client:yarn -x
            :animal-client:check -x app:server-api:asciidoctor --stacktrace
      resources:
        inputs:
        - name: app-repository
          resource: app-repository
        outputs:
        - name: app-backend-build-image
          resource: app-backend-build-image
      taskRef:
        kind: Task
        name: app-java-gradle-task

```

**Comment by grebit** [comment]
Thank you for your help. When I'm running the pipeline I'm getting now the following error...

```
invalid input params: didn't need these params but they were provided anyway: [tasks]
```

**Comment by vdemeester** [comment]
@grebit can you do a `kubectl get app-java-gradle-task -o yaml` ? seems like the version you have in your cluster of that task doesn't have a `tasks` parameter :thinking: (which is weird because given the tasks you shared above, it should)

**Comment by grebit** [comment]
@vdemeester thank you for your reaction. Hereby the task:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: "2020-09-17T23:55:35Z"
  generation: 1
  labels:
    app.kubernetes.io/instance:tst
    version: 0.0.0
  name: app-java-gradle-task
  namespace: tst
  resourceVersion: "59337542"
  selfLink: /apis/tekton.dev/v1beta1/namespaces/tst/tasksapp-java-gradle-task
  uid: 705df92c-7fbe-4c38-b817-39e1cc64c2a0
spec:
  params:
  - default: git@bitbucket.org:tst/tst.git
    description: git url to clone
    name: url
    type: string
  - default: feature/tst
    description: git revision to checkout (branch, tag, sha, ref…)
    name: revision
    type: string
  - default: ""
    description: (optional) git refspec to fetch before checking out revision
    name: refspec
    type: string
  - default: "true"
    description: defines if the resource should initialize and fetch the submodules
    name: submodules
    type: string
  - default: "1"
    description: performs a shallow clone where only the most recent commit(s) will
      be fetched
    name: depth
    type: string
  - default: "true"
    description: defines if http.sslVerify should be set to true or false in the global
      git config
    name: sslVerify
    type: string
  - default: ""
    description: subdirectory inside the "output" workspace to clone the git repo
      into
    name: subdirectory
    type: string
  - default: "false"
    description: clean out the contents of the repo's destination directory (if it
      already exists) before trying to clone the repo there
    name: deleteExisting
    type: string
  - default: gradle:jdk8
    description: The image where tasks are running
    name: image
    type: string
  results:
  - description: The precise commit SHA that was fetched by this Task
    name: commit
  steps:
  - image: $(params.image)
    name: clone
    resources: {}
    script: |
      CHECKOUT_DIR="$(workspaces.output.path)/$(params.subdirectory)"
      cleandir() {
        # Delete any existing contents of the repo directory if it exists.
        #
        # We don't just "rm -rf $CHECKOUT_DIR" because $CHECKOUT_DIR might be "/"
        # or the root of a mounted volume.
        if [[ -d "$CHECKOUT_DIR" ]] ; then
          # Delete non-hidden files and directories
          rm -rf "$CHECKOUT_DIR"/*
          # Delete files and directories starting with . but excluding ..
          rm -rf "$CHECKOUT_DIR"/.[!.]*
          # Delete files and directories starting with .. plus any other character
          rm -rf "$CHECKOUT_DIR"/..?*
        fi
      }

      if [[ "$(params.deleteExisting)" == "true" ]] ; then
        cleandir
      fi

      /ko-app/git-init \
        -url "$(params.url)" \
        -revision "$(params.revision)" \
        -refspec "$(params.refspec)" \
        -path "$CHECKOUT_DIR" \
        -sslVerify="$(params.sslVerify)" \
        -submodules="$(params.submodules)" \
        -depth "$(params.depth)"
      cd "$CHECKOUT_DIR"
      RESULT_SHA="$(git rev-parse HEAD | tr -d '\n')"
      EXIT_CODE="$?"
      if [ "$EXIT_CODE" != 0 ]
      then
        exit $EXIT_CODE
      fi
      # Make sure we don't add a trailing newline to the result!
      echo -n "$RESULT_SHA" > $(results.commit.path)
  workspaces:
  - description: The git repo will be cloned onto the volume backing this workspace
    name: output
```

**Comment by vdemeester** [comment]
> @vdemeester thank you for your reaction. Hereby the task:
> 
> ```
> apiVersion: tekton.dev/v1beta1
> kind: Task
> metadata:
>   creationTimestamp: "2020-09-17T23:55:35Z"
>   generation: 1
>   labels:
>     app.kubernetes.io/instance:tst
>     version: 0.0.0
>   name: app-java-gradle-task
>   namespace: tst
>   resourceVersion: "59337542"
>   selfLink: /apis/tekton.dev/v1beta1/namespaces/tst/tasksapp-java-gradle-task
>   uid: 705df92c-7fbe-4c38-b817-39e1cc64c2a0
> spec:
>   params:
>   - default: git@bitbucket.org:tst/tst.git
>     description: git url to clone
>     name: url
>     type: string
>   - default: feature/tst
>     description: git revision to checkout (branch, tag, sha, ref…)
>     name: revision
>     type: string
>   - default: ""
>     description: (optional) git refspec to fetch before checking out revision
>     name: refspec
>     type: string
>   - default: "true"
>     description: defines if the resource should initialize and fetch the submodules
>     name: submodules
>     type: string
>   - default: "1"
>     description: performs a shallow clone where only the most recent commit(s) will
>       be fetched
>     name: depth
>     type: string
>   - default: "true"
>     description: defines if http.sslVerify should be set to true or false in the global
>       git config
>     name: sslVerify
>     type: string
>   - default: ""
>     description: subdirectory inside the "output" workspace to clone the git repo
>       into
>     name: subdirectory
>     type: string
>   - default: "false"
>     description: clean out the contents of the repo's destination directory (if it
>       already exists) before trying to clone the repo there
>     name: deleteExisting
>     type: string
>   - default: gradle:jdk8
>     description: The image where tasks are running
>     name: image
>     type: string
>   results:
>   - description: The precise commit SHA that was fetched by this Task
>     name: commit
>   steps:
>   - image: $(params.image)
>     name: clone
>     resources: {}
>     script: |
>       CHECKOUT_DIR="$(workspaces.output.path)/$(params.subdirectory)"
>       cleandir() {
>         # Delete any existing contents of the repo directory if it exists.
>         #
>         # We don't just "rm -rf $CHECKOUT_DIR" because $CHECKOUT_DIR might be "/"
>         # or the root of a mounted volume.
>         if [[ -d "$CHECKOUT_DIR" ]] ; then
>           # Delete non-hidden files and directories
>           rm -rf "$CHECKOUT_DIR"/*
>           # Delete files and directories starting with . but excluding ..
>           rm -rf "$CHECKOUT_DIR"/.[!.]*
>           # Delete files and directories starting with .. plus any other character
>           rm -rf "$CHECKOUT_DIR"/..?*
>         fi
>       }
> 
>       if [[ "$(params.deleteExisting)" == "true" ]] ; then
>         cleandir
>       fi
> 
>       /ko-app/git-init \
>         -url "$(params.url)" \
>         -revision "$(params.revision)" \
>         -refspec "$(params.refspec)" \
>         -path "$CHECKOUT_DIR" \
>         -sslVerify="$(params.sslVerify)" \
>         -submodules="$(params.submodules)" \
>         -depth "$(params.depth)"
>       cd "$CHECKOUT_DIR"
>       RESULT_SHA="$(git rev-parse HEAD | tr -d '\n')"
>       EXIT_CODE="$?"
>       if [ "$EXIT_CODE" != 0 ]
>       then
>         exit $EXIT_CODE
>       fi
>       # Make sure we don't add a trailing newline to the result!
>       echo -n "$RESULT_SHA" > $(results.commit.path)
>   workspaces:
>   - description: The git repo will be cloned onto the volume backing this workspace
>     name: output
> ```

This tasks looks like the [`git-clone`](https://github.com/tektoncd/catalog/blob/master/task/git-clone/0.2/git-clone.yaml) from the catalog and nothing like the one you shared above. You or something may have overwritten it but it's definitely not the right task.

**Comment by grebit** [comment]
@vdemeester sorry, hereby the right one:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    version: 0.0.0
  name: java-gradle-task
  namespace: tst
spec:
  params:
  - default: gradle:jdk8
    name: gradle-image
    type: string
  - default: build
    description: The gradle tasks to run
    name: tasks
    type: string
  resources:
    inputs:
    - name: source
      type: git
  stepTemplate:
    env:
    - name: GRADLE_USER_HOME
      value: $(resources.inputs.source.path)
    name: ""
    resources: {}
  steps:
  - args:
    - |-
      set -e
      echo Running gradle task $(params.tasks)
      ./gradlew $(params.tasks)
    command:
    - /bin/bash
    - -c
    image: gradle:jdk8
    name: gradle
    resources: {}
    workingDir: $(resources.inputs.source.path)
```

**Comment by grebit** [comment]
I build a other pipeline with tasks and clustertask. Now I'm getting a error at the first task again:

```
task test has failed: build failed for unspecified reasons.
```

Logs in the pipeline run are showing this:
```
STEP-GIT-SOURCE-HERDOPTIMIZER-REPO-BHJMN
```

**Comment by grebit** [comment]
The code I'm using:

I created the key with the following cmd:
```
ssh-keygen -C "openshift-source-builder/git@bitbucket.org:tst/tst.git" -f repository-at-bitbucket -N  ' '  
```

```
Name:         repository-at-bitbucket
Namespace:    pipeline-tst
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/ssh-auth

Data
====
ssh-privatekey:  2720 bytes
```

Task:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    version: 0.0.0
  name: java-gradle-task
  namespace: pipeline-tst
spec:
  params:
    - default: 'gradle:jdk8'
      name: gradle-image
      type: string
    - default: build
      description: The gradle tasks to run
      name: tasks
      type: string
  resources:
    inputs:
      - name: source
        type: git
  stepTemplate:
    env:
      - name: GRADLE_USER_HOME
        value: $(resources.inputs.source.path)
    name: ''
    resources: {}
  steps:
    - args:
        - |-
          set -e
          echo Running gradle task $(params.tasks)
          ./gradlew $(params.tasks)
      command:
        - /bin/bash
        - '-c'
      image: 'gradle:jdk8'
      name: gradle
      resources: {}
      workingDir: $(resources.inputs.source.path)
```

Taskrun:
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: tst-task-run
  namespace: pipeline-tst
spec:
  serviceAccountName: pipeline
  taskRef:
    name: java-gradle-task
  resources:
     inputs:
      - name: source
        resourceRef:
          name: tst-repo
      - name: image
        resourceRef:
          name: tst-img
```

**Comment by sbwsg** [comment]
The secrets for Git SSH require some extra annotations to have them picked up by Tekton. See the [auth.md](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#configuring-ssh-auth-authentication-for-git) doc for more info.

**Comment by grebit** [comment]
Yes, I know. Even when I'm using the all annotations it still giving me errors:

```
status:
  completionTime: '2020-09-23T16:07:28Z'
  conditions:
    - lastTransitionTime: '2020-09-23T16:07:28Z'
      message: build failed for unspecified reasons.
      reason: Failed
      status: 'False'
      type: Succeeded
```
