### ISSUE TITLE
Support Workspaces' `bound` value as an available variable in WhenExpressions

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#3275]
### Feature request

A Pipeline author should be able to skip or include Tasks in a Pipeline based on whether an optional workspace has been bound by a PipelineRun.

Example syntax:

```yaml
tasks:
- name: fetch-dependencies-if-no-build-cache-provided
  when
    - input: "$(workspaces.build-cache.bound)"
      operator: in
      values: ["false"]
  workspaces:
  - name: dependencies
    workspace: build-cache
  taskRef:
    name: fetch-dependencies
```

In this example the `fetch-dependencies-if-no-build-cache-provided` task will only run if the Pipeline's optional `build-cache` workspace was not provided in a PipelineRun.

### Use case

A Pipeline accepts an optional build cache workspace. If the build cache is not provided then an additional Task should run to fetch dependencies and populate a PVC which will be used by a later build Task.  A PipelineRun that supplies the build cache is able to run faster because this dependency fetch is skipped.
