### ISSUE TITLE
Tasks can have duplicate mountPath values if they are substituted with variables

### ISSUE THREAD

**Issue by khalkie** [tektoncd/pipeline#3295]
# Expected Behavior

When you create a Task, it is validated to ensure all the mountPath values are different.  For example, the following snippet of a Task cannot be created

  ```
....
workspaces:
    - name: source
      mountPath: $(params.input-path)
      readOnly: false
    - name: secondsource
      mountPath: $(params.input-path)
....

validation failed: workspace mount path "$(params.input-path)" must be unique: workspaces.mountpath
```

According to the unique mountPath validation, I would expect that it should not be possible to have duplicate mountPaths for different workspaces.

# Actual Behavior

Using variable substitution, you can assign different mountPath values via different variable names, which will allow the Task to be created.  It is then possible that the different variables will evaluate to the same value, which will result in different mountPaths having non-unique values

(Task created successfully with two different mountPath variables)
````
..... 
  workspaces:
    - name: source
      mountPath: $(params.input-path)
      readOnly: false
    - name: secondsource
      mountPath: $(params.second-input-path)
.....
````

In the TaskRun, I can set both variables to the same value, resulting in two workspaces with duplicate mountPath values

````
.....
  params:
    - name: input-path
      value: theparampath
    - name: second-input-path
      value: theparampath
.......
````

The TaskRun runs, without validation errors.

# Steps to Reproduce the Problem

1.  Create a Task which binds to two or more workspaces.  Set the mountPath values via variable substitution.
2. In a TaskRun or PipelineRun, set the parameter values such that two or more mountPath values are duplicates
3. No validation errors, the Task runs

# Additional Info

- Kubernetes version:

 Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Tekton Pipeline version:

Client version: 0.11.0
Pipeline version: devel
Triggers version: unknown
