### ISSUE TITLE
Volume name differs between $(workspaces.foo.volume) and actual Volume/VolumeMount config 

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#3312]
# Expected Behavior

The `$(workspaces.foo.volume)` variable should match whatever the Volume/VolumeMount for a TaskRun's Pod gets named.  E.g. if my workspace, `foo` gets assigned the random name `ws-12345` then this name should appear in the Volume/VolumeMount config of the Pod _and_ should be rendered the same in a Step's Script block using the `$(workspaces.foo.volume)` variable.

# Actual Behavior

The config that appears in the Pod and the rendered variable in the script differ.

# Steps to Reproduce the Problem

1. Apply the following TaskRun and look at the volume / volumemount config of the pod vs the output of the script:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: fooconf
data:
  foo: bar
---
kind: TaskRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: footr
spec:
  workspaces:
  - name: stuff
    configMap:
      name: fooconf
  taskSpec:
    workspaces:
    - name: stuff
    steps:
    - image: alpine
      script: |
        echo "volume mount: $(workspaces.stuff.volume)"
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

latest master branch

**Comment by pritidesai** [comment]
@sbwsg what are the consequences of this mismatch names? any impact on any of the runs?

**Comment by sbwsg** [comment]
> @sbwsg what are the consequences of this mismatch names? any impact on any of the runs?

Ah, good question. The specific issue I was having was that I couldn't add a volumeMount to a sidecar so that a workspace could be shared:

```yaml
# in a taskspec
workspaces:
- name: ws1
sidecars:
- image: fooimage
  volumeMounts:
  - name: $(workspaces.ws1.volume)
    mountPath: $(workspaces.ws1.path)
```

Here ^ the volume name that the `volumeMount` saw didn't match the one that the workspace was actually mounted with.  This produced a fatal error like `"No volume with name ws-abcdef exists"` because the volume actually had the name `ws-ghijk`.
