### ISSUE TITLE
Json tags on ArrayOrString are misleading

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/pipeline#3323]
https://github.com/tektoncd/pipeline/blob/78f54793880f4494e6d5748d7c27cb8633164148/pkg/apis/pipeline/v1beta1/param_types.go#L92-L96

Json tags here are misleading as `ArrayOrString` uses custom marshalling.
It confuses tools like kubebuilder and probably other tools potentially leading to incorrect generated code.

**Comment by sbwsg** [comment]
We should take a look at kubernete's IntOrString type for comparison here.

**Comment by sbwsg** [comment]
Looks like they don't have tags for json: https://github.com/kubernetes/apimachinery/blob/master/pkg/util/intstr/intstr.go#L40

**Comment by eddycharly** [comment]
Nope, k8s tooling usually has some special code for handling the IntOrString case (some specific open api tag, x-int-or-string, something like this).

From what I understand it’s not possible to represent the ArrayOrString pattern with the structural schema définition constraint that Kubernetes adds on top of open api.

**Comment by eddycharly** [comment]
I feel like the only think we can do here if we don’t want to break compatibility is to ignore the value field and add the preserve unknown field tag :(

**Comment by eddycharly** [comment]
For more context : the doc about structural schema definition (particularly the IntOrString struct) https://kubernetes.io/blog/2019/06/20/crd-structural-schema/#extensions.

And the way controller-tools takes care of IntOrString : https://github.com/kubernetes-sigs/controller-tools/blob/2f203e490e8af05e988fdac460151ff3a93f3ee7/pkg/crd/known_types.go#L91-L100

**Comment by eddycharly** [comment]
More docs https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#intorstring

And a simple example:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: my-crds.my-group.io
spec:
  group: my-group.io
  names:
    kind: my-crd
    plural: my-crds
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            test:
              oneOf:
                - type: integer
                - type: array
                  items: string

```

Will result in:
```
The CustomResourceDefinition "my-crds.my-group.io" is invalid: 
* spec.validation.openAPIV3Schema.properties[test].oneOf[0].type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[test].oneOf[1].type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[test].type: Required value: must not be empty for specified object fields
```
