### ISSUE TITLE
Is there a way to set dynamic the task name?

### ISSUE THREAD

**Issue by shibumi** [tektoncd/pipeline#3352]
Hi,
I have the following problem. I have a build pipeline that shall build multiple docker images. Every build task looks pretty much the same. For example:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace: project-tekton
  name: ocpp-server-build
spec:
  params:
    - name: DOCKERFILE
      type: string
      description: The path to the dockerfile to build
      default: $(resources.inputs.docker-source.path)/build/package/ocpp-server.Dockerfile
    - name: CONTEXT
      type: string
      default: $(resources.inputs.docker-source.path)
    - name: HARBOR
      type: string
      default: harbor.mydomain.tld/project/ocpp-server
  resources:
    inputs:
      - name: docker-source
        type: git
  steps:
    - name: determine-git-tag
      image: harbor.mydomain.tld/project/alpine-helm:3.9.6
      script: |
        #!/bin/bash
        cd $(params.CONTEXT)
        VERSION=$(git describe --abbrev=0 --tags)
        echo "Creating tekton-git-tag file with: $VERSION"
        # remove v from version tag for docker
        echo "$VERSION" > $(params.CONTEXT)/tekton-git-tag
        echo "Switching to $VERSION"
        git checkout "$VERSION"
        if [ -z $VERSION ]; then
          echo "Git tag is empty"
          exit 1
        fi

    - name: build-and-push-image
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      image: gcr.io/kaniko-project/executor:debug #debug is used because we need a shell to be able to use cat.
      script: |
        #!/busybox/sh
        echo "Pushing to $(params.HARBOR):$(cat $(params.CONTEXT)/tekton-git-tag)"
        /kaniko/executor --dockerfile=$(params.DOCKERFILE) --context=$(params.CONTEXT) --destination=$(params.HARBOR):$(cat $(params.CONTEXT)/tekton-git-tag)
```

I have multiple dockerfiles in this project: ocpp-server.Dockerfile, graphql-server.Dockerfile and more... so what I actually want to do is something like this:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace: project-tekton
  name: $(target)-build
spec:
  params:
    - name: DOCKERFILE
      type: string
      description: The path to the dockerfile to build
      default: $(resources.inputs.docker-source.path)/build/package/$(target).Dockerfile
    - name: CONTEXT
      type: string
      default: $(resources.inputs.docker-source.path)
    - name: HARBOR
      type: string
      default: harbor.mydomain.tld/project/$(target)
  resources:
    inputs:
      - name: docker-source
        type: git
  steps:
    - name: determine-git-tag
      image: harbor.mydomain.tld/project/alpine-helm:3.9.6
      script: |
        #!/bin/bash
        cd $(params.CONTEXT)
        VERSION=$(git describe --abbrev=0 --tags)
        echo "Creating tekton-git-tag file with: $VERSION"
        # remove v from version tag for docker
        echo "$VERSION" > $(params.CONTEXT)/tekton-git-tag
        echo "Switching to $VERSION"
        git checkout "$VERSION"
        if [ -z $VERSION ]; then
          echo "Git tag is empty"
          exit 1
        fi

    - name: build-and-push-image
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      image: gcr.io/kaniko-project/executor:debug #debug is used because we need a shell to be able to use cat.
      script: |
        #!/busybox/sh
        echo "Pushing to $(params.HARBOR):$(cat $(params.CONTEXT)/tekton-git-tag)"
        /kaniko/executor --dockerfile=$(params.DOCKERFILE) --context=$(params.CONTEXT) --destination=$(params.HARBOR):$(cat $(params.CONTEXT)/tekton-git-tag)
```

See the $(target) variable in name and params.. is there a way to do this in tekton? I could call my task `generic-build` and then just use the params in the step names.. but I would like to be able to see in the tekton dashboard which task is running there..

**Comment by dibyom** [comment]
Thinking out loud here:
1. Since all the tasks are similar, maybe you can have one generic task (like you said) but each TaskRun name can contain the $(target) so you can distinguish between what is actually being built. Not sure how this will look in the dashboard though.

2. Maybe kustomize to create multiple tasks with different names?

3. If you are using Triggers, you can use a [TriggerTemplate](https://github.com/tektoncd/triggers/blob/master/docs/triggertemplates.md) to customize you Task/TaskRun name using TriggerTemplate params:

```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  namespace: project-tekton
  name: generic-build-template
spec:
  params:
    name: target
  resourceTemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: Task
    metadata:
      namespace: project-tekton
      name: $(tt.params.target)-build
    spec:
      ....
```
