### ISSUE TITLE
Design idea for scannedImage/scan configuration in Task/Pipeline spec

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/pipeline#3356]
Wanted to share this idea while it's still fresh in my head and very interested in feedback (if this is a terrible idea I'd love to figure out what's being suggested as the current go-to) - thanks in advance for checking this out!

### Feature request

Writing security scanners that run on demand, or after a push pipelineruns, or on a cron job, as an additional pipeline or step, shouldn't be necessary IMO: I've been playing a lot with Go operators as part of my day job and I'm wondering if a `scannedImage` field instead of just an `image` or a `scan` struct, may be useful in Tekton, possibly through our Task/Pipeline CRs. 

Note that this particular proposal is concerned with container images.

The proposal consists of three separate but related ideas.

1. Instead of using `image` in Task definitions, use `scannedImage` and provide some configuration pertaining to how it should be scanned: say with a certain scan type (Dockerhub, IBM, Synk, anything else?) and credentials - probably through a Secret or ConfigMap that one would point to.

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: my-task
spec:
  params:
   ...
  steps: 
  - name: kubectl
    scannedImage: myImageToScan
```

2. The proposed `scan` struct you could use in a Pipeline resembles:

```
scan:
  provider: (set of known providers? allow "custom" with their own POST URL?)
  credentials: (unsure: additional provide field to a secret or ConfigMap ref?)
  results:
```

that users include in their Pipeline definition (at the top so it's "global") - and this would scan all images in the generated TaskRun for the PipelineRun - users can provide it just once, upfront, in the `spec` struct of the CR.

3. Finally, we could introduce an init-container as part of the Tekton controller, that scans the image first, automatically, and is pre-configured by a ConfigMap, before a Pipeline can start).

### Use case

Folks are using Pipelines to do things like, git clone, docker build, docker push, deploy, and the images they're using may be their own pointing to :latest that accrue vulnerabilities over time - and I imagine they'd like to know *as soon as* the Pipeline runs, which may be frequent, and they don't want to augment their existing work with scanning steps, or have an entirely new pipeline. 

When working on "production grade" pipelines, we had to pin the images and scan these manually, before shipping the actual pipelines we may want to use, and I'm wondering if, in Tekton, we can do something to make lives easier.

They'd like to change as little as possible and by putting some of the validating logic into Tekton, we can let users focus on writing their awesome Pipelines instead of finding Tasks that do scanning. 

I imagine we would implement this using ideas security scanning references from the Catalog first.

In addition, they'd like their finally produced image(s) to be scanned: so when a `scannedImage` is output (we'd need some way to differentiate between just referencing an image that should be scanned before use, versus the thing we built), and defining one  - so that once we produce it, it's scanned, before we deploy).

### Example CR  (show me the full yaml)

Example Task, before this proposal:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: my-task
spec:
  params:
...
  steps: 
  - name: my-step
    image: my-image-to-scan
```

and then in your Pipeline:

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  params:
...
  tasks:
    - name: clone
      taskRef:
        name: git-clone

    - name: build
      runAfter: [clone]
      taskRef:
        name: kaniko

    - name: scan
     runAfter: [build]
      taskRef:
        name: my-scanner
 

... push, deploy, etc ...

```

With my proposal, using `scannedImage`, here is that same Task:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: my-task
spec:
  params:
...
  steps: 
  - name: my-step
    scannedImage: my-image-to-scan
```

The Pipeline would be the same but without the need for `scan` step.

Alternative to `scannedImage`: this is using my `scan` proposal:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: my-task
spec:
  params:
...
  steps: 
  - name: my-step
    scan: <-- notice this new field
      provider: docker.io
      credentials: my-secret-with-my-docker-credentials
      results: *option field for result details*
    image: my-image-to-scan
...
```

Another alternative is that for the Pipeline itself, under `spec` you could also define a `scan` section there: this would apply to every image used in the TaskRun for the PipelineRun.

This Pipeline would look like

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
   scan:
     provider: docker.io
     credentials: my-secret-with-my-docker-credentials (or an additional field for a configmap instead? so this would be split between either secrets or configmap, but not both?)
     results: optional field for result details
  ...
```

**What I expect the Tekton Pipelines Controller would do**

Fail the Task/PipelineRun citing that TaskRun/PipelineRunRequirements failed and mentioning the image that was detected as problematic in the `status` field.

We could make this configurable because you could make it a warning instead but still mention it in the status. 

The `status` should include a link to the findings hosted somewhere, or we could do something awesome with `results`.

## Considerations

1. How to best provide a means to supply scanning credentials (a secret patched onto the ServiceAccount? A ConfigMap? A secret that isn't necessarily patched but just in the same namespace we refer to?)

2. Should the scan be done on every image used in the Pipeline upfront, or "as we go" through the Pipeline?

3. In addition, I wonder if we want to then remove any bad images that do get pulled in onto the Kubernetes nodes?

4. This is short of this *not* being a thing in standard Kubernetes, where as soon as an image is pulled, you're notified if it's bad (and that would certainly have no hook-in point to a Tekton PipelineRun...)

### What I haven't really fleshed out much...

- Differentiating between an image we use to pull in, versus pushing and then scanning (so something we make vs something we consume)
- Any sensible "defaults" (or would you use a ConfigMap again for config e.g. credentials) if you use just `scannedImage`
- The naming: I thought about `secureImage` first, but the thing you're going to scan may not be: so it's misleading. `scanImage` (present tense) could also work, but then I think it's the image you're going to use for the scanning.

Feedback welcome, thanks again

@afrittoli @skaegi FYI, my first proposal so if you've heard something similar or it's just rubbish, please let me know. Maybe it's already just really easy to include an additional scan task and this is too much heavy-lifting on the Tekton side?
