### ISSUE TITLE
Comment in code contradicts with doc

### ISSUE THREAD

**Issue by adux6991** [tektoncd/pipeline#3362]
# Expected Behavior

In [doc](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#running-scripts-within-steps), it says args will be passed to script in a step of a task.

But in [code](https://github.com/tektoncd/pipeline/blob/master/pkg/apis/pipeline/v1beta1/task_types.go#L126), it says "If Script is not empty, the Step cannot have an Command **or Args.**"

I experimented and the doc is right.

# Actual Behavior

# Steps to Reproduce the Problem

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-script-args
spec:
  steps:
    - args:
        - arg1
        - arg2
      image: 'python:3'
      name: step1
      script: |-
        #!/usr/bin/env python3
        import sys
        print(sys.argv)
```

1. create task
2. create taskrun
3. check output:
`['/tekton/scripts/script-0-frzff', 'arg1', 'arg2']`

# Additional Info
