### ISSUE TITLE
Allow scaling Tekton controllers horizontally

### ISSUE THREAD

**Issue by alan-ghelardi** [tektoncd/pipeline#3404]
### Feature request

According to the comments in this issue: https://github.com/knative/pkg/issues/1813 and to the changes introduced in this pull request: https://github.com/knative/pkg/pull/1301, Knative already supports scaling controllers horizontally. Is there some in progress initiative to add such capability to Tekton controllers?
     
### Use case

Scaling controllers, even in a fixed and somewhat manual manner, would be extremely useful to deal with scenarios of high concurrency.

**Comment by alan-ghelardi** [comment]
After looking carefully at Knative and Tekton's code base, it seems that Tekton already supports such feature. It's kinda obscure, but basically, I've followed these steps to have two controller instances running:
* Added the key `buckets`with the value `"2" to the config-leader-election.yaml file.
* Replaced the controller deployment with a statefulset.
* Increased the number of replicas to 2. 
* Added the field `serviceName` with the value `tekton-controller-pipelines` to the statefulset.
* Included the following environment variables in the controller's container:
```yaml
        - name: STATEFUL_SERVICE_NAME
          value: tekton-pipelines-controller
        - name: STATEFUL_CONTROLLER_ORDINAL
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
```
After applying the changes two active instances came up and started to reconcile pipelineruns and taskruns. I've triggered a few pipelineruns simultaneously and everything looks like okay; they ran normally without being duplicated.

Is that expected? Do you know if this feature can be considered stable to be used in production? As far as I understood, the boilerplate needed to implement the leader election mechanism was generated automatically by Knative codegen.
