### ISSUE TITLE
Taskrun status incorrectly assigned

### ISSUE THREAD

**Issue by jtama-op** [tektoncd/pipeline#3412]
# Expected Behavior

When a build-step is marked `waiting` with reason `CreateContainerConfigError`, it should be marked as failed, which would cause the whole pipeline to be marked as failed 

# Actual Behavior

The build-step is waiting, the taskrun status is unknown and pipelinerun is forever in running state

# Steps to Reproduce the Problem

1. Run a pipeline with securityContext that uses kaniko 

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: go-build
spec:
  description: |
    Takes a git repository and a branch name then go build
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from.
    - name: branch-name
      type: string
      description: The git branch to clone.
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)
    - name: image-build-and-push
      taskRef:
        name: kaniko
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-data

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: issue-reproduction-
spec:
  podTemplate:
    securityContext: # Otherwise git checkout file with a user mvn have no rigth on in directory /workspace
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 3000
      fsGroup: 2000
  pipelineRef:
    name: unknown-state-build
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

````

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.13.0
Pipeline version: v0.16.3
Triggers version: v0.8.1
```
