### ISSUE TITLE
Feature Request: Pooled PersistentVolumeClaims

### ISSUE THREAD

**Issue by bioball** [tektoncd/pipeline#3417]
### Feature request

There should be a way to select a `PersistentVolumeClaim` from a pool as the workspace binding when creating `PipelineRun`s and `TaskRun`s.

Ideally, there should be a way to dynamically grow the pool size; if there are no PVC's available in the pool, a new one gets created dynamically and added to the pool. This implies that there should be some way to expire these PVC's as well.

### Use case

There's a couple use-cases that I can think of:

1. Running multiple PipelineRuns in parallel for the same Pipeline, where each PipelineRun receives a volume that persists across runs (like a cache). Today, this is not possible unless mounted using ReadWriteMany or ReadOnlyMany (assuming the storage backend supports it), or if a separate entity outside of Tekton manages the pooling.
2. Eliminating the number of volumes being created and destroyed. Today, a common way to use volumes is to use a volumeClaimTemplate, which will create a PVC at the start of the run, and delete the PVC then the pod gets deleted. Using pooled PersistentVolumeClaims solves the following problems:
    * I might want to keep around my runs for historical purposes, but I don't want to keep the PVC around because it takes up space.
    * Creating/deleting a PVC incurs extra load on the Kubernetes API and the storage backend. I can reduce this load by simply re-attaching an existing PVC.

**Comment by sbwsg** [comment]
Worth noting that this feature request was also recently opened against Argo: https://github.com/argoproj/argo/issues/4130

I've tried searching for "kubernetes pvc pool" and "kubernetes storage pool" but haven't found anything.  I wonder if this would also be worth looking at as a platform feature and raising with the k8s team.

**Comment by bioball** [comment]
> I've tried searching for "kubernetes pvc pool" and "kubernetes storage pool" but haven't found anything. I wonder if this would also be worth looking at as a platform feature and raising with the k8s team.

That makes sense. Perhaps the ideal solution would look something like Kubernetes having a new Resource representing a pooled PVC, and there being a workspace binding to the PipelineRun. Something like the following:

```yaml
---
apiVersion: v1
kind: PooledPersistentVolumeClaim
metadata:
  name: my-pvc-pool
spec:
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
  spec:
    pipelineRef:
      name: my-pipeline-run
    workspaces:
      - name: my-workspace
         pooledPersistentVolumeClaim:
           claimName: my-pvc-pool
```

Without native k8s support for this, perhaps the other approach here could be either to introduce a new CRD managed by Tekton, or have a way to express a custom workspace binding (similar to the custom task design).

Curious about @skaegi's thoughts per our Slack conversation in https://tektoncd.slack.com/archives/CLCCEBUMU/p1603199756169700?thread_ts=1603139560.165600&cid=CLCCEBUMU
