### ISSUE TITLE
Provide a separate PipelineRun-volumeClaimTemplate, that can be mapped to multiple workspaces

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/pipeline#3440]
### Feature request

Improve usability when multiple workspaces share the same volume.

### Use case

It is a good practice for CI/CD pipelines to contain two git-repos, one for the _source code_ and one for the _configuration_ (ref [Continuous Delivery book](https://www.amazon.com/Continuous-Delivery-Deployment-Automation-Addison-Wesley/dp/0321601912/ref=sr_1_1?crid=3RAE8DS0DPY84&dchild=1))

This use case is also requested in https://github.com/tektoncd/catalog/issues/444#issuecomment-663712885 and I have designed a few pipelines following this pattern.

However, the usability for this today is not very good. 

### Current Situation

* A volume for the PipelineRun is typically created with the `volumeClaimTemplate` property for a workspace.
* A PipelineRun should not use more than one PersistentVolumeClaim (since it does not work well with how Availability Zones and multiple Nodes work)
* Different subPaths of a PVC workspace can be used e.g. for two different `git-clone` - but it is not intuitive.

### Proposal

Introduce a field for PipelineRun-volume
In the `PipelineRun.spec` add a new field, something like:

    volumeClaimTemplate:
      metadata:
         name: pipelinerun-vol
      spec:
        accessModes: 
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

And then let multiple workspaces use the same volume with a subPath in the WorkspaceBinding:

    workspaces:
    - name: source-code-ws
      persistentVolumeClaim:
        claimName: pipelinerun-vol
      subPath: source-code
     - name:  configuration-ws
      persistentVolumeClaim:
        claimName: pipelinerun-vol
      subPath: configuration

....and when binding those, that we first look if the PipelineRun has a `volumeClaimTemplate` mapped with a matching name.

### The improvement

The [PipelineRun example with different subPaths](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/pipelinerun-using-different-subpaths-of-workspace.yaml) works ... but is difficult to get to:
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-using-different-subpaths
spec:
  workspaces:
    - name: ws
  tasks:
    - name: writer-1
      taskRef:
        name: git-clone
      workspaces:
        - name: task-ws
          workspace: ws
          subPath: source-code-dir
    - name: writer-2
      runAfter:
        - writer-1
      taskRef:
        name: git-clone
      workspaces:
        - name: task-ws
          workspace: ws
          subPath: configuration-dir
    - name: read-all
      runAfter:
        - writer-2
      params:
        - name: directory1
          value: dir-1
        - name: directory2
          value: dir-2
      taskRef:
        name: read-both
      workspaces:
        - name: local-ws
          workspace: ws
```

If this proposal is implemented, the `subPaths` is only used in WorkspaceBinding-part, and the **two workspaces can have different names**

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-using-different-subpaths
spec:
  workspaces:
    - name: source-code-ws
    - name: configuration-ws
  tasks:
    - name: writer-1
      taskRef:
        name: git-clone
      workspaces:
        - name: task-ws
          workspace: source-code-ws
    - name: writer-2
      runAfter:
        - writer-1
      taskRef:
        name: git-clone
      workspaces:
        - name: task-ws
          workspace: configuration-ws
    - name: read-all
      runAfter:
        - writer-2
      params:
        - name: directory1
          value: dir-1
        - name: directory2
          value: dir-2
      taskRef:
        name: read-both
      workspaces:
        - name: ws-1
          workspace: source-code-ws
        - name: ws-2
          workspace: configuration-ws
```

The PipelineRun for the former:

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-different-path-
spec:
  pipelineRef:
    name: pipeline-using-different-subpaths
  workspaces:
    - name: ws
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```

and for the latter
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-different-path-
spec:
  pipelineRef:
    name: pipeline-using-different-subpaths
  workspaces:
    - name: source-code-ws
       persistentVolumeClaim:
         claimName: pipelinerun-vol
       subPath: source-code
     - name: configuration-ws
       persistentVolumeClaim:
         claimName: pipelinerun-vol
       subPath: configuration
  volumeClaimTemplate:
     metadata:
       name: pipelinerun-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
```

The improvement is even more clear when the workspace is **used in many tasks within the Pipeline**.

### Note

This "design" was discussed when the `volumeClaimTemplate` was introduced, but at least me did not prefer it - at the time - now I think it was a mistake.

Also see how [StatefulSet](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/) handle the name of the `volumeClaimTemplate` and the mapping to `volume` name.

**Comment by sbwsg** [comment]
Your final example with the PipelineRun spec `volumeClaimTemplate` looks very similar to this, which is supported today:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipelinerun-vol
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-different-path-
spec:
  pipelineRef:
    name: pipeline-using-different-subpaths
  workspaces:
    - name: source-code-ws
       persistentVolumeClaim:
         claimName: pipelinerun-vol
       subPath: source-code
     - name: configuration-ws
       persistentVolumeClaim:
         claimName: pipelinerun-vol
       subPath: configuration
```

I think the one major difference here would be that the `volumeClaimTemplate` has an owner reference to the pipelinerun and will be deleted with it. But there may be other advantages too?

I have a bit of concern about adding a kubernetes-specific field to the top-level of the PipelineRunSpec type. As much as possible we're trying to [keep k8s-specific stuff isolated to specific areas of the API](https://github.com/tektoncd/community/blob/master/design-principles.md#conformance) if they have to be added at all.

I'm starting to think that we need to look at the problem of inter-Node Workspaces more \~~holistically~~ (octopus arms added to try and disarm the heaviness of that word).  There is a ton of complexity here, a lot of different user/org preferences, and Tekton's surface area could bloat _a lot_ if we tried to tackle each problem in isolation.  This in turn could result in some nightmarish situations for platform implementers who then have to figure out support paths for every permutation of volume configuration that a user or tool might generate.
