### ISSUE TITLE
Intermittent timeout_test flake

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/pipeline#3449]
# Expected Behavior

PipelineRun failed with `PipelineRunTimeout`

# Actual Behavior

PipelineRun failed with `Failed`:
```
timeout_test.go:102: Error waiting for PipelineRun pipeline-run-timeout-mncrmugc to finish: "pipeline-run-timeout-mncrmugc" completed with the wrong reason: Failed
```

# Steps to Reproduce the Problem

This is an intermittent flake, though I see it several times a day in the continuous build.

# Additional Info

This snapshot from the resource dump highlights the discrepancy:

```
        spec:
          pipelineRef:
            name: pipeline-run-timeout-kjlunngp
          serviceAccountName: default
          timeout: 5s     <-- Expected to timeout (the task sleeps for 10s)
        status:
          completionTime: "2020-10-24T12:37:13Z"
          conditions:
          - lastTransitionTime: "2020-10-24T12:37:13Z"
            message: 'Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 0'
            reason: Failed    <-- We get Failed instead of PipelineRunTimeout
            status: "False"
            type: Succeeded
          pipelineSpec:
            tasks:
            - name: foo
              taskRef:
                kind: Task
                name: pipeline-run-timeout-lfsmutbs
          startTime: "2020-10-24T12:37:09Z"
          taskRuns:
            pipeline-run-timeout-mncrmugc-foo-74kf8:
              pipelineTaskName: foo
              status:
                completionTime: "2020-10-24T12:37:13Z"
                conditions:
                - lastTransitionTime: "2020-10-24T12:37:13Z"
                  message: TaskRun "pipeline-run-timeout-mncrmugc-foo-74kf8" failed to finish within "5s"
                  reason: TaskRunTimeout   <-- The task run timed out (as expected) though
                  status: "False"
                  type: Succeeded
```

I wanted to open this in the hope of getting more eyeballs on the code to spot the problem.  I'll try to poke around and see what I can see, but if anything pops out at folks, let's squash the flake 🤩 

cc @afrittoli @vdemeester @ImJasonH
