### ISSUE TITLE
Document current best practice for avoiding script injection with variable substitution

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#3458]
## Change Request

In [TEP 17](https://github.com/tektoncd/community/pull/208) @coryrc documented a way to prevent script injection when substituting variables in, for example, `script` fields of Steps.

The approach is to do something like this:

```yaml
   steps:
    - env:
        - name: SCRIPT_CONTENTS
          value: $(params.script)
      script: |
        printf '%s' "${SCRIPT_CONTENTS}" > input-script.sh
        chmod +x input-script.sh
        cd "$(params.package)"
        runner.sh /input-script
```

### What To Do

Make a PR to Tekton's official docs that shows this approach along with a description of how/why this mitigates the risk of script injection.
