### ISSUE TITLE
task has failed: more than one PersistentVolumeClaim is bound

### ISSUE THREAD

**Issue by koceg** [tektoncd/pipeline#3480]
# Expected Behavior
the task to execute from pipelineRun as it executes from taskRun

# Actual Behavior
task backup-prometheus-snapshot has failed: more than one PersistentVolumeClaim is bound
pod for taskrun prometheus-snapshot-run-8cdnx-backup-prometheus-snapshot-fpcgx not available yet
Tasks Completed: 2 (Failed: 1, Cancelled 0), Skipped: 0

# Steps to Reproduce the Problem
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  generateName: prometheus-snapshot-run-
spec:
  serviceAccountNames:
    - taskName: new-prometheus-snapshot
      serviceAccountName: prometheus-backup
  podTemplate:
    nodeSelector:
      kubernetes.io/hostname:
  params:
  - name: oc-image
    value: quay.io/openshift/origin-cli:4.5.0
  - name: oc-prometheus
    value: prometheus-k8s-1
  pipelineRef:
    name: prometheus-snapshot
  workspaces:
  - name: prometheus-pvc
    persistentVolumeClaim:
      claimName: "prometheus-k8s-db-$(params.oc-prometheus)"
  - name: backup-pvc
    persistentVolumeClaim:
      claimName: bkp
status: {}
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  creationTimestamp: null
  generateName: oc-snapshot-bkp-run-
spec:
  podTemplate:
    nodeSelector:
      kubernetes.io/hostname:
  params:
  - name: oc-image
    value: quay.io/openshift/origin-cli:4.5.0
  resources: {}
  serviceAccountName: ""
  taskRef:
    name: oc-snapshot-bkp
  workspaces:
  - name: prometheus
    persistentVolumeClaim:
      claimName: prometheus-k8s-db-prometheus-k8s-1
    subPath: prometheus-db/snapshots
  - name: backup
    persistentVolumeClaim:
      claimName: bkp
status:
  podName: ""
```

# Additional Info

- Kubernetes version: v1.18.3

- Tekton Pipeline version:

  Client version: 0.12.1
  Pipeline version: v0.17.2
  Triggers version: unknown

**Comment by jlpettersson** [comment]
```
  workspaces:
  - name: prometheus
    persistentVolumeClaim:
      claimName: prometheus-k8s-db-prometheus-k8s-1
    subPath: prometheus-db/snapshots
  - name: backup
    persistentVolumeClaim:
      claimName: bkp
```

Could these two workspaces use the same PersistentVolumeClaim? I see one of them is using a `subPath`, could the other use another `subPath` of the same PVC? It does not work well to use two PVCs in the same Task, if you only use a single datacenter, it should work if you disable the [affinit assistant](https://github.com/tektoncd/pipeline/blob/master/config/config-feature-flags.yaml#L32) but if you use a cloud provider this most likely will not help since the two PVCs may live within different Availability Zones in the cluster - this may also be the case in spanned clusters on-prem. In general, try to only use a single PVC for each task.
