### ISSUE TITLE
Support Tekton "Bundles" stored in Git repos

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#3490]
### Feature request

Via https://github.com/tektoncd/pipeline/issues/1839 we now support referencing versioned Tasks and Pipelines in OCI registries (https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#tekton-bundles).

As highlighted in [@ImJasonH 's early design doc](https://docs.google.com/document/d/1zUVrIbGZh2R9dawKQ9Hm1Cx3GevKIfOcRO3fFLdmBDc/edit#heading=h.tp9mko2koenr) this opens up the possibility to refer to Tekton resources (bundles?) in other locations as well, specifically in this issue I'd like to request/propose we add support for referencing Tasks and Pipelines in git, e.g. something like:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: my-task-run
spec:
  taskRef:
    git:
      url: https://github.com/my/repo
      commit: deadbeef
      path: path/to/my/task.yaml
```

### Use case

* I would like to set up a triggering system that uses my git repo as the source of truth for my Pipelines and Tasks, so that they can be versioned alongside my code, and so that I can make changes to these Pipelines and Tasks in my PRs that are picked up and used by CI

For example I could make a TriggerTemplate like:

```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: run-tests
spec:
  params:
  - name: commitish
    description: The commitish to grab the Pipeline from to run
    default: master
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: run-tests-$(uid)-
    spec:
      pipelineRef:
        git:
          url: https://github.com/my/repo
          # This would let me include any changes to the Pipeline in the PR testing
          commit: $(params.commitish)
          path: path/to/my/pipeline.yaml
```

### Additional info

* We'll have to figure out how to provide credentials for this as well
* We've been talking about whether or not our git-init cmd binary continues to live in this project ( + @sbwsg ), if we want git support in the Tekton Pipelines controller I wonder if it might stick around after all
