### ISSUE TITLE
Can multiple conditions be used for when expressions?

### ISSUE THREAD

**Issue by c1505** [tektoncd/pipeline#3513]
I want to run a task only when 2 different set of criteria are met.  As far as I can tell, when expressions only support a single condition.  Is there a way around that or a different option to use?

**Comment by jerop** [comment]
> I want to run a task only when 2 different set of criteria are met. As far as I can tell, when expressions only support a single condition. Is there a way around that or a different option to use?

@c1505 yes, you can specify multiple criteria using when expressions, such as:

```yaml
    tasks:
      - name: foo-bar
        when:
          - input: "$(params.foo)"
            operator: in
            values: ["true"]
          - input: "$(params.bar)"
            operator: notin
            values: ["false"]
        taskSpec:
         ...
```
