### ISSUE TITLE
[Question] Certificate data in a pipeline resource? 

### ISSUE THREAD

**Issue by itscatherinelam** [tektoncd/pipeline#3518]
Good morning! 

I would love to hear the expertise from the community - is there a way to pass in a certificate chain along with a pipeline resource? I see that there is a way to define a parameter for a cluster resource, but nothing in the documentation for a pipeline resource. I envision the cert chain would be stored in either a secret or a config map. Any leads?

Edit: To clarify, I'm also using the Tekton Operator within an Openshift cluster, which I believe is a few version behind the latest Tekton release (i.e. we can't use whenExpressions or 'finally' yet). In case that tidbit changes anything. 

Much appreciated, friends :)!

**Comment by sbwsg** [comment]
I'm not super familiar with a Certificate Chain - how does it manifest?  Is it files on disk?  If so then one approach would be to write your Tasks such that they accept an optional `workspace` which you could then mount wherever the certs needs to be located on disk.  Folks writing TaskRuns could then choose to provide that `workspace` with a `Secret`, which would show up in the Task as files.  Here's a slightly hand-wavey example:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: use-chain-of-certs
spec:
  workspaces:
  - name: certificate-chain
    optional: true
    mountPath: /etc/ssl/certs
  steps:
  - name: use-certs
    image: ubuntu:latest
    script: |
      ls -lah /etc/ssl/certs
```

NB: I'm actually not sure if Openshift has optional workspaces yet?  They were introduced in Tekton Pipelines in version 0.17.0.
