### ISSUE TITLE
Pinning CPU with a pipeline with 50 tasks and use of params/results chain

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#3521]
We are hitting a scalability problem that pins the controller in our clusters when we have a complex pipeline with close to 50 tasks that makes heavy use of params and results. I'll enclose a synthetic test case but this is a real world case that we are seeing in our clusters.

What we see is that the controller is CPU pinned before creating the first Task pod. In my cluster what I'm seeing is a very sudden degradation in start time for the synthetic test case when I run a pipeline that contains:
1) 40 Tasks -- 10 seconds to start
2) 50 Tasks -- 1 minute to start
3) 60 Tasks -- 41 minutes to start
... that feels like we have an algorithm that is out of whack.

The following synthetic tests are standalone and don't use a workspace or anything fancy and might be good in our tests later on...

[pipe40p.yaml.txt](https://github.com/tektoncd/pipeline/files/5539176/pipe40p.yaml.txt)
[pipe50p.yaml.txt](https://github.com/tektoncd/pipeline/files/5539177/pipe50p.yaml.txt)
[pipe60p.yaml.txt](https://github.com/tektoncd/pipeline/files/5539179/pipe60p.yaml.txt)

**Comment by dustym** [comment]
Watching this thread closely. We did an upgrade from v0.10 to v0.17 a couple of weeks ago (had to excise PipelineResources) and performance has been all over the place since then. I'm thinking about downgrading at this point. I've looked into the two HA solutions in [this isssue](https://github.com/tektoncd/pipeline/issues/3404) but the results have not been great -- sometimes we see double work or random task restarts when the task should be finishing with the StatefulSet approach and hardly any performance increase with the documented approach. Our pipelines go from `2 concurrent tasks -> 6 concurrent tasks -> 96 concurrent tasks` and at any given time there are 15 running on the cluster. Each pipeline gets its own namespace if that makes any difference.

If I can provide any data or notes in this area I am eager to help.

**Comment by afrittoli** [comment]
Uhm, pipeline `40` started quickly on my kind cluster, but I found an issue in the pipeline definition:
```
status:
  completionTime: "2020-11-14T10:05:06Z"
  conditions:
  - lastTransitionTime: "2020-11-14T10:05:06Z"
    message: 'unable to find result referenced by param "a" in "t2": Could not find
      result with name a for task run t1'
    reason: InvalidTaskResultReference
    status: "False"
    type: Succeeded
```
