### ISSUE TITLE
TaskRun that uses multiple PVC-backed workspaces will fail to schedule when using Affinity Assistant

### ISSUE THREAD

**Issue by bioball** [tektoncd/pipeline#3545]
# Expected Behavior

Pipelines that use multiple workspaces in a TaskRun should run when affinity assistants are enabled

# Actual Behavior

The underlying pods fail to schedule due to multi-attach errors

# Steps to Reproduce the Problem

Here's a sample pipeline that reproduces this issue:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: multi-workspace
spec:
  tasks:
  - name: my-task
    taskRef:
      name: my-task
    workspaces:
    - name: workspacea
      workspace: workspacea
    - name: workspaceb
      workspace: workspaceb
  workspaces:
  - name: workspacea
  - name: workspaceb
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: multi-workspace-run
spec:
  pipelineRef:
    name: multi-workspace
  workspaces:
  - name: workspacea
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100M
        accessModes:
        - ReadWriteOnce
  - name: workspaceb
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100M
        accessModes:
        - ReadWriteOnce
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: my-task
spec:
  steps:
  - image: busybox
    name: hello
    script: echo "Hello"
  workspaces:
  - name: workspacea
  - name: workspaceb
```

If applied to a multi-node cluster, I see this error within the pod's events:

```
Multi-Attach error for volume "us-west-3a-7d69ae3197354075a037" Volume is already used by pod(s) affinity-assistant-workspacea-multi-workspace-run-0
```

It seems like the root cause is that the affinity assistants were scheduled onto different nodes. These are the pods that I'm seeing:

```
NAME                                                  STATUS      NODE
affinity-assistant-workspacea-multi-workspace-run-0   Running     knode0750.********
affinity-assistant-workspaceb-multi-workspace-run-0   Running     knode0688.********
```

# Additional Info

Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T22:35:52Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"archive", BuildDate:"2020-10-02T05:55:28Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
```

Tekton Pipeline version:

```
v0.13.0-apple.1
```
