### ISSUE TITLE
Status.TaskSpec should reset after params substitution

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#3586]
### Feature request

The `Taskrun.Status.taskSpec` will be set as `Taskrun.Spec` when reconcile, seems for auditing.
I think it should be reset after the `Params` substitution, for auditing, with the real parameters will be more helpful.

current behavior 
```
status:
  taskSpec:
    params:
    - name: arg
      type: string
    steps:
    - image: alpine
      name: do-something
      resources: {}
      script: |
        echo "$(params.arg)" | grep "prefix:suffix"
```

Expect behavior:
```
status:
  taskSpec:
    params:
    - name: arg
      type: string
    steps:
    - image: alpine
      name: do-something
      resources: {}
      script: |
        echo "prefix:suffix" | grep "prefix:suffix"
```
### Use case
Beside auditing, there is another use case, maybe not common:
I try to get a unique hash code based on character of a `taskrun`,  that's could help cache the output of the `taskrun` and reuse(ignore) when a exactly same `taskrun` is invoked.
`Spec` is not enough, `Params` should be consider too. So if we set `Status.TaskSpec` after parameters substitution,  i can calculate hash code base on it.

Maybe it's not a common case, but at least it will help on auditing.
