### ISSUE TITLE
Support for params with `.`s

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/pipeline#3590]
# Expected Behavior

A way to use params with `.`s

# Actual Behavior

No way to reference params with `.`s

# Steps to Reproduce the Problem

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  params:
    - name: dev.mattmoor.foo
  steps:
    - name: echo
      image: ubuntu
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo $(params."dev.mattmoor.foo")
```

# Additional Info

I tested this against `github.com/mattmoor/mink`, so it may be a latent downstream bug, but I've got the validation wired up, so I was surprised this was accepted if it doesn't work.

**Comment by mattmoor** [comment]
_Another take on this is "validation hole!", but let me explain **why** I want domain-style parameter names..._

more to come.

**Comment by mattmoor** [comment]
Another examples of this, which seems especially relevant to syntax precedence, is containerd plugins:
```toml
  [plugins."io.containerd.grpc.v1.cri".containerd]
    disable_snapshot_annotations = true
```

If we were to follow this precedent, then it would suggest allowing: `$(params."this.is.one.name")` syntax.

However, this precedent does double-duty, since it uses reverse-DNS (like Java imports, and CloudEvent types).

I'll take a crack as allowing the `param."foo"` syntax to see how far I can get.

/assign
