### ISSUE TITLE
pipeline expansion of array params seems broken

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/pipeline#3600]
# Expected Behavior

This should expand the array value:
```yaml
value:
- "$(params.array-value[*])"
```

# Actual Behavior

It passes the unresolved parameter string 😞 

# Steps to Reproduce the Problem

I reduced the following repro.  You can `kubectl apply` this:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  params:
    - name: word
      type: array

  steps:
    - name: echo
      image: ubuntu
      command: ["echo"]
      args:
        - "$(params.word[*])"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: echo
spec:
  params:
    - name: word
      type: array

  tasks:
    - name: echo
      taskRef:
        name: echo
      params:
        - name: word
          value:
          - "$(params.word[*])"
```

Then you can `kubectl create` this:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: echo-
spec:
  params:
  - name: word
    value:
    - hello
    - dave
  pipelineRef:
    name: echo
```

This yields:
```
$(params.word[*])
```
