### ISSUE TITLE
Dynamically generate Task

### ISSUE THREAD

**Issue by vvvsrx** [tektoncd/pipeline#3602]
### Feature request

Is it possible to achieve the same dynamic task generation function as Jenkins pipeline

### Use case

This is my Jenkins pipeline code, I found that Tekton seems unable to do the same thing

``` groovy
def parallelBuildImageStagesMap
def parallelPushImageStagesMap

pipeline {
    stages {
        stage('Initialise') {
          steps {
            script {
                def param = ["org/name1:tag1","org/name2:tag2","org/name3:tag3","org/name4:tag4"]
                parallelBuildImageStagesMap = param.collectEntries {
                    ["build-image-${it}" : prepareOneBuildImageStage(it)]
                }
                parallelPushImageStagesMap = param.collectEntries {
                    ["push-image-${it}" : prepareSinglePushImageStage(it, "harbor.org")]
                }
            }
          }
        }
        stage('Build docker image') {
          steps {
              script {
                parallel parallelBuildImageStagesMap
              }
          }
        }
        stage('Push docker image') {
          steps {
              script {
                parallel parallelPushImageStagesMap
              }
          }
        }
    }
}

def prepareOneBuildImageStage(String name) {
    return {
        stage("Build image:${name}") {
            sh "docker build -t ${name} ."
        }
    }
}

def prepareSinglePushImageStage(String name, String horborHost) {
    return {
        stage("Push image:${name}") {
            sh "docker tag ${name}"
            sh "docker push ${horborHost}/${name}"
        }
    }
}
```

**Comment by nikhil-thomas** [comment]
@akram @waveywaves **ptal**

**Comment by vdemeester** [comment]
Hey @vvvsrx,

Looking at your use case, you don't really need any "dynamic" generation of task for having this in tekton. 
Correct me if I am wrong, but your goal is to build an image, tag it multiple times and push all the tagged images. This can be achieve relatively easily in a standard pipeline. For this, you would need a modified version of the [buildah](https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml) task (or kaniko) that would allow you to pass multiple image references so that it build the image, and tag it with the multiple given references. Then the pipeline would just need to pass the correct set of image reference as parameter.

**Comment by vvvsrx** [comment]
Thx @vdemeester 
I was really wrong. Thank you very much for your answer.

**Comment by vvvsrx** [comment]
I tried it and found that my idea still hasn't been realized.
My ideal is like this:
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: pipeline-
spec:
  pipelineRef:
    name: pipeline-standard
  workspaces:
  - name: git-source
  serviceAccountName: robot
  params:
    - name: modules
      value:
        - "default"
        - "product"
        - "account"
        - "search"

---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-standard
spec:
  workspaces:
    - name: git-source
  params:
    - name: modules
      type: array
  tasks:
    - name: docker-build-$(params.modules[*])
      taskRef:
        name: build-docker-image
      workspaces:
        - name: git-source
          workspace: git-source
      params:
        - name: name
          value: $(params.modules[*])
      Timeout: "0h10m0s"

---

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image
spec:
  workspaces:
    - name: git-source
  params:
    - name: name
      type: string
  steps:
    - name: build-docker-image
      image: a.newegg.org/docker-gcr-remote/kaniko-project/executor@sha256:e36c9fa99279217c4bb8ee172819b441c3ca8ef946dc0e28b21721eefb2ba70a
      workingDir: $(workspaces.git-source.path)
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(workspaces.git-source.path)/Dockerfile
        - --context=$(workspaces.git-source.path)
        - --tarPath=$(workspaces.git-source.path)/image-$(params.name).tar
        - --destination=image
        - --no-push
        - --use-new-run
```
**An array is obtained according to the parameters, and multiple "Tasks" with different names and different parameters can be automatically generated according to the array.**
Because there are "default", "product", "account", "search" in the parameters, 4 "Task" with different names will be generated: "docker-build-default","docker-build-product"," docker-build-account","docker-build-search". And they are executed in parallel.
