### ISSUE TITLE
Failed to pull kaniko image from private repo 

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#3604]
Service account

```
apiVersion: v1
imagePullSecrets:
- name: basic-user-pass
kind: ServiceAccount
metadata:
  name: 5f7ac2569596510001b034b7-sa
  namespace: tekton

```
Task
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: app-builder5fc89e3fdbf91600010d0012-task-run
  namespace: tekton
spec:
  serviceAccountName: 5f7ac2569596510001b034b7-sa
  taskRef:
    kind: Task
    name: app-builder5fc89e3fdbf91600010d0012
```

Task

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: app-builder5fc89e3fdbf91600010d0012
  namespace: tekton
spec:
  steps:
  - image: <url>
    imagePullPolicy: Always
    name: app

```

**Comment by zeromsi** [comment]
The error is like following,

```
failed to create task run pod "app-builder5fc89e3fdbf91600010d0012-task-run": translating TaskSpec to Pod: error getting image manifest: GET https://container-registry.console.klovercloud.io/v2/superapp-dxi1zsmt-c12u4ujw/repo/manifests/bf28cf28b5463f51e67c8ab951b41a19c6bf6029: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:superapp-dxi1zsmt-c12u4ujw/repo Type:repository]]. Maybe missing or invalid Task tekton/app-builder5fc89e3fdbf91600010d0012
```

**Comment by vdemeester** [comment]
/kind bug
Sounds like the controller didn't take into account the imagePullSecret from the attached service account.

**Comment by vdemeester** [comment]
My guess is that it *only* looks into the `podTemplate` imagePullSecret (https://github.com/tektoncd/pipeline/blob/ab723e9e79d358b6397cc62a199ba4c489ee3480/docs/podtemplates.md)

**Comment by drriguz** [comment]
Any response to this issue？ I got the same error today, while using custom image as task image.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: dev
  annotations:
    tekton.dev/docker-0: https://registry.example.com:8443
type: kubernetes.io/basic-auth
stringData:
    username: testuser
    password: testpassword
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl-deploy
  namespace: dev
spec:
  params:
    - name: deploy-config-path
      type: string
    - name: image-tag
      type: string
  resources:
    inputs:
      - name: git-src
        type: git
      - name: image-repo
        type: image
  steps:
    - name: kubectl-deploy
      image: registry.example.com:8443/kubectl:r1
      workingDir: /workspace/git-src
      script: |
        export IMAGE=$(resources.inputs.image-repo.url):$(params.image-tag)
        echo "Deploying ${IMAGE} by $(params.deploy-config-path)"
        envsubst < $(params.deploy-config-path) | kubectl apply -f -
```

```
Normal   Pulling    24s (x2 over 40s)  kubelet            Pulling image "registry.example.com:8443/kubectl:r1"
  Warning  Failed     24s (x2 over 40s)  kubelet            Failed to pull image "registry.example.com:8443/kubectl:r1": rpc error: code = Unknown desc = failed to pull and unpack image "registry.example.com:8443/kubectl:r1": failed to resolve reference "registry.example.com:8443/kubectl:r1": pulling from host registry.example.com:8443 failed with status code [manifests r1]: 401 Unauthorized
```

However, images could be successfully pushed into the registry. So I believe the configuration is correct, is this a bug?

**Comment by adelmoradian** [comment]
I had the same issue on tekton-pipeline v0.42.0.
The suggestion from @vdemeester did work... Just had to add the following to my `PipelineRun`

```
spec:
  podTemplate:
    imagePullSecrets: 
      - name: secret-1
      - name: secret-2
```

I did try a few other things which _didn't work_:

- Adding secrets to `PipelineRun`
- Adding secrets to tekton controller service account
- Adding secrets as imagePullSecrets to tekton controller deployment
