### ISSUE TITLE
imagePullSecrets error (doc or code)

### ISSUE THREAD

**Issue by Hokwang** [tektoncd/pipeline#3619]
Hi,

Sorry this may be a question.

I install tekton pipeline and dashboard today.

install using `kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml` command

and edit default config following your guide,
because of dockerhub pull rate limit, I need to set `imagePullSecrets`

Here's some problem.

```
k edit configmap -n tekton-pipelines config-defaults
apiVersion: v1
data:
  default-pod-template: |
    imagePullSecret:
      - name: dockerhub
```

and following basic tutorial,
```
vi task.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World"
k apply -f task.yaml

vi taskrun.yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: echo-hello-world-task-run
spec:
  taskRef:
    name: echo-hello-world
k apply -f taskrun.yaml
```

```
k get pod
NAME                                          READY   STATUS             RESTARTS   AGE
echo-hello-world-task-run-pod-wk5np           0/1     ImagePullBackOff   0          2m50s

k describe pod echo-hello-world-task-run-pod-wk5np
<snip>
Warning  Failed     83s (x4 over 2m50s)  kubelet, node-1  Failed to pull image "ubuntu": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Look at your doc, https://github.com/tektoncd/pipeline/blob/master/docs/podtemplates.md#supported-fields
there's `imagePullSecret` (no last s)

In native, as you know, `imagePullSecrets` used. (last s)

and look at your code 
https://github.com/NikeNano/pipeline/blob/462dde92e9a43da76101283087161439d0e87082/pkg/pod/pod.go#L294
there's `ImagePullSecrets` (first catipal and last s)

I waste couple of hours~.

- Kubernetes version:
  **Output of `kubectl version`:** 1.17.11
- Tekton Pipeline version: 0.19.0

**Comment by afrittoli** [comment]
Thanks for the report; and thank you for taking the time for tracking down the issue and reporting it ^_^

`imagePullsSecrets` is a list and should indeed have the trailing `s`, the documentation has to be fixed.
The lower case `i` is fine as it is though - while the go name is `ImagePullsSecrets`, the json mapping has a lower case `i` (which is the norm): 
https://github.com/tektoncd/pipeline/blob/f530a6907ff30027f15ef948b263d35967dbbe3e/pkg/apis/pipeline/pod/template.go#L102

**Comment by Hokwang** [comment]
@afrittoli Hi, Thanks for your fix. I saw your doc fix.
but I think there's still problem.
working solution is
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
data:
  default-pod-template: |
    ImagePullSecrets:
      - name: dockerhub
```
not small i, isn't it?
