### ISSUE TITLE
Embed variable in pipeline is broken

### ISSUE THREAD

**Issue by gsmlg** [tektoncd/pipeline#3648]
# Expected Behavior

embed variable in pipeline tasks' params like below:
```
params:
      - name: IMAGE
        value: "$(tasks.get-branch.results.image)"
```

tasks.get-branch.results.image actual value is

```
docker.io/user/web:tagname
```

Expect values is  `docker.io/user/web:tagname`

# Actual Behavior

In Pipelinerun, the actual value is 

```
|
  docker.io/user/web:tagname
```

Additional prefix "|
  " had been added in the values

# Steps to Reproduce the Problem

1. 
2.
3.

# Additional Info

- Kubernetes version: `v1.19.4+k3s1`

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4+k3s1", GitCommit:"2532c10faad43e2b6e728fdcc01662dc13d37764", GitTreeState:"clean", BuildDate:"2020-11-18T22:11:18Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version: `v0.19.0`

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by vincent-pli** [comment]
@gsmlg Could you post your pr definition?

**Comment by gsmlg** [comment]
This is the pr definition in tt
```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: web-push
  namespace: devops
spec:
  params:
  - name: project_name
    description: Project Name
    default: web
  - name: revision
    description: The git revision
    default: master
  - name: repository_url
    description: The git repository url
    default: git@gitlab.somewhere.dev:group/web.git
  - name: user_name
    description: The gitlab user display name
    default: ''
  - name: user_username
    default: ''
  - name: user_email
    description: The gitlab user email
    default: ''
  - name: ref
    description: The git commit ref
    default: ''
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: web-push-run-
        namespace: devops
      spec:
        serviceAccountName: pipeline-run-service
        pipelineRef:
          name: web-push
        timeout: "2h0m0s"
        workspaces:
          - name: repo
            volumeClaimTemplate:
              spec:
                storageClassName: nfs
                accessModes:
                  - ReadWriteMany
                resources:
                  requests:
                    storage: 1Gi
        params:
          - name: project_name
            value: $(tt.params.project_name)
          - name: repository_url
            value: $(tt.params.repository_url)
          - name: revision
            value: $(tt.params.revision)
          - name: ref
            value: $(tt.params.ref)
          - name: user_name
            value: $(tt.params.user_name)
          - name: user_username
            value: $(tt.params.user_username)
          - name: user_email
            value: $(tt.params.user_email)

```

**Comment by gsmlg** [comment]
And the pipeline definition:

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: web-push
  namespace: devops
spec:
  params:
    - name: project_name
      type: string
      description: project name
      default: group/web
    - name: repository_url
      type: string
      default: git@gitlab.somewhere.dev:group/web.git
    - name: revision
      type: string
      default: master
    - name: ref
      type: string
      default: refs/origin/master
    - name: user_name
      type: string
      description: gitlab user display name
      default: 'bot'
    - name: user_username
      type: string
      description: git username
      default: webbot
    - name: user_email
      type: string
      description: gitlab user email
      default: web@somewhere.dev.cn
  workspaces:
  - name: repo
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's README.md file to be read.
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: repo
      params:
      - name: url
        value: $(params.repository_url)
      - name: revision
        value: $(params.revision)
    - name: get-branch
      params:
        - name: ref
          value: $(params.ref)
      taskRef:
        name: get-branch-from-ref
    - name: build-image
      taskRef:
        name: kaniko
      runAfter:
        - "clone-repo"  # Wait until the clone is done before reading the readme.
        - "get-branch"
      params:
      - name: IMAGE
        value: "$(tasks.get-branch.results.image)"
      workspaces:
      - name: source
        workspace: repo
    - name: ding
      taskRef:
        name: ding-message
      runAfter:
        - "build-image"
      params:
        - name: message
          value: Successful build image docker.io/group/web:$(tasks.get-branch.results.branch)

```

**Comment by sbwsg** [comment]
How does the `get-branch-from-ref` Task generate the `image` result?  It looks to me like it might be accidentally introducing some extra characters to the result data written to `/tekton/results/image`.

**Comment by gsmlg** [comment]
@sbwsg 
This is the `get-bran ch-from-ref` task

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-branch-from-ref
  namespace: devops
spec:
  results:
    - name: branch
      description: output branch name
    - name: image
      description: output image address
  params:
    - name: ref
      type: string
  steps:
    - name: run
      image: alpine:3.12
      script: |-
        REF=$(params.ref)
        BRANCH=$(echo ${REF} | sed 's;refs/[a-zA-Z0-9]*/;;g' | sed 's;/;-;g')
        echo ${BRANCH} | tee -a $(results.branch.path)
        echo "docker.zdns.cn/zcloud/web:${BRANCH}" | tee -a $(results.image.path)
```
I'd tried to emmbed branch in a string value like this "docker.zdns.cn/zcloud/web:$(tasks.get-branch.results.branch)" and it output same result.
