### ISSUE TITLE
translating       TaskSpec to Pod: error getting image manifest

### ISSUE THREAD

**Issue by ycyxuehan** [tektoncd/pipeline#3655]
version: v0.17.2
taskrun:
```yaml
  podTemplate:
    dnsConfig:
      nameservers:
      - 223.5.5.5
      - 223.6.6.6
      - 114.114.114.114
    imagePullSecrets:
    - name: demo-registry
  resources:
    inputs:
    - name: demo
      resourceRef:
        name: demo
    outputs:
    - name: resourceImage
      resourceRef:
        name: demo-resource-image
  serviceAccountName: demo
....
```
service account:
```yaml
secrets:
- name: demo
- name: demo-git-token
- name: demo-git-privatekey
- name: demo-registry
- name: demo-token-gzcjp
```
secrets:

```yaml
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWd...
kind: Secret
metadata:
  annotations:
    tekton.dev/docker-0: https://demo.myregistry.com
type: kubernetes.io/dockerconfigjson
```
