### ISSUE TITLE
Unable to run Task under the gvisor runtime (GKE)

### ISSUE THREAD

**Issue by rvadim** [tektoncd/pipeline#3657]
# Expected Behavior
Ability to run tekton piplines with gvisor runtime (GKE)

# Actual Behavior
```
$ kubectl get taskrun
test-gvisor   False       CouldntGetTask   11s         11s
$ kubectl describe taskrun test-gvisor
...
Events:
  Type     Reason         Age   From     Message
  ----     ------         ----  ----     -------
  Normal   Started        84s   TaskRun  
  Warning  Failed         84s   TaskRun  failed to create task run pod "test-gvisor": pods "test-gvisor-pod-bqkn4" is forbidden: FSGroup is not supported. Maybe missing or invalid Task default/test-gvisor
```

# Steps to Reproduce the Problem
1. Setup and configure GKE cluster
2. Configure GKE Sandbox (https://cloud.google.com/kubernetes-engine/docs/how-to/sandbox-pods)
3. Create and run a task:
```
cat  > task.yaml <<EOF
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-gvisor
spec:
  description: ""
  steps:
    - name: test
      image: ubuntu:20.04
      script: |
        #!/bin/bash
        echo "Hello world"
EOF
cat > taskrun.yaml <<EOF
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test-gvisor
spec:
  taskRef:
    name: test-gvisor
  podTemplate:
    securityContext: {}
    runtimeClassName: gvisor
EOF
kubectl create -f task.yaml -f taskrun.yaml
```
# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-gke.2001", GitCommit:"00c919adfe4adf308bcd7c02838f2a1b60482f02", GitTreeState:"clean", BuildDate:"2020-11-06T18:24:02Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Tekton Pipeline version: v0.19.0

If I comment out `runtimeClassName: gvisor`(switch to regular runtimeclass). The taskRun completes successfully, and I can see the pod's securityContext:
```
kubectl get pod test-gvisor-pod-tlr8g -o yaml
...
  securityContext:
    fsGroup: 1    #<- Looks bad
    runAsUser: 1
    supplementalGroups:
    - 1
...
```
