### ISSUE TITLE
Fix controller create taskRun all the time after create task failed.

### ISSUE THREAD

**Issue by llhhbc** [tektoncd/pipeline#3678]
ref https://github.com/tektoncd/pipeline/pull/3287

# Expected Behavior
pipeline run expected

# Actual Behavior
pipeline controller creat thousands taskrun.

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

v0.10.1

example pipeline to cause this bugs:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  generation: 1
  name: build-kubeconfig
  namespace: tekton-run
spec:
  params:
  - name: revision
    type: string
  resources:
  - name: kubeconfig-git
    type: git
  tasks:
  - name: build1
    params:
    - name: revision
      type: string
      value: $(params.revision)
    resources:
      inputs:
      - name: workspace
        resource: kubeconfig-git
    taskRef:
      name: build-push-kaniko
  - name: build2
    params:
    - name: revision
      type: string
      value: $(params.revision)
    resources:
      inputs:
      - name: workspace
        resource: kubeconfig-git
    taskRef:
      name: build-push-kaniko
  - name: buil3CAUSEBUGS
    params:
    - name: revision
      type: string
      value: $(params.revision
    resources:
      inputs:
      - name: workspace
        resource: kubeconfig-git
    taskRef:
      name: build-push-kaniko
```

The reason cause this bugs:
Because dns in k8s can't has uppercase word, create taskrun of `buil3CAUSEBUGS`  failed.
