### ISSUE TITLE
pipelineRun status struck in running state  forever even after setting pipelineRun timeout option

### ISSUE THREAD

**Issue by praveen4g0** [tektoncd/pipeline#3703]
# Expected Behavior
When an user creates a Pipeline which  accepts an optional workspace and gives it to a PipelineTask
the PipelineRun reconciler stalls if the workspace isn't provided and Assume I have set timeout at pipelineRun level, I expects pipelineRun to fail, with below reason.

Related to [pr](https://github.com/tektoncd/pipeline/pull/3702)

**Reason: Failed(PipelineRunTimeout)**

# Actual Behavior
```
tkn pr ls
NAME                        STARTED          DURATION     STATUS
optional-workspaces-p59c5   12 minutes ago   ---          Running
```
```
tkn pr describe -o yaml

status:
  conditions:
  - lastTransitionTime: "2021-01-21T07:49:24Z"
    message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Incomplete: 2, Skipped: 0'
    reason: Running
    status: Unknown
    type: Succeeded

```
**Note:** Status unknown is not evident. 

# Steps to Reproduce the Problem
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-source-code-configmap
data:
  main.js: |
    console.log("Hello, World!");
  init.js: |
    console.log("Running pre-lunch setup!");
  teardown.js: |
    console.log("Running teardown script!");
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-js
spec:
  workspaces:
  - name: prelaunch
    optional: true
  - name: launch
  - name: postlaunch
    optional: true
  steps:
  - image: node:lts-alpine3.11
    script: |
      #!/usr/bin/env sh
      if [ $(workspaces.prelaunch.bound) == "true" ] ; then
        node "$(workspaces.prelaunch.path)/init.js"
      else
        echo "Skipping prelaunch."
      fi
      if [ -f "$(workspaces.launch.path)/main.js" ] ; then
        node "$(workspaces.launch.path)/main.js"
      else
        echo "Error: missing main.js file in launch workspace!"
        exit 1
      fi
      if [ $(workspaces.postlaunch.bound) == "true" ] ; then
        node "$(workspaces.postlaunch.path)/teardown.js"
      else
        echo "Skipping postlaunch."
      fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  params:
  - name: values
    type: array
  steps:
  - image: alpine
    command: ["echo"]
    args: ["$(params.values[*])"]
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: optional-workspaces-
spec:
  timeout: 30s
  workspaces:
  - name: launch
    configMap:
      name: example-source-code-configmap
  - name: prelaunch
    configMap:
      name: example-source-code-configmap
  pipelineSpec:
    workspaces:
    - name: launch
      description: |
        The program to run. Must provide a main.js at its root.
    - name: prelaunch
      optional: true
      description: |
        Prelaunch program to run before the launch program. Use this
        to set up any environment-specific requirements. Must provide
        an init.js file at its root.
    - name: postlaunch
      optional: true
      description: |
        Prelaunch program to run before the launch program. Use this
        to set up any environment-specific requirements. Must provide
        an teardown.js file at its root.    
    tasks:
    - name: print-bound-state
      timeout: 10s
      taskRef:
        name: echo
      params:
      - name: values
        value:
        - "Was a prelaunch workspace provided? "
        - $(workspaces.prelaunch.bound)
        - "\n"
        - "Was a launch workspace provided? "
        - "$(workspaces.launch.bound)"
        - "\n"
        - "Was a postlunch workspace provided?"
        - "$(workspaces.postlaunch.bound)"
        - "\n"
    finally:            
    - name: run-js
      timeout: 20s
      workspaces:
      - name: launch
        workspace: launch
      - name: prelaunch
        workspace: prelaunch
      - name: postlaunch
        workspace: postlaunch
      taskRef:
        name: run-js
```
```
kubectl apply -f <above>.yaml
```

# Additional Info

- Kubernetes version: v1.20.0+d9c52cc

  **Output of `kubectl version`:**

```                                                                                        
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"68540fc03a457c57fdbc2c58a8316909686e37a9", GitTreeState:"clean", BuildDate:"2021-01-09T10:38:35Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+d9c52cc", GitCommit:"d9c52cc4e02894215b0d1c2aeea240fe77765c66", GitTreeState:"clean", BuildDate:"2021-01-16T04:43:08Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
tkn version               
Client version: 0.15.0
Pipeline version: v0.19.0
Triggers version: v0.10.2
```
