### ISSUE TITLE
general question: without using persistent volume can i share workspace  among tasks ?

### ISSUE THREAD

**Issue by ishallbethat** [tektoncd/pipeline#3704]
I have trigger template like this
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: helmchart-template
  namespace: tekton
spec:
  params:
  - name: github-repo-revision
    description: The git revision
    default: master
  - name: private-github-repo-url
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: helmchart-pipeline-
    spec:
      serviceAccountName: production-deployment-serviceaccount
      pipelineRef:
        name: helmchart-pipeline
      params:
      - name: github-repo-revision
        value: $(tt.params.github-repo-revision)
      - name: private-github-repo-url
        value: $(tt.params.private-github-repo-url)
      workspaces:
      - name: source
        emptyDir: {}
```
task.yaml
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helmchart-builder
  namespace: tekton
spec:
  steps:
    - name: zip-helmchart
      image: us.gcr.io/sss-admin/jenkins/tekton-scripts:latest
      script: |
        tail -f /dev/null
        ls $(workspaces.output.path)
        cd $(workspaces.output.path)
        zip -r $(workspaces.output.path)/helm-charts.zip xxx
    - name: upload-to-asia-artifacts
      image: us.gcr.io/sss-admin/jenkins/tekton-scripts:latest
      volumeMounts:
        - name: serviceaccount
          mountPath: /var/serviceaccount
      script: |
        gcloud auth activate-service-account --key-file=/var/serviceaccount/jenkins-ci-xxx-org.json
        DATE=`date '+%Y-%m-%d-%H-%M-%S'`
        cp $(workspaces.output.path)/helm-charts.zip $(workspaces.output.path)/helm-charts-latest.zip
        gcloud auth list
        gsutil cp $(workspaces.output.path)/helm-charts-latest.zip gs://asia-artifacts/helm-charts/
        gsutil cp $(workspaces.output.path)/helm-charts-latest.zip gs://asia-artifacts/helm-charts/$DATE/
  volumes:
    - name: serviceaccount
      secret:
        secretName: tekton-admin-deployment-secret
  workspaces:
  - name: output
```
pipeline.yaml
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helmchart-pipeline
  namespace: tekton
spec:
  params:
    - name: private-github-repo-url
      description: The private GitHub Repo
    - name: github-repo-revision
      description: The GitHub revision to use
      default: master
  workspaces:
    - name: source
  tasks:
    - name: clone-sources
      taskRef:
        name: git-clone
      params:
      - name: url
        value: $(params.private-github-repo-url)
      - name: revision
        value: $(params.github-repo-revision)
      - name: deleteExisting
        value: 'true'
      workspaces:
        - name: output
          workspace: source
    - name: helmchart-builder
      retries: 3
      taskRef:
        name: helmchart-builder
      runAfter: [clone-sources]
      workspaces:
        - name: output
          workspace: source
```

Turns out no matter what i do i can not see the cloned repo in task  "helmchart-builder". 

Does it really without using persistent volume,  i can't share data among tasks ? How can i use resource output/input to make this persistent among tasks ?
