### ISSUE TITLE
retries some steps

### ISSUE THREAD

**Issue by renhao-0518** [tektoncd/pipeline#3707]
```yaml
tasks:
  - name: build-the-image
    retries: 1
    taskRef:
      name: build-push
```
When the build fails, it is now to retry the entire task，Can you support retrying certain steps in the task
