### ISSUE TITLE
Add nonroot user to base image

### ISSUE THREAD

**Issue by TakiTake** [tektoncd/pipeline#3712]
### Feature request

Could you add nonroot user to base image?
Like this
```
FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.18.1
RUN addgroup -S -g 65532 nonroot && adduser -S -u 65532 nonroot -G nonroot
ENV HOME=/home/nonroot
```

I'd like to run Task as nonroot user as much as possible. But there is no prefer user in the base image. For example, not in gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init

### Use case

Run git-clone task as nonroot user.
https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.2

I tested with following TaskRun.
And I have disabled home env overwrite to use different home from /home/tekton.

```
$ kubectl get cm feature-flags -n tekton-pipelines -o yaml
apiVersion: v1
data:
  disable-affinity-assistant: "false"
  disable-creds-init: "false"
  disable-home-env-overwrite: "true"
  disable-working-directory-overwrite: "false"
  enable-custom-tasks: "false"
  enable-tekton-oci-bundles: "false"
  require-git-ssh-secret-known-hosts: "false"
  running-in-environment-with-injected-sidecars: "true"
kind: ConfigMap
...
```

#### Without nonroot user

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-
spec:
  params:
  - name: revision
    value: main
  - name: url
    value: git@github.com:TakiTake/private.git
  serviceAccountName: default
  taskRef:
    kind: Task
    name: git-clone
  timeout: 1h0m0s
  workspaces:
  - emptyDir: {}
    name: output
  podTemplate:
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
```

```
$ tkn tr logs
? Select taskrun: git-clone-tpqf7 started 23 seconds ago
task git-clone has failed: "step-clone" exited with code 1 (image: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init@sha256:406e9a4f9d10dbc59e141c1584d1d4dcff995012071eb425a3c117ec0dfe16af"); for logs run: kubectl -n default logs git-clone-tpqf7-pod-mpf4c -c step-clone

[clone] 2021/01/25 00:42:00 warning: unsuccessful cred copy: ".ssh" from "/tekton/creds" to "/": unable to create destination directory: mkdir /.ssh: permission denied
[clone] + CHECKOUT_DIR=/workspace/output/
[clone] + '[[' true '==' true ]]
[clone] + cleandir
[clone] + '[[' -d /workspace/output/ ]]
[clone] + rm -rf '/workspace/output//*'
[clone] + rm -rf '/workspace/output//.[!.]*'
[clone] + rm -rf '/workspace/output//..?*'
[clone] + test -z
[clone] + test -z
[clone] + test -z
[clone] + /ko-app/git-init -url git@github.com:TakiTake/private.git -revision main -refspec  -path /workspace/output/ '-sslVerify=true' '-submodules=true' -depth 1
[clone] {"level":"error","ts":1611535322.160029,"caller":"git/git.go:54","msg":"Error running git [config --global core.sshCommand ssh -o StrictHostKeyChecking=accept-new]: exit status 255\nerror: could not lock config file //.gitconfig: Permission denied\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:54\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:101\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:52\nruntime.main\n\truntime/proc.go:204"}
[clone] {"level":"warn","ts":1611535322.1600974,"caller":"git/git.go:103","msg":"error disabling strict host key checking: exit status 255"}
[clone] {"level":"fatal","ts":1611535322.1601202,"caller":"git-init/main.go:53","msg":"Error fetching git repository: error disabling strict host key checking: exit status 255","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:204"}

container step-clone has failed  : [{"key":"StartedAt","value":"2021-01-25T00:42:02.118Z","type":"InternalTektonResult"}]
```

#### With nonroot user

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-
spec:
  params:
  - name: revision
    value: main
  - name: url
    value: git@github.com:TakiTake/private.git
  - name: gitInitImage
    value: takitake/git-init:with-nonroot
  serviceAccountName: default
  taskRef:
    kind: Task
    name: git-clone
  timeout: 1h0m0s
  workspaces:
  - emptyDir: {}
    name: output
  podTemplate:
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
```

```
$ tkn tr logs
[clone] + CHECKOUT_DIR=/workspace/output/
[clone] + '[[' true '==' true ]]
[clone] + cleandir
[clone] + '[[' -d /workspace/output/ ]]
[clone] + rm -rf '/workspace/output//*'
[clone] + rm -rf '/workspace/output//.[!.]*'
[clone] + rm -rf '/workspace/output//..?*'
[clone] + test -z
[clone] + test -z
[clone] + test -z
[clone] + /ko-app/git-init -url git@github.com:TakiTake/private.git -revision main -refspec  -path /workspace/output/ '-sslVerify=true' '-submodules=true' -depth 1
[clone] {"level":"info","ts":1611535037.9444587,"caller":"git/git.go:165","msg":"Successfully cloned git@github.com:TakiTake/private.git @ baffdfc2ffe1d9c4372f9b8718a1ac234cb4d428 (grafted, HEAD, origin/main) in path /workspace/output/"}
[clone] {"level":"info","ts":1611535037.9667072,"caller":"git/git.go:203","msg":"Successfully initialized and updated submodules in path /workspace/output/"}
[clone] + cd /workspace/output/
[clone] + git rev-parse HEAD
[clone] + RESULT_SHA=baffdfc2ffe1d9c4372f9b8718a1ac234cb4d428
[clone] + EXIT_CODE=0
[clone] + '[' 0 '!=' 0 ]
[clone] + echo -n baffdfc2ffe1d9c4372f9b8718a1ac234cb4d428
[clone] + echo -n git@github.com:TakiTake/private.git
```
