### ISSUE TITLE
mistake : mountPath of workspace

### ISSUE THREAD

**Issue by supershll** [tektoncd/pipeline#3716]
# Expected Behavior

when I use `workspace` as follows:

```
  workspaces:
  - name: messages 
    description: The folder where we write the message to
    mountPath: custompath/relative/to/workspace
```

According to following guide from the [documentation](https://tekton.dev/docs/pipelines/workspaces/) :

```
mountPath - A path to a location on disk where the workspace will be available to Steps. Relative paths will be prepended with /workspace. If a mountPath is not provided the workspace will be placed by default at /workspace/<name> where <name> is the workspace’s unique name.
```

the Expected  Result should be :

-  `$(workspaces.messages.path)`  is  `/workspace/custompath/relative/to/workspace` 
-  the folder should already exist  

but the actual result is 

-  `$(workspaces.messages.path)`  is  `custompath/relative/to/workspace` 
-  the folder  exists as  `/custompath/relative/to/workspace` but not `/workspace/custompath/relative/to/workspace` 

# Steps to Reproduce the Problem

1. create `Task` use follow yaml

```
apiVersion : tekton.dev/v1beta1
kind: Task
metadata:
  name : use-workspace
spec:
  description: "use-workspace"
  workspaces:
  - name: messages 
    description: The folder where we write the message to
    mountPath: custompath/relative/to/workspace
  steps:
  - name: step-use-workspace
    image: ubuntu
    script: |
      #!/usr/bin/env bash
      echo hello! > $(workspaces.messages.path)/message
      echo hello2! > /$(workspaces.messages.path)/message2
      echo "ls $(workspaces.messages.path)"
      ls $(workspaces.messages.path)
      echo "ls /$(workspaces.messages.path)"
      ls /$(workspaces.messages.path) 

```

2. use `tkn` to start `use-workspace Task`

3. use `tkn taskrun logs` to view log 

# Question: Is this a Bug or Mistake of Docs ? 

Looking forward to your answer ! Thanks!
