### ISSUE TITLE
Optional Parameters?

### ISSUE THREAD

**Issue by namloc2001** [tektoncd/pipeline#3726]
Hi, I'm not sure if I've missed it in the documentation, but is it possible to supply optional parameters that don't have to have a value provided in pipelineRun and will default to blank/nothing if not provided?

**Comment by sbwsg** [comment]
Specify a default value of `""` for the param in the [Pipeline](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#specifying-parameters):

```yaml
kind: Pipeline
spec:
  params:
    - name: foo
      default: ""
```

/kind question
