### ISSUE TITLE
The $(context.task.name) is substituted to taskrun name

### ISSUE THREAD

**Issue by jinchihe** [tektoncd/pipeline#3730]
# Expected Behavior
The $(context.task.name) is substituted to task name
# Actual Behavior
The $(context.task.name) is substituted to taskrun name

# Steps to Reproduce the Problem

1. Apply the sample:  https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/using_context_variables.yaml

```
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: test-pipelinerun-
spec:
  serviceAccountName: 'default'
  pipelineSpec:
    tasks:
    - name: task1
  
     ......

        - image: ubuntu
          name: print-names
          script: |
            echo "Task name: $(context.task.name)"
            echo "TaskRun name: $(context.taskRun.name)"
```
2. Check the logs
```
# kubectl logs test-pipelinerun-59tcl-task1-mdn5f-pod-xqnlh -c step-print-names
Task name: test-pipelinerun-59tcl-task1-mdn5f
TaskRun name: test-pipelinerun-59tcl-task1-mdn5f
Pipeline name from params: test-pipelinerun-59tcl
PipelineRun name from params: test-pipelinerun-59tcl
```
3. I think the task name should be "task1", right? Thanks.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
# tkn version
Client version: 0.13.1
Pipeline version: v0.19.0
Dashboard version: v0.7.1
```

**Comment by jinchihe** [comment]
Seems the $(context.pipeline.name) also is same with $(context.pipelineRun.name) ?

**Comment by sbwsg** [comment]
Hi @jinchihe it looks like you're using nested `pipelineSpec` and `taskSpec` in your PipelineRun.  What you're seeing is expected behaviour.

When you embed a `pipelineSpec` inside a `PipelineRun` the pipeline takes on the same name as the PipelineRun.  This happens because we explicitly use the PipelineRun metadata as the Pipeline metadata here: https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/pipelinerun/resources/pipelinespec.go#L45-L47

Similarly when you embed a `taskSpec` directly inside a `PipelineTask` or `TaskRun` the Task takes on the same name as the TaskRun.  This happens here: https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/taskrun/resources/taskspec.go#L51-L53

**Comment by sbwsg** [comment]
Here's an example that uses separate Task, Pipeline, PipelineRun and the context variables we get:

```yaml
kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: test-task
spec:
  params:
  - name: pipelineName
  - name: pipelineRunName
  steps:
  - image: alpine:3.13.0
    script: |
      #!/usr/bin/env ash
      echo "Task:        $(context.task.name)"
      echo "TaskRun:     $(context.taskRun.name)"
      echo "Pipeline:    $(params.pipelineName)"
      echo "PipelineRun: $(params.pipelineRunName)"
---
kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
 name: test-pipeline
spec:
  params:
  - name: pipelineName
  - name: pipelineRunName
  tasks:
  - name: foo
    params:
    - name: pipelineName
      value: $(params.pipelineName)
    - name: pipelineRunName
      value: $(params.pipelineRunName)
    taskRef:
      name: test-task
---
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: test
spec:
  params:
  - name: pipelineName
    value: $(context.pipeline.name)
  - name: pipelineRunName
    value: $(context.pipelineRun.name)
  pipelineRef:
    name: test-pipeline
```

Logs:

```
[foo : unnamed-0] Task:        test-task
[foo : unnamed-0] TaskRun:     test-foo-l6t2h
[foo : unnamed-0] Pipeline:    test-pipeline
[foo : unnamed-0] PipelineRun: test
```
