### ISSUE TITLE
Failed to add the host to the list of known hosts (/root/.ssh/known_hosts)

### ISSUE THREAD

**Issue by dmitry-mightydevops** [tektoncd/pipeline#3745]
# Expected Behavior

I'm trying to authenticate github repo using SSH deploy key.

# Actual Behavior

Pipeline run fails with the following messages

```bash
✦ ➜ k apply -f tekton/beta/build-pipeline.yaml && tkn pipelinerun logs build-pipeline-run-10 -f

pipelineresource.tekton.dev/test-backend-repo unchanged
pipelineresource.tekton.dev/test-backend-image unchanged
task.tekton.dev/ecr-login configured
task.tekton.dev/buildpack configured
pipeline.tekton.dev/build-pipeline configured
pipelinerun.tekton.dev/build-pipeline-run-11 created
[ecr-login : login] + aws ecr get-login-password --region us-west-2

✦ ✗  k get pods | grep run-10                
NAME                                                 READY   STATUS      RESTARTS   AGE
build-pipeline-run-10-buildpack-vns7m-pod-lrnvk      0/2     Error       0          3m52s

✦ ➜ k logs build-pipeline-run-10-buildpack-vns7m-pod-lrnvk --all-containers                
{"level":"error","ts":1612313781.7649286,"caller":"git/git.go:47","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force main]: exit status 128\nCould not create directory '/root/.ssh'.\r\nFailed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\ngit@github.com: Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:47\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:137\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:52\nruntime.main\n\truntime/proc.go:203"}
{"level":"fatal","ts":1612313781.7650263,"caller":"git-init/main.go:53","msg":"Error fetching git repository: failed to fetch [main]: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:203"}
2021/02/03 00:56:21 Skipping step because a previous step failed
```

# Steps to Reproduce the Problem

Every task is defined in the **tekton-pipelines** namespace

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
secrets:
  - name: test-backend-deploy-key

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
data:
  default-service-account: "build-bot"
  default-timeout-minutes: "20"
  default-pod-template: |
    nodeSelector:
      tekton_builder: "true"

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: test-backend-repo
spec:
  type: git
  params:
    - name: url
      value: git@github.com:team-nest/test-backend.git
    - name: revision
      value: main

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: test-backend-image
spec:
  type: image
  params:
    - name: url
      value: XXX.dkr.ecr.us-west-2.amazonaws.com/backend

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ecr-login
spec:
  params:
    - name: region
      type: string
      default: "us-west-2"
  steps:
    - name: login
      image: docker.io/amazon/aws-cli:2.0.52@sha256:1506cec98a7101c935176d440a14302ea528b8f92fcaf4a6f1ea2d7ecef7edc4 #tag: 2.0.52
      script: |
        aws ecr get-login-password --region $(params.region) > $(results.password.path)
  results:
    - name: password
      description: The password to authenticate to ecr registry.

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildpack
spec:
  resources:
    inputs:
      - name: git-source
        type: git
  steps:
    - name: build
      image: ubuntu
      script: |
        echo "hello world"

---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: ecr-image
      type: image
  tasks:
    - name: ecr-login
      taskRef:
        name: ecr-login
      params:
        - name: region
          value: "us-west-2"
    - name: buildpack
      taskRef:
        name: buildpack
      resources:
          inputs:
            - name: git-source
              resource: git-source

      
---

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-pipeline-run-11
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: build-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: test-backend-repo
    - name: ecr-image
      resourceRef:
        name: test-backend-image
```

# Additional Info

Secret was created this way

```
✦ ➜ kubectl -n tekton-pipelines \
    create secret generic test-backend-deploy-key\
    --from-file=ssh-privatekey=test-backend-deploy-key.pem \
    --from-file=ssh-publickey=test-backend-deploy-key.pub \
    --dry-run=client \
    -o yaml | kubectl apply -f -

✦ ✗  k get secret | grep test-backend-deploy-key                                                 
test-backend-deploy-key                          Opaque                                2      87m

```

- Kubernetes version:

```
✦ ➜ kubectl version                           
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

```
✦ ➜ tkn version         
Client version: 0.15.0
Pipeline version: v0.15.2
Triggers version: v0.11.2

```
