### ISSUE TITLE
Cloudevents are sometimes not emitted for task state change

### ISSUE THREAD

**Issue by skk2142** [tektoncd/pipeline#3750]
# Expected Behavior
Taskrun successful should emit an event. 
# Actual Behavior
No event is emitted for success, but I do get events for started and unknown state. 
I have shown the headers of events emitted for the taskrun.
# Additional Info
```json
"headers": {
        "host": "event-logger.devops.svc",
        "user-agent": "Go-http-client/1.1",
        "transfer-encoding": "chunked",
        "accept-encoding": "gzip",
        "ce-id": "6da3bef6-1d26-486b-9c6a-3b5df9b2a3b5",
        "ce-source": "/apis/tekton.dev/v1beta1/namespaces/devops/taskruns/deploy-run-7x5ft-get-info-wjsnz",
        "ce-specversion": "1.0",
        "ce-subject": "deploy-run-7x5ft-get-info-wjsnz",
        "ce-time": "2021-02-03T21:13:38.876059184Z",
        "ce-type": "dev.tekton.event.taskrun.started.v1",
        "connection": "close",
        "content-type": "application/json",
        "eventlistener-request-url": "/"
    }
"headers": {
        "host": "event-logger.devops.svc",
        "user-agent": "Go-http-client/1.1",
        "transfer-encoding": "chunked",
        "accept-encoding": "gzip",
        "ce-id": "b114da84-58db-4716-8f89-22e27f9e740e",
        "ce-source": "/apis/tekton.dev/v1beta1/namespaces/devops/taskruns/deploy-run-7x5ft-get-info-wjsnz",
        "ce-specversion": "1.0",
        "ce-subject": "deploy-run-7x5ft-get-info-wjsnz",
        "ce-time": "2021-02-03T21:13:39.791862396Z",
        "ce-type": "dev.tekton.event.taskrun.unknown.v1",
        "connection": "close",
        "content-type": "application/json",
        "eventlistener-request-url": "/"
    },
"headers": {
        "host": "event-logger.devops.svc",
        "user-agent": "Go-http-client/1.1",
        "transfer-encoding": "chunked",
        "accept-encoding": "gzip",
        "ce-id": "104b5cac-4f02-4738-bcfc-c805de422861",
        "ce-source": "/apis/tekton.dev/v1beta1/namespaces/devops/taskruns/deploy-run-7x5ft-get-info-wjsnz",
        "ce-specversion": "1.0",
        "ce-subject": "deploy-run-7x5ft-get-info-wjsnz",
        "ce-time": "2021-02-03T21:13:43.015077921Z",
        "ce-type": "dev.tekton.event.taskrun.running.v1",
        "connection": "close",
        "content-type": "application/json",
        "eventlistener-request-url": "/"
    },

```
However, the task did succeed:
`
deploy-run-7x5ft-get-info-wjsnz                           48 minutes ago   7 seconds    Succeeded
`
I'm using the cloudevents to notify github of status change. However, with this issue, it becomes hard to keep track of status of tasks on github. Please let me know if you need more info. 
- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-gke.1600", GitCommit:"7c407f5cc8632f9af5a2657f220963aa7f1c46e7", GitTreeState:"clean", BuildDate:"2020-12-07T09:22:27Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
Client version: 0.13.0
Pipeline version: v0.20.1
Triggers version: v0.11.2
Dashboard version: v0.13.0

**Comment by afrittoli** [comment]
@skk2142 Thanks for reporting the issue!
A few questions:
Are you able to reproduce this issue consistently?
Do you see it happening on a regular basis? 
Do you see the issue happening more with specific pipelines / tasks?
Thank you!

**Comment by skk2142** [comment]
I see this happening sporadically and it is not limited to a specific taskrun. I saw this issue happening multiple times yesterday. I will check again today in a few hours. Here's the spec of the task for which I logged the events:
```yaml
taskSpec:
    params:
      - name: repoName
        type: string
      - name: commitSha
        type: string
    steps:
      - name: get-info
        image: stedolan/jq
        script: |
          #!/usr/bin/env bash
          set -e
          imagemap={{ $.Values.tekton.gitRepoToHelmKey | toJson | quote }}
          helmImageKey=`echo ${imagemap} | jq -r '."$(params.repoName)"'`
          echo -n "${helmImageKey}" | tee $(results.helmImageKey.path)
          echo -n "gcr.io/{{ $.Values.googleProjectId }}/${helmImageKey}:$(params.commitSha)" | tee $(results.image.path)
    results:
      - name: helmImageKey
        description: helm key for the service
      - name: image
        description: name of image
```
