### ISSUE TITLE
Pod Template for Task

### ISSUE THREAD

**Issue by skk2142** [tektoncd/pipeline#3756]
### Feature request
PodTemplate for task
### Use case
I want a certain task (kaniko build) to always run in a pod with certain memory and cpu allocated. Currently, I have to specify it for every taskrun or pipelinerun separately which is not DRY.

**Comment by skk2142** [comment]
Acutally, resources can be specified within a step template. That solves the problem:

**Comment by skk2142** [comment]
I have another use case. If I want a task to always run on a node with certain labels, currently I will have to specify the node selector in every taskRun/pipelineRun. Is there a way to specify node constraint at the task level?

**Comment by ErmakovDmitriy** [comment]
Hi @skk2142,

I saw your issue and you wrote that the resources could be configured using pipelinerun, Task Step template.
I tried to look through the Tekton docs and couldn't find an example.

Could you, please, share examples for specifying requests.cpu, request.memory, limits.cpu, limits.memory in PipelineRun, Task step?

Thank you in advance.

**Comment by skk2142** [comment]
You can specify container resources in the step of a task:
```yaml
steps:
  - name: build-and-push
    workingDir: "$(resources.inputs.source.path)"
    image: "$(params.BUILDER_IMAGE)"
    resources:
      requests:
        memory: 16Gi
        cpu: 1800m
```
You can also specify pod level template for a task in pipelinerun under taskPodTemplate
```yaml
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: frontend-deploy-run-
    annotations:
      kollate.tekton.dev/commitSha: "$(tt.params.commitSha)"
      kollate.tekton.dev/repoFullName: "$(tt.params.repoFullName)"
      kollate.tekton.dev/githubNotify: "true"
  spec:
    pipelineRef:
      name: frontend-deploy
    serviceAccountNames:
      - taskName: build-and-push
        serviceAccountName: github-sa
      - taskName: update-helm-chart
        serviceAccountName: github-sa
      - taskName: helm-deploy
        serviceAccountName: helm-upgrade
    params:
      # - name: newImageUrl
        # value: gcr.io/{{ $.Values.googleProjectId }}/$(tt.params.helmImageKey):$(tt.params.commitsha)
      - name: repoName
        value: $(tt.params.repoName)
      - name: repoFullName
        value: $(tt.params.repoFullName)
      - name: commitSha
        value: $(tt.params.commitSha)
      - name: gitRevision
        value: $(tt.params.gitRevision)
    taskRunSpecs:
    - pipelineTaskName: build-and-push
      taskPodTemplate:
        {{- $.Values.taskPodTemplate | toYaml | nindent 12 }}
    {{- range $i, $browser := tuple "firefox" "chrome" }}
    {{- range $j, $index := tuple 1 2 3 4 5 6 7 8 }}
    - pipelineTaskName: cypress-{{ $browser }}-{{ $index }}
      taskPodTemplate:
        {{- $.Values.taskPodTemplate | toYaml | nindent 12 }}
    {{- end }}
    {{- end }}
```
