### ISSUE TITLE
Artifact upload fails on what appears to be an extra step

### ISSUE THREAD

**Issue by nwang92** [tektoncd/pipeline#3760]
# Expected Behavior

When using S3/GCS bucket storage to persist output artifacts in a task, it should execute in the correct order and return successfully.
 
# Actual Behavior

The injected steps to facilitate the upload do not seem to be waiting for the previous step(s) to complete. Specifically, the problem is with what appears to be an extra "upload" container/step. I'm not certain if that step is even necessary, given it doesn't get the BOTO_CONFIG env var added, but it's failing before the previous steps finish.

# Steps to Reproduce the Problem

1. Create a PipelineRun using the following manifest:
```yaml
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: steps-
  namespace: tekton-pipelines
spec:
  resources:
    - name: os-info
      resourceSpec:
        type: storage
        params:
          - name: location
            value: s3://some-bucket/archive.zip
          - name: type
            value: gcs
  pipelineSpec:
    resources:
    - name: os-info
      type: storage
    tasks:
    - name: step-1
      taskSpec:
        resources:
          outputs:
          - name: os-info
            type: storage
        steps:
        - name: get-os-info
          image: alpine:3.13.1
          script: |
            #!/bin/sh
            echo "hello world"
            cat /etc/os-release
            cat /etc/os-release > /workspace/output/os-info/content
            sleep 60
      resources:
        outputs:
        - name: os-info
          resource: os-info
    - name: step-2
      resources:
        inputs:
        - name: os-info
          resource: os-info
          from: [ step-1 ]
      taskSpec:
        resources:
          inputs:
          - name: os-info
            type: storage
        steps:
        - name: print-os-info
          image: alpine:3.13.1
          script: |
            #!/bin/sh
            echo "hello world"
            sleep 60
```

2. `kubectl -n tekton-pipelines create -f <above-yaml-file>`
3. Watching the pipeline run in the Tekton Dashboard shows the last step of the first task hits an error. Additionally, I'm not certain what the difference is between the "artifact-copy-to-" and "upload-" steps. See following screenshots and pod outputs:
<img width="1105" alt="Screen Shot 2021-02-12 at 5 17 31 PM" src="https://user-images.githubusercontent.com/6201822/107837743-41e45f00-6d57-11eb-98e8-fe04b6bb2eca.png">

```yaml
...
- args:
    - -wait_file
    - /tekton/tools/1
    - -post_file
    - /tekton/tools/2
    - -termination_path
    - /tekton/termination
    - -entrypoint
    - gsutil
    - --
    - cp
    - -P
    - -r
    - /workspace/output/os-info
    - s3://some-bucket/steps-h8rl7-tekton-pipelines-bucket/step-1/os-info
    command:
    - /tekton/tools/entrypoint
    env:
    - name: BOTO_CONFIG
      value: /var/bucketsecret/tekton-storage/boto-config
    image: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:27b2c22bf259d9bc1a291e99c63791ba0c27a04d2db0a43241ba0f1f20f4067f
    imagePullPolicy: IfNotPresent
    name: step-artifact-copy-to-os-info-c5kd8
    resources:
      requests:
        cpu: "0"
        ephemeral-storage: "0"
        memory: "0"
    terminationMessagePath: /tekton/termination
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/bucketsecret/tekton-storage
      name: volume-bucket-tekton-storage
    - mountPath: /tekton/tools
      name: tekton-internal-tools
    - mountPath: /tekton/creds
      name: tekton-creds-init-home-v86cj
    - mountPath: /workspace
      name: tekton-internal-workspace
    - mountPath: /tekton/home
      name: tekton-internal-home
    - mountPath: /tekton/results
      name: tekton-internal-results
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-2sgwz
      readOnly: true
    workingDir: /workspace
  - args:
    - -wait_file
    - /tekton/tools/2
    - -post_file
    - /tekton/tools/3
    - -termination_path
    - /tekton/termination
    - -entrypoint
    - gsutil
    - --
    - cp
    - /workspace/output/os-info/*
    - s3://some-bucket/archive.zip
    command:
    - /tekton/tools/entrypoint
    image: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:27b2c22bf259d9bc1a291e99c63791ba0c27a04d2db0a43241ba0f1f20f4067f
    imagePullPolicy: IfNotPresent
    name: step-upload-os-info-hbh2r
    resources:
      requests:
        cpu: "0"
        ephemeral-storage: "0"
        memory: "0"
    terminationMessagePath: /tekton/termination
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tekton/tools
      name: tekton-internal-tools
    - mountPath: /tekton/creds
      name: tekton-creds-init-home-ck4fw
    - mountPath: /workspace
      name: tekton-internal-workspace
    - mountPath: /tekton/home
      name: tekton-internal-home
    - mountPath: /tekton/results
      name: tekton-internal-results
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-2sgwz
      readOnly: true
    workingDir: /workspace
```

# Additional Info

- Kubernetes version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
$ kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'
v0.20.1
```
