### ISSUE TITLE
Unable to get tasks.TASK-NAME.status in finally section of the Pipeline

### ISSUE THREAD

**Issue by dmitry-mightydevops** [tektoncd/pipeline#3762]
# Expected Behavior

Unable to get `tasks.TASK-NAME.status` in **finally** section of the **Pipeline**
Trying to follow this [example - pipelinerun-task-execution-status.yaml](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/pipelinerun-task-execution-status.yaml)

Essentially speaking I need to pass the value, which will be analyzed inside the **slack-notification** task based on the execution status of previous tasks. And if it fails - send a "Failure" notification, otherwise "Success" notification.

**Here is my Pipeline:**

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: backend-build-pipeline
spec:
  description: >-
    Pipeline will only build the image utilizing buildpacks and then send notification via slack.
    The deployment is done via argocd

  params:
    - name: application
    - name: head_commit
    - name: head_commit_message
    - name: pusher_name
    - name: pusher_email
    - name: pusher_avatar
    - name: pusher_url
    - name: repository_url
    - name: repository_ssh_url
    - name: branch
    - name: buildpack_builder_image
    - name: buildpack_runner_image
    - name: docker_registry
    - name: environment

  workspaces:
    - name: source

  resources:
    - name: app
      type: git
    - name: image
      type: image
    - name: kubernetes-repo
      type: git
  
  tasks:
    - name: buildpack
      taskRef:
        name: buildpack
      resources:
          inputs:
            - name: app
              resource: app
          outputs:
              - name: image
                resource: image
      params:
        - name: builder_image
          value: "$(params.buildpack_builder_image)"
        - name: run_image
          value: "$(params.buildpack_runner_image)"
        - name: docker_registry
          value: $(params.docker_registry)
        - name: cache
          value: $(params.application)-buildpacks-cache
        - name: environment
          value: "$(params.environment)"
      workspaces:
        - name: source
          workspace: source  

    - name: kustomize
      taskRef:
        name: kustomize
      resources:
        inputs:
          - name: kubernetes-repo
            resource: kubernetes-repo
      params:
        - name: branch
          value: $(params.branch)
        - name: image
          value: "$(params.docker_registry)/$(params.application):$(params.head_commit)"
        - name: environment
          value: "$(params.environment)"
      runAfter: 
        - buildpack
    
    - name: argocd-deploy
      taskRef:
        name: argocd-deploy
      params:
        - name : argocd_application_name
          value: "$(params.application)"
      runAfter: 
        - kustomize
    
  finally:
    - name: checker
      params:
        - name: buildpack_status
          value: "$(tasks.buildpack.status)"
        - name: kustomize_status
          value: "$(tasks.kustomize.status)"
        - name: argocd_deploy_status
          value: "$(tasks.argocd-deploy.status)"
      taskSpec:
        params:
          - name: buildpack_status
          - name: kustomize_status
          - name: argocd_deploy_status
        steps:
          - image: alpine
            name: verify-status
            script: |
              if [[ $(params.buildpack_status) != "Succeeded" ||  $(params.kustomize_status) != "Succeeded" || $(params.argocd_deploy_status) != "Succeeded" ]]; then
                exit 1;
              fi

    - name: slack-notification
      taskRef:
        name: slack-notification
      params:
        - name: status
          value: "$(tasks.checker.status)"
        - name: application
          value: "$(params.application)"
        - name: head_commit
          value: "$(params.head_commit)"
        - name: head_commit_message
          value: "$(params.head_commit_message)"
        - name: pusher_name
          value: "$(params.pusher_name)"
        - name: pusher_email
          value: "$(params.pusher_email)"
        - name: pusher_avatar
          value: "$(params.pusher_avatar)"
        - name: pusher_url
          value: "$(params.pusher_url)"
        - name: repository_url
          value: "$(params.repository_url)"
        - name: branch
          value: "$(params.branch)"
        - name: environment
          value: "$(params.environment)"
```

# Actual Behavior

```
[status : verify-status] + tasks.buildpack.status
[status : verify-status] /tekton/scripts/script-0-6xn95: line 3: tasks.buildpack.status: not found
[status : verify-status] + tasks.kustomize.status
[status : verify-status] /tekton/scripts/script-0-6xn95: line 3: tasks.kustomize.status: not found
[status : verify-status] + tasks.argocd-deploy.status
[status : verify-status] /tekton/scripts/script-0-6xn95: line 3: tasks.argocd-deploy.status: not found
[status : verify-status] + '[[' '!=' Succeeded -o '!=' Succeeded -o '!=' Succeeded ]]
[status : verify-status] sh: Succeeded: unknown operand

```

# Additional Info

- Kubernetes version:

```
✗  kubectl version  
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
➜ tkn version                                             
Client version: 0.15.0
Pipeline version: v0.15.2
Triggers version: v0.11.2
Dashboard version: v0.14.0
```
