### ISSUE TITLE
Github Interceptor: invalidation of the secret returns positive http code with the response

### ISSUE THREAD

**Issue by dmitry-mightydevops** [tektoncd/pipeline#3763]
# Expected Behavior

If github's repository webhook settings have incorrect **secret** value then the following things happen with a new push:

1. Request is not starting the PipelineRun and I see the error in the logs of the pod (good)

2. A proper error inside trigger event listener POD, like "security token" mismatch, right now it displays the incorrect reason for the failure. 

3. I expected a proper HTTP error code to be returned with the response to github, i.e. **401 Not Authorized**, but instead, **HTTP 202** is returned and Github shows that everything went OK (no errors)

# Actual Behavior

Inside trigger event listener pod:

```bash
kubectl get logs el-backend-build-pipeline-trigger-event-listener-77555d7b5xkxdm

{"level":"info","ts":"2021-02-15T02:39:56.042Z","logger":"eventlistener","caller":"sink/sink.go:211","msg":"interceptor stopped trigger processing: rpc error: code = FailedPrecondition desc = payload signature check failed","knative.dev/controller":"eventlistener","/triggers-eventid":"mkskk","/trigger":"backend-prod-trigger","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"211","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"}}
{"level":"info","ts":"2021-02-15T02:39:56.062Z","logger":"eventlistener","caller":"sink/sink.go:211","msg":"interceptor stopped trigger processing: rpc error: code = FailedPrecondition desc = expression body.ref == 'refs/heads/staging' did not return true","knative.dev/controller":"eventlistener","/triggers-eventid":"mkskk","/trigger":"backend-staging-trigger","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"211","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"}}
{"level":"info","ts":"2021-02-15T02:39:56.064Z","logger":"eventlistener","caller":"sink/sink.go:211","msg":"interceptor stopped trigger processing: rpc error: code = FailedPrecondition desc = expression body.ref == 'refs/heads/develop' did not return true","knative.dev/controller":"eventlistener","/triggers-eventid":"mkskk","/trigger":"backend-development-trigger","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"211","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"}}
```

Github receives HTTP 202 code
![image](https://user-images.githubusercontent.com/70822710/107899968-a8eb4a80-6ef4-11eb-9050-67198fa347fc.png)

# Steps to Reproduce the Problem

```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: backend-build-pipeline-trigger-event-listener
spec:
  serviceAccountName: backend-triggers-sa
  triggers:
  - name: backend-prod-trigger
    interceptors:
    - github:
        secretRef:
          secretName: pga-backend-webhook-secret
          secretKey: secret-token
        eventTypes:
        - push
    - cel:
        filter: "body.ref == 'refs/heads/main'"
    bindings:
    - ref: backend-production-env
    - ref: backend-github-trigger-binding
    template:
      name: backend-build-pipeline-trigger-template
```

# Additional Info

- Kubernetes version:

```
➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
✗  tkn version                                              
Client version: 0.15.0
kuPipeline version: v0.15.2
Triggers version: v0.11.2
Dashboard version: v0.14.0
```
