### ISSUE TITLE
Variable Substitution Not Working in Tasks

### ISSUE THREAD

**Issue by rjackowens** [tektoncd/pipeline#3781]
# Expected Behavior
Pipeline parameters substituting when using `$(params.<name>)` syntax as specified [here](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#using-variable-substitution).

Task File:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  params:
    - name: person
      description: Name of person to greet
      type: string
  steps:
    - name: say-hello
      image: docker.io/library/ubuntu
      command:
        - /bin/bash
      args: ['-c', 'echo Hello $(params.person)']
```
CLI command: `tkn task start --showlog -p person=World hello`

Expected Output:
`[say-hello] Hello World`

# Actual Behavior
Pipeline parameters not substituting.

Actual Output:
```
PS > tkn task start --showlog -p person=World hello
TaskRun started: hello-run-qf6qn
Waiting for logs to be available...
[say-hello] {"level":"info","ts":1614028051.8906758,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
[say-hello] /bin/bash: params.person: command not found
```

# Steps to Reproduce the Problem

1. Create new task containing params property
2. Run task via tkn CLI `tkn task start --showlog -p person=World hello`

**Note**: The issue occurs regardless task is invoked via tkn CLI or via taskRun YAML file.

In addition to the task file above, I have also attempted to map the variable into the shell script like this:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ubuntu-test
  namespace: tekton-pipelines
spec:
  params:
    - name: var
      type: string
  steps:
    - env:
        - name: VAR
          value: $(params.var)
      image: ubuntu
      name: ''
      resources: {}
      script: |
        #!/usr/bin/env bash
        echo "Hello from Bash $VAR!"
```

When I run this task, I see the following ouput:
`[unnamed-0] Hello from Bash $(params.var)!`

# Additional Info
- Kubernetes version: v1.19.0

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+1833054", GitCommit:"183305424c91636d683dfb4a379204c313976be2", GitTreeState:"clean", BuildDate:"2021-01-22T14:47:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.16.0
Pipeline version: v0.10.1
Triggers version: v0.11.2
Dashboard version: v0.14.0
```
