### ISSUE TITLE
Variables are not replaced in workspace mountPath

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#3786]
# Expected Behavior

Variables are replaced in the `mountPath`:
For instance:

```
spec:
  params:
    - name: package
      description: package to release (e.g. github.com/<org>/<project>)
      default: github.com/tektoncd/pipeline
  workspaces:
    - name: source
      description: The workspace where the repo has been cloned
      mountPath: /go/src/$(params.package)
```

The workspace is mounted to `/go/src/github.com/tektoncd/pipeline`

# Actual Behavior

The workspace is mounted to `/go/src/$(params.package)`

# Steps to Reproduce the Problem

1. Create a task with the spec from the example
2. Add a step that prints `$(workspaces.source.path)`
3. Run the task

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.16.0
Pipeline version: v0.21.0
Triggers version: v0.11.2
Dashboard version: v0.14.0
```
