### ISSUE TITLE
[question] Is there a way to specify the tekton entrypoint image

### ISSUE THREAD

**Issue by garyyang85** [tektoncd/pipeline#3790]
Hello Team

I am using tekton in a limited network. When run task, there will be a pod generated with a init container. In this init container, it will copy tekton entrypoint from an image like below. I am wondering if can replace the image with another one? Thanks.

```
initContainers:
  - command:
    - cp
    - /ko-app/entrypoint
    - /tekton/tools/entrypoint
    image: registry.redhat.io/openshift-pipelines-tech-preview/pipelines-entrypoint-rhel8@sha256:4d18aa0dc83d65c4b47baf67da21859319f673e0237d39dedf71e1b82fbdc7ac
    imagePullPolicy: IfNotPresent
    name: place-tools
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tekton/tools
      name: tekton-internal-tools
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: pipeline-token-72dnh
      readOnly: true
```
