### ISSUE TITLE
Failed to clone private github repo

### ISSUE THREAD

**Issue by garyyang85** [tektoncd/pipeline#3797]
# Expected Behavior
git-clone can clone private github repo
# Actual Behavior
 git-clone task clone private github repo failed
# Steps to Reproduce the Problem

1. create secret
```
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
stringData:
  known_hosts: github.com,52.74.223.119 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
  ssh-privatekey: |
    -----BEGIN RSA PRIVATE KEY-----
    key content
    -----END RSA PRIVATE KEY-----
```
2. create service account
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
secrets:
  - name: ssh-key
```
3. tekton run pipeline
```
tkn pipeline start pipeline-clone  -p git-url=git@github.com:garyyang85/testclone.git   -s build-bot
```

# Additional Info

- logs:
```
[fetch-repository : clone] + CHECKOUT_DIR=/workspace/output/
[fetch-repository : clone] + [[ true == \t\r\u\e ]]
[fetch-repository : clone] + cleandir
[fetch-repository : clone] + [[ -d /workspace/output/ ]]
[fetch-repository : clone] + rm -rf '/workspace/output//*'
[fetch-repository : clone] + rm -rf '/workspace/output//.[!.]*'
[fetch-repository : clone] + rm -rf '/workspace/output//..?*'
[fetch-repository : clone] + test -z ''
[fetch-repository : clone] + test -z ''
[fetch-repository : clone] + test -z ''
[fetch-repository : clone] + /ko-app/git-init -url git@github.com:garyyang85/testclone.git -revision master -refspec '' -path /workspace/output/ -sslVerify=true -submodules=true -depth 1
[fetch-repository : clone] {"level":"error","ts":1614606114.8517175,"caller":"git/git.go:47","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force master]: exit status 128\nWarning: Permanently added the RSA host key for IP address '13.250.177.223' to the list of known hosts.\r\nfatal: Couldn't find remote ref master\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\t/opt/app-root/src/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:47\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\t/opt/app-root/src/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:137\nmain.main\n\t/opt/app-root/src/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:52\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:203"}
[fetch-repository : clone] {"level":"fatal","ts":1614606114.8519487,"caller":"git-init/main.go:53","msg":"Error fetching git repository: failed to fetch [master]: exit status 128","stacktrace":"main.main\n\t/opt/app-root/src/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:203"}
```

- Kubernetes version:
```
Kubernetes Version: v1.19.0+7070803
```

- Tekton Pipeline version:
```
Client version: 0.13.1
Pipeline version: v0.16.3
Triggers version: v0.8.1
```
