### ISSUE TITLE
Know the name of the PVC that a volumeClaimTemplate creates (associated with the workspace)

### ISSUE THREAD

**Issue by andrewballantyne** [tektoncd/pipeline#3800]
### Feature request

I would like to be able to know the name of the PVC that was created by the `volumeClaimTemplate` I used on my PipelineRun or TaskRun, specifically in relation to the workspace name.

Creation of either a Task Run or Pipeline Run that uses `volumeClaimTemplates`, the best we have is the owner reference on the PVC but no reference of what workspace it's related to.

When creating through a Pipeline Run, the Task Runs have a reference name to the PVC in their `spec`... this done more widely on the status of the Pipeline Run and Task Run would make a more consistent flow of information.

**Suggestion:** Add this information into the `.status` of the Pipeline Run / Task Run. 

### Use case

Allowing the user to view related PVC resources that are created by the controller/operator and which workspace they are used for.

### Versions

- OpenShift Pipelines Operator: v1.3.0
- Tekton Pipelines: v0.19.0
- Tekton Triggers: v0.10.2
- ClusterTasks based on Tekton Catalog 0.19

### Data examples

`git-clone` ClusterTask ([from the Operator](https://github.com/openshift/tektoncd-pipeline-operator/blob/master/deploy/resources/addons/02-clustertasks/git-clone/git-clone-task.yaml))

Pipeline (a trimmed down reference of `s2i-nodejs` from the Operator):
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: example-s2i-nodejs
spec:
  params:
    - name: GIT_REPO
      type: string
    - name: GIT_REVISION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: clone-again
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      runAfter:
        - fetch-repository
      workspaces:
        - name: output
          workspace: example-clone
  workspaces:
    - name: workspace
    - name: example-clone
```

Pipeline Run example:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: example-s2i-nodejs-run
spec:
  params:
    - name: GIT_REPO
      value: 'https://github.com/pmacik/nodejs-rest-http-crud'
    - name: GIT_REVISION
      value: master
  pipelineRef:
    name: example-s2i-nodejs
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: example-clone
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```

Stand-alone Task Run example:
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: example-fetch-repository
spec:
  params:
    - name: url
      value: 'https://github.com/pmacik/nodejs-rest-http-crud'
    - name: revision
      value: master
    - name: subdirectory
      value: ''
    - name: deleteExisting
      value: 'true'
  taskRef:
    kind: ClusterTask
    name: git-clone
  workspaces:
    - name: output
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```

**Comment by sbwsg** [comment]
Do you want access to this information inside of a Task and its Steps?  If so there are two variables we've got: 

var | desc
-- | --
workspaces.<workspaceName>.claim | The name of the PersistentVolumeClaim specified as a volume source for the Workspace. Empty string for other volume types.
workspaces.<workspaceName>.volume | The name of the volume populating the Workspace.

https://github.com/tektoncd/pipeline/blob/master/docs/variables.md#variables-available-in-a-task

Do either of those do what you want?  You could write a utility Task that takes a workspace and returns this info in results:

```yaml
kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: workspace-volume-info
spec:
  workspaces:
  - name: source
  results:
  - name: claim-name
  - name: volume-name
  steps:
  - image: # an image with a shell
    script: |
      echo -n "$(workspaces.source.claim)" > $(results.claim-name.path)
      echo -n "$(workspaces.source.volume)" > $(results.volume-name.path)
```

Then run it with a TaskRun:

```yaml
kind: TaskRun                                                                                                                 
apiVersion: tekton.dev/v1beta1                                                                                                
metadata:                                                                                                                     
  name: test-run                                                                                                              
spec:                                                                                                                         
  taskRef:                                                                                                                    
    name: workspace-volume-info                                                                                                                
  workspaces:                                                                                                                 
  - name: workspace                                                                                                           
    volumeClaimTemplate:                                                                                                      
      spec:                                                                                                                   
        accessModes:                                                                                                          
          - ReadWriteOnce                                                                                                     
        resources:                                                                                                            
          requests:                                                                                                           
            storage: 256M
```

The taskrun pod logs output:

```bash
+ echo -n pvc-7e4ef8bbdb
+ echo -n ws-q7rvt
```

And the `status.taskResults` field of the TaskRun is populated as follows:

```yaml
  taskResults:
  - name: claim-name
    value: pvc-7e4ef8bbdb
  - name: volume-name
    value: ws-q7rvt
```

Then you can use those results as part of your pipelines or read from the TaskRun's `status.taskResults` field.
