### ISSUE TITLE
Be able to use pipeline execution status in pipeline finally

### ISSUE THREAD

**Issue by esphen** [tektoncd/pipeline#3806]
### Feature request

It's currently possible to [check individual tasks's execution status](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/pipelinerun-task-execution-status.yaml) in a pipeline's finally, but seemingly not the pipeline's execution status as a whole. One could imagine this is a pretty common usecase, as acting on the pipeline's result would make control flow easier as checking each individual task's execution status doesn't scale with larger pipelines. Having a single field for the pipeline result that the user could combine with [when expressions](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md?rgh-link-date=2020-10-22T21%3A23%3A14Z#guard-task-execution-using-whenexpressions) would make a pretty user-friendly way clean up after a pipeline depending on the results.

This feature request suggests adding a variable binding to the pipeline that is accessible from a pipeline's "finally". For example `context.pipelineRun.status` or similar. 

### Use case

We're trying to implement our first pipeline using the [github-set-status](https://github.com/tektoncd/catalog/tree/master/task/github-set-status/0.2) task. Roughly the idea is to set the github commit status to pending when the pipeline starts, do some stuff, and whenever the pipeline fails sets the github commit status to failed. The latter I just can't seem to figure out.

I would like to do something like the following (some parts omitted for brevity):

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
spec:
  tasks:
    - name: github-set-pending
      taskRef:
        name: github-set-status
      params:
        - name: STATE
          value: pending
    # .. More tasks
  finally:
    - name: github-set-error
      when:
        - input: "$(context.pipelineRun.status)"
          operator: in
          values: ["Failure"]
      taskRef:
        name: github-set-status
      params:
        - name: STATE
          value: error
        - name: DESCRIPTION
          value: "$(context.pipelineRun.statusMessage)"
```

From the documentation it's unclear what the idiomatic way to fetch pipeline execution status in finally is. I looked for some time without finding it, apologies if I missed something obvious.

If this feature is hard to implement, then it may be wise to document a workaround under [Adding finally to the Pipeline](https://tekton.dev/vault/pipelines-master/pipelines/#adding-finally-to-the-pipeline) in the interim.
