### ISSUE TITLE
In performance testing,  sometimes the one pipelinerun will create multiple run even if the yaml define one pipeline vs one run

### ISSUE THREAD

**Issue by mengjieli0726** [tektoncd/pipeline#3844]
#### Expected Behavior
the pipelinerun number = the run number according to yaml file definition 
#### Actual Behavior
In performance testing,  sometimes the one pipelinerun will create multiple run even if the yaml define one pipeline vs one run
#### Steps to Reproduce the Problem
1. use the apatch benchmarking tool to create 2000 pipelinerun concurrently.
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-job-activity-
  namespace: tekton-job
spec:
  pipelineSpec:
    tasks:
    - name: job-activity1
      params:
      - name: project_id
        value: 828d13e0-e2cc-4eaa-a34e-101c653da6e9
      - name: space_id
        value: ""
      - name: job_id
        value: b90ee851-a3e1-42f0-bc4e-fbc96c285480
      - name: token
        value: eyJraWQiOiIyMDIxMDMwMTE0NTYiLCJhbGciOiJSUzI1NiJ9.eyJpYW1faWQiOiJJQk1pZC0yNzAwMDcyV1dLIiwiaWQiOiJJQk1pZC0yNzAwMDcyV1dLIiwicmVhbG1pZCI6IklCTWlkIiwianRpIjoiYzI1ZmM1ZDItYWFkNS00YzRkLTgzYjktMGY0YzgzZTQ0ZTI2IiwiaWRlbnRpZmllciI6IjI3MDAwNzJXV0siLCJnaXZlbl9uYW1lIjoiSmluIENoaSIsImZhbWlseV9uYW1lIjoiSGUiLCJuYW1lIjoiSmluIENoaSBIZSIsImVtYWlsIjoiaGVqaW5jaGlAY24uaWJtLmNvbSIsInN1YiI6ImhlamluY2hpQGNuLmlibS5jb20iLCJhdXRobiI6eyJzdWIiOiJoZWppbmNoaUBjbi5pYm0uY29tIiwiaWFtX2lkIjoiaWFtLTI3MDAwNzJXV0siLCJuYW1lIjoiSmluIENoaSBIZSIsImdpdmVuX25hbWUiOiJKaW4gQ2hpIiwiZmFtaWx5X25hbWUiOiJIZSIsImVtYWlsIjoiaGVqaW5jaGlAY24uaWJtLmNvbSJ9LCJhY2NvdW50Ijp7InZhbGlkIjp0cnVlLCJic3MiOiJhZmE0YzJiOTEzZjE0YzVhYWI3MDk3MGI4YWMxN2JlYyIsImZyb3plbiI6dHJ1ZX0sImlhdCI6MTYxNDc1NjcwNywiZXhwIjoxNjE0NzYwMzA3LCJpc3MiOiJodHRwczovL2lhbS50ZXN0LmNsb3VkLmlibS5jb20vaWRlbnRpdHkiLCJncmFudF90eXBlIjoidXJuOmlibTpwYXJhbXM6b2F1dGg6Z3JhbnQtdHlwZTphcGlrZXkiLCJzY29wZSI6ImlibSBvcGVuaWQiLCJjbGllbnRfaWQiOiJkZWZhdWx0IiwiYWNyIjoxLCJhbXIiOlsicHdkIl19.hayj5fDoqCxL0aJUrAyitCBuhX4fyMV0EBZPIVjmLaUuTSJbV_5Vhldad44qP_s2La_bRZMDb02RqTu73Iav9z-ze84-GLBYZNVjMH1MJJnE4wnD6x9mtELsa-zFBB1U5OsJwfetTNh4Ip7ip6UMwKu7SF-jxBbo-IMvMOBCZNmm6g_S9om5x3piYo7IQ7XGXVEOeEYKXfmpHuwgo_NHXvX6dhqKIT6KlKuZGyENalu2AHXFHeUoJ-P1P1AleEbXU0_wlJWZk3juGF9Y9fAesAK6Wgu5tubhAV1T74Cz_unTTsozqUORvfXT8QzFrROGF3e80Vfky9Z6OwQuH9Mm7g
      taskRef:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: Job
        name: job
```
2. check the `pipeline run` vs `run` number, found it is not consistent. and Check the pr and run , found 1 pipeline run will create multiple run
``` console
[root@cws1x226 config]# kc get pr |grep pr-job-activity-zx9ct
pr-job-activity-zx9ct   True        Succeeded   20m         16m
[root@cws1x226 config]# kc get run |grep pr-job-activity-zx9ct
pr-job-activity-zx9ct-job-activity1-6jdm8   True        Success   20m         18m
pr-job-activity-zx9ct-job-activity1-hkdfx   True        Success   19m         18m
```
3. check the tekton controller log:
``` console
{"level":"info","ts":"2021-03-19T08:05:55.831Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:781","msg":"Creating a new Run object pr-job-activity-zx9ct-job-activity1-hkdfx","commit":"10870df","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"4c748563-e575-408d-94bb-4c7f41feec8f","knative.dev/key":"tekton-job/pr-job-activity-zx9ct"}
......
{"level":"info","ts":"2021-03-19T08:05:43.120Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:781","msg":"Creating a new Run object pr-job-activity-zx9ct-job-activity1-6jdm8","commit":"10870df","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"e5383f95-19a7-41ef-a730-a2661f140633","knative.dev/key":"tekton-job/pr-job-activity-zx9ct"}
```

#### Additional Info

- Kubernetes version:
```console
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
 

- Tekton Pipeline version:
```console
[root@cws1x226 config]# tkn version
Client version: 0.16.0
Pipeline version: v0.22.0
```
