### ISSUE TITLE
mountPath can not mount relative path

### ISSUE THREAD

**Issue by dongwangdw** [tektoncd/pipeline#3851]
I try to mount a relative math in a task. But it will be always abs path.
This is not right accoriding to the doc. I think it is a bug.
The task as below(please ignore the indention issue):
```
 apiVersion: tekton.dev/v1beta1
     kind: Task
     metadata:
       name: hello-1
     spec:
       workspaces:
         - name: source
           mountPath: test-dir
       steps:
         - name: set-rel-path
           image: registry.access.redhat.com/ubi8/ubi-minimal
           script: |
             echo hello!
             sleep 5m
```

The result I got as:
``` kexec hello-run-create-file-5cpgd-pod-5nntg -- ls /test-dir/
/test-dir/:
foo
```

And 

```
kexec hello-run-create-file-5cpgd-pod-5nntg -- ls -l /workspace/
/workspace/:
total 0
```

From the doc:
>mountPath can be either absolute or relative. Absolute paths start with / and relative paths start with the name of a directory. For example, a mountPath of "/foobar" is absolute and exposes the Workspace at /foobar inside the Task's Steps, but a mountPath of "foobar" is relative and exposes the Workspace at /workspace/foobar.

I exepect /workspace/test-dir not /test-dir.

Version info:
```
Client version: 0.16.0
Pipeline version: v0.21.0
Triggers version: v0.12.0
```

Or didI miss anything?
