### ISSUE TITLE
Allow tasks to publish results specified by Pipeline spec

### ISSUE THREAD

**Issue by jmcshane** [tektoncd/pipeline#3853]
### Feature request

Allow taskrun to pick up results from a broader context, such as the invoking pipelinerun.

### Use case

I have a task in my Tekton Pipelines that I am using to fetch some parameters from an external source that provides a map of parameters. I then use those parameters later in the pipelinerun. Our current setup looks like this:

```
  - name: inject-params
    runAfter:
    - fetch-repo
    taskSpec:
      results:
      - name: first-result
      - name: second-result
      - name: third-result
      steps:
      - image: param-injector:latest
        name: read-and-write-params
        ...lots of configurations that are the same every time (args/params/env)
      workspaces:
      - name: source
```

The problem here is the results array, which forces me to put this as an embedded task in every pipeline I am writing. What I'd like to be able to do is have a TaskRef and pass results in from the PipelineRun:

```
  - name: inject-params
    runAfter:
    - fetch-repo
    taskRef:
      name: param-injector
    results:
      - name: first-result
      - name: second-result
      - name: third-result
```

The populated `taskRef` could be passed the results array when it gets assembled at invocation time.
