### ISSUE TITLE
Pipe symbol in task result

### ISSUE THREAD

**Issue by qtheya** [tektoncd/pipeline#3858]
Hello
I'm trying to use task result but it's adding "|" symbol to output that is making output value incorrect
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: app-version
spec:
  results:
    - name: calVer
      description: docker image tag
  params:
  - name: timestamp
  - name: dateFormat
  - name: ecr
  workspaces:
  - name: app-source
  steps:
  - name: generate-calender-version
    image: $(params.ecr)/git
    workingDir: "$(workspaces.app-source.path)"
    script: |
      #!/usr/bin/env sh
      
      date $(params.dateFormat) -d @$(params.timestamp) > $(results.calVer.path)
      
      cat $(results.calVer.path)
```
This step generates:
![image](https://user-images.githubusercontent.com/9653011/112589621-18186080-8e0a-11eb-88fd-a5b7c7ba4f0d.png)
![image](https://user-images.githubusercontent.com/9653011/112589644-249cb900-8e0a-11eb-8292-c180bf22a9f5.png)
Then in Pipeline i'm using calVer result in downstream task:
```yaml
  - name: www-build
    taskRef:
      name: app-build
    runAfter:
    - www-version
    params:
    - name: appName
      value: $(params.appName)
    - name: calVer
      value: $(tasks.app-version.results.calVer)
```
```yaml
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:v1.5.1
    workingDir: "$(workspaces.app-source.path)"
    command:
      - /kaniko/executor
    args:
      - --dockerfile=./Dockerfile
      - --destination="$(params.ecr)/$(params.appName):$(params.calVer)"
      - --context=./
```
On dashboard in parameters for downstream task we can see that there are 2 lines. 1st is Pipe "|" and 2nd is Tab or Space and then value
```bash
|
  2021.03.24.155712
```
![image](https://user-images.githubusercontent.com/9653011/112589947-a68ce200-8e0a-11eb-8fb2-e1dd16488fce.png)

And of course error log from kaniko
```bash
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: getting tag for destination: tag can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-.ABCDEFGHIJKLMNOPQRSTUVWXYZ`: 2021.03.24.155712
"
```
I found documentation where described taskResults and there are pipes in values
https://github.com/tektoncd/pipeline/blob/main/docs/developers/README.md#how-task-results-are-defined-and-outputted-by-a-task
From doc
```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
...
status:
...
  taskResults:
  - name: current-date-human-readable
    value: |
      Wed Jan 22 19:47:26 UTC 2020
  - name: current-date-unix-timestamp
    value: |
      1579722445
```

Tekton installed via Operator
```
image: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/operator:v0.21.0-1@sha256:b2548538c47533fef0a923bd2338174b0177f147a224c9dd399b6c2c10feface
```
Will appreciate any advice. Thank you
