### ISSUE TITLE
Task should fail if Container fails to mount 

### ISSUE THREAD

**Issue by Homopatrol** [tektoncd/pipeline#3897]
### Feature request
I recently ran into this bug where I was purposely providing incorrect secret into a task .
```
volumeMounts:
        - mountPath: /home/.docker/
          name: registry-creds
  volumes:
    - name: registry-creds
      secret:
        items:
          - key: .dockerconfigjson
            path: config.json
        secretName: $(params.reg-secret-name)
```
However instead of the task failing it instead hanged and I had to go into the console in order to check this had failed as expected.
```
Normal   Scheduled    46s                default-scheduler  
Successfully assigned tekton-pipelines/simple-page-pipeline-run-9bzv5-vuln-scan-build-q92vl-pod-c2jcf
 to 10.112.78.7 Warning  FailedMount  14s (x7 over 46s)  kubelet   MountVolume.SetUp failed for volume "registry-creds" : secret 
"sbu-pipeline2" not found
```
My request is that if the a Container fails to spin up, we should output an error message and the task should fail instead of hanging.
In addition to this could there be a way to check if the credentials provided are correct and provide that feedback to the user?

### Use case

This would allow for easy and friendly debugging if something were to fail and the task could not start the user would be able to notice and take action rather than waiting and having to go to the cli.
