### ISSUE TITLE
Private git (also need proxy) clone failed

### ISSUE THREAD

**Issue by Xinyan272** [tektoncd/pipeline#3959]
### Problem:
I configured the secret token required by the private gitlab according to this [auth.md](https://github.com/tektoncd/pipeline/blob/main/docs/auth.md#configuring-authentication-for-git), and use httpsProxy in pipelineResource. But the two cannot work at the same time. It means in taskRun, the content of the service account will be executed first, it will try to connect and auth to the private gitlab address use secrets, but I need a proxy to connect, so there will be a connection failure error. How can I use secrets and proxy together?

### Yaml Templates:
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: gitlab-access-token
  annotations:
    tekton.dev/git-0: 'https://private-gitlab.com'
data:
  password: 'gitlab-access-token'
  username: token
type: kubernetes.io/basic-auth
```

```yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline-account
secrets:
  - name: gitlab-access-token
```

```yaml
kind: PipelineResource
apiVersion: tekton.dev/v1alpha1
metadata:
  name: git-r
spec:
  params:
    - name: url
      value: 'https://private-gitlab.com'
    - name: revision
      value: master
    - name: httpsProxy
      value: 'http://proxy.com'
    - name: httpProxy
      value: 'http://proxy.com'
  type: git
```

```yaml
kind: TaskRun
apiVersion: tekton.dev/v1alpha1
metadata:
  generateName: git-pr-
spec:
  resources:
    inputs:
      - name: git-source
        resourceRef:
          name: git-r
  serviceAccountName: pipeline-account
  taskRef:
    kind: Task
    name: git-clone
```

### Error Output :
```bash
{"level":"error","ts":1621328762.4808888,"caller":"git/git.go:54","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force dev]: exit status 128\nfatal: unable to access 'https://private-gitlab.com/': The requested URL returned error: 500\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:54\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:145\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:52\nruntime.main\n\truntime/proc.go:204"}
{"level":"fatal","ts":1621328762.4811654,"caller":"git-init/main.go:53","msg":"Error fetching git repository: failed to fetch [dev]: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:204"}
```

I haven't found a way to use both (proxy and secrets) in the doc.  What should I do?
