### ISSUE TITLE
Replicas in Tekton

### ISSUE THREAD

**Issue by shresthsuman** [tektoncd/pipeline#3990]
Hello Everyone,

I am quite new to Tekton.

I am facing an issue currently - replication of pods using tekton.

What I want to achieve? 
* I want to create a pipeline with two tasks.
* First task creates an echo hello pod
* Second task creates an echo goodbye pod.
* Both pods needs to have 2 replicas.

Error - unknown field "replicas" while running the tasks or pipeline.

I have tried to add replicas in spec section for both tasks and pipeline, but it does not work.
**Any idea where I went wrong?**

Here is my script - 
First task - 

```apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  replicas: 2
  steps:
    - name: hello
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World!"
```

Second Task

```apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  replicas: 2
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Goodbye World!"
```

Pipeline script - 

```apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye
spec:
  replicas: 2
  tasks:
  - name: hello
    taskRef:
      name: hello
  - name: goodbye
    runAfter:
     - hello
    taskRef:
      name: goodbye
```

**Comment by nikhil-thomas** [comment]
A task run itself is a pod. So it doesn't have a concept of replicas.

To achieve what you want, you can repeat each of those tasks 2 times (task-1-1, task-1-2, task-2-1, task-2-2) each in you pipeline. Add `runafter: [task-1-1, task-1-2]` for the repetitions of second tasks (2-1 and 2-2).

Ref: TaskRun Pod: [Russian Doll: Extending Containers with Nested Processes - Christie Wilson & Jason Hall, Google
](https://www.youtube.com/watch?v=iz9_omZ0ctk)

**Comment by shresthsuman** [comment]
Hi @nikhil-thomas, thanks for your reply.

It worked that way.

I have a follow-up question for you. May be you could assist me on this.

Goal - Deploy Graylog environment with Elasticsearch and Mongodb. 1 pod each of graylog and mongo and 2 pods of ES.

Currently, I am trying to deploy mongodb as task and a service. I have written a script for the same, but it does not work as it is supposed to. 

Here is my code - 
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mongo-deploy
  labels:
    service: mongo-deploy
spec:
  steps:
    - name: mongodb
      image: mongo:4.2
      ports:
        - containerPort: 27017


---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    service: mongo-deploy
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017

```

Error -  

Using tekton command - ` $ tkn taskrun logs mongo-deploy-run-dqdmv -f -n default `
``` 
[mongodb] /usr/local/bin/docker-entrypoint.sh: line 4: 1: unbound variable
```

Using kubectl command - ` $ kubectl -n default logs mongo-deploy-run-dqdmv-pod-79fm4 -c step-mongodb `
```
/usr/local/bin/docker-entrypoint.sh: line 4: 1: unbound variable
```

**Comment by nikhil-thomas** [comment]
> apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mongo-deploy
  labels:
    service: mongo-deploy
spec:
  steps:
    - name: mongodb
      image: mongo:4.2
      ports:
        - containerPort: 27017


for this what you need a good old deployment yaml. And maybe a kubectl task which deploys this deployment yaml.

for example: this task https://github.com/openshift/pipelines-tutorial/blob/master/01_pipeline/01_apply_manifest_task.yaml deploys deployment manifest specified inhttps://github.com/openshift/pipelines-vote-ui/tree/master/k8s

**Comment by shresthsuman** [comment]
Hi  @nikhil-thomas, thanks for the link.

One more follow-up question for you, if you could assist me.

Currently, I am trying to deploy tutum-hello-world. I have written a script for the same, but it does not work as it is supposed to. 
I am certain that this issue is related to workspace.

Here is my code for `task-tutum-deploy.yaml`- 
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tutum-deploy
spec:
  workspaces:
    - name: messages
      optional: true
      mountPath: /root/tekton-scripts/tutum-deploy.yaml
  steps:
    - name: tutum-deploy
      image: bitnami/kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "./tutum-deploy.yaml"
```


Here is my code for `tutum-deploy.yaml` which is present on the machine (master node) of Kubernetes cluster with read, write and execute permissions - 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-tutum
  labels:
    service: hello-world-tutum
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hello-world-tutum
  template:
    metadata:
      labels:
        service: hello-world-tutum
    spec:
      containers:
      - name: tutum-hello-world
        image: tutum/hello-world:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-tutum
spec:
  type: NodePort
  selector:
    service: hello-world-tutum
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30050

```

I ran the following commands from my master node of Kubernetes cluster - 
```
1. kubectl apply -f task-tutum-deploy.yaml

2. tkn task start tutum-deploy
```

Error -  

Using tekton command - ` $ tkn taskrun logs tutum-deploy-run-tvlll -f -n default `
``` 
task tutum-deploy has failed: "step-tutum-deploy" exited with code 1 (image: "docker-pullable://bitnami/kubectl@sha256:b83299ee1d8657ab30fb7b7925b42a12c613e37609d2b4493b4b27b057c21d0f"); for logs run: kubectl -n default logs tutum-deploy-run-tvlll-pod-vbl5g -c step-tutum-deploy

[tutum-deploy] error: the path "./tutum-deploy.yaml" does not exist

container step-tutum-deploy has failed  : [{"key":"StartedAt","value":"2021-06-11T14:01:49.786Z","type":"InternalTektonResult"}]

**Comment by nikhil-thomas** [comment]
hi, by default the workingdir of a step is `/workspace`. Hence, the `[tutum-deploy] error: the path "./tutum-deploy.yaml" does not exist` error.

we will have to either set workingDir in the step or use absolute path of the deployment yaml.

ref: [working dir example](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/taskruns/workingdir.yaml)

**Comment by shresthsuman** [comment]
Hi @nikhil-thomas,

I have used mountpath to use my deployment scripts. However, it has a permission denied error.


**UPDATE**
Here is my code for `task-tutum-deploy.yaml`- 


```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tutum-deploy
spec:
  steps:
    - name: tutum-deploy
      image: bitnami/kubectl
      script: |
        kubectl apply -f /root/tekton-scripts/tutum-deploy.yaml
  workspaces:
    - name: messages
      optional: true
      mountPath: /root/tekton-scripts/
```

Error - 
```
root@master1:~/tekton-scripts# tkn taskrun logs tutum-deploy-run-8sq8s -f -n default
[tutum-deploy] + kubectl apply -f /root/tekton-scripts/tutum-deploy.yaml
[tutum-deploy] error: the path "/root/tekton-scripts/tutum-deploy.yaml" cannot be accessed: stat /root/tekton-scripts/tutum-deploy.yaml: permission denied

container step-tutum-deploy has failed  : [{"key":"StartedAt","value":"2021-06-14T12:54:01.096Z","type":"InternalTektonResult"}]
```
PS - I have placed my script on the master node at - `/root/tekton-scripts/tutum-deploy.yaml`
```
root@master1:~/tekton-scripts# ls -l tutum-deploy.yaml 
-rwxrwxrwx 1 root root 626 Jun 11 11:31 tutum-deploy.yaml
```
