### ISSUE TITLE
 error checking context: 'file ('/proc/12/fd/5') not found or excluded by .dockerignore'.

### ISSUE THREAD

**Issue by 13567436138** [tektoncd/pipeline#4003]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sidecars
spec:
  steps:
  - image: docker
    name: client
    script: |
        #!/usr/bin/env sh
        cat > Dockerfile << EOF
        FROM ubuntu
        ENTRYPOINT ["echo", "hello"]
        EOF
        docker build -t hello . && docker run hello
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /var/run/
        name: dind-socket
  sidecars:
  - image: docker:18.05-dind
    name: server
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /var/lib/docker
        name: dind-storage
      - mountPath: /var/run/
        name: dind-socket
  volumes:
  - name: dind-storage
    emptyDir: {}
  - name: dind-socket
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:
[root@master01 task]# tkn version
Client version: 0.18.0
Pipeline version: v0.24.1
Dashboard version: v0.17.0
  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
