### ISSUE TITLE
env variable not effictive

### ISSUE THREAD

**Issue by 13567436138** [tektoncd/pipeline#4004]
# Expected Behavior

# Actual Behavior
[root@master01 task]# tkn taskrun logs steptemplate-run-f42k6 -f -n tekton
[unnamed-0] FOO is ${FOO}

[unnamed-1] FOO is ${FOO}
# Steps to Reproduce the Problem

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: steptemplate
spec:
  stepTemplate:
    env:
    - name: "FOO"
      value: "bar"
  steps:
  - image: ubuntu
    command: [echo]
    args: ["FOO is ${FOO}"]
  - image: ubuntu
    command: [echo]
    args: ["FOO is ${FOO}"]
    env:
      - name: "FOO"
        value: "baz"
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
[root@master01 task]# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:
[root@master01 task]# tkn version
Client version: 0.18.0
Pipeline version: v0.24.1
Dashboard version: v0.17.0
  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
