### ISSUE TITLE
Error: failed to start container "place-tools": Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: chdir to cwd ("/home/nonroot") set in config.json failed: permission denied: unknown

### ISSUE THREAD

**Issue by 13567436138** [tektoncd/pipeline#4007]
# Expected Behavior

# Actual Behavior
Error: failed to start container "place-tools": Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: chdir to cwd ("/home/nonroot") set in config.json failed: permission denied: unknown
# Steps to Reproduce the Problem

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-podtemplate
spec:
  steps:
    - name: hello
      image: ubuntu
      command:
        - id
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: podtemplate-
spec:
  taskRef:
    name: hello-podtemplate
  podTemplate:
#    schedulerName: volcano
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
```

# Additional Info

- Kubernetes version:
[root@master01 taskrun]# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:
[root@master01 taskrun]# tkn version
Client version: 0.18.0
Pipeline version: v0.24.1
Dashboard version: v0.17.0
  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
