### ISSUE TITLE
Add Windows images to the Tekton controller

### ISSUE THREAD

**Issue by aiden-deloryn** [tektoncd/pipeline#4011]
When the Tekton controller is built, Ko generated image tags are baked into [config/controller.yaml](https://github.com/tektoncd/pipeline/blob/9de68e31c25f5587588f74be88784073a861562f/config/controller.yaml) and passed as arguments to [cmd/controller/main.go](https://github.com/tektoncd/pipeline/blob/9de68e31c25f5587588f74be88784073a861562f/cmd/controller/main.go). To add support for Windows, the controller needs to be able to deploy Windows variants of these images. At minimum this would include the Entrypoint, Nop, and Shell images.

A possible solution would be to add references for Windows images, and have the controller deploy Windows containers when the are needed. We could make use of [node selectors](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) (defined in the [PodTemplate](https://github.com/tektoncd/pipeline/blob/9de68e31c25f5587588f74be88784073a861562f/pkg/apis/pipeline/pod/template.go#L28) of a [TaskRunSpec](https://github.com/tektoncd/pipeline/blob/9de68e31c25f5587588f74be88784073a861562f/pkg/apis/pipeline/v1beta1/taskrun_types.go#L44) or [PipelineRunSpec](https://github.com/tektoncd/pipeline/blob/9de68e31c25f5587588f74be88784073a861562f/pkg/apis/pipeline/v1beta1/pipelinerun_types.go#L162)) as a point of truth for determining whether a Windows or Linux image should be used. Using the [default Kubernetes OS label](https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetes-io-os) a user can define an OS requirement using `spec.podTemplate.nodeSelector."kubernetes.io/os": "windows"` or `spec.podTemplate.nodeSelector."kubernetes.io/os": "linux"`

### No node selector is defined
If `spec.podTemplate.nodeSelector."kubernetes.io/os"` is not defined, the controller uses Linux images (i.e. no change in current behaviour).

### Linux node selector is defined
If `spec.podTemplate.nodeSelector."kubernetes.io/os"` is equal to `"linux"`, the controller uses Linux images.

### Windows node selector is defined
If `spec.podTemplate.nodeSelector."kubernetes.io/os"` is equal to `"windows"`, the controller uses Windows images.

**Comment by aiden-deloryn** [comment]
Here is an example of what an implementation might look like: https://github.com/TensorWorks/pipeline/commit/bddc128a87d6f75a04e20f1221ee59ee43cfeed3

**Comment by aiden-deloryn** [comment]
Here is an example of what a mixed OS pipeline would look like:

<details>
  <summary>example.yaml</summary>

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: example-task-windows
spec:
  steps:
    - name: probe
      image: mcr.microsoft.com/windows/nanoserver:1809
      command:
        - "ping"
      args:
        - "localhost"
        - "-n"
        - "10"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: example-task-linux
spec:
  steps:
    - name: probe
      image: alpine:latest
      command:
        - "ping"
      args:
        - "localhost"
        - "-c"
        - "10"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: example-pipeline-mixed-os
spec:
  tasks:
  - name: pipeline-task-windows
    taskRef:
      name: example-task-windows
  - name: pipeline-task-linux
    taskRef:
      name: example-task-linux
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: example-run-mixed-os
spec:
  pipelineRef:
    name: example-pipeline-mixed-os
  taskRunSpecs:
    - pipelineTaskName: pipeline-task-windows
      taskPodTemplate:
        nodeSelector:
          "kubernetes.io/os": "windows"
    - pipelineTaskName: pipeline-task-linux
      taskPodTemplate:
        nodeSelector:
          "kubernetes.io/os": "linux"
```
</details>
