### ISSUE TITLE
bad substitution

### ISSUE THREAD

**Issue by 13567436138** [tektoncd/pipeline#4026]
# Expected Behavior

# Actual Behavior
^C[root@master01 condition]# kubectl logs -f mypipeline-run2bbvr-deploy-app-dswrv-is-equal-0-5j5fh-pod-xhfc5 -n tekton
/tekton/scripts/script-0-8vp87: line 9: syntax error: bad substitution
# Steps to Reproduce the Problem

```
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: is-equal
spec:
  params:
  - name: left
    type: string
  - name: right
    type: string
  check:
    image: alpine
    script: |
      #!/bin/sh
      if [ $(params.left) = $(params.right) ]; then
        echo "$(params.left) == $(params.right)"
        exit 0
      else
        echo "$(params.left) != $(params.right)"
        exit 1
      fi
```

````
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mypipeline
spec:
  tasks:
  - name: build-app
    taskRef:
      name: build-push-kaniko
    resources:
      inputs:
      - name: workspace
        resource: workspace
      outputs:
      - name: builtImage
        resource: my-image
  - name: deploy-app
    conditions:
      - conditionRef: is-equal
        params:
          - name: left
            value: ${params.left_pipeline}
          - name: right
            value: ${params.right_pipeline}
    taskRef:
      name: kubectl-deploy
    runAfter:
    - build-app
    resources:
      inputs:
      - name: workspace
        resource: workspace
      - name: image
        resource: my-image
        from:
          - build-app
    params:
    - name: script_body
      value: $(params.script_body_pipeline)
  params:
  - name: script_body_pipeline
    type: string
  - name: left_pipeline
    type: string
  - name: right_pipeline
    type: string
  resources:
    - name: workspace
      type: git
    - name: my-image
      type: image
```

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: mypipeline-run
spec:
  serviceAccountName: test-task-robot-git-ssh
  pipelineRef:
    name: mypipeline
  params:
  - name: script_body_pipeline
    value: "kubectl apply -f /workspace/workspace/deploymen2.yaml "
  - name: left_pipeline
    value: “1”
  - name: right_pipeline
    value: “1”
  resources:
    - name: workspace
      resourceRef: 
        name: workspace
    - name: my-image
      resourceRef: 
        name: my-image
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:
[root@master01 condition]# tkn version
Client version: 0.18.0
Pipeline version: v0.24.1
Dashboard version: v0.17.0
  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**


<!-- Any other additional information -->
