### ISSUE TITLE
question: is my config effictive,second task can not executed

### ISSUE THREAD

**Issue by 13567436138** [tektoncd/pipeline#4027]
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-kaniko
spec:
  results:
  - name: test
  resources:
    inputs:
    - name: workspace
      type: git
    outputs:
    - name: builtImage
      type: image
  params:
    - name: pathToDockerFile
      description: The path to the dockerfile to build
      default: /workspace/workspace/Dockerfile
    - name: pathToContext
      description: The build context used by Kaniko
      default: /workspace/workspace
  steps:
  - name: build-and-push
    image: registry.us-west-1.aliyuncs.com/hxpapp/kaniko-executor:latest
    #env:
    #- name: "DOCKER_CONFIG"
    #  value: "/tekton/home/.docker/"
    args:
    - --dockerfile=$(inputs.params.pathToDockerFile)
    - --destination=$(outputs.resources.builtImage.url)
    - --context=$(inputs.params.pathToContext)
    - --oci-layout-path=$(inputs.resources.builtImage.path)
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker/
  - name: print-date-human-readable
    image: bash:latest
    script: |
      #!/usr/bin/env bash
      echo "true"> $(results.test.path)
      cat  $(results.test.path)
  volumes:
    - name: kaniko-secret
      secret:
        secretName: registry-secret
        items:
          - key: .dockerconfigjson
            path: config.json
```

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mypipeline
spec:
  tasks:
  - name: build-app
    taskRef:
      name: build-push-kaniko
    resources:
      inputs:
      - name: workspace
        resource: workspace
      outputs:
      - name: builtImage
        resource: my-image
  - name: deploy-app
    when:
    - input: $(tasks.build-app.results.test)
      operator: in
      values: ["true"]
    taskRef:
      name: kubectl-deploy
    resources:
      inputs:
      - name: workspace
        resource: workspace
      - name: image
        resource: my-image
        from:
          - build-app
    params:
    - name: script_body
      value: $(params.script_body_pipeline)
  params:
  - name: script_body_pipeline
    type: string
  resources:
    - name: workspace
      type: git
    - name: my-image
      type: image
```

it seems pipeline when is false. why
