### ISSUE TITLE
2021/06/11 07:44:47 Error executing command: fork/exec /tekton/scripts/script-2-qtkcs: no such file or directory

### ISSUE THREAD

**Issue by 13567436138** [tektoncd/pipeline#4033]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: volume-task
spec:
  resources:
    inputs:
      - name: workspace
        type: git
    outputs:
      - name: workspace
        type: git
  steps:
    - name: build-war
      image: busybox
      script: |
        #!/usr/bin/env bash
        tar -cvf projectname.war /workspace/workspace
        ls /custom/workspace/
      volumeMounts:
        - name: custom-volume
          mountPath: /custom
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
