### ISSUE TITLE
resoruce output paths not effective,resource not copy from /workspace/workspace to /custom

### ISSUE THREAD

**Issue by 13567436138** [tektoncd/pipeline#4036]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: volume-task
spec:
  resources:
    inputs:
      - name: workspace
        type: git
    outputs:
      - name: workspace
        type: git
  steps:
    - name: build-war
      image: busybox
      script: |
        #!/bin/sh
        tar -cvf projectname.war /workspace/workspace
      volumeMounts:
        - name: custom-volume
          mountPath: /custom
    - name: ls
      image: busybox
      script: |
        #!/bin/sh
        ls /custom
      volumeMounts:
        - name: custom-volume
          mountPath: /custom
```

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: volume-taskrun-
spec:
  taskRef:
    name: volume-task
  resources:
    inputs:
      - name: workspace
        resourceRef:
          name: workspace-java
    outputs:
      - name: workspace
        paths:
          - /custom/workspace/
        resourceRef:
          name: workspace-java
  podTemplate:
    volumes:
      - name: custom-volume
        emptyDir: {}
```

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: workspace-java
spec:
  type: git
  params:
  - name: url
    value: https://github.com/skeeto/sample-java-project.git
  - name: revision
    value: master
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
- Tekton Pipeline version:
[root@master01 paths]# tkn version
Client version: 0.18.0
Pipeline version: v0.24.1
Triggers version: v0.14.2
Dashboard version: v0.17.0
```
