### ISSUE TITLE
Error from server (BadRequest): error when creating "mypipeline-run.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: must not set the field(s): spec.pipelineref.bundle

### ISSUE THREAD

**Issue by 13567436138** [tektoncd/pipeline#4053]
# Expected Behavior
create success
# Actual Behavior
Error from server (BadRequest): error when creating "mypipeline-run.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: must not set the field(s): spec.pipelineref.bundle
# Steps to Reproduce the Problem

`````
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: mypipeline-run
spec:
  serviceAccountName: test-task-robot-git-ssh
  pipelineRef:
    name: mypipeline
    bundle: registry.cn-shanghai.aliyuncs.com/hxpdocker/build-push-kaniko:latest
  resources:
    - name: workspace
      resourceRef: 
        name: workspace
    - name: my-image
      resourceRef: 
        name: my-image
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:
[root@master01 bundle]# tkn version
Client version: 0.18.0
Pipeline version: v0.24.1
Triggers version: v0.14.2
Dashboard version: v0.17.0
  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**


<!-- Any other additional information -->
