### ISSUE TITLE
Change the error message or reason on Result Parameter Too Large

### ISSUE THREAD

**Issue by tlawrie** [tektoncd/pipeline#4060]
### Feature request

The current message for a step that has a Termination message is above max allowed size 4096 is appended to the containers (step) log and not passed back into the TaskRun and therefore cannot be easily consumed by an interacting system.

The condition is a generic failure message about looking at the logs rather than highlighting the actual issue.

```
status:
  completionTime: "2021-06-24T00:36:45Z"
  conditions:
  - lastTransitionTime: "2021-06-24T00:36:45Z"
    message: |
      "step-task" exited with code 1 (image: "docker.io/boomerangio/worker-flow@sha256:d8c227694c8779447ff790199717fe1812e9924c168089789a13fb77bd7bc930"); for logs run: kubectl -n bmrg-dev logs bmrg-flow-task-60d3d39278ff9138268edd5c-2lw8j-pod-zphpz -c step-task
    reason: Failed
    status: "False"
    type: Succeeded
```

The change I am advocating is that we update either the message or reason to be due to a documented known failure reason such as 

| status | reason | completionTime is set | Description
-- | -- | -- | --
"False" | TaskRunResultTooLarge | Yes | A step in the TaskRun has exceeded the maximum allowed 4096 byte size. |

Reference: https://tekton.dev/docs/pipelines/taskruns/#monitoring-execution-status

### Use case

This would allow systems (as well as users) that interact with Tekton to understand the issue by interrogating the condition. At the moment there is no way to distinguish this error from any other container terminating with an error code.
