### ISSUE TITLE
Cannot pass array to spec.tasks[0].when[0].values

### ISSUE THREAD

**Issue by jochen1234** [tektoncd/pipeline#4061]
I am using Tekton in openshift 4.7 and want to the when clause in pipeline to have a dynamic list to switch off/on tasks. In my test both task should not run, but only the one with the hard coded list ["blue","yellow","green"] skips. Can someone guide to what to do. Thank you very much in advance.

 Pipeline
```yaml
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test
spec:
  workspaces:
    - name: psb-deployment-checkout
  params:
    - name: deployments
      type: array
      description: "array of deployment to do"
  tasks:
    - name: getpodno1
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: "oc get pods"
      when:
        - input: "red"
          operator: in
          values: ["blue","yellow","green"]
      workspaces:
        - name: output
          workspace: psb-deployment-checkout
    - name: getpodno2
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: "oc get pods"
      when:
        - input: "red"
          operator: in
          values: ["$(spec.params.deployments)"]
      workspaces:
        - name: output
          workspace: psb-deployment-checkout
```

PipelineRun

```yaml
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: testrun
spec:
  pipelineRef:
    name: test
  serviceAccountName: default
  params:
    - name: deployments
      value:
        - "green"
        - "yellow"
        - "blue"
  workspaces:
    - name: psb-deployment-checkout
      persistentVolumeClaim:
        claimName: psb-deployment-pvc
      subPath: git-checkout
```
