### ISSUE TITLE
YAML anchors do NOT working

### ISSUE THREAD

**Issue by czerasz-allianz** [tektoncd/pipeline#4062]
# Expected Behavior

YAML anchors do NOT working with Tekton

# Actual Behavior

Currently I get:

```bash
for: "pipeline.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "_status_check"
```

For the following code:

```yaml
---
# BEGIN YAML ANCHORS
_status_check: &_status_check
  name: github-set-status-to-
  taskRef:
    kind: Task
    name: github-set-status
  params:
    - name: SOME_PARAM
      value: ...
  ...
# END YAML ANCHORS

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ...
spec:
  tasks:
  # use YAML anchors
  - <<: *_status_check
    name: github-set-status-to-pending
    params:
      - name: DESCRIPTION
        value: "CI has started"
      - name: STATE
        value: pending
  ...
```

# Steps to Reproduce the Problem

1. create the `pipeline.yaml`
  
  ```bash
  $ cat <<EOF > pipeline.yaml
  ---
  # BEGIN YAML ANCHORS
  _status_check: &_status_check
    name: github-set-status-to-
    taskRef:
      kind: Task
      name: github-set-status
    params:
      - name: SOME_PARAM
        value: test
  # END YAML ANCHORS

  apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    name: test
  spec:
    tasks:
    # use YAML anchors
    - <<: *_status_check
      name: github-set-status-to-pending
      params:
        - name: DESCRIPTION
          value: "CI has started"
        - name: STATE
          value: pending
  EOF
  ```

2. Apply `pipeline.yaml` with `--dry-run`:

  ```bash
  $ kubectl -n ci apply -f pipeline.yaml --dry-run -o yaml
  _status_check:
    name: github-set-status-to-
    params:
    - name: SOME_PARAM
      value: test
    taskRef:
      kind: Task
      name: github-set-status
  apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"_status_check":{"name":"github-set-status-to-","params":[{"name":"SOME_PARAM","value":"test"}],"taskRef":{"kind":"Task","name":"github-set-status"}},"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{},"name":"test","namespace":"ci"},"spec":{"tasks":[{"name":"github-set-status-to-pending","params":[{"name":"DESCRIPTION","value":"CI has started"},{"name":"STATE","value":"pending"}],"taskRef":{"kind":"Task","name":"github-set-status"}}]}}
    name: test
    namespace: ci
  spec:
    tasks:
    - name: github-set-status-to-pending
      params:
      - name: DESCRIPTION
        value: CI has started
      - name: STATE
        value: pending
      taskRef:
        kind: Task
        name: github-set-status
  ```

3. Apply `pipeline.yaml`:

  ```bash
  $ kubectl -n ci apply -f pipeline.yaml
  Error from server (BadRequest): error when creating "pipeline.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "_status_check"
  ```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: <redacted>
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  Client version: 0.18.0
  Pipeline version: v0.24.0
  Triggers version: v0.14.0
  Dashboard version: v0.17.0
  ```

**Comment by bobcatfish** [comment]
hey @czerasz-allianz !

looking at the expanded yaml after the dry run, it seems like the problem is that this configuration remains after the anchor is applied:

```
_status_check:
  name: github-set-status-to-
  params:
  - name: SOME_PARAM
    value: test
  taskRef:
    kind: Task
    name: github-set-status
```

Since there is no `_status_check` section in the `Pipeline` spec, the controller doesn't know what to do with it (I'm kind of surprised it doesn't ignore it, but that's another story :D )

I think that if you wanted to use yaml anchors, you'd have to refer to them within the existing configuration (i.e. it seems like you can't just add your own arbitrary section and refer to that), e.g.:

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test
spec:
  tasks:
  - &_status_check
    name: github-set-status-1
    taskRef:
      kind: Task
      name: github-set-status
    params:
    - name: SOME_PARAM
      value: test
  - <<: *_status_check
    name: github-set-status-to-pending
    params:
      - name: DESCRIPTION
        value: "CI has started"
      - name: STATE
        value: pending
~
```

(another avenue of investigation might be to use the same approach for a Pod or Deployment or some other k8s type - I'm guessing you'd run into the same issue)
