### ISSUE TITLE
admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value: no task result allowed under params,final task param pipeline_run_name has set task result as its value: spec.finally[0].params

### ISSUE THREAD

**Issue by dmitry-mightydevops** [tektoncd/pipeline#4063]
# Expected Behavior

Use of task results in `finally` task is allowed

# Actual Behavior

Received the error:

```
admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value: no task result allowed under params,final task param pipeline_run_name has set task result as its value: spec.finally[0].params
```

I'm using Pipeline version: v0.20.1, maybe this functionality was introduced in late versions?

# Steps to Reproduce the Problem

**Task**

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:     
  name: get-pipelinerun-name
spec:
  description: >-
    Obtain the exact name of the pipelinerun

  params:
    - name: application
    - name: tekton_namespace
      description: Namespace in which we run tekton (ci by default)
      default: "ci"
  
  results:
    - name: pipelinerun_name
      description: The name of the pipelinerun
  

  steps:
    - name: get-pipelinerun-name
      image: bitnami/kubectl:latest
      script: |
        pipelinerun_name=`kubectl -n $(params.tekton_namespace) get pipelinerun -l triggers.tekton.dev/trigger=$(params.application)-trigger --no-headers -o="custom-columns=NAME:.metadata.name, STATUS:.status.conditions[0].reason, COMPLETION:.status.completionTime"  | sort -r -k3,3 | head -n 1 | awk '{print $1}'`
        echo $pipelinerun_name | tee $(results.pipelinerun_name.path)

```

**Pipeline**

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: wordpress-build-pipeline
spec:
  description: >-
    Pipeline will trigger redeployments of the POD of the deployment managed by the bitnami wordpress
    chart. 

  params:
    - name: application
    - name: project
    - name: sha
    - name: head_commit
    - name: head_commit_message
    - name: pusher_name
    - name: pusher_email
    - name: pusher_avatar
    - name: pusher_url
    - name: repository_url
    - name: repository_ssh_url
    - name: environment
    - name: branch
    - name: kubernetes_namespace

  tasks:
    - name: wordpress-deployment
      taskRef:
        name: redeploy
      params:
        - name: application
          value: "$(params.application)"
        - name: kubernetes_namespace
          value: "$(params.kubernetes_namespace)"

    - name: get-pipelinerun-name
      taskRef:
        name: get-pipelinerun-name
      params:
        - name: application
          value: "$(params.application)"
        - name: tekton_namespace
          value: "ci"

  finally:
    - name: slack-notification
      taskRef:
        name: slack-notification
      params:
        - name: application
          value: "$(params.application)"
        - name: head_commit
          value: "$(params.head_commit)"
        - name: head_commit_message
          value: "$(params.head_commit_message)"
        - name: pusher_name
          value: "$(params.pusher_name)"
        - name: pusher_email
          value: "$(params.pusher_email)"
        - name: pusher_avatar
          value: "$(params.pusher_avatar)"
        - name: pusher_url
          value: "$(params.pusher_url)"
        - name: repository_url
          value: "$(params.repository_url)"
        - name: branch
          value: "$(params.branch)"
        - name: environment
          value: "$(params.environment)"
        - name: status
          value: "$(tasks.wordpress-deployment.status)"
        - name: pipeline_run_name
          value: "$(tasks.get-pipelinerun-name.results.pipelinerun_name)"

```

so it complains on 

```
 - name: pipeline_run_name
    value: "$(tasks.get-pipelinerun-name.results.pipelinerun_name)"
```

# Additional Info

- Kubernetes version:
```
✗  k version                                                                                             
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```
- Tekton Pipeline version:

```
➜ tkn version                                                     
Client version: 0.18.0
Pipeline version: v0.20.1
Triggers version: v0.11.2
Dashboard version: v0.14.0
```
