### ISSUE TITLE
Add a gateway task or grouping for pipelines

### ISSUE THREAD

**Issue by mjgkaastrupandersen** [tektoncd/pipeline#4067]
### Feature request

I would love a (possibly native) feature to create gateways in my pipeline. It should just be a "do-nothing-task", representing a gateway that waits for a group of parallel task to finish. Just as regular tasks waits for other tasks to complete in a sequential pipeline.

The purpose would be to simplify the runAfter part of a task. This would be useful if a group of tasks all need to wait for another group of tasks. As a side-effect you would have a better visual representation of the pipeline.

See the example below for my current solution/workaround.

### Use case

In this particular pipeline, I have 5 tasks that processes and applies various templates including a DeploymentConfig. Once these are completed, 3 other tasks add Configmaps and Secrets to the DeploymentConfig. 

Instead of adding each of the 5 task names to the runAfter section of the 3 tasks, requiring a total of 15 items in the runAfter section, I have added a custom task that does nothing important. It looks like this:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wait
  labels:
    app.kubernetes.io/version: '0.1'
spec:
  description: Task that can be used as a gateway for tasks in the pipeline.
  steps:
    - command:
        - /bin/bash
        - '-c'
        - echo
        - waited
      image: registry.redhat.io/ubi7/ubi-minimal
      name: 'wait'
```

This isn't particularly optimal, as it requires the pipeline to spin up a ubi-minimal pod, which takes up some resources and prolongs the pipeline run. It does, however, reduce the runAfter section to 5 items instead of the 15, that I would otherwise need to manage. And the following tasks only needs to reference the gateway task.

![image](https://user-images.githubusercontent.com/73833600/124103133-45a42400-da61-11eb-8ca1-89fed6fb8454.png)

### What I suggest

I have 2 suggestions 

* A native/special task, requiring no image or steps, which has a name and a runAfter section where you can specify the tasks to wait for.
![image](https://user-images.githubusercontent.com/73833600/124113999-5dcd7080-da6c-11eb-80c7-2fe213eff28f.png)

or

* A task grouping feature, such that you can group a list of tasks together, that the following tasks (or another task group) can reference in their respective runAfter sections.
![image](https://user-images.githubusercontent.com/73833600/124114071-6de55000-da6c-11eb-8827-384a32467710.png)

### Note

I'm aware of the experimental wait-task: https://github.com/tektoncd/experimental/tree/main/wait-task
However, it seems that the purpose of this task is to have a task that "waits a given amount of time", which is not entirely, what I'm suggesting here.
