### ISSUE TITLE
TaskRun hangs when command field is not set

### ISSUE THREAD

**Issue by dippynark** [tektoncd/pipeline#4084]
# Expected Behavior

I'm not sure if this is bug or whether I've missed something in Tekton where you have to set the `command` field, but I feel that the following TaskRun should either use the image entrypoint (which is `/kaniko/executor` from [here](https://github.com/GoogleContainerTools/kaniko/blob/v1.6.0/deploy/Dockerfile#L81)) as the command or error (and raise it in the API):

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: kaniko
spec:
  taskSpec:
    steps:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.6.0
      # command:
      # - /kaniko/executor
``` 

# Actual Behavior

If I don't uncomment the command field above then the TaskRun hangs forever and doesn't spawn a corresponding Pod. If I uncomment the command field the TaskRun fails as expected.

# Steps to Reproduce the Problem

1. `kubectl apply -f` TaskRun spec above

# Additional Info

- Kubernetes version:

  ```
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", 
  GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", 
  GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", 
  GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", 
  GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version: v0.24.1
