### ISSUE TITLE
Allow passing additional labels and annotations when using external tasks

### ISSUE THREAD

**Issue by anthonysuterag** [tektoncd/pipeline#4105]
### Feature request

When using Tasks CRD as taskRef, all the annotations and labels need to be defined inside the Task resource itself. 
There is no way to pass additional labels or annotations as far as I understood. https://github.com/tektoncd/pipeline/blob/a9b729b9e83959dbc0f00baeb83b9c8b46780f17/pkg/apis/pipeline/v1beta1/task_types.go#L176-L189.

### Use case

We would like to use Vault sidecar injection to provide sensitive information into the Task and in order to enable the sidecar injection, we need to provide annotations that are required into the task.
The problem why we can't define the annotations statically in the task because the sidecar template will be generated dynamically based on the secrets that users want to pass into the task.

**Comment by sbwsg** [comment]
All labels from the `TaskRun` are attached to the `Pod`.  Not the annotations though atm.

**Comment by anthonysuterag** [comment]
@sbwsg I believe the annotations should be attached to the `Pod` as well, because I have successfully done this when I define the tasks in `TaskSpec`. However, if I want to use `TaskRef`, there is no way to define the annotation. 

FYI, I have tried combining `TaskRef` (containing the actual steps to be executed) and `TaskSpec` (containing only the required annotations) at the same time, but I got this error `admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: expected exactly one, got both: spec.pipelinespec.tasks[0].taskRef, spec.pipelinespec.tasks[0].taskSpec missing field(s): spec.pipelinespec.tasks[0].taskSpec.steps`.

**Comment by sbwsg** [comment]
/label help-wanted

It sounds like the really tricky bit here is that we don't have support for adding annotations / metadata from a PipelineRun's PipelineTask taskRefs. But we do support this for PipelineTask taskSpec.

**Comment by sbwsg** [comment]
Another use-case here would be for when you want to add annotations to specific PipelineTasks in a PipelineRun that map to functionality on a per-Task basis.

**Comment by sbwsg** [comment]
Ahh, interesting, I don't imagine we'd want to nest an additional `metadata` field inside `TaskRef`, since this would allow for some slightly odd scenarios like:

```yaml
kind: TaskRun
apiVersion: tekton.dev/v1beta1
metadata:
  annotations:
    # ...
  taskRef:
    metadata:
      annotations:
        # ...
```

So either only allow the annotations to copied down from the PipelineRun to the TaskRun pods, or create a new type, `PipelineTaskRef`, as a copy of `TaskRef` with the addition of metadata?

**Comment by austinzhao-go** [comment]
Hi @sbwsg @wlynch, was looking into this issue and digesting the discussion..

thinking If considering the initial use case - annotations/labels to be applied for the task(s) as need, propagating these metadata perhaps leads to extra annotations on the pipeline and task(s) which don't need. 

I tended to think about more on adding the optional metadata field into the existing TaskRef, as a new type (with a minor diff on the metadata) leads to more explanation on docs and bring a bit confusing here. Also, if thinking this requirement will be also applied on TaskRun/PipelineRun, one or two naming could be needed here.

But the concern on the confusing nest naming is true. while I was thinking if the structure of yaml could help here, such as the same name fields under the diff levels.

**Comment by sbwsg** [comment]
Let's clarify the problem a bit before we proceed here. I think we need to be sure of what we are trying to solve.

Below is an example Task + Pipeline + PipelineRun. Each resource has its own annotation (`foo:foo`, `bar:bar`, `baz:baz`):

```yaml
kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: foo-task
  annotations:
    foo: foo
spec:
  steps:
  - name: echo
    image: alpine:latest
    command: ["echo", "hello world"]
---
kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: foo-pipeline
  annotations:
    bar: bar
spec:
  tasks:
  - name: echo
    taskRef:
      name: foo-task
---
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: foo-pipelinerun
  annotations:
    baz: baz
spec:
  pipelineRef:
    name: foo-pipeline
```

After running this through Tekton I observe the following:

1. The `PipelineRun` object is created with annotations  `bar` and `baz`. These come from the `PipelineRun` and the `Pipeline`.
2. A `TaskRun` object is created with annotations `foo`, `bar` and `baz`. These come from the `PipelineRun`, the `Pipeline`, and the `Task`.
3. Finally, the `Pod` is created with annotations `foo`, `bar`, and `baz`. These mirror what's on the `TaskRun` in (2).

Annotations are copied `Pipeline` -> `PipelineRun` -> `TaskRun` -> `Pod`.

The original use-case is to add annotations at "runtime" so that Vault can dynamically provision `Secrets` and mount them into a TaskRun `Pod`. We already know that `TaskRuns` copy their Annotations to their `Pods`, so the only remaining runtime type we need to worry about is `PipelineRuns`. `taskRef` is a field of `Pipeline` and is therefore an "authoring time" field and unsuitable for adding annotations at runtime. So I don't think adding metadata to `taskRef` solves for the original use-case. Instead the user should be able to define PipelineTask-specific metadata in the `PipelineRun`, since this is a "runtime" type.

Today we support a similar dynamic runtime behaviour for other fields of a PipelineTask by using `PipelineRun's` [`taskRunSpecs` field](https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md#specifying-taskrunspecs). Maybe we could add `annotations` and `labels` field [to that type](https://github.com/tektoncd/pipeline/blob/adc127a5f1215019863768d58ad88bdf1a44fb5f/pkg/apis/pipeline/v1beta1/pipelinerun_types.go#L542-L550), which would allow a PipelineRun to map annotations into one specific TaskRun Pod at runtime. @wlynch @austinzhao-go wdyt?
