### ISSUE TITLE
Finally task is skipped when dependent on results from a failed task

### ISSUE THREAD

**Issue by joshfrench** [tektoncd/pipeline#4118]
# Expected Behavior

According to the docs: "Final tasks are guaranteed to be executed in parallel after all PipelineTasks under tasks have completed **regardless of success or error**."

# Actual Behavior

If a final task references the result of a task which exited with an error, that final task is skipped.

# Steps to Reproduce the Problem

Run a pipeline with:
1. A failing task
2. A final task that depends on a result from the above

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-finally-
  namespace: default
spec:
  pipelineSpec:
    tasks:
      - name: fail
        taskSpec:
          results:
            - name: missing
          steps:
            - name: fail
              image: alpine:latest
              script: exit 1
    finally:
      - name: final
        params:
          - name: required
            value: $(tasks.fail.results.missing)
        taskSpec:
          params:
            - name: required
              default: 'ok'
          steps:
            - name: final
              image: alpine:latest
              command: ["echo"]
              args: ["$(params.required)"]
```

Inspect the run to see the skipped final task:
```
% tkn pr describe test-finally-xxxxx
Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 1 ("step-fail" exited with code 1 (image: "docker-pullable://alpine@sha256:234cb88d3020898631af0ccbbcca9a66ae7306ecd30c9720690858c1b007d2a0")

...

Skipped Tasks

 NAME
 ∙ final
```

Removing the final  task's input param and using the default value instead makes the final task run as expected.

Writing something to `$(results.missing.path)` before exiting with an error does not change the behavior; a non-zero exit code seems to be sufficient to trigger this.

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

I first discovered this on v0.23.0 but it affects the most recent version as well:

```
Client version: 0.18.0
Pipeline version: v0.26.0
Triggers version: v0.13.0
Dashboard version: v0.17.0
```

**Comment by pritidesai** [comment]
hey @joshfrench, when a task exits with an error, the results are not added to the status. The results are only initialized with successful task. @afrittoli has requested a result (or something similar) to be made available even when a task fails with error, see issue https://github.com/tektoncd/pipeline/issues/3749. 

Also, if you have a use case where you would like to continue after a step error and also have the result initialized before exiting with 1, we have a proposal to introduce a feature to ignore step error https://github.com/tektoncd/community/blob/main/teps/0040-ignore-step-errors.md. The implementation [PR](https://github.com/tektoncd/pipeline/pull/4106) is open as well. You can refer to the example demonstrating the results with failed steps [here](https://github.com/tektoncd/pipeline/pull/4106/files#diff-778825eeaefcc41a4c4d47b35e3fbc616bd544e62d38cc25970d55ade9590805R23).

**Comment by joshfrench** [comment]
Thanks @pritidesai, that's helpful context. Until one of those features is merged, is wrapping a step with `exit 0` how the community typically works around this?

**Comment by pritidesai** [comment]
> is wrapping a step with `exit 0` how the community typically works around this?

That is correct, its a workaround until we have issue #3749 fixed and PR #4106 merged.

**Comment by joshfrench** [comment]
Thanks! Looking forward to those changes.

**Comment by ekonijn** [comment]
Since #3749 is still open, you could consider a workaround, where you have a copy of the finally task that uses some dummy value instead of the missing result, something like this:
```
  finally:
  - name: report-to-teams-that-build-failed
    # when build fails, there is no tasks.update-digest.results.commit
    # and that means normal report-to-teams will not run
    when:
    - input: $(tasks.build.status)
      operator: notin
      values: [ "Succeeded" ]
    taskRef:
      kind: Task
      name: teams
    params:
    - name: config-repo-commit
      value: N/A
```
