### ISSUE TITLE
PipelineRun keep in CancelledRunningFinally status and finally task not be executed when updating running pipelineRun spec status to CancelledRunFinally

### ISSUE THREAD

**Issue by yuanyanran** [tektoncd/pipeline#4125]
# Expected Behavior
Finally task to be executed and pipelineRun status to be Cancelled after finally task done when updating running pipelineRun spec status to CancelledRunFinally
# Actual Behavior
If the pipeline DAG task with retries parameter grater than 0, when I update running pipelineRun spec status to CancelledRunFinally, running task to be cancelled but finally task not be executed and pipelineRun status keep in CancelledRunningFinally
# Steps to Reproduce the Problem

1. Run a pipeline with: a task with retries parameter greater than 0 and a finally task
2. When pipeline running, update pipelineRun spec status to CancelledRunFinally
3. Inspect pipelineRun and taskRun status:
 `message: 'Tasks Completed: 1 (Failed: 0, Cancelled 1), Incomplete: 1, Skipped: 0'
   reason: CancelledRunningFinally
   status: Unknown`
  taskRun status:
  `message: TaskRun "xxxxx" was cancelled
    reason: TaskRunCancelled
    status: "False"
    type: Succeeded`

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
v0.25.0
```

**Comment by jerop** [comment]
The issue is that `Finally Tasks` are executed only when all `DAG Tasks` are _done_
https://github.com/tektoncd/pipeline/blob/535006925b60ed8a4ff41659a6632e055cfc47c3/pkg/reconciler/pipelinerun/resources/pipelinerunstate.go#L298-L316

Where _done_ means a `Task` is _skipped_, _succeeded_ or _failed_ 

https://github.com/tektoncd/pipeline/blob/535006925b60ed8a4ff41659a6632e055cfc47c3/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L78-L80

But a `Task` is considered _failed_ only when its retries are all done

https://github.com/tektoncd/pipeline/blob/535006925b60ed8a4ff41659a6632e055cfc47c3/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L110-L121

In a scenario where a `Task` with `Retries` is `Cancelled`, it's not considered `Failed` 

**To fix this, we should include _cancelled_  to the definition of _done_**

Reproduced this issue with this example:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-task
spec:
  params:
    - name: message
      type: string
  results:
    - description: ''
      name: test-result
  steps:
    - image: ubuntu
      name: ''
      resources: {}
      script: |
        echo "$(params.message)"
        sleep 60
        echo -n "$(params.message)" > "$(results.test-result.path)"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: echo-pipeline
spec:
  tasks:
    - name: echo-task
      params:
        - name: message
          value: morning
      retries: 2
      taskRef:
        kind: Task
        name: echo-task
  finally:
    - name: echo-finally
      params:
        - name: message
          value: evening
      taskRef:
        kind: Task
        name: echo-task
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: echo-pipelinerun
spec:
  pipelineRef:
    name: echo-pipeline
#  status: "CancelledRunFinally"
```
