### ISSUE TITLE
Pipeline task retries not working occasionally

### ISSUE THREAD

**Issue by yuanyanran** [tektoncd/pipeline#4165]
# Expected Behavior
Pipeline dag tasks with retries should retry when the taskRun failed
# Actual Behavior
The pipeline dag task with retries did not retry when corresponding taskRun failed or the times retried actually less than task retries setting . 
The PipelineRun keep in running state.
```
 conditions:
  - lastTransitionTime: "2021-08-17T08:19:58Z"
    message: 'Tasks Completed: 1 (Failed: 1, Cancelled 0), Incomplete: 2, Skipped:
      0'
    reason: Running
    status: Unknown
    type: Succeeded
```
The TaskRun keep in failed state and no new pods to be created.
```
conditions:
 - lastTransitionTime: "2021-08-17T08:20:14Z"
    message: |
            "step-step-1" exited with code 127 (image: "docker-pullable://alpine@sha256:2bb501e6173d9d006e56de5bce2720eb06396803300fe1687b58a7ff32bf4c14"); for logs r
un: kubectl -n test-0804 logs pipeline-b4s8l-6-task-2-8842-ztthn-pod-pftn6 -c step-step-1
   reason: Failed
   status: "False"
   type: Succeeded
```
 It is an occasional problem. 
# Steps to Reproduce the Problem

1. run below pipeline run, watch taskRun and pipelineRun state. task-2085 and task-2084 will fail because no 'noretry' command.
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    creator: pipeline
    task: email-notify
  name: task-2086
  namespace: test-0804
spec:
  description: send email notification
  params:
  - default: ""
    name: project-name
    type: string
  - default: ""
    name: pipeline-name
    type: string
  - default: ""
    name: pipeline-run-name
    type: string
  - default: ""
    name: state
    type: string
  - default: ""
    name: receivers
    type: string
  steps:
  - args:
    - echo 'send email notification'
    command:
    - sh
    - -c
    env:
    - name: PROJECT_NAME
      value: $(params.project-name)
    - name: PIPELINE_NAME
      value: $(params.pipeline-name)
    - name: PIPELINE_RUN_NAME
      value: $(params.pipeline-run-name)
    - name: STATE
      value: $(params.state)
    - name: RECEIVERS
      value: $(params.receivers)
    image: alpine:3.8
    imagePullPolicy: Always
    name: notify
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 500Mi
    stdin: true
    timeout: 6h0m0s
    tty: true

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    creator: pipeline
    task: task-2
  name: task-2085
  namespace: test-0804
spec:
  steps:
  - args:
    - echo 'hahahaha 666' && noretry
    command:
    - sh
    - -c
    image: alpine:3.8
    imagePullPolicy: Always
    name: step-1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 500Mi
    stdin: true
    timeout: 6h0m0s
    tty: true

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    creator: pipeline
    task: task1
  name: task-2084
  namespace: test-0804
spec:
  steps:
  - args:
    - echo 'test pipeline retry, 66666' && noretry
    command:
    - sh
    - -c
    image: alpine:3.8
    imagePullPolicy: Always
    name: step-1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 500Mi
    stdin: true
    timeout: 6h0m0s
    tty: true
---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  generation: 1
  labels:
    creator: pipeline
  name: pipeline-b4s8l-1
  namespace: test-0804
spec:
  finally:
  - name: email-notify
    params:
    - name: project-name
      value: ci-test
    - name: pipeline-name
      value: pipeline-b4s8l-1
    - name: pipeline-run-name
      value: pipeline-b4s8l-6
    - name: state
      value: $(tasks.task1-9833.status),$(tasks.task-2-8842.status)
    resources: {}
    retries: 3
    taskRef:
      kind: Task
      name: task-2086
  tasks:
  - name: task1-9833
    resources: {}
    retries: 3
    taskRef:
      kind: Task
      name: task-2084
  - name: task-2-8842
    resources: {}
    retries: 3
    taskRef:
      kind: Task
      name: task-2085
---

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    creator: pipeline
    tekton.dev/pipeline: pipeline-b4s8l-1
  name: pipeline-b4s8l-6
  namespace: test-0804
spec:
  pipelineRef:
    name: pipeline-b4s8l-1
  podTemplate: {}
  serviceAccountName: default
  taskRunSpecs:
  - pipelineTaskName: task1-9833
    taskPodTemplate: {}
  - pipelineTaskName: task-2-8842
    taskPodTemplate: {}
  - pipelineTaskName: email-notify
    taskPodTemplate: {}
  timeouts:
    pipeline: 12h5m0s
    tasks: 12h0m0s
```

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
v0.25.0
```
