### ISSUE TITLE
`workspace-in-sidecar` example test is very flakey

### ISSUE THREAD

**Issue by ghost** [tektoncd/pipeline#4169]
# Expected Behavior

Examples should run reasonably consistently from PR to PR.

# Actual Behavior

I estimate that the `workspace-in-sidecar` example fails about half the time I initiate an integration run in our CI. It just doesn't seem to be able to complete successfully on a regular basis. It's super unclear why this is but here's the error log from the [most recent run](https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/4168/pull-tekton-pipeline-alpha-integration-tests/1427773298288103424/) that failed for me:

```
    build_logs.go:35: Could not get logs for pod workspace-in-sidecar-phrks-pod-x95zf: container "step-unnamed-0" in pod "workspace-in-sidecar-phrks-pod-x95zf" is waiting to start: PodInitializing
```

~~Hunch: maybe setting explicit resource requirements for the containers in the example would help?~~
^ This unfortunately did not help after all.

# Steps to Reproduce the Problem

1. Open a PR and let the integration suites run
2. Check if `workspace-in-sidecar` example failed
3. Re-run the test suites if the example passed

**Comment by sbwsg** [comment]
Here's a snippet of the yaml from the most recent failure I saw:

```yaml
        status:
          conditions:
          - lastProbeTime: null
            lastTransitionTime: "2021-08-17T23:41:18Z"
            status: "True"
            type: Initialized
          - lastProbeTime: null
            lastTransitionTime: "2021-08-17T23:41:12Z"
            message: 'containers with unready status: [step-unnamed-0 sidecar]'
            reason: ContainersNotReady
            status: "False"
            type: Ready
          - lastProbeTime: null
            lastTransitionTime: "2021-08-17T23:41:12Z"
            message: 'containers with unready status: [step-unnamed-0 sidecar]'
            reason: ContainersNotReady
            status: "False"
            type: ContainersReady
          - lastProbeTime: null
            lastTransitionTime: "2021-08-17T23:41:12Z"
            status: "True"
            type: PodScheduled
          containerStatuses:
          - image: alpine:3.12.0
            imageID: ""
            lastState: {}
            name: sidecar
            ready: false
            restartCount: 0
            started: false
            state:
              waiting:
                reason: PodInitializing
          - image: alpine:3.12.0
            imageID: ""
            lastState: {}
            name: step-unnamed-0
            ready: false
            restartCount: 0
            started: false
            state:
              waiting:
                reason: PodInitializing
          hostIP: 10.128.0.3
          initContainerStatuses:
          - containerID: docker://62d43b4aa1f1792dbccabfa9833abbbae7dfd8c94018e0d812af84d09656b153
            image: sha256:1da710f4bbbdfadf5c0f8ac1214f695105d05ea87c3f8c5795287c5bb5f50048
            imageID: docker-pullable://gcr.io/tekton-prow-13/tpipeline-e2e-img/entrypoint-bff0a22da108bc2f16c818c97641a296@sha256:4125d5f93bbd74bc178ff5c29555b3cd4ad3f11ac39e38852400224d9a3f52df
            lastState: {}
            name: place-tools
            ready: true
            restartCount: 0
            state:
              terminated:
                containerID: docker://62d43b4aa1f1792dbccabfa9833abbbae7dfd8c94018e0d812af84d09656b153
                exitCode: 0
                finishedAt: "2021-08-17T23:41:16Z"
                reason: Completed
                startedAt: "2021-08-17T23:41:16Z"
          - containerID: docker://de1044deea32e4e2fc38601f9b1cc209a9cf9ad925127ae372e3720a2fdd106f
            image: sha256:ac2afeee8f96767b2362a686e98503c9e1d1d24375be9896a0109b80e9cab631
            imageID: docker-pullable://gcr.io/distroless/base@sha256:aa4fd987555ea10e1a4ec8765da8158b5ffdfef1e72da512c7ede509bc9966c4
            lastState: {}
            name: place-scripts
            ready: true
            restartCount: 0
            state:
              terminated:
                containerID: docker://de1044deea32e4e2fc38601f9b1cc209a9cf9ad925127ae372e3720a2fdd106f
                exitCode: 0
                finishedAt: "2021-08-17T23:41:17Z"
                reason: Completed
                startedAt: "2021-08-17T23:41:17Z"
          phase: Pending
```

**Comment by sbwsg** [comment]
Under `Events` I also notice the following errors related to the emptyDir volume that the sidecar and step are supposd to share:

```
arendelle-4mlqr    4m26s       Warning   Failed                         pod/workspace-in-sidecar-phrks-pod-x95zf                                  Error: cannot find volume "ws-76s6x" to mount into container "step-unnamed-0"
arendelle-4mlqr    4m26s       Normal    Pulled                         pod/workspace-in-sidecar-phrks-pod-x95zf                                  Container image "alpine:3.12.0" already present on machine
arendelle-4mlqr    4m26s       Warning   Failed                         pod/workspace-in-sidecar-phrks-pod-x95zf                                  Error: cannot find volume "ws-76s6x" to mount into container "sidecar"
```

**Comment by bobcatfish** [comment]
especially weird that it wouldn't find the volume definition when we're using emptyDir! I thought maybe a PVC hadn't been created, but how is it possible for the emptyDir volume to not be found??

**Comment by xchapter7x** [comment]
Once PR [4634](https://github.com/tektoncd/pipeline/pull/4634) is merged, this flake should be resolved.

**Comment by xchapter7x** [comment]
> /reopen
> 
> It looks like this flaked again on #4596
> 
> The test run logs are here: https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/4596/pull-tekton-pipeline-alpha-integration-tests/1499073528324952067/

😞

**Comment by sbwsg** [comment]
From the logs in that test run we see the following:

```
    panic.go:632: #####################################################
    panic.go:632: ### Dumping logs from Pods in the arendelle-n7xcb ###
    panic.go:632: #####################################################
    build_logs.go:37: build logs 
        >>> Container step-unnamed-0:
        
        >>> Container sidecar:
        Polling channel...
        Polling channel...
        Polling channel...
        Polling channel...
        Polling channel...
        Polling channel...
        Polling channel...
        Polling channel...
        Polling channel...
        Polling channel...
```

So what we're seeing here is that the Step never created the fifo special file for communicating between the containers. Either that or the sidecar couldn't see the fifo special file for some reason.

Looking at the container statuses it looks like both were ready and started at the same time:

```
          containerStatuses:
          - containerID: docker://d37e381690e0848177f126e3c85600adcf0d543ea87030389be710a4e0f7dc06
            image: alpine:3.12.0
            imageID: docker-pullable://alpine@sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
            lastState: {}
            name: sidecar
            ready: true
            restartCount: 0
            started: true
            state:
              running:
                startedAt: "2022-03-02T17:45:33Z"
          - containerID: docker://8da5c68a979d2503c2e5c950df756171fcf63a3cec89e6139343a93633a80c2b
            image: alpine:3.12.0
            imageID: docker-pullable://alpine@sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
            lastState: {}
            name: step-unnamed-0
            ready: true
            restartCount: 0
            started: true
            state:
              running:
                startedAt: "2022-03-02T17:45:33Z"
```

The TaskRun's start time is recorded as `2022-03-02T17:45:12Z` and the pod's creation time as `2022-03-02T17:45:12Z`. So it looks like it took about 20 seconds from pod creation to step + sidecar container starts. Is it possible that it then took > 40 seconds for the step to create the fifo file?  Or that ... like ... (waves hands) ... the processes aren't being given cpu cycles enough to run in parallel ... or something?
