### ISSUE TITLE
Workspace default to `empty Dir`

### ISSUE THREAD

**Issue by hakuna-matatah** [tektoncd/pipeline#4173]
### Feature request

Today we need to define workspace  as part of triggertemplate or Task or pipeline:
```
      workspaces:
      - name: source
        emptyDir: {}
      - name: config
        emptyDir: {}
      - name: results
        emptyDir: {}
````

### Use case

Could we have it defaulted to `emptyDir` when nothing is specified ?
