### ISSUE TITLE
Problems with command execution in task

### ISSUE THREAD

**Issue by leandrodamascena** [tektoncd/pipeline#4199]
I'm trying to build a pipeline to send artifacts to AWS CodeArtifact and I'm having issues with some strange behavior.

# Expected Behavior
Execute successfully login into AWS CodeArtifact

# Actual Behavior
I can't because task definitions replace single and double quotes and aws cli can't understand or taskrun tries to run dotnet command, but dotnet is a command argument and not a command

# Steps to Reproduce the Problem

1. I created a task using this template (don't care about aws secret as env, I'll use secrets in production).. See that I tried using command + args (commented in this example) and script and both failed
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildlib
spec:
  resources:
    inputs:
    - name: source
      type: git
  steps:
    - name: auth-aws
      image: docker.io/amazon/aws-cli:2.2.33
      #args:
      #  - codeartifact
      #  - login
      #  - --tool
      #  - 'dotnet'
      #  - --repository
      #  - dotnet
      #  - --domain
      #  - artefatos
      #  - --region
      #  - us-east-1
      #command:
      #  - aws
      script:
        aws codeartifact login --tool "dotnet" --repository dotnet --domain artefatos --region us-east-1
      env:
      - name: AWS_ACCESS_KEY_ID
        value: "XXXXX"
      - name: AWS_SECRET_ACCESS_KEY
        value: "ZZZZZZ"
```

2. When I execute the task the output is:
![image](https://user-images.githubusercontent.com/4295173/131213681-1c0c730a-4164-4115-aa1e-aed83abbfa5b.png)

3. Looking at the task definition in WEB-UI I can see that the command keep the double quote but when execute it doesn't.
![image](https://user-images.githubusercontent.com/4295173/131213759-6e507a10-74bb-4a09-b9b9-596f07f3c46b.png)

4. Using the terminal I can authenticate using double quotes 
![image](https://user-images.githubusercontent.com/4295173/131213831-9a982d63-de32-4d51-8f7b-2f57680840a0.png)

# Additional Info

- Kubernetes version:

```
[ec2-user@ip-172-31-22-239 tekton]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

```
[ec2-user@ip-172-31-22-239 tekton]$ tkn version
Client version: 0.20.0
Pipeline version: v0.27.2
Dashboard version: v0.19.0
```

**Comment by leandrodamascena** [comment]
Hello...

Any kind of help here? Thanks

**Comment by lbernick** [comment]
Hi @leandrodamascena, thanks for opening this issue!

I think the problem here may be that the docker container you are running does not have the dotnet tool installed but your computer does.

**Here's what I did to try to reproduce the issue:**
A task's script is Base64 encoded and written to a tempfile; this file is decoded in an initContainer and executed in the container. I created this example task, which prints the contents of the tempfile executed by the container, and includes the command you are trying to run:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: echo
      image: docker.io/amazon/aws-cli:2.2.33
      #command:
      #  - echo
      #args:
      #  - "Hello World"
      script: |
        cat $(ls /tekton/scripts/script*)
        aws codeartifact login --tool "dotnet" --repository dotnet --domain artefatos --region us-east-1
```
When I start a taskrun from this task, here are the logs:

```
$ tkn taskrun logs echo-hello-world-run-5dn8s -f -n default
[echo] ++ ls /tekton/scripts/script-0-whfc4
[echo] + cat /tekton/scripts/script-0-whfc4
[echo] #!/bin/sh
[echo] set -xe
[echo] cat $(ls /tekton/scripts/script*)
[echo] aws codeartifact login --tool "dotnet" --repository dotnet --domain artefatos --region us-east-1
[echo] + aws codeartifact login --tool dotnet --repository dotnet --domain artefatos --region us-east-1
[echo]
[echo] Unable to locate credentials. You can configure credentials by running "aws configure".
```
You can see that the double quotes are preserved in the script that is executed. I think the shell will treat `"dotnet"` the same as `dotnet`.

**Can you please try running this command from within the AWS docker container?** I don't have AWS credentials, but here is what you can try:
- Run the docker container and exec into it with an interactive bash shell: `sudo docker run -it  --entrypoint bash docker.io/amazon/aws-cli:2.2.33`
- Try running your command from within the container: `AWS_ACCESS_KEY_ID=XXXX AWS_SECRET_ACCESS_KEY=YYYY aws codeartifact login --tool "dotnet" --repository dotnet --domain artefatos --region us-east-1`

If you still run into the error "dotnet was not found", I think you will need to make sure dotnet is installed in the container you're running. If you don't, the issue may be with tekton after all.
