### ISSUE TITLE
Tekton admission webhook complains about the when clause in my pipeline

### ISSUE THREAD

**Issue by DrissiReda** [tektoncd/pipeline#4211]
I'm using these versions of tekton

<details>
<summary> tekton images tags </summary>

```
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.23.0
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.23.0
gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard:v0.13.0
gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller:v0.13.0
gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook:v0.13.0
```
</details>

When I try to add this pipeline:

<details>
<summary> pipeline </summary>

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy-conditional-pipeline
  namespace: processing
spec:
  params:
    - default: http://gitea-http.ci:3000/user/sample-app
      description: Git repository url
      name: gitUrl
      type: string
    - default: master
      description: Git revision to check out
      name: gitRevision
      type: string
  tasks:
    - name: clone-repo
      params:
        - name: url
          value: $(params.gitUrl)
        - name: revision
          value: $(params.gitRevision)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
    - name: retrieve-metadata
      runAfter:
      - clone-clone
      taskRef:
        kind: Task
        name: parse-metadata
      workspaces:
      - name: git
        workspace: git-source
    - when:
      - input: $(tasks.retrieve-metadata.results.codeLang)
        operator: in
        values:
        - "golang"
      name: build-code
      params:
        - name: package
          value: ''
        - name: name
          value: $(params.gitUrl)
        - name: image
          value: $(tasks.retrieve-metadata.results.buildImg)
      runAfter:
        - clone-repo
      taskRef:
        kind: Task
        name: golang-build
      workspaces:
        - name: source
          workspace: git-source
```

</details>

When I try to add this to my kubernetes dashboard, I get this error:

```
admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "when" 
```

I'm only going off of [this](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/pipelinerun-with-when-expressions.yaml#L47-L68) link. 

Is there any reason that my when clause isn't working?
