### ISSUE TITLE
/tekton/debug scripts absent after step has failed

### ISSUE THREAD

**Issue by jeffmaury** [tektoncd/pipeline#4224]
# Expected Behavior

Debug scripts should be found under /tekton

# Actual Behavior

No debug sub folder under /tekton
# Steps to Reproduce the Problem

1. Start minikube `minikube start -p tekton`
2. install pipeline: `kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml`
3. activate alpha fields: `kubectl path cm/feature-flags -p "{\"data\":{\"enable-api-fields\":\"alpha\"}}"`
4. create namespace: `kubectl create ns demo`
5. set default ns: `kubens demo`
6. create task from payload:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  steps:
    - name: step1
      image: fedora
      command: 
      - /bin/bash
      args: ['-c', 'echo hello world']
    - name: step2
      image: fedora
      command:
        - /bin/bas
      args: ['-c', 'echo hello world']
    - name: step3
      image: fedora
      command:
        - /bin/bash
      args: ['-c', 'echo hello world']
```
7. create taskrun from payload:
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: echo-run
spec:
  debug:
    breakpoint: [onFailure]
  taskRef:
    kind: Task
    name: echo
  timeout: 1h0m0s
```
8. wait until echor-run-pod-xxx is NotReady
9. run exec `echo-run-pod-f4mln -c step-step2 -- ls /tekton`
# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
 Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
v0.27.3
