### ISSUE TITLE
Documentation for image pull secrets might be wrong or is unclear

### ISSUE THREAD

**Issue by mlieberman85** [tektoncd/pipeline#4225]
I don't know if Tekton does anything behind the scenes with secrets but in the docs it says:

   ```bash
   kubectl create secret generic regcred \
    --from-file=.dockerconfigjson=<path/to/.docker/config.json> \
    --type=kubernetes.io/dockerconfigjson
   ```

   ```yaml
   apiVersion: v1
   kind: ServiceAccount
   metadata:
     name: build-bot
   secrets:
     - name: regcred
   ```

Shouldn't secrets be imagePullSecrets? Before creating a PR, I just wanted to make sure I wasn't missing anything Tekton is doing. As far as I can tell secrets as described above won't work. I see a similar set of docs for docker with basic auth which I think has the same issue.
