### ISSUE TITLE
Restrict step volumes as read-only

### ISSUE THREAD

**Issue by wlynch** [tektoncd/pipeline#4227]
# Expected Behavior

Internal `/tekton` folders should only be manipulated by trusted Tekton components (i.e. controller / entrypoint).

# Actual Behavior

Tekton mounts the following volumes for each step:

```
# Read-write
- mountPath: /tekton/tools
  name: tekton-internal-tools
- mountPath: /tekton/downward
  name: tekton-internal-downward
- mountPath: /tekton/creds
  name: tekton-creds-init-home-0
- mountPath: /workspace
  name: tekton-internal-workspace
- mountPath: /tekton/home
  name: tekton-internal-home
- mountPath: /tekton/results
  name: tekton-internal-results
- mountPath: /tekton/steps
  name: tekton-internal-steps

# Read-only
- mountPath: /tekton/scripts
  name: tekton-internal-scripts
  readOnly: true
- mountPath: /var/run/secrets/kubernetes.io/serviceaccount
  name: kube-api-access-9fk95
  readOnly: true
```

Since many of these directories are mounted read-write and are shared by all steps in the task, these can be manipulated to cause unexpected behavior for steps.

Directory | Description | Consequence | Recommendation
----------|------------|---------------|-------------------
/tekton/tools | Contains entrypoint, post_files for coordinating step starts | Bad step could manipulate it's own entrypoint (requires container restart), or write post_files to prematurely cause steps to start. | Move entrypoint into its own directory <br><br> Only let step write its own post_files
/tekton/steps | [Step exit codes](https://github.com/tektoncd/pipeline/blob/78d6d75473ea00118fa1e07cbf6b8e97439689ad/docs/developers/README.md#how-to-access-the-exit-code-of-a-step-from-any-subsequent-step-in-a-task) | Bad step can mutate the perceived exit code for other steps. This does **not** affect container exit / Task status. | Only let step write its own exit codes.
/tekton/results | [Results](https://github.com/tektoncd/pipeline/blob/edcaa970f62e1031c4f7243ebc827e453ead6cb5/docs/tasks.md#emitting-results) output | None - Results are defined at the Task level. | Nothing - expected behavior
/tekton/downward | [Contains files provided by the k8s Downward API to control Task start once sidecars are up](https://github.com/tektoncd/pipeline/blob/1f5980f8c8a05b106687cfa3e5b3193c213cb66e/cmd/entrypoint/README.md#waiting-for-sidecars) | None - despite the `readOnly` option not being set, the volume appears to be read-only if you attempt to mutate it. | Make the mount readonly, even though it's redundant?
/tekton/creds | Used by [creds-init](https://github.com/tektoncd/pipeline/blob/e76d4132ab2ecfbedc45a964f08a01022e2d4c14/docs/auth.md) to inject credentials for steps | None - we don't guarantee credential isolation in steps, and [recommend manual volume mounts if this is required](https://github.com/tektoncd/pipeline/blob/e76d4132ab2ecfbedc45a964f08a01022e2d4c14/docs/auth.md#limiting-secret-access-to-specific-steps) | Nothing - expected behavior (and [required for the entrypoint to support creds-init](https://github.com/tektoncd/pipeline/blob/288a7485ae2b728f5c0d1b65369b7a705e9db80a/cmd/entrypoint/main.go#L91-L100))
/workspace | Used for [workspaces](https://github.com/tektoncd/pipeline/blob/e76d4132ab2ecfbedc45a964f08a01022e2d4c14/docs/workspaces.md#overview) | None - workspaces are currently mounted Task-wide, and [step-isolated workspaces] | Nothing - expected behavior [step isolated workspaces](https://github.com/tektoncd/pipeline/blob/e76d4132ab2ecfbedc45a964f08a01022e2d4c14/docs/workspaces.md#isolating-workspaces-to-specific-steps-or-sidecars) would be used if users want to restrict this. | 
/tekton/home | [Deprecated Tekton home directory](https://github.com/tektoncd/pipeline/pull/3878) | None | Nothing - expected behavior

# Steps to Reproduce the Problem

### /tekton/tools

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: step-script-
spec:
  taskSpec:
    steps:
    - name: bad
      image: ubuntu
      script: |
        # Create post_files - this can be done for any step 0-n 
        # to cause the next container to start.
        touch /tekton/tools/0
        touch /tekton/tools/0.err
        sleep 10
        echo "done!"
    - image: ubuntu
      script: |
        echo $(context.task.name)
```

### /tekton/steps

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: step-script-
spec:
  taskSpec:
    steps:
    - name: pass
      image: ubuntu
      script: |
        exit 0
    - name: bad
      image: ubuntu
      script: |
        # Re-write 
        for f in `ls /tekton/steps`; do
          f="/tekton/steps/${f}/exitCode"
          echo "1" > ${f}
        done
    - name: echo
      image: ubuntu
      script: |
        # We now think step-pass failed, even though the
        # container status is 0.
        cat $(steps.step-pass.exitCode.path)
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  ```
  Client version: 0.20.0
  Pipeline version: devel (78d6d75473ea00118fa1e07cbf6b8e97439689ad
  ```

This issue is similar in nature to #4160. Credit for discovering this + the ideas for fixes goes to @06kellyjac and the folks at https://github.com/controlplaneio/ !

# Proposal

- [x] Mount `/tekton/downward` as read-only for consistency (even though it's already readonly)
- [x] Move step post_files to a separate directory (name TBD), make `/tekton/tools` readonly. (`/tekton/tools` is [**not** bound](https://github.com/tektoncd/pipeline/blob/78d6d75473ea00118fa1e07cbf6b8e97439689ad/docs/developers/README.md#reserved-directories) by the Tekton deprecation policy.
- [ ] (up for discussion - see below) Introduce sidecar to manage step lifecycle outside the control of step containers?

## Open Questions

An interesting question that popped up from this is how much trust should steps within a Task should have with each other, particularly if the Task is made up of different container images being pulled in from different sources.

On one hand, we typically refer to a Task as the single unit of work for Tekton, similar to a [Pod](https://kubernetes.io/docs/concepts/workloads/pods/#how-pods-manage-multiple-containers). If users require greater isolation guarantees between steps, they could convert each step into a Task within a Pipeline (and with things like #3476 / @bobcatfish's [Pipeline in a Pod proposal](https://github.com/tektoncd/community/blob/main/teps/0044-decouple-task-composition-from-scheduling.md) - the differences between these might be minimal).

On the other hand, because Tasks can be composed of multiple images, it can make it harder to guarantee that each container will not disrupt each other in unexpected ways. Introducing a sidecar that would manage step lifecycles could help this out. High level proposal - The sidecar could rely on step container status to determine whether a step is done, then handle the post_file write (and be the only container with write access) to kick off the next step. The post_files could then be mounted as read-only with steps. This obviously comes with overhead of maintaining the sidecar, which increases the [complexity (and possibly latency)](https://github.com/tektoncd/pipeline/blob/78d6d75473ea00118fa1e07cbf6b8e97439689ad/docs/developers/README.md#handling-of-injected-sidecars) of Tasks.

I'm on the fence here - would love to hear other's thoughts/opinions! If there's interest we can look into drafting a more detailed design, or at the very least we can document expectations/best practices for users who need more isolation.

/cc @bobcatfish - particularly interested in your thoughts here, since I think there's a lot of overlap here with Pipeline-in-a-Pod.
