### ISSUE TITLE
Running script within steps -  is waiting to start: PodInitializing

### ISSUE THREAD

**Issue by JCzz** [tektoncd/pipeline#4241]
## Running script within steps -  is waiting to start: PodInitializing

Tekton:
```
 tkn version                           
Client version: 0.20.0
Pipeline version: v0.27.3

```
Env: Ubuntu server running K8s on arm64, but same result using `arm64v8/alpine` and "alpine" works with just using command(see "**Works if you change to command**" ).

From Tekton documentation "[Running script within steps](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#running-scripts-within-steps)"

And RedHat [tutorial](https://redhat-scholars.github.io/tekton-tutorial/tekton-tutorial/tasks.html#_run_clustertask_echoer)
```
---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: echoer
spec:
  steps:
    - image: alpine
      script: |
        #!/bin/sh
        echo 'Meeow!! from Tekton 😺🚀'
```

Error:
**tkn clustertask start echoer --showlog**
```
TaskRun started: echoer-run-jc9vp
Waiting for logs to be available...
error in getting logs for step unnamed-0: error getting logs for pod echoer-run-jc9vp-pod-p29n9(step-unnamed-0) : container "step-unnamed-0" in pod "echoer-run-jc9vp-pod-p29n9" is waiting to start: PodInitializing
```

## Works if you change to command - therefore it could be a "**script** issue":
```
---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: echoer
spec:
  steps:
    - image: alpine
      command: ["ls"]
```

**tkn clustertask start echoer --showlog**
```
TaskRun started: echoer-run-45jwt
Waiting for logs to be available...
[unnamed-0] bin
[unnamed-0] dev
...

```
