### ISSUE TITLE
Idea: entrypoint resolution of results in task config

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/pipeline#4342]
### Feature request

Allow entrypoint to resolve `$(results.foo)` in the configuration of steps before executing them.

### Use case

Today I have a workflow where I emit a digest to the `IMAGES` result (for Chains), but then want to do things like attach SBOMs to the same digest, so I do:
```yaml
      command: [/busybox/sh, -c]
      args: ["/ko-app/cosign attach sbom --type spdx --sbom /workspace/image.sbom $(cat /tekton/results/IMAGES)"]
```

This is somewhat unpleasant because I need to have a shell in my step container.  It struck me that Tekton is already wrapping things in `entrypoint`, so we could conceivably allow:
```yaml
      args: [
        attach, sbom,
        --type, spdx,
        --sbom, /workspace/image.sbom,
        $(results.IMAGES)         # What if this was read and resolved by `entrypoint`?  🤯 
      ]
```

cc @imjasonh @dlorenc

**Comment by wlynch** [comment]
This is something I expected to work already, so I did some testing and I think this is a bug:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: pr-
spec:
  pipelineSpec:
    tasks:
      - name: a  # Populates result
        taskSpec:
          steps:
            - image: alpine
              script: |
                echo $(results.IMAGES.path)
                echo -n "hello!" > $(results.IMAGES.path)
          results:
            - name: IMAGES
      - name: b  # Read result from script - both from param and task substitution directly
        runAfter: [a]
        params:
          - name: foo
            value: $(tasks.a.results.IMAGES)
        taskSpec:
          params:
            - name: foo
          steps:
            - image: alpine
              script: |
                echo "$(params.foo)"  # Works
                echo "$(tasks.a.results.IMAGES)"  # Doesn't work
      - name: c  # Read task substitution from args
        runAfter: [b]
        taskSpec:
          steps:
            - image: alpine
              command: ["sh"]
              args: ["-c", "echo $(tasks.a.results.IMAGES)"]  # Doesn't work
      - name: d  # Read param substitution from args
        runAfter: [c]
        params:
          - name: foo
            value: $(tasks.a.results.IMAGES)
        taskSpec:
          params:
            - name: foo
          steps:
            - image: alpine
              command: ["sh"]
              args: ["-c", "echo $(params.foo)"]  # Works
```

Output:

```
[a : unnamed-0] /tekton/results/IMAGES
[a : unnamed-0] + echo /tekton/results/IMAGES
[a : unnamed-0] + echo -n 'hello!'

[b : unnamed-0] hello!
[b : unnamed-0] + echo 'hello!'
[b : unnamed-0] + tasks.a.results.IMAGES
[b : unnamed-0] /tekton/scripts/script-0-fc2qv: line 4: tasks.a.results.IMAGES: not found
[b : unnamed-0] + echo
[b : unnamed-0]

[c : unnamed-0] sh: tasks.a.results.IMAGES: not found
[c : unnamed-0]

[d : unnamed-0] hello!
```

@mattmoor If `c` worked would that be sufficient? Or are there other reasons why you would want the resolution to be done in the entrypoint?
