### ISSUE TITLE
resource hoarding for steps of a taskrun

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/pipeline#4347]
Hi, we noticed the following issue after upgrading from v0.26.0 to v0.28.2

# Expected Behavior
When creating a taskrun with multiple steps where the steps have resource requests defined, tekton should not "hoard resources". The created pod should only request the maximum of the step containers and not the sum of all step containers. This is also described in https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#specifying-resources with "The CPU, memory, and ephemeral storage resource requests will be set to zero (also known as BestEffort), or, if specified, the minimums set through LimitRanges in that Namespace, if the container image does not have the largest resource request out of all container images in the Task. This ensures that the Pod that executes the Task only requests enough resources to run a single container image in the Task rather than hoard resources for all container images in the Task at once."

# Actual Behavior
Tekton does hoard resources in 0.28.2

# Steps to Reproduce the Problem

1. Create a TaskRun with multiple steps and resource requests
2. Check the resource requests of the created pod

TaskRun
```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: run-
spec:
  taskSpec:
    steps:
      - name: step-a
        image: alpine
        script: echo "step-a"
        resources:
          requests:
            cpu: 1
      - name: step-b
        image: alpine
        script: echo "step-b"
        resources:
          requests:
            cpu: 1
```

Resulting Pod using Tekton v0.28.2 - unexpected resource hoarding

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: run-w5m78-pod-lnl5t
spec:
  containers:
    - name: step-step-a
      resources:
        requests:
          cpu: "1"
    - name: step-step-b
      resources:
        requests:
          cpu: "1"
```

Resulting Pod using Tekton v0.26.0 - expected behavior, no resource hoarding

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: run-ttnjl-pod-rwj5x
spec:
  containers:
    - name: step-step-a
      resources:
        requests:
          cpu: "1"
          ephemeral-storage: "0"
          memory: "0"
    - name: step-step-b
      resources:
        requests:
          cpu: "0"
          ephemeral-storage: "0"
          memory: "0"
```

# Additional Info
- Kubernetes version: `v1.21.1`
- Tekton Pipeline version: `v0.28.2`
