### ISSUE TITLE
Address is not allowed error occured while creating a task

### ISSUE THREAD

**Issue by GudaboinaSuhas** [tektoncd/pipeline#4365]
# Actual Behavior

```Error from server (InternalError): error when creating "hello.yaml": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=10s": Address is not allowed```

hello.yaml:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: hello
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World!"
```
Installed using the following command:
```kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml```

EKS version: 1.20
CNI(Cilium) version: 1.10.5

# Additional Info

- Kubernetes version: 1.20

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version: v0.27.1

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
