### ISSUE TITLE
Admin / view custom resources with admin/view cluster roles 

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#439]
## Expected Behavior

A service account with admin / view clusterrole, should be able to admin / view build-pipeline custom resources.

## Actual Behavior

```
$ kubectl get all -n health
Error from server (Forbidden): images.caching.internal.knative.dev is forbidden: User "system:serviceaccount:health:health-admin" cannot list images.caching.internal.knative.dev in the namespace "health"
Error from server (Forbidden): tasks.pipeline.knative.dev is forbidden: User "system:serviceaccount:health:health-admin" cannot list tasks.pipeline.knative.dev in the namespace "health"
Error from server (Forbidden): taskruns.pipeline.knative.dev is forbidden: User "system:serviceaccount:health:health-admin" cannot list taskruns.pipeline.knative.dev in the namespace "health"
Error from server (Forbidden): clustertasks.pipeline.knative.dev is forbidden: User "system:serviceaccount:health:health-admin" cannot list clustertasks.pipeline.knative.dev at the cluster scope
Error from server (Forbidden): pipelines.pipeline.knative.dev is forbidden: User "system:serviceaccount:health:health-admin" cannot list pipelines.pipeline.knative.dev in the namespace "health"
Error from server (Forbidden): pipelineruns.pipeline.knative.dev is forbidden: User "system:serviceaccount:health:health-admin" cannot list pipelineruns.pipeline.knative.dev in the namespace "health"
Error from server (Forbidden): pipelineresources.pipeline.knative.dev is forbidden: User "system:serviceaccount:health:health-admin" cannot list pipelineresources.pipeline.knative.dev in the namespace "health"
```

## Steps to Reproduce the Problem

1. Create a service account 
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-admin
  namespace: health
```
2. Create a role binding with the cluster role admin 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: health-admin-user-binding
  namespace: health
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: health-admin
  namespace: health
```

3. kubectl get all

## Additional Info
A clusterrolebinding `build-pipeline-controller-admin` exists, but it's not aggregated to `admin`.
There is no `build-pipeline-controller-view` defined.

**Comment by bobcatfish** [comment]
Looking at the config we use for deploying Pipelines we have:

1. [This service account](https://github.com/knative/build-pipeline/blob/master/config/200-serviceaccount.yaml)

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-pipeline-controller
  namespace: knative-build-pipeline
```

2. [This RoleBinding](https://github.com/knative/build-pipeline/blob/master/config/201-clusterrolebinding.yaml), which refers to service account `build-pipeline-controller` but also ClusterRole `knative-build-pipeline-admin`

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: build-pipeline-controller-admin
subjects:
  - kind: ServiceAccount
    name: build-pipeline-controller
    namespace: knative-build-pipeline
roleRef:
  kind: ClusterRole
  name: knative-build-pipeline-admin
  apiGroup: rbac.authorization.k8s.io
```

3. And then [this ClusterRole](https://github.com/knative/build-pipeline/blob/master/config/200-clusterrole.yaml) gives permission to perforom operations such as listing specific resources:

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-build-pipeline-admin
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "secrets", "events", "serviceaccounts", "configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["pipeline.knative.dev"]
    resources: ["tasks", "clustertasks", "taskruns", "pipelines", "pipelineruns", "pipelineresources"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["build.knative.dev"]
    resources: ["builds", "buildtemplates", "clusterbuildtemplates"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
```

So I think that what is causing your user to not be able to list those resources would be the restrictions of [the `admin` ClusterRole](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles)

> Allows admin access, intended to be granted within a namespace using a RoleBinding. If used in a RoleBinding, allows read/write access to most resources in a namespace, including the ability to create roles and rolebindings within the namespace. It does not allow write access to resource quota or to the namespace itself.

It says "most" resources but doesn't elaborate XD - I'm guessing it doesn't allow access to CRDs by deafult?

**Comment by bobcatfish** [comment]
@afrittoli quick ping, is this still giving you any trouble or should I resolve this issue?

**Comment by afrittoli** [comment]
If I deploy pipelines in a namespaces, and I want to run them via a service account, it's not enough for the service account to be `admin` on the namespace, it will have to have special permissions added to be able to view / run tekton resources.

The way I solved this was to add the following to `tekton-pipeline-admin`:
```
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
```

That makes it to that an `admin` is automatically a pipeline admin as well.
I understand that that may not be the desired default behavior for everyone though, so it's fine if you want to close this. 

An alternative could be to add a some documentation about available roles and how to use them.
