### ISSUE TITLE
Finally task not executed when tasks define "retries"

### ISSUE THREAD

**Issue by khrm** [tektoncd/pipeline#4409]
# Expected Behavior
Final tasks are always executed

# Actual Behavior
In a pipeline with two parallel tasks where both fail and one of them has "retries=2", final tasks are never executed. Pipeline fails later because of timeout.

# Steps to Reproduce the Problem

1. Create Task: 
```

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: noop
spec:
  params:
  - name: RETURN_CODE
    default: "0"
  steps:
    - name: sleep
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |
        #!/usr/bin/env bash
        set -e

        echo "Will sleep for 2 seconds"
        sleep 2

        if [[ $(params.RETURN_CODE) != "0" ]]; then
          echo "Failure"
        else
          echo "Success"
        fi

        exit $(params.RETURN_CODE)
```

2. Create Pipeline

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-finally
spec:
  tasks:
  - name: test1
    taskRef:
      name: noop
    params:
      - name: RETURN_CODE
        value: "1"
    retries: 2
  - name: test2
    taskRef:
      name: noop
    params:
      - name: RETURN_CODE
        value: "1"
    # retries: 2
  finally:
    - name: cleanup
      taskRef:
        name: noop
```

3. Create pipelinerun

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-finally-
spec:
  pipelineRef:
    name: test-finally
  timeout: 2m

```

# Additional Info
This pipeline works as expected when any of following changes

1. Task test2 succeeds
2. Both task1 and task2 have retries=2 (or any number)
3. Task test1 has retries=1, retries=0 or retries is omitted
