### ISSUE TITLE
Accessing kubernetes secret for building a container

### ISSUE THREAD

**Issue by v1nc3nt27** [tektoncd/pipeline#4425]
Hello,

I'm trying to pass secrets `GITHUB_TOKEN`and `GITHUB_USER` to the container building step within a task. I checked that the launched container has the two environment variables correctly set. In the building process however, if I print out the variables within the dockerfile via `RUN echo $GITHUB_TOKEN`, the actual value of the envrionment variable is also `$GITHUB_TOKEN`, i.e. it is only set as a string and I don't understand why. The `Task`is defined as follows:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
  namespace: tekton-pipelines
spec:
  params:
    - name: contextDir
    - name: GITHUB_FULL_CREDS
    - name: varlibcPath
  steps:
    - name: build-image
      image: quay.io/buildah/stable:v1.11.6
      workingDir: "/workspace/output/$(inputs.params.contextDir)"
      command:
        - "buildah"
      args:
        - "bud"
        - "--layers"
        - "--build-arg"
        - "GITHUB_TOKEN=$GITHUB_TOKEN"
        - "--build-arg"
        - "GITHUB_USER=$GITHUB_USER"
        - "-f"
        - "$(inputs.params.dockerFile)"
        - "-t"
        - "$(inputs.params.destinationImage)"
        - "."
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - name: varlibc
          mountPath: "$(params.varlibcPath)"
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.GITHUB_FULL_CREDS)
              key: github_token
        - name: GITHUB_USER
          valueFrom:
            secretKeyRef:
              name: $(params.GITHUB_FULL_CREDS)
              key: github_user
```

I cannot set the variable via `GITHUB_USER=${GITHUB_USER}` as Terraform will then complain about not knowing the variable. Not sure if this would help, though. Can anyone see what I'm doing wrong and is there any other way to get the environment variable into the building process? Is there perhaps another way to access the secret within the `args`? Thanks a lot!
