### ISSUE TITLE
CSI volumes as workspaces

### ISSUE THREAD

**Issue by emenaceb** [tektoncd/pipeline#4446]
### Feature request

Support kubernetes CSI volumes (https://kubernetes.io/docs/concepts/storage/volumes/#csi) as workspaces

### Use case

My main motivation is to be able to use Secrets Store CSI Driver (https://secrets-store-csi-driver.sigs.k8s.io/introduction.html)
to use Hashicorp Vault (or any other secret provider) . 

I want to be able to define a workspace in the following way:

 ```
spec:
  workspaces:
    - name: my-credentials
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "vault-database"
```

Of course, there are other ways to mount secrets into the task's pods, but this way we can define tasks in a standard way (using workspaces) and select later the source of those workspaces.
