### ISSUE TITLE
Windows container image missing from entrypoint manifest

### ISSUE THREAD

**Issue by aiden-deloryn** [tektoncd/pipeline#4457]
# Expected Behavior
The manifest for the entrypoint should include a Windows image, such as in the 0.30.0 release: [0.30.0 manifest](https://console.cloud.google.com/gcr/images/tekton-releases/global/github.com%2Ftektoncd%2Fpipeline%2Fcmd%2Fentrypoint@sha256:34ee7658bb8a657584e1ada8e84121758cc5d067c1f0740873d614d07423886f/details?tab=pull)

This is required for Tekton to run Windows workloads.

# Actual Behavior
The manifest for the 0.31.0 release does not include a Windows image: [0.31.0 manifest](https://console.cloud.google.com/gcr/images/tekton-releases/global/github.com%2Ftektoncd%2Fpipeline%2Fcmd%2Fentrypoint@sha256:97139f59df7c6e2b3d22e75191be653f4202143859d3937e2bafa7a8a7a44822/details?tab=pull)

Windows workloads fail to pull the entrypoint image when using 0.31.0.

# Steps to Reproduce the Problem

This affects all [Windows tasks](https://github.com/tektoncd/pipeline/blob/main/docs/windows.md).

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-17T02:23:27Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.20.0
Pipeline version: v0.31.0
```

**Comment by sbwsg** [comment]
It doesn't look like windows image releases are accounted for in our release pipeline? Looking in dashboard the `Pipeline` we use doesn't include `windows/arm64` in the default platform string:

https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelines/pipeline-release?view=yaml

```yaml
    - default: 'linux/amd64,linux/arm,linux/arm64,linux/s390x,linux/ppc64le'
      description: 'Platforms to publish for the images (e.g. linux/amd64,linux/arm64)'
      name: platforms
      type: string
``` 

Nor does the release cheatsheet we use include us overriding that param with a different platform string: https://github.com/tektoncd/pipeline/blob/main/tekton/release-cheat-sheet.md#tekton-pipelines-official-release-cheat-sheet
(Step 7 in ^ doesn't mention an extra `--param=platforms=`).

So I guess my question is: how did we release windows images for 0.30 in the first place?

**Comment by sbwsg** [comment]
Addendum to my previous comment: we seem to publish windows images via the `publish-release` Task. https://dashboard.dogfooding.tekton.dev/#/namespaces/default/tasks/publish-release?view=yaml

This does include the following:

```yaml
    - default: 'linux/amd64,linux/arm,linux/arm64,linux/s390x,linux/ppc64le,windows/amd64'
      description: 'Platforms to publish for the images (e.g. linux/amd64,linux/arm64)'
      name: platforms
      type: string
```
