### ISSUE TITLE
Strange behavior of inputs.params variables

### ISSUE THREAD

**Issue by ARogovsky** [tektoncd/pipeline#4490]
# Expected Behavior

`" ./Dockerfile url:latest ./`

# Actual Behavior
`./Dockerfile ${params.imageUrl}:${params.imageTag} ${params.pathToContext}`

# Steps to Reproduce the Problem

Execute sample task:

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: source-to-image
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: pathToContext
        description: The path to the build context, used by Kaniko - within the workspace
        default: "./"
      - name: pathToDockerFile
        description: The path to the dockerfile to build (relative to the context)
        default: "./Dockerfile"
      - name: imageUrl
        description: Url of image repository
        default: "url"
      - name: imageTag
        description: Tag to apply to the built image
        default: "latest"
  steps:
    - name: echovar
      image: ubuntu
      command:
        - /bin/echo
      args:
        - "$(inputs.params.pathToDockerFile) $(inputs.params.imageUrl):$(inputs.params.imageTag) $(inputs.params.pathToContext)"

```

# Additional Info

- Kubernetes version:

  ```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

  ```

- Tekton Pipeline version:

`v0.31.0`

**Comment by sbwsg** [comment]
Thanks for the issue report.  I wasn't able to reproduce on v0.31.0 using the TaskRun you supplied. Here's the complete test yaml I used:

```yaml
piVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: source-to-image
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: pathToContext
        description: The path to the build context, used by Kaniko - within the workspace
        default: "./"
      - name: pathToDockerFile
        description: The path to the dockerfile to build (relative to the context)
        default: "./Dockerfile"
      - name: imageUrl
        description: Url of image repository
        default: "url"
      - name: imageTag
        description: Tag to apply to the built image
        default: "latest"
  steps:
    - name: echovar
      image: ubuntu
      command:
        - /bin/echo
      args:
        - "$(inputs.params.pathToDockerFile) $(inputs.params.imageUrl):$(inputs.params.imageTag) $(inputs.params.pathToContext)"
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: foo
spec:
  params:
  - name: url
    value: github.com/sbwsg/results
  - name: revision
    value: main
  type: git
---
kind: TaskRun
apiVersion: tekton.dev/v1alpha1
metadata:
  name: run-source-to-image
spec:
  taskRef:
    name: source-to-image
  inputs:
    resources:
    - name: git-source
      resourceRef:
        name: foo
```

A Pod gets created with the following container entry:

```yaml
  - args:
    - -wait_file
    - /tekton/run/0/out
    - -post_file
    - /tekton/run/1/out
    - -termination_path
    - /tekton/termination
    - -step_metadata_dir
    - /tekton/steps/step-echovar
    - -step_metadata_dir_link
    - /tekton/steps/1
    - -entrypoint
    - /bin/echo
    - --
    - ./Dockerfile url:latest ./
    command:
    - /tekton/bin/entrypoint
```

So here at least the params do seem to be injected correctly to the container definition.

How does the Pod look on your side after running the test yaml I pasted above?
