### ISSUE TITLE
TaskRun script error messages include Tekton-generated script name

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#4510]
# Expected Behavior

TaskRun logs should be understandable to users without knowledge of Tekton's implementation.

# Actual Behavior

TaskRun script errors include the auto-generated name of the script in /tekton/scripts, for example:
`[echo] /tekton/scripts/script-0-ddzfg: line 3: syntax error: unexpected ")"`

We should take out the `/tekton/scripts/script-0-ddzfg` part of the error message and just replace with `script error in step foo:` or similar.

# Steps to Reproduce the Problem

example Task:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: script-err-task
spec:
  steps:
  - image: alpine
    name: echo
    script: |
      this is broken
```

Taskrun logs: `[echo] /tekton/scripts/script-0-tc62d: line 3: this: not found`

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1302", GitCommit:"639f3a74abf258418493e9b75f2f98a08da29733", GitTreeState:"clean", BuildDate:"2021-10-21T21:35:48Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
Client version: 0.21.0
Pipeline version: devel
Triggers version: v0.17.1
```
