### ISSUE TITLE
context.pipelineRun.namespace not working

### ISSUE THREAD

**Issue by tmds** [tektoncd/pipeline#4540]
My OpenShift 4.8 cluster doesn't support the latest version of .NET (.NET 6).

I've imported the [s2i-dotnetcore image streams](https://github.com/redhat-developer/s2i-dotnetcore/blob/master/dotnet_imagestreams.json) into my namespace.

I'm trying to patch the https://github.com/openshift/pipelines-catalog/blob/master/task/s2i-dotnet/0.1/s2i-dotnet.yaml Task so it will use the `dotnet` images from the namespace.
To do that, I've replaced `'image-registry.openshift-image-registry.svc:5000/openshift/dotnet:$(params.VERSION)'` with `'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/dotnet:$(params.VERSION)'`.

It seems like the version gets substituted, but the namespace does not:

```
error: Failed to parse docker reference image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/dotnet:6.0
```

cc @vdemeester

**Comment by tmds** [comment]
@vdemeester can you give an update?

**Comment by vdemeester** [comment]
@tmds sorry 😅 
You replaced it at [this line](https://github.com/openshift/pipelines-catalog/blob/master/task/s2i-dotnet/0.1/s2i-dotnet.yaml#L45) right ?

**Comment by vdemeester** [comment]
Looking into the version shipped in OCP, I think 4.8 should already have the `context.pipelineRun.namespace` which is super weird.

**Comment by tmds** [comment]
> @tmds sorry sweat_smile
You replaced it at [this line](https://github.com/openshift/pipelines-catalog/blob/master/task/s2i-dotnet/0.1/s2i-dotnet.yaml#L45) right ?

Yes, that location. And from the error message it seems the version did get substituted, but the namespace did not.

**Comment by jerop** [comment]
@tmds could you try to pass in `PipelineRun` context variables through `Parameters` to reach the `Task`? Only the `Task` and `TaskRun` context variables are directly accessible in the `Task` specification - please let us know if this doesn't work

see this example: https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/using_context_variables.yaml

**Comment by KyWa** [comment]
Adding to this as I just came across the same issue. Can confirm in the tech-preview of OCP 4.6 it does not work either (the variable sub for context.pipelineRun.namespace). I'd settle for the ability to get the namespace similar to how metadata is normally obtained for a Pod to consume. Just chiming in there are others experiencing this.

**Comment by jerop** [comment]
@tmds @KyWa - could you please share an example where you see this happening? 

Tested with a modified version of the [context variables example](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/using_context_variables.yaml):

```yaml
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: test-pipelinerun-
spec:
  serviceAccountName: 'default'
  pipelineSpec:
    tasks:
    - name: task1
      retries: 7
      params:
      - name: pipeline-uid
        value: "$(context.pipelineRun.uid)"
      - name: pipeline-name
        value: "$(context.pipeline.name)"
      - name: pipelineRun-name
        value: "$(context.pipelineRun.name)"
      - name: pipelineRun-namespace
        value: "$(context.pipelineRun.namespace)"
      - name: pipelineTask-retries
        value: "$(context.pipelineTask.retries)"
      taskSpec:
        params:
        - name: pipeline-uid
        - name: pipeline-name
        - name: pipelineRun-name
        - name: pipelineRun-namespace
        - name: pipelineTask-retries
        steps:
        - image: ubuntu
          name: print-uid
          script: |
            echo "TaskRun UID: $(context.taskRun.uid)"
            echo "PipelineRun UID from params: $(params.pipeline-uid)"
        - image: ubuntu
          name: print-names
          script: |
            echo "Task name: $(context.task.name)"
            echo "TaskRun name: $(context.taskRun.name)"
            echo "Pipeline name from params: $(params.pipeline-name)"
            echo "PipelineRun name from params: $(params.pipelineRun-name)"
            echo "PipelineRun namespace from params: $(params.pipelineRun-namespace)"
        - image: ubuntu
          name: print-retries
          script: |
            echo "PipelineTask retries from params: $(params.pipelineTask-retries)"
            echo "PipelineTask current retry count: $(context.task.retry-count)"
```

And this was the result, where `context.pipelineRun.namespace` is substituted with "default" as expected:

```shell
$ kubectl create -f examples/v1beta1/pipelineruns/using_context_variables.yaml
pipelinerun.tekton.dev/test-pipelinerun-pz8dz created

$ tkn pipelinerun logs test-pipelinerun-pz8dz -f -n default 
[task1 : print-uid] TaskRun UID: fe5a4a59-e7d8-4f30-a19b-181a376bd947
[task1 : print-uid] PipelineRun UID from params: 0a63b376-e1a4-4f65-bb58-ab2d03e2c584

[task1 : print-names] Task name: test-pipelinerun-pz8dz-task1
[task1 : print-names] TaskRun name: test-pipelinerun-pz8dz-task1
[task1 : print-names] Pipeline name from params: test-pipelinerun-pz8dz
[task1 : print-names] PipelineRun name from params: test-pipelinerun-pz8dz
[task1 : print-names] PipelineRun namespace from params: default

[task1 : print-retries] PipelineTask retries from params: 7
[task1 : print-retries] PipelineTask current retry count: 0
```

Will update the example to include the namespace too, but please share your example if it still doesn't work
