### ISSUE TITLE
Pipelines don't respect mixed Task API versions

### ISSUE THREAD

**Issue by wlynch** [tektoncd/pipeline#4543]
So a weird quirk of the Pipelines API is that it's valid to create a request like:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-
spec:
  pipelineSpec:
    tasks:
      - name: a
        taskSpec:
          apiVersion: tekton.dev/v1alpha1
          steps:
            - image: alpine
              script: |
                echo "hi!"
      - name: b
        taskSpec:
          steps:
            - image: alpine
              script: |
                echo "hello!"
```

# Expected Behavior

I'm not sure what the behavior should be. I see 2 options:

1. Respect the TypeMeta field and create resources corresponding to the type (e.g. allow a v1beta1 Pipeline to create a v1alpha1 Task) - this might be useful to allow for users to use experimental Tasks within a Pipeline.
2. Enforce that v1beta1 Pipelines must use v1beta1 Tasks. 

# Actual Behavior

The request is accepted, the TypeMeta field is ignored, v1beta1 Tasks are always used. (didn't check what the behavior is for TaskRefs).

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
    Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

Client version: 0.15.0
Pipeline version: v0.32.0
