### ISSUE TITLE
Tekton is unable to execute a linux/arm64 container. Looking for linux/arm64/v8

### ISSUE THREAD

**Issue by vaikas** [tektoncd/pipeline#4548]
# Expected Behavior
Task to run successfully if it's linux/arm64 container

# Actual Behavior
Task fails because it looks for linux/arm64/v8 container

# Steps to Reproduce the Problem

1.  Create a task
2. Create a taskrun
3. Observe the taskrun fails

Here's the small repro with a publicly available image. If you just want to YOLO:

```
kubectl apply -f - <<EOF
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: repro
spec:
  steps:
  - name: repro
    image: gcr.io/projectsigstore/cosign:v1.5.1
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: repro
spec:
  taskRef:
    name: repro
EOF
```

This will fail after a few seconds with the following in the logs:
```
vaikas@villes-mbp build-playground % kubectl -n default logs repro-pod -c step-repro
2022/02/04 23:18:21 could not find command for platform "linux/arm64/v8"
```

Broken out:
Task:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: repro
spec:
  steps:
  - name: repro
    image: gcr.io/projectsigstore/cosign:v1.5.1
```

Taskrun:
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: repro
spec:
  taskRef:
    name: repro
```

So, even though the image is built for linux/arm64 for some reason it's looking for the additional /v8 in the end
```
vaikas@villes-mbp build-playground % crane manifest gcr.io/projectsigstore/cosign:v1.5.1 | jq .
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "manifests": [
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 1079,
      "digest": "sha256:e3f258567876a3e5932eb9bfc501e8a94ac9aaa769b6691061ae9ecd46568b6b",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 1079,
      "digest": "sha256:e7204ed4bc7ef66202fdf9e0a3a3d072395c3f10a23872802f3a164db5ab87fe",
      "platform": {
        "architecture": "arm",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 1079,
      "digest": "sha256:27704b8ef493680464860c7d8a15bbbaa08f39b6ced2ab05f3669cab9919d603",
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 1079,
      "digest": "sha256:cba07e8398c081e5e2ecc2a60f84623ca9f0562ada1e19d15d0e18992de5fcbc",
      "platform": {
        "architecture": "ppc64le",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 1079,
      "digest": "sha256:86307c9c886467263ede1c59b04f7bc34d0a6b6cb25263c921213c7949a537be",
      "platform": {
        "architecture": "s390x",
        "os": "linux"
      }
    }
  ]
}
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-dispatcher", GitCommit:"2a8027f41d28b788b001389f3091c245cd0a9a60", GitTreeState:"clean", BuildDate:"2022-01-21T20:32:40Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:06:30Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}  ```

- Tekton Pipeline version:
```
vaikas@villes-mbp build-playground % tkn version
Client version: 0.21.0
Pipeline version: v0.32.1
```
