### ISSUE TITLE
Failed to create task: '...translating TaskSpec to Pod:  duplicate image found for platform'

### ISSUE THREAD

**Issue by vaikas** [tektoncd/pipeline#4566]
# Expected Behavior
Task to run, but it fails. **NOTE** Not sure if this is a problem with the image being run (in which case I'd be happy to chase that fix), or me doing something wrong, or just a bug here.

Trying to run this task/taskrun:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: repro
spec:
  steps:
  - name: repro
    image: anchore/syft:v0.37.10
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: repro
spec:
  taskRef:
    name: repro
```

# Actual Behavior
Taskrun fails with:

```
status:
  completionTime: "2022-02-11T02:41:33Z"
  conditions:
  - lastTransitionTime: "2022-02-11T02:41:33Z"
    message: 'failed to create task run pod "repro": translating TaskSpec to Pod:
      duplicate image found for platform: linux/amd64. Maybe missing or invalid Task
      default/repro'
    reason: CouldntGetTask
    status: "False"
    type: Succeeded
```

# Steps to Reproduce the Problem

1. Create a task / taskrun like so:
```
kubectl apply -f - <<EOF
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: repro
spec:
  steps:
  - name: repro
    image: anchore/syft:v0.37.10
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: repro
spec:
  taskRef:
    name: repro
EOF
```

2. Wait a few seconds
3. Taskrun fails

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-dispatcher", GitCommit:"2a8027f41d28b788b001389f3091c245cd0a9a60", GitTreeState:"clean", BuildDate:"2022-01-21T20:32:40Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:06:30Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}  ```

- Tekton Pipeline version:

```
Client version: 0.22.0
Pipeline version: v20220210-2b3a0dbcab
Dashboard version: v0.24.1
```

<!-- Any other additional information -->
Tekton deployed is from nightly.
