### ISSUE TITLE
TestHermeticTaskRun is flakey

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#4567]
# Expected Behavior

`TestHermeticTaskRun` should only fail due to actual bugs

# Actual Behavior

`TestHermeticTaskRun` flaked in:
- https://github.com/tektoncd/pipeline/pull/4541#issuecomment-1027998805 and passed on rerun
- https://github.com/tektoncd/pipeline/pull/4564 - https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/4564/pull-tekton-pipeline-alpha-integration-tests/1492134427130597378/

```
Error waiting for TaskRun not-hermetic-run-as-root to finish: "not-hermetic-run-as-root" failed
Error executing command: fork/exec /tekton/scripts/script-0-wrvhk: permission denied
```

**Comment by bobcatfish** [comment]
Some more context, It looks like for https://github.com/tektoncd/pipeline/pull/4541 it failed 3 times in a row:

https://tekton-releases.appspot.com/builds/tekton-prow/pr-logs/pull/tektoncd_pipeline/4541/pull-tekton-pipeline-alpha-integration-tests/

![image](https://user-images.githubusercontent.com/432502/154344556-3ca0f4dc-c1ac-4e1d-b2d3-82a03887de89.png)

* https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/4541/pull-tekton-pipeline-alpha-integration-tests/1488883003433160704/
* https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/4541/pull-tekton-pipeline-alpha-integration-tests/1488840473651974144/
* https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/4541/pull-tekton-pipeline-alpha-integration-tests/1488819711146725378/

I think `Error executing command: fork/exec /tekton/scripts/script-0-wrvhk: permission denied` might be a red herring - I think that might actually be from a previous run with hermetic mode on (makes me wonder if the expected failure in hermetic mode is happening for the right reason - maybe script mode doesnt work with hermetic mode? but that's another story!)

It seems like the failing taskrun is timing out:

```
          podName: not-hermetic-run-as-root-pod
          startTime: "2022-02-02T10:36:41Z"
          steps:
          - container: step-access-network
            imageID: docker-pullable://ubuntu@sha256:669e010b58baf5beb2836b253c1fd5768333f0d1dbcb834f7c07a4dc93f474be
            name: access-network
            terminated:
              exitCode: 1
              finishedAt: "2022-02-02T10:37:41Z"
              reason: TaskRunTimeout
              startedAt: "2022-02-02T10:36:46Z"
```

And then I _think_ we're not getting any logs b/c iirc when a TaskRun times out we have to stop the pod from executing, and I think that might involved deleting the underlying pod?? I'm getting rusty though so I'm not sure XD but if so that might explain why we aren't seeing any logs for the taskrun that is timing out:

```
    build_logs.go:35: Could not get logs for pod not-hermetic-run-as-root-pod: pods "not-hermetic-run-as-root-pod" not found
```

Looking at the test that is failing, I'm wondering if it might be that the `apt-get` commands sometimes take more than a minute 🤔 

https://github.com/tektoncd/pipeline/blob/38b9f26af4d04491ef3ea2ec42bf000e56a554bd/test/hermetic_taskrun_test.go#L101-L102
