### ISSUE TITLE
place-scripts not compatible with "runAsNonRoot" SCC on OpenShift

### ISSUE THREAD

**Issue by mtcolman** [tektoncd/pipeline#4593]
Hi, I'm running OpenShift Pipelines 1.4.1 on OpenShift 4.7.40 and have created a single task pipeline that I need to run as non-root. I've created the following SCC:
```
kind: SecurityContextConstraints
apiVersion: "security.openshift.io/v1"
metadata:
  name: scc-buildah
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
- SETUID
- SETGID
defaultAddCapabilities: null
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
```

I've then associated my service account with it, via `oc adm policy add-scc-to-user scc-buildah -z buildah-sa` and specified this service account for the task:
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
...
...
  serviceAccountName: "pipelinerunner"
  serviceAccountNames:
    - taskName: source-to-image-buildah
      serviceAccountName: "buildah-sa"
```

However when I try and run the task, I get an error in OpenShift:
```
Warning  Failed 7s (x9 over 88s)  kubelet  Error: container has runAsNonRoot and image will run as root 
(pod: "example-pipeline-test-buildah-e0mfmc-source-to-image-buil-ql2t9_tekton-pipelines(df3e9f55-b422-49b1-9605-bba384530bec)", container: place-scripts)
```

I've subsequently changed the SCC to be `RunAsUser: RunAsAny` and then it all runs fine.

The place-scripts image is: `registry.access.redhat.com/ubi8/ubi-minimal@sha256:fdfb0770bff33e0f97d78583efd68b546a19d0a4b0ac23eef25ef261bca3e975`.

Just wondering why this has to run as root which then adversely impacts the security I can apply to my task itself? Thanks!

(Tagging @vdemeester and @chmouel as I can see you might have knowledge of this area given: https://github.com/openshift/tektoncd-pipeline/pull/149/files and https://github.com/openshift/tektoncd-pipeline/pull/120/files)
