### ISSUE TITLE
Maven ConfigMap maven-settings not read correctly by tkn pipeline

### ISSUE THREAD

**Issue by ezYakaEagle442** [tektoncd/pipeline#4604]
# Expected Behavior

From the Pipeline, the Maven build should run successfully
  ```
  - name: maven-build
    taskRef:
      name: maven
      kind: ClusterTask
    params:
    - name: GOALS # https://hub.tekton.dev/tekton/task/maven
      value:
        # - -DskipTests
        - clean
        - package
        - Dmaven.repo.local=$(workspaces.local-maven-repo.path)
    workspaces:
    - name: source
      workspace: shared-workspace
    #- name: maven-repo
    #  workspace: local-maven-repo
    - name: maven-settings
      workspace: maven-settings      
    runAfter:
    - fetch-repository
  ```

# Actual Behavior

Maven build fails as if it was not able to get the  settings.xml key

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings>
      <mirrors>
        <mirror>
          <id>maven.org</id>
          <name>Default mirror</name>
          <url>http://repo1.maven.org/maven2</url>
          <mirrorOf>central</mirrorOf>
        </mirror>
      </mirrors>
    </settings>
```

# Steps to Reproduce the Problem
repro steps at [my repo](https://github.com/ezYakaEagle442/aro-java-petclinic-mic-srv/blob/master/cicd/tkn/setup_aro_pipelines.md)
1. 
```
oc create -f ./cnf/apply_manifest_task.yaml
oc create -f ./cnf/update_deployment_task.yaml
oc create -f ./cnf/persistent_volume_claim.yaml
oc create -f ./cnf/storageclass-azurefile.yaml
oc create cm maven-settings --from-file=./cnf/maven_config_map.yaml
oc apply -f  ./cnf/pipeline.yaml
```
2.
 ```
tkn pipeline start build-and-deploy \
    -w name=shared-workspace,volumeClaimTemplateFile=./cnf/persistent_volume_claim.yaml \
    -w name=maven-settings,config=maven-settings \ # how to set the ConfigMap Key settings.xml ??
    -p deployment-name=admin-server \
    -p git-url=https://github.com/ezYakaEagle442/aro-java-petclinic-mic-srv \
    -p git-revision=master \
    -p DOCKERFILE=docker/petclinic-admin-server/Dockerfile \
    -p CONTEXT=/ \
    -p IMAGE=image-registry.openshift-image-registry.svc:5000/$projectname/admin-server
    -p FORMAT=oci \
    -p subdirectory=spring-petclinic-admin-server
```
3.
  ```console
STEP-MVN-SETTINGS

/tekton/scripts/script-0-sggjr: line 6: /workspace/maven-settings/settings.xml: Read-only file system
STEP-MVN-GOALS

[ERROR] Error executing Maven.
[ERROR] The specified user settings file does not exist: /workspace/maven-settings/settings.xml
  ```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```console
Client Version: 4.8.0-202110262219.p0.git.88e7eba.assembly.stream-88e7eba
Server Version: 4.8.18
Kubernetes Version: v1.21.1+6438632
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```console
Client version: 0.22.0
Pipeline version: v0.24.3
Triggers version: v0.14.2
```
