### ISSUE TITLE
Is it possible to run a Tekton without internet access?

### ISSUE THREAD

**Issue by 41lx** [tektoncd/pipeline#4629]
Hi,

we are trying to run Tekton v0.32.1 on our 1.20 (k8s 1.21+ is not available for us thus no 0.33.1) on our local cluster which has no internet access. We are actually facing a lot of problems and failing to do so.

Problems:
* pipelines 0.32.1:
** after editing release.yaml file to point to our local harbor we are able to run tekton-pipelines-controller and tekton-triggers-controller. After creating a simple step and task(https://camel.apache.org/camel-k/next/tutorials/tekton/tekton.html) we are facing the issue: 

```
completionTime: '2022-02-26T22:52:44Z'
conditions:
  - lastTransitionTime: '2022-02-26T22:52:44Z'
    message: 'failed to create task run pod "camel-k-pipeline-run-1-run-integration": Internal error occurred: failed calling webhook "proxy.operator.tekton.dev": Post "https://tekton-operator-proxy-webhook.tekton-pipelines.svc:443/defaulting?timeout=10s": service "tekton-operator-proxy-webhook" not found. Maybe missing or invalid Task tekton-pipelines/camel-k-run-integration'
    reason: CouldntGetTask
    status: 'False'
    type: Succeeded
podName: ''
startTime: '2022-02-26T22:52:44Z'
taskSpec:
  params:
    - description: The integration file to run
      name: file
      type: string
  resources:
    inputs:
      - name: repository
        type: git
  steps:
    - args:
        - run
        - '--wait'
        - $(inputs.params.file)
      command:
        - kamel
      image: 'harbor/apache/camel-k:1.8.0'
      name: run-integration
      resources: {}
      workingDir: /workspace/repository
```
Mentioned service 'tekton-operator-proxy-webhook' is not present in cluster.

* operator 0.54.0:
** operator is downloaded from local harbor and successfully deployed into tekton-operator namespace which creates tekton-pipelines namespace and its spawning tekton pods but these are trying to reach gcr.io hub. That is a problem because there is no internet access. Is there any way how to change this particular behavior ?

Thanks for any explanation and tips! :)
