### ISSUE TITLE
Unwanted annotation propagation from Pipeline to PipelineRun

### ISSUE THREAD

**Issue by jimmyjones2** [tektoncd/pipeline#4636]
# Expected Behavior

Annotations are not propagated from Pipeline to PipelineRun, duplicated ones are not overridden, or at least have a list of keys to not propagate (eg. `argocd.argoproj.io/tracking-id`). This is particularly an issue with ArgoCD - if it is used to sync Pipelines and PipelineRuns (eg. as an post sync hook) the `argocd.argoproj.io/tracking-id` annotation will be incorrect, confusing ArgoCD. Slightly related to #3202

# Actual Behavior

Annotations from Pipeline are propagated onto PipelineRun (overriding any duplicated). This behaviour is [documented for labels](https://tekton.dev/docs/pipelines/labels/), but not annotations.

# Steps to Reproduce the Problem

1. Download https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml
2. Add annotation to PipelineRun:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: write-and-cleanup-workspace
  annotations:
    foo: abc
...
```
4. Add annotation with same key but different value to Pipeline:
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-cleanup-workspace
  annotations:
    foo: bar
...
```
5. `kubectl apply -f pipelinerun-with-final-tasks.yaml`
6. `kubectl get pipelinerun write-and-cleanup-workspace -oyaml`
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    foo: bar
...
```
Note: Pipelines admission controller has changed the annotation on the PipelineRun from `foo: abc` to `foo: bar`.

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"archive", BuildDate:"2021-07-22T00:00:00Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
v0.32.1
```
