### ISSUE TITLE
Task running cpu is limited

### ISSUE THREAD

**Issue by linmuqin** [tektoncd/pipeline#4648]
I define the following resource limits in the task:
```
resources:
       requests:
         memory: "500Mi"
         cpu: "1500m"
       limits:
         memory: "600Mi"
         cpu: "2000m"
```

But the pod is only using 0.5cpu, resulting in slow cicd builds. I manually started a similar pod to run the build task, and it used 1 cpu. Why does the pod created with TriggerTemplate only use 0.5, even if I set resources in the task, it doesn't work. I feel like I'm being restricted somewhere.
