### ISSUE TITLE
Not possible to define `stepOverrides` in a `PipelineRun` element `taskRunSpecs`

### ISSUE THREAD

**Issue by mrbq** [tektoncd/pipeline#4653]
# Expected Behavior

When in a PipelineRun, it should be possible to add the `stepOverrides` and `sidecarOverrides` element to the `taskRunSpec`

# Actual Behavior
It is not possible to define the object `stepOverrides` 

# Steps to Reproduce the Problem

Create the following yaml:

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: my-pipeline
spec:
  pipelineRef:
    name: my-pipeline
  taskRunSpecs:
  - pipelineTaskName: my-task-to-override
    stepOverrides:
    - name: build
      resources:
        requests:
          memory: 1Gi
  resources:
  - name: repository
    resourceRef:
      name: anything
  - name: image
    resourceRef:
      name: test
  serviceAccountName: pipeline
  workspaces:
  - name: my-builds
    persistentVolumeClaim:
      claimName: my-pvc
```

Object cannot be created:

```
 cannot decode incoming new object: json: unknown field "StepOverrides"
```

In the doc it is stated that this change should be possible:

```
If used with this `Pipeline`,  `build-task` will use the task specific `PodTemplate` (where `nodeSelector` has `disktype` equal to `ssd`).
`PipelineTaskRunSpec` may also contain `StepOverrides` and `SidecarOverrides`; see
[Overriding `Task` `Steps` and `Sidecars`](./taskruns.md#overriding-task-steps-and-sidecars) for more information.
```

However, I do not see the element defined in the type:

```
// PipelineTaskRunSpec holds task specific specs
type PipelineTaskRunSpec struct {
	PipelineTaskName       string       `json:"pipelineTaskName,omitempty"`
	TaskServiceAccountName string       `json:"taskServiceAccountName,omitempty"`
	TaskPodTemplate        *PodTemplate `json:"taskPodTemplate,omitempty"`
}
```
