### ISSUE TITLE
Tasks workDir as Dockerfiles WorkDir

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#4655]
I created a task and taskrun that runs a container. Container runs a build artifact from  a work directory named app. 

My task is like following,

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: step-runner
  namespace: tekton
spec:
  steps:
  - name: intermediary
    image: myimage
    workingDir: /app
```
Problem is, the value of ```workingDir``` attribute is not in my hand always. Is there any way to initialize it with dockerfiles ```WORKDIR ```

My Dockerfile is like following 

```Dockerfile
....
....
WORKDIR /app
COPY --from=builder /app/bin /app
EXPOSE 8080
# Run the executable
CMD ["./test-app"]
```
