### ISSUE TITLE
How to add tolerance to pods

### ISSUE THREAD

**Issue by linmuqin** [tektoncd/pipeline#4664]
Hello,
I want to add tolerance to the pod started by pipelinerun, but it doesn't take effect no matter what the configuration is.

[1.txt](https://github.com/tektoncd/pipeline/files/8228467/1.txt)
```
apiVersion: triggers.tekton.dev/v1beta1  
kind: TriggerTemplate
metadata:
  name: gitlab-echo-template
spec:
  params:  
  - name: gitrevision
  - name: gitrepositoryurl

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipeline-build-run-
    spec:
      serviceAccountName: tekton-triggers-gitlab-sa
      pipelineRef:
        name: pipeline-build
      podTemplate:
        tolerations:
        - key: "tekton"
          value: "true"
          operator: "Equal"
          effect: "NoSchedule"
```

triggers: 0.15.0
pipeline: 0.27.0

@vdemeester @goldmann @abayer @imjasonh @bobcatfish
