### ISSUE TITLE
Do 'sidecars' support 'hostAliases'?

### ISSUE THREAD

**Issue by ben-wangz** [tektoncd/pipeline#4674]
I got such problem while trying to set `hostAliases` for `sidecars`
```text
for: "tekton.pipeline.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "hostAliases"
```

use case:
In my case, I use sidecars to provide docker in docker functionality.
I want to use a local registry for `docker push`, but the hostname of this registry won't be resolved by default. Therefore, hostAliases need to be added. (any other solutions is welcome~, thanks in advance)

part of my task definition
```yaml
# ...
  sidecars:
    - image: $(params.image-registry)/docker:20.10.13-dind-alpine3.15
      name: dockerd
      #args:
      #  - --insecure-registry=insecure.docker.registry.local
      securityContext:
        privileged: true
      hostAliases:
        - ip: "192.168.123.7"
          hostnames:
            - "insecure.docker.registry.local"
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
        - name: $(workspaces.code.volume)
          mountPath: $(workspaces.code.path)
# ...
```
