### ISSUE TITLE
If I pass something that can be interpreted as a variable on a task input it will break the task with a non-existent variable error

### ISSUE THREAD

**Issue by viniagostini** [tektoncd/pipeline#4690]
# Expected Behavior
print the literal `{"key": "$(params.a)"}`

# Actual Behavior
CouldntGetTask error
`failed to create task run pod "some-task-run-2": non-existent variable in "echo {\"key\": \"$(params.a)\"}\n": steps[0].script. Maybe missing or invalid Task my-ns/some-task`

# Steps to Reproduce the Problem

``` yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: some-task
  namespace: my-ns
spec:
  params:
    - name: input
  steps:
    - name: print
      image: alpine
      script: |
        echo $(params.input)

---

apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: some-task-run-2
  namespace: my-ns
spec:
  taskRef:
    name: some-task
  serviceAccountName: tekton-triggers-admin
  params:
    - name: input
      value: '{"key": "$(params.a)"}'

```

I ran into this problem trying to pass a TaskRun cloud event payload as a param to another Task. For now, I have a workaround using CEL on the EventListener to replace every `$(params.` for an empty string like so 
```
- name: "overlays"
   value:
     - key: cePayload
        expression: body.marshalJSON().replace('$(params.','')
```

This works fine for me now but I see some unexpected behaviors happening in the future, so it would be nice if the task could escape or not try to interpret the values on the params.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

``` 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.23.0
Pipeline version: v0.28.2
Triggers version: v0.18.0
Dashboard version: v0.24.1
```
