### ISSUE TITLE
Failed to create pipeline of version v1beta1 with client-go

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#4696]
### ERRROR
```
Failed to apply pipelineadmission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "spec"
```
Client versions:
```
	k8s.io/api => k8s.io/api v0.22.5
	k8s.io/apimachinery => k8s.io/apimachinery v0.22.5
	k8s.io/client-go => k8s.io/client-go v0.22.5
```

**Comment by zeromsi** [comment]
I've installed 0.20.0 version of tekton pipeline. I can apply pipeline via kubectl. But Facing problem with client-go.
In my go.mod file,
```
go 1.16

require (
	github.com/dgrijalva/jwt-go v3.2.0+incompatible
	github.com/evanphx/json-patch v4.12.0+incompatible // indirect
	github.com/ghodss/yaml v1.0.0 // indirect
	github.com/go-openapi/spec v0.20.4 // indirect
	github.com/google/uuid v1.3.0
	github.com/gorilla/websocket v1.4.2
	github.com/gregjones/httpcache v0.0.0-20190611155906-901d90724c79 // indirect
	github.com/joho/godotenv v1.3.0
	github.com/json-iterator/go v1.1.12 // indirect
	github.com/labstack/echo-contrib v0.11.0
	github.com/labstack/echo/v4 v4.6.1
	github.com/labstack/gommon v0.3.1 // indirect
	github.com/mailru/easyjson v0.7.7 // indirect
	github.com/mattbaird/jsonpatch v0.0.0-20171005235357-81af80346b1a // indirect
	github.com/opentracing/opentracing-go v1.2.0
	github.com/peterbourgon/diskv v2.0.1+incompatible // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/stretchr/testify v1.7.0
	github.com/swaggo/echo-swagger v1.1.4
	github.com/swaggo/files v0.0.0-20210815190702-a29dd2bc99b2 // indirect
	github.com/swaggo/swag v1.7.4
	github.com/tektoncd/pipeline v0.33.1
	go.mongodb.org/mongo-driver v1.7.1
	gopkg.in/inf.v0 v0.9.1 // indirect
	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
	k8s.io/api v0.23.4
	k8s.io/apimachinery v0.23.4
	k8s.io/cli-runtime v0.21.4 // indirect
	k8s.io/client-go v1.5.2
	knative.dev/pkg v0.0.0-20220131144930-f4b57aef0006 // indirect
	sigs.k8s.io/yaml v1.3.0 // indirect
)

replace (
	k8s.io/api => k8s.io/api v0.22.5
	k8s.io/apimachinery => k8s.io/apimachinery v0.22.5
	k8s.io/client-go => k8s.io/client-go v0.22.5
	k8s.io/code-generator => k8s.io/code-generator v0.22.5
	k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20211109043538-20434351676c
)

```

**Comment by jbpratt** [comment]
@zeromsi `0.20.0` is quite old, but I think we still need some more information. Can you post an example of the Go code and the yaml that is causing this? The goal is to reproduce the issue with as little code as possible  :smiley_cat:

**Comment by zeromsi** [comment]
@jbpratt ,I'm trying apply the following yaml
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: buildpacks-test-pipeline
spec:
  params:
    - name: image
      type: string
      description: image URL to push
  workspaces:
    - name: source-workspace # Directory where application source is located. (REQUIRED)
    - name: cache-workspace # Directory where cache is stored (OPTIONAL)
  tasks:
    - name: fetch-repository # This task fetches a repository from github, using the `git-clone` task you installed
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: url
          value: https://github.com/buildpacks/samples
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: buildpacks # This task uses the `buildpacks` task to build the application
      taskRef:
        name: buildpacks
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source-workspace
        - name: cache
          workspace: cache-workspace
      params:
        - name: APP_IMAGE
          value: "$(params.image)"
        - name: SOURCE_SUBPATH
          value: "apps/java-maven" # This is the path within the samples repo you want to build (OPTIONAL, default: "")
        - name: BUILDER_IMAGE
          value: paketobuildpacks/builder:base # This is the builder we want the task to use (REQUIRED)
    - name: display-results
      runAfter:
        - buildpacks
      taskSpec:
        steps:
          - name: print
            image: docker.io/library/bash:5.1.4@sha256:b208215a4655538be652b2769d82e576bc4d0a2bb132144c060efc5be8c3f5d6
            script: |
              #!/usr/bin/env bash
              set -e
              echo "Digest of created app image: $(params.DIGEST)"              
        params:
          - name: DIGEST
      params:
        - name: DIGEST
          value: $(tasks.buildpacks.results.APP_IMAGE_DIGEST)
```
My code:

```golang
	pipeline := v1beta1.Pipeline{
		TypeMeta: metaV1.TypeMeta{
			Kind:       "Pipeline",
			APIVersion: "tekton.dev/v1beta1",
		},
		ObjectMeta: metaV1.ObjectMeta{
			Name:      step.Name,
			Namespace: config.CiNamespace,
			Labels:    label,
		},
		Spec: v1beta1.PipelineSpec{
			Params: []v1beta1.ParamSpec{
				{Name: "image", Type: "string", Description: "image URL to push"},
			},
			Workspaces: []v1beta1.PipelineWorkspaceDeclaration{
				{Name: "source-workspace", Description: "Directory where application source is located"},
				{Name: "cache-workspace", Description: "Directory where cache is stored for the application"},
			},
			Tasks: []v1beta1.PipelineTask{
				{Name: "fetch-repository", TaskRef: &v1beta1.TaskRef{
					Name: "git-clone",
				}, Params: []v1beta1.Param{
					{
						Name: "url", Value: v1beta1.ArrayOrString{
							Type:      v1beta1.ParamTypeString,
							StringVal: step.Params[enums.IMAGE_URL],
						},
					},
					{
						Name: "subdirectory", Value: v1beta1.ArrayOrString{
							Type:      v1beta1.ParamTypeString,
							StringVal: "",
						},
					},
					{
						Name: "deleteExisting", Value: v1beta1.ArrayOrString{
							Type:      v1beta1.ParamTypeString,
							StringVal: "true",
						},
					},
				}, Workspaces: []v1beta1.WorkspacePipelineTaskBinding{{Name: "output", Workspace: "source-workspace"}}},

				{Name: "buildpacks", TaskRef: &v1beta1.TaskRef{
					Name: "buildpacks",
				}, Params: []v1beta1.Param{
					{
						Name: "APP_IMAGE", Value: v1beta1.ArrayOrString{
							Type:      v1beta1.ParamTypeString,
							StringVal: "$(params.image)",
						},
					},
					{
						Name: "SOURCE_SUBPATH", Value: v1beta1.ArrayOrString{
							Type:      v1beta1.ParamTypeString,
							StringVal: "apps/java-maven",
						},
					},
					{
						Name: "BUILDER_IMAGE", Value: v1beta1.ArrayOrString{
							Type:      v1beta1.ParamTypeString,
							StringVal: "paketobuildpacks/builder:base",
						},
					},
				}, RunAfter: []string{"fetch-repository"}, Workspaces: []v1beta1.WorkspacePipelineTaskBinding{{Name: "source", Workspace: "source-workspace"}, {Name: "cache", Workspace: "cache-workspace"}}},

				{Name: "display-results", TaskSpec: &v1beta1.EmbeddedTask{
					TaskSpec: v1beta1.TaskSpec{
						Params: []v1beta1.ParamSpec{
							{Name: "DIGEST"},
						},
						Steps: []v1beta1.Step{{Container: corev1.Container{
							Name:  "print",
							Image: "docker.io/library/bash:5.1.4@sha256:b208215a4655538be652b2769d82e576bc4d0a2bb132144c060efc5be8c3f5d6",
						}, Script: " #!/usr/bin/env bash\n              set -e\n              echo \"Digest of created app image: $(params.DIGEST)\""}},
					},
				}, Params: []v1beta1.Param{
					{
						Name: "DIGEST", Value: v1beta1.ArrayOrString{
							Type:      v1beta1.ParamTypeString,
							StringVal: "$(tasks.buildpacks.results.APP_IMAGE_DIGEST)",
						},
					},
				}, RunAfter: []string{"buildpacks"}},
			},
		},
	}
```

How I'm creating the object:

```golang
client.TektonV1beta1().Pipelines(config.CiNamespace).Create(context.Background(), &pipeline, metaV1.CreateOptions{})
```
