### ISSUE TITLE
Make namespace accessible in Task definition

### ISSUE THREAD

**Issue by tmds** [tektoncd/pipeline#4716]
A `Task` definition can not obtain the namespace it is running in. This is a request to make that namespace available, for example using `context.namespace`.

Relates to https://github.com/tektoncd/pipeline/issues/4540.

cc @vdemeester @jerop @KyWa

**Comment by sbwsg** [comment]
Thanks for the issue report.  Our docs indicate [there's already a variable Tasks can use](https://github.com/tektoncd/pipeline/blob/main/docs/variables.md#variables-available-in-a-task): `$(context.taskRun.namespace)`. You should be able to place this variable in your Task's definition and Tekton should replace it with the namespace that the Task is executing in (regardless if it's a pipelinerun or taskrun that executes it).  If it doesn't then I reckon we should probably call this a bug and I can look into it.

Here's a small example to illustrate this:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: foo
spec:
  steps:
  - name: test-context
    image: quay.io/openshift-pipeline/s2i
    command: ['echo', '$(context.taskRun.namespace)']
```

And a PipelineRun that uses this Task:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pr-test-foo
spec:
  tasks:
  - name: try-foo
    taskRef:
      name: foo
```

And just for completeness' sake here's a TaskRun that also uses this Task:

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: tr-test-foo
spec:
  taskRef:
    name: foo
```

When I get the logs from the taskrun and pipelinerun pods I see `default` printed in both cases.
