### ISSUE TITLE
[TEP 0075, 0076]: Structured object / arrays in Results and Params

### ISSUE THREAD

**Issue by ywluogg** [tektoncd/pipeline#4723]
### Feature request

The issue will track the implementation for [TEP-0075 Propose object (dicitonary) param and result types](https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md) and [TEP-0076 Propose array results and indexing](https://github.com/tektoncd/community/commit/e0e7d73e08113ac82e5fe8bc6467d31db51fbec7)

The two docs are in the process of review to get to *Implementable* states (https://github.com/tektoncd/community/pull/661)

### Use case

Will have a more detailed use case summary, but please refer to the use cases mentioned in [TEP-0075 Propose object (dicitonary) param and result types](https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md) and [TEP-0076 Propose array results and indexing](https://github.com/tektoncd/community/blob/main/teps/0076-array-result-types.md)

To summarize, we want to change the params to be supporting the following:

Params will affect the following:
- Pipeline.params
- Pipeline.TaskRef.params
- PipelineRun.params
- PipelineRun.PipelineSpec.params
- PipelineRun.PipelineSpec.tasks.params
- PipelineRun.PipelineSpec.taskSpec.params
- Task.params
- TaskRun.spec.params
- TaskRun.TaskSpec,params

We also want to change the results to be supporting objects and arrays in Pipeline Results and Task Results.
Results will affect the following:
- PipelineRun.Spec.PipelineSpec.Results
- PipelineRun.Spec.PipelineSpec.PipelineSpec.TaskSpec.Results
- Pipeline.Spec.Results
- TaskRun.Spec.TaskSpec.Results
- Task.Spec.Results

Below an example to specify a object param in Tasks and using its key1 and image1 value, and also specify a object in Task results and use script to write the results:
``` yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-with-parameters
spec:
  params:
  - name: objectVal1
     description: "description1"
     type: object
     properties:
        key1:
          type: string
        image1:
          type: string
  - name: objectVal2
     description: "description2"
     type: object
     properties:
        key1:
          type: string
        image1:
          type: string
  steps:
  - name: step1
     image: $(objectVal1.image1)
     script: |
     echo $(objectVal1.key1)
  - name: step2
     image: $(objectVal2.image1)
     script: |
     echo $(objectVal2.key1)
  - name: step3
     image: bash:latest
     script: |
          #!/usr/bin/env bash
          echo -n "{"key1": "$(params.objectVal1.key1)", "image1": "$(params.objectVal1.image1)"}" | tee $(results.resultObject1.path)
  results:
  - name: resultObject1
    description: "description3"
     type: object
     properties:
        key1:
          type: string
        image1:
          type: string
```

Below an example to specify a object param in TaskRuns:
``` yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun1
spec:
  params:
  - name: objectVal1
     value:
        key1: value1
        image1: bash:latest
  - name: objectVal2
     value:
        key1: value2
        image1: bash:latest
  taskRef:
    name: task-with-parameters
```

Below an example to specify a object param in PipelineRun and use it as a whole in tasks:
``` yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-object-param
spec:
  pipelineSpec:
    params:
      - name: pipelineObjectVal1
        description: "description1"
        type: object
        default:
            key1: "val1"
            image1: "bash:latest"
    tasks:
      - name: task-1
        taskRef:
          name: task-with-parameters
        params:
          - name: objectVal1
             value: $(params.pipelineObjectVal1[*])
          - name: objectVal2
             value: $(params.pipelineObjectVal1[*])
      - name: task-2
        taskRef:
          name: task-with-parameters
        params:
          - name: objectVal1
             value: $(tasks.task-1.params.resultObject1[*])
          - name: objectVal2
             value: $(tasks.task-1.params.resultObject1[*])
  params:
    - name: pipelineObjectVal1
       value:
          key1: "val1"
          image1: "bash:latest"
     
```

Below an example to specify a object param in a Task inPipelineRun and use it as a whole in:
``` yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-object-param
spec:
  pipelineSpec:
    params:
      - name: pipelineObjectVal1
        description: "description1"
        type: object
        default:
            key1: val1
            image1: bash:latest
    tasks:
      - name: task-1
        taskRef:
          name: task-with-parameters
        params:
          - name: objectVal1
             value: $(params.pipelineObjectVal1[*])
          - name: objectVal2
             value: $(params.pipelineObjectVal1[*])
    results:
    - name: pipelineResult1
       description: "result description 1"
       value: $(tasks.task-1.results.resultObject1[*])
    - name: pipelineResult2
       description: "result description 2"
       value:
          key2: $(tasks.task-1.results.resultObject1.key1)
  params:
    - name: pipelineObjectVal1
      value:
         key1: val2
         image1: bash:latest
```

### General Implementation Requirements
- First Stage: implement features in v1beta1 apiversion and hide them under alpha feature flag,

### Task Breakdowns
- Area 1
   - Object in Params
     - Task, TaskRun webhook validations on object params
     - Task, TaskRun webhook mutations on object params
     - Pipeline, PipelineRun webhook validations on object params
     - Object vs object properties validations
     - TaskRun & PipelineRun reconciler substitutions on object params: individual keys and as a whole
     - Param value type corrections
     - TaskRun against Task spec & PipelineRun against Pipeline spec reconciler validations on object params using object vs object properties validations
     - E2E Tests for object params
- Area 2
   - Array types
     - Support array type of results spec in Task and Pipeline
     - Support array type of results for emitting in file and consuming from file
     - Task webhook validations on array results
     - Pipeline webhook validations on array results
     - Param and Result array indexing substitutions
     - E2E Tests for results in TaskRuns and PipelineRuns on array params
     - Example yamls for results in TaskRuns and PipelineRuns on array s
   - Object type of Results
     - Task and Pipeline webhook validations on object results
     - Results emissions and consuming from files on object results
     - TaskRun & PipelineRun reconciler substitutions on object results: individual keys and as a whole
     - TaskRun against Task spec & PipelineRun against Pipeline spec reconciler validations on object results using object vs object properties validations
    - E2E Tests for results in TaskRuns and PipelineRuns on objects
    - Example yamls for results in TaskRuns and PipelineRuns on objects

Future Work
- Matrix support objects and params
- Example yamls for object params in TaskRuns and PipelineRuns
- Nested objects
- Support more ways of object param & results of substitutions (#5056)
- Refactoring params and results into separate directories (#5001 )
- CRD for objects
- Nested arrays of objects
- Validate array param out of bound (pkg/reconciler/pipelinerun/resources/apply.go)
- Invalidate usage of object / array as a whole in format `results.result1` and `params.param1` (#5078)

**Comment by Yongxuanzhang** [comment]
/ assign @Yongxuanzhang

**Comment by chuangw6** [comment]
Hi @ywluogg ,
I just realized that we might need to disallow the parameters whose name contains dot(.). Reasons are mentioned in #4797 , which is related to [TEP-0075](https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md).

Do you have any thoughts on this?
Thanks!

**Comment by ywluogg** [comment]
> Hi @ywluogg , I just realized that we might need to disallow the parameters whose name contains dot(.). Reasons are mentioned in #4797 , which is related to [TEP-0075](https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md).
> 
> Do you have any thoughts on this? Thanks!

Thanks Chuang for the updates!

**Comment by Yongxuanzhang** [comment]
It may be worth discussing the support for custom tasks when we finish these two teps

**Comment by ywluogg** [comment]
> It may be worth discussing the support for custom tasks when we finish these two teps

+1 I will organize a list of extended items for the two TEPs

**Comment by ywluogg** [comment]
PRs that need to be added to milestone: #5139 #5132 #5088

**Comment by ywluogg** [comment]
All the features listed not in "Future Work" section are finished

**Comment by ywluogg** [comment]
``` yaml
params:
    - name: IMAGE_URL
       value: gcr.io/foo/bar
    - name: IMAGE_DIGEST
       value: sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b7
...
results:
   - name: MAVEN_PKG_URL
       value: us-west4-maven.pkg.dev/test-project/test-repo/com/google/guava/guava/31.0/guava-31.0.jar
    - name: MAVEN_PKG_DIGEST
       value: sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b8
```

``` yaml
params:
    - name: image_object
       value:
           uri: gcr.io/foo/bar
           digest: sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b7
...
results:
   - name: maven_pkg
       value:
           uri: us-west4-maven.pkg.dev/test-project/test-repo/com/google/guava/guava/31.0/guava-31.0.jar
           digest: sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b8
```
