### ISSUE TITLE
pipeline fails to mount secrets

### ISSUE THREAD

**Issue by kplimack** [tektoncd/pipeline#4730]
Pipeline fails to initialize due to failed mounts.  These secrets exist in the correct namespace.

version: `tektoncd/pipeline/cmd/controller:v0.29.0@sha256:72f79471f06d096cc53e51385017c9f0f7edbc87379bf415f99d4bd11cf7bc2b`

```
  Warning  FailedMount  43s (x3 over 44s)  kubelet            MountVolume.SetUp failed for volume "builder-token-zqlkw" : object "tekton-pipelines"/"builder-token-zqlkw" not registered
  Warning  FailedMount  43s (x3 over 44s)  kubelet            MountVolume.SetUp failed for volume "tekton-internal-secret-volume-builder-registrycreds-kpkxm" : object "tekton-pipelines"/"builder-registrycreds" not registered


 k get secrets | egrep '(builder|registry)'
builder-registrycreds                       kubernetes.io/dockerconfigjson
builder-token-zqlkw                             kubernetes.io/service-account-token
```

**Comment by debuggerpk** [comment]
I am having the same problem.

**Comment by debuggerpk** [comment]
I think I have narrowed down the problem.

First the context, Below is my `Task`

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rust-compile
  labels:
    app.kubernetes.io/version: "0.0.1"
spec:
  params:
    - name: image
      description: The image to use for the build.
      type: string
      default: ubuntu:16.04
    - name: debug
      description: Whether to enable debug mode.
      type: string
      default: "true"
  workspaces:
    - name: source
      description: The source code that will be cloned.
    - name: artifacts
      description: The location where the artifacts will be stored.
  steps:
    - name: compile
      image: $(params.image)
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
        - name: WORKSPACE_ARTIFACTS_PATH
          value: $(workspaces.artifacts.path)
      script: |
        #!/usr/bin/env bash
        cd ${WORKSPACE_SOURCE_PATH}
        ls -alhR

        UBUNTU=ubuntu
        CENTOS=centos
        DISTRO=$(grep -oP '(?<=^ID=).+' /etc/os-release | tr -d '"')
        VERSION=$(grep -oP '(?<=^VERSION_ID=).+' /etc/os-release | tr -d '"')

        echo ${DISTRO}

        case $DISTRO in
          $UBUNTU)
            apt-get update -y
            apt-get install -y curl gcc libpcap-dev build-essential
            ;;
          $CENTOS)
            yum groupinstall -y "Development Tools"
            yum install -y libpcap-devel
            ;;
          *)
            echo "Unsupported distribution: $DISTRO"
            exit 1
            ;;
        esac

        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        CARGO_TARGET_DIR="${WORKSPACE_ARTIFACTS_PATH}/debug/${DISTRO}/${VERSION}"
        cd src
        cargo build --verbose
```

and my `Pipeline` definition

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rust-compile
  labels:
    app.kubernetes.io/version: "0.0.1"
spec:
  params:
    - name: github-url
      description: The git url to clone from.
      type: string
    - name: github-revision
      description: The git revision to checkout.
      type: string
      default: "main"
  workspaces:
    - name: source
      description: The source code that will be cloned.
    - name: artifacts
      description: The location where the artifacts will be stored.
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.github-url)
        - name: revision
          value: $(params.github-revision)
      workspaces:
        - name: output
          workspace: source

    - name: centos--7
      taskRef:
        name: rust-compile
      runAfter:
        - clone
      params:
        - name: image
          value: centos:centos7
        - name: debug
          value: "true"
      workspaces:
        - name: source
          workspace: source
        - name: artifacts
          workspace: artifacts

    - name: ubuntu--16-04
      taskRef:
        name: rust-compile
      runAfter:
        - clone
      params:
        - name: image
          value: ubuntu:16.04
        - name: debug
          value: "true"
      workspaces:
        - name: source
          workspace: source
        - name: artifacts
          workspace: artifacts
```

The following `PipelineRun` runs without any problem

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipeline-run-rust-compile-
spec:
  pipelineRef:
    name: rust-compile
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: tkn-workspace
      subPath: source
    - name: artifacts
      emptyDir: {}
  params:
    - name: github-url
      value: # redacted
  serviceAccountName: trace-bot
```

But the minute I apply the same `persistentVolumeClaim` to workspaces.artifacts, i get the secret volume mount error, which shouldn't be the case.
