### ISSUE TITLE
 Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "sh": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by usernameisnull** [tektoncd/pipeline#4766]
# Expected Behavior
run success
# Actual Behavior
 Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "sh": executable file not found in $PATH: unknown
# Steps to Reproduce the Problem

1.  download `https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/taskruns/task-result.yaml`
2.  k creat -f task-result.yaml
3.  fail

# Additional Info
- include:
      - https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/taskruns/task-result.yaml
      - https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/taskruns/task-volume-args.yaml
      - https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/taskruns/template-volume.yaml
      - https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/taskruns/unnamed-steps.yaml
- Kubernetes version: v1.23.5

  **Output of `kubectl version`:**

  ```
  # k version
     Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
     Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version: v0.34.1

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Is there something wrong with my installation?**
I changed the script to follow：
```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: print-date-
spec:
  taskSpec:
    description: |
      A simple task that prints the date.
    results:
      - name: current-date-unix-timestamp
        description: The current date in unix timestamp format
      - name: current-date-human-readable
        description: The current date in human readable format
    steps:
      - name: print-date-unix-timestamp
        image: 10.6.182.195:5000/ubuntu:latest
        #script: |
        #  #!/usr/bin/env bash
        #  date +%s | tee /tekton/results/current-date-unix-timestamp
        command:
          - bash
          - -c
          - date +%s | tee /tekton/results/current-date-unix-timestamp
      - name: print-date-human-readable
        image: 10.6.182.195:5000/ubuntu:latest
        #script: |
        #  #!/usr/bin/env bash
        #  date | tee /tekton/results/current-date-human-readable
        command:
          - bash
          - -c
          - date | tee /tekton/results/current-date-human-readable

```
