### ISSUE TITLE
place-scripts initContainer fails on permission denied

### ISSUE THREAD

**Issue by shirouto** [tektoncd/pipeline#4784]
# Actual Behavior

Any task using `script` fails before the main container starts during `place-scripts`.

# Steps to Reproduce the Problem
A task like
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
  - name: echo
    image: alpine
    script: |
      #!/bin/sh
      echo "Hello World"
```
will fail when run with `sh: /tekton/bin/entrypoint: Permission denied` in the `place-scripts` container logs.

# Additional Info

- Kubernetes version: 
client/server 1.23 
- Tekton Pipeline version:
Client version: 0.19.1
Pipeline version: v0.34.1
Dashboard version: v0.25.0

this is a brand new deployment of tekton pipelines on a on-prem cluster. Avoiding `script` and relying  instead on `command`/`args` works just fine.
