### ISSUE TITLE
Missing validation against parameter name format

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/pipeline#4792]
# Expected Behavior
[This doc](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#specifying-parameters) mentioned that the parameter names should follow the following rules:
- Must only contain alphanumeric characters, hyphens (-), underscores (_), and dots (.).
- Must begin with a letter or an underscore (_).
> For example, foo.Is-Bar_ is a valid parameter name, but barIsBa$ or 0banana are not.

Therefore, there should be existing validation against parameter names that users specified. For example, the following parameter names are invalid, which should be caught and reported by the admission webhook when the taskrun yaml is applied.
```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: validation-
spec:
  taskSpec:
    params:
      - name: 0foo
        default: "bar1"
      - name: a b
        default: "bar2"
      - name: $x
        default: "bar3"
    results:
      - name: echo-output
        description: "successful echo"
      - name: bad-echo
        description: "bad echo behaviour"
    steps:
      - name: echo-params
        image: bash
        script: |
          set -e
          echo $(params.0foo) $(params.a b) $(params.$x) | tee $(results.echo-output.path)
          echo $(params.0fo) | tee $(results.bad-echo.path)
```
# Actual Behavior
`taskResults` output
```
  taskResults:
  - name: bad-echo
    value: |2+

  - name: echo-output
    value: |
      bar1 bar2 bar3
```

1. When you apply the above taskrun yaml, it can be successfully applied, which should've been reported because of invalid param name format instead.
2.  From taskrun result, `echo-output` is populated with values `bar1 bar2 bar3`, which should not happen because the parameter names are all invalid i.e. `0foo` starts with 0, `a b` has a space in the middle, `$x` starts with $
3. In addition, the taskrun result `bad-echo` is shown in the `taskResults` list under status, but has some confusing value `+2`.  (See the reason why this happens [here](https://github.com/tektoncd/pipeline/issues/4792#issuecomment-1109397484))

# Steps to Reproduce the Problem

1. Save above yaml code into a file, and apply it
2. see the taskrun
`kubectl get tr <TASKRUN_NAME> -o yaml`
3. find status -> taskResults 

# Additional Info

## Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1503", GitCommit:"2c7bbda09a9b7ca78db230e099cf90fe901d3df8", GitTreeState:"clean", BuildDate:"2022-02-18T03:17:45Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
  WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
  ```

## Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  Client version: 0.21.0
  Pipeline version: devel
  ```

## Also found that a param without a name also works, which is weird 
```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: validation-
spec:
  taskSpec:
    params:
      - name:
        default: "bar1"
    results:
      - name: echo-output
        description: "successful echo"
    steps:
      - name: echo-params
        image: bash
        script: |
          set -e
          echo $(params.) | tee $(results.echo-output.path)
```

**Comment by chuangw6** [comment]
# Thoughts
- The purpose of the function [ValidateVariableP](https://github.com/tektoncd/pipeline/blob/f0f9e32da6b4145ede27a371900e853a3530c1ee/pkg/substitution/substitution.go#L48-L63) called in [task_validation.go](https://github.com/tektoncd/pipeline/blob/main/pkg/apis/pipeline/v1beta1/task_validation.go) is to use [extractVariablesFromString](https://github.com/tektoncd/pipeline/blob/f0f9e32da6b4145ede27a371900e853a3530c1ee/pkg/substitution/substitution.go#L149-L165) to parse the name part from the string `$(params.<NAME>)` and check if the name is one of param names in `vars` - a set of all param names in task spec. 
- [extractVariablesFromString](https://github.com/tektoncd/pipeline/blob/f0f9e32da6b4145ede27a371900e853a3530c1ee/pkg/substitution/substitution.go#L149-L165) seems to extract param names that follow the two rules mentioned at the beginning of the issue using the `pattern` it composed at the function's beginning.
- The bug is that when the param name is invalid format, [extractVariablesFromString](https://github.com/tektoncd/pipeline/blob/f0f9e32da6b4145ede27a371900e853a3530c1ee/pkg/substitution/substitution.go#L149-L165) will return empty, and [ValidateVariableP](https://github.com/tektoncd/pipeline/blob/f0f9e32da6b4145ede27a371900e853a3530c1ee/pkg/substitution/substitution.go#L48-L63) will return nil, which means it cannot catch the invalid param name. When the validation is done without any error, the taskrun is actually executed and when `0fo` is actually referenced in `echo $(params.0fo) | tee $(results.bad-echo.path)`, it's found that oh it doesn't exist in task's params list and some unexpected behaviour appears.
  ```
    taskResults:
    - name: bad-echo
      value: |2+
  
  ```

**Comment by afrittoli** [comment]
@chuangw6 thank you for this report, it sounds like validation there can use some improvement and unit tests :)
Do you plan to work on a fix for this or shall we mark it as help wanted?

**Comment by chuangw6** [comment]
Hi @afrittoli ,
Yeah, I am happy to look into this.
Just wonder why two rules for param name forma are in place. Are we restricting this to avoid something or is it just a convention for variable names? Can you help me understand this?
Thank you!

**Comment by chuangw6** [comment]
# Proposal: disallow the usage of dots(.) in param names
[This doc](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#specifying-parameters) mentioned that the parameter names should follow the following rules:
- Must only contain alphanumeric characters, hyphens (-), underscores (_), and dots (.).
- Must begin with a letter or an underscore (_).

But we need to disallow the usage of dots(.) in param names.

# Reason:
[TEP-0075](https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md) proposes supporting object/dictionary type parameters that will have keys defined in `properties` section. See the parameter `foo` in the following example. And to reference a particular field in this object parameter we can use dot notation i.e. `$(params.foo.key1)`, which is mentioned [here](https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md#using-objects-in-variable-replacement).

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: object-param-test-
spec:
  taskSpec:
    params:
      - name: foo
        properties:
          key1: {}
          key2: {}
        default:
          key1: "val1"
          key2: "val2"
      - name: foo.key1
        default: "tricky"
    results:
      - name: echo-output
    steps:
      - name: echo-params
        image: bash
        script: |
          set -e
          echo $(params.foo.key1) | tee $(results.echo-output.path)
```

This reference approach for a key of the object parameter will have conflicts when it appears together with a parameter whose name contains dot(.) such as `foo.key1`. For example, when we use `$(params.foo.key1)`, it's impossible to know whether it's referencing the particular key `key1` of the object parameter named `foo` OR it's referencing a standalone parameter named `foo.key1`. This confusion is caused by the fact that containing a dot in parameter name is allowed currently.
Therefore, we should not allow to use dot(.) in parameter names.
