### ISSUE TITLE
Disallow using dots(.) in param names

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/pipeline#4797]
# Proposal: Disallow using dots(.) in param names
[This doc](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#specifying-parameters) mentioned that the parameter names should follow the following rules. (But we do not enforce it currently - reported here #4792 )
- Must only contain alphanumeric characters, hyphens (-), underscores (_), and ***dots (.)***.
- Must begin with a letter or an underscore (_).

But we need to disallow the usage of dots(.) in param names.

# Reason:
[TEP-0075](https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md) proposes supporting object/dictionary type parameters that will have keys defined in `properties` section. See the parameter `foo` in the following example. And to reference a particular field in this object parameter we can use dot notation i.e. `$(params.foo.key1)`, which is mentioned [here](https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md#using-objects-in-variable-replacement).

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: object-param-test-
spec:
  taskSpec:
    params:
      - name: foo
        properties:
          key1: {}
          key2: {}
        default:
          key1: "val1"
          key2: "val2"
      - name: foo.key1
        default: "tricky"
    results:
      - name: echo-output
    steps:
      - name: echo-params
        image: bash
        script: |
          set -e
          echo $(params.foo.key1) | tee $(results.echo-output.path)
```

This reference approach for a key of the object parameter will have conflicts when it appears together with a parameter whose name contains dot(.) such as `foo.key1`. For example, when we use `$(params.foo.key1)`, it's impossible to know whether it's referencing the particular key `key1` of the object parameter named `foo` OR it's referencing a standalone parameter named `foo.key1`. This confusion is caused by the fact that containing a dot in parameter name is allowed currently.
Therefore, we should not allow to use dot(.) in parameter names.
