### ISSUE TITLE
Missing validation against duplicated parameter names

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/pipeline#4798]
# Expected Behavior
Duplicated parameters (with same name) should be checked in both ***TaskRunSpec's*** `params` and ***TaskSpec's*** `params`
Example:
- two `bars` in ***TaskRunSpec's*** `params` and two `foos` in ***TaskSpec's*** `params`
```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: validation-
spec:
  params:
    - name: bar
      value: "xxx1"
    - name: bar
      value: "xxx2"
  taskSpec:
    params:
      - name: foo
        default: "value1"
      - name: foo
        default: "value2"
    results:
      - name: echo-output
        description: "see echo output"
    steps:
      - name: echo-params
        image: bash
        script: |
          set -e
          echo $(params.foo) | tee $(results.echo-output.path)
```
# Actual Behavior
- The duplicated two `bar`s in ***TaskRunSpec's*** params will be captured and reported by this [function](https://github.com/tektoncd/pipeline/blob/f0f9e32da6b4145ede27a371900e853a3530c1ee/pkg/apis/pipeline/v1beta1/taskrun_validation.go#L152-L165). And this will cause the taskrun cannot be applied successfully and the following error message will be returned, which makes sense!
  ```
  Error from server (BadRequest): error when creating "dup.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: expected exactly one, got both: spec.params[bar].name
  ```
- But the duplicated two `foo`s in ***TaskSpec's*** params will not be captured. With line 6-10 (TaskRunSpec's params) deleted, the taskrun will be executed successfully, but the param value`value2` is written to result. This is confusing i.e. why `value2` is chose instead of `value1`?
# Steps to Reproduce the Problem

1. save the above yaml code into a file, and `kubectl apply -f <FILE_NAME>.yaml`
2. you can see the error message when apply it, which is mentioned in `Actual Behavior`'s 1st point.
3. delete line 6-10 (TaskRunSpec's params section), reapply the yaml file 
4. you can see the taskrun is executed successfully, but the weird value is written into taskresult, which is mentioned in `Actual Behavior`'s 2nd point.
> you can see taskresult by run `kubectl get tr <taskrun_name> -o yaml`
# Additional Info
## Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1503", GitCommit:"2c7bbda09a9b7ca78db230e099cf90fe901d3df8", GitTreeState:"clean", BuildDate:"2022-02-18T03:17:45Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
  WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
  ```

## Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  Client version: 0.21.0
  Pipeline version: devel
  ```
