### ISSUE TITLE
Using Kaniko catalog with ECR does not seem to work

### ISSUE THREAD

**Issue by spstarr** [tektoncd/pipeline#4809]
So, I am trying to upload docker images to AWS ECR, I've added the IAM bindings to the EKS policy.

The problem is, with a `PipelineRun` I see no way to tell the Kaniko task how to set the environment variable as mentioned by the Kaniko developers for their container:

You can use instance roles when pushing to ECR from a EC2 instance or from EKS, by [configuring the instance role permissions](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_on_EKS.html) (the AWS managed policy **EC2InstanceProfileForImageBuilderECRContainerBuilds** provides broad permissions to upload ECR images and may be used as configuration baseline). Additionally, set **AWS_SDK_LOAD_CONFIG=true** as environment variable within the kaniko pod

So.

Given this command line as an example to test my Pipeline:

`tkn pipeline start clone-build-pipeline --param image=XXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/myapp-dev00/test/app --param url=https://github.com/MyCompany/myApp --param revision=develop --param verbose=true --param imageTag=0.0.0 --workspace name=shared-workspace,claimName=tekton-build-pvc --workspace name=git-config,secret=github-access-token --workspace name=ecr-config,config=docker-config,item=config.json=1 --showlog
`

Error:

_[build-push-image : build-and-push] error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "XXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/myapp-dev00/test/app:0.0.0": Post "https://XXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/v2/myapp-dev00/test/app/blobs/uploads/": EOF_

So how do I set `AWS_SDK_LOAD_CONFIG=true` to the task from the pipeline/run?

Thanks!

**Comment by afrittoli** [comment]
@spstarr The bad news is that today you can't using the stock kaniko task today. The good news are:
- you can create your own copy of the kaniko task which sets `AWS_SDK_LOAD_CONFIG` (based on the an input parameter if you wish)
- we have folks working on addressing this, see [TEP-101 Env in Pod Template](https://github.com/tektoncd/community/pull/658) 

Feel free to chime in the discussion on the TEP if you'd like, yours is definitely a good use case for adding the ability of passing env variables through in some way, since I would not want to change the catalog kaniko task to support every possible cloud vendor specific environment variable, but still I would like everyone to be able to use the stock kaniko task without having to create their own version of it.

**Comment by spstarr** [comment]
I'll clone the catalog in the meantime, as workaround. When new Tekton comes out with the CRD changes supported, I'll update our `tekton-pipelines` deployment.

**Comment by spstarr** [comment]
This worked when I modified the catalog for Kaniko, and:

```
  steps:
    - name: build-and-push
      workingDir: $(workspaces.source.path)
      image: $(params.BUILDER_IMAGE)
      env:
        - name: AWS_SDK_LOAD_CONFIG
          value: 'true'
        - name: AWS_EC2_METADATA_DISABLED
          value: 'true'
```

This worked, and some fixing of my IAM roles, I had an issue with wrong mapping but then it worked.

**Comment by SergK** [comment]
**Tekton v0.30.4**

Kaniko build task works without issues on AWS EKS 1.20 with IRSA (IAM Roles for Service Accounts) enabled.
The **only patch** you need to apply is to user proper service account:

Service account
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edp-kaniko
  namespace: tekton-pipelines
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::012345678910:role/AWSIRSAKaniko
```

PipelineRun
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: petclinic-kaniko
spec:
  serviceAccountNames:
    - taskName: kaniko-build          # my task
      serviceAccountName: edp-kaniko  # service account with Enabled IRSA
  pipelineRef:
    name: maven-build-pipeline
...
```
