### ISSUE TITLE
Case-insensitive duplication check in TaskRunSpec's params

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/pipeline#4814]
# Background
There is a function named [validateNoDuplicateNames](https://github.com/tektoncd/pipeline/blob/6f39e948ccd2b2b8091fb3b26d84d83412352087/pkg/apis/pipeline/v1beta1/taskrun_validation.go#L149-L165) in place to check **case-insensitive** duplication against ***taskRun spec's params***, WorkspaceBindings, StepOverrides and SidecarOverrides.

For params duplication check, it's only used in ***taskRun spec's params***, but not ***task spec params***. To make sure param names are consistent, #4806 will also call this [validateNoDuplicateNames](https://github.com/tektoncd/pipeline/blob/6f39e948ccd2b2b8091fb3b26d84d83412352087/pkg/apis/pipeline/v1beta1/taskrun_validation.go#L149-L165) to validate names in ***task spec params***. 

# Expected Behavior
We should expect this function to work correctly regardless of the order of case-insensitive duplications.

# Actual Behavior
- If name `foo` is provided in ***taskRun spec's*** params and then `Foo`, it can check duplication.
- If a name `Foo` is provided in ***taskRun spec's*** params and then `foo`, it fails to check duplication.

# Proposed solution
- caused by the implementation of [validateNoDuplicateNames](https://github.com/tektoncd/pipeline/blob/6f39e948ccd2b2b8091fb3b26d84d83412352087/pkg/apis/pipeline/v1beta1/taskrun_validation.go#L149-L165).

# Question
Why do we check ***case-insensitive*** duplication not ***case-sensitive***? In other words, is there any problem with treating name `foo` and `Foo` as two different parameters?

# Steps to Reproduce the Problem
```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: case-
spec:
  params:
    - name: Foo
      value: "x"
    - name: foo
      value: "y"
  taskSpec:
    params:
      - name: foo
      - name: Foo
    results:
      - name: echo-output
        description: "successful echo"
    steps:
      - name: echo-params
        image: bash
        script: |
          set -e
          echo $(params.foo) | tee $(results.echo-output.path)
```
1. run the yaml above you can see, it cannot check duplicated `Foo` and `foo` in taskrun spec.
2. change the order of `Foo` and `foo` in taskrun spec (provide value for `foo` first and then `Foo`) and apply again, you can see it validates the duplication
```
Error from server (BadRequest): error when creating "case-sensitivity.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: expected exactly one, got both: spec.params[Foo].name
```
