### ISSUE TITLE
task sed: couldn't open temporary file  Permission denied

### ISSUE THREAD

**Issue by balainit** [tektoncd/pipeline#4816]
cat /etc/issue
Debian GNU/Linux 11 \n \l

Kubernetes "v1.20.11"

deploy-to-k8s.yaml

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-to-k8s
spec:
  workspaces:
    - name: source
    - name: kubernetesconfig
      mountPath: /root/.kube
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: deployment.yaml
    - name: IMAGE
    - name: TAG
  steps:
    - name: run-kubectl
      image: xxxxxx/kubectl:1.20.11
      workingDir: $(workspaces.source.path)
      script: |
        sed -i s#IMAGE#$(params.IMAGE)#g $(params.pathToYamlFile)
        sed -i s#TAG#$(params.TAG)#g $(params.pathToYamlFile)
        kubectl apply -f $(params.pathToYamlFile)
```
tkn version

Client version: 0.23.1
Pipeline version: v0.34.1
Triggers version: v0.19.1
Dashboard version: v0.25.0

kubectl logs -f  deploy-to-k8s-pod

```
2022/05/02 08:59:49 warning: unsuccessful cred copy: ".gitconfig" from "/tekton/creds" to "/": unable to open destination: open /.gitconfig: permission denied
2022/05/02 08:59:49 warning: unsuccessful cred copy: ".git-credentials" from "/tekton/creds" to "/": unable to open destination: open /.git-credentials: permission denied
sed: couldn't open temporary file ./sedKiqC1e: Permission denied
```

**Comment by afrittoli** [comment]
Hello @balainit - thanks your for report. It looks like `sed` does not have access to create a temporary file. 
I'm not 100% sure what `sed` is doing there, but it feels like it may be trying to use same folder where your file is to create a temporary file. 

As a side not I would recommend using `apiVersion: tekton.dev/v1beta1` instead of `apiVersion: tekton.dev/v1alpha1`.

**Comment by balainit** [comment]
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-to-k8s
spec:
  workspaces:
    - name: source
    - name: kubernetesconfig
      mountPath: /root/.kube
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: deployment.yaml
    - name: IMAGE
    - name: TAG
  steps:
    - name: run-kubectl
      image: xxxxxx/kubectl:1.20.11
      workingDir: $(workspaces.source.path)
      script: |
         sed -i s#IMAGE#$(params.IMAGE)#g $(params.pathToYamlFile)
         sed -i s#TAG#$(params.TAG)#g $(params.pathToYamlFile)
         kubectl apply -f $(params.pathToYamlFile)
      securityContext:
          privileged: true
```
@afrittoli 
Thanks a lot, I used securityContext: privileged: true and it works fine
