### ISSUE TITLE
Pipeline stuck running after task failure

### ISSUE THREAD

**Issue by migeorge** [tektoncd/pipeline#4840]
I have a Pipeline that does a number of tasks and I'd like to update the status of each task on the commit in Github. I have the status update working, but the Pipeline Run doesn't seem to be working the way I expect it to. Maybe I'm missing something?

# Expected Behavior
Using the example Pipeline / Tasks provided, all tasks in the pipeline should pass except for `run-consumer-tests` and `set-consumer-tests-success`. `run-consumer-tests` should fail and `set-consumer-tests` should be skipped since the step before it failed.
After this, the `finally` tasks should be run as normal.

# Actual Behavior
`run-consumer-tests` fails and the Pipeline gets stuck in running with the following errors from the `tekton-pipelines` controller:

```
{"level":"error","ts":"2022-05-06T16:24:09.934Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:566","msg":"Reconcile error","commit":"68f2a66","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"8b353784-fe5b-499c-bc25-89afe3390bf7","knative.dev/key":"mgeorge/test-pipeline-run-w9qd2","duration":0.017773317,"error":"1 error occurred:\n\t* invalid list of done tasks; some tasks were indicated completed without ancestors being done: [set-consumer-tests-success]\n\n","stacktrace":"github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).handleErr\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:566\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:543\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).RunContext.func3\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:491"}
{"level":"info","ts":"2022-05-06T16:24:09.934Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:285","msg":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"mgeorge\", Name:\"test-pipeline-run-w9qd2\", UID:\"f91d20a5-b07a-43e0-a65b-3733b9c241f9\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"2578350\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' 1 error occurred:\n\t* invalid list of done tasks; some tasks were indicated completed without ancestors being done: [set-consumer-tests-success]\n\n","commit":"68f2a66"}
```

# Steps to Reproduce the Problem

1. Run the included issue reproduction pipleine

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.23.1
Pipeline version: v0.35.0
Triggers version: v0.19.1
Dashboard version: v0.25.0
```

test-pipeline.yaml:
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline
  namespace: mgeorge
spec:
  tasks:
    - name: get-token
      taskRef:
        name: pass-task
    - name: git-clone
      taskRef:
        name: pass-task
      runAfter:
        - get-token
    - name: run-unit-tests
      taskRef:
        name: pass-task
      runAfter:
        - set-unit-tests-pending
    - name: run-consumer-tests
      taskRef:
        name: fail-task
      runAfter:
        - set-consumer-tests-pending

    - name: set-unit-tests-pending
      taskRef:
        name: pass-task
      runAfter:
        - git-clone
    - name: set-unit-tests-success
      taskRef:
        name: pass-task
      runAfter:
        - run-unit-tests
    - name: set-consumer-tests-pending
      taskRef:
        name: pass-task
      runAfter:
        - git-clone
    - name: set-consumer-tests-success
      taskRef:
        name: pass-task
      runAfter:
        - run-consumer-tests
  finally:
    - name: pipeline-status
      taskRef:
        name: pass-task
    - name: set-unit-tests-failure
      when:
        - input: $(tasks.run-unit-tests.status)
          operator: notin
          values: ["Succeeded"]
      taskRef:
        name: pass-task
    - name: set-consumer-tests-failure
      when:
        - input: $(tasks.run-consumer-tests.status)
          operator: notin
          values: ["Succeeded"]
      taskRef:
        name: pass-task
```

pass-task.yaml
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pass-task
  namespace: mgeorge
spec:
  steps:
    - name: test-step
      image: alpine:latest
      script: |
        #!/bin/sh
        exit 0
```

fail-task.yaml
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fail-task
  namespace: mgeorge
spec:
  steps:
    - name: test-step
      image: alpine:latest
      script: |
        #!/bin/sh
        exit 1
```

**Comment by joaosilva15** [comment]
Hey, this is also happening to us. I believe the issue is in https://github.com/tektoncd/pipeline/blob/v0.35.0/pkg/reconciler/pipeline/dag/dag.go#L116 and https://github.com/tektoncd/pipeline/blob/v0.35.0/pkg/reconciler/pipelinerun/resources/pipelinerunstate.go#L627 . The done list contains the tasks that were skipped because the tasks in `runAfter` failed but that task is not visited and so the diff states that there is an error.
An example of pipeline run that fails is
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-fail-
  labels:
    type: test
spec:
  pipelineSpec:
    tasks:
    - name: fail
      taskSpec:
        steps:
        - image: bash
          name: no-fail
          script: |
            exit 1
    - name: no-fail
      runAfter:
        - fail
      taskSpec:
        steps:
        - image: bash
          name: no-fail
          script: |
            exit 0
```
Removing the `runAfter` from the second task will make the pipeline finish with an error as expected.
I can make a PR if someone points me in the right direction of how to fix it. Either change the `successfulOrSkippedDAGTasks` or the diff so that it is aware of tasks that were skipped
