### ISSUE TITLE
Matrix support is broken, `matrix` is always invalid 😅 

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#4885]
# Expected Behavior

Given the following `Pipeline` (simple adaptation from the documentation), the `Pipeline` gets created.

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: neo
spec:
  params:
  - name: persons
    type: array
    default:
    - Neo
    - Trinity
    - Morpheus
    - Tank
    - Switch
  - name: actions
    type: array
    default:
    - hello
    - bye
  tasks:
  - name: hello-people
    matrix:
    - name: person
      value: $(params.persons)
    - name: action
      value: $(params.actions)
    taskSpec:
      params:
      - name: person
        type: string
      - name: action
        type: string
      steps:
      - image: docker.io/library/bash:latest
        script: |
          echo $(params.action) $(params.person)
```

# Actual Behavior

It fails with the following message:

```
Error from server (BadRequest): error when creating "matrix.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value: parameters of type array only are allowed in matrix: spec.tasks[0].matrix[action], spec.tasks[0].matrix[person]
```

Those *parameters* are of type array though.

# Steps to Reproduce the Problem

1. Create the given `Pipeline`
2. What the error

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  devel (today's main branch)
  ```
