### ISSUE TITLE
Design: Notifications

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#49]
The work for this task is to design this feature and present one or more proposals (before implementing).

## Expected Behavior
In a many modern pipelines, we want to be able to 

Requirements:
* Must support: slack updates, email updates, github PR commenting
* Should be possible to perform different actions on failure of a task or a pipeline, or success
* Must be possible to provide required credentials/auth info

Possibly a notification could be a top level directive in both a Pipeline and a Task, e.g.:

```yaml
kind: Pipeline
...
spec:
    tasks:
        - name: unit-test-kritis
          taskRef:
              name: make
          inputSourceBindings:
              - inputName: workspace
                sourceKey: kritis
          params:
              - name: makeTarget
                value: test
          notifications:
               failure:
                   ....
               success:
                  .....
```

## Actual Behavior
In the current design, a user would have to implement this as a `Task` that knows how to report these notifications.

## Additional Info
There is some potential overlap with #27 which is about executing `Tasks` conditionally.

**Comment by pivotal-nader-ziada** [comment]
A small addition might be to add `notification.always` which will be trigger at the end irrespective of Task run.
For example: 

```
kind: Pipeline
...
spec:
    tasks:
        - name: unit-test-kritis
          taskRef:
              name: make
          inputSourceBindings:
              - inputName: workspace
                sourceKey: kritis
          params:
              - name: makeTarget
                value: test
          notifications:
               failure:
                   ....
               success:
                  .....
               always:
                  .....
```

Simple use case would updating PR/Slack with a message confirming a test run or an docker image upload.
