### ISSUE TITLE
Fully support dot in result name

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#4909]
### Feature request
[TEP-0080](https://github.com/tektoncd/community/blob/main/teps/0080-support-domainscoped-parameterresult-names.md) proposes supporting dot in param and result names but we cannot really use dot in result name for param replacement. This seems a missing feature in current code base.

### Use case

 see the example:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-results-name-dot
spec:
  pipelineSpec:
    tasks:
      - name: task1
        taskSpec:
          results:
            - name: string.results
              description: The current date in human readable format
          steps:
            - name: write-json
              image: bash:latest
              script: |
                #!/usr/bin/env bash
                echo -n "hello" | tee $(results["string.results"].path)
      - name: task2
        params:
          - name: foo
            value: "$(tasks.task1.results["string.results"])"
        taskSpec:
          params:
            - name: foo
              type: string
              default: "world"
          steps:
              - name: print-param
                image: bash:latest
                args: [
                  "echo",
                  "$(params.foo)"
                  ]


```
