### ISSUE TITLE
Fully Support results reference format in docs

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#4910]
# Expected Behavior
In [docs](https://github.com/tektoncd/pipeline/blob/main/docs/variables.md#variables-available-in-a-pipeline) we support three formats for results variable replacements but we only support `tasks.<taskName>.results.<resultName>`, not `tasks.<taskName>.results['<resultName>']` and `tasks.<taskName>.results["<resultName>"]`

# Actual Behavior
`tasks.<taskName>.results['<resultName>']` and `tasks.<taskName>.results["<resultName>"]` don't work
# Steps to Reproduce the Problem

Example:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: printdate-pipelinerun
spec:
  pipelineSpec:
    tasks:
      - name: task1
        taskSpec:
          results:
            - name: json-results
              description: The current date in human readable format
          steps:
            - name: write-json
              image: bash:latest
              script: |
                #!/usr/bin/env bash
                echo -n "hello" | tee $(results.json-results.path)
      - name: task2
        params:
          - name: foo
            value: "$(tasks.task1.results['json-results'])"
        taskSpec:
          params:
            - name: foo
              type: string
              default: "defaultparam"
          steps:
              - name: print-param
                image: bash:latest
                args: [
                  "echo",
                  "$(params.foo)"
                  ]


```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
