### ISSUE TITLE
Cannot refer array params in script

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#4912]
# Expected Behavior
Not sure if this is expected or a bug. If I want to use array params in `script` it will fail the validation webhook. But it can work in `args`

Working Example:
```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: array-with-default
spec:
  params:
    - name: array-to-echo
      value:
        - "foo"
        - "bar"
  taskSpec:
    params:
      - name: array-to-echo
        type: array
      - name: another-array-to-echo
        type: array
        default:
        - "foo-default"
        - "bar-default"
      - name: string-to-echo
        type: string
        default: "baz"
    steps:
      # this step should echo "foo bar foo-default bar-default baz"
      - name: echo-params
        image: bash:3.2
        args: [
          "echo",
          "$(params.array-to-echo[*])",
          "$(params.another-array-to-echo[*])",
          "$(params.string-to-echo)",
        ]
```

# Actual Behavior

# Steps to Reproduce the Problem
Not working:

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: array-with-default
spec:
  params:
    - name: array-to-echo
      value:
        - "foo"
        - "bar"
  taskSpec:
    params:
      - name: array-to-echo
        type: array
      - name: another-array-to-echo
        type: array
        default:
        - "foo-default"
        - "bar-default"
      - name: string-to-echo
        type: string
        default: "baz"
    steps:
      # this step should echo "foo bar foo-default bar-default baz"
      - name: echo-params
        image: bash:3.2
        script: |
          #!/bin/bash
          echo $(params.array-to-echo[*])

```

err log:

```
Error from server (BadRequest): error when creating "STDIN": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: variable type invalid in "#!/bin/bash\necho $(params.array-to-echo[*])\n": spec.taskSpec.steps[0].script
Error: error executing 'kubectl apply': exit status 1
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Client version: 0.22.0
Pipeline version: v0.35.1**
