### ISSUE TITLE
Wrong variable propagating Finally Task Results to Pipeline Results

### ISSUE THREAD

**Issue by vsinghai** [tektoncd/pipeline#4923]
# Expected Behavior

As described in the [doc](https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#cannot-configure-pipeline-result-with-finally), `Finally Task`'s can emit `Results` but they cannot be referenced in `Pipeline Result`'s - but we intend to support this using `$(finally.<finally-task-name>.results.<finally-task-result>)`. This work is tracked in this [issue](https://github.com/tektoncd/pipeline/issues/2710).

**Example**

Modified the `Pipeline` in the provided [example](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml#:~:text=workspace%20after%20done-,apiVersion%3A%20tekton.dev/v1beta1,fi,-%2D%2D%2D) as such:

```
# Pipeline to clone repo into shared workspace and cleanup the workspace after done
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-cleanup-workspace
spec:
  results:
      - name: commit
        value: $(tasks.clone-app-repo.results.commit)
      - name: initialized
        value: $(tasks.check-git-commit.results.init)
  workspaces:
    # common workspace where git repo is cloned and needs to be cleanup after done
    - name: git-source
  tasks:
    # Clone app repo to workspace
    - name: clone-app-repo
      taskRef:
        name: git-clone-from-catalog
      params:
        - name: url
          value: https://github.com/tektoncd/community.git
        - name: subdirectory
          value: application
      workspaces:
        - name: output
          workspace: git-source
  finally:
    # Cleanup workspace
    - name: cleanup
      taskRef:
        name: cleanup-workspace
      workspaces:
        - name: source
          workspace: git-source
    - name: check-git-commit
      params:
        - name: commit1
          value: $(tasks.clone-app-repo.results.commit)
      taskSpec:
        params:
          - name: commit1
        results:
          - name: init
        steps:
          - name: check-commit-initialized
            image: alpine
            script: |
              if [[ ! $(params.commit1) ]]; then
                exit 1
              fi
              printf true | tee /tekton/results/init

```

# Actual Behavior

And this was the created `PipelineRun`, with the `Finally Task`'s `Result` passed on to the `Pipeline`:

```
$ tkn pr describe -L
Name:              write-and-cleanup-workspace
Namespace:         test
Pipeline Ref:      clone-cleanup-workspace
Service Account:   default
Timeout:           1h0m0s
Labels:
 tekton.dev/pipeline=clone-cleanup-workspace

🌡️  Status

STARTED        DURATION     STATUS
1 minute ago   31 seconds   Succeeded

📝 Results

 NAME            VALUE
 ∙ commit        1312e1011d061fad481446e99c869837fd94d6e0
 ∙ initialized   true

📂 Workspaces

 NAME           SUB PATH   WORKSPACE BINDING
 ∙ git-source   ---        VolumeClaimTemplate

🗂  Taskruns

 NAME                                             TASK NAME          STARTED          DURATION     STATUS
 ∙ write-and-cleanup-workspace-cleanup            cleanup            45 seconds ago   7 seconds    Succeeded
 ∙ write-and-cleanup-workspace-check-git-commit   check-git-commit   45 seconds ago   8 seconds    Succeeded
 ∙ write-and-cleanup-workspace-clone-app-repo     clone-app-repo     1 minute ago     23 seconds   Succeeded
```
Note that `initialized` is true, when in fact the validation should fail. The unintended behavior is that the variable referencing `initialized` uses `tasks` as a prefix rather than `finally`. Related feature request [here](https://github.com/tektoncd/pipeline/issues/2710).

# Steps to Reproduce the Problem

1. Modify the `Pipeline` in the provided [example](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml#:~:text=workspace%20after%20done-,apiVersion%3A%20tekton.dev/v1beta1,fi,-%2D%2D%2D) with the code pasted above
2. Run the following commands:
 - `kubectl apply -f pipelinerun-with-final-tasks.yaml`
 -  `tkn pr describe -L`

# Additional Info

- Kubernetes version:

```
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.21.11-gke.1100
```

- Tekton Pipeline version:
```
Client version: 0.23.1
Pipeline version: v0.35.0
```
