### ISSUE TITLE
`v1beta1` has changed to require results have `type: something` in `0.36.0`

### ISSUE THREAD

**Issue by 06kellyjac** [tektoncd/pipeline#4925]
# Expected Behavior

`v1beta1` should behave the same no matter what release version of pipelines

`v1beta2` should be created if it's necessary to change the validation behavior etc

# Actual Behavior

```
2022/06/01 12:01:30 invalid value: : spec.results[0].type
type must be string
```

# Steps to Reproduce the Problem

this was validating fine before on `github.com/tektoncd/pipeline v0.34.1`:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: name
spec:
  results:
    - name: RESULT
  steps:
    - name: image-1
      image: image-1
      script: |
        echo hi

```

now on `github.com/tektoncd/pipeline v0.36.0` it must be:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: name
spec:
  results:
    - name: RESULT
      type: string
  steps:
    - name: image-1
      image: image-1
      script: |
        echo hi

```
