### ISSUE TITLE
How does Tekton behave if OOM(Out of Memory)?

### ISSUE THREAD

**Issue by austinzhao-go** [tektoncd/pipeline#4930]
As being discussed from [TEP-0104: Support Task-level Compute Resource Requirements](https://github.com/tektoncd/community/pull/703), an interesting question will be - how does Tekton behave if the used memory is out of the specified limit in runtime?

K8s will monitor and kill the OOM container while marking it as `OOMKilled` for status, as [ref](https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#exceed-a-container-s-memory-limit). Will Tekton have the same behaviour and mark an OOM `TaskRun` as `failed/OOMKilled`?

After digging into details, this answer is 
- Yes, `TaskRun` will be marked as `Failed` with 2 diff error msgs for cases “OOM during Pod Initialization” and “OOM during Pod Running”
- No/But, not marked as `OOMKilled` and not with specific messages to point out the cause as “OOMKilled”

This `TaskRun` template was used for testing:
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: hello
      image: alpine
      script: |
         ${oom-scripts}
      resources:
        limits:
          memory: ${limit}
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: hello-taskrun-
spec:
  taskRef:
    name: hello
```

### OOM Reproducing
**OOM during Pod Initialization**
Configured as:
${oom-scripts}=
```bash
#!/bin/sh
echo "Hello World
```
${limit}=`4Mi`

This setting should be not enough to pull the image and complete the Pod Initialization stage. 

`TaskRun` status as:
```bash
❯ tkn taskrun describe hello-taskrun-5wkvn
Name:              hello-taskrun-5wkvn
Namespace:         default
Task Ref:          hello
Service Account:   default
Timeout:           1h0m0s
Labels:
 app.kubernetes.io/managed-by=tekton-pipelines
 tekton.dev/task=hello

🌡️  Status

STARTED          DURATION     STATUS
51 seconds ago   16 seconds   Failed

Message

build failed for unspecified reasons.

🦶 Steps

 NAME      STATUS
 ∙ hello   PodInitializing
```

**OOM during Pod Running**
Configured as:
${oom-scripts}=
```bash
#!/bin/sh
</dev/zero head -c $((1024**3*2)) | tail #this line will fill 2GiB memory
```
${limit}=`500Mi`

This config will cause the OOM as the required `2GiB`  > `500MiB`

```bash
❯ tkn taskrun describe hello-taskrun-v7tjw
Name:              hello-taskrun-v7tjw
Namespace:         default
Task Ref:          hello
Service Account:   default
Timeout:           1h0m0s
Labels:
 app.kubernetes.io/managed-by=tekton-pipelines
 tekton.dev/task=hello

🌡️  Status

STARTED      DURATION     STATUS
1 hour ago   13 seconds   Failed

Message

"step-hello" exited with code 137 (image: "docker-pullable://alpine@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c"); for logs run: kubectl -n default logs hello-taskrun-v7tjw-pod -c step-hello


🦶 Steps

 NAME      STATUS
 ∙ hello   OOMKilled
```

cc @lbernick @dibyom
