### ISSUE TITLE
Git Clone unsafe repository

### ISSUE THREAD

**Issue by aceeric** [tektoncd/pipeline#4966]
# Expected Behavior
Using Pipelines 0.36.0, Create a `TaskRun` to git clone a  repository results in success

# Actual Behavior
Fails with error: `Exit status 128 fatal // Unsafe repository ('/workspace/output' is owned by someone else) // To add an exception for this directory, call: git config --global --add safe.directory /workspace/output`

# Additional info
Based on https://github.com/tektoncd/pipeline/pull/4756 being merged in April and 0.36.0 being cut in June, I thought this would be resolved in 0.36.0.

# Steps to Reproduce the Problem

1. Install Tekton Pipelines 0.36.0: `kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.36.0/release.yaml`
2. Get this manifest - https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.6/git-clone.yaml - and change both occurrences of "0.29.0" to "0.36.0". Then `kubectl apply` the manifest
3. Create a `TaskRun` with this manifest, following guidance [here](https://github.com/tektoncd/catalog/tree/main/task/git-clone/0.6#running-as-a-non-root-user) to run as non-root
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: git-clone-run-brancch
spec:
  podTemplate:
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
  workspaces:
  - name: output
    emptyDir: {}
  - name: ssh-directory
    secret:
      secretName: tekton-ssh
      items:
      - key: ssh-privatekey
        path: id_rsa
  taskRef:
    name: git-clone
  params:
  - name: url
    value: git@gitlab.our.co/myproj/foo.git
  - name: revision
    value: main
  - name: sslVerify:
    value: false
  - name: userHome
    value: /home/nonroot
```
Observe the `TaskRun` fails with error:

```
Exit status 128 fatal:
unsafe repository ('/workspace/output') is owned by someone else
To add an exception for this directory, call: git config --global --add safe.directory /workspace/output
```
