### ISSUE TITLE
Tekton finally task pending for ever

### ISSUE THREAD

**Issue by darkprisco** [tektoncd/pipeline#5058]
Hi all, 
 I am trying to use the finally task in case of failures, having something like this: 

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-that-fail
spec:
  params:
        <SOME PARAMETERS HERE>
  workspaces:
    - name: pipeline-pvc
  
  tasks:

    # I am simulating a fialure on this task 
    - name: simulate-failure
      runAfter: [clone-ci-cd]
      taskRef:
        name: task-that-fails
      params:
        <SOME PARAMETERS HERE>
      workspaces:
        - name: task-pvc
          workspace: pipeline-pvc

  finally:
    - name: open-incident
      when:
        - input: $(tasks.simulate-failure.status)
          operator: in
          values: ["Failed"]
      taskRef:
        name: task-open-incident
      params:
        - name: setenv-file
          value: ".setenv"
        - name: environment
          value: $(params.environment)
        - name: problem
          value: "Backup"
      workspaces:
        - name: task-pvc
          workspace: pipeline-pvc
```
instead the task definition is:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-open-incident
spec:
  params:
        <SOME PARAMETERS HERE>
  workspaces:
    - name: task-pvc
      mountPath: /artifacts
  steps:
    - name: open-incident
      image: pipeline-base-image:latest
      env:
        - name: WORKSPACE
          value: "/artifacts"
        - name: SETENV_FILE
          value: $(params.setenv-file)
        - name: ENVIRONMENT
          value: $(params.environment)
        - name: PROBLEM
          value: $(params.problem)
        - name: UID
          value: "TEST"
        - name: TEKTON_PIPELINE_ID
          value: "TEST"
      workingDir: /artifacts
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "STARTING task-open-incident.yaml..."

          set -eo pipefail
          
          echo WORKSPACE IS $WORKSPACE 

          source "$WORKSPACE/$SETENV_FILE"

          echo "task-open-incident STARTING..."
          echo "task-open-incident ENTRY - Environment: ${ENVIRONMENT}"

```

What is happening is that the previous simple task which is triggered once the **simulate-failure** fails (as expected)  is never returning and the task is always running eve if the pipeline seems failed.
I am not able neither to understand what is going on in the pod where the task should be running.
Is there something very bad with such kind of definition that is causing this issue?
Sometimes it seems going on, other times no... 

The tekton version I am using is the **0.36.0**, while the **k8s** version is: **v1.23.8**
