### ISSUE TITLE
Projected volumes as workspaces

### ISSUE THREAD

**Issue by 0xFelix** [tektoncd/pipeline#5075]
### Feature request

Support kubernetes projected volumes (https://kubernetes.io/docs/concepts/storage/projected-volumes/) as workspace type.

### Use case

By using projected volumes a user could pass an arbitrary amount of ConfigMaps or Secrets to a PipelineRun/TaskRun without modifying the actual Task/ClusterTask.

In kubevirt-tekton-tasks we have tasks to [customize](https://github.com/kubevirt/kubevirt-tekton-tasks/tree/main/tasks/disk-virt-customize)/[sysprep](https://github.com/kubevirt/kubevirt-tekton-tasks/tree/main/tasks/disk-virt-sysprep) VM images, where this would allow to pass data in a flexible way. The user could pass multiple ConfigMaps or Secrets to the task, which would also allow to split and reuse them in several tasks.

```
spec:
 workspaces:
   - name: my-customization-data
     projected:
       sources:
        - secret:
            name: my-secrets
        - configMap:
            name: my-configs-1
        - configMap:
            name: my-configs-2
```
