### ISSUE TITLE
Document and design the relationship with Knative Serving

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#509]
## Expected Behavior
There should be a clear story designed and documented about the relationship between pipelines and serving. Pipelines aims to replace build, so we should have use cases and examples documented about how pipelines can be used to create revisions to be used in k-services.

In the source-to-url example (https://github.com/knative/docs/tree/master/serving/samples/source-to-url-go) the knative services uses a `build` to generate the image that is going to be used to run the service. That `build` could be a `pipeline` (or `pipelinerun` actually), but there's no definition about what the interface is between a `pipeline` and a the `revisionTemplate`; there should be examples about this is meant to be used for instance in a real CI/CD environment.
 

## Actual Behavior
There's no documentation about this apart from https://github.com/knative/docs/tree/master/serving/samples/source-to-url-go. From the last meeting I got the impression that this is not really decided / fleshed out yet, it would be good to have this discussion in the community, perhaps on the mailing list.

## Steps to Reproduce the Problem
N/A

**Comment by bobcatfish** [comment]
Related: proposal re. moving knative/build-pipelines https://github.com/knative/build/pull/569

**Comment by vdemeester** [comment]
@afrittoli I think we should be able to close this now. The relationship with Knative Serving is now the same as any other "deployment" system (standard kubernetes services, …). We should document those in their respective task in the catalog :angel: 

/close

**Comment by afrittoli** [comment]
@vdemeester While Knative can be just an extra deployment system, there is an extra relationship, that is tekton pipelineruns can be used in Knative Serving spec via duck typing, e.g.:

```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: withTekton
spec:
  runLatest:
    configuration:
      build:
        apiVersion: tekton.dev/v1alpha1
        kind: TaskRun
        metadata:
        spec:
          taskRef:
            name: source-to-image
          inputs:
            resources:
              - name: workspace
                resourceRef:
                  name: git-resource
            params:
              - name: pathToContext
                value: images/foobar
              - name: imageTag
                value: latest
              - name: dockerIgnoreFile
                value: images/api/.dockerignore
          outputs:
            resources:
              - name: builtImage
                resourceRef:
                  name: myimage
      revisionTemplate:  # template for building Revision
        spec:
          container:
            image: us.icr.io/andreaf/myimage:latest
            imagePullPolicy: Always
            ports:
              - name: http1
                containerPort: 80
                protocol: TCP
            readinessProbe:
              httpGet:
                path: /status
            livenessProbe:
              httpGet:
                path: /status
```
