### ISSUE TITLE
Results doesn't work on Windows

### ISSUE THREAD

**Issue by wilstdu** [tektoncd/pipeline#5102]
Hey, I'm not able to reference results from the task on Windows nodes, in Linux it works without any problems.

- Tekton Pipeline version:
v0.35.1

- Pipeline definition:
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: results-win
  labels:
    framework: tekton-framework
spec:
  tasks:
  - name: get-commit-hash
    taskSpec:
      results:
      - name: commit-hash
      steps:
      - image: "mcr.microsoft.com/windows/servercore:1809"
        name: doit
        script: |
          #!win powershell.exe -File
          "Dummy message" | Out-File -FilePath $(results.commit-hash.path)

  - name: print-commit-hash
    params:
      - name: hash
        value: $(tasks.get-commit-hash.results.commit-hash)
    taskSpec:
      params:
        - name: hash
          type: string
      steps:
      - image: "mcr.microsoft.com/windows/servercore:1809"
        name: doit
        script: |
          #!win powershell.exe -File
          Write $(params.hash)
    runAfter:
    - get-commit-hash
```
Getting this error in PipelineRun:
![image](https://user-images.githubusercontent.com/40565212/177793112-b532a174-13cc-4af4-a85f-ed4ae2463411.png)

`Results` documentation (https://tekton.dev/docs/pipelines/tasks/#emitting-results) states that results files are created in hardcoded /tekton/results directory, which won't work in Windows. 

Am I doing something wrong, or this is actually a bug?
