### ISSUE TITLE
[FR] Specifying compute resources on Pipeline Tasks

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5110]
### Feature request

Example:

```
kind: Pipeline
spec:
  tasks:
  - name: build
    taskRef:
      name: build-go
    resources:
      limits:
         cpu: 100m
         memory: 128Mi
      requests:
         cpu: 100m
         memory: 128Mi
```

### Use case

Spin-off from #4080. In [OpenDevStack](https://github.com/opendevstack/ods-pipeline/blob/master/docs/ods-configuration.adoc#pipeline), the user is responsible for configuring Pipeline Tasks, and the platform automatically injects some additional starting/finally tasks and creates PipelineRuns. From @michaelsauter "We have been thinking to simply create PipelineRuns instead of Pipelines from our config file, in order to move into the "runtime", but the downside of that is that e.g. grouping of runs in the UI is lost (we're using the OpenShift console)."

### Design principles thoughts

Compute resources are definitely a ["runtime" concept instead of an "authoring time" concept](https://github.com/tektoncd/community/blob/main/design-principles.md#reusability), but there's some precedent for including runtime concepts in PipelineTasks: e.g. [timeout](https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#configuring-the-failure-timeout).

### Implementation thoughts

**One way to implement this feature** would be to support parameterization of resource requirements in Tasks (the original request in #4080). This would allow a Task's resource requirements to be defined in a Pipeline. For example:

```
kind: Task
metadata:
  name: mytask
spec:
  params:
  - name: cpu-request
  - name: memory-request
     steps:
     - name: step-1
        resources:
          requests:
            cpu: $(params.cpu-request)
            memory: $(params.memory-request)
```

```
kind: Pipeline
spec:
  params:
  - name: cpu-request
     value: 100m
  - name: memory-request
     value: 200Mi
  tasks:
  - name: mytask
    taskRef:
      name: mytask
    params:
    - name: cpu-request
       value: $(params.cpu-request)
    - name: memory-request
       value: $(params.memory-request)
```

I don't think this is a good idea long term, because I think we should move away from a model where compute resources are specified on Tasks (they should be specified in TaskRuns and PipelineRuns instead, and Pipelines if we choose to implement this FR). However, parameterizing Task compute resource requirements could address the use case in the short term.

**A different way to implement this feature** would be to just add these fields to our API, as in the first example above. I personally feel this would be a better solution. If we go this route, it's probably a good idea to wait until #4470 is implemented and we have feedback on it.

**Comment by michaelsauter** [comment]
Thanks for opening this!

We were discussing this again internally, and we came out of that discussion one step closer to "let's switch to PipelineRuns". There are other things that can be done with PipelineRuns that can't be done with Pipelines, such as [inline task specs](https://github.com/tektoncd/pipeline/blob/release-v0.35.x/examples/v1beta1/pipelineruns/pipelinerun-with-pipelinespec-and-taskspec.yaml). So we're wondering if we would just fight against a design choice if we continue to go with the pipeline approach.

On top, viewing the config file in the Git repo as the "pipeline definition" feels "right". We only really use the Pipeline CRD to have a grouping mechanism in the UI. Since most people probably navigate straight from the CI build status to the PipelineRun, it may not be so bad if we loose the grouping in the UI. Plus, one can still filter runs by label, which is more cumbersome, but still OK.

All in all, it looks like this is becoming less critical for us, but #4235 (for pipeline runs) is still very high on our "wish list" :)

**Comment by lbernick** [comment]
Good to know! Just FYI-- I am wondering if our upcoming [pipelines in pipelines](https://github.com/tektoncd/community/blob/main/teps/0056-pipelines-in-pipelines.md) feature will help with your use case? Your users could define Pipelines, and they could be used as sub-Pipelines within Pipelines you create.

**Comment by BlueCog** [comment]
Hey @lbernick your wish (parameterization of resource requirements in Tasks) seems still inpossible. Did you our your team have any solution and/or workaround for this in the meantime?

**Comment by lbernick** [comment]
Compute resource requirements can't be parameterized, but they can be specified in TaskRuns at [the task level](https://github.com/tektoncd/pipeline/blob/main/docs/compute-resources.md#task-level-compute-resources-configuration) or the [step/sidecar level](https://github.com/tektoncd/pipeline/blob/main/docs/taskruns.md#overriding-task-steps-and-sidecars). They can also be specified in pipelinerun.spec.taskrunspecs.

**Comment by BlueCog** [comment]
> Compute resource requirements can't be parameterized, but they can be specified in TaskRuns at [the task level](https://github.com/tektoncd/pipeline/blob/main/docs/compute-resources.md#task-level-compute-resources-configuration) or the [step/sidecar level](https://github.com/tektoncd/pipeline/blob/main/docs/taskruns.md#overriding-task-steps-and-sidecars). They can also be specified in pipelinerun.spec.taskrunspecs.

Thanks for the quick reply! Yeah we doing that now. But i'd like to parameterize so that we could be more flexible. A trigger from Repo X needs a bigger resource (for a specific task) then a trigger from repo Y for example.

**Comment by lbernick** [comment]
> I'd like to parameterize so that we could be more flexible. A trigger from Repo X needs a bigger resource (for a specific task) then a trigger from repo Y for example.

Can you try this?

```
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: foo
spec:
  params:
  - name: cpu
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    spec:
      computeResources:
        requests:
           cpu: $(tt.params.cpu)
```

A TriggerTemplate's `resourceTemplates` can be arbitrary strings and should get substituted with the values of the trigger template params (unlike a `task.spec.step.computeresources`, which disallows `$(params.foo)` syntax). (I was able to create this triggertemplate but haven't tried running it yet)
