### ISSUE TITLE
Windows node volume not detaching when multiple workspaces are used

### ISSUE THREAD

**Issue by edvinysz** [tektoncd/pipeline#5135]
# Expected Behavior

Task that uses multiple shared workspaces, after pipeline run, removes the attached volumes from the windows node.

# Actual Behavior

The attached volumes are left after the pipeline has finished working (does not matter if failed/success)

# Steps to Reproduce the Problem

1. Have windows node and affinity assistant enabled
2. Create Pipeline run with shared workspace like so: 
```
workspaces: 
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        storageClassName: aws-windows
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
              storage: 1Gi
```
3. Create pipeline with task that uses two workspaces like so: 
```
        workspaces:
        - name: source
          workspace: shared-workspace
        - name: output
          workspace: shared-workspace
```
5. Run the pipeline.
6. After the run, log in to AWS or directly to the windows node. In AWS volume is stuck in detaching mode, in Windows it just shows that volumes are attached and working as expected.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
```
 Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

 ```
v0.35.1
 ```

**This does not reproduce if we run the pipeline with only one workspace specified in the pipeline.**
Windows does not show any interesting logs in event viewer. (Volume Signature collision BUT it shows the same when running one workspace and it mounts/removes volumes just fine)

Only option to remove the stuck volumes manually from AWS, because if left, it bubbles up and windows volume mounting speed is greatly impact (for example: clean node runs some task in 3min, after ~20 stuck volumes the same task runs ~30min or more)
