### ISSUE TITLE
Unable to use array parameter substitution in pipeline

### ISSUE THREAD

**Issue by pietervincken** [tektoncd/pipeline#5149]
# Expected Behavior

Array parameters can be used in order to pass lists to pipelines and tasks. Since v0.36.0 this behaviour seems broken and prevents the usage of array parameters in pipelines. 

# Actual Behavior

When using array parameter substitution the following error is thrown: 

`invalid input params for task task-name: param types don't match the user-specified type: [array-variable-name]`

# Steps to Reproduce the Problem

1. Create a pipeline that uses an array parameter and passes it down as described [here](https://tekton.dev/docs/pipelines/pipelines/#specifying-parameters) 
2. Create a task that uses parameter substitution as described [here](https://tekton.dev/docs/pipelines/tasks/#substituting-array-parameters) 
3. Perform a pipeline, with or without a value for the array, even with a default in the pipeline, it will fail. 

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"5a97ee6d15525f6e4a1c2646bf1dfd2ebd5220b5", GitTreeState:"clean", BuildDate:"2022-06-15T04:26:33Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

Pipeline version: v0.36.0 and v0.37.2 (confirmed on both)

Potentially related: 
- https://github.com/tektoncd/catalog/pull/992
- https://github.com/tektoncd/pipeline/pull/4845

## Pipeline example

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline
  labels:
    name: test-pipeline
spec:
  params:
    - name: additional-parameters
      type: array
      default: []

  tasks:
    - name: test-pipeline
      taskRef:
        name: test-pipelines
      params:
        - name: additional-parameters
          value: ["$(params.additional-parameters[*])"]
```

## Pipeline run 
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-pipeline-run
spec:
  pipelineRef:
    name: test-pipeline
  params:
    - name: additional-parameters
      value:
        - "test"
```

**Comment by pietervincken** [comment]
Hi @Yongxuanzhang 

I used the exact same example as you did, but without the action params in the pipelinerun. That results in the issue. If the additional-parameters isn't specified, it should default to []. I get the error `invalid input params for task array-issue-task: param types don't match the user-specified type: [additional-parameters]`

**Comment by pietervincken** [comment]
Using 
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-pipeline-run
spec:
  pipelineRef:
    name: test-pipeline
  params:
    - name: additional-parameters
      value: []
```

or

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-pipeline-run
spec:
  pipelineRef:
    name: test-pipeline
```

triggers the behavior
