### ISSUE TITLE
TEP-0114: Custom Tasks Beta - References and Specifications

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#5154]
In [TEP-0114: Custom Tasks Beta][tep-0114], we proposed migrating `Custom Tasks` and `Runs` to beta. This issue tracks this API changes to references and specifications in `Custom Tasks` and `Runs`.

Today, [embedded specs][runs-spec-docs] are in `Run.Spec.Spec`. In [TEP-0114: Custom Tasks Beta][tep-0114], we agreed to align the embedded specs with the rest of the API such that it's `CustomRun.Spec.CustomSpec`.

  ```yaml
  # before
  apiVersion: tekton.dev/v1alpha1
  kind: Run
  metadata:
    name: run-with-spec
  spec:
    spec:
      apiVersion: example.dev/v1alpha1
      kind: Example
      spec:
        field1: value1
        field2: value2
  # after
  apiVersion: tekton.dev/v1beta1
  kind: CustomRun
  metadata:
    name: customrun-with-spec
  spec:
    customSpec:
      apiVersion: example.dev/v1beta1
      kind: Example
      spec:
        field1: value1
        field2: value2
  ```

Today, [references][runs-spec-docs] are in `Run.Spec.Ref`. In [TEP-0114: Custom Tasks Beta][tep-0114], we agreed to align the references with the rest of the API such that it's `CustomRun.Spec.CustomRef`.

  ```yaml
  # before
  apiVersion: tekton.dev/v1alpha1
  kind: Run
  metadata:
    name: run-with-reference
  spec:
    ref:
      apiVersion: example.dev/v1alpha1
      kind: Example
      name: my-example
  ---
  # after
  apiVersion: tekton.dev/v1beta1
  kind: CustomRun
  metadata:
    name: customrun-with-reference
  spec:
    customRef:
      apiVersion: example.dev/v1beta1
      kind: Example
      name: my-customtask
  ```

Note that the API for `TaskRuns` and `PipelineRuns` is:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-with-ref
spec:
  pipelineRef:
    name: my-pipeline
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-with-reference
spec:
  taskRef:
    name: my-task
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-with-spec
spec:
  pipelineSpec:
    params:
      - name: param1
    tasks:
      - name: my-task
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-with-spec
spec:
  taskSpec:
    params:
      - name: param1
    steps:
      - name: my-step
```

[wg-notes]: https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#bookmark=id.8o3u0xfwrgy4
[5005]: https://github.com/tektoncd/pipeline/pull/5005
[runs-spec-docs]: https://github.com/tektoncd/pipeline/blob/main/docs/runs.md#2-specifying-the-target-custom-task-by-embedding-its-spec
[tep-0114]: https://github.com/tektoncd/community/blob/main/teps/0114-custom-tasks-beta.md
