### ISSUE TITLE
Custom controller behaviour with no retries support

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#5182]
### Feature request

In [TEP-69: Support retries for custom task in a pipeline](https://github.com/tektoncd/community/pull/491), the cases where the custom controller 
does not support retries have not been clarified. 
Hence this issue is addressed to track down the cases and to seek for improvement on the user experience.

Follow up of #4686 

### Use case

To produce the case:
 - Create a Custom Task with the `retries` field
 - Try running it with a controller that does not support `retries`
 - Fail the Custom Task and record the output/ behaviour

### Supports of concepts

```
The concern is how a user would know that the custom task controller doesn't support retries -- it may be surprising or confusing to users, maybe documentation or tooling can address this
```
_Originally posted by @jerop in https://github.com/tektoncd/community/pull/491#pullrequestreview-759994087_

cc @lbernick @jerop 

### References:
- Implementation PR: https://github.com/tektoncd/pipeline/pull/4327
- Design PR https://github.com/tektoncd/community/pull/491

**Comment by JeromeJu** [comment]
###Cases:
- Succeeded
   - Succeeded after 10s wait time
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
 name: custom-task-pipeline
 namespace: foo
spec:
 tasks:
 - name: wait-tasks
   retries: 2
   taskRef:
     apiVersion: example.dev/v0
     kind: Wait
   params:
     - name: duration
       value: 10s
```
