### ISSUE TITLE
k3d + tekton. No such host 

### ISSUE THREAD

**Issue by marniks7** [tektoncd/pipeline#5225]
# Expected Behavior
TaskRun should NOT fail when docker image executed without `command` with private artifactory
# Actual Behavior
TaskRun fails
```
failed to create task run pod "test1-run-zgnhb": translating TaskSpec to Pod: Get "https://artifactory.company.com:17064/v2/": dial tcp: lookup artifactory.company.com on 10.43.0.10:53: no such host. Maybe missing or invalid Task default/test1'
```
# Steps to Reproduce the Problem

1. Install k3d https://k3d.io/v5.4.4/#installation
2. See script below. Change ` artifactory.company.com:17064` to your company proxy
3. Run
```
k3d cluster create
kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
kubectl rollout status deployment -n tekton-pipelines tekton-pipelines-controller
kubectl rollout status deployment -n tekton-pipelines tekton-pipelines-webhook

echo '
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  steps:
    - name: step
      image: artifactory.company.com:17064/hashicorp/http-echo:alpine
      args: [ "-text=test"]
' | kubectl apply -f -
echo '
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: test-run-
spec:
  taskRef:
    name: test
' | kubectl create -f -
```

# Additional Info

- Kubernetes version:
 ```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+k3s1", GitCommit:"53f2d4e7d80c09a7db1858e3f4e7ddfa13256c45", GitTreeState:"clean", BuildDate:"2022-06-27T21:48:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.23) exceeds the supported minor version skew of +/-1
  ```

- Tekton Pipeline version:
  **v0.38.0**

Note,  with `command` it works fine
```
echo '
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test2
spec:
  steps:
    - name: step
      image: artifactory.company.com:17064/hashicorp/http-echo:alpine
      command: [ "echo" ]
      args: [ "-text=test"]
' | kubectl apply -f -
echo '
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: test-run-
spec:
  taskRef:
    name: test2
' | kubectl create -f -
```
