### ISSUE TITLE
Question: Is it possible to not use default LimitRange values in pipelines

### ISSUE THREAD

**Issue by chabeezy** [tektoncd/pipeline#5230]
At my org we have very small default values for LimitRange. Default request is 40Mi, Default Limit is 180Mi. Our none default limit is 2Gi which is closer to what I need (running a set of tests in the pipeline). 

I can't find anyway to use the none default limit in tasks. I thought it might be possible to set an overarching limit for the pipeline, but it doesn't appear to be the case.

If I set the memory on a task higher than the default limit, but under the overall limit the task will crash with the following error

```
[spec.containers[0].resources.requests: Invalid value: "300Mi": must be less than or equal to memory limit, spec.containers[1].resources.requests: Invalid value: "300Mi": must be less than or equal to memory limit].
```

Is there no way to use the none default limit with Tekton?

**Comment by lbernick** [comment]
Hi @chabeezy, thanks for filing! The behavior you want here should already be possible. Could you please provide the limitrange spec and task spec you're using, plus the tekton version? (no need to provide the entire task spec, just anywhere you specify compute resources)

**Comment by chabeezy** [comment]
Thanks @lbernick, no problem

So the task spec

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
 ...
spec:
params:
...
  steps:
    - env:
        - name: CI
          value: 'true'
      image: $(params.IMAGE)
      name: run-tests
      resources:
        requests:
          cpu: 300m
          memory: 500Mi
      script: |
        npm ci
        npm run lint-check
        npm run prettier-check
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
  workspaces:
    - name: source
```

The limitrange is set on the namespace and is 


```
kind: LimitRange
apiVersion: v1
metadata:
...
  managedFields:
    - manager: Go-http-client
      ...
    - manager: helm-operator
      ...
spec:
  limits:
    - type: Pod
      max:
        cpu: '2'
        memory: 3Gi
      min:
        cpu: 20m
        memory: 6Mi
    - type: Container
      max:
        cpu: '2'
        memory: 3Gi
      min:
        cpu: 20m
        memory: 4Mi
      default:
        cpu: 300m
        memory: 180Mi
      defaultRequest:
        cpu: 50m
        memory: 40Mi
      maxLimitRequestRatio:
        cpu: '20'
```
