### ISSUE TITLE
docker-build task fails with exec format error

### ISSUE THREAD

**Issue by TomHart** [tektoncd/pipeline#5233]
# Expected Behavior
Able to build a docker image

# Actual Behavior
Fails to run
`docker-build` step fails with
```
2022/07/28 16:45:50 Error executing command: fork/exec /tekton/scripts/script-0-6znlv: exec format error
```

# Steps to Reproduce the Problem

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: v1.24.1
  Kustomize Version: v4.5.4
  Server Version: v1.24.3+k3s1
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  v0.38.0
  ```

Pipeline YAML
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
    name: docker-build-push
    namespace: tekton-pipelines
spec:
    description: |
        This pipeline clones a git repo, builds a docker file, and pushed the image to a registry.
    params:
        -   name: repo-url
            type: string
            description: The git repo URL to clone from.
        -   name: image-name
            type: string
            description: The name of the docker image to build including tag
    workspaces:
        -   name: shared-data
            description: |
                This workspace contains the cloned repo files, so they can be read by the
                next task.
        -   name: git-credentials
            description: SSH credentials
    tasks:
        -   name: fetch-source
            taskRef:
                name: git-clone
            workspaces:
                -   name: output
                    workspace: shared-data
                -   name: ssh-directory
                    workspace: git-credentials
            params:
                -   name: url
                    value: $(params.repo-url)

        -   name: build-and-push
            runAfter: [ "fetch-source" ]
            taskRef:
                name: docker-build
            workspaces:
                -   name: source
                    workspace: shared-data
            params:
                -   name: image
                    value: $(params.image-name)
```
Pipeline Run YAML
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
    name: my-app-name
    namespace: tekton-pipelines
spec:
    pipelineRef:
        name: docker-build-push
    workspaces:
        -   name: shared-data
            volumeClaimTemplate:
                spec:
                    accessModes:
                        - ReadWriteOnce
                    resources:
                        requests:
                            storage: 256Mi
        -   name: git-credentials
            secret:
                secretName: git-credentials
    params:
        -   name: repo-url
            value: git@github.com:my_repo.git
        -   name: image-name
            value: my.personal.registry/test-app:tekton
```
