### ISSUE TITLE
Timeout: missing logs

### ISSUE THREAD

**Issue by wilstdu** [tektoncd/pipeline#5251]
# Actual Behavior
After Tekton timeout, application pods get deleted and in result the logs also disappear.
![image](https://user-images.githubusercontent.com/40565212/182314493-fb357315-39d6-43e7-90b5-cadaa5012c3d.png)

# Steps to Reproduce the Problem
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-timeout
spec:
  tasks:
  - name: do-it
    taskSpec:
      steps:
      - image: ubuntu
        script: |
          #!/usr/bin/env bash

          echo "Before sleep"
          sleep 36000
          echo "Post sleep"

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: produce-timeout
  labels:
    framework: tekton-framework
spec:
  timeouts:
    pipeline: "0h0m60s"
    tasks: "0h0m40s"
    finally: "0h0m20s"
  pipelineRef:
    name: tekton-timeout
```

# Additional Info
- Kubernetes version: 1.21
- Tekton Pipeline version: v0.35.1

**Comment by AlanGreene** [comment]
I believe this is expected behaviour, and the docs should be updated to make this clear.

From the [docs on TaskRun timeout](https://tekton.dev/docs/pipelines/taskruns/#configuring-the-failure-timeout):
> If a TaskRun runs longer than its timeout value, the pod associated with the TaskRun will be deleted. This means that the logs of the TaskRun are not preserved.

The corresponding docs for Pipeline / PipelineRun do not mention this fact but I believe the same behaviour is expected.

**Comment by vdemeester** [comment]
/remove-lifecycle stale

I need to rework : https://github.com/tektoncd/pipeline/pull/5401 in order to fix this.

**Comment by marniks7** [comment]
Hi, 
Interested in this fix... otherwise it is impossible to analyze what happened before timeout.
Simple reproduce pipelineRun:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: fast-pipeline-
spec:
  timeouts:
    pipeline: "40s"
  pipelineSpec:
    tasks:
      - name: sleep
        taskSpec:
          steps:
            - name: sleep
              image: bash
              script: |
                sleep 50
                echo "after sleep 50"
                sleep 10
                echo "after sleep 10"
```
