### ISSUE TITLE
Compose multiple Pipeline workspaces into a single Task workspace

### ISSUE THREAD

**Issue by ben-galusha** [tektoncd/pipeline#5315]
### Feature request

Add the ability to compose multiple Pipeline workspaces into a single Task workspace. The new workspace would essentially be an emptyDir + subdirectories for each workspace.

### Use case

A taskRef is expecting a single workspace to be provided, but that data exists within multiple workspaces in my Pipeline. For example, one workspace contains data loaded from a ConfigMap and another contains data from a PVC.

Another use case is a taskRef that expects N configurations to be provided within a single workspace (for example, a set of [service bindings](https://github.com/servicebinding/spec#example-directory-structure), each in its own directory). This could be accomplished using a `projected` volume that maps a bunch of Secrets & ConfigMaps into my workspace, but `projected` volumes have other problems:

* They cannot map PVCs
* The root of the volume remains read-only, even if it's empty
* Each key of a ConfigMap or Secret must be explicitly enumerated (At least in all the examples I can find). This is unlike a regular Secret/ConfigMap workspace binding inside of a PipelineRun, which includes the entire contents of the Secret/ConfigMap. This is important for scenarios where the Secret/ConfigMap may contain arbitrary keys.

### Example
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  workspaces:
  - name: foo-workspace
    description: A workspace containing foo.txt, mounted from a ConfigMap
  - name: bar-workspace
    description: A workspace containing bar.txt, mounted from a PVC
  tasks:
  - name: my-task 
    taskRef:
      name: my-taskref
    workspaces:
    - name: config
      workspaces:
      - name: foo-workspace
        mountPath: config1
      - name: bar-workspace
        mountPath: config2
```
In this example, `my-task` expects a single workspace `config`, which is formed by combining two workspaces. In the end, `my-taskref` sees this:
```
<workspace>/config1/foo.txt
<workspace>/config2/bar.txt
```
