### ISSUE TITLE
An error occurs when `stepTemplate` and `steps` contain the same env key

### ISSUE THREAD

**Issue by cugykw** [tektoncd/pipeline#5334]
# Expected Behavior

When stepTemplate and steps contain the same env key, they are finally merged into the env in steps

# Actual Behavior

An error occurs when `stepTemplate` and `steps` contain the same env key, and one is of type value and the other is of type valueFrom. 

The error is as follows:

``` 
    message: 'failed to create task run pod "xxx":
      Pod "xxxt" is invalid:
      spec.containers[0].env[4].valueFrom: Invalid value: "": may not be specified
      when `value` is not empty. Maybe invalid TaskSpec'
```

# Steps to Reproduce the Problem
Create the following pipeline and trigger it to run

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test
  namespace: test
spec:
  tasks:
  - name: xxx
    taskSpec:
      metadata: {}
      params:
      - name: test
        type: string
      stepTemplate:
        env:
        - name: test
          value: A
        imagePullPolicy: Always
        name: ""
        resources: {}
      steps:
      - env:
        - name: test
          valueFrom:
            secretKeyRef:
              key: secret-A
              name: key
        image: xxxx
        name: xx
        resources: {}
        script: sleep 1000
```

# Additional Info

- Kubernetes version:

kubernetes: 1.21.3

- Tekton Pipeline version:

pipeline version: 0.30.0
