### ISSUE TITLE
is command field always required for task?

### ISSUE THREAD

**Issue by hillbun** [tektoncd/pipeline#5392]
I create a task without command field:

```
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: xxxxxx
spec:
  steps:
    - name: xxxxxx
      image: harbor.xxxxx.com/xxxxxx/xxxxxx:v2.0.0
  workspaces:
    - name: ws
```

but I get error for taskrun

```
Status:
  Completion Time:  2022-08-30T03:33:10Z
  Conditions:
    Last Transition Time:  2022-08-30T03:33:10Z
    Message:               failed to create task run pod "gitlab-pipelinerun-zgtn4-xxxxx-task": translating TaskSpec to Pod: Get "https://harbor.xxxxx.com/v2/": x509: certificate signed by unknown authority. Maybe missing or invalid Task default/xxxxxx
```

follwing task with script filed works well:

```
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: xxxxxx
spec:
  steps:
    - name: xxxxxx
      image: harbor.xxxxxx.com/xxxxxx/xxxxxx:v2.0.0
      script: |
        #!/usr/bin/env bash
        echo "Hello from xxxxxx!"
  workspaces:
    - name: ws
```

**Comment by hillbun** [comment]
or with command field is ok

```
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: xxxxxx
spec:
  steps:
    - name: xxxxxx
      image: harbor.xxxxxx.com/xxxxxx/xxxxxx:v2.0.0
      command: ["echo", "xxxxx"]
  workspaces:
    - name: ws
```
