### ISSUE TITLE
Variable substitution on task results in nested pipelineSpec/taskSpec

### ISSUE THREAD

**Issue by gsouzab** [tektoncd/pipeline#5404]
# Expected Behavior

The variable substitution is ignored while running a pipeline containing an inline definition of a pipeline and task. See the example on steps to reproduce.

I expected the following output for my example:
```
Result is: 05f28f2cbc22bd4eafadc34a263637cb16ef00f9
```

# Actual Behavior

I received the following output for my example:
```
Result is: $(tasks.git-clone.results.commit)
```

# Steps to Reproduce the Problem

`k create -f example.yaml`

Definition of the example:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: run-example-
spec:
  pipelineSpec:
    workspaces:
    - name: shared-data
    tasks:
      - name: git-clone
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-data
        params:
          - name: url
            value: https://github.com/tektoncd/pipeline.git
          - name: revision
            value: 05f28f2cbc22bd4eafadc34a263637cb16ef00f9
      - name: print-result
        runAfter:
          - git-clone
        taskSpec:
          steps:
          - name: echo
            image: docker.io/busybox:1.35.0@sha256:eac8ec5c7a8e387d50447e64441f31e3b289c8853655e4587087d8aed77925ca
            env:
            - name: COMMIT
              value: $(tasks.git-clone.results.commit)
            script: |
              echo "Result is: $COMMIT"
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 256Mi
```
# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

v0.39.0

**Comment by jerop** [comment]
@gsouzab results are substituted in parameters and when expressions only -- could you try passing the result through a parameter to the env var?

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: run-example-
spec:
  pipelineSpec:
    workspaces:
    - name: shared-data
    tasks:
      - name: git-clone
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-data
        params:
          - name: url
            value: https://github.com/tektoncd/pipeline.git
          - name: revision
            value: 05f28f2cbc22bd4eafadc34a263637cb16ef00f9
      - name: print-result
        params:
        - name: commit
          value:  $(tasks.git-clone.results.commit)
        taskSpec:
          params:
          - name: commit
          steps:
          - name: echo
            image: docker.io/busybox:1.35.0@sha256:eac8ec5c7a8e387d50447e64441f31e3b289c8853655e4587087d8aed77925ca
            env:
            - name: COMMIT
              value: $(params.commit)
            script: |
              echo "Result is: $COMMIT"
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 256Mi
```

**Comment by Yongxuanzhang** [comment]
Yes, another similar way is like this:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-example
spec:
  pipelineSpec:
    workspaces:
    - name: shared-data
    tasks:
      - name: git-clone
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-data
        params:
          - name: url
            value: https://github.com/tektoncd/pipeline.git
          - name: revision
            value: 05f28f2cbc22bd4eafadc34a263637cb16ef00f9
      - name: print-result
        runAfter:
          - git-clone
        params:
          - name: COMMIT
            value: $(tasks.git-clone.results.commit)
        taskSpec:
          params:
          - name: COMMIT
            default: ""
          steps:
          - name: echo
            image: docker.io/busybox:1.35.0@sha256:eac8ec5c7a8e387d50447e64441f31e3b289c8853655e4587087d8aed77925ca
            script: |
              echo "Result is: $(params.COMMIT)"
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 256Mi

```
