### ISSUE TITLE
PipelineRef resolver part doesn't support `context` variable replacement

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#5475]
# Expected Behavior

Using the following `PipelineRun` should create the following `ResolutionRequest`.

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: simple-pipelinerun
spec:
  pipelineRef:
    resolver: foo
    params:
    - name: bar
      value: $(context.pipelinerun.name)
---
apiVersion: resolution.tekton.dev/v1alpha1
kind: ResolutionRequest
metadata:
  labels:
    resolution.tekton.dev/type: foo
  name: foo-bf6f3d56876eb1d6948a50c52c0d1d87
spec:
  params:
    bar: simple-pipelinerun
```

# Actual Behavior

It doesn't *resolve* the `context.*` variable, resulting in the following `ResolutionRequest`.

```
apiVersion: resolution.tekton.dev/v1alpha1
kind: ResolutionRequest
metadata:
  labels:
    resolution.tekton.dev/type: foo
  name: foo-bf6f3d56876eb1d6948a50c52c0d1d87
spec:
  params:
    bar: $(context.pipelinerun.name)
```

# Steps to Reproduce the Problem

1. Create the above `PipelineRun`
2. See what `ResolutionRequest` it creates

# Additional Info

- Tekton Pipeline version: `main`

/assign @abayer
