### ISSUE TITLE
Add support for using multiple remote resolution Git providers in the same cluster

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#5487]
With #5450 about to merge, we're adding support for remote resolution of `Task`s and `Pipeline`s using Git providers' APIs. Which is great! But it does come with a sizable limitation - you can only have one provider type/server/token per cluster. While this is fine to start with, we really should add the ability for admins to configure multiple supported providers, so that you can use both an internal GitHub Enterprise and github.com, or any other combination of the various providers supported through go-scm.

**Comment by abayer** [comment]
I'm kicking around a couple ideas at the moment. Both revolve around having the provider configured in the `git-resolver-config` `ConfigMap` as the "default", with an optional parameter for the `git` resolver available to specify the "name" of a different provider configuration. The question, in my mind, is how to store those additional provider configurations. My current ideas:

* `ConfigMap`s in the `tekton-pipelines-resolvers` namespace, containing the relevant fields from `git-resolver-config` and the unique "name" as an identifier for the provider config. For discovery of these `ConfigMap`s, I'm thinking requiring a label, like `resolution.tekton.dev/git-provider-config: "true"`. Then the resolver will use watches to load/update those configurations into a map keyed on the "name".
* A new CRD, something like `ResolutionGitProvider`, with instances of the CRD also living in the `tekton-pipelines-resolvers` namespace. This would also have the config fields from `git-resolver-config`, albeit as actual fields rather than map keys, with the `name` of the instance being used as the identifier. Again, they'd be loaded up via watches.

The `ConfigMap` approach is probably the right one, but I just really like the CRD approach - less things to document (key names, the required label, etc), and it just feels nice? I'm giving myself a week or two to come back to this and see how I feel about the options then.

**Comment by chuangw6** [comment]
> ConfigMaps in the tekton-pipelines-resolvers namespace, containing the relevant fields from git-resolver-config and the unique "name" as an identifier for the provider config.

Agreed that this is probably the good path to explore. Depending on what is best for the users, we might want to consider how to reuse `api-token-secret-name` that could store the tokens for different providers in a single secret under different `api-token-secret-key`. wdyt?

**Comment by abayer** [comment]
Ok, I ran into some walls with the config map approach - namely, how to know when a new provider's config map has been added so we can add it to the config map watch. I've prototyped a new approach:

Rather than put the provider-specific information in different config maps, instead the user would add new keys to the existing configmap, formatted like `provider.(provider name).(key name)`. So for a provider we call `banana`, the git resolver config map would look like this:

```
metadata:
  name: git-resolver-config
  namespace: tekton-pipelines-resolvers

data:
  default-revision: master
  fetch-timeout: 1m

  scm-type: gitlab
  api-token-secret-key: default-token
  api-token-secret-name: default-token-secret
  api-token-secret-namespace: default-namespace

  provider.banana.api-token-secret-key: banana-token
  provider.banana.api-token-secret-name: banana-token-secret
  provider.banana.api-token-secret-namespace: banana-namespace
  provider.banana.scm-type: github
  provider.banana.server-url: https://private.github.internal
```

This is obviously a wee bit hacky - it's a workaround for configmaps just being `map[string]string`. When a `git` `ResolutionRequest` comes in with a `providerName` parameter, we'll look for `provider.[providerName].[key]` values, erroring if we can't find the required ones (token secret name and key, scm type). If no `providerName` is given, we'll fall back to the "global"/"default" configuration.

I have this passing unit tests correctly, so while I haven't tested it end to end, I'm very confident that it'll work just fine there. Buuuut I'm not nearly sure this is actually the right way to go - I just got frustrated with the configmap detection etc and decided to see how much work this approach would take. Turns out, it did not take much work at all.

cc @vdemeester - I'd appreciate your thoughts.
