### ISSUE TITLE
TaskRun fails with folder already exists error

### ISSUE THREAD

**Issue by R2wenD2** [tektoncd/pipeline#5497]
Scenario: A single task using a shared workspace to share data between steps in the task, clones a repo onto the workspace in the first step, and in a subsequent step uses a subdir of the repo as a workingdir. This causes the clone to fail since the dir already exists.

We do this in a single task because Tekton Chains doesn't support Pipeline level provenance so we need to keep steps in the same task in order to generate complete provenance.

Error Logs:
```2022/09/14 08:07:21 Entrypoint initialization
2022/09/14 08:07:24 Decoded script /tekton/scripts/script-4-h66wt
2022/09/14 08:07:24 Decoded script /tekton/scripts/script-5-9zvfz
fatal: destination path 'Pillow' already exists and is not an empty directory.

**Comment by chitrangpatel** [comment]
I think I was able to recreate this issue with the following yaml:
```yaml
apiVersion: tekton.dev/v1beta1 
kind: TaskRun                  
metadata:
  generateName: steps-run-in-order-
spec:
  workspaces:                  
    - name: my-workspace
      emptyDir: {}
  taskSpec:
    workspaces:
      - name: my-workspace     
    steps:
    - image: ubuntu
      script: |
        mkdir $(workspaces.my-workspace.path)/subdir
        echo "hello" > $(workspaces.my-workspace.path)/subdir/hi.txt
    - image: ubuntu
      workingDir: /workspace/my-workspace/subdir
      script: |
       cat $(workspaces.my-workspace.path)/subdir/hi.txt 
```

In my case, I was getting the following error:
```
 mkdir: cannot create directory '/workspace/my-workspace/subdir': File exists  
```
