### ISSUE TITLE
Dynamic Input Parameters

### ISSUE THREAD

**Issue by warrenbailey** [tektoncd/pipeline#552]
## Expected Behavior
I'm building a release pipeline for one of our projects and ideally I want to pass a dynamically created value between two tasks. I want the first task to generate the 'release version' and do the git tags etc. Then the second tasks (which is Kaniko) to build the image and push it to the docker registry with the released version from the first task as a tag.

I know it's possible to have input parameters but the value of these need to be defined upfront in the pipeline run files but in this scenario they are not known at that point. I also had a look at pipeline resources but the only thing a task seems to be able to output is an image or file. It would be great if it could output a variable.

## Actual Behavior
None - new feature suggestion

## Steps to Reproduce the Problem

1. Create a Task that writes generates info required for a future task, e.g. this Task will write a version value to a file as json (this is a detail of the design and open to change)

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-version
spec:
  inputs:
    resources:
      params:
      - name: currentVersion
        description: The current version as just a single number for this trivial example
  outputs:
    resources:
    - name: version
      type: keyValue # also a detail of the design and open to change
  steps:
  - name: write-new-num
    image: ubuntu
    command:
    - /bin/bash
    args:
    - -c
    - "echo \"{ \\"version\\": $((5 + 3)) }\" > /workspace/version/keyvalue" 
```

2. Create another Task that uses that value

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-version
spec:
  inputs:
    resources:
    - name: version
      type: keyValue
  outputs:
  steps:
  - name: echo-version
    image: ubuntu
    command:
    - echo
    args:
    - "${inputs.resources.version.version}" # also a design detail open to change
```

3. Link them together in a Pipeline:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  resources:
  - name: version-key-value
    type: keyvalue
  tasks:
  - name: make-version
    taskRef:
      name: create-version
    params:
    - name: currentVersion
      value: 5
    resources:
      outputs:
      - name: version
        resource: version-key-value
  - name: output-the-version
    taskRef:
      name: echo-version
    resources:
      inputs:
      - name: version
        resource: version-key-value
        from: [make-version]
```

4. Create a PipelineRun to run the Pipeline
5. The goal would be that the first Task could generate a Version which could be echoed by the next one

## Additional Info
Related to functionality needed for #216
