### ISSUE TITLE
Taskrun not working with volumeClaimTemplate

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/pipeline#5537]
# Expected Behavior

Taskrun Should Work

# Actual Behavior

Taskrun is throwing an error

```
task task-with-workspace has failed: failed to create task run pod "task-with-workspace-run-j622l": Pod "task-with-workspace-run-j622l-pod" is invalid: [spec.volumes[10].name: Required value, spec.containers[0].volumeMounts[0].name: Required value, spec.containers[0].volumeMounts[0].name: Not found: ""]. Maybe missing or invalid Task tekton-pipelines/task-with-workspace
Error: pod for taskrun task-with-workspace-run-j622l not available yet
```

# Steps to Reproduce the Problem

1. Create a task

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-with-workspace
spec:
  steps:
  - name: list-files
    image: ubuntu
    script: ls $(workspaces.read-allowed.path)
  workspaces:
  - name: read-allowed
```

2. Create taskrun

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: task-with-workspace-run-
spec:
  taskRef:
    kind: Task
    name: task-with-workspace
  workspaces:
    - name: read-allowed
      volumeClaimTemplate:
        metadata:
          name: pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          volumeMode: Filesystem
```

3. See the taskrun getting failed.

# Additional Info

- Kubernetes version:

```
  kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-14T19:49:27Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0+3882f8f", GitCommit:"0a57f1f59bda75ea2cf13d9f3b4ac5d202134f2d", GitTreeState:"clean", BuildDate:"2022-09-13T15:03:52Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.26.0
Pipeline version: v0.40.0
```

It is working fine with pipeline 0.39 but not with pipeline 0.40. It is a regression.
