### ISSUE TITLE
`serviceAccount` is not a valid `EventListener.spec.triggers` attribute

### ISSUE THREAD

**Issue by Elkasitu** [tektoncd/pipeline#5546]
# Expected Behavior

According to the tekton docs [1] one can define, for each individual trigger in an `EventListener`'s spec, a `serviceAccount` object from a different namespace in multi-tenant scenarios.

The following `EventListener` definition should work:

```
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: foo
  namespace: foo
spec:
  serviceAccountName: pipeline
  triggers:
    - name: build-trigger
      serviceAccount:
        name: pipeline
        namespace: bar
      bindings:
        - kind: TriggerBinding
          ref: foo-binding
      template:
        ref: foo-template
```

When created/applied on the target namespace

`$ oc create -f my-el.yml`

# Actual Behavior

The server replies back with the following error message:

```
Error from server (BadRequest): error when creating "my-el.yaml": admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "serviceAccount"
```

# Steps to Reproduce the Problem

1. Create an `EventListener` definition that uses `EventListener.spec.triggers.serviceAccount`
2. Create/Apply the resource on a namespace
3. Get error message from server

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: 4.9.18
  Kubernetes Version: v1.22.8+9e95cb9
  ```

- Tekton Pipeline version: Not sure, but I think 0.6.1

Running on Red Hat OpenShift 4.9, I assume using an operator but I don't manage the cluster so I don't actually know, I'm just a tenant.

[1] https://tekton.dev/vault/triggers-v0.6.1/eventlisteners/#triggers
