### ISSUE TITLE
Add configuration types for built-in resolvers in ResolverRef

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#5549]
I keep thinking that it may make sense to eventually add real fields (with relevant structs) to `ResolverRef` for the built-in resolvers, so that you can just do 
```
pipelineRef:
  git:
    org: foo
    repo: bar
    revision: main
    pathInRepo: a/b/c.yaml
```

Rather than the more elaborate generic params approach of
```
pipelineRef:
  resolver: git
  params:
  - name: org
    value: foo
  - name: repo
     value: bar
  - name: revision
     value: main
  - name: pathInRepo
    value: a/b/c.yaml
```

We could only support the `git: ...` syntax for built-in resolvers, but for those, we'd be able to do admission control-time validation, a simpler syntax, `PipelineRun`-wide defaults, etc.

So `ResolverRef` would change from:
```
type ResolverRef struct {
	Resolver ResolverName `json:"resolver,omitempty"`
	Params []Param `json:"params,omitempty"`
}
```

to:

```
type ResolverRef struct {
	Resolver ResolverName `json:"resolver,omitempty"`
	Params []Param `json:"params,omitempty"`

	Git     *GitResolverConfig     `json:"git,omitempty"`
	Bundle  *BundlesResolverConfig `json:"bundle,omitempty"`
	Cluster *ClusterResolverConfig `json:"cluster,omitempty"`
	Hub     *HubResolverConfig     `json:"hub,omitempty"`
}        
```

With these new structs:
```
type GitResolverConfig struct {
	Org        string `json:"org,omitempty"`
	Repo       string `json:"repo,omitempty"`
	URL        string `json:"url,omitempty"`
	PathInRepo string `json:"pathInRepo,omitempty"`
	Revision   string `json:"revision,omitempty"`
}

type BundlesResolverConfig struct {
	ServiceAccount string `json:"serviceAccount,omitempty"`
	Bundle         string `json:"bundle,omitempty"`
	Name           string `json:"name,omitempty"`
	Kind           string `json:"kind,omitempty"`
}

type ClusterResolverConfig struct {
	Name      string `json:"name,omitempty"`
	Kind      string `json:"kind,omitempty"`
	Namespace string `json:"namespace,omitempty"`
}

type HubResolverConfig struct {
	Name    string `json:"name,omitempty"`
	Kind    string `json:"kind,omitempty"`
	Version string `json:"version,omitempty"`
	Catalog string `json:"catalog,omitempty"`
}
```

The current `resolver: git` + `params: ...` would still work for the built-in resolvers, and would be how third-party resolvers need to be used. At runtime, `GetPipelineFunc` and `GetTaskFunc` would know about these new config types, and would be able to produce a `ResolutionRequest` for a ref using one of them that would be identical to a `ResolutionRequest` created for a ref using the full `params` syntax.

(oh, and we get the `pipelineRef.git` in this scenario because `PipelineRef` and `TaskRef` both inline `ResolverRef`)

/kind feature
