### ISSUE TITLE
tekton-resource-pruner: no image found in manifest list for architecture arm64

### ISSUE THREAD

**Issue by T0MASD** [tektoncd/pipeline#5568]
# Expected Behavior

image for tekton-resource-pruner available on arm64 architecture 

# Actual Behavior

```
 Failed to pull image "gcr.io/tekton-releases/dogfooding/tkn@sha256:025de221fb059ca24a3b2d988889ea34bce48dc76c0cf0d6b4499edb8c21325f": rpc error: code = Unknown desc = choosing image instance: no image found in manifest list for architecture arm64, variant "v8", OS linux
```

# Additional Info

Tekton operator installed via: `kubectl apply -f https://storage.googleapis.com/tekton-releases/operator/latest/release.yaml`

- Kubernetes version:

```
clientVersion:
  buildDate: "2022-08-18T00:00:00Z"
  compiler: gc
  gitCommit: 95ee5ab382d64cfe6c28967f36b53970b8374491
  gitTreeState: archive
  gitVersion: v1.24.4
  goVersion: go1.18.5
  major: "1"
  minor: "24"
  platform: linux/arm64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-09-21T13:12:04Z"
  compiler: gc
  gitCommit: b39bf148cd654599a52e867485c02c4f9d28b312
  gitTreeState: clean
  gitVersion: v1.24.6
  goVersion: go1.18.6
  major: "1"
  minor: "24"
  platform: linux/arm64
```

- Tekton Pipeline version:

  **v0.40.0**
