### ISSUE TITLE
get step index or step name inside container

### ISSUE THREAD

**Issue by LilyHolms** [tektoncd/pipeline#5592]
### Feature request

I noticed we can get pipeline name, task name inside a container. (https://tekton.dev/docs/pipelines/variables/)
Is it possible to get step name or step index inside a container?

**Comment by LilyHolms** [comment]
for example, with following script, I can set task name and namespace as environment variables, and use them inside my container.  
Is there a way to do the same for step name or step index?

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-name
spec:
  steps:
    - name: step-name
      env:
        - name: TASK_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          value: metadata.namespace
      image:  myimage:latest
      script: |
        #!/bin/sh
        echo $TASK_NAME
        echo $NAMESPACE
```
