### ISSUE TITLE
`context.task.retry-count` returns value zero all the time

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/pipeline#5594]
# Expected Behavior
`context.task.retry-count` should give the actual retry count value

# Actual Behavior
`context.task.retry-count` returns value zero all the time

# Steps to Reproduce the Problem

1. Create a Pipeline as described in [this section](https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#using-the-retries-and-retry-count-variable-substitutions)
2. Start the pipeline and observe the logs of pipelinerun

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: v1.24.6
  Kustomize Version: v4.5.4
  Server Version: v1.24.0+3882f8f
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
```
  tkn version                                                                                                                                                            ✔  11:06:19 AM 
  Client version: 0.24.0
  Pipeline version: v0.37.4
  Triggers version: v0.20.2
  Operator version: v0.60.1
```

**Comment by pritidesai** [comment]
thank you @VeereshAradhya for reporting this issue 👍 

What API version are you running with, `v1beta1`? I am a little surprised since we have an [example](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/using-retries-and-retry-count-variables.yaml) which validates this context variable. Do you observe `$(context.pipelineTask.retries)` set to zero as well? otherwise this example should fail the CI, right? 🤔

**Comment by VeereshAradhya** [comment]
@pritidesai I tried the given [example](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/using-retries-and-retry-count-variables.yaml) and observed that the `"$(context.task.retry-count)"` works fine in the embedded spec that the  [example](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/using-retries-and-retry-count-variables.yaml) contains but fails when we create task and pipeline separately. 
I am attaching the task and pipeline yaml files
Task:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: retry-task-bug
spec:
  params:
    - name: pipelineTask-retries
    - name: pipelineTask-retry-count
      default: "$(context.task.retry-count)"
  steps:
    - name: retry-me
      image: alpine:3.12.0
      script: |
        #!/usr/bin/env sh
        if [ "$(params.pipelineTask-retry-count)" == "$(params.pipelineTask-retries)" ]; then
          echo "This is the last retry."
          exit 0;
        fi
        echo "The PipelineTask has retried $(context.task.retry-count) times."
        echo "pipelineTask-retries = $(params.pipelineTask-retries)" 
        exit 1
```
Pipeline:
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: retry-pipeline-bug
spec:
  tasks:
    - name: retry-task-bug
      params:
        - name: pipelineTask-retries
          value: "$(context.pipelineTask.retries)"
      taskRef:
        name: retry-task-bug
      retries: 5
```

**Comment by chengjoey** [comment]
@VeereshAradhya  do you mean task and pipelinerun like this:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: retry-task-bug
spec:
  params:
    - name: pipelineTask-retries
      default: "$(context.pipelineTask.retries)"
    - name: pipelineTask-retry-count
      default: "$(context.task.retry-count)"
  steps:
    - name: retry-me
      image: alpine:3.12.0
      script: |
        #!/usr/bin/env sh
        if [ "$(params.pipelineTask-retry-count)" == "$(params.pipelineTask-retries)" ]; then
          echo "This is the last retry."
          exit 0;
        fi
        echo "The PipelineTask has retried $(context.task.retry-count) times."
        echo "pipelineTask-retries = $(params.pipelineTask-retries)" 
        exit 1
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: retry-pipeline-bug
spec:
  pipelineSpec:
    tasks:
      - name: retry-tasks
        retries: 5
        taskRef:
          name: retry-task-bug
```

## get results
pods:
```
NAME                                        READY   STATUS   RESTARTS   AGE
retry-pipeline-bug-retry-tasks-pod          0/1     Error    0          5m11s
retry-pipeline-bug-retry-tasks-pod-retry1   0/1     Error    0          5m6s
retry-pipeline-bug-retry-tasks-pod-retry2   0/1     Error    0          5m1s
retry-pipeline-bug-retry-tasks-pod-retry3   0/1     Error    0          4m55s
retry-pipeline-bug-retry-tasks-pod-retry4   0/1     Error    0          4m50s
retry-pipeline-bug-retry-tasks-pod-retry5   0/1     Error    0          4m45s
```

kubectl logs retry-pipeline-bug-retry-tasks-pod-retry5 -c step-retry-me:
```
/tekton/scripts/script-0-72rw8: line 2: context.pipelineTask.retries: not found
The PipelineTask has retried 0 times.
pipelineTask-retries =
/tekton/scripts/script-0-72rw8: line 7: context.pipelineTask.retries: not found
```

**Comment by VeereshAradhya** [comment]
@chengjoey Sorry for the delayed response. You are trying to access a [pipeline variable](https://github.com/tektoncd/pipeline/blob/main/docs/variables.md#variables-available-in-a-pipeline) (`"$(context.task.retry-count)"`) inside a task definition, it does not if it is not an embedded spec. 
You can reproduce the issue by creating the task and pipeline from the spec that I provided and use the below pipelinerun spec to start the pipelinerun 
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: retry-pipeline-bug-run-
spec:
  pipelineRef:
    name: retry-pipeline-bug
```

**Comment by maruiz93** [comment]
I faced this same issue, can we reopen it?

**Comment by scoheb** [comment]
I am able to reproduce the same issue when NOT using an embedded spec

consider:

```
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: test-plr
spec:
  PipelineRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/scoheb/test-retries
      - name: revision
        value: main
      - name: pathInRepo
        value: pipeline.yaml
```

and 

```
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: test-pipeline
spec:
  tasks:
    - name: echo
      retries: 20
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/scoheb/test-retries
          - name: revision
            value: main
          - name: pathInRepo
            value: echo-task.yaml
      params:
        - name: pipelineTask-retries
          value: "$(context.pipelineTask.retries)"
        - name: pipelineTask-retry-count
          value: "$(context.task.retry-count)"
```

with 

```
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: echo
spec:
  params:
    - name: pipelineTask-retries
    - name: pipelineTask-retry-count
  steps:
    - name: collect-data
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
          #!/usr/bin/env sh
          if [ "$(params.pipelineTask-retry-count)" == "$(params.pipelineTask-retries)" ]; then
            echo "This is the last retry."
            exit 0;
          fi
          echo "The PipelineTask has retried $(context.task.retry-count) times."
          exit 1
```

it never succeeds
