### ISSUE TITLE
Is it possible to bind a workspace from within a Pipeline (not a PipelineRun) or create a PipelineRun with bound workspaces using GUI?

### ISSUE THREAD

**Issue by kamieniarzk** [tektoncd/pipeline#5635]
First of all, pardon me if it's not the right place for such questions but I've struggled to find the answer in the documentation and did not find any other community forums related to tekton.

I'd like to be able to start my pipeline which uses two workspaces using the Tekton dashboard (GUI) but from what I can see, there is no option to provide workspaces here. 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/MWFKM.png

The only two options of creating a `PipelineRun` with bound workspaces I can think of are to either: 

 - Create it programmatically and apply using either `kubectl` or `tekton-cli`
 - Create a `TriggerTemplate` with bound workspaces and run the pipeline by a webhook to an `EventListener`

My main problem is both of those options require the developer to go through a very non-user-friendly process. Ideally, I'd like to run the pipelines with bound workspaces from tekton GUI. Can this be somehow achieved?
I've tried providing the binding in the `workspaces` section of the `Pipeline` definition as below:
```
  workspaces:
    - name: source-dir
      persistentVolumeClaim:
        claimName: gradle-cache-pvc
    - name: ssh-creds
      secret:
        secretName: ssh-key-secret
```
But I got an error saying persistentVolumeClaim field is not allowed.
