### ISSUE TITLE
PipelineRun reconciler shouldn't care about how the `Timeout` field is implemented in Custom Task Run. 

### ISSUE THREAD

**Issue by XinruZhang** [tektoncd/pipeline#5653]
PipelineRun reconciler shouldn't care about how the Timeout field is implemented in Custom Task Run.

Currently in PipelineRun reconciler, it cancells the Run when it detects that Run is TimeOut: https://github.com/tektoncd/pipeline/blob/2b54123eaafe5d6b86577402830e0957928374d2/pkg/reconciler/pipelinerun/pipelinerun.go#L657-L659
by calling https://github.com/tektoncd/pipeline/blob/2b54123eaafe5d6b86577402830e0957928374d2/pkg/apis/pipeline/v1alpha1/run_types.go#L230-L241

This behavior leads to flaky unit test results now and then. See the test result of `TestWaitCustomTask_PipelineRun/Wait_Task_Retries_on_Timeout` in 
- https://storage.googleapis.com/tekton-prow/pr-logs/pull/tektoncd_pipeline/5547/pull-tekton-pipeline-alpha-integration-tests/1574802170165858304/build-log.txt
- https://storage.googleapis.com/tekton-prow/pr-logs/pull/tektoncd_pipeline/5648/pull-tekton-pipeline-alpha-integration-tests/1582078450888347648/build-log.txt

Say we have defined the following PipelineRun
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: custom-task-pipeline
spec:
  tasks:
  - name: run-wait
    timeout: "1s"
    retries: 1
    taskRef:
      apiVersion: wait.testing.tekton.dev/v1alpha1
      kind: Wait
    params:
    - name: duration
      value: "2s"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: custom-task-pipelinerun
spec:
  pipelineRef:
    apiVersion: tekton.dev/v1beta1
    name: custom-task-pipeline
```

# Expected Behavior
1. PR reconciler creates a Run: `custom-task-pipelinerun-run-wait` https://github.com/tektoncd/pipeline/blob/8399472eda2706e5416751b74daae7af22ab75ab/pkg/reconciler/pipelinerun/pipelinerun.go#L790-L801
2. Run reconciler reconcils the Run, continues reconciling because the Run hasn't TimedOut.
3. Run reconciler detects the Run has timed out, marks it as failed on `TimedOut` after `1s`, example: https://github.com/tektoncd/pipeline/blob/8399472eda2706e5416751b74daae7af22ab75ab/test/custom-task-ctrls/wait-task/pkg/reconciler/reconciler.go#L126-L139
4. PR reconciler detects the Run is marked as `TimedOut`, update its `ChildReferences` or `RunsStatus`: https://github.com/tektoncd/pipeline/blob/8399472eda2706e5416751b74daae7af22ab75ab/pkg/reconciler/pipelinerun/pipelinerun.go#L684-L691

# Actual Behavior
1. PR reconciler creates a Run: `custom-task-pipelinerun-run-wait` https://github.com/tektoncd/pipeline/blob/8399472eda2706e5416751b74daae7af22ab75ab/pkg/reconciler/pipelinerun/pipelinerun.go#L790-L801
2. Run reconciler reconcils the Run, continues reconciling because the Run hasn't TimedOut.
3. **[The flaky part]** PR reconciler `processRunTimeouts` https://github.com/tektoncd/pipeline/blob/2b54123eaafe5d6b86577402830e0957928374d2/pkg/reconciler/pipelinerun/pipelinerun.go#L657-L659 at this time, **The Run has TimedOut, but the Run reconciler hasn't update the Run's status yet**, then PR reconciler tries to cancel the Run https://github.com/tektoncd/pipeline/blob/2b54123eaafe5d6b86577402830e0957928374d2/pkg/reconciler/pipelinerun/pipelinerun.go#L718-L725
