### ISSUE TITLE
Resources for Tasks with many images in the same registry are repetitive

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#569]
# Expected Behavior

If I'm creating a `Task` that needs to build a lot of images, that means I need to provide many [image resources](https://github.com/knative/build-pipeline/blob/master/docs/resources.md#image-resource). If these all need to get pushed to the same image registry, it would be great if I only needed to provide this information once.

# Actual Behavior

While working on #528 I started to create a `Task` that can publish all the images required for this project. There are a lot of them tho and so what I've currently got is something like this:

```yaml
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: entrypoint-image
spec:
  type: image
  params:
   - name: url
     value: gcr.io/christiewilson-catfactory/entrypoint # Replace this with your own image registry
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kubeconfigwriter-image
spec:
  type: image
  params:
   - name: url
     value: gcr.io/christiewilson-catfactory/kubeconfigwriter # Replace this with your own image registry
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: creds-init-image
spec:
  type: image
  params:
   - name: url
     value: gcr.io/christiewilson-catfactory/creds-init # Replace this with your own image registry
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-init-image
spec:
  type: image
  params:
   - name: url
     value: gcr.io/christiewilson-catfactory/git-init # Replace this with your own image registry
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: nop-image
spec:
  type: image
  params:
   - name: url
     value: gcr.io/christiewilson-catfactory/nop # Replace this with your own image registry
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: bash-image
spec:
  type: image
  params:
   - name: url
     value: gcr.io/christiewilson-catfactory/bash # Replace this with your own image registry
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: gsutil-image
spec:
  type: image
  params:
   - name: url
     value: gcr.io/christiewilson-catfactory/gsutil # Replace this with your own image registry
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: controller-image
spec:
  type: image
  params:
   - name: url
     value: gcr.io/christiewilson-catfactory/controller # Replace this with your own image registry
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: webhook-image
spec:
  type: image
  params:
   - name: url
     value: gcr.io/christiewilson-catfactory/webhook # Replace this with your own image registry
```

If someone wants to use the `Task` that consumes these with their own registry, they're going to have to change each of those `url` values.

# Additional Info

Note that these images are built using [`ko`](https://github.com/google/go-containerregistry/tree/master/cmd/ko), which doesn't take as input information about individual images, it just takes the `KO_DOCKER_REPO`
