### ISSUE TITLE
`docs/taskruns.md` misses a section for fields in status

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/pipeline#5720]
We should have a section in the [`docs/taskruns.md`](https://github.com/tektoncd/pipeline/blob/main/docs/taskruns.md#monitoring-execution-status) file to document the fields in taskrun status in detail.  What we have in [`docs/pipelineruns.md`](https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md#pipelinerun-status) is an good example.

**Comment by pritidesai** [comment]
Hey @chuangw6 @lbernick is this something we would like to pursue this?

@HamzaMateen is interested in contributing and starting to work on this doc update. Thanks!

**Comment by lbernick** [comment]
Thanks @pritidesai and @HamzaMateen, it looks like this is still not addressed so if you'd like to take this on it would be very helpful!

**Comment by pritidesai** [comment]
@HamzaMateen the ask here is to add a section [PipelineRun Status](https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md#pipelinerun-status) with one single section [The Status field](https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md#the-status-field). 

Add two sections, `Required` and `Optional`.

Required section will have very similar list of entries except `taskSpec` instead of `pipelineSpec`. Similarly for optional section, please fill in the list based on an example:

```
completionTime: '2023-08-29T21:34:37Z'
conditions:
  - lastTransitionTime: '2023-08-29T21:34:37Z'
    message: All Steps have completed executing
    reason: Succeeded
    status: 'True'
    type: Succeeded
podName: publish-catalog-tekton-wtpg9-publish-pod
provenance:
  featureFlags:
    AwaitSidecarReadiness: true
    DisableAffinityAssistant: false
    DisableCredsInit: false
    EnableAPIFields: alpha
    EnableProvenanceInStatus: true
    EnableTektonOCIBundles: true
    EnforceNonfalsifiability: ''
    MaxResultSize: 4096
    RequireGitSSHSecretKnownHosts: false
    ResultExtractionMethod: termination-message
    RunningInEnvWithInjectedSidecars: true
    ScopeWhenExpressionsToTask: false
    SendCloudEventsForRuns: false
    SetSecurityContext: false
    VerificationNoMatchPolicy: ignore
startTime: '2023-08-29T21:30:27Z'
steps:
  - container: step-publish
    imageID: gcr.io/tekton-releases/dogfooding/tkn@sha256:015bb6018d5eaf4523a775f4955c85f68077099753661941d06843d5a61a86df
    name: publish
    terminated:
      containerID: containerd://4d7821a229851cb94abae746347b3980516a0df3c41e1435657cda42f7624108
      exitCode: 0
      finishedAt: '2023-08-29T21:34:36Z'
      reason: Completed
      startedAt: '2023-08-29T21:30:34Z'
taskSpec:
  description: This task publishes each Task in a Tekton catalog as a Tekton Bundle. The catalog must be structured as a Tekton Catalog. Bundles are published to $TARGET/<task-name>:<task-version> and, when TAG is provided, to $TARGET/<task-name>:$TAG. A typical extra tag would be the git sha of the catalog repo that is being published. The task uses the "tkn bundle" command to publish, which is available in tkn starting with version v0.18.0.
  params:
    - default: gcr.io/tekton-releases/dogfooding/tkn@sha256:015bb6018d5eaf4523a775f4955c85f68077099753661941d06843d5a61a86df
      description: tkn CLI container image to run this task
      name: TKN_IMAGE
      type: string
    - description: The registry where bundles are published to
      name: REGISTRY
      type: string
    - default: tekton/catalog/tasks
      description: The path in the registry
      name: PATH
      type: string
    - default: ''
      description: An optional extra tag. If provided, tasks are tagged with it too.
      name: TAG
      type: string
  steps:
    - env:
        - name: REGISTRY
          value: gcr.io
        - name: REGISTRY_PATH
          value: tekton-releases/catalog/upstream
        - name: TAG
          value: cc481a5f26f9844123dd3d6aafda944c1c421a58
        - name: DOCKER_CONFIG_PATH
          value: /workspace/dockerconfig
      image: gcr.io/tekton-releases/dogfooding/tkn@sha256:015bb6018d5eaf4523a775f4955c85f68077099753661941d06843d5a61a86df
      name: publish
      resources: {}
      script: |
        #!/usr/bin/env sh
        set -e -o pipefail
        TARGET="${REGISTRY}"
        [ "${REGISTRY_PATH}" != "" ] && TARGET="${TARGET}/${REGISTRY_PATH}"
        # If a dockerconfig workspace was provided, set DOCKER_CONFIG to point to it
        if [ -d "$DOCKER_CONFIG_PATH" ]; then
            export DOCKER_CONFIG="${DOCKER_CONFIG_PATH}"
        fi
        find task -type f -mindepth 3 -maxdepth 3 -name '*.yaml' -o -name '*.yml'| while read -r task_version_dir; do
          FOLDER=$(dirname "$task_version_dir")
          VERSION=$(basename "$FOLDER")
          TASK=$(basename "$(dirname "$FOLDER")")
          tkn bundle push "${TARGET}/${TASK}:${VERSION}" -f "$task_version_dir"
          [ "${TAG}" != "" ] && \
            tkn bundle push "${TARGET}/${TASK}:${TAG}" -f "$task_version_dir"
          sleep 0.1
        done
        
      workingDir: /workspace/catalog
  workspaces:
    - description: A workspace that holds the catalog to be published. The catalog must be stored in the root of the workspace mount point, and is must follow the [Tetkon Catalog](https://github.com/tektoncd/catalog#catalog-structure) structure.
      name: catalog
    - description: An optional workspace that allows providing a .docker/config.json file for tkn to access the container registry. The file should be placed at the root of the Workspace with name config.json.
      name: dockerconfig
      optional: true
```

I have copied this example from https://dashboard.dogfooding.tekton.dev/#/namespaces/default/taskruns/publish-catalog-tekton-wtpg9-publish?taskRunDetails=true&view=status.

Please let me know if you have any further question. Thanks!
