### ISSUE TITLE
The pipelinerun never ends due to duplicate workspaces

### ISSUE THREAD

**Issue by cugykw** [tektoncd/pipeline#5723]
We have a pipeline of users that hasn't finished for more than a day. When we checked, we found that there was a pipeline task with duplicate workspaces. The pr never done.

``` 
NAME                                                                     SUCCEEDED   REASON    STARTTIME   COMPLETIONTIME
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  Unknown           Started       47h 
```
pr status:
```
  conditions:
  - lastTransitionTime: "2022-11-04T03:29:39Z"
    reason: Started
    status: Unknown
    type: Succeeded
```

tekton-controller error:
```
{"level":"error","ts":"2022-11-06T03:04:58.310Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:229","msg":"Reconcile error: error creating TaskRun called xxx for PipelineTask 6xxx from PipelineRun xxx: admission webhook \"validation.webhook.pipeline.tekton.dev\" denied the request: validation failed: expected exactly one, got both: spec.workspaces[1].name","commit":"d9dbdaa","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"07ee2f2e-cc08-48e4-957d-13234918ff4a","knative.dev/key":"xxx/xxx","stacktrace":"github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:229\ngithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/pipelinerun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/pipelinerun/reconciler.go:235\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220329144915-0a1ec2e0d46c/controller/controller.go:542\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220329144915-0a1ec2e0d46c/controller/controller.go:491"}
```

# Expected Behavior
1. The Pipeline creation is prohibited
2. The pipelinerun should display specific error messages, and pipelinerun should end.

# Steps to Reproduce the Problem

1. pipeline yaml:
```
...
  tasks:
  - name: xxx
    params:
    - name: url
      value: $(params.git_url)
    - name: revision
      value: $(params.revision)
    - name: subdirectory
      value: $(params.git_reponame)
    - name: branch
      value: $(params.branch)
    - name: tag
      value: $(params.tag)
    - name: pipeline_name
      value: $(context.pipeline.name)
    taskRef:
      kind: ClusterTask
      name: pull-code
    workspaces:
    - name: repo
      workspace: repo
    - name: repo
      workspace: repo
...
```
- Kubernetes version:
kubernetes: 1.21.3

- Tekton Pipeline version:
0.37.3
