### ISSUE TITLE
Remote resolution for kaniko catalog examples

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#5727]
The compatible remote resolution task referred in the catalog repo needs to be updated in  https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/pipelinerun.yaml#L39-L40.

The yaml file to reproduce:
```
# This demo modifies the cluster (deploys to it) you must use a service
# account with permission to admin the cluster (or make your default user an admin
# of the `default` namespace with default-cluster-admin.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  generateName: default-cluster-admin-
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: "unit.tests"
spec:
  workspaces:
  - name: source
    mountPath: /workspace/source/go/src/github.com/GoogleContainerTools/skaffold
  steps:
  - name: run-tests
    image: golang
    env:
    - name: GOPATH
      value: /workspace/go
    workingDir: $(workspaces.source.path)
    script: |
      # The intention behind this example Task is to run unit test, however we
      # currently do nothing to ensure that a unit test issue doesn't cause this example
      # to fail unnecessarily. In the future we could re-introduce the unit tests (since
      # we are now pinning the version of Skaffold we pull) or use Tekton Pipelines unit tests.
      echo "pass"
---
# This task deploys with kubectl apply -f <filename>
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: demo-deploy-kubectl
spec:
  params:
  - name: path
    description: Path to the manifest to apply
  - name: yqArg
    description: Okay this is a hack, but I didn't feel right hard-coding `-d1` down below
  - name: yamlPathToImage
    description: The path to the image to replace in the yaml manifest (arg to yq)
  - name: imageURL
    description: The URL of the image to deploy
  workspaces:
  - name: source
  steps:
  - name: replace-image
    image: mikefarah/yq:3
    command: ['yq']
    args:
    - "w"
    - "-i"
    - "$(params.yqArg)"
    - "$(params.path)"
    - "$(params.yamlPathToImage)"
    - "$(params.imageURL)"
  - name: run-kubectl
    image: lachlanevenson/k8s-kubectl
    command: ['kubectl']
    args:
    - 'apply'
    - '-f'
    - '$(params.path)'
---
# This Pipeline Builds two microservice images(https://github.com/GoogleContainerTools/skaffold/tree/master/examples/microservices)
# from the Skaffold repo (https://github.com/GoogleContainerTools/skaffold) and deploys them to the repo currently running Tekton Pipelines.
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: "demo.pipeline"
spec:
  params:
  - name: image-registry
    default: gcr.io/christiewilson-catfactory
  workspaces:
  - name: git-source
  tasks:
  - name: fetch-from-git
    taskRef:
      resolver: hub
      params:
        - name: type  #optional
          value: artifact
        - name: kind  #optional
          value: task
        - name: name
          value: git-clone
        - name: version
          value: "0.4"
    params:
    - name: url
      value: https://github.com/GoogleContainerTools/skaffold
    - name: revision
      value: v1.32.0
    workspaces:
    - name: output
      workspace: git-source
  - name: skaffold-unit-tests
    runAfter: [fetch-from-git]
    taskRef:
      name: "unit.tests"
    workspaces:
    - name: source
      workspace: git-source
  - name: build-skaffold-web
    runAfter: [skaffold-unit-tests]
    taskRef:
      resolver: hub
      params:
        - name: type  #optional
          value: artifact
        - name: kind  #optional
          value: task
        - name: name
          value: kaniko
        - name: version
          value: "0.6"
    params:
    - name: IMAGE
      value: $(params.image-registry)/leeroy-web
    - name: CONTEXT
      value: examples/microservices/leeroy-web
    - name: DOCKERFILE
      value: $(workspaces.source.path)/examples/microservices/leeroy-web/Dockerfile
    workspaces:
    - name: source
      workspace: git-source
  - name: build-skaffold-app
    runAfter: [skaffold-unit-tests]
    taskRef:
      resolver: hub
      params:
        - name: type  #optional
          value: artifact
        - name: kind  #optional
          value: task
        - name: name
          value: kaniko
        - name: version
          value: "0.6"
    params:
    - name: IMAGE
      value: $(params.image-registry)/leeroy-app
    - name: CONTEXT
      value: examples/microservices/leeroy-app
    - name: DOCKERFILE
      value: $(workspaces.source.path)/examples/microservices/leeroy-app/Dockerfile
    workspaces:
    - name: source
      workspace: git-source
  - name: deploy-app
    taskRef:
      name: demo-deploy-kubectl
    params:
    - name: imageURL
      value: $(params.image-registry)/leeroy-app@$(tasks.build-skaffold-app.results.IMAGE_DIGEST)
    - name: path
      value: $(workspaces.source.path)/examples/microservices/leeroy-app/kubernetes/deployment.yaml
    - name: yqArg
      value: "-d1"
    - name: yamlPathToImage
      value: "spec.template.spec.containers[0].image"
    workspaces:
    - name: source
      workspace: git-source
  - name: deploy-web
    taskRef:
      name: demo-deploy-kubectl
    params:
    - name: imageURL
      value: $(params.image-registry)/leeroy-web@$(tasks.build-skaffold-web.results.IMAGE_DIGEST)
    - name: path
      value: $(workspaces.source.path)/examples/microservices/leeroy-web/kubernetes/deployment.yaml
    - name: yqArg
      value: "-d0"
    - name: yamlPathToImage
      value: "spec.template.spec.containers[0].image"
    workspaces:
    - name: source
      workspace: git-source
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: demo-pipeline-run-1
spec:
  pipelineRef:
    name: "demo.pipeline"
  serviceAccountName: 'default'
  workspaces:
  - name: git-source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```

Error:
https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5712/pull-tekton-pipeline-alpha-integration-tests/1588181464132882432

Would it make sense to file an issue for the kaniko catalog remote resolution? That doesn't seem like an issue we'd want to ignore.

_Originally posted by @lbernick in https://github.com/tektoncd/pipeline/issues/5712#issuecomment-1305703094_
