### ISSUE TITLE
Can't parse image references for gcr.io/cloud-builders/go:debian

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#573]
# Expected Behavior

If I try to use a Task step that uses the image `gcr.io/cloud-builders/go:debian` without specifying a `command` explicitly, the controller should be able to fetch that image and determine what the command is (this is required for our [entrypoint rewriting logic](https://github.com/knative/build-pipeline/blob/master/docs/container-contract.md#entrypoint)).

# Actual Behavior

The controller fails to retrieve info about the image with this error:

```yaml
    - lastTransitionTime: "2019-03-01T18:08:37Z"
      message: 'References a Task default/publish-tekton-pipelines that doesn''t exist:  could
        not get entrypoint from registry for gcr.io/cloud-builders/go:debian: failed
        to fetch remote image gcr.io/cloud-builders/go:debian@sha256:bdc4c18aa7df622be964d1905c5ef60eac648c307105d23ee4b7dbbad5fe3e7d:
        couldn''t parse image gcr.io/cloud-builders/go:debian@sha256:bdc4c18aa7df622be964d1905c5ef60eac648c307105d23ee4b7dbbad5fe3e7d:
        could not parse reference'
      reason: CouldntGetTask

```

# Steps to Reproduce the Problem

1. Create a Task with a step that tries to use `gcr.io/cloud-builders/go:debian` without specifying a command, e.g. this example which is based on [go-containerregistry's cloudbuild.yaml](https://github.com/google/go-containerregistry/blob/master/cloudbuild.yaml) (it tries to install `ko`):

```yaml
  steps:
  - name: install-ko
    image: gcr.io/cloud-builders/go:debian
    env:
    - name: PROJECT_ROOT
      value: github.com/google/go-containerregistry
    args:
    - install
    - github.com/google/go-containerregistry/cmd/ko
```

2. Create a TaskRun that uses the above

# Additional Info
Note that in #564 @pivotal-nader-ziada is updating this logic anyway, maybe it will fix the issue? :sweat_smile:
