### ISSUE TITLE
Pipeline workspaces not accessible in embedded Tasks

### ISSUE THREAD

**Issue by dgeorgievski** [tektoncd/pipeline#5732]
# Expected Behavior
Content of Tekton Workspaces to be accessible in embedded Tasks.

Cloned github.com repo should be available through a shared workspace to Tasks subsequent to the git-clone task.
git-clone is a standalone Tektone task that clones successfully a github.com repository, and stores its content into a shared Pipeline workspace to make it available to subsequent Pipeline tasks.

Other Pipeline tasks should be able to access the contents of the shared Pipeline workspace.

# Actual Behavior
Embedded Tasks cannot access Pipeline workspaces with the following error:
```
task show-dockerfile has failed: workspace binding "source" does not match any declared workspace
```

This error doesn't occur if tasks are standalone and referred to from the Pipeline. This is the case with git-clone task.

# Steps to Reproduce the Problem
Deploy the attached Pipeline and PipelineRun. The logic of the Pipeline is simple - clone a public GitHub repository and then print into the logs the contents of the Dockerfile managed by the github repository. 
1.  kubectl create -f p-embedded.yaml
2.  kubectl create -f pr-embedded.yaml
3. tkn p logs embedded-tasks

# Additional Info

- Kubernetes version:
```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5+012e945", GitCommit:"3c28e7a79b58e78b4c1dc1ab7e5f6c6c2d3aedd3", GitTreeState:"clean", BuildDate:"2022-07-13T08:38:41Z", GoVersion:"go1.17.12", Compiler:"gc", Platform:"linux/amd64"}
```
  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:
```
Pipeline version: v0.37.4
```
  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

Logs output
```shell
 $ tkn p logs embedded-tasks
+ CHECKOUT_DIR=/workspace/output/
+ '[[' true '==' true ]]
+ cleandir
+ '[[' -d /workspace/output/ ]]
+ rm -rf /workspace/output//lost+found
+ rm -rf '/workspace/output//.[!.]*'
+ rm -rf '/workspace/output//..?*'
+ test -z
+ test -z
+ test -z
+ /ko-app/git-init -url https://github.com/stefanprodan/podinfo.git -revision  -refspec  -path /workspace/output/ '-sslVerify=true' '-submodules=true' -depth 1 -sparseCheckoutDirectories
{"level":"info","ts":1667933051.8927941,"caller":"git/git.go:169","msg":"Successfully cloned https://github.com/stefanprodan/podinfo.git @ 1cf228c67b8f8102db1a6966f81a95c09954b3e8 (grafted, HEAD) in path /workspace/output/"}
{"level":"info","ts":1667933051.9264257,"caller":"git/git.go:207","msg":"Successfully initialized and updated submodules in path /workspace/output/"}
+ cd /workspace/output/
+ git rev-parse HEAD
+ RESULT_SHA=1cf228c67b8f8102db1a6966f81a95c09954b3e8
+ EXIT_CODE=0
+ '[' 0 '!=' 0 ]
+ echo -n 1cf228c67b8f8102db1a6966f81a95c09954b3e8
+ echo -n https://github.com/stefanprodan/podinfo.git

task show-dockerfile has failed: workspace binding "source" does not match any declared workspace
```

Pipeline `p-embedded.yaml`
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: embedded-tasks
spec:
  description: | 
    This pipeline clones a git repo, then echoes the README file to the stout.
  params:
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
  workspaces:
  - name: shared-data
    description: | 
      This workspace contains the cloned repo files, so they can be read by the
      next task.
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: show-dockerfile
    runAfter: ["fetch-source"]
    taskSpec:
      steps:
        - image: docker.io/library/golang:1.18
          script: |
            cat Dockerfile
    workspaces:
    - name: source
      workspace: shared-data
 
```

PipelineRun `pr-embedded.yaml`
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: embedded-tasks-
  labels:
    pln: embedded-tasks
spec:
  pipelineRef:
    name: embedded-tasks
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
  params:
  - name: repo-url
    value: https://github.com/stefanprodan/podinfo.git
```

**Comment by vdemeester** [comment]
Hey @dgeorgievski,

The embedded task need to define the workspace as well, in the `taskSpec`. The error state that "does not match any declared workspace", which means in the *embedded* task spec, there is not "declared" workspace named `source`.

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: embedded-tasks
spec:
  description: | 
    This pipeline clones a git repo, then echoes the README file to the stout.
  params:
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
  workspaces:
  - name: shared-data
    description: | 
      This workspace contains the cloned repo files, so they can be read by the
      next task.
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: show-dockerfile
    runAfter: ["fetch-source"]
    taskSpec:
      workspaces:
        - name: source
      steps:
        - image: docker.io/library/golang:1.18
          script: |
            cat Dockerfile
    workspaces:
    - name: source
      workspace: shared-data
```

Behind the `enable-api-fields: alpha` feature-flag, there is a way to not "declare"/repeat those as documented [here](https://tekton.dev/docs/pipelines/pipelineruns/#propagated-workspaces), but it is not enabled by default.
