### ISSUE TITLE
Cannot pass params from pipelinerun inside trigger template to pipeline

### ISSUE THREAD

**Issue by simonlaw0711** [tektoncd/pipeline#5772]
# Expected Behavior
My params defined in pipelineRun inside triggerTemplate should work

# Actual Behavior
`PipelineRun tekton-pipelines parameters is missing some parameters required by Pipeline build-deploy-stage-qxtqs's parameters: PipelineRun missing parameters: [environment]`

# Steps to Reproduce the Problem

```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy-dev-template
  namespace: tekton-pipelines
spec:
  params:
  - name: buildRevision
    description: The Git commit revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-deploy-dev-
      namespace: tekton-pipelines
    spec:
      serviceAccountName: pipeline
      params:
      - name: buildRevision
        value: 'master'
      - name: appGitUrl
        value: 'link'
      - name: configGitUrl
        value: 'link'
      - name: appImage
        value: 'gcr.io/dev-playground-366808/my-app'
      - name: environment  ## I have already defined params `environment` here
        value: dev
      workspaces:
      - name: app-source
        emptyDir: {}
      - name: config-source
        emptyDir: {}
      pipelineRef:
        name: build-deploy
      resources:
        - name: source-repo
          resourceSpec:
            type: git
            params:
            - name: revision
              value: master
            - name: url
              value: url
        - name: image-source
          resourceSpec:
            type: image
            params:
              - name: url
                value: gcr.io/dev-playground-366808/my-app:$(tt.params.buildRevision)
```

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy
spec:
  resources:
    - name: source-repo
      type: git
    - name: image-source
      type: image
  params:
    - name: environment
    - name: buildRevision
      description: The revision of the build, i.e. the commit revision of the application repository
    - name: appGitUrl
      description: The application repository
    - name: configGitUrl
      description: The application config (GitOps) repository
    - name: appImage
      description: The application Docker image name
  workspaces:
  - name: app-source
  - name: config-source

```
# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8-gke.1900", GitCommit:"79209257257c051b27df67c567755783eda93353", GitTreeState:"clean", BuildDate:"2022-07-15T09:23:51Z", GoVersion:"go1.17.11b7", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
v0.29.0
