### ISSUE TITLE
result value type is not same as defined

### ISSUE THREAD

**Issue by yuzp1996** [tektoncd/pipeline#5803]
# Expected Behavior
When defining the result type as string, the result value should be a string no matter what data it contains.
# Actual Behavior
If the string data is JSON then the result type will be recognized as object and cause pipelineRun to fail.

# Steps to Reproduce the Problem

1. Deploy pipeline with the latest commit
2. Apply task pipeline and pipelineRun to cluster
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: wrong-type-result-pipeline
spec:
  tasks:
    - name: wrongtype
      taskRef:
        name: wrong-type-task
  results:
    - name: string0
      value: $(tasks.wrongtype.results.string0)
      type: string
    - name: string1
      value: $(tasks.wrongtype.results.string1)
      type: string
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wrong-type-task
spec:
  results:
    - name: string0
      type: string
    - name: string1
      type: string
  steps:
    - name: add
      image: alpine:latest
      script: |
        #!/bin/sh
        echo -n '{"key": "value"}' | tee $(results.string0.path);
        echo -n "key:value" | tee $(results.string1.path)
        # echo -n "key:value" | tee $(results.string0.path);
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: wrong-type-result-pipeline-
spec:
  pipelineRef:
    name: wrong-type-result-pipeline
```
3. Check the result
<img width="973" alt="image" src="https://user-images.githubusercontent.com/23007448/204137857-57705d3f-4d54-4b77-8cec-8f50a3e4c0a2.png">

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
Client version: 0.19.1
Pipeline version: devel
Dashboard version: v0.30.0
```
Deploy with latest commit b3e4f35712f on branch main
