### ISSUE TITLE
CPU and Memory sources are not specified for tekton-pipelines-controller

### ISSUE THREAD

**Issue by marniks7** [tektoncd/pipeline#5848]
# Expected Behavior
for deploment of tekton-pipelines-controller I would expect to see some preconfigured memory and cpu requests and limits
e.g.
```yaml
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
```
# Actual Behavior
there are no requests or limits configured.

for me LimitRanger plugin set memory limit to 80m and tekton-pipelines-controller was crashing by OOMKiller by kubernetes

# Steps to Reproduce the Problem

1. Open https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.42.0/release.yaml
2. search for `Deployment` with `name: tekton-pipelines-controller`
3. check "resources" section, it is absent

# Additional Info
- Tekton Pipeline version:
v0.42.0
