### ISSUE TITLE
TaskRunValidationFailed for string result that could also be an array

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/pipeline#5857]
# Expected Behavior

Emitting a string result that happens to be an array should work (e.g. result value `[]`)

# Actual Behavior

The TaskRun fails with `TaskRunValidationFailed` and `missmatched Types for these results, map[result-a:[string string]]`

# Steps to Reproduce the Problem

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: result-issue-
spec:
  taskSpec:
    results:
      - name: result-a
        type: string
    steps:
      - name: write-array
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          echo -n "[]" | tee $(results.result-a.path)
```
# Additional Info

- Tekton Pipeline version: `v0.42.0` with `enable-api-fields: stable`

Thanks, Fabian
