### ISSUE TITLE
Support `Array` and `Strings` for Matrix param validation

### ISSUE THREAD

**Issue by nschad** [tektoncd/pipeline#5925]
Hey,

Currently validation for the `matrix` alpha feature is partly done in this code:

```go
func validateParametersInTaskMatrix(matrix *Matrix) (errs *apis.FieldError) {
	if matrix != nil {
		for _, param := range matrix.Params {
			if param.Value.Type != ParamTypeArray {
				errs = errs.Also(apis.ErrInvalidValue("parameters of type array only are allowed in matrix", "").ViaFieldKey("matrix", param.Name))
			}
		}
	}
	return errs
}
```

Unfortunately this doesn't yet support passing in Tekton `Arrays` as kubernetes type `String` as described here in [TEP-0090](https://github.com/tektoncd/community/blob/main/teps/0090-matrix.md#specifying-results-in-the-matrix)

For example the following is not currently supported

```yaml
tasks:
...
- name: task-5
  taskRef:
    name: task-5
  matrix:
  - name: values
    value: (tasks.task-4.results.foo) # array
```

Err:
```
for: "pipeline/pipeline-test.yaml": error when patching "pipeline/pipeline-test.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value: parameters of type array only are allowed in matrix: spec.tasks[1].matrix[k8s-versions], spec.tasks[1].matrix[machine-versions]
```

Is that something that is being worked on?
