### ISSUE TITLE
Separating "tekton-pipelines" and "tekton-pipelines-resolvers" manifests.

### ISSUE THREAD

**Issue by michaelsatish** [tektoncd/pipeline#5931]
Hi,

Creating this issue to request the separation of "tekton-pipelines" and "tekton-pipelines-resolvers" manifests with each release.

```sh
kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.43.0/release.yaml
kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.43.0/resolvers.yaml
```

I am using the Flux Kustomize controller to deploy Tekton Pipeline and running into kustomize namespace confliction. 

**Error: namespace transformation produces ID conflict**

#### This does not work
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-pipelines
spec:
  interval: 10m0s
  prune: true
  wait: true
  force: true
  path: ./infrastructure/tekton/pipelines
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
```

The directory `./infrastructure/tekton/pipelines` has the pipeline release file.

1. release.yaml
2. kustomization.yaml

#### This works
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-pipelines
spec:
  interval: 10m0s
  prune: true
  wait: true
  force: true
  path: ./infrastructure/tekton/pipelines
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-pipelines-resolvers
spec:
  interval: 10m0s
  prune: true
  wait: true
  force: true
  path: ./infrastructure/tekton/pipelines-resolvers
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
```
The directory `./infrastructure/tekton/pipelines` has the pipeline release file and the directory `./infrastructure/tekton/pipelines-resolvers` has the resolvers file.

**Comment by AlanGreene** [comment]
This was originally the case but they were combined before release, see https://github.com/tektoncd/pipeline/issues/5607 for previous discussion.
@abayer fyi

**Comment by michaelsatish** [comment]
@abayer Is it possible to revert the decision to include the resolvers with the pipeline manifest and provide pipeline and resolvers separately with future releases?

Unfortunately I cannot use the Tekton operator as there is no support to provide images from a Private repo.

**Comment by vdemeester** [comment]
@michaelsatish if the resolvers *where* to live in the same namespace as the rest of the pipeline payload (aka in `tekton-pipelines`), would it work ?

**Comment by michaelsatish** [comment]
@vdemeester Thank you. That will work for me.

**Comment by vdemeester** [comment]
@michaelsatish ok so the real problem is that we "ship" 2 namespaces in the same `release.yaml` 🤔

**Comment by michaelsatish** [comment]
I think kustomize will not handle a manifest file having 2 kind of type namespace. See this https://github.com/kubernetes-sigs/kustomize/issues/3156

**Comment by samip5** [comment]
Just hit this issue with Flux.

```
error: accumulating resources: accumulation err='accumulating resources from 'pipelines': '/home/sky/Github/k8s-cluster/cluster/apps/ci/tekton/app/pipelines' must resolve to a file': recursed accumulation of path '/home/sky/Github/k8s-cluster/cluster/apps/ci/tekton/app/pipelines': namespace transformation produces ID conflict: [{"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"internal.config.kubernetes.io/previousKinds":"Namespace","internal.config.kubernetes.io/previousNames":"tekton-pipelines","internal.config.kubernetes.io/previousNamespaces":"_non_namespaceable_"},"labels":{"app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-pipelines","pod-security.kubernetes.io/enforce":"restricted"},"name":"tekton-pipelines"}} {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"internal.config.kubernetes.io/previousKinds":"Namespace","internal.config.kubernetes.io/previousNames":"tekton-pipelines-resolvers","internal.config.kubernetes.io/previousNamespaces":"_non_namespaceable_"},"labels":{"app.kubernetes.io/component":"resolvers","app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-pipelines","pod-security.kubernetes.io/enforce":"restricted"},"name":"tekton-pipelines"}}]
```

**Comment by danmanners** [comment]
I'm running into this in my homelab as well with both ArgoCD. Having the single file breaks any GitOps tooling I've tested so far.

Genuine question: was https://github.com/tektoncd/pipeline/issues/5607 QA tested with any GitOps tools like Flux or ArgoCD? This should/would have immediately failed.

**Comment by vdemeester** [comment]
@michaelsatish @samip5 same question I asked @danmanners on https://github.com/tektoncd/pipeline/issues/5607#issuecomment-1437200648.

do you have an example of how one deploys Tekton Pipelines witsh Fluy or ArgoCD (aka the Application or other CRD used and the possible layout of a repo or something) ?

I want to understand how we can solve this, and if this is solvable independently of the `release.yaml` or not.

**Comment by michaelsatish** [comment]
@vdemeester 

Here is a simplified repo structure. 

```
├── clusters
│   ├── dev
│   │   ├── infrastructure.yaml
├── infrastructure
│   ├── tekton
│   │   ├── pipelines
│   │   │   ├── release.yaml

```

The path `./infrastructure/tekton/pipelines` has the release.yaml file. 

The file `./clusters/dev/infrastructure.yaml` has the flux CRD "kustomization". The flux source and kustomization controllers reconciles any changes in path `./infrastructure/tekton/pipelines`

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-pipelines
spec:
  interval: 10m0s
  prune: true
  wait: true
  force: true
  path: ./infrastructure/tekton/pipelines
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
```

Hope this helps.
