### ISSUE TITLE
Deprecation confusion in auth docs

### ISSUE THREAD

**Issue by jimmyjones2** [tektoncd/pipeline#5971]
I'm trying to set up the git-clone task to support different credentials depending on what git server is used. The [git-clone task says](https://hub.tekton.dev/tekton/task/git-clone) I can "Use Tekton Pipelines' built-in credentials support" and links to the [docs](https://github.com/tektoncd/pipeline/blob/main/docs/auth.md). These give an example for SSH auth:
```
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  annotations:
    tekton.dev/git-0: github.com # Described below
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: <private-key>
  # This is non-standard, but its use is encouraged to make this more secure.
  # If it is not provided then the git server's public key will be requested
  # when the repo is first fetched.
  known_hosts: <known-hosts>
```

however this has a PipelineResources deprecation warning before it. If I use this together with the git-clone task am I inadvertently using PipelineResources?
