### ISSUE TITLE
Windows containers: 0.42.0 affinity assistant doesn't work - missing Windows images

### ISSUE THREAD

**Issue by wilstdu** [tektoncd/pipeline#5998]
> Problem occurred before: #4471
> Changes to resolve it are still in-place, but the images for Windows are not present.

# Expected Behavior

Tasks running on Windows can start.

# Actual Behavior
After pipelines upgrade Windows pipelines (0.40.0 -> 0.42.0, opetator: 0.62 -> 0.64) stopped working because of:
```
reason: ImagePullBackOff
message: Back-off pulling image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.42.0@sha256:77e43d0fc9f7e7bdfa31dc16082b08dace05ce81c91a06c00dfa2f547212ce72"

reason: ErrImagePull
message: 'rpc error: code = Unknown desc = no matching manifest for windows/amd64 10.0.17763 in the manifest list entries'
```

Same for: `gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop@sha256:bd1fcc45d40a8ef1621789856caa2f54d7a884f19af921105feafae0131648c5` image

Affinity assistant doesn't work when using tasks running on Windows with workspaces as there's no Windows image entrypoint and nop.

# Steps to Reproduce the Problem
```
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-verification-win
  namespace: default
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: print-message
      taskSpec:
        steps:
          - name: dummy
            image: mcr.microsoft.com/windows/servercore:1809
            script: |
              Write-Output dummy

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tekton-verification-win
spec:
  pipelineRef:
    name: tekton-verification-win
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        storageClassName: win
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  podTemplate:
    nodeSelector:
      kubernetes.io/os: windows
    tolerations:
    - key: "windows"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    securityContext:
      windowsOptions:
        runAsUserName: "ContainerAdministrator"
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.42.0
```
