### ISSUE TITLE
taskrunvalidationfailed - array results - results initialized with ambiguous failure message

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#6023]
# Expected Behavior

As a user, I expect the type of a result in the `taskRun` status matches with the type specified in the task definition. I do not expect to have the result set to `string` type by default. 

# Actual Behavior

I see two issues here when a result is defined as an array but it is initialized using a string value:

Issue 1: The taskRun results section lists the result of type string whereas it was originally defined as array in the task definition.

Issue 2: The error message in the status section of a taskRun is ambiguous. The error message needs to be a little more verbose and explicit. Also, the error message needs to list down the result names and their specified types. 

# Steps to Reproduce the Problem

1. Deploy Tekton Pipelines with the latest commit
2. Apply task, pipeline, and pipelineRun to the cluster.

```
$ kubectl create -f pipelinerun.yaml
pipeline.tekton.dev/mismatch-type-in-result created
task.tekton.dev/mismatch-type-task created
pipelinerun.tekton.dev/mismatch-type-in-result-pipelinerun-jq8mh created
```

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mismatch-type-in-result
spec:
  tasks:
    - name: mismatch-type
      taskRef:
        name: mismatch-type-task
---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mismatch-type-task
spec:
  results:
    - name: result1
      type: array
  steps:
    - name: write-invalid-result
      image: alpine:latest
      script: |
        #!/bin/sh
        echo -n "this is a string for a result with array type" | tee $(results.result1.path);
---

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: mismatch-type-in-result-pipelinerun-
spec:
  pipelineRef:
    name: mismatch-type-in-result
```

3. Check the taskRun status:

```
$ kubectl get tr
NAME                                                      SUCCEEDED   REASON                    STARTTIME   COMPLETIONTIME
mismatch-type-in-result-pipelinerun-jq8mh-mismatch-type   False       TaskRunValidationFailed   8s          3s
```

![Screen Shot 2023-01-23 at 6 44 18 PM](https://user-images.githubusercontent.com/206285/214203071-30c8866b-56f7-4187-89eb-987d404dd7f2.png)

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:40:19Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}

```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.23.1
Pipeline version: devel
```

**Comment by pritidesai** [comment]
/cc @Yongxuanzhang
Preparing for the promotion - #5688

**Comment by pritidesai** [comment]
The same issue happens for object results.

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mismatch-type-task
spec:
  results:
    - name: result1
      type: array
    - name: result2
      type: object
      properties:
        hello:
          type: string
  steps:
    - name: write-invalid-result
      image: alpine:latest
      script: |
        #!/bin/sh
        echo -n "this is a string for a result with array type" | tee $(results.result1.path);
        echo -n "this is a string for a result with object type" | tee $(results.result2.path);
```

![Screen Shot 2023-01-23 at 7 32 08 PM](https://user-images.githubusercontent.com/206285/214206952-659e783d-90e0-47b2-9fd7-a795396cf2b4.png)

The message can be a little more descriptive and clear, for example:

```
Error: the result type does not match with the value its assigned to. The taskResult `result1` is defined as `array` but its assigned `string` value. The taskResult `result2` is defined as `object` but its assigned `string` value. 
```
