### ISSUE TITLE
Legacy bundle syntax does not work with remote resoruces

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#6058]
# Expected Behavior

I can use the legacy bundle syntax in Tekton v0.44:

```yaml
    taskRef:
      kind: Task
      params:
      - name: bundle
        value: gcr.io/tekton-releases/catalog/upstream/git-batch-merge:0.2
      - name: name
        value: git-batch-merge
      - name: kind
        value: Task
```

# Actual Behavior

```
Pipeline tekton-ci/tekton-image-build can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "": failed to get task: error requesting remote resource: error getting "bundleresolver" "tekton-ci/bundles-e48f9a9d47f93b59899b7d303fe7799a": could not find object in image with kind: Task and name: git-batch-merge
```

# Steps to Reproduce the Problem

1. Any of the Tekton CI jobs in plumbing
2.
3.

# Additional Info

- Kubernetes version:

```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14-gke.1800", GitCommit:"1eab5b8da4acab130c72aea21eb7ed3e96523ca2", GitTreeState:"clean", BuildDate:"2022-12-07T09:32:46Z", GoVersion:"go1.17.13b7", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.28.0
Chains version: v0.8.0
Pipeline version: v0.44.0
Triggers version: v0.22.1
Dashboard version: v0.32.0
```

**Comment by abayer** [comment]
So the remote bundles syntax is:
```
  taskRef:
    resolver: bundles
    params:
      - name: bundle
        value: gcr.io/tekton-releases/catalog/upstream/git-batch-merge:0.2
      - name: name
        value: git-batch-merge
      - name: kind
        value: task
```

I'm guessing this is v1 conversion stuff, and it's somehow not setting `resolver: bundles`?
