### ISSUE TITLE
Support Parameters Substitution when Referring a PipelineRun Param in Step Args

### ISSUE THREAD

**Issue by XinruZhang** [tektoncd/pipeline#6066]
# Expected Behavior

Submit the following YAML:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-param-sustitution-
spec:
  params:
  - name: pr-params
    value:
    - 'pr-param-value-1'
    - 'pr-param-value-2'
  pipelineSpec:
    params:
    - name: pr-params
      type: array
    tasks:
    - name: cat-worker
      params:
      - name: task-params
        value: '$(params.pr-params[0])'
      taskSpec:
        params:
        - name: task-params
          type: string
        steps:
        - name: echo-param-1
          image: bash:latest
          args: ["$(params.task-params[0])"]
          script: |
            echo $1
```

It is successfully scheduled and executed, within the TaskRun step `echo-param-1`, it prints out "pr-param-value-1"

# Actual Behavior

It's child TaskRun prints out "$(params.task-params[0])" instead of the actual value "pr-param-value-1".

# Steps to Reproduce the Problem

submit the yaml, and check the TaskRun's pod logs.

# Additional Info

- Kubernetes version:
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8-gke.2000", GitCommit:"63bd400145c58fe450325af1d249c3072fed68ef", GitTreeState:"clean", BuildDate:"2022-12-07T09:33:04Z", GoVersion:"go1.18.8b7", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
❯ kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'
v0.44.0
```

**Comment by Yongxuanzhang** [comment]
first of all, you need to enable alpha feature flag.
second, the reference in `args: ["$(params.task-params[0])"]` is wrong, it should be `args: ["$(params.task-params)"]` since your task-params is not an array

**Comment by Yongxuanzhang** [comment]
try out this one:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-param-sustitution-
spec:
  params:
  - name: pr-params
    value:
    - 'pr-param-value-1'
    - 'pr-param-value-2'
  pipelineSpec:
    params:
    - name: pr-params
      type: array
    tasks:
    - name: cat-worker
      params:
      - name: task-params
        value: '$(params.pr-params[0])'
      taskSpec:
        params:
        - name: task-params
          type: string
        steps:
        - name: echo-param-1
          image: bash:latest
          args: ["$(params.task-params)"]
          script: |
            echo $1
```
