### ISSUE TITLE
Tekton unable to handle PipelineRuns too big

### ISSUE THREAD

**Issue by RafaeLeal** [tektoncd/pipeline#6076]
# Expected Behavior

Tekton should be able to run PipelineRuns that are big or at least give a proper error.
# Actual Behavior

PipelineRun gets stuck in the same status in the cluster, not respecting any timeouts. 

# Steps to Reproduce the Problem

1. Create a PipelineRun with a lot of embedded tasks and status
2. Watch the tekton controller logs
3.

# Versions Info

<details>
  <summary><b>Kubernetes Version</b> (output of `kubectl version -o yaml`)</summary>

```yaml
$ kubectl version -o yaml
clientVersion:
  buildDate: "2022-10-12T10:47:25Z"
  compiler: gc
  gitCommit: 434bfd82814af038ad94d62ebe59b133fcb50506
  gitTreeState: clean
  gitVersion: v1.25.3
  goVersion: go1.19.2
  major: "1"
  minor: "25"
  platform: darwin/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-11-29T18:41:42Z"
  compiler: gc
  gitCommit: 52e500d139bdef42fbc4540c357f0565c7867a81
  gitTreeState: clean
  gitVersion: v1.22.16-eks-ffeb93d
  goVersion: go1.16.15
  major: "1"
  minor: 22+
  platform: linux/amd64
```

</details>

<details>
  <summary><b>Tekton Pipeline Version</b> (output of `tkn version`)</summary>

```
Client version: 0.26.0
Pipeline version: v0.35.1
Triggers version: v0.20.0
Dashboard version: v0.26.0
```

</details>

# Additional Info
- We (Nubank) manage a very large CICD cluster (we reached over 700k taskruns/week), and we've built some abstractions over Tekton to make it easier for our users to declare new pipelines
- We started to observe that some pipelineruns were getting stuck in our cluster, not finishing even hours after the timeout.
- Investigating the logs, we found these (im formatting to become easier to read):
```yaml
{ 
   caller: pipelinerun/reconciler.go:268
   commit: 422a468
   error: etcdserver: request is too large
   knative.dev/controller: github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler
   knative.dev/key: pipelines/itaipu-tests-main-run-ie3c7
   knative.dev/kind: tekton.dev.PipelineRun
   knative.dev/traceid: d1c3c461-cd4e-4656-a913-900fede9ba6e
   level: warn
   logger: tekton-pipelines-controller
   msg: Failed to update resource status
   targetMethod: ReconcileKind
   ts: 2023-01-18T13:54:54.256Z
}
```

```yaml
{ 
   caller: controller/controller.go:566
   commit: 422a468
   duration: 14.036001784
   error: etcdserver: request is too large
   knative.dev/controller: github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler
   knative.dev/key: pipelines/itaipu-tests-main-run-ie3c7
   knative.dev/kind: tekton.dev.PipelineRun
   knative.dev/traceid: d1c3c461-cd4e-4656-a913-900fede9ba6e
   level: error
   logger: tekton-pipelines-controller
   msg: Reconcile error
   stacktrace: github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).handleErr
        github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:566
github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem
        github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:543
github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).RunContext.func3
        github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:491
   ts: 2023-01-18T13:54:54.256Z
}
```

- These two errors were indicating that the Tekton Pipelines controller were trying to update the status, but it's getting this `request is too large` error.
- Searching for other logs, we found these:
```yaml
{
   caller: pipelinerun/pipelinerun.go:1360
   commit: 422a468
   knative.dev/controller: github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler
   knative.dev/key: pipelines/itaipu-tests-main-run-ie3c7
   knative.dev/kind: tekton.dev.PipelineRun
   knative.dev/traceid: d1c3c461-cd4e-4656-a913-900fede9ba6e
   level: info
   logger: tekton-pipelines-controller
   msg: Found a TaskRun itaipu-tests-main-run-ie3c7-bors-ready that was missing from the PipelineRun status
   ts: 2023-01-18T13:54:40.233Z
}
``` 
```yaml
{ 
   caller: taskrun/taskrun.go:117
   commit: 422a468
   knative.dev/controller: github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler
   knative.dev/key: pipelines/itaipu-tests-main-run-ie3c7-bors-ready
   knative.dev/kind: tekton.dev.TaskRun
   knative.dev/traceid: 74f9a53a-8c95-49c0-9093-2e6095e0ffa3
   level: info
   logger: tekton-pipelines-controller
   msg: taskrun done : itaipu-tests-main-run-ie3c7-bors-ready 
   ts: 2023-01-18T13:59:38.227Z
}
```
- These logs indicated that there was nothing wrong at the TaskRun level: the TaskRun `itaipu-tests-main-run-ie3c7-bors-ready` was done, but it was missing from the PipelineRun status, since it was failing to update the status due to `etcd: request is too large` error.
- This made the PipelineRun get stuck since it couldn't update the status, even for timing out.
- We are still using the `full` embedded status. We know that's not ideal for our scenario, and we want to go to `minimal` as soon as possible. That being said, I still believe that we might have this error in the future for some pipelines that can get really huge.
