### ISSUE TITLE
task results not replaced with their values in childReferences

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#6093]
# Expected Behavior

As a user, I expect the `pipelineRun` status to include the results in place of a task result reference. This helps diagnose the pipeline run using its status.

# Actual Behavior

`pipelineRun.status.childReferences` does not replace a task result when referred in `when` expressions using `"$(tasks.task1.results.string-result)"` or `"$(tasks.task1.results.array-results[1])"`.

# Steps to Reproduce the Problem

1. Deploy Tekton Pipelines with the latest commit
2. Enable `alpha` feature flag 

```
kubectl patch cm/feature-flags -p "{\"data\":{\"enable-api-fields\":\"alpha\"}}" -n tekton-pipelines
```

3. Apply pipelineRun to the cluster.

```
kubectl create -f pipeline-with-when-expressions-using-array-results.yaml
pipelinerun.tekton.dev/pipelinerun-with-when-expressions-using-array-results-dcghl created
```

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipelinerun-with-when-expressions-using-array-results-
spec:
  pipelineSpec:
    tasks:
      - name: task1
        taskSpec:
          results:
            - name: array-results
              type: array
              description: The array results
            - name: string-result
              type: string
              description: The string results
          steps:
            - name: write-array
              image: bash:latest
              script: |
                #!/usr/bin/env bash
                echo -n "[\"1\", \"2\", \"3\"]" | tee $(results.array-results.path)
                echo -n "1" | tee $(results.string-result.path)
      - name: task2
        when:
          - input: "$(tasks.task1.results.array-results[1])"
            operator: in
            values: ["2"]
          - input: "$(tasks.task1.results.string-result)"
            operator: in
            values: ["1"]
        taskSpec:
          steps:
            - name: say-hi
              image: bash:latest
              script: |
                echo "hi"
```

4. Check pipelineRun status:

```
 kubectl get pr pipelinerun-with-when-expressions-using-array-results-w74qq -o json | jq .status.childReferences
[
  {
    "apiVersion": "tekton.dev/v1beta1",
    "kind": "TaskRun",
    "name": "pipelinerun-with-when-exp9fe3c5278f6960248e739a1c08e9e593-task1",
    "pipelineTaskName": "task1"
  },
  {
    "apiVersion": "tekton.dev/v1beta1",
    "kind": "TaskRun",
    "name": "pipelinerun-with-when-exp9fe3c5278f6960248e739a1c08e9e593-task2",
    "pipelineTaskName": "task2",
    "whenExpressions": [
      {
        "input": "$(tasks.task1.results.array-results[1])",
        "operator": "in",
        "values": [
          "2"
        ]
      },
      {
        "input": "$(tasks.task1.results.string-result)",
        "operator": "in",
        "values": [
          "1"
        ]
      }
    ]
  }
]
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:40:19Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.23.1
Pipeline version: v0.43.0
```
