### ISSUE TITLE
Support v1 Task&Pipeline in remote resolution

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#6141]
# Expected Behavior
Remote resolution can resolve remote v1 tasks and pipelines

# Actual Behavior
Remote resolution cannot resolve remote v1 tasks and pipelines

The pipelinerun is not created, and error log is:
```
"error":"1 error occurred:\n\t* failed to get pipeline: failed to convert obj [tekton.dev/v1](http://tekton.dev/v1), Kind=Pipeline into Pipeline\n\n",
```

# Steps to Reproduce the Problem

apply the sample pipeline run:
```yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: example-pipelinerun
  namespace: trusted-resources
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/Yongxuanzhang/sample-tekton-pipeline
      - name: revision
        value: main
      - name: pathInRepo
        value: signed-pipeline.yaml
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.23.1
Pipeline version: devel (latest main)
```
