### ISSUE TITLE
Improvement of Examples Test

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#6142]
This issue aims to track the improvement of examples test from both bug fixes at local and Improvement on documentations:

- Bug fixes for examples that work on CI but not on local:
  Thanks to @lbernick for [the fix of security context for example PRs using catalog git-clone, which passes on CI but fails on local with GCR before this fix](https://github.com/tektoncd/pipeline/pull/6138)
- Discrepancies of Setup for Examples between CI Env and Local Registry, GCR and Kind as Registry
  This is to track that the debugging and local test setup for ./examples setup in the pipeline repo and debugging could be confusing for new users. eg. during the changes for https://github.com/tektoncd/pipeline/blob/2da10fc5ff9d99571b6055bcb86aca12805cb9e0/examples/v1beta1/pipelineruns/pipelinerun.yaml#L152, there are no instructions for the following points without looking into the actual codes:
  
  - How examples tests setup the registry as `KO_DOCKER_REPO`
  - Why are registries always set to `localhost:5000` by the dogfooding cluster on CI
  - Why Kind cluster as `KO_DOCKER_REPO` could not grant similar access to `push` to registry, which is different from the behavior for GCR

- The examples shall be kept up-to-date with related resources for example: catalog tasks:
  - Related https://github.com/tektoncd/pipeline/issues/5727

Goal:

- [ ] All examples shall pass and behave the same in CI and local
- [ ] Document and comments in and not limited to plumbing, `Development.md` to mitigate the discrepancies between the setup for local example testing and creation

**Comment by Basavaraju-G** [comment]
yes, Im facing similar issue while https://github.com/tektoncd/pipeline/blob/main/examples/v1/pipelineruns/pipelinerun.yaml with secure registry. tests are working fine when i use KO_DOCKER_REPO with unsecure_Registry, but when i try to use secure registry like GCR or Secure docker registry, example tests are failing with authentication required.

there is noway we can pass the docker_config in this pipelinerun.

```kubectl logs -n arendelle-dt987              demo-pipeline-run-1-build-image-pod -c step-build-and-push
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "s390x-cluster.bastion-z.svc.cluster.local:443/getting-started": POST http://s390x-cluster.bastion-z.svc.cluster.local:443/v2/getting-started/blobs/uploads/: unexpected status code 401 Unauthorized: <html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.22.0</center>
</body>
</html>
```
here is the pod log:
```
spec:
          params:
          - name: IMAGE
            value: s390x-cluster.bastion-z.svc.cluster.local:443/getting-started
          - name: CONTEXT
            value: examples/getting-started
          - name: DOCKERFILE
            value: $(workspaces.source.path)/examples/getting-started/Dockerfile
          podTemplate:
            securityContext:
              fsGroup: 65532
          serviceAccountName: default
          taskRef:
            kind: Task
            name: kaniko
          timeout: 1h0m0s
          workspaces:
          - name: source
            persistentVolumeClaim:
              claimName: pvc-8bdc738878
        status:
          completionTime: "2023-04-26T09:38:18Z"
          conditions:
          - lastTransitionTime: "2023-04-26T09:38:18Z"
            message: |
              "step-build-and-push" exited with code 1 (image: "gcr.io/kaniko-project/executor@sha256:b44b0744b450e731b5a5213058792cd8d3a6a14c119cf6b1f143704f22a7c650"); for logs run: kubectl -n arendelle-k4lvb logs demo-pipeline-run-1-build-image-pod -c step-build-and-push
            reason: Failed
            status: "False"
            type: Succeeded
          podName: demo-pipeline-run-1-build-image-pod
          sidecars:
```
