### ISSUE TITLE
Enhance the output of the kubectl get taskruns

### ISSUE THREAD

**Issue by skeeey** [tektoncd/pipeline#615]
# Expected Behavior

When I execute `kubectl get taskruns` command, I want to get more helpful information about the `taskruns`

e.g.

- `TaskRun.Status.StartTime`
- `TaskRun.Status.CompletionTime`
- `TaskRun.Status.Conditions.Type`
- `TaskRun.Status.Conditions.Status`
- `TaskRun.Status.Conditions.Reason`

# Actual Behavior

When I execute `kubectl get taskruns` command, I don't get any helpful  information

**Comment by skeeey** [comment]
If this make sense, I can send out a PR to fix this

**Comment by bobcatfish** [comment]
Hey there @skeeey ! Trying to make sure I know what's missing: so when I run `kubectl get taskruns -o yaml` I seem to be seeing the info you're looking for, e.g.:

```yaml
status:
  conditions:
    - lastTransitionTime: 2018-12-11T15:50:09Z
      status: "True"
      type: Succeeded
  podName: echo-hello-world-task-run-pod-85ca51
  startTime: 2018-12-11T15:49:39Z
  steps:
    - terminated:
        containerID: docker://fcfe4a004...6729d6d2ad53faff41
        exitCode: 0
        finishedAt: 2018-12-11T15:50:01Z
        reason: Completed
        startedAt: 2018-12-11T15:50:01Z
    - terminated:
        containerID: docker://fe86fc5f7...eb429697b44ce4a5b
        exitCode: 0
        finishedAt: 2018-12-11T15:50:02Z
        reason: Completed
        startedAt: 2018-12-11T15:50:02Z
```

(I took this example output from https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#task)

So we've got:

* `TaskRun.Status.StartTime`
* `TaskRun.Status.CompletionTime` is technically: `TaskRun.Status.Conditions[0].LastTransitionTime`
* `TaskRun.Status.Conditions.Type` is technically: `TaskRun.Status.Conditions[0].Type`
* `TaskRun.Status.Conditions.Status` is technically: `TaskRun.Status.Conditions[0].Status`
* `TaskRun.Status.Conditions.Reason` is in the status of each `step` (note that #549 proposes adding names to these step statuses so they're easier to read)

Is that the info you're looking for?

(Note that some of this is not super intuitive b/c it's trying to follow these kubernetes api best practices: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties)
