### ISSUE TITLE
`startedAt` of a container should not be nil when taskRun exits with `TaskRunTimeout`

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#6174]
# Expected Behavior

Creating a `taskRun` with a `timeout`  sets the startedAt 
The `taskRun` status has set the start time (`startedAt`) of a container when a `taskRun` exits with `TaskRunTimeout`.

# Actual Behavior

When a `taskRun` is created with a `timeout` and it exits with `TaskRunTimeout`, the `startedAt` of a container is set to `null`. 

# Steps to Reproduce the Problem

1. Deploy Tekton Pipelines with the latest commit.
2. Apply TaskRun to the cluster

```
kubectl create -f taskrun-timeout.yaml
taskrun.tekton.dev/taskrun-timeout-2lzgn created
```

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: taskrun-timeout-
spec:
  timeout: 1s
  taskSpec:
    steps:
      - name: sleeping-beauty
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          echo "I am supposed to sleep for 10 second!"
          sleep 10
```

4. Check the taskRun status:

```
kubectl get tr taskrun-timeout-b2fhk -o=jsonpath='{.status.steps[0].terminated.startedAt}'
<nil>                                                                                                                                  
```

```
 kubectl get tr taskrun-timeout-b2fhk -o json | jq .status 
{
  "completionTime": "2023-02-15T20:12:26Z",
  "conditions": [
    {
      "lastTransitionTime": "2023-02-15T20:12:26Z",
      "message": "TaskRun \"taskrun-timeout-b2fhk\" failed to finish within \"1s\"",
      "reason": "TaskRunTimeout",
      "status": "False",
      "type": "Succeeded"
    }
  ],
  "podName": "taskrun-timeout-b2fhk-pod",
  "startTime": "2023-02-15T20:12:25Z",
  "steps": [
    {
      "container": "step-sleeping-beauty",
      "name": "sleeping-beauty",
      "terminated": {
        "exitCode": 1,
        "finishedAt": "2023-02-15T20:12:26Z",
        "reason": "TaskRunTimeout",
        "startedAt": null
      }
    }
  ],
  "taskSpec": {
    "steps": [
      {
        "computeResources": {},
        "image": "bash:latest",
        "name": "sleeping-beauty",
        "script": "#!/usr/bin/env bash\necho \"I am supposed to sleep for 10 second!\"\nsleep 10\n"
      }
    ]
  }
}

```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:40:19Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.23.1
Pipeline version: devel
```
