### ISSUE TITLE
step timing out sets the reason to `TaskRunTimeout` instead of `Failed`

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#6178]
# Expected Behavior

When a step of the task hits the timeout specified in that step, I expect the taskRun to exit with `Failed` reason and the appropriate message saying `my-step` exited because the step exceeded the specified timeout limit irrespective of whether `taskRun` timeout is specified or not.

Doc: https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#specifying-a-timeout

# Actual Behavior

TaskRun exits with `Failed` when a step exceeds the timeout limit. The same step exits with a different reason and message, `TaskRunTimeout` when an extended `timeout` is specified in the `taskRun`  (taskRun timeout > step timeout).

# Steps to Reproduce the Problem

1. Deploy Tekton Pipelines with the latest commit.
2. Apply TaskRuns to the cluster

```
kubectl create -f experimental/timeout/step-timeout-without-taskrun-timeout.yaml
taskrun.tekton.dev/step-timeout-without-taskrun-timeout-fhhw2 created
```

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: step-timeout-without-taskrun-timeout-
spec:
  taskSpec:
    steps:
      - name: sleeping-beauty
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          echo "I am supposed to sleep for 10 second!"
          sleep 10
        timeout: 1s
```

```
kubectl create -f experimental/timeout/step-timeout-with-taskrun-timeout.yaml                 
taskrun.tekton.dev/step-timeout-with-taskrun-timeout-xrn5l created
```

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: step-timeout-with-taskrun-timeout-
spec:
  timeout: 5s
  taskSpec:
    steps:
      - name: sleeping-beauty
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          echo "I am supposed to sleep for 10 second!"
          sleep 10
        timeout: 1s
```

4. Check the taskRuns status:

```
kubectl get tr step-timeout-without-taskrun-timeout-fhhw2 -o json | jq .status
{
  "completionTime": "2023-02-15T23:47:09Z",
  "conditions": [
    {
      "lastTransitionTime": "2023-02-15T23:47:09Z",
      "message": "\"step-sleeping-beauty\" exited because the step exceeded the specified timeout limit; for logs run: kubectl -n default logs step-timeout-without-taskrun-timeout-fhhw2-pod -c step-sleeping-beauty\n",
      "reason": "Failed",
      "status": "False",
      "type": "Succeeded"
    }
  ],
  "podName": "step-timeout-without-taskrun-timeout-fhhw2-pod",
  "startTime": "2023-02-15T23:47:02Z",
  "steps": [
    {
      "container": "step-sleeping-beauty",
      "imageID": "docker-pullable://bash@sha256:ad93c5cceb1a38ba5b089b6cb839b939a341efe872fbd4eefa027fbe59e95d5d",
      "name": "sleeping-beauty",
      "terminated": {
        "containerID": "docker://92a7266f7e25ee6964308a81c2df40f2daff0eb52eeb1d23cba05f6d3a2c9472",
        "exitCode": 1,
        "finishedAt": "2023-02-15T23:47:08Z",
        "reason": "Error",
        "startedAt": "2023-02-15T23:47:07Z"
      }
    }
  ],
  "taskSpec": {
    "steps": [
      {
        "computeResources": {},
        "image": "bash:latest",
        "name": "sleeping-beauty",
        "script": "#!/usr/bin/env bash\necho \"I am supposed to sleep for 10 second!\"\nsleep 10\n",
        "timeout": "1s"
      }
    ]
  }
}
```

```
 kubectl get tr step-timeout-with-taskrun-timeout-vfgrp -o json | jq .status
{
  "completionTime": "2023-02-16T00:14:28Z",
  "conditions": [
    {
      "lastTransitionTime": "2023-02-16T00:14:28Z",
      "message": "TaskRun \"step-timeout-with-taskrun-timeout-vfgrp\" failed to finish within \"5s\"",
      "reason": "TaskRunTimeout",
      "status": "False",
      "type": "Succeeded"
    }
  ],
  "podName": "step-timeout-with-taskrun-timeout-vfgrp-pod",
  "startTime": "2023-02-16T00:14:23Z",
  "steps": [
    {
      "container": "step-sleeping-beauty",
      "name": "sleeping-beauty",
      "terminated": {
        "exitCode": 1,
        "finishedAt": "2023-02-16T00:14:28Z",
        "reason": "TaskRunTimeout",
        "startedAt": null
      }
    }
  ],
  "taskSpec": {
    "steps": [
      {
        "computeResources": {},
        "image": "bash:latest",
        "name": "sleeping-beauty",
        "script": "#!/usr/bin/env bash\necho \"I am supposed to sleep for 10 second!\"\nsleep 10\n",
        "timeout": "1s"
      }
    ]
  }
}

```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:40:19Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.23.1
Pipeline version: devel
```

Note the two different conditions for the exact same failure (step timedout):

step-timeout-without-taskrun-timeout:

```
    {
      "message": "\"step-sleeping-beauty\" exited because the step exceeded the specified timeout limit; for logs run: kubectl -n default logs step-timeout-without-taskrun-timeout-fhhw2-pod -c step-sleeping-beauty\n",
      "reason": "Failed",
    }
```

step-timeout-with-taskrun-timeout:
```
    {
      "message": "TaskRun \"step-timeout-with-taskrun-timeout-vfgrp\" failed to finish within \"5s\"",
      "reason": "TaskRunTimeout",
    }
```

**Comment by pritidesai** [comment]
This becomes even more interesting for a task with multiple steps. For example, for a task with two steps, when a first step is expected to be successful and the second step is when the step timeout hits, both the steps have  non-zero `exitCode` instead of just the second step. But at least, the `startedAt` is initialized unlike the issue reported in #6174 but the `finishedAt` for both steps and the taskRun is set to the same value 🙃. 

Example taskRun:

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: step-timeout-with-taskrun-timeout-
spec:
  timeout: 10s
  taskSpec:
    steps:
      - name: sleeping-beauty-1
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          echo "I am supposed to sleep for 1 second!"
          sleep 1
        timeout: 3s
      - name: sleeping-beauty-2
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          echo "I am supposed to sleep for 1 second!"
          sleep 1
        timeout: 1ms
```

In this sample `taskRun`, the first step should run just fine without any failures and the second step must exit with `failure` as the timeout is much more lower than the execution time. But the status has both steps marked as failure:

```
{
  "completionTime": "2023-02-16T20:04:16Z",
  "conditions": [
    {
      "lastTransitionTime": "2023-02-16T20:04:16Z",
      "message": "TaskRun \"step-timeout-with-taskrun-timeout-2gfbg\" failed to finish within \"10s\"",
      "reason": "TaskRunTimeout",
      "status": "False",
      "type": "Succeeded"
    }
  ],
  "podName": "step-timeout-with-taskrun-timeout-2gfbg-pod",
  "startTime": "2023-02-16T20:04:06Z",
  "steps": [
    {
      "container": "step-sleeping-beauty-1",
      "imageID": "docker-pullable://bash@sha256:ad93c5cceb1a38ba5b089b6cb839b939a341efe872fbd4eefa027fbe59e95d5d",
      "name": "sleeping-beauty-1",
      "terminated": {
        "exitCode": 1,
        "finishedAt": "2023-02-16T20:04:16Z",
        "reason": "TaskRunTimeout",
        "startedAt": "2023-02-16T20:04:11Z"
      }
    },
    {
      "container": "step-sleeping-beauty-2",
      "imageID": "docker-pullable://bash@sha256:ad93c5cceb1a38ba5b089b6cb839b939a341efe872fbd4eefa027fbe59e95d5d",
      "name": "sleeping-beauty-2",
      "terminated": {
        "exitCode": 1,
        "finishedAt": "2023-02-16T20:04:16Z",
        "reason": "TaskRunTimeout",
        "startedAt": "2023-02-16T20:04:12Z"
      }
    }
  ],
  "taskSpec": {
    "steps": [
      {
        "computeResources": {},
        "image": "bash:latest",
        "name": "sleeping-beauty-1",
        "script": "#!/usr/bin/env bash\necho \"I am supposed to sleep for 1 second!\"\nsleep 1\n",
        "timeout": "3s"
      },
      {
        "computeResources": {},
        "image": "bash:latest",
        "name": "sleeping-beauty-2",
        "script": "#!/usr/bin/env bash\necho \"I am supposed to sleep for 1 second!\"\nsleep 1\n",
        "timeout": "1ms"
      }
    ]
  }
}
```
