### ISSUE TITLE
Does not restart pods

### ISSUE THREAD

**Issue by abergmeier** [tektoncd/pipeline#618]
# Expected Behavior
When I delete an initializing Pod, it should restart the pod (at least attempt N times).

# Actual Behavior
It complains over and over:
```
{"level":"error","logger":"controller.taskrun-controller","caller":"controller/controller.go:286","msg":"{error 25 0 pods \"extract-schema-pod-7d02a3\" not found}","knative.dev/controller":"taskrun-controller","stacktrace":"github.com/knative/build-pipeline/vendor/github.com/knative/pkg/controller.(*Impl).handleErr\n\t/usr/local/google/home/jasonhall/go/src/github.com/knative/build-pipeline/vendor/github.com/knative/pkg/controller/controller.go:286\ngithub.com/knative/build-pipeline/vendor/github.com/knative/pkg/controller.(*Impl).processNextWorkItem\n\t/usr/local/google/home/jasonhall/go/src/github.com/knative/build-pipeline/vendor/github.com/knative/pkg/controller/controller.go:272\ngithub.com/knative/build-pipeline/vendor/github.com/knative/pkg/controller.(*Impl).Run.func1\n\t/usr/local/google/home/jasonhall/go/src/github.com/knative/build-pipeline/vendor/github.com/knative/pkg/controller/controller.go:223"}
```

# Steps to Reproduce the Problem

1. Create a _TaskRun_ without rights to pull from Docker registry.
2. Pod will be stuck in setup state
3. Delete Pod

# Additional Info

**Comment by abayer** [comment]
Yeah, I think we don't really have retry logic in place in general - we discussed this a bunch over in #221, and https://github.com/tektoncd/pipeline/pull/510 is in flight, but we probably need to do more work.

**Comment by bobcatfish** [comment]
hm this seems super weird, i would have thought kubernetes would create a new pod in this case - looks like a bit of investigation is warranted! :D

**Comment by khrm** [comment]
@abergmeier 
I am not able recreate this issue for your scenario. My pod isn't getting stuck in in setup state. I used following taskrun.yaml:
```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: pull
spec:
  serviceAccount: kbaig
  taskSpec:
    steps:
    - name: pull
      # Private image is just Ubuntu
      image: quay.io/rhpipeline/skopeo:alpine
      command: ["skopeo"]
      args: ["copy", "docker://gcr.io/build-crd-testing/secret-sauce", "dir:///tmp/"] 
  trigger:

```
