### ISSUE TITLE
Clearer Custom Task Reference Interface

### ISSUE THREAD

**Issue by XinruZhang** [tektoncd/pipeline#6186]
### Feature Request
 
Request to have an additive **dedicated field** for referencing Custom Task, instead of using **generally named fields** `apiVersion + kind + name` under `taskRef` for it.

```yaml
- name: sample-custom-task-new
  taskRef:
    customTask: "wait.testing.tekton.dev/v1beta1/Wait"
    name: "wait-task" # optional, depends on how custom tasks are implemented.
```

In this way, we create a new field `customTask` under `taskRef` for referencing Custom Task (just like we have a dedicated field `resolver` for Remote Resources).

 ```yaml
 - name: custom-task
  taskRef:
    customTask: "wait.testing.tekton.dev/v1beta1/Wait"
    name: "wait-task"

- taskRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/tektoncd/catalog.git
    - name: revision
      value: main
    - name: pathInRepo
      value: task/git-clone/0.6/git-clone.yaml

- name: regular-task
  taskRef:
    name: "sample-task"
 ```

### Use Case

Say I'm a new comer to Tekton, the first thing I knew about `taskRef` is it refers to a `Task` and will be scheduled as a `TaskRun`.

When I want to use the powerful Custom Task, I realized I need to use the following genaric syntax under `taskRef` to specify a CustomTask reference. 

What's even more weird is, I'm not allowed to use `taskRef.apiVersion` when specifying a regular Task, which seems like an inconsistent API design.

```yaml
# the current way of referencing a custom task
- name: custom-task 
  taskRef:
    apiVersion: "wait.testing.tekton.dev/v1beta1"
    kind: "Wait"
    name: "wait-task"
# illegal usage
- name: regular-task
  taskRef:
    apiVersion: "tekton.dev/v1beta1"  # illegal, PipelineRun controller ceates a CustomRun/Run for this taskRef instead of a TaskRun.
    kind: Task # optional
    name: "regular-task"
```

It would be clearer if we have a dedicated field to refer to `CustomTask`s under `taskRef`.

**Comment by vdemeester** [comment]
@XinruZhang I am not sure I completely agree with this statement. The `apiVersion` + `kind` + `name` is a very well known construct in Kubernetes types

**Comment by XinruZhang** [comment]
Thank you for the comment @vdemeester. Sorry for the confusion that I might have introduced here 🙃

My main point is it is confusing for a new Tekton user that using **taskRef.apiVersion + taskRef.kind + taskRef.name** to refer to a **Custom Task**. I updated the issue description, added the **Use Case** section to describe **where the confusion is** for a Tekton User, and **why it is inconsistent**, hope this helps with clarifying my idea.

Since I'm proposing a new field here, we can consider makeing this API field more generic (remove the implied Kubernetes-ism) as suggested in [this conformance design principle](https://github.com/tektoncd/community/blob/main/design-principles.md#conformance) to improve our API abstraction.

**Comment by XinruZhang** [comment]
@tektoncd/core-collaborators  PTAL :)

**Comment by lbernick** [comment]
Even though apiVersion and kind are technically kubernetes-isms, I think the spirit of the design principle on conformance is to not introduce fields that are only be able to run on k8s as opposed to other platforms. I'm not convinced that apiVersion and kind detract from conformance goals because it's extremely likely that custom task users would need to specify this info regardless of platform (I'm assuming that's why it's encoded in the "customTask" syntax in the example above).

Also, we can make this an additive change, but it introduces redundancy into the API. I'd imagine we'd consider deprecating the existing syntax at some point. I'm not sure there's a strong enough reason to do this.

Maybe to lessen confusion, we could allow the "illegal usage" example above? i.e.

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
spec:
- name: regular-task
  taskRef:
    apiVersion: "tekton.dev/v1"  # Create a v1 TaskRun instead of a v1beta1 TaskRun (the current behavior)
    kind: Task # optional
    name: "regular-task"
```

**Comment by XinruZhang** [comment]
Thank you for the comment @lbernick! 

> It's extremely likely that custom task users would need to specify this info regardless of platform

An interesting idea emerged when I discussed this with @vdemeester offline, `APIVersion` + `Kind` is not necessarily required when referring to a Custom Task, the two fields are often used for two purposes:

**1. Filtering `Event`s for `CustomRun`/`Run`:**

https://github.com/tektoncd/experimental/blob/f60e1cd8ce22ed745e335f6f547bb9a44580dc7c/cel/pkg/reconciler/cel/controller.go#L53

https://github.com/tektoncd/experimental/blob/f60e1cd8ce22ed745e335f6f547bb9a44580dc7c/task-loops/pkg/reconciler/tasklooprun/tasklooprun.go#L102-L107

https://github.com/tektoncd/experimental/blob/f60e1cd8ce22ed745e335f6f547bb9a44580dc7c/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go#L86-L91

https://github.com/tektoncd/experimental/blob/f60e1cd8ce22ed745e335f6f547bb9a44580dc7c/pipelines-in-pipelines/pkg/reconciler/pip/piprun.go#L67-L71

For the filtering purpose, we actually **don't have to** use `APIVersion` + `Kind`, for example using "pipelineLoop" to filter all the Kubernetes Event on `v1alpha.Run` has the same effect.

**2. Get the target CRD resource back and make modifications**:

https://github.com/tektoncd/experimental/blob/f60e1cd8ce22ed745e335f6f547bb9a44580dc7c/pipeline-in-pod/pkg/reconciler/pipelineinpod/pipelineinpod.go#L136-L142

For this purpose, the info "APIVersion" and "Kind" is important for those custom task controllers who take care of those CRDs defined within `CustomRun/Run`. But they don't have to be specified by end users by using the `pipeline.spec.tasks[].taskRef` or `run.spec.ref`or `customRun.spec.customRef`. Instead, each individual custom task controller can decide what CRD they want to manage within the controller, as long as end users specify which Custom Task Controller they want to use.

For example, a custom task user can specify:

```yaml
taskRef:
  customTask: "PipelineLoop"
  name: "my-pipeline-loop"
``` 

And in the PipelineLoop controller, it can only reconcile resources where their
- `apiVersion`=="`pipelineloop.dev/v1beta1`"
- `kind`=="`PipelineLoop`"
- `name`=="`taskRef.name`"

> I think the spirit of the design principle on conformance is to not introduce fields that are only able to run on k8s as opposed to other platforms

I partially agree with this statement, for the conformance policy, the functional capability of being platform-ignorant is indeed important, but the **naming** itself is also important.

**Comment by XinruZhang** [comment]
Moving [the discussion](https://docs.google.com/document/d/1AfJfdyd1JN2P4haBdYOxEn6SMENMgvQF9ps7iF2QSG0/edit?resourcekey=0-lm66bE68HA_WVLA6AaCh6w&disco=AAAAmUnoQCQ) with @pritidesai here in the issue: the main idea that @pritidesai  brings is:

> The pipeline author decided to choose the Tekton Task specifications as Custom Task. I do not think we should restrict or try to interpret the values specified in those fields. It's very well documented that those specifications (taskRef.apiVersion and taskRef.kind) creates customRun/Run. 
> 
> A pipeline author could also decide to specify apiVersion: "[tekton.dev/v1beta1](https://www.google.com/url?q=http://tekton.dev/v1beta1&sa=D&source=docs&ust=1677045455584094&usg=AOvVaw0whHhKBmdBq4iiXNSCjLrE)" and kind: Pipeline. It's user's decision to specify any kind of resource as a customRun/Run.

**Comment by lbernick** [comment]
Chatted offline with @XinruZhang and we agreed that it's not necessarily the fact that "apiVersion" and "kind" are "kubernetes-isms" that makes them confusing-- what's actually confusing is that custom run controllers reconcile custom run objects, and whether they reconcile objects with the specified api version and kind is entirely up to the controller. We're overloading "kind" to mean both the custom run controller that should reconcile the object and the type of object that the custom run controller can optionally reconcile. Similarly, we're overloading "apiVersion" to mean both the version of the custom spec (where api group is not clearly meaningful) and the api group + version of the object that the controller can optionally reconcile.

It's also confusing that name is required for Tasks but optional for custom Tasks. If the custom task controller supports reconciling objects of the same name and api version, it's supposed to look up the object with that name and use its spec, and if the user doesn't specify a name, the custom task controller may support reconciling w/ an empty spec.

Imagine a custom run controller must continue to reconcile CustomRuns, but can do so however it wants to (i.e. it's not necessarily required to reconcile objects of the same api version and kind as it filters for). The following syntax would be clearer IMO. (I'm not proposing this syntax, I'm just trying to brainstorm what it would look like if we didn't overload apiversion/kind in this way.)

```
taskRef:
  customRunController: "PipelineLoopFancyController"
  customSpecAPIVersion: "v1"
  customSpec:  # Anything in here is entirely up to the controller.
     pipelineLoopNameToFetchFromCluster: "my-pipeline-loop-crd"
```

This signifies that the custom run would be reconciled by the "PipelineLoopFancyController", using its v1 version of the custom spec. This specific custom run controller can either accept a custom spec inline, or it can look up whatever type of objects it reconciles. In this example, it would look up whatever type of object it reconciles, named "my-pipeline-loop-crd", and use that object's spec.

I'm not sure what syntax I'd want for a reference to a custom task in an ideal world, but wanted to hear others' thoughts on this (maybe nobody else finds this confusing?)
