### ISSUE TITLE
Display Failed Task Information in Finally Task

### ISSUE THREAD

**Issue by BlueCog** [tektoncd/pipeline#6214]
Currently, when a pipeline fails, the Finally task is executed. 
I can trigger a failed or succesfull Finally with (as an example):

```
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Failed"]
```

However, `$(tasks.status)`  does not provide information about **which** task failed. I would like to see a parameter that is passed to the Finally task, indicating which task failed This information could be used in a script to post to GIT (comit/PR) for example, indicating which task failed and why and maybe provide some context.

I've tried `tasks[*]` for example. But that doesnt work (see https://tekton.dev/docs/pipelines/variables/)
