### ISSUE TITLE
Permission denied when executing build steps

### ISSUE THREAD

**Issue by abergmeier** [tektoncd/pipeline#623]
# Expected Behavior
Should just run the steps container fine.

# Actual Behavior
Prints `standard_init_linux.go:178: exec user process caused "permission denied"`

# Steps to Reproduce the Problem

1. Configure Ubuntu:rolling container
2. Set `command: ['true']`

# Additional Info
The generated Pod Container then looks like:

```
    - command:
        - /tools/entrypoint
      env:
        - name: HOME
          value: /builder/home
        - name: ENTRYPOINT_OPTIONS
          value: >-
            {"args":["true"],"process_log":"/tools/process-log.txt","marker_file":"/tools/marker-file.txt"}
      image: 'docker-registry.default.svc:5000/common/ubuntu'
      imagePullPolicy: Always
      name: build-step-extract-table-def
      resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 500Mi
      securityContext:
        capabilities:
          drop:
            - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /def
          name: task-volume
        - mountPath: /tools
          name: tools
        - mountPath: /workspace
          name: workspace
        - mountPath: /builder/home
          name: home
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-g5zqn
          readOnly: true
      workingDir: /workspace
```

**Comment by vbatts** [comment]
@abergmeier hey hey, can you provide information about the version of tekton/pipeline and kubernetes that you're using?
@vdemeester have you seen this?

**Comment by bobcatfish** [comment]
I tried this out with this Task and TaskRun (with the controllers at commit 1861bddc364cd82930f506901180bfd2c10b5e77):

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: some-task
spec:
  steps:
  - name: true-step
    image: ubuntu:rolling
    command:
    - 'true'
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: some-task-run
spec:
  taskRef:
    name: some-task
  trigger:
    type: manual
```

And the TaskRun succeeded :thinking: so I think something else might be going on :thinking: , maybe related to the version of kube you're using like @vbatts said? (Maybe https://github.com/moby/moby/issues/30097 is related?)
