### ISSUE TITLE
Access paths to input/output resources via templating

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#626]
# Expected Behavior

When creating Tasks that use inputs and outputs, it's important to know what the path is to them on disk. It would be cool to obtain the path via templating, e.g.:

```
kind: Task
metadata:
  name: publish-tekton-pipelines
spec:
  inputs:
    resources:
    - name: source
      type: git
    - name: bucket
      type: storage
  outputs:
    resources:
    - name: bucket
      type: storage
  - name: run-ko
    image: golang
    workingDir: ${inputs.resources.source.path}
    env:
    - name: KO_DOCKER_REPO
      value: ${inputs.params.imageRegistry}
    command:
    - /bin/sh
    args:
    - -ce
    - |
      ${resources.rootPath} resolve --preserve-import-paths -f config/ > ${inputs.resources.bucket.path}/latest/release.yaml
```

_This could also mean that in the future maybe changes could be made to this path without affecting users (e.g. randomizing it)?_

# Actual Behavior

In order to know where to find the files provided by inputs or where to put files required by outputs, users have to look at [the docs for inputs](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#input-resources) and [the docs for outputs](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#outputs) and hardcode the paths, like this:

```
kind: Task
metadata:
  name: publish-tekton-pipelines
spec:
  inputs:
    resources:
    - name: source
      type: git
    - name: bucket
      type: storage
  outputs:
    resources:
    - name: bucket
      type: storage
  - name: run-ko
    image: golang
    workingDir: "/workspace/source"
    env:
    - name: KO_DOCKER_REPO
      value: ${inputs.params.imageRegistry}
    command:
    - /bin/sh
    args:
    - -ce
    - |
      /workspace/ko resolve --preserve-import-paths -f config/ > /workspace/bucket/latest/release.yaml
```

# Additional info

This issue would entail making available something like:

- ${resources.rootPath} <-- maybe this is too far? the idea is templating the value of `/workspace`
- ${inputs.resources.someresource.path}
- ${outputs.resources.someresource.path}
