### ISSUE TITLE
Incorrect templating should result in error

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#627]
# Expected Behavior
Whenever a user uses `${}` templating syntax in their Task, if the value within the {} can't be resolved, an error should be returned to the user and the execution of any related TaskRuns or PipelineRuns should stop.

# Actual Behavior

With these output resources:
```
  outputs:
    resources:
    - name: bucket
      type: storage
    - name: builtBaseImage
      type: image
    - name: builtEntrypointImage
      type: image
    - name: builtKubeconfigWriterImage
      type: image
    - name: builtCredsInitImage
      type: image
    - name: builtGitInitImage
      type: image
    - name: builtNopImage
      type: image
    - name: builtBashImage
      type: image
    - name: builtGsutilImage
      type: image
    - name: builtControllerImage
      type: image
    - name: builtWebhookImage
      type: image
```

I tried to use this within one of my steps:

```
        ${inputs.params.pathToProject}/${outputs.resources.builtCredsInitImage}: ${inputs.params.imageRegistry}/${inputs.params.pathToProject}/build-base:latest
        ${inputs.params.pathToProject}/${outputs.resources.builtGitInitImage}: ${inputs.params.imageRegistry}/${inputs.params.pathToProject}/build-base:latest
```

Values like `${outputs.resources.builtCredsInitImage}` are incomplete b/c I actually should have been using attributes on the resource, e.g. `${outputs.resources.builtCredsInitImage.url}`.

Instead of getting an error, the pod was created and tried to execute.

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

_side note: how does a user escape the templating, if they need to literally use `${}` in their Task?_
