### ISSUE TITLE
Failed to create task run pod ... : translating TaskSpec to Pod: Get "https://index.docker.io/v2/": dial tcp 34.205.13.154:443: i/o timeout

### ISSUE THREAD

**Issue by lucienbanholzer** [tektoncd/pipeline#6286]
Dear guys,

I am running tekton-pipeline v.0.45.0 in a Kubernetes cluster v1.26.2.
When I run this task :
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: echo
      image: ubuntu
      script: |
        echo "hello"
```
-> it's working like a charm.

But when I remove the **script** instruction : 
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: echo
      image: ubuntu
```
-> I got the following error : '**_failed to create task run pod "pipelinerun-hello": translating TaskSpec to Pod: Get "https://index.docker.io/v2/": dial tcp 34.205.13.154:443: i/o timeout. Maybe missing or invalid Task default/hello_**'.

For instance I have the same problem when using kaniko task (https://hub.tekton.dev/tekton/task/kaniko) which tries to pull from gcr registry : 
**_'failed to create task run pod "build-bash-build-bash-image": translating TaskSpec to Pod: Get "https://gcr.io/v2/": dial tcp 142.251.31.82:443: i/o timeout. Maybe missing or invalid Task default/kaniko'_**

I am able to pull the exact same kaniko image from the host and from a pod within the cluster.

Do you have any idea what's the issue here ?

Thanks a lot,

BR

**Comment by pritidesai** [comment]
Thank you @lucienbanholzer for reporting this issue!

What happens when you run it with `args` but no `script`?

**Comment by pritidesai** [comment]
I ran this example without any issues on `0.45.x`:

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun
spec:
  taskSpec:
    steps:
      - name: hey
        image: ubuntu
```

```
kubectl apply -f taskrun.yaml
```

```
kubectl get tr taskrun -o json | jq .status
{
  "completionTime": "2023-03-03T17:51:06Z",
  "conditions": [
    {
      "lastTransitionTime": "2023-03-03T17:51:06Z",
      "message": "All Steps have completed executing",
      "reason": "Succeeded",
      "status": "True",
      "type": "Succeeded"
    }
  ],
  "podName": "taskrun-pod",
  "startTime": "2023-03-03T17:49:35Z",
  "steps": [
    {
      "container": "step-hey",
      "imageID": "docker-pullable://ubuntu@sha256:2adf22367284330af9f832ffefb717c78239f6251d9d0f58de50b86229ed1427",
      "name": "hey",
      "terminated": {
        "containerID": "docker://4c07c4be41716967ea1b768ea7e49b23d0ac9ef50ac12924914cb803c51a0da5",
        "exitCode": 0,
        "finishedAt": "2023-03-03T17:51:06Z",
        "reason": "Completed",
        "startedAt": "2023-03-03T17:51:06Z"
      }
    }
  ],
  "taskSpec": {
    "steps": [
      {
        "computeResources": {},
        "image": "ubuntu",
        "name": "hey"
      }
    ]
  }
}
```
