### ISSUE TITLE
Status of pending steps no longer displayed in status

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#630]
# Expected Behavior
When running `kubectl get taskruns -o yaml` for a TaskRun that is in progress, the `steps` section should display a pending status for all steps that have not yet started executing.

# Actual Behavior

Since we switched from init containers to regular containers, the `steps` section will show only completed steps and not in progress steps, for example:

```
  status:
    conditions:
    - lastTransitionTime: 2019-03-18T17:38:28Z
      reason: Building
      status: Unknown
      type: Succeeded
    podName: publish-run-pod-f761a6
    startTime: 2019-03-18T17:37:53Z
    steps:
    - terminated:
        containerID: docker://684ef788d066f5185c9bdb1e7dad2b6bb25be1e8b9aeb673cb216fe316fedf77
        exitCode: 0
        finishedAt: 2019-03-18T17:37:56Z
        reason: Completed
        startedAt: 2019-03-18T17:37:56Z
```

# Steps to Reproduce the Problem

1. Create a Task with mulitple steps
2. Create a TaskRun to invoke it
3. Run `kubectl get taskrun -o yaml <my task run>` and observe the steps
