### ISSUE TITLE
results in args

### ISSUE THREAD

**Issue by qingchuwudi** [tektoncd/pipeline#6327]
### Feature request

The `results` can be used in `command` and `env` between steps within a same task at this moment. While there is a scene to use the `results` in `args` which I have met.

### Use case

```yaml

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: busybox-task
spec:
  results:
    - name: result-test
  steps:
    - name: write-url
      image: bash:5.2.15
      script: |
        set -e
        echo -n "hello world" | tee "$(results.result-test.path)"
    - name: read-url
      image: AnotherImage:tag
      args:
        - $(results.result-test.bound)
```
