### ISSUE TITLE
support token based authenication for git pipelineresource

### ISSUE THREAD

**Issue by pickledrick** [tektoncd/pipeline#633]
# Expected Behavior

Creating a PipelineResource of type git should be able to reference secrets for token based authentication via https git access

```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: wizzbang-git
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/wizzbangcorp/wizzbang.git
    - name: revision
      value: master
  secrets:
    - fieldName: token
      secretKey: tokenKey
      secretName: git-secrets

apiVersion: v1
kind: Secret
metadata:
  name: git-secrets
data:
  tokenkey: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbX....M2ZiCg==
```

# Actual Behavior
Not yet implemented

# Additional Info
This is a proposal, as a first cut at git authentication without supporting all methods. I would like to take this up as a first issue.
