### ISSUE TITLE
affinity assistant pod no mount potTemplate volume

### ISSUE THREAD

**Issue by nzlov** [tektoncd/pipeline#6331]
# Expected Behavior
affinity assistant pod mount potTemplate volume

# Actual Behavior
affinity assistant pod not mount potTemplate volume

# Steps to Reproduce the Problem

1. pipelinerun.yaml
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-build-push-run-1678327816767
  namespace: default
  labels: {}
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: gocache
    securityContext:
      fsGroup: 65532
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"archive", BuildDate:"2023-03-01T12:14:03Z", GoVersion:"go1.20.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:32:22Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.42.0
```

![image](https://user-images.githubusercontent.com/2859981/223979327-a4b90440-cbf9-4491-b356-8873300cd423.png)
![image](https://user-images.githubusercontent.com/2859981/223979399-4be6f227-033f-4529-b24e-eb48cbe5478f.png)

**Comment by AliDev0ps** [comment]
You can try editing the `feature-flags` ConfigMap to set `disable-affinity-assistant` to `true`

**Comment by nzlov** [comment]
when `disable-affinity-assistant` is `true`.
```
Unable to attach or mount volumes: unmounted volumes=[cache], unattached volumes=[kube-api-access-bcwjt ws-g7ktw tekton-internal-steps tekton-internal-scripts tekton-internal-home cache tekton-internal-downward tekton-creds-init-home-0 tekton-internal-run-0 tekton-internal-bin tekton-internal-workspace tekton-internal-results]: timed out waiting for the condition
```

**Comment by nzlov** [comment]
Install `tekton` with `operator`.
```
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: all
  pruner:
    keep: 100
    resources:
      - pipelinerun
      - taskrun
    schedule: 0 8 * * *
  targetNamespace: tekton-pipelines
```
