### ISSUE TITLE
A Particular Param Syntax Makes Git Resolver Stop Working

### ISSUE THREAD

**Issue by XinruZhang** [tektoncd/pipeline#6365]
# Expected Behavior
Tekton controller can successfully schedule the TaskRun when using the following Param syntax for Git Resolver

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: "tr-git-resolver-"
spec:
  workspaces:
    - name: output
      emptyDir: {}
  params:
    - name: url
      value: https://github.com/tektoncd/catalog.git
    - name: revision
      value: main
  taskRef:
    resolver: git
    params:
      - name: url
        value:
          type: string
          stringVal: https://github.com/tektoncd/catalog.git
      - name: revision
        value:
          type: string
          stringVal: main
      - name: pathInRepo
        value:
          type: string
          stringVal: task/git-clone/0.8/git-clone.yaml
```
# Actual Behavior
It fails to schedule the TaskRun, error message:

```
message: 'failed to get task: error requesting remote resource: error getting
      "Git" "default/git-22641305a9f3dd8efe7d2f99769499f0": error opening file "":
      cannot open directory: /'
```

# Steps to Reproduce the Problem

1. Submit the YAML file
2. Describe the created TaskRun.

# Additional Info

## Environment

`enable-api-fields=alpha`

- Kubernetes version:

  **Output of `kubectl version`:**

```
This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9-gke.3200", GitCommit:"92ea556d4e7418d0e7b5db1ee576a73f8fc47e91", GitTreeState:"clean", BuildDate:"2023-01-20T09:29:29Z", GoVersion:"go1.18.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version`**

```
Client version: dev
Pipeline version: v0.45.0
```
## Error Logs in Tekton Controller Pod
```
{"severity":"error","timestamp":"2023-03-16T15:27:53.401Z","logger":"tekton-pipelines-controller","caller":"taskrun/taskrun.go:361","message":"Failed to determine Task spec to use for taskrun tr-git-resolver-1cfq2b: failed to get task: error requesting remote resource: error getting \"Git\" \"default/git-5f3b816bda119ef32529173400b6f525\": error opening file \"\": cannot open directory: /","commit":"d1b63d4","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"e1f2c547-30e2-4b27-8fa2-3214ad8a11c4","knative.dev/key":"default/tr-git-resolver-1cfq2b","stacktrace":"github.com/tektoncd/pipeline/pkg/reconciler/taskrun.(*Reconciler).prepare\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun.go:361\ngithub.com/tektoncd/pipeline/pkg/reconciler/taskrun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun.go:181\ngithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/reconciler.go:235\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20221123011842-b78020c16606/controller/controller.go:542\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20221123011842-b78020c16606/controller/controller.go:491"}
```

## Valid Syntax
The following syntax works:
```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: "tr-git-resolver-valid"
spec:
  workspaces:
    - name: output
      emptyDir: {}
  params:
    - name: url
      value: https://github.com/tektoncd/catalog.git
    - name: revision
      value: main
  taskRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/tektoncd/catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: task/git-clone/0.8/git-clone.yaml
```

**Comment by Yongxuanzhang** [comment]
We have discussed offline that this is not a supported syntax, shall we close this issue?

**Comment by XinruZhang** [comment]
SGTM

/close

**Comment by Yongxuanzhang** [comment]
> If this syntax isn't supported, we should deny pipelineruns and taskruns that use it. This error message is confusing-- it doesn't tell users what they can do to fix the problem. (I just ran into the same issue using this syntax in pipeline tasks.)

I think we already have docs&examples about how to use params correctly.
I wonder why did you run into this issue? Did you refer to any docs/examples? If so maybe we should fix them first.

The logic is in this function:
https://github.com/tektoncd/pipeline/blob/8541ed1d1173424e9b03684223b553da16be938f/pkg/apis/pipeline/v1beta1/param_types.go#L385 
We overwrite the unmarshaljson to support string, array and object types for the same `value`.  What you're writing here:
```
      - name: url
        value:
          type: string
          stringVal: https://github.com/tektoncd/catalog.git
```
is the `object` syntax. The object has 2 keys "type" and "stringVal".

**Comment by lbernick** [comment]
> I think we already have docs&examples about how to use params correctly. I wonder why did you run into this issue? Did you refer to any docs/examples? If so maybe we should fix them first.

I was trying to reproduce an error encountered by an internal user. However, it looks like our [API spec lists this syntax as "required"](https://github.com/tektoncd/pipeline/blob/main/docs/api-spec.md#paramvalue) which seems inconsistent with saying this syntax is unsupported? (I found this via `rg stringVal -g '*.md'`.)

> What you're writing here:
> ```
>       - name: url
>         value:
>           type: string
>           stringVal: https://github.com/tektoncd/catalog.git
> ```
> 
> is the `object` syntax. The object has 2 keys "type" and "stringVal". I think it may be hard to "tell users what to do" from code

🤯 

I thought object syntax looked like this? https://tekton.dev/docs/pipelines/tasks/#object-type

```
 - name: url
    type: object
    properties:
        type: string
        stringVal: https://github.com/tektoncd/catalog.git
```

Are there multiple supported syntaxes for object params?

The specific error I got was `param types don't match the user-specified type: [url revision]` (from [here](https://github.com/tektoncd/pipeline/blob/5deea1f5542cd1c90ea11c06094484368d69ddc3/pkg/reconciler/taskrun/validate_taskrun.go#L43-L45)), which was confusing because I thought I had specified string params and the task required string params. At the very least, we should add more detail to this error message.

Re: the git resolver, I'm not sure where this went wrong, but it seems like if it receives an object param called "pathInRepo" instead of a string param called "pathInRepo" it treats the "pathInRepo" as "/" which seems very user unfriendly
