### ISSUE TITLE
Steps are getting volume mounts from other steps

### ISSUE THREAD

**Issue by stephenc** [tektoncd/pipeline#6373]
# Expected Behavior

I should get the volume mounts for the step that I specify.

# Actual Behavior

Steps are getting the wrong volume mounts which are the same as a previous step.

I think the root cause might be here: https://github.com/tektoncd/pipeline/blob/70a2d714dcbaefb952924edf6df0c217aff80548/pkg/pod/pod.go#L283 as I suspect that if you are in the case where `toAdd` is empty, the `append` may return the same slice from the iterator... though I think that could just be a mis-reading on my behalf

# Steps to Reproduce the Problem

Working on trying to get the minimal steps. I haven't finished cleaning this up and it may not be a functional test, but it's as close to the YAML that is reproducing the issue for me as I can edit by hand right now

I have a task that is something like this:

```yaml
apiVersion: tekton.dev/v1
kind: Task
metadata:
    creationTimestamp: null
    name: test-test-3c9a407df28bbcdbe55bd21af2f05c97b79fd29ccf1a8a20f7801
spec:
    description: test
    params:
        - default: workflow_dispatch
          name: eventName
          type: string
        - default: /home/runner
          name: home
          type: string
        - name: needs_build_output_foo
          type: string
        - name: needs_build_result
          type: string
    results:
        - name: status
          type: string
    stepTemplate:
        computeResources: {}
        volumeMounts:
            - mountPath: $(params.home)/sbin
              name: sbin
              readOnly: true
            - mountPath: $(params.home)
              name: home
            - mountPath: $(params.home)/var/event.json
              name: event
              readOnly: true
              subPath: event.json
        workingDir: $(params.home)/workspace
    steps:
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          name: steps1
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/state
              name: state-s1
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          imagePullPolicy: Never
          name: step--run
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-0/s1
              name: state-s1
              readOnly: true
            - mountPath: $(params.home)/var/with
              name: inputs-fooactionsfirstyaml
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          name: stepfooactionsfirstyaml-s1
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionsfirstyaml
              readOnly: true
            - mountPath: $(params.home)/var/state
              name: state-fooactionsfirstyamls1-e56457c408805b33bccee9465fabd
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          imagePullPolicy: Never
          name: stepfooactionsfirstyaml
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-1/s1
              name: state-fooactionsfirstyamls1-e56457c408805b33bccee9465fabd
              readOnly: true
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionsfirstyaml
              readOnly: true
            - mountPath: $(params.home)/var/with
              name: inputs-fooactionssecondyaml
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          name: stepfooactionssecondyaml-s1
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionssecondyaml
              readOnly: true
            - mountPath: $(params.home)/var/state
              name: state-fooactionssecondyamls1-7dbaa632b88e349a08a9d3b89637
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          imagePullPolicy: Never
          name: stepfooactionssecondyaml
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-2/s1
              name: state-fooactionssecondyamls1-7dbaa632b88e349a08a9d3b89637
              readOnly: true
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionssecondyaml
              readOnly: true
            - mountPath: $(params.home)/var/state
              name: state-fooactionsfirstyamls2-42cfc2b2edd3d2cf335f46c323d0e
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          name: stepfooactionsfirstyaml-2
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-3/s1
              name: state-fooactionsfirstyamls1-e56457c408805b33bccee9465fabd
              readOnly: true
            - mountPath: $(params.home)/var/steps-3/s2
              name: state-fooactionsfirstyamls2-42cfc2b2edd3d2cf335f46c323d0e
              readOnly: true
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionsfirstyaml
              readOnly: true
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          imagePullPolicy: Never
          name: stepfooactionsfirstyaml-3
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-4/s1
              name: state-fooactionsfirstyamls1-e56457c408805b33bccee9465fabd
              readOnly: true
            - mountPath: $(params.home)/var/steps-4/s2
              name: state-fooactionsfirstyamls2-42cfc2b2edd3d2cf335f46c323d0e
              readOnly: true
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionsfirstyaml
              readOnly: true
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          imagePullPolicy: Never
          name: step--run-2
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-5/s1
              name: state-s1
              readOnly: true
            - mountPath: $(params.home)/var/with
              name: inputs-fooactionssecondyaml2-337af8d140bc8aabc62dfadd24c3
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          name: stepfooactionssecondyaml-2-s1
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionssecondyaml2-337af8d140bc8aabc62dfadd24c3
              readOnly: true
            - mountPath: $(params.home)/var/state
              name: state-fooactionssecondyaml2s1-aea194106fc3b4402d0aacd8ed9
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          imagePullPolicy: Never
          name: stepfooactionssecondyaml-2
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-6/s1
              name: state-fooactionssecondyaml2s1-aea194106fc3b4402d0aacd8ed9
              readOnly: true
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionssecondyaml2-337af8d140bc8aabc62dfadd24c3
              readOnly: true
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          imagePullPolicy: Never
          name: step--run-3
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-7/s1
              name: state-s1
              readOnly: true
            - mountPath: $(params.home)/var/with
              name: inputs-fooactionssecondyaml3-b743709819c6f07beac2c860aa3b
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          name: stepfooactionssecondyaml-3-s1
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionssecondyaml3-b743709819c6f07beac2c860aa3b
              readOnly: true
            - mountPath: $(params.home)/var/state
              name: state-fooactionssecondyaml3s1-77f8a545e3cf0829197392edba8
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          imagePullPolicy: Never
          name: stepfooactionssecondyaml-3
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-8/s1
              name: state-fooactionssecondyaml3s1-77f8a545e3cf0829197392edba8
              readOnly: true
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionssecondyaml3-b743709819c6f07beac2c860aa3b
              readOnly: true
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          imagePullPolicy: Never
          name: step--run-4
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-9/s1
              name: state-s1
              readOnly: true
            - mountPath: $(params.home)/var/with
              name: inputs-fooactionsfirstyaml2-78427d02ce7e28440b543047a1d49
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          name: stepfooactionsfirstyaml-2-s1
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionsfirstyaml2-78427d02ce7e28440b543047a1d49
              readOnly: true
            - mountPath: $(params.home)/var/state
              name: state-fooactionsfirstyaml2s1-0a86de14517d7378aa4d46d20caa
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          imagePullPolicy: Never
          name: stepfooactionsfirstyaml-2-2
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-10/s1
              name: state-fooactionsfirstyaml2s1-0a86de14517d7378aa4d46d20caa
              readOnly: true
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionsfirstyaml2-78427d02ce7e28440b543047a1d49
              readOnly: true
            - mountPath: $(params.home)/var/with
              name: inputs-fooactionssecondyaml4-f0436eac861647726e141a628e64
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          name: stepfooactionssecondyaml-4-s1
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionssecondyaml4-f0436eac861647726e141a628e64
              readOnly: true
            - mountPath: $(params.home)/var/state
              name: state-fooactionssecondyaml4s1-4eceec73b11f30970d1abc3c46d
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          imagePullPolicy: Never
          name: stepfooactionssecondyaml-4
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-11/s1
              name: state-fooactionssecondyaml4s1-4eceec73b11f30970d1abc3c46d
              readOnly: true
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionssecondyaml4-f0436eac861647726e141a628e64
              readOnly: true
            - mountPath: $(params.home)/var/state
              name: state-fooactionsfirstyaml2s2-e94997f47e66fe37432a4ca30a7d
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          name: stepfooactionsfirstyaml-2-3
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-12/s1
              name: state-fooactionsfirstyaml2s1-0a86de14517d7378aa4d46d20caa
              readOnly: true
            - mountPath: $(params.home)/var/steps-12/s2
              name: state-fooactionsfirstyaml2s2-e94997f47e66fe37432a4ca30a7d
              readOnly: true
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionsfirstyaml2-78427d02ce7e28440b543047a1d49
              readOnly: true
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          imagePullPolicy: Never
          name: stepfooactionsfirstyaml-2-s2
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-13/s1
              name: state-fooactionsfirstyaml2s1-0a86de14517d7378aa4d46d20caa
              readOnly: true
            - mountPath: $(params.home)/var/inputs
              name: inputs-fooactionsfirstyaml2-78427d02ce7e28440b543047a1d49
              readOnly: true
            - mountPath: $(params.home)/var/state
              name: state-s2
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          name: step--run-5
          onError: continue
          volumeMounts:
            - mountPath: $(params.home)/var/steps-14/s1
              name: state-s1
              readOnly: true
            - mountPath: $(params.home)/var/steps-14/s2
              name: state-s2
              readOnly: true
          workingDir: $(params.home)/workspace
        - script: ls -lRa $(params.home)
          computeResources: {}
          image: alpine:latest
          imagePullPolicy: Never
          name: step--run-6
          volumeMounts:
            - mountPath: $(params.home)/var/steps-15/s2
              name: state-s2
              readOnly: true
            - mountPath: $(params.home)/var/steps-15/s1
              name: state-s1
              readOnly: true
          workingDir: $(params.home)/workspace
    volumes:
        - configMap:
            name: test-event-35c9df848e0817e4c879b8cd5ba797c53a26877c9bf1899139b6
          name: event
        - emptyDir: {}
          name: home
        - emptyDir: {}
          name: inputs-fooactionsfirstyaml
        - emptyDir: {}
          name: inputs-fooactionsfirstyaml2-78427d02ce7e28440b543047a1d49
        - emptyDir: {}
          name: inputs-fooactionssecondyaml
        - emptyDir: {}
          name: inputs-fooactionssecondyaml2-337af8d140bc8aabc62dfadd24c3
        - emptyDir: {}
          name: inputs-fooactionssecondyaml3-b743709819c6f07beac2c860aa3b
        - emptyDir: {}
          name: inputs-fooactionssecondyaml4-f0436eac861647726e141a628e64
        - emptyDir: {}
          name: sbin
        - emptyDir: {}
          name: state-fooactionsfirstyaml2s1-0a86de14517d7378aa4d46d20caa
        - emptyDir: {}
          name: state-fooactionsfirstyaml2s2-e94997f47e66fe37432a4ca30a7d
        - emptyDir: {}
          name: state-fooactionsfirstyamls1-e56457c408805b33bccee9465fabd
        - emptyDir: {}
          name: state-fooactionsfirstyamls2-42cfc2b2edd3d2cf335f46c323d0e
        - emptyDir: {}
          name: state-fooactionssecondyaml2s1-aea194106fc3b4402d0aacd8ed9
        - emptyDir: {}
          name: state-fooactionssecondyaml3s1-77f8a545e3cf0829197392edba8
        - emptyDir: {}
          name: state-fooactionssecondyaml4s1-4eceec73b11f30970d1abc3c46d
        - emptyDir: {}
          name: state-fooactionssecondyamls1-7dbaa632b88e349a08a9d3b89637
        - emptyDir: {}
          name: state-s1
        - emptyDir: {}
          name: state-s2
```

And then when I look at `stepfooactionsfirstyaml-2-s1` in Tekton Dashboard I will see on the details tab:

```yaml
name: stepfooactionsfirstyaml-2-s1
resources: {}
volumeMounts:  
  - mountPath: /home/runner/sbin
    name: sbin
    readOnly: true  
  - mountPath: /home/runner
    name: home
  - mountPath: /home/runner/var/event.json
    name: event
    readOnly: true    
    subPath: event.json
  - mountPath: /home/runner/var/state
    name: state-fooactionsfirstyaml2s1-0a86de14517d7378aa4d46d20caa
  - mountPath: /home/runner/var/steps-13/s1
    name: state-fooactionsfirstyaml2s1-0a86de14517d7378aa4d46d20caa
    readOnly: true
  - mountPath: /home/runner/var/inputs
    name: inputs-fooactionsfirstyaml2-78427d02ce7e28440b543047a1d49
    readOnly: true  
  - mountPath: /home/runner/var/steps-12/s1
    name: state-fooactionsfirstyaml2s1-0a86de14517d7378aa4d46d20caa
    readOnly: true
  - mountPath: /home/runner/var/steps-12/s2
    name: state-fooactionsfirstyaml2s2-e94997f47e66fe37432a4ca30a7d
    readOnly: true
  - mountPath: /home/runner/var/steps-11/s1
    name: state-fooactionssecondyaml4s1-4eceec73b11f30970d1abc3c46d
    readOnly: true
  - mountPath: /home/runner/var/steps-10/s1
    name: state-fooactionsfirstyaml2s1-0a86de14517d7378aa4d46d20caa
    readOnly: true
  - mountPath: /home/runner/var/with
    name: inputs-fooactionssecondyaml4-f0436eac861647726e141a628e64
workingDir: /home/runner/workspace
script:  ls -lRA /home/runner
image: alpine:latest
onError: continue
```

Which seems like far far too many mounts

I am expecting to see

```yaml
  - mountPath: /home/runner/sbin
    name: sbin
    readOnly: true  
  - mountPath: /home/runner
    name: home
  - mountPath: /home/runner/var/event.json
    name: event
    readOnly: true    
    subPath: event.json
  - mountPath: $(params.home)/var/inputs
    name: inputs-fooactionsfirstyaml2-78427d02ce7e28440b543047a1d49
    readOnly: true
  - mountPath: $(params.home)/var/state
    name: state-fooactionsfirstyaml2s1-0a86de14517d7378aa4d46d20caa
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
(Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
``

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.45.0
```


<!-- Any other additional information -->

**Comment by stephenc** [comment]
The plot thickens.

I don't know if it is Tekton Dashboard that has the issue.

Using the following trimmed down YAML I can reproduce the strange reporting I have seen in Tekton Dashboard:

```yaml
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: issue-6373
spec:
  description: build
  stepTemplate:
    computeResources: { }
    volumeMounts:
      - mountPath: /foo/bar
        name: vol-1
        readOnly: true
      - mountPath: /foo/manchu
        name: vol-2
    workingDir: /foo
  steps:
    - name: step-1
      image: alpine:latest
      volumeMounts:
        - mountPath: /foo/step-1
          name: vol-3
        - mountPath: /foo/step-1/a
          name: vol-6
        - mountPath: /foo/step-1/b
          name: vol-7
        - mountPath: /foo/step-1/c
          name: vol-8
        - mountPath: /foo/step-1/d
          name: vol-9
      workingDir: /foo
      script: ls -lRa /foo && mount
    - name: step-2
      image: alpine:latest
      volumeMounts:
        - mountPath: /foo/prev/step-1
          name: vol-3
          readOnly: true
        - mountPath: /foo/step-2
          name: vol-4
        - mountPath: /foo/step-2/a
          name: vol-6
        - mountPath: /foo/step-2/d
          name: vol-9
      workingDir: /foo
      script: ls -lRa /foo && mount
    - name: step-3
      image: alpine:latest
      volumeMounts:
        - mountPath: /foo/step-3
          name: vol-5
      workingDir: /foo
      script: ls -lRa /foo && mount
  volumes:
    - name: vol-1
      emptyDir: { }
    - name: vol-2
      emptyDir: { }
    - name: vol-3
      emptyDir: { }
    - name: vol-4
      emptyDir: { }
    - name: vol-5
      emptyDir: { }
    - name: vol-6
      emptyDir:  {}
    - name: vol-7
      emptyDir: { }
    - name: vol-8
      emptyDir: { }
    - name: vol-9
      emptyDir: { }
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: issue-6373
spec:
  taskRef:
    name: issue-6373
```

As can be verified in the following GIF:
![issue-6373](https://user-images.githubusercontent.com/209336/226290961-698ba162-86c2-4455-abbb-16873aea2f84.gif)

Specifically the mounts in the Details tab for step 1 include mounts for step 2 and 3
<img width="1027" alt="Screenshot 2023-03-20 at 08 54 25" src="https://user-images.githubusercontent.com/209336/226291168-e782fa48-e770-4f5f-82d4-1dae6310ae57.png">

The good news is that the logs for step-1 do not seem to include those mounts:

```
/foo:
total 20
drwxr-xr-x    5 root     root          4096 Mar 20 08:47 .
drwxr-xr-x    1 root     root          4096 Mar 20 08:47 ..
drwxrwxrwx    2 root     root          4096 Mar 20 08:47 bar
drwxrwxrwx    2 root     root          4096 Mar 20 08:47 manchu
drwxrwxrwx    6 root     root          4096 Mar 20 08:47 step-1

/foo/bar:
total 8
drwxrwxrwx    2 root     root          4096 Mar 20 08:47 .
drwxr-xr-x    5 root     root          4096 Mar 20 08:47 ..

/foo/manchu:
total 8
drwxrwxrwx    2 root     root          4096 Mar 20 08:47 .
drwxr-xr-x    5 root     root          4096 Mar 20 08:47 ..

/foo/step-1:
total 24
drwxrwxrwx    6 root     root          4096 Mar 20 08:47 .
drwxr-xr-x    5 root     root          4096 Mar 20 08:47 ..
drwxrwxrwx    2 root     root          4096 Mar 20 08:47 a
drwxrwxrwx    2 root     root          4096 Mar 20 08:47 b
drwxrwxrwx    2 root     root          4096 Mar 20 08:47 c
drwxrwxrwx    2 root     root          4096 Mar 20 08:47 d

/foo/step-1/a:
total 8
drwxrwxrwx    2 root     root          4096 Mar 20 08:47 .
drwxrwxrwx    6 root     root          4096 Mar 20 08:47 ..

/foo/step-1/b:
total 8
drwxrwxrwx    2 root     root          4096 Mar 20 08:47 .
drwxrwxrwx    6 root     root          4096 Mar 20 08:47 ..

/foo/step-1/c:
total 8
drwxrwxrwx    2 root     root          4096 Mar 20 08:47 .
drwxrwxrwx    6 root     root          4096 Mar 20 08:47 ..

/foo/step-1/d:
total 8
drwxrwxrwx    2 root     root          4096 Mar 20 08:47 .
drwxrwxrwx    6 root     root          4096 Mar 20 08:47 ..
```

Similarly the pod for the TaskRun looks to have correct mounts.

I will see if I can dig further to see if this is just not a minimal reproducer... but I think there is an issue in Dashboard given this 

<img width="426" alt="Screenshot 2023-03-20 at 08 58 06" src="https://user-images.githubusercontent.com/209336/226291855-4664d449-0cd0-4405-aadc-0e192a9f16d1.png">
