### ISSUE TITLE
Pipelineruns with failed task with result fails on `PipelineValidationFailed` reason, hiding the failure

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#6383]
Given the following `PipelineRun`:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-results
spec:
  pipelineSpec:
    results:
      - name: abc
        value: "$(tasks.xxx.results.abc)"
    tasks:
    - name: xxx
      taskSpec:
        results:
          - name: abc
        steps:
        - name: update-sa
          image: bash:latest
          script: |
            echo 'test' >  $(results.abc.path)
            exit 1
```

# Expected Behavior

When a Task "with a results" in a PipelineRun fails, the PipelineRun result in a `PipelineValidationFailed` instead of saying that the `TaskRun` failed.

# Actual Behavior

When a Task "with a results" in a PipelineRun fails, the PipelineRun result in a the Pipeline failing *because* the Task failed.

# Steps to Reproduce the Problem

1. Apply the `PipelineRun` above
2. See the failure

# Additional Info

The result was written even 👼🏼 So *technically*, it has the result.

- Tekton Pipeline version: v0.45.0 (and below)

/kind bug
cc @pritidesai @jerop I think it "might be" by design, but it is confusing.
