### ISSUE TITLE
Support for variable interpolation in `workspace.*` (in `PipelineRun` and `TaskRun`)

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#6384]
### Feature request

We should be able to use variables (like `params.FOO`, or `tasks.foo.results.BAR`) in a `PipelineRun` when binding workspaces. The following "parts" of `PipelineRun` or `TaskRun` should work. Today they do not.

```yaml
workspaces:
  - name: myworkspace
    persistentVolumeClaim:
      claimName: $(params.FOO)
    subPath: $(params.BAR)
---
workspaces:
  - name: myworkspace
    configmap:
      name: $(params.MYCONFIG)
---
workspaces:
  - name: myworkspace
    secret:
      secretName: $(params.MYSECRET)
---
workspaces:
  - name: myworkspace
    projected:
      sources:
        - configMap:
            name: $(params.MYCONFIG)
        - secret:
            name: $(params.MYSECRET)
---
# probably for CSI driver as well
```

### Use case

This would allow cases where the data mounted as a workspace can be dependent on a parameters of the PipelineRun or TaskRun. An example is for mounting a different secret depending on the PipelineRun, depending on some parameters (for example, the repository that is gonna be fetch, etc..)
