### ISSUE TITLE
Allow for images output by one Task to be used by steps of downstream Tasks

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#639]
# Expected Behavior

Sometimes folks need to be able to build an image, which later they need to run as part of their CI/CD. For example, say you need an image (like we did for https://github.com/tektoncd/pipeline/pull/632) that has:

* gcloud
* ko
* golang

You might not be able to find a published and supported image that meets your exact needs, so you might need to build and publish your own. It would be great to have the option to do this as part of your CI/CD pipeline, e.g. something like:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  resources:
  - name: source-repo
    type: git
  - name: ko-image
    type: image
  tasks:
  - name: build-ko-image
    taskRef:
      name: ko-image-builder
    resources:
      inputs:
      - name: workspace
        resource: source-repo
      outputs:
      - name: builtImage
        resource: ko-image
  - name: use-ko-image
    taskRef:
      name: run-ko
    resources:
      inputs:
      - name: workspace
        resource: source-repo
      - name: builtImage
        resource: web-image
        from: [build-ko-image]
```

Where the `run-ko` Task looks something like:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run-ko
spec:
  inputs:
    resources:
    - name: workspace
      type: git
    - name: ko-image
      type: image
  steps:
  - name: build-and-push
    image: ${inputs.resources.ko-image.url}@${inputs.resources.ko-image.digest}
    command:
       ... 
```

`image: ${inputs.resources.ko-image.url}@${inputs.resources.ko-image.digest}` would allow the Task to use an image which is actually an input resource

# Actual Behavior

The only way to do this now would be to make the above Task something like:

```yaml
```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run-ko
spec:
  inputs:
    resources:
    - name: workspace
      type: git
  steps:
  - name: build-and-push
    image: my-ko-image
    command:
       ... 
```
```

And hope that `my-ko-image:latest` happens to be the one that was built by the previous Task.

# Additional Info

* https://github.com/tektoncd/pipeline/issues/216 is about adding Image outputs
