### ISSUE TITLE
it contains Tasks that don't exist: Couldn't retrieve Task ""

### ISSUE THREAD

**Issue by jihwong** [tektoncd/pipeline#6408]
# Expected Behavior
Expect pipelinerun to run normally
# Actual Behavior
Running again is normal, and this error occasionally occurs.

Discover through webhook logs. Creating a resolutionrequest normally will result in three `"knative.dev/operation":"CREATE"` records. But the `cluster-564cb716f353f3b29acf2eeae11d0d07` has six records
```
#k logs -n tekton-pipelines tekton-pipelines-webhook-696cb8f894-kvwg8 |grep 6c189aca7abcb406496e8aa9bbb5fd5d|grep CREATE|wc -l
3

#k logs -n tekton-pipelines tekton-pipelines-webhook-696cb8f894-kvwg8 |grep 564cb716f353f3b29acf2eeae11d0d07 |grep CREATE|wc -l
6
```
resolutionrequests (There are usually three records, but an error occurs when the second record is created)
```
#k get resolutionrequests -n NAMESPACE |grep XXX
cluster-564cb716f353f3b29acf2eeae11d0d07   PipelineRun   XXX   True                 2023-03-20T15:26:16Z   2023-03-20T15:26:16Z
cluster-5ed0564a1b690a9c48c1da7294932a56   PipelineRun   XXX   True                 2023-03-20T15:26:15Z   2023-03-20T15:26:15Z
```
pipelinerun.status content
```
status:
  completionTime: "2023-03-20T15:26:16Z"
  conditions:
  - lastTransitionTime: "2023-03-20T15:26:16Z"
    message: 'Pipeline NAMESPACE/PIPELINERUN_NAME can''t be Run; it contains
      Tasks that don''t exist: Couldn''t retrieve Task "": error requesting remote
      resource: resolutionrequests.resolution.tekton.dev "cluster-564cb716f353f3b29acf2eeae11d0d07"
      already exists'
    reason: CouldntGetTask
    status: "False"
    type: Succeeded
```

# Additional Info
- Tekton Pipeline version: 
v0.41.0
