### ISSUE TITLE
taskRun timeout overwrite failure

### ISSUE THREAD

**Issue by TianxiangShen** [tektoncd/pipeline#6419]
# Expected Behavior
Based on the doc, I'm expecting use `pipeline.spec.tasks[].timeout` to overwrite the field in pipelinerun `spec.timeouts`

# Actual Behavior
The created taskrun timed out based onthe field in pipelinerun `spec.timeouts`

# Steps to Reproduce the Problem
The specs I'm using:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-echo-message
spec:
  params:
  - name: MESSAGE
    type: string
    default: "Hello World"
  steps:
    - name: echo
      image: alpine/git:v2.26.2
      script: |
        sleep 15s
        echo "$(inputs.params.MESSAGE)"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-tos-v1beta1-1
spec:
  timeouts:
    pipeline: "1h0m00s"
    tasks: "0h0m25s"
  pipelineSpec:
    params:
      - name: MORNING_GREETINGS
        description: "morning greetings, default is Good Morning!"
        type: string
        default: "Good Morning!"
      - name: NIGHT_GREETINGS
        description: "Night greetings, default is Good Night!"
        type: string
        default: "Good Night!"
    tasks:
      # Task to display morning greetings
      - name: echo-good-morning
        taskRef:
          name: task-echo-message
        params:
          - name: MESSAGE
            value: $(params.MORNING_GREETINGS)
      # Task to display night greetings
      - name: echo-good-night
        taskRef:
          name: task-echo-message
        params:
          - name: MESSAGE
            value: $(params.NIGHT_GREETINGS)
        runAfter:
        - echo-good-morning
        timeout: 0h30m0s
    finally:
    - name: echo-status
      params:
        - name: echoStatus
          value: "$(tasks.echo-good-night.status)"
      taskSpec:
        params:
          - name: echoStatus
        steps:
          - name: verify-status
            image: alpine/git:v2.26.2
            script: |
              if [ $(params.echoStatus) == "Succeeded" ]
              then
                echo " Good night! echoed successfully"
              fi
  params:
    - name: MORNING_GREETINGS
      value: "Good Morning, Bob!"
    - name: NIGHT_GREETINGS
      value: "Good Night, Bob!"
```
The taskrun created:
```
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"PipelineRun","metadata":{"annotations":{},"name":"pipelinerun-tos-v1beta1-2","namespace":"tekton-dev"},"spec":{"params":[{"name":"MORNING_GREETINGS","value":"Good Morning, Bob!"},{"name":"NIGHT_GREETINGS","value":"Good Night, Bob!"}],"pipelineSpec":{"finally":[{"name":"echo-status","params":[{"name":"echoStatus","value":"$(tasks.echo-good-night.status)"}],"taskSpec":{"params":[{"name":"echoStatus"}],"steps":[{"image":"alpine/git:v2.26.2","name":"verify-status","script":"if [ $(params.echoStatus) == \"Succeeded\" ]\nthen\n  echo \" Good night! echoed successfully\"\nfi\n"}]}}],"params":[{"default":"Good Morning!","description":"morning greetings, default is Good Morning!","name":"MORNING_GREETINGS","type":"string"},{"default":"Good Night!","description":"Night greetings, default is Good Night!","name":"NIGHT_GREETINGS","type":"string"}],"tasks":[{"name":"echo-good-morning","params":[{"name":"MESSAGE","value":"$(params.MORNING_GREETINGS)"}],"taskRef":{"name":"task-echo-message"}},{"name":"echo-good-night","params":[{"name":"MESSAGE","value":"$(params.NIGHT_GREETINGS)"}],"runAfter":["echo-good-morning"],"taskRef":{"name":"task-echo-message"},"timeout":"0h30m0s"}]},"timeouts":{"pipeline":"1h0m60s","tasks":"0h0m25s"}}}
    pipeline.tekton.dev/release: 6db52ca
    results.tekton.dev/record: tekton-dev/results/89b3f679-fff7-412c-a26c-888459d7e63d/records/89b3f679-fff7-412c-a26c-888459d7e63d
    results.tekton.dev/result: tekton-dev/results/89b3f679-fff7-412c-a26c-888459d7e63d
    tekton.dev/v1beta1Resources: '{}'
  creationTimestamp: "2023-03-21T22:34:38Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
    tekton.dev/memberOf: tasks
    tekton.dev/pipeline: pipelinerun-tos-v1beta1-2
    tekton.dev/pipelineRun: pipelinerun-tos-v1beta1-2
    tekton.dev/pipelineTask: echo-good-night
    tekton.dev/task: task-echo-message
  name: pipelinerun-tos-v1beta1-2-echo-good-night
  namespace: tekton-dev
  ownerReferences:
  - apiVersion: tekton.dev/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: PipelineRun
    name: pipelinerun-tos-v1beta1-2
    uid: 89b3f679-fff7-412c-a26c-888459d7e63d
  ...
spec:
  params:
  - name: MESSAGE
    value: Good Night, Bob!
  serviceAccountName: default
  status: TaskRunCancelled
  statusMessage: TaskRun cancelled as the PipelineRun it belongs to has timed out.
  taskRef:
    kind: Task
    name: task-echo-message
  timeout: 30m0s
status:
  completionTime: "2023-03-21T22:34:43Z"
  conditions:
  - lastTransitionTime: "2023-03-21T22:34:43Z"
    message: TaskRun "pipelinerun-tos-v1beta1-2-echo-good-night" was cancelled. TaskRun
      cancelled as the PipelineRun it belongs to has timed out.
    reason: TaskRunCancelled
    status: "False"
    type: Succeeded
  podName: pipelinerun-tos-v1beta1-2-echo-good-night-pod
  startTime: "2023-03-21T22:34:38Z"
  steps:
  - container: step-echo
    name: echo
    terminated:
      exitCode: 1
      finishedAt: "2023-03-21T22:34:43Z"
      reason: TaskRunCancelled
      startedAt: null
  taskSpec:
    params:
    - default: Hello World
      name: MESSAGE
      type: string
    steps:
    - computeResources: {}
      image: alpine/git:v2.26.2
      name: echo
      script: |
        sleep 10s
        echo "Good Night, Bob!"
```
I noticed the taskrun is first created with apiVersion: `tekton.dev/v1beta1` (from the annotation: `kubectl.kubernetes.io/last-applied-configuration`), but then was changed to `tekton.dev/v1`, I'm not sure if this is related, since `timeout` is deprecated in apiVersion V1.

# Additional Info

- Kubernetes version: 1.18

- Tekton Pipeline version:0.44.0

**Comment by AlanGreene** [comment]
The PipelineRun `timeouts.tasks` is the cumulative timeout for all non-finally tasks, not for each individual task.

The documentation has been updated to clarify this in https://github.com/tektoncd/pipeline/pull/6171

**Comment by TianxiangShen** [comment]
@AlanGreene Thanks for the reply, I understand this part. But my question is I'm expecting using field `pipeline.spec.tasks[].timeout` to overwrite the field `spec.timeouts.tasks`, is this correct?
```
      tasks:
      - name: echo-good-morning
       ...
      - name: echo-good-night
        taskRef:
          name: task-echo-message
        params:
          - name: MESSAGE
            value: $(params.NIGHT_GREETINGS)
        runAfter:
        - echo-good-morning
        timeout: 0h30m0s
```
