### ISSUE TITLE
[v0.44.x] embedded-status is ignored.

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#6437]
# Expected Behavior

When I set `embedded-status` to `boh` in 0.44.x, I am assuming I will see both "status" reported, aka in `taskruns` and in `childReferences`.

# Actual Behavior

When I set `embedded-status` to `boh` in 0.44.x, only `childReferences` is populated.

```
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
# […]
spec:
# […]
status:
  childReferences:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    name: demo-pipeline-run-4-cluster-task-pipeline-4
    pipelineTaskName: cluster-task-pipeline-4
  completionTime: "2023-03-27T15:38:06Z"
  conditions:
  - lastTransitionTime: "2023-03-27T15:38:06Z"
    message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
    reason: Succeeded
    status: "True"
    type: Succeeded
  pipelineSpec:
    tasks:
    - name: cluster-task-pipeline-4
      taskRef:
        kind: ClusterTask
        name: cluster-task-pipeline-4
  startTime: "2023-03-27T15:37:44Z"
```

# Steps to Reproduce the Problem

1. Edit the `feature-flags` configmap to set `embedded-status` to `both`
2. Run a `PipelineRun`
3. Watch the status

# Additional Info

`embedded-status` is removed in 0.45.x but it is supposed to work as intended up to that point. As `0.44` is an LTS, we should probably fix it 👼🏼 

- Kubernetes version:
```
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-26T15:06:14Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Pipeline version: v0.44.0
```
