### ISSUE TITLE
invalid metadata of pipelinetask, cause the pipelinerun has been waiting.

### ISSUE THREAD

**Issue by cugykw** [tektoncd/pipeline#6453]
# Expected Behavior

I recently encountered a webhook verification failure again, which made it impossible to create a taskrun, and the pr has been waiting.

have a similar question: #5723.

An invalid metadata is defined in the pipelinetask, the pipelinerun should directly report failure and stop running immediately.

# Actual Behavior

the pr has been running, and did not directly report an error.

# Steps to Reproduce the Problem

```
...
  tasks:
  - name: test
    taskSpec:
      metadata: 
        labels:
          example.io/: test
...
```

Kubernetes version:
kubernetes: 1.23.1

Tekton Pipeline version:
0.41.x
