### ISSUE TITLE
Any non-empty `Kind` with empty `APIVersion` in `TaskRef` is a `Task`

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#6459]
# Expected Behavior

Setting `Kind` to any non-empty string and `APIVersion` to an empty string in a `TaskRef` will be considered a validation error.

Note that I don't expect it to be considered a `Custom Task` because `APIVersion` is empty. 

# Actual Behavior

Setting `Kind` to any non-empty string and `APIVersion` to an empty string in a `TaskRef` will be considered a `Task`, and attempt to create a `TaskRun`. This is especially a problem if `Kind` is not set to `"Task"`. 

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-
spec:
  pipelineSpec:
    tasks:
      - name: greeting
        taskRef:
          kind: Example
          name: foo
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pr-6whfx
spec:
  pipelineSpec:
    tasks:
    - name: greeting
      taskRef:
        kind: Example
        name: foo
status:
  completionTime: "2023-03-29T16:34:42Z"
  conditions:
  - lastTransitionTime: "2023-03-29T16:34:42Z"
    message: 'Pipeline default/pr-6whfx can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "foo": failed to get task: tasks.tekton.dev "foo" not found'
    reason: CouldntGetTask
    status: "False"
    type: Succeeded
  pipelineSpec:
    tasks:
    - name: greeting
      taskRef:
        kind: Example
        name: foo
```

# Steps to Reproduce the Problem

1. Create a `PipelineRun` with a `TaskRef` where the `Kind` is set to a non-empty string that's not `"Task"`
2. Observe the `PipelineRun` status
