### ISSUE TITLE
Fetching empty GCS storage bucket of type `dir` fails

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#646]
# Expected Behavior
If a user is invoking a Task that needs a GCS bucket, sometimes that bucket will be empty and will be populated by the Task.

It should be possible to fetch this empty bucket and use it in the Task.

# Actual Behavior
If you try to use [a GCS storage resource](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#gcs-storage-resource) with the `dir` flag set as an input, and the bucket is empty, the container which fetches the contents of the bucket fails with an error like:

```
Error executing command "gsutil cp -r gs://christies-empty-bucket/* /workspace/bucket" ; error exit status 1; cmd_output CommandException: No URLs matched: gs://christies-empty-bucket/*
"   
  stacktrace:  "main.main
	/Users/christiewilson/Code/go/src/github.com/tektoncd/pipeline/cmd/gsutil/main.go:94
runtime.main
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198"   
  ts:  1553120763.622061   
```

# Steps to Reproduce the Problem

1. Make an empty GCS bucket (e.g. create a new one or delete everything from an existing one)
2. Crate a GCS bucket resource, e.g.:

```
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-bucket
spec:
  type: storage
  params:
   - name: type
     value: gcs
   - name: location
     value: gs://christies-empty-bucket # REPLACE with your own bucket
   - name: dir
     value: "y
```
3. Try to use that resource as [an input to a task](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#inputs) via [a taskrun](https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#providing-resources)

# Additional Info

In https://github.com/tektoncd/pipeline/pull/632 we create a Task that operates on a bucket. If the bucket is empty, the intention is that it will create the folders it needs, and in subsequent calls it won't be empty.
