### ISSUE TITLE
Step Resource "Request" Distribution Regression

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#6525]
This was originally work done in #723 but it looks like part of the functionality was omitted during a refactor for in #4176

Since steps run sequentially we rewrite their resource "requests" to only have the max request for that resource name in one step container and zero out the requests for that resource name in the other step containers.

For example...
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: resourcerequest-taskrun
spec:
  taskSpec:
    steps:
    - name: s1
      image: alpine
      script: sleep 1
      resources:
        requests:
          memory: "32Mi"
          cpu: "250m"
    - name: s2
      image: alpine
      script: sleep 1
      resources:
        requests:
          memory: "64Mi"
          cpu: "125m"
    sidecars:
    - name: sc1
      image: alpine
      script: sleep 30
      resources:
        requests:
          memory: "32Mi"
          cpu: "250m"
    - name: sc2
      image: alpine
      script: sleep 30
      resources:
        requests:
          memory: "64Mi"
          cpu: "125m"
```
# Expected Behavior
```
Containers:
  step-s1:
    Requests:
      cpu:                250m
      memory:             0
  step-s2:
    Requests:
      cpu:                0
      memory:             64Gi
  sidecar-sc1:
    Requests:
      cpu:                250m
      memory:             32Mi
  sidecar-sc2:
    Requests:
      cpu:                125m
      memory:             64Gi
```
# Actual Behavior
```
Containers:
  step-s1:
    Requests:
      cpu:                250m
      memory:             32Mi
  step-s2:
    Requests:
      cpu:                125m
      memory:             64Gi
  sidecar-sc1:
    Requests:
      cpu:                250m
      memory:             32Mi
  sidecar-sc2:
    Requests:
      cpu:                125m
      memory:             64Gi
  ```
