### ISSUE TITLE
Tekton tag to digest conversion and Kubernetes QPS?

### ISSUE THREAD

**Issue by durera** [tektoncd/pipeline#6530]
# Expected Behavior
When I define a `Task` like so:

```yaml
  steps:
    - image: '<someimage>:$(params.version)'
      imagePullPolicy: IfNotPresent
```

I expect to see a pod created like so:

```yaml
spec:
  containers:
  - image: <someimage>:1.0.1
```

# Actual Behavior

However, Tekton seems to do some internal converstion from tag to digest and I actually get:

```yaml
spec:
  containers:
  - image: <someimage>@sha256:xxxxxxxxxxxxxxxxxxxxxxx
```

This creates a problem in busy pipelines because Tekton doesn't appear to have great error handling here, and when it hits (I assume) the QPS limit it just gives up ... resulting in a scenario where the pod never even gets created, and you can see in the Task error:

```yaml
status:
  completionTime: '2023-04-12T10:33:41Z'
  conditions:
    - lastTransitionTime: '2023-04-12T10:33:41Z'
      message: >-
        The step "unnamed-0" in TaskRun "fvtnocpd-fvt-1481-fvt-optimizer" failed
        to pull the image "". The pod errored with the message: "Back-off
        pulling image
        "<someimage>@sha256:914dab53d028dbfc7012d806d36505a80a2642f53f337b9551c64756574651b7"."
      reason: TaskRunImagePullFailed
      status: 'False'
      type: Succeeded
  podName: fvtnocpd-fvt-1481-fvt-optimizer-pod
  startTime: '2023-04-12T10:28:00Z'
  steps:
    - container: step-unnamed-0
      name: unnamed-0
      terminated:
        exitCode: 1
        finishedAt: '2023-04-12T10:33:41Z'
        reason: TaskRunImagePullFailed
        startedAt: null
```
![image](https://user-images.githubusercontent.com/4400618/231462262-12ae567e-a5de-4911-87f8-839b1a6cc603.png)

The UI shows a pod .. but the pod does not exist (neither from the command line, or if you follow the link in the console); tekton hasn't got as far as creating it yet
![image](https://user-images.githubusercontent.com/4400618/231461818-917ab50d-3fe6-4d1d-ba07-d5c8fd973b67.png)

Normally, when a QPS is kicks in, it results in a small delay before you get the image you want, and we never see any issues with image pulls when a Pod resource is created, it only occurs in whatever is happening inside Tekton before it creates the pod .. which I assume is some process of pulling the image to inspect it's digest, to then convert from tag to digest on the fly.

# Steps to Reproduce the Problem

1. Create a pipeline using multiple tasks using the same image (referenced by a label rather than digest)
2. Run pipeline in a cluster with QPS a few times until you exceed the QPS

# Additional Info

Kubernetes version:
```
Server Version: 4.12.7
Kubernetes Version: v1.25.4+18eadca
```

Tekton Pipeline version:
```
Pipeline version: v0.41.1
Triggers version: v0.22.2
Operator version: v0.63.0
```

We're running with OpenShift Pipelines version of Tekton on OCP 4.12, but we have been seeing this issue for many months across OCP 4.9, 4.10, and 4.11.  We spent a lot of time pointing the finger at infrastructure etc, but having looked more closely at this, and the fact that it's not happening to the Pods created by the Tekton Task, but is instead happening - I think - inside Tekton as part of it's process to generate the Pod template to apply on the cluster, it feels more like an issue with the way Tekton works?

Does any of this make sense/is there such a system inside Tekton for converting tags to digests?  Is there a way to turn that off via a configuration option?  We're starting to rewrite a whole pile of automation to rebase around using digests and having to convert from tags to digests before we pass the information into the PipelineRun params, but if there's a way to just configure Tekton not to do this conversion it could save us a hell of a lot of time.

I'm only guessing that we're hitting the QPS, it could be something else, but whatever the cause it appears Tekton is reaching out to get the image, which has already been pulled into the cluster many many times, to determine it's digest, and we really don't need it to do that.
