### ISSUE TITLE
Taskrun 

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#6557]
# Expected Behavior
Setting Kind to any non-empty string and APIVersion to an empty string in a Taskrun's TaskRef will be considered a validation error.
# Actual Behavior

```
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: tr
  namespace: default
spec:
  taskRef:
    kind: Example
    name: foo
status:
  completionTime: "2023-04-19T02:48:40Z"
  conditions:
  - lastTransitionTime: "2023-04-19T02:48:40Z"
    message: 'error when listing tasks for taskRun tr: failed to get task: tasks.tekton.dev
      "foo" not found'
    reason: TaskRunResolutionFailed
    status: "False"
    type: Succeeded
  podName: ""
```

# Steps to Reproduce the Problem

1. Create this example with `kubectl create -f example.yaml`
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: tr-
spec:
  taskRef:
    kind: Example
    name: foo

```
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
(paste your output here)
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
(paste your output here)
```
