### ISSUE TITLE
inconsistent ClusterTask references in V1

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#6587]
Our [docs state](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#task-vs-clustertask) that "a v1beta1 clustertask can still be referenced in a v1 pipeline".

The following taskrun succeeds:
```
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: v1-taskrun
spec:
  taskRef:
    name: my-cluster-task
    kind: ClusterTask
```

However, the following Pipeline cannot be created, even though the TaskRef is the same:
```
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: v1-pipeline
spec:
  tasks:
  - name: first
    taskRef:
      name: my-cluster-task
      kind: ClusterTask
```
Error message is 
```
Error from server (BadRequest): error when creating "/Users/leebernick/tkndefs/clustertask/v1pipelinerun.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value: custom task ref must specify apiVersion: spec.tasks[0].taskRef.apiVersion
```
(introduced in https://github.com/tektoncd/pipeline/pull/6505) -- fyi @jerop @Yongxuanzhang.

Labeling this as a bug since our docs are inconsistent with implementation, and TaskRef is inconsistent between TaskRun and PipelineRun (a separate issue https://github.com/tektoncd/pipeline/issues/6557 was created for TaskRun taskrefs, but in hindsight I think it would have been better to treat all TaskRefs the same).

**I think we need to decide whether ClusterTasks can be referenced from v1 TaskRefs** (I vote yes).

If so, we should fix this validation. There shouldn't be any work required when swapping the v1 storage version, i.e. I don't think we need to reopen https://github.com/tektoncd/pipeline/pull/6552, since we should be able to update this function [here](https://github.com/tektoncd/pipeline/blob/7d6cd810e2ea4348415be9b094d1db9deb625e3e/pkg/reconciler/taskrun/resources/taskref.go#L245-L261) to convert a clustertask into a v1 Task instead of a v1beta1 Task. (FYI @JeromeJu @dibyom)

If not, we need to update docs and disallow clustertask references in validation. I'm not sure if we want to clarify the error message returned here, or whether we'd want to treat kind "ClusterTask" as a custom task reference (this could be a bit confusing). Note that ClusterTask support [cannot be removed until July](https://github.com/tektoncd/pipeline/blob/main/docs/deprecations.md#deprecation-table).
