### ISSUE TITLE
Consume array `Results` in `Matrix`

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#6602]
In [TEP-0090: Matrix](https://github.com/tektoncd/community/blob/main/teps/0090-matrix.md), we introduced `Matrix` to support fanning out a `PipelineTask` with different combinations of `Parameters`.

This issue tracks the work to consume array `Results` in a `Matrix`, as described in [TEP-0090](https://github.com/tektoncd/community/blob/main/teps/0090-matrix.md#results). This work was scoped out as we waited for [TEP-0076: Array Results](https://github.com/tektoncd/community/blob/main/teps/0076-array-result-types.md) to land. 

```yaml
tasks:
...
- name: task-5
  taskRef:
    name: task-5
  matrix:
    params:
      - name: values
        value: (tasks.task-4.results.foo) # array
```
