### ISSUE TITLE
Params + Results with nil Properties treated differently than Params + Results with empty Properties

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#6605]
# Expected Behavior

Our API doesn't differentiate between a map being nil and a map being empty.

The following two Task result definitions should be equivalent:

```
results:
  - name: my-result
```

```
results:
  - name: my-result
    properties: {}
```

Note: this is unrelated to the result values outputted by the TaskRun.

From the [Go style guide](https://google.github.io/styleguide/go/decisions#nil-slices): "Do not create APIs that force their clients to make distinctions between nil and the empty slice." (There's no equivalent guidance for maps but it seems like it should be the same?)

If we do want to differentiate this behavior we should at least make sure to document it clearly. I'm not sure why someone would want to declare an object param/result with no properties; it doesn't seem very meaningful.
Fixed in https://github.com/tektoncd/pipeline/pull/6570 and https://github.com/tektoncd/pipeline/pull/6578.

# Actual Behavior

nil Properties -> defaults to string param/result:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nil-properties
spec:
  results:
    - name: object-results
  steps:
  - image: bash
    script: |
      echo -n "{\"IMAGE_URL\":\"ar.com\", \"IMAGE_DIGEST\":\"sha234\"}" > $(results.object-results.path)
```

```
$ k get task nil-properties -o yaml
...
spec:
  results:
  - name: object-results
    type: string
...
```

empty Properties -> defaults to object param/result
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: empty-properties
spec:
  results:
    - name: object-results
      properties: {}
  steps:
  - image: bash
    script: |
      echo -n "{\"IMAGE_URL\":\"ar.com\", \"IMAGE_DIGEST\":\"sha234\"}" > $(results.object-results.path)
```

```
$ k create -f ~/tkndefs/properties/nil-properties.yaml
Error from server (BadRequest): error when creating "/Users/leebernick/tkndefs/properties/nil-properties.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: missing field(s): spec.results[0].object-results.properties
```
