### ISSUE TITLE
Accidental support of propagated params for remote (not local) referenced pipelines

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#6670]
# Expected Behavior

- Propagated params are not supported for referenced Pipelines: https://github.com/tektoncd/community/blob/main/teps/0107-propagating-parameters.md#referenced-resources
- Validation of local Pipelines matches validation of remote Pipelines

# Actual Behavior

Creating the following Pipeline locally fails, as expected:

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: invalid
spec:
  tasks:
  - name: foo
    taskSpec:
      steps:
      - image: busybox
        script: echo $(params.abcd)
```

```
Error from server (BadRequest): error when creating "propagation/invalid-pipeline.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: non-existent variable in "echo $(params.abcd)": spec.tasks[0].taskSpec.steps[0].script
```

However, when this same Pipeline is referenced from git, the PipelineRun succeeds, with parameters propagated:

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: invalid-remote-pipeline
spec:
  params:
  - name: abcd
    value: efgh
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/lbernick/tkndefs.git
    - name: revision
      value: main
    - name: pathInRepo
      value: propagation/invalid-pipeline.yaml
```

```
$ k get pr
NAME                      SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
invalid-remote-pipeline   True        Succeeded   13m         13m

$ tkn tr logs invalid-remote-pipeline-foo
[unnamed-0] efgh
```

# Additional Info

- Kubernetes version:

```
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.24.10-gke.2300
```

- Tekton Pipeline version:

```
Client version: 0.25.0
Pipeline version: devel
Triggers version: v0.23.0
```

**Comment by chitrangpatel** [comment]
Hi @lbernick I was taking a look at this today. You example should be working fine because even without propagated parameters, this is exactly how we would declare params right? We cannot re-declare the params under the pipelineRef field. I would expect failure if there was an underlying taskRef where parameters were propagated to. Like in this [example](https://github.com/tektoncd/community/blob/main/teps/0107-propagating-parameters.md#referenced-resources).

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: invalid-remote-pipeline
spec:
  params:
  - name: abcd
    value: efgh
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/lbernick/tkndefs.git
    - name: revision
      value: main
    - name: pathInRepo
      value: propagation/invalid-pipeline.yaml
```
