### ISSUE TITLE
Allow namespace to be specified in pipelineRef

### ISSUE THREAD

**Issue by kahirokunn** [tektoncd/pipeline#6681]
### Feature request

Allow namespace to be specified in pipelineRef

### Use case

Sometimes you want to reference a commonly used pipeline, such as git clone, from several namespaces.

**Comment by kahirokunn** [comment]
The following code could have done it!

```yaml
  pipelineRef:
    resolver: cluster
    params:
    - name: kind
      value: pipeline
    - name: name
      value: build-container
    - name: namespace
      value: example-xxxx
```
