### ISSUE TITLE
ClusterTask creates CustomRun (v0.41.1 -> v0.44.2)

### ISSUE THREAD

**Issue by rh-hectormartinezdev** [tektoncd/pipeline#6682]
# Expected Behavior

I get an error/warning when I create my `ClusterTasks` or they run as normal `TaskRuns`.

# Actual Behavior

My `ClusterTasks` create `CustomRuns` instead of `TaskRuns` when I update from `v0.41.1` to `v0.44.2`.

# Steps to Reproduce the Problem

1. `minikube start --driver=kvm2 --cpus=4 --memory=6g --disk-size=30GB --embed-certs`
2. `kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.41.1/release.yaml`
3. `kubect apply --filename dummy.yaml` (file below)
4. `kubect get pipelinerun dummy` (this should complete after a while)
5. `kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.44.2/release.yaml`
6. `kubect apply --filename dummy.yaml` (file below)
7. `kubect get pipelinerun dummy` (this should hang)
8. `kubectl get customruns` (this should return a single one, called `dummy-init`)

<details>
<summary>dummy.yaml</summary>

```
# dummy.yaml
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dummy-2
  namespace: default
spec:
  tasks:
  - name: init
    params:
    - name: resource
      value: resouce
    taskRef:
      apiVersion: tekton.dev/v1beta1
      kind: ClusterTask
      name: init
    workspaces:
    - name: output
      workspace: shared
  workspaces:
  - description: Main workspace that is shared across each task in the build pipeline
    name: shared
---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: init
spec:
  workspaces:
    - name: output
  params:
  - name: resource
    type: string
  steps:
  - name: hello
    image: registry.access.redhat.com/ubi9-micro:latest
    args: ["$(params.resource)"]
    command: ["echo"]
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: dummy
spec:
  pipelineRef:
    name: dummy-2
  workspaces:
  - name: shared
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi

```

</details>

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.26.3
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.41.1

v0.44.2
```

I am trying to understand why this is happening. Thanks!
