### ISSUE TITLE
Some code blocks are not rendered properly in the documentation's PipelineRuns page

### ISSUE THREAD

**Issue by dinushchathurya** [tektoncd/pipeline#6697]
# Expected Behavior

Code blocks are rendered properly at 

- https://tekton.dev/docs/pipelines/pipelineruns/#tekton-bundles
- https://tekton.dev/docs/pipelines/pipelineruns/#mapping-serviceaccount-credentials-to-tasks
- https://tekton.dev/docs/pipelines/pipelineruns/#specifying-a-pod-template
- https://tekton.dev/docs/pipelines/pipelineruns/#specifying-taskrunspecs

# Actual Behavior

```yaml spec: pipelineRef: resolver: bundles params: - name: bundle value: docker.io/myrepo/mycatalog:v1.0 - name: name value: mypipeline - name: kind value: Pipeline ```

# Steps to Reproduce the Problem

1. Go to https://tekton.dev/docs/pipelines/pipelineruns
2. Need to add missing annotations to {{< tab >}} section

**Comment by chitrangpatel** [comment]
I think the instructions had a typo: https://tekton.dev/docs/contribute/doc-con-formatting/

https://learn.netlify.app/en/shortcodes/tabs/ shows how to resolve it.

```
{{< tabs >}}
{{< tab "v1beta1" >}}
{{< readfile file="samples/pipeline1.yaml" code="true" lang="yaml" >}}
{{< /tab >}}

{{< tab "v1" >}}
{{< readfile file="samples/pipeline2.yaml" code="true" lang="yaml" >}}
{{< /tab >}}
{{< /tabs >}}
```

Should actually be

```
{{< tabs >}}
{{% tab "v1beta1" %}}
{{< readfile file="samples/pipeline1.yaml" code="true" lang="yaml" >}}
{{% /tab %}}

{{% tab "v1" %}}
{{< readfile file="samples/pipeline2.yaml" code="true" lang="yaml" >}}
{{% /tab %}}
{{< /tabs >}}
```

After implementing the above fix to the actual docs, it is resolved
```
{{< tabs >}}
{{% tab "v1 & v1beta1" %}}
```yaml
spec:
  taskRef:
    resolver: bundles
    params:
    - name: bundle
      value: docker.io/myrepo/mycatalog
    - name: name
      value: echo-task
    - name: kind
      value: Task
```
{{% /tab %}}
```
<img width="924" alt="Screenshot 2023-05-31 at 11 48 31 AM" src="https://github.com/tektoncd/pipeline/assets/11685590/801aa053-f349-4fa3-b543-be65b6b62aa3">
