### ISSUE TITLE
No validation for workspaces referenced in Tasks

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#6699]
# Expected Behavior

If I create a Task referencing workspaces it has not declared, this task should be rejected.

# Actual Behavior

A Task referencing workspaces that don't exist should be rejected. (This doesn't apply to inline task specs in a taskrun or pipelinerun in the case of propagated parameters.)

# Steps to Reproduce the Problem

The following Task is accepted by the cluster:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: references-workspaces-dont-exist
spec:
  steps:
    - name: echo
      image: alpine
      script: |
        echo $(workspaces.abcd.path)
```

Then, create the following TaskRun:

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: references-workspaces-dont-exist
spec:
  taskRef:
    name: references-workspaces-dont-exist
```

This TaskRun succeeds with logs `/tekton/scripts/script-0-9tf2v: line 3: workspaces.abcd.path: not found`.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.24.11-gke.1000
```

- Tekton Pipeline version:

```
devel
```
