### ISSUE TITLE
Skipped task keep in pending status

### ISSUE THREAD

**Issue by eirisdg** [tektoncd/pipeline#6731]
Hi.

I think that we're missing something in the configuration, so I dont know if our case is a bug or not.
By the way, we need help, so... could you help us?

We are creating a pipeline that has some conditionals in the tasks.

For example:
```yaml
    #########################################
    ## TASK: get dockerfiles and artifacts ##
    #########################################
    - name: set-comerzzia-envs-dockers
      taskRef:
        name: set-comerzzia-envs-dockers
      runAfter:
        - maven-deploy
      params:
      [...]
      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: $(params.git-revision)
      when:
        - input: $(params.git-customer-project)
          operator: in
          values:
            - BO
```

So if ´params.git-customer-project´ is not BO, the task is skipped. That is working, but... in the task status, it stays as pending:

![image](https://github.com/tektoncd/pipeline/assets/5367659/7b4a45ba-c910-42aa-b902-efd7ce77273a)

Staying as pending results that when the task timeout happens, the pipelinerun changes from complete to pipelineruntimeout.

![image](https://github.com/tektoncd/pipeline/assets/5367659/dfd5c657-6239-4f76-be88-d6c9a7ea7935)

What are we missing?
I've seen a discussion about using "when" conditionals (https://github.com/tektoncd/pipeline/discussions/4185) and we have set the feature-flag to true, but i think is not affected.
