### ISSUE TITLE
Tekton Access Bit Bucket Repository

### ISSUE THREAD

**Issue by tppalani** [tektoncd/pipeline#6755]
# Expected Behavior

Trying to git init from the existing bitbucket repository,  to initiate this i have created PAT personal access token inside the bit bucket repository then using base64 command i encoded my PAT to inject into k8s secret.yaml file it self.

```
echo -n <key> | base64
```

When i see official blog https://tekton.dev/docs/pipelines/auth/#using-secrets-as-a-non-root-user we have document only for username and password method configuration with github annotation value.

But not sure how we can implement for bitbucket repository with what kind of annotation  we need use to access the tekton pipeline task. But note i want to use PAT only.

# Actual Behavior

```
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/docker-0: https://gcr.io # Described below
type: kubernetes.io/basic-auth
stringData:
  username: <cleartext username>
  password: <cleartext password>
 
```

# Additional Info

- Kubernetes version:

  **Output of `:**`

```
Client Version: v1.26.2-eks-a59e1f0
```

- Tekton Pipeline version: Client version: 0.31.0

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.31.0
```
