### ISSUE TITLE
Question: volumeClaimTemplate

### ISSUE THREAD

**Issue by zppinho** [tektoncd/pipeline#6773]
Is there a way to define a volumeClaimTemplate without the tekton-controller adding a suffix to the name? like in this pipelinerun spec 
```
workspaces:
  - name: shared-data
    volumeClaimTemplate:
      metadata:
        name: abc
        labels: 
          app: abc
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
```
Like this it will create a PVC with the name "abc-7w25332d129" , i would like a PVC with the name "abc"
