### ISSUE TITLE
Calculated tasks timeout is not working

### ISSUE THREAD

**Issue by SirNyeteg** [tektoncd/pipeline#6794]
# Expected Behavior
When I set pipeline timeout and finally timeout tekton should cancel any running non-finally taskruns when calculated tasks timeout elapsed.

# Actual Behavior
Tekton does not cancel the running tasks, in worst case finally tasks can't run because the pipeline timeout is also elapsed.

It won't cancel:
```
timeouts:
  finally: 1m0s
  pipeline: 2m0s
```

It will cancel:
```
timeouts:
  tasks: 1m0s
  pipeline: 2m0s
```

Both should result the same behavior.

# Steps to Reproduce the Problem

1. Create this pipelinerun:
```
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pr-echo-
spec:
  params:
  - name: HELLO
    value: "Hello World!"
  - name: BYE
    value: "Bye World!"
  pipelineSpec:
    tasks:
      - name: echo-hello
        taskSpec:
          params:
          - name: HELLO
            type: string
            default: "Hello!"
          steps:
            - name: echo
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "$(params.HELLO)"
            - name: sleep
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                date
                echo "Sleeping..."
                sleep 300
                date
    finally:
      - name: echo-bye
        taskSpec:
          params:
          - name: BYE
            type: string
            default: "Bye!"
          steps:
            - name: echo
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "$(params.BYE)"
  timeouts:
    finally: 1m0s
    pipeline: 2m0s
```
3. `echo-hello` task won't be canceled after 1 minutes and `echo-bye` won't started

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-11-02T03:22:35Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.48.0
```

# Default pipeline timeout
In my opinion, the default pipeline timeout is not correctly set. It is set to default (1h in my case) even if tasks and finally timeouts are set, leading to an invalid pipelinerun definition. Consider 2h timeouts for both tasks and finally. The unit test (`timeouts.pipeline is nil with timeouts.tasks and timeouts.finally`) for this case is also incorrect, it expects an invalid settings.
