### ISSUE TITLE
Design: Deployment build-pipeline-resource

### ISSUE THREAD

**Issue by nader-ziada** [tektoncd/pipeline#68]
The work for this task is to design this feature and present one or more proposals (before implementing).

## Expected Behavior
A common expectation of a pipeline is to deploy the created application/function on some cluster

The `deploy` resource should satisfy the following requirements:  
 * Defined as an output of a Task 
 * Can only be used as an output binding, if used as an input will have no-op
 * Can deploy the application/function using a helm chart
 * Helm chart is provided to the resource
 * Follows the standard resource interface and can be created the same way 

an example definition of a pipeline
```
kind: Pipeline
...
spec:
    tasks:
        - name: unit-test-kritis
          taskRef:
              name: make
          inputSourceBindings:
              - name: workspace
                key: kritis
          outputSourceBindings:
              - name: deploy-output
                key: deploy-to-test-cluster               
          params:
              - name: makeTarget
                value: test
```
and an example of a resource
```
 ...
apiVersion: pipeline.knative.dev/v1beta1
kind: Resource
metadata:
  name: deploy-to-test-cluster
  namespace: default
spec:  
  name: deploy-to-test-cluster
  type: deploy
  params:
  - name: cluster
    value: kritis-cluster
  ...  
```

## Actual Behavior
We have no resource currently to deploy using helm chart or otherwise

## Additional Info
 * related to #63 
 * [kritis helm docs](https://github.com/grafeas/kritis/blob/master/install.md#step-6-install-and-configure-helm) as an example
 * [kritis helm charts](https://github.com/grafeas/kritis/blob/master/kritis-charts/values.yaml)
