### ISSUE TITLE
PipelineRuns finished as Succeeded change to PipelineRunTimeout after some time

### ISSUE THREAD

**Issue by zalejus** [tektoncd/pipeline#6812]
Properly closed PipelineRuns, set as 'Succeeded', should stay in this Status till deletion.

After some time (I don't know exactly how long it takes now) PR changes its status to Failed(PipelineRunTimeout). At the same time, all TaskRuns remain correctly set as Succeeded.

```
pr1   1 hour ago    5m56s      Succeeded
pr2   2 hours ago   26m34s     Succeeded
pr3   5 hours ago   3m59s      Succeeded
pr4   2 days ago    9h39m28s   Failed(PipelineRunTimeout)
pr5   2 days ago    5h3m2s     Failed(PipelineRunTimeout)

PR describe Message:
PipelineRun "pr3" failed to finish within "2h0m0s"
```
I set the timeout to 2 hours

- Kubernetes version:
1.27

```
clientVersion:
  buildDate: "2023-05-17T14:20:07Z"
  compiler: gc
  gitCommit: 7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647
  gitTreeState: clean
  gitVersion: v1.27.2
  goVersion: go1.20.4
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-04-14T20:40:28Z"
  compiler: gc
  gitCommit: abfec7d7e55d56346a5259c9379dea9f56ba2926
  gitTreeState: clean
  gitVersion: v1.27.1-eks-2f008fe
  goVersion: go1.20.3
  major: "1"
  minor: 27+
  platform: linux/amd64
```

- Tekton Pipeline version:

```
Client version: 0.31.0
Chains version: v0.16.0
Pipeline version: v0.47.0
Triggers version: v0.24.0
Dashboard version: v0.35.0
Operator version: v0.67.0
```
