### ISSUE TITLE
Doc: How to use generate name to replay Task

### ISSUE THREAD

**Issue by skeeey** [tektoncd/pipeline#685]
# Expected Behavior

It should be possible to use [`generateName`](https://kubernetes.io/docs/reference/using-api/api-concepts/#generated-values) like functionality to create `TaskRun` yaml definitions such that the definition in a yaml file can be reapplied.

# Actual Behavior

I cannot reapply a `taskrun` when the `taskrun` fails

# Steps to Reproduce the Problem

1. apply a `taskrun` with a broken `task` reference

```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: echo-hello-world-task-run
  namespace: test
spec:
  taskRef:
    name: hello-world # this task does not exist
  trigger:
    type: manual
```

then check the `taskrun` status by `kubectl get taskrun echo-hello-world-task-run -o yaml`

```
...
status:
  conditions:
  - lastTransitionTime: 2019-03-27T05:18:49Z
    message: error when listing tasks for taskRun echo-hello-world-task-run task.tekton.dev
      "hello-world" not found
...
```

2. correct the `task` reference in `taskrun` and apply it again

```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: echo-hello-world-task-run
  namespace: test
spec:
  taskRef:
    name: echo-hello-world # this task exists
  trigger:
    type: manual
```

```
kubectl apply -f helloworld-taskrun.yaml

taskrun.tekton.dev/echo-hello-world-task-run configured
```

3. the `taskrun` still failed, **note: the task reference has been changed**

```
...

spec:
  Status: ""
  inputs: {}
  outputs: {}
  taskRef:
    kind: Task
    name: echo-hello-world # a right task reference
  trigger:
    type: manual
status:
  conditions:
  - lastTransitionTime: 2019-03-27T05:18:49Z
    message: error when listing tasks for taskRun echo-hello-world-task-run task.tekton.dev
      "nonexistent-hello-world" not found
    reason: TaskRunResolutionFailed
    status: "False"
    type: Succeeded

```

# Additional Info
