### ISSUE TITLE
Unused workspaces in PipelineRun

### ISSUE THREAD

**Issue by jimmyjones2** [tektoncd/pipeline#6856]
If I create a PipelineRun containing a workspace that is unused by the Pipeline, there are no errors and it completes successfully. I can't find this behaviour documented.

I've got a fairly generic process that creates PipelineRuns, but depending on the Pipeline chosen, some of the workspaces may be unused. It is safe to rely on this behaviour?

Example:
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-read
  namespace: default
spec:
  description: |
    This pipeline clones a git repo, then echoes the README file to the stout.
  params:
  - description: The git repo URL to clone from.
    name: repo-url
    type: string
  tasks:
  - name: fetch-source
    params:
    - name: url
      value: $(params.repo-url)
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
  - name: show-readme
    runAfter:
    - fetch-source
    taskRef:
      kind: Task
      name: show-readme
    workspaces:
    - name: source
      workspace: shared-data
  workspaces:
  - description: |
      This workspace contains the cloned repo files, so they can be read by the
      next task.
    name: shared-data
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-read-run-
  namespace: default
spec:
  params:
  - name: repo-url
    value: https://github.com/tektoncd/website.git
  pipelineRef:
    name: clone-read
  podTemplate:
    securityContext:
      fsGroup: 65532
  serviceAccountName: default
  timeout: 1h0m0s
  workspaces:
  - name: foo
    configMap:
      name: foo
  - name: shared-data
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
```
