### ISSUE TITLE
set-security-context flag set to true does not work in tekton-pipelines namespace!

### ISSUE THREAD

**Issue by AliDev0ps** [tektoncd/pipeline#6867]
Tekton version: 
- v0.49.0

Question:
1. Pod creation in tekton-pipelines namespace is limited，when running pipelineruns, taskrun execution fails!
2. Do I have to add the `containers.securityContext` configuration manually?
3. Or change the namespace labels to `pod-security.kubernetes.io/warn: restricted` ?

Taskrun:
```bash
$ kubectl get taskrun -n tekton-pipelines pipelinerun-pfjr4-git-clone -o yaml

...
status:
  conditions:
  - lastTransitionTime: "2023-06-26T09:12:53Z"
    message: 'pods "pipelinerun-pfjr4-git-clone-pod" is forbidden: violates
      PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container
      "step-clone" must set securityContext.allowPrivilegeEscalation=false), unrestricted
      capabilities (container "step-clone" must set securityContext.capabilities.drop=["ALL"]),
      runAsNonRoot != true (pod or container "step-clone" must set securityContext.runAsNonRoot=true),
      seccompProfile (pod or container "step-clone" must set securityContext.seccompProfile.type
      to "RuntimeDefault" or "Localhost")'
    reason: PodAdmissionFailed
    status: "False"
    type: Succeeded
  ...
  provenance:
    featureFlags:
      AwaitSidecarReadiness: true
      DisableAffinityAssistant: true
      DisableCredsInit: false
      EnableAPIFields: beta
      EnableProvenanceInStatus: true
      EnableTektonOCIBundles: false
      EnforceNonfalsifiability: ""
      MaxResultSize: 4096
      RequireGitSSHSecretKnownHosts: false
      ResultExtractionMethod: termination-message
      RunningInEnvWithInjectedSidecars: true
      ScopeWhenExpressionsToTask: false
      SendCloudEventsForRuns: false
      SetSecurityContext: true
      VerificationNoMatchPolicy: ignore
```

feature-flags:
```bash
$ kubectl get cm -n tekton-pipelines feature-flags -o yaml

apiVersion: v1
data:
  await-sidecar-readiness: "true"
  disable-affinity-assistant: "true"
  disable-creds-init: "false"
  enable-api-fields: beta
  enable-provenance-in-status: "true"
  enable-tekton-oci-bundles: "false"
  enforce-nonfalsifiablity: none
  require-git-ssh-secret-known-hosts: "false"
  results-from: termination-message
  running-in-environment-with-injected-sidecars: "true"
  send-cloudevents-for-runs: "false"
  set-security-context: "true"
  trusted-resources-verification-no-match-policy: ignore
kind: ConfigMap
```

After changing the namespace labels to `pod-security.kubernetes.io/warn: restricted`, I successfully created the Pod and checked the Pod manifests to see that set-security-context was in effect and the `securityContext` was injected into the initContainers, However, the containers are not injected with `securityContext`.

**Comment by AliDev0ps** [comment]
Thanks for the reply, my problem is solved !

Without modifying namespace labels, you must enable `set-security-context` and add the `securityContext` configuration to `Task.spec.steps`

For example:

edit feature-flags configmap:
```bash
$ kubectl patch cm feature-flags -n tekton-pipelines -p '{"data":{"set-security-context":"true"}}'
```

task:
```yaml
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-pipelines
spec:
  steps:
    - name: clone
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
```

But I have a question, why not support injecting securityContext for user-defined containers? Is it considered to support this feature?

**Comment by AliDev0ps** [comment]
> Hi @AliDev0ps, thanks for your question. set-security-context only applies to init containers and sidecar containers injected by Tekton, not step/sidecar containers specified by the user. So what you are seeing is expected behavior. Here's an [example of setting security context on a step](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#running-step-containers-as-a-non-root-user) and one [for the pod](https://github.com/tektoncd/pipeline/blob/main/docs/podtemplates.md). Running taskruns and pipelineruns in the tekton-pipelines namespace is not recommended. Please feel free to reopen if you have additional questions!

Thanks for the reply, my problem is solved !

Without modifying namespace labels, you must enable `set-security-context` and add the `securityContext` configuration to `Task.spec.steps`

For example:

- edit feature-flags configmap:

  ```bash
  $ kubectl patch cm feature-flags -n tekton-pipelines -p '{"data":{"set-security-context":"true"}}'
  ```

- task:

  ```yaml
  apiVersion: tekton.dev/v1
  kind: Task
  metadata:
    name: git-clone
    namespace: tekton-pipelines
  spec:
    steps:
      - name: clone
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
  ```

But I have a question, why not support injecting securityContext for user-defined containers? Is it considered to support this feature?
