### ISSUE TITLE
Local filesystem resolver

### ISSUE THREAD

**Issue by ileixe** [tektoncd/pipeline#6899]
### Feature request

I'd like to refer Task via file path. 

Pseudo syntax

```
  - name: run
    taskRef:
      resolver: file
      params:
      - name: path
        value: ./task.yaml
```

### Use case

Currently, we should create Task before to refer, and it makes difficult to sync up. I think simple file resolver can make it better.
