### ISSUE TITLE
Improve Validation for a PipelineTask Spec Error Type

### ISSUE THREAD

**Issue by EmmaMunley** [tektoncd/pipeline#6945]
# Expected Behavior

The following would say something like "pt2-with-result" has an unknown field `type`. Only `name` and `value` can be defined in the Pipelinetask.
```
- name: pt2-with-result
      params:
        - name: versions
           type: array
```

# Actual Behavior

Current Error returned: `Error calling MarshalJSON for type v1.ParamValue: impossible ParamValues.Type: ""`

# Steps to Reproduce the Problem

Pipeline Spec
```
`metadata:
  name: %s
  namespace: %s
spec:
  tasks:
    - name: pt1-with-result
      params:
        - name: GOARCHs
          type: array
      taskRef:
        name: task1withresults
        kind: Task
    - name: pt2-with-result
      params:
        - name: versions
          type: array
      taskRef:
        name: task2withresults
        kind: Task
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.31.1
Pipeline version: devel
```
