### ISSUE TITLE
Matrix parameter with array result value

### ISSUE THREAD

**Issue by yeplaa** [tektoncd/pipeline#6949]
# Expected Behavior

From a first task, i retrieve a list of directory from the container stdout. I use the Results feature to retrieve this values and load to param matrix. I need to perform a loop and create a container by directory. 

# Actual Behavior

Currently, the Results of type Array loaded by matrix parameter fail. I have this error message : 
`Error from server (BadRequest): error when creating "pipelinefull.yml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: matrix parameters cannot contain whole array result references: spec.pipelineSpec.tasks[1].matrix.params[0]`

The doc seems indicate that is supported ( cf https://tekton.dev/docs/pipelines/matrix/#results-in-matrixincludeparams), but could you confirm please? 

# Steps to Reproduce the Problem

Bellow are my configuration : 

```
apiVersion: tekton.dev/v1
kind: Task
metadata:
 name: gcs-generic
spec:
 description: >-
  A Task that allows users to customize and extend the gsutil
  command line based on their needs. 
 params:
 - name: command
   description: The command line that you would like to enter.
   type: array
 - name: image
   description: google cloud image that will be used in steps.
   type: string
   default: google/cloud-sdk:slim
 results:
   - name: gcs-generic
 workspaces:
   - name: frame
 steps:
 - name: run-gsutil
   image: "$(params.image)"
   command: [/bin/sh]
   args: ["-c", "$(params.command[*])"]
```

```
apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test
spec:
  workspaces:
    - name: frame
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  pipelineSpec:
    workspaces:
      - name: frame
    tasks:
      - name: gcs-list
        taskRef:
          name: gcs-generic
        workspaces:
          - name: frame
        params:
        - name: command
          value:
          - "gsutil ls gs://<bucket>/images/ | awk -F/ '{print $6}' | tee $(results.gcs-generic.path)"
      - name: test-parallelism
        runAfter:
          - gcs-list
        matrix:
          params:
            - name: directo
              value: 
               - ["$(tasks.gcs-list.results.gcs-generic[*])"]
        taskSpec:        
          params:
            - name: directo
          steps:
            - name: test

              image: busybox
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh"]
              args: ["-c", "echo $(params.directo)"]
  taskRunTemplate:
    serviceAccountName: gcp-gke
    podTemplate:
      automountServiceAccountToken: true
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"31aa3e89a926f81aa0af30320ffcb71acadf3015", GitTreeState:"clean", BuildDate:"2023-04-07T11:17:33Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5-gke.1200", GitCommit:"4eb57372b0f0ac0023caca078161b75185febeef", GitTreeState:"clean", BuildDate:"2023-06-01T19:55:11Z", GoVersion:"go1.19.9 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.49.0
```
