### ISSUE TITLE
When there is an invalid pipelinetask name in taskRunSpecs, the cause of the error does not match.

### ISSUE THREAD

**Issue by cugykw** [tektoncd/pipeline#6956]
Recently, we planned to upgrade to 0.45.x, tested some new features, etc., 
and found some problems.

When an invalid pipelinetaskname appears in the pipelineName in taskRunSpecs, an error is reported in the status that does not match.

# Expected Behavior

The configuration is as follows：
```
...
  taskRunSpecs:
  - metadata:
      annotations:
        env: prod
    pipelineTaskName: prod-kc
  tasks:
  - name: prod-kc-ea704bf6-54e6-40b0-a957-a73bf2b8f3e5
...
```
We want to show the appropriate error reason.

# Actual Behavior
The actual error is as follows：
```
  conditions:
  - lastTransitionTime: "2023-07-21T02:06:08Z"
    message: 'PipelineRun cicd/test-kc-inject-annotation doesn''t define taskRunSpecs
      correctly: PipelineRun''s taskrunSpecs defined wrong taskName: "prod-kc", does
      not exist in Pipeline'
    reason: InvalidServiceAccountMappings
    status: "False"
    type: Succeeded
```

/kind bug
