### ISSUE TITLE
Can we allow pipelineRef.resolver and pipelineRef.name to exist at the same time

### ISSUE THREAD

**Issue by cugykw** [tektoncd/pipeline#6961]
### Feature request

Currently, our number of pipelines is getting bigger and bigger, however, we also observe 
that there are many pipelines that are not active and will not even be used in the future. 
We want to archive this part of the pipeline. When we try to archive part of the pipeline, 
some users use it again, so we need to recover it again.

We noticed that there is a new feature[TEP-060](https://github.com/tektoncd/community/blob/main/teps/0060-remote-resource-resolution.md) that seems to be sufficient, but it does not fully 
meet the needs.

Can we allow pipelineRef.resolver and pipelineRef.name to exist at the same time, and pipelineRef.name 
has a higher priority, when pipelineRef.name cannot be obtained, then pipelineRef.resolver is used 
to resolve the pipeline. We can even use a parameter to control whether when pipelineRef.resolver 
and pipelineRef.name exist at the same time, if pipelineRef.name cannot be obtained, it can be resolved 
through pipelineRef.resolver and the pipeline is created in the cluster.

### Use case

The detailed description is as above.

The specific configuration example is as follows:

```
...
  taskRef:
    resolver: git-example 
    params:
    - name: url
      value: https://git.example.com/cicd/remote-pipeline.git
    - name: revision
      value: production
    - name: pathInRepo
      value: pipeline.yml    
    name: cicd
...
```
