### ISSUE TITLE
Can't echo array params in a task

### ISSUE THREAD

**Issue by EmmaMunley** [tektoncd/pipeline#6972]
# Expected Behavior

I expect to be able to run this yaml file and have it echo the array values.
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mytask
spec:
  params:
    - name: TEST
      type: array
  steps:
    - name: echo
      image: alpine
      script: |
        echo "$(params.TEST[*])"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: platforms-with-results
spec:
  serviceAccountName: "default"
  pipelineSpec:
    tasks:
      - name: task
        taskRef:
          name: mytask
          kind: Task
        params:
          - name: TEST
            value:
              - a
              - b
              - c

```

# Actual Behavior

Instead I get this error message: `Error from server (BadRequest): error when creating "test.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: variable type invalid in "echo \"$(params.TEST[*])\"\n": spec.steps[0].script`

As a workaround, you can use environment variables like so, but this doesn't always work because I sometimes get this error: ` env: can't execute 'bash': No such file or directory`
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mytask
spec:
  params:
    - name: TEST
      type: array
  steps:
    - name: use-environments
      image: bash:latest
      args: ["$(params.TEST[*])"]
      script: |
        for arg in "$@"; do
          echo "Arg: $arg"
        done
````

# Steps to Reproduce the Problem

1.  Run the examples provided

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/arm64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.31.1
Pipeline version: devel
```
