### ISSUE TITLE
After upgarding to v0.50.0, get PipelineValidationFailed when using cluster resolver in a PipelineRun

### ISSUE THREAD

**Issue by adelmoradian** [tektoncd/pipeline#7015]
# Expected Behavior

After upgrading to `v0.50.0`, when using a pipelineRef such as 
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: foo-
spec:
  pipelineRef: 
    resolver: cluster
    params:
      - name: kind
        value: pipeline
      - name: name
        value: pipeline-name
      - name: namespace
        value: some-namespace
```
I get a `PipelineValidationFailed` error on pipelineRun:
```
validation failed for referenced Pipeline pipeline-name: the namespace of the provided object does not match the namespace sent on the request
```

# Actual Behavior

When using `v0.48.0` the pipeline is resolved correctly.

# Steps to Reproduce the Problem

1. Upgrade from `v0.48.0` to `v0.50.0`
2. Create a `PipelineRun` with cluster resolver `pipelineRef`. In my case `PipelineRun` and referenced `Pipeline` are in different namespaces
3. Apply the `PipelineRun`

# Additional Info

Still was using the `v1beta1` api after the upgrade. 

- Kubernetes version:

```
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"890a139214b4de1f01543d15003b5bda71aae9c7", GitTreeState:"clean", BuildDate:"2023-05-17T14:08:49Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```

- cluster-resolver-config

```
{"allowed-namespaces":"some-namespace","blocked-namespaces":"","default-kind":"task","default-namespace":"some-namespace"}
```

- resolvers-feature-flags

```
{"enable-bundles-resolver":"false","enable-cluster-resolver":"true","enable-git-resolver":"false","enable-hub-resolver":"false"}
```

- feature-flags

```
{"await-sidecar-readiness":"true","disable-affinity-assistant":"true","disable-creds-init":"false","enable-api-fields":"alpha","enable-custom-tasks":"false","enable-provenance-in-status":"false","enable-tekton-oci-bundles":"false","require-git-ssh-secret-known-hosts":"false","resource-verification-mode":"skip","running-in-environment-with-injected-sidecars":"true","send-cloudevents-for-runs":"false"}
```
