### ISSUE TITLE
runtime context with matrix

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#7024]
Please document the standards for replacing context variables with matrix, specifically:

- What is the value of `"$(tasks.task1.status)"` when `task1` is a matrix task?
- What is `context.taskRun.name` set to when a taskRun is part of a matrix task?
 
References:

https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#using-execution-status-of-pipelinetask
https://github.com/tektoncd/pipeline/blob/main/docs/variables.md

/kind documentation

**Comment by vdemeester** [comment]
Marking as `good first issue` — this is a docs-only change.

## What to do

Document how context variables behave when used with matrix tasks. Specifically:

1. What does `$(tasks.task1.status)` resolve to when `task1` is a matrixed task? (Does it reflect the aggregate status of all matrix instances?)
2. What is `$(context.taskRun.name)` set to inside a matrixed TaskRun?

## Files to edit

- [`docs/pipelines.md`](https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md) — the "Using execution status of pipelinetask" section
- [`docs/variables.md`](https://github.com/tektoncd/pipeline/blob/main/docs/variables.md) — add notes in the context variables table for matrix behavior

## How to investigate the behavior

You can create a simple PipelineRun with a matrix task that echoes context variables to understand the current behavior:

```yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-matrix-context
spec:
  pipelineSpec:
    tasks:
      - name: matrix-task
        matrix:
          params:
            - name: val
              value: ["a", "b"]
        taskSpec:
          params:
            - name: val
          steps:
            - name: show-context
              image: mirror.gcr.io/alpine
              script: |
                echo "taskRun.name = $(context.taskRun.name)"
                echo "task.retry-count = $(context.task.retry-count)"
```

/good-first-issue
