### ISSUE TITLE
When Expressions not scoped to the task when results is missing too

### ISSUE THREAD

**Issue by RafaeLeal** [tektoncd/pipeline#7029]
# Expected Behavior
Not sure if this is the expected behavior, I just thought that this was pretty confusing for my scenario, let me know what you think.
I have PipelineRun that runs something like this:
```

  ┌──────────┐  ┌─────────┐
  │build-app1├─►│push-app1├──┐
  └──────────┘  └─────────┘  │ ┌──────┐
                             │►│deploy│
  ┌──────────┐  ┌─────────┐  │ └──────┘
  │build-app2├─►│push-app2├──┘
  └──────────┘  └─────────┘

```

This PipelineRun is generated and quite big/complex, so I tried to simplify as much as possible, to something like this:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: testing-when-expressions
  namespace: pipelines
spec:
  pipelineSpec:
    tasks:
      - name: build-app1
        taskSpec:
          results:
            - name: app1-image-tarball
              type: string
          steps: [...]
        when:
          - input: "app1"
            operator: in
            values: [app1, both]

      - name: push-app1
        params:
          - name: app1-image-tarball
            value: $(tasks.build-app1.results.app1-image-tarball)
        taskSpec:
          params:
            - name: app1-image-tarball
              type: string
          steps: [...]
        when:
          - input: "app1"
            operator: in
            values: [app1, both]

      - name: build-app2
        taskSpec:
          results:
            - name: app2-image-tarball
              type: string
          steps: [...]
        when:
          - input: "app1"
            operator: in
            values: [app2, both]

      - name: push-app2
        params:
          - name: app2-image-tarball
            value: $(tasks.build-app2.results.app2-image-tarball)
        taskSpec:
          params:
            - name: app2-image-tarball
              type: string
          steps: [...]
        when:
          - input: "app1"
            operator: in
            values: [app2, both]
      - name: deploy
        runAfter:
          - push-app1
          - push-app2
        taskSpec:
          steps: [ ... ]
```

What do I expected:
1. build-app1 runs
2. build-app2 is skipped
3. push-app1 runs
4. push-app2 is skipped
5. deploy runs

# Actual Behavior

What actually happened:

1. ✅  build-app1 runs
2. ✅  build-app2 is skipped
3. ✅  push-app1 runs
4. 🟡  push-app2 is skipped
5. ❌  deploy runs

Debugging what happened, I first noticed in the `status`:
```yaml
  provenance:
    featureFlags:
      ...
      ScopeWhenExpressionsToTask: false
 ```
 
 This is confusing since this feature-flag used to have default "true" value and I didn't change it. But AFAIK this is just a visibility problem since this feature flag doesn't actually exist anymore.
 
 Looking at the skipped tasks:
 ```yaml
 skippedTasks:
    - name: build-app2
      reason: When Expressions evaluated to false
      whenExpressions: [...]
    - name: deploy
      reason: Parent Tasks were skipped
    - name: push-app2
      reason: Results were missing
      whenExpressions: [...]
```

So here it lies the problem: `push-app2` was skipped due to results being missing, instead of when expressions.. So the deploy was skipped too, since the parent was skipped not due to when expressions.

From what I could gather, this happens because we evaluate first the results references then the when expressions [here](https://github.com/tektoncd/pipeline/blob/19af21c1fbb113b561cfeb188a0711a2cc3170cc/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L313-L316)

So what happened was that `push-app2` was skipped for the "wrong" reason so `deploy` was unexpectedly skipped.

# Steps to Reproduce the Problem

1. Create a PipelineRun as described above

# Additional Info

- Kubernetes version:

  **Output of `kubectl version -o yaml | yq .serverVersion`:**

```yaml
buildDate: "2023-06-16T17:32:40Z"
compiler: gc
gitCommit: 78c8293d1c65e8a153bf3c03802ab9358c0e1a14
gitTreeState: clean
gitVersion: v1.27.3-eks-a5565ad
goVersion: go1.20.5
major: "1"
minor: 27+
platform: linux/amd64
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.48.0
```
