### ISSUE TITLE
Allow users to specify step image's reference (Image and Tag/SHA ) via explicit fields

### ISSUE THREAD

**Issue by QuanZhang-William** [tektoncd/pipeline#7035]
### Background

Currently, Tekton does not have an elegant way to allow users to specify step image's reference (images and/or the identifier) at runtime. 

The workaround today is to let users to pass in the reference via `Params` , i.e.

``` yaml
...
params:
    - name: gitInitImage
      type: string
...
steps:
    - name: clone
      image: "$(params.gitInitImage)"
...
```

or 

``` yaml
...
params:
    - name: version
      type: string
...
steps:
  - name: build
    image: docker.io/library/golang:$(params.version)
...
```

This is a working solution but has the following pain points:
- It is not possible to differentiate the identifier between a *digest* and a *tag*.  It introduces difficulty when concatnating the container image with the identifier as a `Param` (*tag* is followed by a `colone :` while *digest* is followed by `at @`)
  - `docker.io/golang:latest`
  - `docker.io/golang@sha:abc`
 - It is not possible for `Task` authors or cluster operators to set container image specific usage policies in the future.
 
### Feature request
Tekton provides explicit API fields to allow users to specify container image, tag or digest to be used in `Task.Steps`. This is the first step to support "trusted container images" in Tekton (https://github.com/tektoncd/pipeline/issues/7036).

### Use case
- Tekton [golang-build verified catalog](https://github.com/tektoncd-catalog/golang/blob/837fdb7218b90c851359a73a119ce2b678518f5b/task/golang-build/golang-build.yaml#L57C5-L57C54) only allows users to pass in *tag* as identifier by `Params` due to the lack of explicit *digest* API field
- Tekton [git-clone verified catalog](https://github.com/tektoncd-catalog/git-clone/blob/54fde69b0406742b138e644c7ecc25e04ace184d/task/git-clone/git-clone.yaml#L118C1-L118C38) takes the `Param` as the whole image reference, with no image specific validation policy check.
