### ISSUE TITLE
Change ordering of Matrixed TaskRuns Produced to Not Be Deterministic 

### ISSUE THREAD

**Issue by EmmaMunley** [tektoncd/pipeline#7056]
This issue is tracking the discussion regarding the fact that TaskRuns are currently fanned out from a Matrixed PipelineTask in a deterministic order with a suggestion of wanting to change it to be non-deterministic so that users won't rely on the ordering. This was originally brought up when discussing  TEP-140: Produce Results from Matrixed PipelineTasks: https://github.com/tektoncd/community/pull/1047#discussion_r1293685528

![Screenshot 2023-08-21 at 11 06 11 AM](https://github.com/tektoncd/pipeline/assets/46881325/cecdd464-14c8-412a-9aca-2d44bc4fb43b)

This issue should be resolved before promoting Matrix to Beta #5265

**Comment by EmmaMunley** [comment]
@lbernick @pritidesai @jerop

**Comment by lbernick** [comment]
Original discussion where this was introduced: https://github.com/tektoncd/pipeline/pull/6312#discussion_r1131175378
Note that Golang randomizes iteration order over map keys for a similar reasons: https://go.dev/doc/go1#iteration

**Comment by pritidesai** [comment]
Yes absolutely, ordering over `map` is randomized but not an `array`. Fanning out feature is equivalent to an `array` or a list. This is not a beta blocker.

@lbernick Please explain the use cases for your concerns. Thanks!

**Comment by pritidesai** [comment]
> The use case is for Tekton developers wanting to change implementation of fanned out tasks.

What could be the motivation for pipeline developers wanting to change implementation of fanned out tasks?

> Consider a matrixed taskrun that produces an array result, which is then fanned out into another matrixed taskrun. We will probably initially implement this to wait until all matrixed taskruns are complete, and then fan out the second task in the same order as the first task. But what if we want to improve performance, and start creating matrixed taskruns for the second task as soon as the string results from some of the previous matrixed taskruns are ready? If we guarantee deterministic ordering, we might not be able to make this change.

The use case you have included is not clear to me. Let's say we have two tasks in a pipeline.

```
    - name: kaniko-build
      taskRef:
        name: kaniko
      matrix:
        params:
          - name: IMAGE
            value: [ "image-1", "image-2", "image-3" ]
    - name: task-deploy-images
      taskRef:
        name: deploy
        matrix:
          params:
            - name: DIGEST
              value: $(tasks.kaniko-build.results.IMAGE-DIGEST[*]) 
```

Now, the use case you are describing includes scheduling an instance of `task-deploy-images` as soon as an instance with running an `image-1` is done. Is that correct? 

> While deterministic ordering makes testing easier, I'm not aware of any use cases for it.

what kind testing are you referring to?

Let me take some time to understand your concerns with `matrix`.

Let's continue with the same example. 

```yaml
    - name: kaniko-build
      taskRef:
        name: kaniko
      matrix:
        params:
          - name: IMAGE
            value: [ "image-1", "image-2", "image-3" ]
```

Now, the `param` `IMAGE` is an `array`. When you index into `IMAGE`, would the first element be always `image-1` or it changes everytime you access `IMAGE[0]`?

By following the standard programming language constructs, `IMAGE[0]` will always return `image-1`. So the first instance of the taskRun will return the `DIGEST` for the first element in an `array`.

Now, making it a little bit more complex, let's say:

```yaml
    - name: kaniko-build
      taskRef:
        name: kaniko
      matrix:
        params:
          - name: IMAGE
            value: [ "image-1", "image-2", "image-3" ]
          - name: OS
            value: ["linux", "windows"]
```

`matrix` is a list of `params` i.e it is an `array` of `objects`. Is the map of `IMAGE` always the first element of `matrix`?

Ranging over an array `matrix` returns `IMAGE` as the first element of `matrix` in [FanOut](https://github.com/tektoncd/pipeline/blob/main/pkg/apis/pipeline/v1/matrix_types.go#L72) and `OS` as the second element of an array.

Now, the first instance of this `matrix` is executed with `image-1` and `linux`. 

> Change ordering of Matrixed TaskRuns Produced to Not Be Deterministic

Are you suggesting to randomize ranging over an array using `rand`?

**Comment by lbernick** [comment]
> What could be the motivation for pipeline developers wanting to change implementation of fanned out tasks?

It's hard for me to predict what changes we want to make in the future, but I think it's important to leave ourselves the option of doing so. We can always re-introduce sorting later, but it's hard to take away. The example I gave was just an attempt to brainstorm a reason we might want to change the implementation. I don't think we need to know that we will change the implementation; I think we just shouldn't lock ourselves into this implementation without a good reason.

> > While deterministic ordering makes testing easier, I'm not aware of any use cases for it.
> 
> what kind testing are you referring to?

Just tekton pipelines unit tests. However, I don't think easier testing (by itself) is a good reason to have deterministic ordering.

> Let me take some time to understand your concerns with `matrix`.
> 
> Let's continue with the same example.
> 
> ```yaml
>     - name: kaniko-build
>       taskRef:
>         name: kaniko
>       matrix:
>         params:
>           - name: IMAGE
>             value: [ "image-1", "image-2", "image-3" ]
> ```
> 
> Now, the `param` `IMAGE` is an `array`. When you index into `IMAGE`, would the first element be always `image-1` or it changes everytime you access `IMAGE[0]`?
> 
> By following the standard programming language constructs, `IMAGE[0]` will always return `image-1`. So the first instance of the taskRun will return the `DIGEST` for the first element in an `array`.
> 
> Now, making it a little bit more complex, let's say:
> 
> ```yaml
>     - name: kaniko-build
>       taskRef:
>         name: kaniko
>       matrix:
>         params:
>           - name: IMAGE
>             value: [ "image-1", "image-2", "image-3" ]
>           - name: OS
>             value: ["linux", "windows"]
> ```
> 
> `matrix` is a list of `params` i.e it is an `array` of `objects`. Is the map of `IMAGE` always the first element of `matrix`?
> 
> Ranging over an array `matrix` returns `IMAGE` as the first element of `matrix` in [FanOut](https://github.com/tektoncd/pipeline/blob/main/pkg/apis/pipeline/v1/matrix_types.go#L72) and `OS` as the second element of an array.
> 
> Now, the first instance of this `matrix` is executed with `image-1` and `linux`.

I agree that typical expectations are that array ordering is preserved. However, I don't think there are typical expectations when it comes to iteration over 2D (or 3D etc) arrays (e.g. should the next combo be "image-2" and "linux" or "image-1" and "windows"?), and it's not clear what the ordering should be if there's an `include` statement as well.

> Are you suggesting to randomize ranging over an array using `rand`?

No, I'm just suggesting we remove our [sorting logic](https://github.com/tektoncd/pipeline/blob/445734d92807a80158b4b7af605d768c647fdb3d/pkg/apis/pipeline/v1/matrix_types.go#L204-L218) and document that matrix ordering is not guaranteed.

**Comment by pritidesai** [comment]
> I agree that typical expectations are that array ordering is preserved. However, I don't think there are typical expectations when it comes to iteration over 2D (or 3D etc) arrays (e.g. should the next combo be "image-2" and "linux" or "image-1" and "windows"?), and it's not clear what the ordering should be if there's an include statement as well.
 
We are not reinventing here, this is a standard programming paradigm. The entire language specifications for `include` is described in the proposal. Please refer to the [TEP](https://github.com/tektoncd/community/blob/main/teps/0118-matrix-with-explicit-combinations-of-parameters.md) to understand how the combinations are derived. 

> Just tekton pipelines unit tests. However, I don't think easier testing (by itself) is a good reason to have deterministic ordering.

> No, I'm just suggesting we remove our [sorting logic](https://github.com/tektoncd/pipeline/blob/445734d92807a80158b4b7af605d768c647fdb3d/pkg/apis/pipeline/v1/matrix_types.go#L204-L218) and document that matrix ordering is not guaranteed.

This sorting logic has no impact or influence on the matrix ordering. This sorting logic was introduced to order each combination object e.g. a combination with multiple parameters returns the same order of params such that comparing combinations does not cause any failures due to mismatch order.

Let's take an existing [example](https://github.com/tektoncd/pipeline/blob/main/examples/v1/pipelineruns/alpha/pipelinerun-with-matrix.yaml) with the latest pipelines release:

Here is the list of taskRuns created:

```
🗂  Taskruns

 NAME                                           TASK NAME                STARTED          DURATION   STATUS
 ∙ matrixed-pr-scd79-matrix-and-params-2        matrix-and-params        21 seconds ago   20s        Succeeded
 ∙ matrixed-pr-scd79-matrix-and-params-1        matrix-and-params        21 seconds ago   19s        Succeeded
 ∙ matrixed-pr-scd79-platforms-and-browsers-8   platforms-and-browsers   22 seconds ago   20s        Succeeded
 ∙ matrixed-pr-scd79-matrix-and-params-0        matrix-and-params        22 seconds ago   21s        Succeeded
 ∙ matrixed-pr-scd79-platforms-and-browsers-6   platforms-and-browsers   23 seconds ago   15s        Succeeded
 ∙ matrixed-pr-scd79-platforms-and-browsers-7   platforms-and-browsers   23 seconds ago   21s        Succeeded
 ∙ matrixed-pr-scd79-platforms-and-browsers-4   platforms-and-browsers   24 seconds ago   12s        Succeeded
 ∙ matrixed-pr-scd79-platforms-and-browsers-5   platforms-and-browsers   24 seconds ago   15s        Succeeded
 ∙ matrixed-pr-scd79-platforms-and-browsers-3   platforms-and-browsers   24 seconds ago   13s        Succeeded
 ∙ matrixed-pr-scd79-platforms-and-browsers-1   platforms-and-browsers   25 seconds ago   17s        Succeeded
 ∙ matrixed-pr-scd79-platforms-and-browsers-0   platforms-and-browsers   25 seconds ago   16s        Succeeded
 ∙ matrixed-pr-scd79-platforms-and-browsers-2   platforms-and-browsers   25 seconds ago   19s        Succeeded
```

Now, let's see what were the combination used for each instance:

```
k get tr matrixed-pr-scd79-platforms-and-browsers-0 -o json | jq .spec.params 
[
  {
    "name": "browser",
    "value": "chrome"
  },
  {
    "name": "platform",
    "value": "linux"
  }
]

k get tr matrixed-pr-scd79-platforms-and-browsers-1 -o json | jq .spec.params
[
  {
    "name": "browser",
    "value": "chrome"
  },
  {
    "name": "platform",
    "value": "mac"
  }
]

k get tr matrixed-pr-scd79-platforms-and-browsers-2 -o json | jq .spec.params
[
  {
    "name": "browser",
    "value": "chrome"
  },
  {
    "name": "platform",
    "value": "windows"
  }
]

k get tr matrixed-pr-scd79-platforms-and-browsers-3 -o json | jq .spec.params           
[
  {
    "name": "browser",
    "value": "safari"
  },
  {
    "name": "platform",
    "value": "linux"
  }
]

k get tr matrixed-pr-scd79-platforms-and-browsers-4 -o json | jq .spec.params
[
  {
    "name": "browser",
    "value": "safari"
  },
  {
    "name": "platform",
    "value": "mac"
  }
]

k get tr matrixed-pr-scd79-platforms-and-browsers-5 -o json | jq .spec.params
[
  {
    "name": "browser",
    "value": "safari"
  },
  {
    "name": "platform",
    "value": "windows"
  }
]
```

Note the combinations, first three taskRuns 0 through 2 has browser set to `chrome` with all three platforms [ `linux`, `mac`, and `windows` ] just like when you iterate over an array.

The next three taskRuns 3 through 5 has browser set to `safari` with all three platforms in order [ `linux`, `mac`, and `windows` ].

Now, I deleted the [sorting logic](https://github.com/tektoncd/pipeline/blob/445734d92807a80158b4b7af605d768c647fdb3d/pkg/apis/pipeline/v1/matrix_types.go#L204-L218) and ran the same example:

```
k get tr matrixed-pr-mnjbl-platforms-and-browsers-0 -o json | jq .spec.params
[
  {
    "name": "browser",
    "value": "chrome"
  },
  {
    "name": "platform",
    "value": "linux"
  }
]

k get tr matrixed-pr-mnjbl-platforms-and-browsers-1 -o json | jq .spec.params
[
  {
    "name": "browser",
    "value": "chrome"
  },
  {
    "name": "platform",
    "value": "mac"
  }
]

k get tr matrixed-pr-mnjbl-platforms-and-browsers-2 -o json | jq .spec.params
[
  {
    "name": "browser",
    "value": "chrome"
  },
  {
    "name": "platform",
    "value": "windows"
  }
]

k get tr matrixed-pr-mnjbl-platforms-and-browsers-3 -o json | jq .spec.params
[
  {
    "name": "browser",
    "value": "safari"
  },
  {
    "name": "platform",
    "value": "linux"
  }
]

k get tr matrixed-pr-mnjbl-platforms-and-browsers-4 -o json | jq .spec.params
[
  {
    "name": "browser",
    "value": "safari"
  },
  {
    "name": "platform",
    "value": "mac"
  }
]

k get tr matrixed-pr-mnjbl-platforms-and-browsers-5 -o json | jq .spec.params
[
  {
    "name": "browser",
    "value": "safari"
  },
  {
    "name": "platform",
    "value": "windows"
  }
]
```

The order is still the same.

**Comment by jerop** [comment]
If it helps, Matrix in GitHub Actions inspired Matrix in Tekton, and you'll observe that the ordering is also deterministic there

The blurb below the line below is lifted from this documentation: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#using-a-matrix-strategy

---

```yaml
jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
```

The order of the variables in the matrix determines the order in which the jobs are created. The first variable you define will be the first job that is created in your workflow run. For example, the above matrix will create the jobs in the following order:

```
{version: 10, os: ubuntu-latest}
{version: 10, os: windows-latest}
{version: 12, os: ubuntu-latest}
{version: 12, os: windows-latest}
{version: 14, os: ubuntu-latest}
{version: 14, os: windows-latest}
```

**Comment by pritidesai** [comment]
thanks @jerop yes it is an industry standard and common across many CI/CD platforms.

**Comment by lbernick** [comment]
> Now, I deleted the [sorting logic](https://github.com/tektoncd/pipeline/blob/445734d92807a80158b4b7af605d768c647fdb3d/pkg/apis/pipeline/v1/matrix_types.go#L204-L218) and ran the same example:
> 
> The order is still the same.

Thank you for testing this out; I didn't realize this sorting logic was not what was causing the deterministic ordering.

@jerop thanks for the info about GHA; do you happen to have any insight on why they chose to support this? (I understand this might not be publicly available info.)

I am not opposed to deterministic ordering, but I want to understand the use cases that exist for it before users come to rely on it.

**Comment by pritidesai** [comment]
> I am not opposed to deterministic ordering

Thanks a bunch for clarifying this. May be I misread this issue suggesting to change the deterministic order. Now that since you not opposed to it, can we please move this out as a blocker from https://github.com/tektoncd/pipeline/issues/5265#issue-1327646147. Thanks! 

> but I want to understand the use cases that exist for it before users come to rely on it.

Please clarify what exactly you would like to understand, I am happy to help!

**Comment by lbernick** [comment]
I still believe this is important to decide before beta, for the reasons I listed in [this comment](https://github.com/tektoncd/pipeline/issues/7056#issuecomment-1686666041). Would a clearer title for this issue be "decide whether to preserve deterministic ordering of matrixed taskruns"?

I see a few options:
- If there's a clear use case for deterministic ordering, move forward with that
- If we don't think there's a clear use case, make ordering randomized, since we can always revert to deterministic later on
- Agree to disagree, and make a decision on the way forward via a method other than consensus

I'd like to understand an example of a CI/CD workflow that would be much more difficult to implement if matrixed ordering was not deterministic.

**Comment by jerop** [comment]
> @jerop thanks for the info about GHA; do you happen to have any insight on why they chose to support this? (I understand this might not be publicly available info.)

I cannot speak to why GitHub Actions chose to support it, but I can see the predictability of the matrix being useful for users

Users can rely on the deterministic ordering to automate progressive deployments to different environments by using a matrix and limiting concurrency to one: https://cbrgm.net/post/2022-01-12-github-actions-environments/ 

```yaml
...
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: ['development', 'integration', 'production']
      fail-fast: true
      max-parallel: 1
    steps:
      - name: do some stuff
        uses: ...
        with: ...
```

In [TEP-0090](https://github.com/tektoncd/community/blob/main/teps/0090-matrix.md#concurrency-control), we indicated interest in adding similar concurrency controls in Matrix in Tekton
> "When a Matrix in PipelineTask would generate more than the maximum TaskRuns or Runs, this would fail the Pipeline in the first iteration. After initial usage of Matrix, we can explore other ways of supporting usage beyond that limit, such as allowing TaskRuns or Runs only up to the limit to run at a time, in a follow-up TEP."

While looking into the deterministic ordering in GHA matrix, I ran into reported issues with comments from frustrated users when the ordering was broken: https://github.com/actions/runner/issues/703, https://github.com/actions/runner/issues/483. The examples mentioned in the issues are depending on matrix and concurrency to automate progressive processes.

```yaml
# running two tests at a time, then progress to more expensive tests only when the previous were successful
...
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ['simple', 'groovy', 'filesystem', 'webflow', 'webflowconfig', 'attributes']
      fail-fast: true
      max-parallel: 2
    steps:
      - name: run the tests
        uses: ...
        with: ...
```

```yaml
# changing terraform workspace one at a time, starting with dev then staging
...
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ['dev-us-east-1', 'stg-us-west-2']
      fail-fast: true
      max-parallel: 1
    steps:
      - name: change terraform workspace
        uses: ...
        with: ...
```
