### ISSUE TITLE
`retry-count` variable substitution not supported with `taskRef`

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#7063]
We have an [example](https://github.com/tektoncd/pipeline/blob/main/examples/v1/pipelineruns/using-retries-and-retry-count-variables.yaml) demonstrating the context variables which works great. This example works as expected with `taskSpec` but not `taskRef`. We must clarify it in the [docs](https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#using-the-retries-and-retry-count-variable-substitutions).

The following example `pipelineRun` results in a failure:
 
```
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: retry-task
spec:
  params:
    - name: pipelineTask-retries
    - name: pipelineTask-retry-count
  steps:
    - image: alpine:3.12.0
      script: |
        #!/usr/bin/env sh
        if [ "$(params.pipelineTask-retry-count)" == "$(params.pipelineTask-retries)" ]; then
          echo "This is the last retry."
          exit 0;
        fi
        echo "The PipelineTask has retried $(context.task.retry-count) times."
        exit 1
---

apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: retry-example-
spec:
  taskRunTemplate:
    serviceAccountName: 'default'
  pipelineSpec:
    tasks:
      - name: retry-me
        retries: 5
        params:
          - name: pipelineTask-retries
            value: "$(context.pipelineTask.retries)"
          - name: pipelineTask-retry-count
            value: "$(context.task.retry-count)"
        taskRef:
          name: retry-task
      - name: hello-world
        runAfter:
          - retry-me
        taskSpec:
          steps:
            - image: busybox
              script: |
                echo "hello world"
```

```
   "spec": {
        "params": [
            {
                "name": "pipelineTask-retries",
                "value": "5"
            },
            {
                "name": "pipelineTask-retry-count",
                "value": "$(context.task.retry-count)"
            }
        ],
```

/kind documentation

Also question to anyone using this context variable, do you expect this variable to be supported in a `pipelineTask` with `taskRef`?
