### ISSUE TITLE
`InvalidMatrixParameterTypes` for param which is not part of `matrix`

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#7070]
https://github.com/tektoncd/pipeline/pull/7064#issuecomment-1692065569

The example [pipelineRun](https://github.com/tektoncd/pipeline/blob/ed441e7e091e7d9121b03e4839f469e48cfe2335/examples/v1/pipelineruns/alpha/pipelinerun-with-matrix.yaml) fails with:

```
     status:
          completionTime: "2023-08-24T05:03:18Z"
          conditions:
          - lastTransitionTime: "2023-08-24T05:03:18Z"
            message: parameters of type array only are allowed, but param "browser" has type
              "string" in pipelineTask "matrix-and-params"
            reason: InvalidMatrixParameterTypes
            status: "False"
            type: Succeeded
```

The `pipelineTask` `matrix-and-params` does not have a param named `browser` as part of the `matrix`. Why is `browser` listed as a `matrix` param 🤔

https://github.com/tektoncd/pipeline/blob/ed441e7e091e7d9121b03e4839f469e48cfe2335/examples/v1/pipelineruns/alpha/pipelinerun-with-matrix.yaml#L42-L54

Running it locally, results in the same corrupted data:

```
(v1.Params) (len=1 cap=1) {
 (v1.Param) {
  Name: (string) (len=7) "browser",
  Value: (v1.ParamValue) {
   Type: (v1.ParamType) (len=6) "string",
   StringVal: (string) (len=6) "chrome",
   ArrayVal: ([]string) <nil>,
   ObjectVal: (map[string]string) <nil>
  }
 }
}
```

/kind bug
