### ISSUE TITLE
Configurable `displayName` for a Matrix TaskRun

### ISSUE THREAD

**Issue by AverageMarcus** [tektoncd/pipeline#7082]
### Feature request

A new field, that supports variable substitution, that allows specifying a display name to use for the Task in TaskRuns created from a Matrix.

### Use case

TaskRuns created from a Pipeline Matrix all have the same Task name which requires checking each manually to find a specific combination.
![Screenshot 2023-08-31 at 9 26 51 am](https://github.com/tektoncd/pipeline/assets/3384072/04c8738a-bb00-4f31-8e52-c62ba37a9c76)

I'd like to be able to configure the `displayName` property dynamically for each of the variations to make it easier to see which variation has passed and failed without needing to check all.
E.g.
![Screenshot 2023-08-31 at 9 29 11 am](https://github.com/tektoncd/pipeline/assets/3384072/0f1f4be4-9676-4692-8230-108f7f906758)

The field would need to be able to reference the variant parameters to be able to handle this, and optionally all the tasks params.

Possible approach:

```yaml
- name: run-tests
  matrix:
    displayName: "Run Tests - $(params.VARIANT)"
    params:
      - name: VARIANT
        value: $(tasks.calculate-vars.results.variations)
  taskRef:
    name: run-tests-task
```

I would expect a matrix `displayName` to override any other `displayName` if one is provided.
