### ISSUE TITLE
Results "interpolation" in embedded spec (or "results" propagation)

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#7086]
# Expected Behavior

A "somewhat" consistent behavior when using results and embedded spec. Naively, I would assume the following would work (but it does not).

```
cat <<'EOF' | kubectl create -f -
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: uid-task
spec:
  results:
    - name: uid
  steps:
    - name: uid
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
        - echo "1001" | tee $(results.uid.path)
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: uid-pipeline-run
spec:
  pipelineSpec:
    tasks:
    - name: add-uid
      taskRef:
        name: uid-task
    - name: show-uid
      taskSpec:
        steps:
          - name: show-uid
            image: alpine
            command: ["/bin/sh", "-c"]
            args:
              - echo $(tasks.add-uid.results.uid)
EOF
```

# Actual Behavior

The above example fails with `/bin/sh: tasks.add-uid.results.uid: not found`. My guess is that, we do have params and workspace propagation on embedded spec, but we do not have them for results.

# Steps to Reproduce the Problem

1. Run the command above
2. See it fail
3. …

# Additional Info

- Kubernetes version: 1.25.0
- Tekton Pipeline version: v0.50.x

As said above, this might be more a feature request than a bug as, I feel this is mainly because we do not "propagate" `results` to embedded spec. This does feel inconsistent as we do it for other fields (like `params` and `workspaces`).

cc @jerop @lbernick
