### ISSUE TITLE
task results not templated if task order is reversed

### ISSUE THREAD

**Issue by gerrnot** [tektoncd/pipeline#7103]
# Expected Behavior
In a `kind: "Pipeline"`, where you define the `tasks` (list), the order should not matter because the order in tekton is normally defined via the `runAfter` attribute or in case of a resource dependencies via a syntax like `$(tasks.<task-name>.results.<result-name>)`.

# Actual Behavior
However, it can be demonstrated, in the latest release of tekton pipelines (`v0.51.0`) that the ordering in the task list matters.
That is, tasks might behave in very awkward ways, depending on how they treat receiving an actual result string vs an untemplated string like `$(tasks.<task-name>.results.<result-name>)`.

# Steps to Reproduce the Problem

Unpack the attached tar.gz (contains only yaml files)
1. `k apply -f task-exe.yaml`
2. `k apply -f pipeline-order-wrong.yaml`
3. `k create -f pipelinerun.yaml`
4. The resulting pipelinerun will fail, reproducing the error.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.8", GitCommit:"395f0a2fdc940aeb9ab88849e8fa4321decbf6e1", GitTreeState:"clean", BuildDate:"2023-08-24T00:43:07Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.51.0
```

[cd-pipeline-dev-reduced.tar.gz](https://github.com/tektoncd/pipeline/files/12588068/cd-pipeline-dev-reduced.tar.gz)

**Comment by adelmoradian** [comment]
I also bumped into this issue after upgrading to `v0.51.0`

Here is an example that showcases this issue:

This following example runs `task3` after `task1` and `task2` however the output is 

```
$(tasks.task1.results.foo)
$(tasks.task2.results.bar)
```

```
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pr-echo-
spec:
  pipelineSpec:
    tasks:
      - name: task1
        taskSpec:
          results:
            - name: foo
          steps:
            - name: step1
              env:
                - name: RESULT_PATH
                  value: $(results.foo.path)
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "foo-value" > "$RESULT_PATH"

      - name: task3
        runAfter:
          - task1
          - task2
        params:
          - name: foo-value
            value: $(tasks.task1.results.foo)
          - name: bar-value
            value: $(tasks.task2.results.bar)
        taskSpec:
          steps:
            - name: step1
              env:
                - name: FOO_VALUE
                  value: $(params.foo-value)
                - name: BAR_VALUE
                  value: $(params.bar-value)
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "$FOO_VALUE"
                echo "$BAR_VALUE"

      - name: task2
        taskSpec:
          results:
            - name: bar
          steps:
            - name: step1
              env:
                - name: RESULT_PATH
                  value: $(results.bar.path)
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "bar-value" > "$RESULT_PATH"

```

If i put `task3` after `task2` however, the output is correct 

```
foo-value

bar-value
```
