### ISSUE TITLE
The task result before retry is retained in the current taskrun status.

### ISSUE THREAD

**Issue by cugykw** [tektoncd/pipeline#7125]
The task result before retry is retained in the current taskrun status.

There is a code scanning task in my pipeline, which returns failure or success based on the result. When it fails, a link will be generated and written to the task result. The final task will send me a message based on this result. I set a retry count for this task.

The first execution failed (because the external scanning service queue was full), and the task succeeded when it was retried and executed again, but the message was still sent to me.

# Expected Behavior
This taskrun should clean up the last results when retrying, and the final task does not need to send me a message in the end.

# Actual Behavior
The final task send me a message in the end.

# Steps to Reproduce the Problem

```
kind: PipelineRun
metadata:
  name: demo
spec:
  pipelineSpec:
    finally:
     - name: send-all-report
       params:
       - name: scan-result
         value: $(tasks.scan.results.scan-failed-report)
       taskSpec:
         steps:
         - image: example.com/notify/demo:latest
           name: send-scan-report
           script: |
             # some commands
    tasks:
     - name: scan
       retries: 2
       taskSpec:
         results:
         - name: scan-failed-report
           type: string
         steps:
         - image: example.com/scan/demo:latest
           name: demo
           script: |
             # For example：
             # The first execution fails and then the successful execution of the command
...
```

/kind bug
