### ISSUE TITLE
Want to know the policy that Tekton  request resource for  the Task with multi containers

### ISSUE THREAD

**Issue by NEUerYZY** [tektoncd/pipeline#7148]
I have done an experiment with the Tekton version v0.25.0  but meet a problem .

I try to make a TaskRun with the following description  in a  namespace with limit range  20C 20Gi.

```
spec:
  steps:
    - name: step1
      resources:
        requests:
          memory: 4Gi
          cpu: 2C
        limits:
          memory: 4Gi
          cpu: 2C
    - name: step2
      resources:
        requests:
          memory: 8Gi
          cpu: 4C
        limits:
          memory: 8Gi
          cpu: 4C
    - name: step3
      resources:
        requests:
          memory: 16Gi
          cpu: 8C
        limits:
          memory: 16Gi
          cpu: 8C
```
Then I found Tekton request the POD from K8S cluster  with **request resource 8C 16GI  and limit  resource  2+4+8 = 14C  , 4+8+16=28Gi** .  The POD doesn't execute  because of  the namespace level limitation  20GI < limit resource 28Gi.

From the description of Pull request #723  and  the document  [https://github.com/tektoncd/pipeline/blob/v0.25.0/docs/tasks.md#defining-steps] . I can know that Tetkon reserve the max **Request** resource for multi containers rather than the **sum** of request . But there is no related description with  **Limit**  resource  

So , all of above  I want to know 
1. The principle that Tekton request  **limit  resource** from K8S cluster  when a Task has multi containers .  
2. Is there any solution for this scene that can request the limit resource using the max limit resource  among containers ?
