### ISSUE TITLE
Docker entrypoint is ignored when a command is specified for a step

### ISSUE THREAD

**Issue by Shankar1598** [tektoncd/pipeline#7182]
# Expected Behavior
Task run to print the same outout as the following docker run

Docker run
```
docker run docker.io/shankar1598/echoer Hi "there"
```
Please note that `Hi` is a command here and `there` is the first argument as per docker run command reference: `docker run [OPTIONS] IMAGE [COMMAND] [ARG...]`

Output
```
Hi there
```

Dockerfile (for reference)
```
FROM alpine:latest
WORKDIR /
ENTRYPOINT [ "echo" ]
CMD [ "Hi" ]
```

# Actual Behavior
Task run failing with error
```
Error executing command: exec: "Hi": executable file not found in $PATH
```
The ENTRYPOINT specified in the dockerfile is not being executed if we give a `command` for the step in task run.

# Steps to Reproduce the Problem

1.Write Task run YML
```
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: echo-
spec:
  taskSpec:
    steps:
      - name: echo
        image: docker.io/shankar1598/echoer
        command:
          - Hi
        args:
          - " there"
        securityContext:
          runAsUser: 0
```
2. Run using: kubectl create -f task_run.yml

# Workaround

We are able to work around this issue in the following ways
1. Pass the CMD (`Hi` in this case) as part of the `args` in the step definition and do not specify a `command` value.
2. Pass the ENTRYPOINT of the dockerfile (`echo` in this case) again as the `command` in the step definition and pass the other things as `args`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.27.3
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.31.0
Pipeline version: v0.52.0
Dashboard version: v0.40.1
```

Please let me know if you want me to share more info on the actual use case that caused this issue.

**Comment by chengjoey** [comment]
similar with this #4794

**Comment by vdemeester** [comment]
Yes, this is expected behaviour. In Kubernetes and Tekton `command` is *equivalent* to the "entrypoint" *field* in Docker (be it `docker run --entrypoint …` or `ENTRYPOINT` in a `Dockerfile`) and `args` is *equivalent* to the "commands" field in Docker. 

The following should work.

```
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: echo-
spec:
  taskSpec:
    steps:
      - name: echo
        image: docker.io/shankar1598/echoer
        args:
          - "Hi there"
        securityContext:
          runAsUser: 0
```

I'll close this issue as it's the expected behavior.
