### ISSUE TITLE
Multiple Service Account

### ISSUE THREAD

**Issue by parlacom** [tektoncd/pipeline#7191]
### Feature request

We need to set up `multiple ServiceAccount` for different services such as GitHub, Private Registry, etc. but we can only configure one ServiceAccount in each PipelineRun

### Use case

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: my-pipeline-
spec:
  serviceAccountNames:
    - serviceaccount-buildpacks
    - serviceaccount-github
  pipelineRef:
    name: my-pipeline
  params:
    - name: private-registry-url
      value: https://parlacom.harbor.com/parla
    - name: repo-url
      value: https://github.com/parlacom/tekton.git
    - name: revision
      value: main
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: pvc-tekton-claim
```

**Comment by vdemeester** [comment]
This is not technically possible, at least from the Kubernetes point of view. A Pod can only have one `ServiceAccount` and this, the same is true for a `TaskRun`. That said, for `PipelineRun` you can already specify multiple service account, but "attached" to a given Task, see [here](https://tekton.dev/docs/pipelines/pipelineruns/#mapping-serviceaccount-credentials-to-tasks).

**Comment by parlacom** [comment]
Thanks @vdemeester, really appreciate your comments. I followed the example and it worked fine.

**Comment by vdemeester** [comment]
@parlacom I think we can close that issue then, am I right ? 👼🏼

**Comment by tppalani** [comment]
Hi @vdemeester 

i have same requirements

1.  I have a git clone task from private repo, so i have created service account and i added service account name inside run.yaml its working file as we expected.
2. Having another task kuberentes-action which will setup kube cofig file to connect to the GKE cluster, for this i have created another service account because if not create genrally tekton pipeine line will get error message like this.

```
deployments.apps "java" is forbidden: User "system:serviceaccount:devops-caas-maven:bitbucket-sa-git-clone" 
cannot get resource "deployments" in API group "apps" in the namespace "devops-caas-maven"
```

To avoid this i have created service account and i added into run.yaml like this.


```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kube-test
  namespace: devops-caas-maven
spec:
  serviceAccountName: bitbucket-sa-git-clone
  pipelineRef:
    name: kubernetes
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: maven-source-pvc
```

But git clone will always will be success  but kubernetes-action task will getting failed with below error

```
from server for: "/workspace/shared-workspace/source/k8s/deployment.yaml": deployments.apps "java" is forbidden: User "system:serviceaccount:devops-caas-maven:bitbucket-sa-git-clone" cannot get resource "deployments" in API group "apps" in the namespace "devops-caas-maven"

```
Can you please help me, is that service can be manage with task level ? because https://tekton.dev/docs/pipelines/pipelineruns/#mapping-serviceaccount-credentials-to-tasks this page having mapping with single service account name.
