### ISSUE TITLE
tekton cluster resolver let anyone access any tasks on any namespaces

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#7236]
# Expected Behavior

Don't let someone who does not have access to the task be able to access it

# Actual Behavior

Anyone can access to any task as long as they know its name

# Steps to Reproduce the Problem

1. User-a have a git-clone task with for example a reference in a password in clear in that task
   (bad security practice but one can assume people may feel safe to do this in their own namespace)
3. User-b create a TaskRun with a reference to User-a namespace and git-clone:
 

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: remote-task-reference
spec:
  taskRef:
    resolver: cluster
    params:
    - name: kind
      value: task
    - name: name
      value: git-clone
    - name: namespace
      value: user-a
 ```

5. User-b is able to read the task from user-a and content

# Additional Info

- Kubernetes version:

v0.52.1

This assumes user-b know the task name of user-a but security which mitigate this by obscurity doesn't scale very far :)
