### ISSUE TITLE
ViaField/ ViaFieldIndex does not propagate validation errors along the specified field path access

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#7258]
# Expected Behavior
When .ViaField(https://pkg.go.dev/knative.dev/pkg/apis#FieldError.ViaField) is used, it should propagate validaiton errors along the specified field path. For example, I am expecting to see the error message containing `invalid value * params[param1].value` if validation is used ViaField/ViaFieldIndex:
```
errs = errs.Also(config.ValidateEnabledAPIFields(ctx, "object type parameter", config.BetaAPIFields).ViaFieldIndex("params", i))
```
(ViaFieldIndex has similar issue for usage since is just combining the fields with indexing)

# Actual Behavior
The validation error has not been propagated as expected by ViaField(Task)

# Steps to Reproduce the Problem
This has occurred in couple of validations in existing pipeline [v0.52.x](https://github.com/tektoncd/pipeline/releases/tag/v0.52.1) . For example at [Pipeline Validation](https://github.com/tektoncd/pipeline/blob/b44868cb2be53219c4bfc7e2e9145fe9f880e8a3/pkg/apis/pipeline/v1/pipeline_validation.go#L127). 

1. Deploy the v0.52.x pipeline
2. Run the existing Pipeline
```
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: clone-cleanup-workspace
spec:
  workspaces:
    # common workspace where git repo is cloned and needs to be cleanup after done
    - name: git-source
  tasks:
    # Clone app repo to workspace
    - name: clone-app-repo
      taskRef:
        name: git-clone-from-catalog
      params:
        - name: url
          value: https://github.com/tektoncd/community.git
        - name: subdirectory
          value: application
      workspaces:
        - name: output
          workspace: git-source
  finally:
    # Cleanup workspace
    - name: cleanup
      taskSpec:
        params:
        - name: tests
        steps:
          - name: check-commit-initialized
            image: alpine
            script: |
              if [[ ! $(params.tests[1]) ]]; then
                exit 1
              fi
      params:
      - name: tests
        value: string-value
    - name: check-git-commit
      params:
        - name: commit
          value: $(tasks.clone-app-repo.results.commit)
      taskSpec:
        params:
          - name: commit
        steps:
          - name: check-commit-initialized
            image: alpine
            script: |
              if [[ ! $(params.commit) ]]; then
                exit 1
              fi
```

You will see:
```
Error from server (BadRequest): error when creating "examples/v1/pipelineruns/pipelinerun-with-final-tasks.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: indexing into array parameters requires "enable-api-fields" feature gate to be "alpha" or "beta" but it is "stable": 
```

instead of it starting with the field path `spec.finally[0]` for Pipeline validation.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
(paste your output here)
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
(paste your output here)
```
