### ISSUE TITLE
Entrypoint cancellation is a bit "noisy" and scary

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#7268]
# Expected Behavior

When running a `PipelineRun` (such as below) or `TaskRun`, I expected to only see the output of my `Task` if everything goes well.

# Actual Behavior

The `entrypoint` cancellation feature (from https://github.com/tektoncd/pipeline/pull/6511) seems to log some error when it's a normal behavior (aka no cancel was called).

```
[add-uid : uid] {"level":"error","ts":1698142443.0641263,"caller":"entrypoint/entrypointer.go:178","msg":"Error while waiting for cancellation{error 26 0  context canceled}","stacktrace":"github.com/tektoncd/pipeline/pkg/entrypoint.Entrypointer.Go.func2\n\tgithub.com/tektoncd/pipeline/pkg/entrypoint/entrypointer.go:178"}
```

# Steps to Reproduce the Problem

```
cat <<'EOF' | kubectl create -f -
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: uid-task
spec:
  results:
    - name: uid
  steps:
    - name: uid
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
        - echo "1001" | tee $(results.uid.path)
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: uid-pipeline-run
spec:
  pipelineSpec:
    tasks:
    - name: add-uid
      taskRef:
        name: uid-task
    - name: show-uid
      taskSpec:
        steps:
          - name: show-uid
            image: alpine
            command: ["/bin/sh", "-c"]
            args:
              - echo $(tasks.add-uid.results.uid)
EOF
```

1. Run the above tekton `PipelineRun`
2. Look at the logs

# Additional Info

- Kubernetes version: 1.26

  **Output of `kubectl version`:**

```
(paste your output here)
```

- Tekton Pipeline version: `main` branch

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
(paste your output here)
```
