### ISSUE TITLE
[TEP-0144] Param Enum - Implementation

### ISSUE THREAD

**Issue by QuanZhang-William** [tektoncd/pipeline#7270]
In [TEP-0144](https://github.com/tektoncd/community/blob/main/teps/0144-param-enum.md), we introduced a new `Enum` field to enable Tekton built-in `param` input validation.

This is the umbrella issue to tracking all the implementation work.
### Implementation
- [x] Add `enable-param-enum` feature flag
  - https://github.com/tektoncd/pipeline/pull/7279
- [x] Introduce `Param.Enum` API fields, validation and conversion webhooks
  - https://github.com/tektoncd/pipeline/pull/7289
- [x] Implement TaskRun validation against `Param.Enum`
  - https://github.com/tektoncd/pipeline/pull/7326
- [x] Implement PipelineRun validation against `Param.Enum`
  - https://github.com/tektoncd/pipeline/pull/7338

### Promotion Feedback Issue:
  - https://github.com/tektoncd/pipeline/issues/7410

**Comment by QuanZhang-William** [comment]
This feature is implemented and will be available in v0.54 release!

/close

**Comment by dohoangkhiem** [comment]
Hey, this is causing issues after we upgraded to latest Tekton Pipeline, with `enable-param-enum` set to `true`. 

This line [https://github.com/tektoncd/pipeline/commit/8a8c0c39ca42a757077a8808aad0a9fcf749281e#diff-39d9baa708e379638f742c8b9fd36d9d15c64c3386de958b5a3f309ca8fa037aR825](https://github.com/tektoncd/pipeline/commit/8a8c0c39ca42a757077a8808aad0a9fcf749281e#diff-39d9baa708e379638f742c8b9fd36d9d15c64c3386de958b5a3f309ca8fa037aR825) does not work in case of task param value is a script which referenced multiple pipeline params. 

For example, this is the task in the pipeline 

```
    - name: push-s3
      runAfter:
        - install-build
      taskRef:
        name: aws-cli
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: SCRIPT
          value: |
            # this is to avoid aws-cli permission denied error on /.aws
            export HOME=/tmp/.aws
            aws s3 sync $(workspaces.source.path)/$(context.pipelineRun.name)/dist/ s3://$(params.s3-bucket)/$(params.s3-path) --delete --region $(params.aws-region) --debug
```
will result to 
`unexpected resolved param in ExtractVariablesFromString, expect 1 but got 3`

@QuanZhang-William
