### ISSUE TITLE
Support CEL's variable substitution in WhenExpression.CEL

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#7287]
CEL in WhenExpression has been [implemented](https://github.com/tektoncd/pipeline/issues/7244). And current [variable substitution](https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#use-cel-expression-in-whenexpression) only supports Tekton's variable substitution. e.g. 
```yaml
  when:
    # string result
    - cel: "$(tasks.unit-test.results.test-coverage) > 0.9"
    # array indexing result
    - cel: "$(tasks.unit-test.results.test-coverage[0]) > 0.9"
    # object result key
    - cel: "'$(tasks.objectTask.results.repo.url)'.matches('github.com/tektoncd/.*')"
    # string param
    - cel: "'$(params.foo)' == 'foo'"
    # array indexing
    - cel: "'$(params.branch[0])' == 'foo'"
    # object param key
    - cel: "'$(params.repo.url)'.matches('github.com/tektoncd/.*')"
```

CEL's variable substitution is:
```yaml
  when:
    # string result
    - cel: "tasks.unit-test.results.test-coverage > 0.9"
    # array indexing result
    - cel: "tasks.unit-test.results.test-coverage[0] > 0.9"
    # object result key
    - cel: "'tasks.objectTask.results.repo.url.matches('github.com/tektoncd/.*')"
    # string param
    - cel: "params.foo == 'foo'"
    # array indexing
    - cel: "params.branch[0] == 'foo'"
    # object param key
    - cel: "params.repo.url.matches('github.com/tektoncd/.*')"
```
