### ISSUE TITLE
Should it be possible to create a `Pipeline` without any `Task` ?

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#7375]
Given the following `Pipeline`, should it fail to create or succeed ? It is documented that `tasks` are required, so possible, it should fail to create. As of today, it does not.

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: testing
  namespace: default
spec:
  params:
    - name: abc
      type: string
    - description: ku
      name: abc1
      type: string
```

A follow-up question is: A `Pipeline` with no `Task` but one or more finally `Task`, should it fail to create or succeed ?
