### ISSUE TITLE
filterMatrixContextVar leads to panic: runtime error: index out of range [2] with length 1

### ISSUE THREAD

**Issue by SergK** [tektoncd/pipeline#7384]
# Expected Behavior
No issues should be observed. At least we had no such issues for the same pipelines on Pipeline version v0.53.0

# Actual Behavior
pipeline-controller restarts because of a panic issue
```
panic: runtime error: index out of range [2] with length 1

goroutine 197 [running]:
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/resources.filterMatrixContextVar({0xc001244e10?, 0x1, 0x2874a6a?})
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/resources/apply.go:163 +0x335
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/resources.ApplyPipelineTaskContexts(0xc000a0b5e0?, {{0x0, {0xc0003f42a0, 0x1, 0x1}, 0x0}, {0xc000de6588, 0x0, {0x0, 0x0, ...}, ...}}, ...)
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/resources/apply.go:185 +0x165
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).createTaskRun(0xc0004e2000, {0x2c656e0, 0xc0007df200}, {0xc000e87f80, 0x31}, {0x0, 0x0, 0x0}, 0xc000bab320, 0xc0004a6b40, ...)
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:890 +0x205
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).createTaskRuns(0xc0004e2000, {0x2c656e0, 0xc0007df050}, 0xc000bab320, 0x1?, 0x0?)
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:876 +0x385
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).runNextSchedulableTask(0xc0004e2000, {0x2c656e0, 0xc000df1560}, 0xc0004a6b40, 0xc0010c1028)
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:841 +0x9de
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).reconcile(0xc0004e2000, {0x2c656e0, 0xc000df14d0}, 0xc0004a6b40, 0x41184c8?, 0xc0003f4700)
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:725 +0x3892
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).ReconcileKind(0xc0004e2000, {0x2c656e0, 0xc000df1140}, 0xc0004a6b40)
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:264 +0xf8b
github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun.(*reconcilerImpl).Reconcile(0xc0007e8140, {0x2c656e0, 0xc000df1080}, {0xc000e86d80, 0x3e})
	github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun/reconciler.go:236 +0x582
knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc0002d4fc0)
	knative.dev/pkg@v0.0.0-20231011193800-bd99f2f98be7/controller/controller.go:542 +0x58d
knative.dev/pkg/controller.(*Impl).RunContext.func3()
	knative.dev/pkg@v0.0.0-20231011193800-bd99f2f98be7/controller/controller.go:491 +0x68
created by knative.dev/pkg/controller.(*Impl).RunContext
	knative.dev/pkg@v0.0.0-20231011193800-bd99f2f98be7/controller/controller.go:489 +0x312
```

# Steps to Reproduce the Problem

It is rather hard to reproduce the issue since we have hundreds of pipelines
1. Use tekton pipeline version v0.51.0
2. Upgrade tekton pipeline to v0.53.0
3. Periodically observe panic

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.10-eks-4f4795d", GitCommit:"164dfb62db432c0b28a1fced3956256af68533b6", GitTreeState:"clean", BuildDate:"2023-10-20T23:21:27Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.33.0
Chains version: v0.19.0
Pipeline version: v0.53.0
Triggers version: v0.25.2
```

Will try to find the root cause with pipeline example, that produce such behaviour

**Comment by pratap0007** [comment]
/assign @pratap0007
Hey, I am interested in this issue and am assigning to me

**Comment by Allen-yan** [comment]
I have the same issue. When I trigger a pipelineRun from event listener

Client version: 0.32.2
Pipeline version: v0.54.0
Triggers version: v0.25.3
Dashboard version: v0.41.0

I start a pipelineRun directly , the issue will not occur. But when start the same pipelineRun from event Listener ,the bug will definitely appear

**Comment by Allen-yan** [comment]
I have tried this version all have the same issue
Pipeline version: v0.54.0/v0.53.0
Triggers version:v0.25.3/v0.25.2

**Comment by joaosilva15** [comment]
Hey 👋 any update on this? I just got this today and it does not seem to be random. It happens when a param's value is set referencing another param's values. It is easy to reproduce in the tests, just add another parameter to [this test](https://github.com/tektoncd/pipeline/blob/v0.53.2/pkg/reconciler/pipelinerun/pipelinerun_test.go#L288-L298) like:
```
     params:
     - name: foo
       value: somethingfun
+    - name: foo2
+      value: $(params.foo)
     - name: bar
       value: $(params.bar)
     - name: contextRunParam
```
It seems like the controller does not check if the parameter exists or not and leaves this for the matrix evaluation, which then tries to split by `.` and access [index 2](https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/pipelinerun/resources/apply.go#L162-L163) which does not exist.

**Comment by chitrangpatel** [comment]
> /assign @pratap0007 Hey, I am interested in this issue and am assigning to me

@pratap0007 any progress on this? It's important to fix this ASAP. Please let us know if you need any assistance. 
If you don't have the bandwidth anymore please un-assign yourself so that we can identify someone else to provide a fix. 

Thanks 🙏

**Comment by joaosilva15** [comment]
I was sniffing around a bit more and here is what I found:
1. The test that I posted above will break with any parameter not found because the reconcile is not calling the validate that tests for parameters not defined. But when trying to apply it to the cluster the conditions change because the pipelinerun validation looks for it.
2. I could reproduce this in the cluster using task parameter values in other task parameter values.
3. This happens because [the param names for the tasks are being appended](https://github.com/tektoncd/pipeline/blob/main/pkg/apis/pipeline/v1/pipelinerun_validation.go#L165) to the validation dict for later checking and so task parameters using other task parameters name pass this test.
4. Later in parameter substitution these parameters are not replaced and then enter that if for the matrix evaluation, causing the panic.

What is the behaviour intended with the task params? Should it be possible to reference other parameters in a parameter's value? Or should this be checked and denied?

Despite all this, I believe this split should be checked to prevent the panic. I can create a PR to fix the panic and/or the parameter validation on the tasks

**Comment by chitrangpatel** [comment]
Thanks for the investigation @joaosilva15 !

I think from your example, its more like that value `params.param1` should be coming from one level above, i.e. params defined under pipelineSpec or pippelineRun (and propagated) and that would be perfectly valid. 

This is valid:

``` yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline1
spec:
  params:
    - name: param1
      value: "HELLO"
  pipelineSpec:
    params:
      - name: param1
    tasks:
      - name: test-params
        taskSpec:
          params:
            - name: param1
            - name: param2
          steps:
            - name: build
              image: public.ecr.aws/docker/library/golang:1.18.1-alpine
              script: |
                echo $(params.param1)
                echo $(params.param2)
        params:
          - name: param1
            value: "foo"
          - name: param2
            value: "$(params.param1)"
```
