### ISSUE TITLE
Feedback/beta release for TEP-0144: Param Enum

### ISSUE THREAD

**Issue by QuanZhang-William** [tektoncd/pipeline#7410]
### Feature looking for Promotion

Promote `Param Enum` feature to `beta`. `Param.Enum` allows resource authors to pre define a set of allowed values for a `param` and provides a built-in mechanism to perform param input value. This feature is guarded by dedicated feature flag `enable-param-enum` (setting it to `true` to experiment the feature).

### Current Feature Version
alpha
### Raise Feature Version
beta

### Pipeline Release

v0.54
### Issues Reported by the Users
- https://github.com/tektoncd/pipeline/issues/7084
- https://github.com/tektoncd/dashboard/issues/3193

### Implementation PRs
- https://github.com/tektoncd/pipeline/issues/7270

**Comment by martinmlouis** [comment]
Could you please add enum feature with array values support? It currently supports string only. This is must if we switch from jenkins UI to tekton UI for deployment. All is good for Continuous Delivery but for Continuous Deployment we need this, please  help

**Comment by QuanZhang-William** [comment]
Hi @martinmlouis 👋 , thanks for the feedback.

When designing the TEP, we left the `enum` support for `array` param to future work since the use cases was not clear to us (e.g. how do we validate an array against an allowlist, do we need the enum to be an array of arr? ).

If you have a clear use case of `enum` for `array` param, we can definitely extend the TEP to support it!

Is https://github.com/tektoncd/dashboard/issues/3193 your usecase? I was going through the discussion and it is still not clear how can an `enum` for array param type can help. But I'm happy to chat more about it.

**Comment by martinmlouis** [comment]
I am not sure of how you will implement it, but if I get - single select AND - multi select or - checkboxes from dashboard implementation it would sufficient for us

**Comment by QuanZhang-William** [comment]
cc @tektoncd/core-collaborators @tektoncd/core-maintainers

**Comment by vdemeester** [comment]
So one remark, missing piece is support of enum in objects, something like the following.

```yaml
    params:
    - name: go
      description: >-
        Golang options, such as flags, …
      type: object
      properties:
        version:
          type: string
          enum: ["1.19", "1.20", "1.21", "1.22"]
        GOFLAGS: {type: string}
        GOOS: {type: string}
        GOARCH: {type: string}
        CGO_ENABLED: {type: string}
      default:
        version: "1.21"
        GOFLAGS: "-v"
        GOOS: ""
        GOARCH: ""
        CGO_ENABLED: "0"
```

I'll create an issue about it.
