### ISSUE TITLE
Unable to Unmarshal Pipelines correctly after upgrade from 0.44 to 0.53.0

### ISSUE THREAD

**Issue by Richard87** [tektoncd/pipeline#7435]
# Expected Behavior

Unmarshalling Pipeline.Tasks.Params should work according to the spec:

# Actual Behavior

Notice how the first parameters is broken when unmarshalling.

We discoverre this when using a stricter unmarsal library:
```
panic: yaml: unmarshal errors:
  line 16: cannot unmarshal !!str `$(param...` into v1.ParamValue
```

- If we follow the documentation, the strict Unmarshall fails, but the k8s `sigs.k8s.io/yaml` works fine
- if we follow the crd it fails silently, and the stringVal is blank

```yaml
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: details
      params:
        # As defined by Struct Type:
        - name: tasktest1
          value:
            stringVal: $(params.test1)

        # As defined in Documentation
        - name: tasktest2
          value: $(params.test2)
      taskRef:
        name: task1
```
Results:
```
[]v1.PipelineTask{
    v1.PipelineTask{
        Name:"details",
        DisplayName:"",
        Description:"",
        TaskRef:(*v1.TaskRef)(0xc0003bfc80),
        TaskSpec:(*v1.EmbeddedTask)(nil),
        When:v1.WhenExpressions(nil),
        Retries:0,
        RunAfter:[]string(nil),
        Params:v1.Params{
            v1.Param{
                Name:"tasktest1",
                Value:v1.ParamValue{
                    Type:"object",
                    StringVal:"",
                    ArrayVal:[]string(nil),
                    ObjectVal:map[string]string{
                        "stringVal":"$(params.test1)"
                    }
                }
            },
            v1.Param{
                Name:"tasktest2",
                Value:v1.ParamValue{
                    Type:"string",
                    StringVal:"$(params.test2)",
                    ArrayVal:[]string(nil),
                    ObjectVal:map[string]string(nil)
                }
            }
        },
        Matrix:(*v1.Matrix)(nil),
        Workspaces:[]v1.WorkspacePipelineTaskBinding(nil),
        Timeout:(*v1.Duration)(nil),
        PipelineRef:(*v1.PipelineRef)(nil),
        PipelineSpec:(*v1.PipelineSpec)(nil),
        OnError:""
    }
}
```

# Steps to Reproduce the Problem

<details><summary>Code:</summary>
<p>

```go
package main

import (
	_ "embed"
	"fmt"

	pipelinev1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
	"sigs.k8s.io/yaml"
)

//go:embed pipeline.yaml
var content []byte

func main() {

	fmt.Printf("Parsing V1:\n")

	pipeline := &pipelinev1.Pipeline{}
	err := sigyaml.Unmarshal(content, pipeline)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%#v\n\n\n", pipeline.Spec.Tasks)

	err = goyaml.Unmarshal(content, pipeline)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%#v\n", pipeline.Spec.Tasks)
}

```

</p>
</details> 

# Additional Info

- Kubernetes version: 
```
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.7
```

```go.mod
module tekton-bug

go 1.21

require (
	github.com/tektoncd/pipeline v0.54.0
	gopkg.in/yaml.v3 v3.0.1
	sigs.k8s.io/yaml v1.4.0
)
```

- Tekton Pipeline version:
```
tkn version
Client version: 0.33.0
Pipeline version: v0.53.0
---
kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'
v0.53.0
```

Seems related to this issue: https://github.com/tektoncd/pipeline/issues/5803

**Comment by Yongxuanzhang** [comment]
I don't remember the documentation mentions the syntax of 
```
      params:
        - name: tasktest1
          value:
            stringVal: $(params.test1)
```
you should use
```
      params:
        - name: tasktest1
          value: $(params.test1)
```
If there are any documentations wrong, please let me know and we can clarify it
