### ISSUE TITLE
Inconsistent validation for the `image` field for Sidecar versus Step

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#7437]
# Expected Behavior
Without specific use cases(i.e. a ref is used in Step for referencing StepAction), users shall assume that sidecars and steps undergo identical validation processes.

# Actual Behavior

For Step validation:
```
Error from server (BadRequest): error when creating "sidecar-step-validation.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: missing field(s): spec.taskSpec.steps[0].Image
```
While for Sidecar it can only be observed via taskRun status:
```
tkn tr logs
? Select taskrun: sidecar-ready-x8nnj started 34 seconds ago
task Task 0 has failed: failed to create task run pod "sidecar-step-validaiton-x8nnj": Pod "sidecar-ready-x8nnj-pod" is invalid: spec.containers[1].image: Required value. Maybe invalid TaskSpec
Error: pod for taskrun sidecar-ready-x8nnj not available yet
```

There are two questions:
- Image field for both [Step](https://github.com/tektoncd/pipeline/blob/532591101c08d7f6103c3dd7cd005ef1a5c3f8cb/pkg/apis/pipeline/v1/container_types.go#L31) and [Sidecar](https://github.com/tektoncd/pipeline/blob/532591101c08d7f6103c3dd7cd005ef1a5c3f8cb/pkg/apis/pipeline/v1/container_types.go#L375) are marked as optional, but Step Image is being validated 
- Why does the static validation at admission webhook for Sidecar differentiate from that for Step, which made Sidecar validation error observable at runtime while Step validation failing admission webhook?

# Steps to Reproduce the Problem

Apply the following yaml with the image field of sidecar and step commented out one at a time.
```
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: sidecar-step-validation-
spec:
  taskSpec:
    sidecars:
    - name: slow-sidecar
       # image: ubuntu
      script: |
        echo "hello from sidecar" > /shared/message
      volumeMounts:
      - name: shared
        mountPath: /shared
    steps:
    - name: check-ready
      # image: ubuntu
      script: cat /shared/message
      volumeMounts:
      - name: shared
        mountPath: /shared
    # Sidecars don't have /workspace mounted by default, so we have to define
    # our own shared volume.
    volumes:
    - name: shared
      emptyDir: {}
```

# Additional Info

- Tekton Pipeline version:
devel
Client version: 0.33.0
Pipeline version: v0.54.0
