### ISSUE TITLE
sidecar always exits with exit code 1

### ISSUE THREAD

**Issue by lwabish** [tektoncd/pipeline#7439]
# Expected Behavior
When the step container exits with no error, side car exit with exit code 0, too
# Actual Behavior
The main part of my task is as follow:
```yaml
 ...
  sidecars:
    - image: colinianking/stress-ng
      name: stress
      script: |
        stress-ng -c 1
  steps:
    - name: control
      image: $(params.imageRegistry)/cloud-native-clients
      script: |
        if [ "$(params.skip)" = "true" ]; then
          echo "skipping"
          exit 0
        fi
 ...
```
When the step exits, the stress process in the sidecar container keeps running until the container is terminated with exit code 1 seconds later. 
The sidecar container log shows something like this: `exec /tekton/scripts/sidecar-script-0-ls7zf: no such file or directory` and the pod status changes to Failed.

I have seen the document saying that there is a bug relating to sidercar exiting problem but I am not quite sure if I am facing the same situation.
Whether or not, Is there any workaround? 

# Steps to Reproduce the Problem

1. prepare a task as shown before
2. run the task 

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:38:19Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10+rke2r1", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-19T17:41:09Z", GoVersion:"go1.19.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.50.3
```
