### ISSUE TITLE
cannot decode incoming new object: json: unknown field "TaskSpec"

### ISSUE THREAD

**Issue by willzhang** [tektoncd/pipeline#7472]
# Expected Behavior

run step-action success.

# Actual Behavior

run step-action failed.

# Steps to Reproduce the Problem

```
$ cat demo1.yaml 
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: step-action
spec:
  TaskSpec:
    params:
      - name: param-for-step-action
        description: "this is a param that the step action needs."
    steps:
      - name: action-runner
        ref:
          name: step-action
        params:
          - name: step-action-param
            value: $(params.param-for-step-action)
```

https://tekton.dev/docs/pipelines/stepactions/#passing-params-to-stepaction
![image](https://github.com/tektoncd/pipeline/assets/33590311/6e15785b-703a-450a-bf89-9fb1338b5f16)

```
$ kubectl apply -f demo1.yaml 
Error from server (BadRequest): error when creating "demo1.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "TaskSpec"
```

# Additional Info

- Kubernetes version:

```
root@kube001:/data/tekton/stepaction# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
root@kube001:/data/tekton/stepaction# 

```

- Tekton Pipeline version:

```
n# tkn version
Client version: 0.33.0
Chains version: v0.9.0
Pipeline version: v0.54.0
Triggers version: v0.25.3
Dashboard version: v0.42.0
```

i have config ` enable-step-actions: "true"`
```
root@kube001:/data/tekton/stepaction# kubectl -n tekton-pipelines get cm feature-flags  -o yaml
apiVersion: v1
data:
  await-sidecar-readiness: "true"
  coschedule: workspaces
  disable-affinity-assistant: "false"
  disable-creds-init: "false"
  enable-api-fields: beta
  enable-cel-in-whenexpression: "false"
  enable-param-enum: "false"
  enable-provenance-in-status: "true"
  enable-step-actions: "true"
  enable-tekton-oci-bundles: "false"
  enforce-nonfalsifiability: none
  keep-pod-on-cancel: "false"
  require-git-ssh-secret-known-hosts: "false"
  results-from: termination-message
  running-in-environment-with-injected-sidecars: "true"
  send-cloudevents-for-runs: "false"
  set-security-context: "false"
  trusted-resources-verification-no-match-policy: ignore
kind: ConfigMap
```

**Comment by willzhang** [comment]
> Hi @willzhang , I think that's a typo in the documentation. I think it needs to be `taskSpec` instead of `TaskSpec` in your yaml.
> 
> Can you try it and see if that works. I can then put in a fix ASAP.

I have try `taskSpec`, it still not work, maybe `kind: task` not support `TaskSpec`?  

and `kind: TaskRun` is ok.

```
root@kube001:/data/tekton/stepaction# cat task.yaml 
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: step-action-run
spec:
  TaskSpec:
    steps:
      - name: action-runner
        ref:
          name: example-stepaction-name
root@kube001:/data/tekton/stepaction# kubectl apply -f task.yaml 
taskrun.tekton.dev/step-action-run configured
```

**Comment by chitrangpatel** [comment]
Ah yes! There is no `TaskSpec` inside `kind: Task`. 

It needs to be `kind: TaskRun` and 
```
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: step-action
spec:
  taskSpec:
    params:
      - name: param-for-step-action
        description: "this is a param that the step action needs."
    steps:
      - name: action-runner
        ref:
          name: step-action
        params:
          - name: step-action-param
            value: $(params.param-for-step-action)
```

Or

```
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: step-action
spec:
  params:
    - name: param-for-step-action
      description: "this is a param that the step action needs."
  steps:
    - name: action-runner
      ref:
        name: step-action
      params:
        - name: step-action-param
          value: $(params.param-for-step-action)
```
