### ISSUE TITLE
default timeouts

### ISSUE THREAD

**Issue by flokain** [tektoncd/pipeline#7473]
### Feature request
refactor `default-timeout-minutes` to the following parameters in `[config-defaults](https://github.com/tektoncd/pipeline/blob/release-v0.54.x/config/config-defaults.yaml)`. 
```
default-timeout-pipeline-minutes: "40"  
default-timeout-task-minutes: "40"  
default-timeout-finally-minutes: "20"
```

```
timeouts:
  pipeline: "0h0m60s"
  tasks: "0h0m40s"
  finally: "0h0m20s"
```

### Use case
To be sure that by default finally sections get a chance to run one a timeout. Currently we have to set this on EVERY Pipelinerun. i would be neat to set this as default.

Also it would streamline the configuration options, as it is available in pipelineruns already.
