### ISSUE TITLE
Enum validation failed when Task Param referenced multiple Pipeline Params

### ISSUE THREAD

**Issue by QuanZhang-William** [tektoncd/pipeline#7476]
Reported in https://github.com/tektoncd/pipeline/issues/7270#issuecomment-1849488340

# Expected Behavior

Tekton should pass `enum` validation when a pipelineTasks-level `param` references multiple pipeline-level `params`:

```
- name: task1
     ...
      params:
        - name: SCRIPT
          value: |
            echo $(params.base-url)/$(params.path)
```

# Actual Behavior

`enum` validation failed due to `unexpected resolved param in ExtractVariablesFromString, expect 1 but got 2`

# Steps to Reproduce the Problem

1. Set `enable-param-enum: true`
2. Run following:

```
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: demo
spec:
  params:
    - name: base-url
      value: www.abc.com
    - name: path
      value: aaa
  pipelineSpec:
    params:
      - name: base-url
        enum: [www.abc.com, www.xyz.com]
    params:
      - name: path
        enum: [aaa, bbb]
    tasks:
      - name: task1
        params:
          - name: full-path
            value: "$(params.base-url)/$(params.path)"
        taskSpec:
          params:
            - name: full-path
          steps:
            - name: step1
              image: alpine
              script: |
                echo -n $(params.full-path)
```

# Additional Info

- Kubernetes version:
```
lient Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.8", GitCommit:"0ce7342c984110dfc93657d64df5dc3b2c0d1fe9", GitTreeState:"clean", BuildDate:"2023-03-15T13:39:54Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.10-gke.2700", GitCommit:"df2448d7739c44e41ee999b9065ce506cab86344", GitTreeState:"clean", BuildDate:"2023-06-22T09:25:37Z", GoVersion:"go1.19.9 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
v0.54
