### ISSUE TITLE
Result substitution fails on inlined spec pipelineRun if parameter name is not unique

### ISSUE THREAD

**Issue by cezar-guimaraes** [tektoncd/pipeline#7489]
# Expected Behavior
Result/parameter substitution should work the same if pipeline/task spec are inlined or not.

# Actual Behavior
If task parameter shares the same name as a pipeline parameter, result substitution fails.

# Steps to Reproduce the Problem

1. Apply the following pipelinerun
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-repro-
spec:
  params:
    - name: common
      value: "my param value"
  pipelineSpec:
    params:
      - name: common
    tasks:
      - name: taskone
        taskSpec:
          spec: null
          metadata: {}
          steps:
            - name: write-result
              image: busybox
              script: |
                #!/bin/sh
                echo 'my-result' > $(results.example.path)
          results:
            - name: example
      - name: tasktwo
        taskSpec:
          spec: null
          metadata: {}
          params:
            - name: common
          steps:
            - name: test
              image: busybox
              resources: {}
              script: |
                #!/bin/sh
                
                echo "$EXAMPLE"
          stepTemplate:
            env:
              - name: EXAMPLE
                value: $(params.common)
        runAfter:
          - taskone
        params:
          - name: common
            value: $(tasks.taskone.results.example)
```
2. `tasktwo` echo prints `$(tasks.taskone.results.example)`
3. If `tasktwo` parameter `common` is renamed to something different, `tasktwo` correctly prints `my-result`

# Additional Info

- Kubernetes version: v1.24

  **Output of `kubectl version`:** 

```
  WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.13-eks-0a21954", GitCommit:"6305d65c340554ad8b4d7a5f21391c9fa34932cb", GitTreeState:"clean", BuildDate:"2023-04-15T00:37:31Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.17-eks-4f4795d", GitCommit:"af19e454a15b5eb16d9f29d4d2361b3050ac78a6", GitTreeState:"clean", BuildDate:"2023-10-20T23:22:36Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version: 0.47

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'
v0.47.0%

```
