### ISSUE TITLE
[Discussion] Unify GitSource CRD &  PiplelineResource of type Git

### ISSUE THREAD

**Issue by sbose78** [tektoncd/pipeline#749]
Hi,

I'm Shoubhik from the OpenShift Developer Console team.

The DevConsole operator team is using a CRD called `GitSource` which represents a Git repo. Here's how it looks like

https://github.com/redhat-developer/devconsole-operator/blob/master/deploy/crds/devconsole_v1alpha1_gitsource_crd.yaml

```
apiVersion: devconsole.openshift.io/v1alpha1
kind: GitSource
metadata:
  name: example-gitsource
spec:
  url: "https://github.com/sclorg/nodejs-ex"
  ref: master
  contextDir: /cmd/manager
  httpProxy: http://proxy.example.com
  httpsProxy: https://proxy.example.com
  noProxy: somedomain.com, otherdomain.com
  secretRef:
    name: mysecret
  flavor: github
```

We use this for in our _suite_ of CRDs which also consists of Component CRD and GitSourceAnalysis CRD. The GitSource CRD has a controller which verifies the Git 'connection' for the repository and writes an _assertive_/_negative_ to the `status` field. 

The structure/spec has been inspired from the `BuildConfig` type and the reason we went for a new CRD altogether is because we wanted to store Git Source information in a way that we are able to use this outside the context of `BuildConfig` as well. Example, a user can import an application in OpenShift Developer Console and then launch it in `Che` in which case we could use the `GitSource` belonging to the associated app `Component` in Che for cloning code into Che ( and other Che to Git operations )

I feel the goal of `PipelineResource` of type 'git' and `GitSource` is similar - and should try unifying the effort :)

Let me know your thoughts!
