### ISSUE TITLE
Feature: Name based Remote Resolution 

### ISSUE THREAD

**Issue by wlynch** [tektoncd/pipeline#7508]
### Feature request

Previously you used to be able to reference OCI bundles via a simple `bundle` field:

```yaml
taskRef:
  bundle: docker.io/myrepo/mycatalog@sha256:abc123
```

but this has been marked as deprecated. 😢 
the new way is to use remote resolution, which looks much more verbose:

```yaml
taskRef:
    resolver: bundles
    params:
    - name: bundle
      value: docker.io/myrepo/mycatalog@sha256:abc123
```

I liked the simplicity of the field based approach - I want to see if we can bring a version of this back (at least for simple cases), and fall back to params for everything else. 🙏 

### Use case

`name` is already a part of the [remote resolver interface](https://github.com/tektoncd/pipeline/blob/c43d040d0954b152bd02878f7f55a43283e7441e/pkg/remote/resolver.go#L35) yet it is unused in the [actual implementation](https://github.com/tektoncd/pipeline/blob/c43d040d0954b152bd02878f7f55a43283e7441e/pkg/remote/resolution/resolver.go#L59).

I think we can use this to provide a short hand for remote resolution params for well-known types, e.g.:

```yaml
taskRef:
  name: bundle://docker.io/myrepo/mycatalog@sha256:abc123
```

Using `git` as another example:

```yaml
taskRef:
  name: git://github.com/wlynch/test@main#task.yaml?token=secret-name
```

which would resolve to:

```yaml
taskRef:
    resolver: git
    params:
    - name: url
      value: github.com/wlynch/test
    - name: revision
      value: main
    - name: pathInRepo
      value: task.yaml
    - name: token
      value: secret-name
```

And you could still mix-and-match params + name for anything that doesn't conform / isn't easily represented in a name-based format.

```yaml
taskRef:
  name: git://github.com/wlynch/test@main#task.yaml
  params:
    - name: token
      value: secret-name
```

This should be backwards compatible - `://` can't be in a valid k8s object name name, so there's a clear opt-in for this behavior.
This also won't effect existing remote resolution specs, since `name` is currently unused, which also means arbitrary resolvers can continue to be used.

cc @chitrangpatel

**Comment by vdemeester** [comment]
> ###
> 
> Previously you used to be able to reference OCI bundles via a simple `bundle` field:
> 
> ```yaml
> taskRef:
>   bundle: docker.io/myrepo/mycatalog@sha256:abc123
> ```
> but this has been marked as deprecated. 😢 the new way is to use remote resolution, which looks much more verbose:
> 
> ```yaml
> taskRef:
>     resolver: bundles
>     params:
>     - name: bundle
>       value: docker.io/myrepo/mycatalog@sha256:abc123
> ```

This is a missing some bits.
```yaml
# Before
taskRef:
  name: task-or-pipeline-to-get-from-bundle # to know which "resource" to get from the bundle
  bundle: docker.io/myrepo/mycatalog@sha256:abc123
# After
taskRef:
  resolver: bundles
  params:
  - name: bundle
    value: docker.io/myrepo/mycatalog@sha256:abc123
  - name: kind # probably optional, "can be inferred"
    value: task
  - name: name 
    value: task-or-pipeline-to-get-from-bundle
```


> I liked the simplicity of the field based approach - I want to see if we can bring a version of this back (at least for simple cases), and fall back to params for everything else. 🙏

I think you liked because it was more **concise**, not really more simple. The current syntax is verbose, but definitely not complex. In that regard, `git://github.com/wlynch/test@main#task.yaml?token=secret-name` or `bundle://docker.io/myrepo/mycatalog@sha256:abc123#task:name-of-the-task` is probably slightly more complex (to read or to write for the user, and to parse probably). 

If we dig a bit more:
- It would need to be `bundles://` instead of `bundle://` (because of the name of the resolver)
- What make a "field" to be part of the main scheme (`{name}://{main-part}?{options}`) and which one not ? e.g. for the `git` resolver, the `url` is probably obvious, *but* you can also use `repo` + `org` (without a `url`).
- Some resolver might be confusing to users. For example, `git://…` is a "scheme" support by the `git` command-line ; for a user who knows that, is it that "scheme" or something else ? Same for, the `http` resolver, would be use `https://{user}:{password}@example.com` ? What about the `http-password-secret-key` ? Or should we use `http://example.com/…?http-username=foo&http-password-secret-key=my-secret` ? Here, `http` is for the name of the resolver, not the real `http` protocol — what happens if I want to use HTTP without TLS or with, do I use `http://https://…` ?
- We can "decide"/"infer" how it "reslove" to for built-in resolvers, but how would it work for non built-in ? e.g. given `foo://bar#baz?toto=tata`, what should it resolve to ?
- From the previous item, would we restrict this to only the built-in resolvers ? It might also confuse some people, where they have different syntax depending on which resolver they use ?

What if we had a slightly different syntax (I think that was even in the inital TEP, we just moved away from it to stay consistent with how `params` is in other part of the API) ? (kind of what we want to do for `v2` already)

```yaml
# Before
taskRef:
  name: task-or-pipeline-to-get-from-bundle # to know which "resource" to get from the bundle
  bundle: docker.io/myrepo/mycatalog@sha256:abc123
# After
taskRef:
  resolver: bundles
  params:
  - bundle: docker.io/myrepo/mycatalog@sha256:abc123
  - kind: task # probably optional, "can be inferred"
  - name: task-or-pipeline-to-get-from-bundle
```

I tend to like the idea of conciseness, but I would want to make sure we are not making it more confusing, and that we can treat all resolvers the same.
