### ISSUE TITLE
TaskRun with extremely large params fails to run

### ISSUE THREAD

**Issue by rouke-broersma** [tektoncd/pipeline#7513]
# Expected Behavior

Either TaskRun is denied/invalid if param size is above certain limits or TaskRun starts successfully. 

# Actual Behavior

TaskRun fails with error `exec /bin/sh: argument list too long`

```
completionTime: '2023-12-20T13:49:51Z'
conditions:
  - lastTransitionTime: '2023-12-20T13:49:51Z'
    message: |
      init container failed, "place-scripts" exited with code 1 (image: "cgr.dev/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791"); for logs run: kubectl -n xxx logs yyy -c place-scripts
      
    reason: Failed
    status: 'False'
    type: Succeeded
podName: yyy
provenance:
  featureFlags:
    AwaitSidecarReadiness: true
    Coschedule: workspaces
    DisableAffinityAssistant: false
    DisableCredsInit: false
    EnableAPIFields: stable
    EnableCELInWhenExpression: false
    EnableKeepPodOnCancel: false
    EnableParamEnum: false
    EnableProvenanceInStatus: true
    EnableStepActions: false
    EnableTektonOCIBundles: false
    EnforceNonfalsifiability: none
    MaxResultSize: 4096
    RequireGitSSHSecretKnownHosts: false
    ResultExtractionMethod: termination-message
    RunningInEnvWithInjectedSidecars: true
    ScopeWhenExpressionsToTask: false
    SendCloudEventsForRuns: false
    SetSecurityContext: true
    VerificationNoMatchPolicy: ignore
startTime: '2023-12-20T13:49:47Z'
```

```
kubectl -n xxx logs yyy -c place-scripts
exec /bin/sh: argument list too long
```

# Steps to Reproduce the Problem

1. Create TaskRun with param containing more than 25K characters (it's a base64 encoded file)
2. TaskRun fails

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
clientVersion:
  buildDate: "2023-06-14T09:47:38Z"
  compiler: gc
  gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
  gitTreeState: clean
  gitVersion: v1.27.3
  goVersion: go1.20.5
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-10-23T08:13:55Z"
  compiler: gc
  gitCommit: a8a1abc25cad87333840cd7d54be2efaf31a3177
  gitTreeState: clean
  gitVersion: v1.28.3
  goVersion: go1.20.10
  major: "1"
  minor: "28"
  platform: linux/amd64
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.54.0
```
