### ISSUE TITLE
"From" does not work

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#755]
# Expected Behavior
This my pipeline:
```
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tutorial-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: build-model-image
      taskRef:
        name: build-docker-image-from-git-source
      params:
        - name: pathToDockerFile
          value: /workspace/docker-source/mnist/Dockerfile.model
        - name: pathToContext
          value: /workspace/docker-source/mnist/ #configure: may change according to your source
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: docker-image
            resource: docker-image
    - name: train
      taskRef:
        name: train-model
      resources:
        inputs:
          - name: train-image
            from:
              - build-model-image
```
I guess it's right, just follow the guide, I expect the task will run as build-model-image -> train
# Actual Behavior
I get error:
**pipelineTask tried to use input resource  not present in declared resources**

# Additional Info
I try to figure out what happened, then find the code in pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go
```
func getPipelineRunTaskResources(pt v1alpha1.PipelineTask, providedResources map[string]v1alpha1.PipelineResourceRef) ([]v1alpha1.TaskResourceBinding, []v1alpha1.TaskResourceBinding, error) {
	inputs, outputs := []v1alpha1.TaskResourceBinding{}, []v1alpha1.TaskResourceBinding{}
	if pt.Resources != nil {
		for _, taskInput := range pt.Resources.Inputs {
			// if len(taskInput.From) > 0 {
			// 	continue
			// }
			resource, ok := providedResources[taskInput.Resource]
			if !ok {
				return inputs, outputs, fmt.Errorf("pipelineTask tried to use input resource %s not present in declared resources", taskInput.Resource)
			}
			inputs = append(inputs, v1alpha1.TaskResourceBinding{
				Name:        taskInput.Name,
				ResourceRef: resource,
			})
		}
		for _, taskOutput := range pt.Resources.Outputs {
			resource, ok := providedResources[taskOutput.Resource]
			if !ok {
				return outputs, outputs, fmt.Errorf("pipelineTask tried to use output resource %s not present in declared resources", taskOutput.Resource)
			}
			outputs = append(outputs, v1alpha1.TaskResourceBinding{
				Name:        taskOutput.Name,
				ResourceRef: resource,
			})
		}
	}
	return inputs, outputs, nil
}
```
I don't know, the logic is not right, then I try to add additional code(the comment ones) and I get a memory error in 
**pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.ValidateFrom**

at the end, I pass the issue by add additional item in inputs section of the second task:
from:
```
      resources:
        inputs:
          - name: train-image
            from:
              - build-model-image
```
to:
```
      resources:
        inputs:
          - name: train-image
            resource: docker-image
            from:
              - build-model-image
```

So is this issue just a document error?
