### ISSUE TITLE
The Default and Run's `PodTemplate` (`env` and `volumes`) have not merged well

### ISSUE THREAD

**Issue by l-qing** [tektoncd/pipeline#7551]
# Expected Behavior
The `Env` and `Volumes` are merged well, this should be merged based on the `name`.
Merging the global env shouldn't have any side effects.

https://github.com/tektoncd/pipeline/blob/e59ee42163de4150f8951b135cbed14bf99b61fc/pkg/apis/pipeline/pod/template.go#L35-L40
https://github.com/tektoncd/pipeline/blob/e59ee42163de4150f8951b135cbed14bf99b61fc/pkg/apis/pipeline/pod/template.go#L56-L62

Otherwise this verification has no practical meaning.
Although the same env name is verified, the global env will not be considered during actual execution.
https://github.com/tektoncd/pipeline/blob/e59ee42163de4150f8951b135cbed14bf99b61fc/pkg/apis/pipeline/v1/taskrun_validation.go#L147-L158

## Refs:
* https://github.com/tektoncd/pipeline/pull/4057
* https://github.com/tektoncd/pipeline/issues/6846

# Actual Behavior
It's just a simple overlay.

https://github.com/tektoncd/pipeline/blob/e59ee42163de4150f8951b135cbed14bf99b61fc/pkg/apis/pipeline/pod/template.go#L174-L191

# Steps to Reproduce the Problem

1. Set the default configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
data:
  # TEP-0101 PodTemplate should support environment variables
  # https://github.com/tektoncd/community/blob/main/teps/0101-env-in-pod-template.md
  # https://github.com/tektoncd/pipeline/pull/5699
  default-forbidden-env: TEST_TEKTON1

  default-pod-template: |
    env:
    - name: "GLOBAL_ENV"
      value: "GLOBAL_ENV"
    - name: "TEST_TEKTON"
      value: "Global - TEST_TEKTON"

    volumes:
      - name: global-workspace-1
        hostPath:
          path: /tmp/global-workspace-1
          type: DirectoryOrCreate
      - name: global-workspace-2
        hostPath:
          path: /tmp/global-workspace-2
          type: DirectoryOrCreate
```

2. Create the `Task` and `TaskRun`
```
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: mytask
spec:
  workspaces:
    - name: workspace-1
    - name: workspace-2
  steps:
    - name: echo-env
      image: ubuntu
      imagePullPolicy: IfNotPresent
      command: ["bash", "-c", "--"]
      args:
        - |
          echo 'TEST_TEKTON:'$TEST_TEKTON ;
          echo 'GLOBAL_ENV:'$GLOBAL_ENV ;
      env:
        - name: "TEST_TEKTON"
          value: "true"
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: mytaskrun
spec:
  taskRef:
    name: mytask

  workspaces:
    - name: workspace-1
      emptyDir: {}
    - name: workspace-2
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 16Mi

  podTemplate:
    env:
      - name: "TEST_TEKTON"
        value: "false"

    volumes:
      - name: global-workspace-2
        hostPath:
          path: /tmp/taskrun-pod-template-workspace-2
          type: DirectoryOrCreate
```

3. Actual `TaskRun`
```
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
    tekton.dev/task: mytask
  name: mytaskrun
spec:
  podTemplate:
    env:
    - name: TEST_TEKTON
      value: "false"
    volumes:
    - hostPath:
        path: /tmp/taskrun-pod-template-workspace-2
        type: DirectoryOrCreate
      name: global-workspace-2
  serviceAccountName: default
  taskRef:
    kind: Task
    name: mytask
  timeout: 1h0m0s
  workspaces:
  - emptyDir: {}
    name: workspace-1
  - name: workspace-2
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 16Mi
      status: {}
```
4. Except `TaskRun`
```
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
    tekton.dev/task: mytask
  name: mytaskrun
spec:
  podTemplate:
    env:
    - name: TEST_TEKTON
      value: "false"
    - name: GLOBAL_ENV
      value: "GLOBAL_ENV"
    volumes:
    - hostPath:
        path: /tmp/taskrun-pod-template-workspace-2
        type: DirectoryOrCreate
      name: global-workspace-2
    - hostPath:
        path: /tmp/global-workspace-1
        type: DirectoryOrCreate
      name: global-workspace-1
  serviceAccountName: default
  taskRef:
    kind: Task
    name: mytask
  timeout: 1h0m0s
  workspaces:
  - emptyDir: {}
    name: workspace-1
  - name: workspace-2
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 16Mi
      status: {}
```

# Additional Info

- Kubernetes version:

```
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4
```

- Tekton Pipeline version:

```
v0.53.3
```

# Use Case

For instance, if I want to inject an environment variable into a pipeline executed by Tekton to distinguish whether it's running within a Tekton pipeline, I could configure a global environment variable.

Ref: [Get details about the current Continuous Integration environment.](https://github.com/watson/ci-info)
