### ISSUE TITLE
`cel` expression does not work when `tasks.<taskname>.status` is used

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/pipeline#7560]
# Expected Behavior
`cel` expression should work when `tasks.<taskname>.status` is used

# Actual Behavior
`cel` expression does not work when `tasks.<taskname>.status` is used

# Steps to Reproduce the Problem

1. Create a task
2. Create a pipeline with finally task and use the cel expression with `tasks.<taskname>.status` for the task in finally section
3. Run the pipeline

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
 Client Version: v1.27.9
 Kustomize Version: v5.0.1
 Server Version: v1.27.8+4fab27b
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
 Client version: 0.31.3
 Chains version: v0.19.0
 Pipeline version: v0.53.3
 Triggers version: v0.25.3
 Operator version: v0.69.1
```

**Pipeline:**
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: when-with-two-cel-expressions
  namespace: varadhya
spec:
  finally:
    - name: echo-task-u59
      params:
        - name: message
          value: Second
      taskRef:
        kind: Task
        name: echo-task
      when:
        - cel: '''$(tasks.echo-task.status)'' == ''Succeeded'''
  params:
    - name: test-param
      type: string
  tasks:
    - name: echo-task
      params:
        - name: message
          value: First
      taskRef:
        kind: Task
        name: echo-task
```

**Pipelinerun Skippedtask section**:
```
skippedTasks:
    - name: echo-task-u59
      reason: When Expressions evaluated to false
      whenExpressions:
        - cel: '''Succeeded'' == ''Succeeded'''
```
