### ISSUE TITLE
git resolver does not work with repositories with a symlink

### ISSUE THREAD

**Issue by concaf** [tektoncd/pipeline#7561]
# Expected Behavior

a symlink being present in the remote git repo should be inconsequential for the git resolver to function

# Actual Behavior

if the remote git repo has a symlink, then the remote resolution fails with the error -
```
checkout error: worktree contains unstaged changes
```

the resolution request shows this as well, but i don't have the output - i do have logs from the remote-resolvers pod though -

`{"severity":"error","timestamp":"2024-01-11T11:41:49.669Z","logger":"controller","caller":"controller/controller.go:566","message":"Reconcile error","commit":"e59ee42","knative.dev/traceid":"e14854a9-45fe-4120-a304-5b287fd5e39e","knative.dev/key":"default/git-3bfb7d8d2e23690240e63c76dce6902f","duration":1.072205099,"error":"error getting \"Git\" \"default/git-3bfb7d8d2e23690240e63c76dce6902f\": checkout error: worktree contains unstaged changes","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20231023150739-56bfe0dd9626/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20231023150739-56bfe0dd9626/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20231023150739-56bfe0dd9626/controller/controller.go:491"}`

# Steps to Reproduce the Problem

1. create a pipeline and push to your git repo:
```yaml
kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: a-simple-pipeline
spec:
  params:
  - name: username
  tasks:
  - name: task-1
    params:
    - name: username
      value: $(params.username)
    taskSpec:
      params:
      - name: username
      steps:
      - image: alpine:3.15
        script: |
          echo "hello $(params.username)"
```

2. create a pipelinerun pointing to the remote git repo:
```yaml
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: run-basic-pipeline-from-git
spec:
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/concaf/tmp.git 
    - name: revision
      value: test
    - name: pathInRepo
      value: git-resolver/pipeline.yaml
  params:
  - name: username
    value: liza
```

3. note the symlink in my remote repo at https://github.com/concaf/tmp/tree/test/kedge-blog

4. when you create the pipelinerun, note the error in tekton resolvers pod and the resolution request:
```
checkout error: worktree contains unstaged changes
```

5. removing the symlink from the remote git repo fixes this.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.27.3
```

- Tekton Pipeline version:

```
Client version: 0.33.0
Pipeline version: v0.55.0
```

while speaking with @vdemeester, he pointed out that this might be caused by https://github.com/go-git/go-git/issues/511
