### ISSUE TITLE
Add support for enum in object params

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#7568]
### Feature request

It should be possible to use enum in parameters of type `object` on string fields.

### Use case

An example of usage would be:

```yaml
    params:
    - name: go
      description: >-
        Golang options, such as flags, …
      type: object
      properties:
        version:
          type: string
          enum: ["1.19", "1.20", "1.21", "1.22"]
        GOFLAGS: {type: string}
        GOOS: {type: string}
        GOARCH: {type: string}
        CGO_ENABLED: {type: string}
      default:
        version: "1.21"
        GOFLAGS: "-v"
        GOOS: ""
        GOARCH: ""
        CGO_ENABLED: "0"
```
