### ISSUE TITLE
Can we use the values present inside a configmap and refer those in a when condition

### ISSUE THREAD

**Issue by AshwinSridharan0410** [tektoncd/pipeline#7607]
So, my need is, I want to enable a global variable called codeqlscan in tekton. So the value for this comes from a configMap 
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config-codeql
data:
  enableCodeqlScanGlobal: "true"
  
  So the flow is , my pipeline should refer this configmap and when the enableCodeqlScanGlobal value is false, a task say.codeql scan should not participate in that . 
  I want to use this variable in the when condition .
  
  And based on this global variable, participation of task should  happen in a pipeline

**Comment by AshwinSridharan0410** [comment]
Yep. Thanks.

**Comment by AlanGreene** [comment]
Here's an example of a PipelineRun that loads a key from a ConfigMap into an environment variable, emits it as a result, and uses it as input to a when expression:

```yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: configmap-guard-
spec:
  pipelineSpec:
    tasks:
      - name: load-configmap
        taskSpec:
          results:
            - name: feature-flag
          steps:
            - name: get-feature-flag
              image: alpine
              env:
                - name: FEATURE_FLAG
                  valueFrom:
                    configMapKeyRef:
                      name: feature-flags
                      key: myFeatureFlag
              script: |
                #!/usr/bin/env sh
                echo -n $FEATURE_FLAG | tee $(results.feature-flag.path)
      - name: guarded
        when:
          - input: "$(tasks.load-configmap.results.feature-flag)"
            operator: in
            values: ["true"]
        taskSpec:
          steps:
            - name: guarded
              image: alpine
              script: |
                #!/usr/bin/env sh
                echo Hello
```
