### ISSUE TITLE
Tekton Approval Task Yaml apply failed

### ISSUE THREAD

**Issue by tppalani** [tektoncd/pipeline#7625]
# Expected Behavior

Yaml file should be   applied

# Actual Behavior

Not Able to apply yaml file

# Steps to Reproduce the Problem

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: stage-approval-task
spec:
  inputs:
    params:
      - name: approvalDecision
        description: "Approval decision (approve/reject)"
        type: string
  steps:
    - name: stage-approval-task
      image: my-approval-image
      command: [sh, -c]
      args: ["echo 'Approval decision: $(inputs.params.approvalDecision)'"]
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`: 1.26**

```
(paste your output here)
```

- Tekton Pipeline version: 

  **Output of `v0.48.0` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
kubectl apply -f stage-approval-task.yaml
Error from server (BadRequest): error when creating "stage-approval-task.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "inputs"

```
