### ISSUE TITLE
When a duplicate parameter name is encountered in the pipeline, there is an issue with inaccurate path reporting.

### ISSUE THREAD

**Issue by l-qing** [tektoncd/pipeline#7650]
# Expected Behavior

```
admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: params names must be unique, the same param: abc is defined multiple times at:
spec.tasks[0].params[1].name
```

# Actual Behavior

```
admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: parameter names must be unique, the parameter "abc" is also defined at:
spec.tasks.params[0][1].name, spec.tasks[0].params[1].name
```

# Steps to Reproduce the Problem

1. Create a pipeline
```
cat <<EOF | kubectl create -f -
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: name-1
      taskRef:
        name: hi
        kind: Task
      params:
        - name: "abc"
          value: ""
        - name: "abc"
          value: ""
EOF
```

# Additional Info

- Kubernetes version:

```
Client Version: v1.29.1
Server Version: v1.27.7
```

- Tekton Pipeline version:

```
v0.56.0
```
