### ISSUE TITLE
Support for variable interpolation in workspace.configmap.items * (in PipelineRun and TaskRun)

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/pipeline#7667]
This is follow up issue of https://github.com/tektoncd/pipeline/issues/6384 

Currently, we do support workspace provided as

```
    - name: custom4
      configMap:
        name: $(params.name)-configmap
        items:
          - key: message
            path: my-message.txt 
```

but we do not support workspace provided as

```
    - name: custom4
      configMap:
        name: $(params.name)-configmap
        items:
          - key: message
            path: $(params.name)-message.txt 
 ```

This is to add the support for param replacement at items level in workspace
