### ISSUE TITLE
Variable substitution of Task spec.steps[].name is broken.

### ISSUE THREAD

**Issue by Ferenc-** [tektoncd/pipeline#7669]
# Expected Behavior

According [to the docs](https://tekton.dev/docs/pipelines/variables/#fields-that-accept-variable-substitutions) `Task spec.steps[].name`, accepts variable substitution, so the exepcted behaviour is that the task would be created.

# Actual Behavior

````
Error from server (BadRequest): error when creating "/tmp/string.txt": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value "test$(params.dnsLabelName)": spec.steps[0].name
Task step name must be a valid DNS Label, For more info refer to https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
````
# Steps to Reproduce the Problem

1. Create Task:
````
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-task
spec:
  params:
  - name: dnsLabelName
    type: string
  steps:
    - name: test$(params.dnsLabelName)
      image: busybox
````

# Additional Info

- Kubernetes version:

```
kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6+IKS
```

- Tekton Pipeline version:

```
tkn version
Client version: 0.35.1
Pipeline version: v0.56.1
Dashboard version: v0.43.1

```
