### ISSUE TITLE
Entrypoint cannot be found in private repository image

### ISSUE THREAD

**Issue by wilstdu** [tektoncd/pipeline#7698]
# Expected Behavior

Task without command and script arguments can resolve entrypoint from image manifest laying in a private repository.

# Actual Behavior

`PodCreationFailed.`

Tekton Pipelines controller receives this error:
`Failed to create task run pod for taskrun \"tester-17\": failed to create task run pod \"tester-17\": translating TaskSpec to Pod: GET https://<redacted-account-id>.dkr.ecr.<redacted-region>.[amazonaws.com/v2/](http://amazonaws.com/v2/)<redacted-repo>/<redacted>/manifests/<redacted-sha>: unexpected status code 401 Unauthorized: Not Authorized\n. Maybe missing or invalid Task default/resolve-dependencies`

Issue started occurring since v0.55.0. With exactly the same system setup and older Tekton Pipelines version is was still working.

# Steps to Reproduce the Problem

1. Tekton deployed on AWS EKS
2. Tekton running at least 0.55.0
3. Image is available in private ECR repository
4. Nodes have required IAM policies attached to pull from private ECR repositories
5. Apply a TaskRun that references Task having a step with image from private ECR repository

# Additional Info
Discussion on Slack: https://tektoncd.slack.com/archives/CJ62C1555/p1708526794010999
Tekton is installed via Tekton Operator with this configuration, but operator doesn't seem to have impact for this error:
```
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: lite
  targetNamespace: tekton-pipelines
  config:
    nodeSelector:
      kubernetes.io/os: linux
    priorityClassName: system-cluster-critical
  chain:
    disabled: true
  pipeline:
    enable-api-fields: alpha
    enable-tekton-oci-bundles: true
    disable-affinity-assistant: true
```

- Kubernetes version:
```
EKS 1.28
```
