### ISSUE TITLE
StepAction steps order not preserved, error: unexpected end of JSON input

### ISSUE THREAD

**Issue by uqix** [tektoncd/pipeline#7707]
# Expected Behavior

StepAction steps order is preserved, and steps successfully complete.

# Actual Behavior

<img width="935" alt="image" src="https://github.com/tektoncd/pipeline/assets/10142314/b15142b9-825e-49a9-a898-6460e91a969d">

* StepAction steps order not preserved

```yaml
apiVersion: tekton.dev/v1
kind: TaskRun

status:
  steps:
    - container: step-report-on-start
    - container: step-checkout-source
    - container: step-build-ts
  taskSpec:
    steps:
      - name: report-on-start
      - name: build-ts
      - name: checkout-source
spec:
  taskSpec:
    steps:
      - name: report-on-start
        ref:
          name: cpp-report-v1
      - name: build-ts
        ref:
          name: build-ts-v1
      - name: checkout-source
        ref:
          name: git-checkout-v1
```
* error: unexpected end of JSON input

# Steps to Reproduce the Problem

1. Pipeline:
```yaml
apiVersion: tekton.dev/v1
kind: Pipeline

metadata:
  name: build-module-nodejs-frontend-v1-dev
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    app.kubernetes.io/version: "1.0.6"

spec:
  workspaces: &w
    - name: affinity-assistant-placeholder

  params:
    - name: repository
    - name: branch
    - name: commit

    - name: cpp-build-id
      default: ""

    - name: app

    - name: run-subpath
      default: ""

    - name: app-subpath
      default: ""

    - name: artifact-subpath
      default: "dist"

    - name: skip-reporting-status
      enum: ["true", "false"]
      default: "true"

    - name: skip-uploading-artifact
      enum: ["true", "false"]
      default: "true"

    - name: skip-cleaning
      default: "false"

    - name: node-version
      default: 10.16.3

    - name: node-options
      default: ""

    - name: build-script
      default: build

    - name: build-script-options
      default: ""

    - name: package-manager
      default: npm

    - name: enable-lockfiles
      default: "false"

    - name: deep-clean-first
      default: "false"

  tasks:
    - name: main

      workspaces: *w
      params:
        - name: skip-reporting-status
          value: $(params.skip-reporting-status)
        - name: cpp-build-id
          value: $(params.cpp-build-id)
        - name: run-subpath
          value: $(params.run-subpath)
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: commit
          value: $(params.commit)
        - name: deep-clean-first
          value: $(params.deep-clean-first)

      taskSpec:
        workspaces: *w

        params:
          - name: skip-reporting-status
          - name: cpp-build-id
          - name: run-subpath
          - name: repository
          - name: branch
          - name: commit
          - name: deep-clean-first

        volumes:
          - name: global-tekton-run
            hostPath:
              path: /mnt/d1/global-tekton-run
          - name: git-credentials-config
            secret:
              secretName: git-credentials-config

        steps:
          - name: report-on-start
            ref:
              name: cpp-report-v1
            params:
              - name: when
                value: $(params.skip-reporting-status) = false
              - name: build-id
                value: $(params.cpp-build-id)
              - name: pipelinerun-name
                value: $(context.pipelineRun.name)

          - name: build-ts
            ref:
              name: build-ts-v1

          - name: checkout-source
            ref:
              name: git-checkout-v1
            params:
              - name: run-subpath
                value: $(params.run-subpath)
              - name: pipelinerun-name
                value: $(context.pipelineRun.name)

              - name: repository
                value: $(params.repository)
              - name: branch
                value: $(params.branch)
              - name: commit
                value: $(params.commit)

              - name: deep-clean
                value: $(params.deep-clean-first)

```
2. PipelineRun:
```yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-module-nodejs-frontend-v1-dev-
  labels:
    tekton/concurrency-group: build-module-nodejs-frontend-v1-dev
    tekton/run-group: build-module-nodejs-frontend-v1-dev

spec:
  pipelineRef:
    name: build-module-nodejs-frontend-v1-dev

  workspaces:
    - name: affinity-assistant-placeholder
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Mi

  params:
    - name: repository
      value: http://...
    - name: branch
      value: master
    - name: commit
      value: 40c2949ead55eb1174e53e22b71e9208038761de

    - name: app-subpath
      value: vue-demo

    - name: app
      value: vue-demo

    - name: enable-lockfiles
      value: "true"

    # - name: deep-clean-first
    #   value: "true"
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:21:34Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:14:09Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.57.0
```

- Running these StepAction by single-step `TaskRun` works:

```yaml
apiVersion: tekton.dev/v1
kind: TaskRun

metadata:
  generateName: git-checkout-v1-dev-

spec:
  taskSpec:
    volumes:
      - name: global-tekton-run
        hostPath:
          path: /mnt/d1/global-tekton-run
      - name: git-credentials-config
        secret:
          secretName: git-credentials-config

    steps:
      - name: test
        ref:
          name: git-checkout-v1

        params:
          - name: repository
            value: http://...
          - name: branch
            value: master
          - name: commit
            value: cba00968deb75a12a683786e2add6639e0775403

```

**Comment by vdemeester** [comment]
@uqix thanks for the report. I am not sure I understand the relation between the error (in a step `unexpected end of JSON input` is the log of a step execution) and the order in the status. The order in the list in the status, doesn't necessarily reflect the execution order (I don't think we give any guarantees there).

Without the definition of the `StepAction`, it is a bit hard to debug your issue. Can you share the definition of the `StepAction` ?

**Comment by uqix** [comment]
Sorry for late reply, here's the simplified yaml to reproduce the problem:

* stepaction:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: git-checkout
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    app.kubernetes.io/version: "1.0.0"
spec:
  image: bitnami/git:2.41.0
  script: |
    #!/usr/bin/env bash
    set -exu -o pipefail +o histexpand
    shopt -s inherit_errexit extglob
    echo test
```

* taskrun:

```yaml
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: build-ts-v1-dev-
spec:
  taskSpec:
    steps:
      - name: test
        ref:
          name: git-checkout-v1
      - name: test2
        ref:
          name: git-checkout-v1
      - name: test3
        ref:
          name: git-checkout-v1
```

* Error:
<img width="740" alt="image" src="https://github.com/tektoncd/pipeline/assets/10142314/428ccbe2-fa4c-47c2-a447-d846974b18de">

* Some experiment:

```yaml
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: build-ts-v1-dev-
spec:
  taskSpec:
    steps:
      - name: test
        ref:
          name: git-checkout-v1
      - name: test2
        ref:
          name: git-checkout-v1
      # - name: test3
      #   ref:
      #     name: git-checkout-v1
```

<img width="774" alt="image" src="https://github.com/tektoncd/pipeline/assets/10142314/76f0e7df-ffd3-4246-b015-06f6a385cf99">

Comment out 3rd step, it suddenly works.

**Comment by vdemeester** [comment]
![2024-02-26-100955](https://github.com/tektoncd/pipeline/assets/6508/5b67cc3e-dc09-4cb0-8e3b-c9b8c571d40c)

Interesting, it *just* works for me. I wonder if the "unexpected end of json input" might be dashboard related only ? (cc @AlanGreene as I am clueless 🙃 )

*nit: `git-checkout-v1` should be `git-checkout` in your `TaskRun` example though*

**Comment by vdemeester** [comment]
@uqix how does the `TaskRun` looks like from the API or CLI ? (`kubectl get taskrun build-ts-…`)

**Comment by AlanGreene** [comment]
"unexpected end of JSON input" is being returned in the pod logs, it's not something added by the Dashboard. The timestamp is part of the logs too returned by the k8s API server.

**Comment by uqix** [comment]
Here's some significant diffs of their pods: (left side from the 2-steps task, right side from the 3-steps task)

1st container:

<img width="1247" alt="image" src="https://github.com/tektoncd/pipeline/assets/10142314/15249565-f402-438d-bcac-5b1ec2e4f6e9">

2nd container:

<img width="1257" alt="image" src="https://github.com/tektoncd/pipeline/assets/10142314/639d0301-88f9-4ad1-b32b-b819846cfc63">

Those container args of the 3-steps task (right side) seem weird.

**Comment by uqix** [comment]
My `feature-flags` configmap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tekton-pipelines
  name: feature-flags
data:
  enable-api-fields: alpha
  enable-param-enum: "true"
  enable-step-actions: "true"
```
