### ISSUE TITLE
Task results can't be used in resolver parameters of other tasks

### ISSUE THREAD

**Issue by fische** [tektoncd/pipeline#7716]
# Expected Behavior

I am currently playing with the resolver concept and trying to understand everything that is possible with it. I was particularly interested in being able to re-use a task result in the resolver parameters, so a task outcome could decide the next task to run. I know you can do this statically but I was more interested in a dynamic approach.

Let's say in some pipeline, `task-a` outputs a `target` result and `task-b` has the following reference:
```
      taskRef:
        resolver: woodhouse-git
        params:
        - name: target
          value: $(tasks.task-a.results.target)
```

I would expect `$(tasks.task-a.results.target)` to be substituted in the ResolutionRequest for `task-b`.

# Actual Behavior

`$(tasks.task-a.results.target)` is not substituted in the ResolutionRequest.

# Steps to Reproduce the Problem

I just applied the following:
```
kind: PipelineRun
apiVersion: tekton.dev/v1
metadata:
  generateName: some-pipeline-
spec:
  pipelineSpec:
    params:
    - name: commit
    tasks:
    - name: task-a
      taskSpec:
        results:
        - name: target
          description: target for next task
        steps:
        - image: alpine:3.15
          script: |
            echo "//corp/woodhouse/tasks:task-a" > $(results.target.path)
    - name: task-b
      taskRef:
        resolver: woodhouse-git
        params:
        - name: repo
          value: git@github.com:tektoncd/pipeline.git
        - name: commitish
          value: $(params.commit)
        - name: target
          value: $(tasks.task-a.results.target)
  params:
  - name: commit
    value: "master"
```

This created the following ResolutionRequest:
```
apiVersion: resolution.tekton.dev/v1beta1
kind: ResolutionRequest
metadata:
  creationTimestamp: "2024-02-26T13:54:48Z"
  generation: 1
  labels:
    resolution.tekton.dev/type: woodhouse-git
  name: woodhouse-git-ff164e182c04759de8ea8acdd2ba272b
  namespace: woodhouse-tekton
  ownerReferences:
  - apiVersion: tekton.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: PipelineRun
    name: some-pipeline-qsqc7
    uid: 4fa2e350-a62e-40d2-be2e-ba5fe67b20c9
  resourceVersion: "1239944"
  uid: e5456bb6-e738-4147-a917-ce55e8fb8ff7
spec:
  params:
  - name: repo
    value: git@github.com:tektoncd/pipeline.git
  - name: commitish
    value: master
  - name: target
    value: $(tasks.task-a.results.target)
```

Notice the `target` value: `$(tasks.task-a.results.target)`, while I was expecting it to be `//corp/woodhouse/tasks:task-a` as outputted by `task-a`.

I have also just realised that the ResolutionRequests for pipeline's tasks get created right when the PipelineRun is created (which is most likely related to this issue) and are owned by that PipelineRun. I don't understand this approach as it would have been so much simpler (and worked so much nicer with the rest), if the PipelineRun instead created the TaskRuns, and then those would create the ResolutionRequests. This would've meant that you would not need the additional logic when reconciling pipelines to check if there's any task to resolve and start their resolution, and instead you would be able to start the pipeline ASAP. I guess the only "tradeoff" with this is that you won't see a resolution failure immediately.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.17", GitCommit:"22a9682c8fe855c321be75c5faacde343f909b04", GitTreeState:"clean", BuildDate:"2023-08-23T23:44:35Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.11", GitCommit:"3cd242c51317aed8858119529ccab22079f523b1", GitTreeState:"clean", BuildDate:"2023-11-15T16:50:12Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.50.0
```
