### ISSUE TITLE
Related metrics tag name is wrong

### ISSUE THREAD

**Issue by cugykw** [tektoncd/pipeline#7730]
When i used remote pipeline to replace the old reference pipeline approach, 
I found that my grafana dashboard data was inaccurate，There are some pipeline metrics issues.

![image](https://github.com/tektoncd/pipeline/assets/19320253/0263179d-8963-44f5-b2a6-6e85282a985a)

# Expected Behavior

The task name in taskrun-related metrics is not empty, and the pipeline name 
in pipelinerun-related metrics is not `anonymous`.

# Actual Behavior
The relevant metrics tag names should be set correctly.

# Steps to Reproduce the Problem

1.
```
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: reproduce
spec:
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://git.example.com/example/remote.yml
    - name: revision
      value: main
    - name: pathInRepo
      value: pipeline.yml
```
2. Resources in the git repository:
```
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: reproduce
spec:
  tasks:
  - name: f-1
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://git.example.com/example/remote.yml
      - name: revision
        value: main
      - name: pathInRepo
        value: task.yml
```

```
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: reproduce
spec:
    steps:
    - image: centos7
      imagePullPolicy: Always
      name: demo
      script: |
        echo "hello"
```

# Additional Info

tekton: 0.53.0
