### ISSUE TITLE
Windows script requires escape chars to run successfully, Linux script does not

### ISSUE THREAD

**Issue by fabar022windriver** [tektoncd/pipeline#7740]
# Expected Behavior
Windows and Linux script should behave the same way when you are writing the scripts. Windows should not require to escape special chars.

# Actual Behavior
Windows and Linux scripts are considering different validations about escaping chars
 
For example for windows you need to create the script as follow, if not the var are going to be added to the file as an empty value:
```
#!win powershell.exe -File
`$text="some value"
echo `$text
```

For Linux cases it is not necessary to keep escaping char, so the coding is more natural.

# Steps to Reproduce the Problem

```
apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: Task
metadata:
  name: example-task-name
spec:
  steps:
    - name: powershell
      image: mcr.microsoft.com/powershell
      script: |
        #!win powershell.exe -File
        $text="some value"
        echo $text
```

# Additional Info
A possible solution is to encode the script before create the file, like the non windows script logic https://github.com/tektoncd/pipeline/blob/main/pkg/pod/script.go#L189

When a script requires windows, the script can be encoded and then create the output file command like the following example:
https://github.com/tektoncd/pipeline/blob/main/pkg/pod/script.go#L177C3-L180C23

```
script = encodeScript(script)
initContainer.Args[1] += fmt.Sprintf(`@"
[System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String(%s))
"@ | Out-File -FilePath %s
`, script, scriptFile)
```

- Kubernetes version:

 v1.27.9-eks-5e0fdde

- Tekton Pipeline version:

v0.56.1
