### ISSUE TITLE
PodTemplate for specific Task without TaskRun

### ISSUE THREAD

**Issue by MitchelNijdam-Rockstars** [tektoncd/pipeline#7749]
I have a setup where we have `Pipeline`, some `Task`s and a `TriggerTemplate`. Pipelines are triggered by a Github webhook, so we are not manually creating `PipelineRuns` or `TaskRuns`.

Now, I would like to force **only one of my tasks** to be scheduled on the same node that contains a Pod with a certain label. Restricting all the Tasks to the same node will decrease the chance of them being scheduled in time.

I've seen that there is `TaskRun.spec.podTemplate`. However, the `TaskRuns` are created automatically, so that's not an option.
Another option is the `TriggerTemplate.spec.resourcetemplates.spec.podTemplate`, but that is applied for all the `Tasks` in the Pipeline.

Now my question is, can I define a `podTemplate` on `Task` level?

Current `TriggerTemplate`:

```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: my-trigger-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      spec:
        podTemplate:
          # Needed so that the publish-results task can write to the same PVC used by the nginx server
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: shared-test-results-pvc
                        operator: In
                        values:
                          - "true"
                  topologyKey: "kubernetes.io/hostname"
```
