### ISSUE TITLE
gcs storage input cannot overwrite files from git input

### ISSUE THREAD

**Issue by pwittrock** [tektoncd/pipeline#775]
# Expected Behavior

- git input creates dir in `gitspace`
  - has file `gitspace/foo/secret`
- gcs input copies `secret` file into `gitspace/foo` dir

- gcs overwrites the existing file in the git input with the one from gcs

# Actual Behavior

- gcs doesn't overwrite the existing file in the git input with the one from gcs

# Steps to Reproduce the Problem

```yaml
    inputs:
      resources:
      - name: gitspace
        type: git
      - name: gssecrets
        type: storage
        targetPath: "gitspace/path/to/dir"
```

# Additional Info

**Comment by bobcatfish** [comment]
Worked with @elizucker to investigate this and we found that the reason these are not being applied in the expected order is because of this:

https://github.com/tektoncd/pipeline/blob/c137ac5a2a6b9c8a0f263830e4ff27d70528ea20/pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go#L135

The variable `taskSpec.Steps` is being used to hold the complete list of containers that will be executed by the pod, and they are executed in the order that they appear in that list. We are using the `append(, ...)` syntax to pre-pend the resource containers, so they are executed before the actual steps. Because of this shortcut, the resources are being applied in the reverse order.

(So @pwittrock that means you can actually work around your problem if you want by reversing the order the resources are declared in! 🤭 😅 Though when we "fix" this you'll have to change it again...)

Possible solutions:

1. Declare that users should _not_ depend on the order the resources are declared in
2. Decide that this order _is_ part of the API and apply resources in the order they appear in <-- I lean toward this one b/c it is the way steps work and seems intuitive but would be interested if ppl feel differently!

p.s. interestingly even if a bucket only contains one file and you configure the repo to point directly at it, it is still checked out into a dir (even if `dir` is false):

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: magic-bucket
spec:
  type: storage
  params:
    - name: type
      value: gcs
    - name: location
      value: gs://christie-catfactory-bucket/README.md
```

With this task spec:

```
    - name: gssecrets
      type: storage
      targetPath: "gitspace/docs/README.md"
```

README.md actually ends up in `<resource name>/README.md/README.md` 🤔
