### ISSUE TITLE
The params in step are passed to `stdoutConfig.path`.

### ISSUE THREAD

**Issue by cugykw** [tektoncd/pipeline#7753]
# Expected Behavior
In my taskrun resource, the params in spec and the params in step 
have a variable with the same name. This can lead to unexpected behavior.

I've provided a simple example.

```
apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: stepaction-demo
spec:
  params:
  - name: path
    type: string
  image: alpine
  workingDir: $(params.path)
  script: |
    env
    pwd
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: step-action-example
spec:
  params:
  - name: path
    value: /home/work
  taskSpec:
    steps:
    - params:
      - name: path
        value: $(params.path)/app/demo
      ref: 
        name: stepaction-demo
      name: demo
      stdoutConfig: 
        path: $(params.path)/log
```

![image](https://github.com/tektoncd/pipeline/assets/19320253/9c53d681-b62a-4f8a-9f61-c4199dfd8a11)

I hope the `stdoutConfig.path` value is '/home/work/log', but got 
'/home/work/app/demo/log'.

The `stdoutConfig` in step should be replaced by params in taskrun, 
but it is replaced by params in step.

# Additional Info

tekton: 0.53.0
