### ISSUE TITLE
[StepAction] taskSpec.results in Pipeline not works with workspaces

### ISSUE THREAD

**Issue by uqix** [tektoncd/pipeline#7754]
# Expected Behavior

`taskSpec.results` in `Pipeline` works with `workspaces` and `StepAction`.

# Actual Behavior

`taskSpec.results` in `Pipeline` not works with `workspaces`.

<img width="1065" alt="image" src="https://github.com/tektoncd/pipeline/assets/10142314/1469c240-49b5-450f-9925-3b38b7167e34">

No results generated.

# Steps to Reproduce the Problem

1. pipeline.yaml

```yaml
apiVersion: tekton.dev/v1
kind: Pipeline

metadata:
  name: build-module-nodejs-frontend-v1-sadev2
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    app.kubernetes.io/version: "1.0.5"

spec:
  workspaces:
    - name: ws

  params:
    - name: value

  tasks:
    - name: main
      workspaces:
        - name: ws
      taskSpec:
        workspaces:
          - name: ws
        results:
          - name: build-ts
            value: $(steps.build-ts.results.value)
        steps:
          - name: build-ts
            ref:
              name: build-ts-v1.2

```

2. stepaction.yaml

```yaml
apiVersion: tekton.dev/v1alpha1
kind: StepAction

metadata:
  name: build-ts-v1.2
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    app.kubernetes.io/version: "1.0.0"

spec:
  results:
    - name: value

  image: bash:5.2.15

  script: |
    #!/usr/bin/env bash

    echo -n "abc" | tee "$(step.results.value.path)"

    # </bash>

```

3. pipelinerun.yaml

``` yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-module-nodejs-frontend-v1-dev2-
  labels:
    tekton/concurrency-group: build-module-nodejs-frontend-v1-dev
    tekton/run-group: build-module-nodejs-frontend-v1-dev

spec:
  workspaces:
    - name: ws
      emptyDir: {}

  pipelineRef:
    name: build-module-nodejs-frontend-v1-sadev2
  params:
    - name: value
      value: yyy

```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:21:34Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:14:09Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.57.0
```

**Comment by uqix** [comment]
It works if `workspaces` commented out:

pipeline.yaml

```yaml
apiVersion: tekton.dev/v1
kind: Pipeline

metadata:
  name: build-module-nodejs-frontend-v1-sadev2
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    app.kubernetes.io/version: "1.0.5"

spec:
  # workspaces:
  #   - name: ws

  params:
    - name: value

  tasks:
    - name: main
      # workspaces:
      #   - name: ws
      taskSpec:
        # workspaces:
        #   - name: ws
        results:
          - name: build-ts
            value: $(steps.build-ts.results.value)
        steps:
          - name: build-ts
            ref:
              name: build-ts-v1.2

```

pipelinerun.yaml

```yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-module-nodejs-frontend-v1-dev2-
  labels:
    tekton/concurrency-group: build-module-nodejs-frontend-v1-dev
    tekton/run-group: build-module-nodejs-frontend-v1-dev

spec:
  # workspaces:
  #   - name: ws
  #     emptyDir: {}

  pipelineRef:
    name: build-module-nodejs-frontend-v1-sadev2
  params:
    - name: value
      value: yyy

```

<img width="1107" alt="image" src="https://github.com/tektoncd/pipeline/assets/10142314/511065a5-7cd6-4a9c-a9fd-28aa41f32801">
