### ISSUE TITLE
TaskRun Fails to Create Pod When ServiceAccount References Non-Existent Secret

### ISSUE THREAD

**Issue by l-qing** [tektoncd/pipeline#7760]
# Expected Behavior

When repairing a ServiceAccount that includes a reference to a non-existent secret, I expect the TaskRun to issue a warning and proceed with the creation of the Pod, similar to Kubernetes’ behavior of handling missing imagePullSecrets within a Pod’s service account configuration.

[Log a warning if a ImagePullSecrets does not exist](https://github.com/kubernetes/kubernetes/pull/117927/files)

# Actual Behavior

Currently, if a ServiceAccount is referenced by a TaskRun and contains a non-existent secret, the TaskRun fails to create the associated Pod and results in an error.

# Steps to Reproduce the Problem

1. Execute the following script:
```
kubectl apply -f - <<EOF
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskrun-sa
secrets:
- name: not-exist
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: test-sa-has-not-found-secret
spec:
  serviceAccountName: taskrun-sa
  taskSpec:
    description: |
      A simple task that prints the date.
    steps:
      - name: echo
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          echo "Hello, world!"
status:
  conditions:
  - message: 'failed to create task run pod "test-sa-has-not-found-secret": translating
      TaskSpec to Pod: secrets "not-exist" not found. Maybe invalid TaskSpec'
    reason: PodCreationFailed
    status: "False"
    type: Succeeded
EOF

```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.35.1
Pipeline version: v0.57.0
```
