### ISSUE TITLE
Unexpected Default ‘kind’ in taskRef When Using Resolver in Tekton Pipelines

### ISSUE THREAD

**Issue by l-qing** [tektoncd/pipeline#7762]
# Expected Behavior

When using a `resolver` to reference a Task in Tekton Pipeline, the taskRef should not automatically have a default `kind` type value set as the `Task` is not applicable in the context of resolvers.

Despite using a resolver to reference a Task, the taskRef still has a default `kind` type value inserted, which appears to be added by the webhook. This addition seems unnecessary and can cause confusion as it modifies the user’s configuration without a clear purpose within resolver usage.

# Actual Behavior

# Steps to Reproduce the Problem

1. Execute the following script
```
kubectl apply -f - <<EOF
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-default-taskref-kind
  namespace: default
spec:
  description: |
    A simple task that prints the date.
  steps:
    - name: echo
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo "Hello, world!"
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: test-default-taskref-kind
spec:
  taskRef:
    resolver: cluster
    params:
      - name: kind
        value: task
      - name: name
        value: test-default-taskref-kind
      - name: namespace
        value: default
EOF
```

2. The `TaskRun`
```
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: test-default-taskref-kind
spec:
  serviceAccountName: default
  taskRef:
    kind: Task                <- This default value is set
    params:
    - name: kind
      value: task
    - name: name
      value: test-default-taskref-kind
    - name: namespace
      value: default
    resolver: cluster
  timeout: 1h0m0s
status:
  taskSpec:
    description: |
      A simple task that prints the date.
    steps:
    - computeResources: {}
      image: bash:latest
      name: echo
      script: |
        #!/usr/bin/env bash
        echo "Hello, world!"

```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.35.1
Pipeline version: v0.57.0
```
