### ISSUE TITLE
Pipeline fails with default array params when type is not specified in remote resource

### ISSUE THREAD

**Issue by l-qing** [tektoncd/pipeline#7775]
# Expected Behavior

When defining default parameters within a remote resource, if the default value is an array, the pipeline should accept the default array value and proceed with execution without any issues, even if the parameter type is not explicitly set.

# Actual Behavior

If a param in the remote resource definition does not have the type specified and the default value given is an array, the pipeline execution fails.

# Steps to Reproduce the Problem

1. Execute the following script:
```
kubectl apply -f - <<EOF
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: mock-task-run
spec:
  taskRef:
    resolver: http
    params:
      - name: url
        value: https://raw.githubusercontent.com/l-qing/catalog/chore/test-array-params-in-resolver/task/test-array-params-in-resolver.yaml
  params:
    - name: tags
      value:
        - latest
        - v1
        - v2

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: mock-pipeline-run
spec:
  pipelineRef:
    resolver: http
    params:
      - name: url
        value: https://raw.githubusercontent.com/l-qing/catalog/chore/test-array-params-in-resolver/pipeline/test-array-params-in-resolver.yaml
  params:
    - name: tags
      value:
        - latest
        - v1
        - v2
EOF
```

2. Task definition
```
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: mock-task
spec:
  params:
    - name: tags
      # type: array         <- The type is not set
      default:
        - latest
        - v1
        - v2

  steps:
    - image: ubuntu
      name: mock
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 50m
          memory: 50Mi
      args:
        - --tags
        - $(params.tags[*])
      script: |
        #!/bin/bash

        tags=()
        parsing_flag=""
        echo "args are $@"
        for arg in "$@"; do
            # flag keys
            if [ "$arg" == "--tags" ]; then
                echo "-> Parsing tags variables..."
                parsing_flag="tags"
            # flag values
            elif [ "$parsing_flag" == "tags" ] && [ "$arg" != "" ]; then
                tags+=("$arg")
            fi
        done
        echo "tags are ${tags[@]}"
```

3. Pipeline definition
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mock-pipeline
spec:
  params:
    - name: tags
      default:
        - pr-latest
  tasks:
    - name: task-1
      taskRef:
        resolver: http
        params:
          - name: url
            value: https://raw.githubusercontent.com/l-qing/catalog/chore/test-array-params-in-resolver/task/test-array-params-in-resolver.yaml
    - name: task-2
      taskRef:
        resolver: http
        params:
          - name: url
            value: https://raw.githubusercontent.com/l-qing/catalog/chore/test-array-params-in-resolver/task/test-array-params-in-resolver.yaml
      params:
        - name: tags
          value: $(params.tags[*])
```

4. TaskRun Results
```
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
status:
  completionTime: "2024-03-19T06:49:36Z"
  conditions:
  - lastTransitionTime: "2024-03-19T06:49:36Z"
    message: 'validation failed for referenced object mock-task: admission webhook
      "validation.webhook.pipeline.tekton.dev" denied the request: validation failed:
      "string" type does not match default value''s type: "array": spec.params.tags.default.type,
      spec.params.tags.type'
    reason: TaskValidationFailed
    status: "False"
    type: Succeeded
```

5. PipelineRun Results
```
apiVersion: tekton.dev/v1
kind: PipelineRun
status:
  completionTime: "2024-03-19T06:49:36Z"
  conditions:
  - lastTransitionTime: "2024-03-19T06:49:36Z"
    message: '[User error] Pipeline /mock-pipeline can''t be Run; it has an invalid
      spec: "string" type does not match default value''s type: "array": finally.params.tags.default.type,
      finally.params.tags.type, tasks.params.tags.default.type, tasks.params.tags.type'
    reason: PipelineValidationFailed
    status: "False"
    type: Succeeded
  pipelineSpec:
    params:
    - default:
      - pr-latest
      name: tags
      type: string
    tasks:
    - name: task-1
      taskRef:
        kind: Task
        params:
        - name: url
          value: https://raw.githubusercontent.com/l-qing/catalog/chore/test-array-params-in-resolver/task/test-array-params-in-resolver.yaml
        resolver: http
    - name: task-2
      params:
      - name: tags
        value: $(params.tags[*])
      taskRef:
        kind: Task
        params:
        - name: url
          value: https://raw.githubusercontent.com/l-qing/catalog/chore/test-array-params-in-resolver/task/test-array-params-in-resolver.yaml
        resolver: http
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.35.1
Pipeline version: v0.56.2
```
