### ISSUE TITLE
Workingdir does not give write access to the group

### ISSUE THREAD

**Issue by urvi-p** [tektoncd/pipeline#7804]
# Expected Behavior
Workingdir should be created with write access for the group. 
Images with the user as nonroot should be able to run commands that require write access in the workingdir.

# Actual Behavior
Workingdir is created with no write access for the group, even though the group has write access for the workspace itself. 
(For images with a nonroot user) Running a command like `mkdir` in the workingdir will return a `Permission denied` error.

# Steps to Reproduce the Problem

1. TaskRun
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: workingdir-example
spec:
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: output
      emptyDir: {}
  params:
    - name: subDirectory
      value: /testDir/
  taskSpec:
    steps:
      - name: run-command
        image: urvip/workingdir-example:latest
        workingdir: $(workspaces.output.path)/$(params.subDirectory)
        script: |
          #!/bin/sh
          set -eu

          ls -l ../
          ls -l ../../
```
2. Output
```
total 4
drwxr-sr-x 2 root nonroot 4096 Mar 25 16:04 testDir
total 4
drwxrwsrwx 3 root nonroot 4096 Mar 25 16:04 output
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.28.7
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3-gke.1286000
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.32.0
Pipeline version: v0.52.0
```
