### ISSUE TITLE
"TaskRun's declared resources didn't match usage in Task"

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/pipeline#786]
# Expected Behavior

I can create a `TaskRun` that pulls source from Google Cloud Storage, entirely specified in one 
resource, without having to create a `Task`, `Resource` and `TaskRun` separately.

This is the YAML I'm trying to create:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: fails
spec:
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: storage
        params:
        - name: location
          value: gs://my-bucket/my-object.tar#1490884291512041
        - name: artifactType
          value: bucket
        - name: type
          value: build-gcs
  taskSpec:
    steps:
    - image: gcr.io/kaniko-project/executor
      command:
      - --context=/workspace
      - --dockerfile=Dockerfile
```

# Actual Behavior

That taskrun fails with:

```
status:
  conditions:
  - lastTransitionTime: "2019-04-23T20:55:36Z"
    message: 'invalid input resources: TaskRun''s declared resources didn''t match
      usage in Task: Provided extra values: [source]'
    reason: TaskRunValidationFailed
    status: "False"
    type: Succeeded
```

# Additional Info

If I remove the `name: source` from my `resourceSpec` it fails with `Provided extra values: []`.

It sounds like it's telling me I have to use that name somewhere else in my taskrun spec? But, where?

Let me know if this is just wrong for some reason, or is purposefully impossible. I'm trying to replicate some Knative Build workflows to write a migration guide. Knative Builds allow users to specify all the information needed to run in one resource, but they're also a lot less flexible, so 🤷‍♂️

Since I might be the ~only person interested in one-shot taskruns like this, I'd be happy to write some e2e tests that check that this keeps working, once I get something that works.

Also worth noting that this is not caught by the webhook admission controller, so the taskrun exists and is just immediately updated to `Failure` -- if this is actually invalid for some reason it'd be nice if it was just rejected upfront.

/cc @shashwathi since I think this was code you originally wrote, and you might have pointers.

**Comment by ImJasonH** [comment]
Shash pointed out I need to specify the task input 

https://github.com/tektoncd/pipeline/blob/master/examples/taskruns/gcs-resource-spec-taskrun.yaml

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: list-file
spec:
  taskSpec:
   inputs:
    resources:
    - name: workspace  # <-- here
      type: storage
    steps:
    - name: list
      image: ubuntu
      command: ["/bin/bash"]
      args: ['-c', 'ls -al /workspace/rules/rules_docker-master'] # tests build-gcs resource
  trigger:
    type: manual
  inputs:
    resources:
    - name: workspace  # <-- and here
      resourceSpec:
        type: storage
        params:
          - name: location
            value: gs://build-crd-tests/rules_docker-master.zip
          - name: artifactType
            value: Archive
          - name: type
            value: build-gcs
```

So this is WAI, and I just need to make sure to remember/document that for any Knative Build migrators.

The benefit is that you can skip defining the resource twice if you're going to reuse it in multiple task(run)s.
