### ISSUE TITLE
Allow param substitution in StepAction Reference Resolver Params

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/pipeline#7865]
Today, we allow param substitution in `TaskRef`'s and `PipelineRef`'s Resolver `params`. However, we do not allow this for Resolver params when referencing `StepActions`. This was not intended and we should allow the substitution so that it is harmonious across remote resolution for all resources.

# Expected Behavior
```yaml
status:
  completionTime: "2024-04-09T15:47:37Z"
  conditions:
  - lastTransitionTime: "2024-04-09T15:47:37Z"
    message: All Steps have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
  podName: step-action-run-6z8ck-pod
  provenance:
    featureFlags:
      EnableStepActions: true
      ...
  startTime: "2024-04-09T15:47:31Z"
  steps:
  - container: step-action-runner
    imageID: docker.io/library/alpine@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b
    name: action-runner
    terminated:
      containerID: containerd://b07c561cf5d0a1a01b10b7363c5acccb800893495bf00ce3655551ab17d86c99
      exitCode: 0
      finishedAt: "2024-04-09T15:47:37Z"
      reason: Completed
      startedAt: "2024-04-09T15:47:37Z"
    terminationReason: Completed
  taskSpec:
    steps:
    - computeResources: {}
      image: alpine
      name: action-runner
      script: |
        echo hi
```
# Actual Behavior

```yaml
status:
  completionTime: "2024-04-09T15:44:19Z"
  conditions:
  - lastTransitionTime: "2024-04-09T15:44:19Z"
    message: 'error requesting remote resource: invalid resource request "default/git-cd7426fc92f974ec9865eb272dbce63f":
      invalid git repository url: $(params.repoUrl)'
    reason: TaskRunResolutionFailed
    status: "False"
    type: Succeeded
  podName: ""
  provenance:
    featureFlags:
      EnableStepActions: true
      ...
  startTime: "2024-04-09T15:44:19Z"
  taskSpec:
    steps:
    - computeResources: {}
      name: action-runner
      ref:
        params:
        - name: url
          value: $(params.repoUrl)
        - name: revision
          value: $(params.revision)
        - name: pathInRepo
          value: $(params.pathInRepo)
        resolver: git
```
# Steps to Reproduce the Problem

1. Enable StepActions
2. Execute the following yaml
```yaml
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: step-action-run-
spec:
  params:
    - name: repoUrl
      value: https://github.com/chitrangpatel/repo1M.git
    - name: revision
      value: main
    - name: pathInRepo
      value: basic_step.yaml
  TaskSpec:
    steps:
      - name: action-runner
        ref:
          resolver: git
          params:
            - name: url
              value: $(params.repoUrl)
            - name: revision
              value: $(params.revision)
            - name: pathInRepo
              value: $(params.pathInRepo)
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.8-gke.1067004", GitCommit:"6f460c12ad45abb234c18ec4f0ea335a1203c415", GitTreeState:"clean", BuildDate:"2024-01-04T22:48:32Z", GoVersion:"go1.20.11 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
0.56.0
```
