### ISSUE TITLE
Allow unused taskRunSpec pipelineTaskName

### ISSUE THREAD

**Issue by jimmyjones2** [tektoncd/pipeline#7929]
### Feature request

Currently a Task matching `pipelineTaskName` specified as part of `taskRunSpecs` must exist in the Pipeline (although no explicitly [documented](https://tekton.dev/docs/pipelines/pipelineruns/#specifying-taskrunspecs)), otherwise the PipelineRun will fail:

```
spec:
  taskRunSpecs:
    - pipelineTaskName: build-task
      serviceAccountName: sa-for-build
```

However in some cases, similar to those described in #2513 and #6856, it's useful for this to be permitted, as unused parameters and workspaces are today. Changing the default behaviour would be non-breaking (although possibly slightly surprising if people were relying on the behaviour). Alternatively, an extra boolean field `optional` could be added (similar to mounting [optional Secrets as volumes](https://kubernetes.io/docs/concepts/configuration/secret/#restriction-secret-must-exist)), defaulted to `false`. Maybe this behaviour should be extended to workspaces and parameters too, so users can choose the behaviour?

```
spec:
  taskRunSpecs:
    - pipelineTaskName: build-task
      optional: true
      serviceAccountName: sa-for-build
```

### Use case

Quoting #2513 as a similar use case:
> Imagine you have a system creating PipelineRuns automatically, and each PipelineRun uses a different Pipeline which has a different set of parameters. The system has a number of parameters it knows how to provide, e.g. the service account and url of a bucket the Pipelines can push to (but not all Pipelines need to push to a bucket).
>
> It would be very convenient if the system creating the PipelineRuns could provide all the parameters it has available to all PipelineRuns, and the Pipelines could use the ones they need and ignore the rest.
