### ISSUE TITLE
How to Use the microservice as deployment using Tekton pipeline

### ISSUE THREAD

**Issue by tppalani** [tektoncd/pipeline#7959]
# Expected Behavior

# Actual Behavior

I have single micro services (shopfront) right now which has java app inside the java app source code main folder i have folder name called kubernetes which has deployment yaml respective to shopfront micro services. please find the below task which pipeline will perform, its working as expected. please refer the pipeline.yaml and maven-task.yaml

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: shopfront
  namespace: docker-kubernetes-java-project
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: maven-local-m2
  params:
    - name: url
    - name: revision
      default: docker-kubernetes-java-project
    - name: subdirectory
    - name: builder-image
    - name: dockerfile
    - name: app-image
    - name: app-tag
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://my-repo.git
        - name: subdirectory
          value: source
        - name: revision
          value: docker-kubernetes-java-project
        - name: flags
          value: --insecure
        - name: deleteExisting
          value: "true"
    - name: bash
      workspaces:
        - name: shared-workspace
      taskRef:
        name: bash
      runAfter:
        - fetch-repository
    - name: maven-run
      taskRef:
        name: maven
      runAfter:
        - bash
      params:
        - name: CONTEXT_DIR
          value: "source/shopfront"
        - name: image
          value: build
        - name: insecure_registry
          value: registry.default.svc.cluster.local:5000
        - name: GOALS
          value:
            - -DskipTests
            - clean
            - install
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: shared-workspace
          workspace: shared-workspace
        - name: maven-local-repo
          workspace: maven-local-m2
```

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven
  namespace: docker-kubernetes-java-project
  # labels:
  #   app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Image Build
    tekton.dev/tags: docker, build-image, push-image, dind
    tekton.dev/displayName: maven
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
   This Task can be used to run a Maven build. It uses a workspace to store m2 local repo.
  workspaces:
    - name: shared-workspace
      description: The workspace consisting of maven project.
    - name: maven-settings
      description: >-
        The workspace consisting of the custom maven settings
        provided by the user.
    - name: maven-local-repo
      description: Local repo (m2) workspace
      optional: true
  params:
    - name: image
      description: Reference of the image docker will produce.
    - name: builder_image # 
      description: The location of the docker builder image.
      default: builder_image
    - name: dind_image
      description: The location of the docker-in-docker image.
      default: docker-in-docker
    - name: push_image
      description: The location of the docker push image
      default: docker-in-docker
    - name: dockerfile
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: context
      description: Path to the directory to use as context.
      default: .
    - name: build_extra_args
      description: Extra parameters passed for the build command when building images.
      default: ""
    - name: push_extra_args
      description: Extra parameters passed for the push command when pushing images.
      default: ""
    - name: insecure_registry
      description: Allows the user to push to an insecure registry that has been specified
      default: ""
  
    - name: MAVEN_IMAGE
      type: string
      description: Maven base image
      default: gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641 #tag: latest
    - name: GOALS
      description: maven goals to run
      type: array
      default:
          - "package"
    - name: MAVEN_MIRROR_URL
      description: The Maven repository mirror url
      type: string
      default: ""
    - name: SERVER_USER
      description: The username for the server
      type: string
      default: ""
    - name: SERVER_PASSWORD
      description: The password for the server
      type: string
      default: ""
    - name: PROXY_USER
      description: The username for the proxy server
      type: string
      default: ""
    - name: PROXY_PASSWORD
      description: The password for the proxy server
      type: string
      default: ""
    - name: PROXY_PORT
      description: Port number for the proxy server
      type: string
      default: ""
    - name: PROXY_HOST
      description: Proxy server Host
      type: string
      default: ""
    - name: PROXY_NON_PROXY_HOSTS
      description: Non proxy server host
      type: string
      default: ""
    - name: PROXY_PROTOCOL
      description: Protocol for the proxy ie http or https
      type: string
      default: "http"
    - name: CONTEXT_DIR
      type: string
      description: >-
        The context directory within the repository for sources on
        which we want to execute maven goals.
      default: ""
  steps:
    - name: mvn-settings
      image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
      script: |
        #!/usr/bin/env bash

        [[ -f $(workspaces.maven-settings.path)/settings.xml ]] && \
        echo "using existing $(workspaces.maven-settings.path)/settings.xml" && exit 0

        cat > "$(workspaces.maven-settings.path)/settings.xml" <<EOF
        <settings>
          <servers>
            <!-- The servers added here are generated from environment variables. Don't change. -->
            <!-- ### SERVER's USER INFO from ENV ### -->
          </servers>
          <mirrors>
            <!-- The mirrors added here are generated from environment variables. Don't change. -->
            <!-- ### mirrors from ENV ### -->
          </mirrors>
          <proxies>
            <!-- The proxies added here are generated from environment variables. Don't change. -->
            <!-- ### HTTP proxy from ENV ### -->
          </proxies>
        </settings>
        EOF

        xml=""
        if [ -n "$(params.PROXY_HOST)" ] && [ -n "$(params.PROXY_PORT)" ]; then
          xml="<proxy>\
            <id>genproxy</id>\
            <active>true</active>\
            <protocol>$(params.PROXY_PROTOCOL)</protocol>\
            <host>$(params.PROXY_HOST)</host>\
            <port>$(params.PROXY_PORT)</port>"
          if [ -n "$(params.PROXY_USER)" ] && [ -n "$(params.PROXY_PASSWORD)" ]; then
            xml="$xml\
                <username>$(params.PROXY_USER)</username>\
                <password>$(params.PROXY_PASSWORD)</password>"
          fi
          if [ -n "$(params.PROXY_NON_PROXY_HOSTS)" ]; then
            xml="$xml\
                <nonProxyHosts>$(params.PROXY_NON_PROXY_HOSTS)</nonProxyHosts>"
          fi
          xml="$xml\
              </proxy>"
          sed -i "s|<!-- ### HTTP proxy from ENV ### -->|$xml|" "$(workspaces.maven-settings.path)/settings.xml"
        fi

        if [ -n "$(params.SERVER_USER)" ] && [ -n "$(params.SERVER_PASSWORD)" ]; then
          xml="<server>\
            <id>serverid</id>"
          xml="$xml\
                <username>$(params.SERVER_USER)</username>\
                <password>$(params.SERVER_PASSWORD)</password>"
          xml="$xml\
              </server>"
          sed -i "s|<!-- ### SERVER's USER INFO from ENV ### -->|$xml|" "$(workspaces.maven-settings.path)/settings.xml"
        fi

        if [ -n "$(params.MAVEN_MIRROR_URL)" ]; then
          xml="    <mirror>\
            <id>mirror.default</id>\
            <url>$(params.MAVEN_MIRROR_URL)</url>\
            <mirrorOf>central</mirrorOf>\
          </mirror>"
          sed -i "s|<!-- ### mirrors from ENV ### -->|$xml|" "$(workspaces.maven-settings.path)/settings.xml"
        fi
    - name: mvn-goals
      image: $(params.MAVEN_IMAGE)
      workingDir: /workspace/shared-workspace/$(params.CONTEXT_DIR)
      command: ["/usr/bin/mvn"]
      args:
        - -s
        - $(workspaces.maven-settings.path)/settings.xml
        - "$(params.GOALS)"
        - '-Dmaven.repo.local=$(workspaces.maven-local-repo.path)/.m2'

    - name: docker-build
      image: $(params.builder_image)
      workingDir: $(workspaces.shared-workspace.path)/source/shopfront
      env:
      # Connect to the sidecar over TCP, with TLS.
      - name: DOCKER_HOST
        value: tcp://localhost:2376
      # Verify TLS.
      - name: DOCKER_TLS_VERIFY
        value: '1'
      # Use the certs generated by the sidecar daemon.
      - name: DOCKER_CERT_PATH
        value: /certs/client
      volumeMounts:
        - mountPath: /certs/client
          name: dind-certs
      script: |
        docker images
        docker build \
          $(params.build_extra_args) \
          --no-cache \
          -f $(params.dockerfile) -t $(params.image) $(params.context)
        docker images

    - name: docker-push
      image: $(params.builder_image)
      env:
      # Connect to the sidecar over TCP, with TLS.
      - name: DOCKER_HOST
        value: tcp://localhost:2376
      # Verify TLS.
      - name: DOCKER_TLS_VERIFY
        value: '1'
      # Use the certs generated by the sidecar daemon.
      - name: DOCKER_CERT_PATH
        value: /certs/client
      workingDir: $(workspaces.shared-workspace.path)/shared-workspace
      script: |
        docker push $(params.push_extra_args) $(params.image)
      volumeMounts:
        - mountPath: /certs/client
          name: dind-certs
      volumeMounts:
        - mountPath: /certs/client
          name: dind-certs
  volumes:
  - name: config-volume
    configMap:
    name: ca-pemstore
  sidecars:
  - image: $(params.dind_image)
    name: server
    args:
      - --storage-driver=vfs
      - --userland-proxy=false
      - --debug
      - --insecure-registry=$(params.insecure_registry)
    securityContext:
      privileged: true
    env:
    # Write generated certs to the path shared with the client.
    - name: DOCKER_TLS_CERTDIR
      value: /certs
    volumeMounts:
    - mountPath: /certs/client
      name: dind-certs
    # Wait for the dind daemon to generate the certs it will share with the
    # client.
    readinessProbe:
      periodSeconds: 1
      exec:
        command: ['ls', '/certs/client/ca.pem']
  volumes:
  - name: dind-certs
    emptyDir: {}
```

1. git clone
2. mvn goals
3. docker build
4. docker push
5. deploy to k8s environment

# Steps to Reproduce the Problem

Now i want to add another micro service in the same pipeline using single maven task using if else condition for example please refer above actual code which has single mvn goal path when the mvn-goals will perform mvn build if the working directory if params will match from pipeline.yaml context DIR value: "source/shopfront" now i want add another path  context DIR value: "source/productcatalog" 

if the path is equal to source/shopfront build should be happen from specific location if the path is equal to source/productcatalog build should be happen respective location.

Will this possible ?
