### ISSUE TITLE
Pipelines ignoring following name fields on resolvers

### ISSUE THREAD

**Issue by Aleromerog** [tektoncd/pipeline#7980]
# Expected Behavior
Have multiple different resources resolved from a specific resolver using name field and concise remote syntax.
# Actual Behavior
Following StepActions/Task/Pipeline are ignored and the first declared name is being passed to the following resources.

# Steps to Reproduce the Problem
execute a TaskRun with the following:
```
steps:
      - name: step-1
        ref:
          resolver: some-resolver
          name: scheme://<path>/step-1
        params:
          - name: param1
            value: value1
          - name: param2
            value: value2
     - name: step-2
        ref:
          resolver: some-resolver
          name: scheme://<path>/step-2
        params:
          - name: param3
            value: value3
          - name: param4
            value: value4
```

Resulting in 
```
extra params passed by Step to StepAction: [params3 params4]
```
Even though `step-2` supports those parameters. Which means that is trying to apply `params3` and `params4` as if it was using `step-1`.

# Additional Info
## Proposed solution

change `GetNameAndNamespace` in  `pkg/resolution/resource/name.go` to accept `*v1beta1.ResolutionRequestSpec` parameter instead of just params
```
func GetNameAndNamespace(resolverName string, owner kmeta.OwnerRefable, name string, namespace string, req *v1beta1.ResolutionRequestSpec) (string, string, error) { ... }
```
