### ISSUE TITLE
Invalid Validation of StepTemplate with StepAction Ref

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/pipeline#7981]
# Expected Behavior
When using `StepTemplates` in `Steps` referencing `StepActions`, there shouldn't be a validation error if the StepTemplate uses fields that conflict with StepActions (e.g. `env`)

e.g. The following should work be passed by the validation web hook. After the StepAction is fetched, it should naturally be merged with the underlying StepTemplate. 

```yamlapiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: task-run
spec:
  taskSpec:
    steps:
      - ref:
          name: step-action
    stepTemplate:
      env:
        - name: foo
          value: bar
---
apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: step-action
spec:
  image: ubuntu
  command: ["env"]
```
# Actual Behavior

A web hook validation error is thrown that `env` cannot be used with `ref`. This is wrong since the user did not explicitly provide the `env` with the `ref` field in the `Step`. The purpose of `StepTemplate` is to add values to Steps. This should only happen after the `StepAction` is fetched and inlined.

# Steps to Reproduce the Problem

1. Run the above yaml `kubectl apply -f <above yaml>`
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.12-gke.1115000", GitCommit:"885327b7f1bebce409c843425b4688e3eeed33f4", GitTreeState:"clean", BuildDate:"2024-03-28T09:16:53Z", GoVersion:"go1.21.8 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.34.0
Chains version: v0.21.0
Pipeline version: v0.60.0
```
