### ISSUE TITLE
Too Strict validation of the Resolver Name during Webhook Validation

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/pipeline#7986]
# Expected Behavior

After implementation of Stage 1 of TEP-0154 (concise resolver syntax), Users should be able to pass anything that looks like:
`<scheme>://...` as input.

e.g. Something like 

```yaml
kind: Pipeline
spec:
  tasks:
    - name: t1
       taskRef:
          name: <custom-scheme>://<location>:<version>
          resolver: custom-resolver
```
 should work.

# Actual Behavior

The above example runs into a web hook validation where the validation is unintentionally too strict and treats `version` as a port.

# Fix

Update the validation logic to be regex based so that it just leaves the validation to `<some-scheme>://` and does not worry about the rest. This was the [intent](https://github.com/tektoncd/community/blob/main/teps/0154-concise-remote-resolver-syntax.md#resolver-reference) of the TEP all along. The validation of the remaining string was at the discretion of the resolvers. 

<img width="1024" alt="Screenshot 2024-05-24 at 3 13 13 PM" src="https://github.com/tektoncd/pipeline/assets/11685590/0eeaf60a-3888-4b53-96f2-a86444fdd136">

The current validation logic was accidentally implemented as too strict.
