### ISSUE TITLE
Increase Task Reuse

### ISSUE THREAD

**Issue by BoyChai** [tektoncd/pipeline#7988]
### Feature request

It would be beneficial to introduce a 'TaskRef' option in the creation of a Task to facilitate the reuse of certain features of a Task where the variations may simply be one parameter, to avoid the complexity of repeatedly inputting parameters. For instance, in sending notifications, most of the server information may remain the same and the only difference would typically be the message content. Entering these parameters for every task creation is cumbersome. Of course, one can create a task with fixed values and then invoke this Task, but this approach may be too complicated for beginners. Additionally, if some tasks are installed from hub.tekton.dev, altering their YAML configurations could also necessitate an understanding of their internal purposes, thus involving a learning cost.

### Use case
I hope
```yaml
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: notice-host-1
spec:
  params:
    - name: server
      value: host.com
    - name: port
      value: 8080
    - name: token
      value: "xxxxxxxxxxxxxxxxxxxxxx"
    - name: msg
  taskRef:
    name: notice
```
