### ISSUE TITLE
Missing substitution of propagated workspace in WorkingDirs

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/pipeline#8008]
# Expected Behavior
```
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ws-1
spec:
  workspaces:
  - name: "default-workspace"
    volumeClaimTemplate:
      spec:
        accessModes:
         - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  pipelineSpec:
    tasks:
    - name: "write-sth"
      taskSpec:
        steps:
          - image: "ubuntu"
            script: |
              #!/bin/bash
              cd "$(workspaces.default-workspace.path)"
              mkdir -p backend/app
              ls -tlr
    - name: "get-it"
      taskSpec:
        steps:
          - image: "ubuntu"
            workingDir: $(workspaces.default-workspace.path)/backend/app
            script: |
              pwd
              echo done
```

The abovePipelineRun should run well and replace `$(workspaces.default-workspace.path)` with `/workspace/default-workspace` in the `workingDir` of the step because of workspace propagation. 

# Actual Behavior
The substitution is not applied and the container fails with the error message that `the workingDir must be an absolute path`. However, the same works in a Taskrun.

# Steps to Reproduce the Problem

1. Execute the above pipelinerun in any of the recent Tekton Pipelines releases.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
(paste your output here)
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
(paste your output here)
```
