### ISSUE TITLE
The pipeline controller keeps refreshing logs

### ISSUE THREAD

**Issue by cugykw** [tektoncd/pipeline#8055]
When we were troubleshooting a problem, we needed to check the pipeline controller logs and found that the logs were constantly refreshing and could not be viewed. 

Finally, we found that there were several pipelines that were still executing the finale task, which caused the problem of constantly refreshing the logs.

These pipelines set the same `pipeline` and `tasks` timeouts.

# Expected Behavior
The pipeline controller will not flush logs repeatedly.

I've provided a simple example.

```
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: example
spec:
  pipelineSpec:
    finally:
     - name: example-01
       taskSpec:
         steps:
         - image: alpine
           name: final-task
           script: sleep 1h
    tasks:
     - name: example-00
       taskSpec:
         steps:
         - image: alpine
           name: task
           script: echo "hello"
  timeouts:
    pipeline: 1h0m0s
    tasks: 1h0m0s
```

We can observe that the pipeline controller is constantly refreshing logs.

# Additional Info

tekton: 0.53.0
