### ISSUE TITLE
When using ${variable} in containerTemplate, it is not working

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/pipeline#811]
# Expected Behavior

Templating in containerTemplate should work.

# Actual Behavior

Templating in containerTemplate is not working.

# Steps to Reproduce the Problem

1. Create a Cluster resource.
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cluster-details
spec:
  type: cluster
  params:
  - name: url
    value: " "
  - name: name
    value: " "
  - name: username
    value: " "
  - name: token
    value: " "
  - name: cadata
    value: " "
```
2. Create a task using cluster resource.
```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-openshift-command-clusterresource
spec:
  containerTemplate:
    env:
      - name: "KUBECONFIG"
        value: "/workspace/${inputs.resources.clusterdetails.name}/kubeconfig"
  inputs:
    resources:
      - name: clusterdetails
        type: cluster
  steps:
    - name: foo
      image: ubuntu
      command:
        - /bin/bash
      args: ["-c", "env"]
```
3. Create task run for the task
```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: task-run-openshift-command-clusterresource
spec:
  taskRef:
    name: task-openshift-command-clusterresource
  inputs:
    resources:
      - name: clusterdetails
        resourceRef:
          name: cluster-details
```
4. Check the logs of the step, it will show something like
```
oc logs task-run-openshift-command-clusterresource-pod-4645e9 -c build-step-foo
KUBECONFIG=/workspace/${inputs.resources.clusterdetails.name}/kubeconfig
```
# Additional Info

Tekton version v0.3.1
