### ISSUE TITLE
New tkn not working with old pipeline release

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/pipeline#8225]
# Expected Behavior

tkn client with vendor 0.62, not working with 0.61 release

# Actual Behavior

tkn client should work fine.

# Steps to Reproduce the Problem

1. Install Pipeline Release 0.61.x
2. Create Task
```
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: echo-task
spec:
  steps:
  - image: mirror.gcr.io/ubuntu
    script: echo hello
```
3. Install tkn client 0.38.0
4. Do `tkn task start echo-task` and you will error like
```
Error: admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "artifacts"
```

# Additional Info

- Kubernetes version:

```
1.30
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
0.61
```

Can we add new field in spec such that empty json does not get added.

CLI reported issue https://github.com/tektoncd/cli/issues/2388 

cc @vdemeester
