### ISSUE TITLE
Task validation ignores containerTemplate

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/pipeline#824]
When validating a Task before creation, it should take the attributes from `containerTemplate` into account. Defining an `image` attribute on `containerTemplate` but not on the `steps` should pass the validation but right now fails with:

```
Error from server (InternalError): error when creating "tasks/buildah-task.yml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: missing field(s): steps.Image
```

Example task:
```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: buildah
spec:
  inputs:
    resources:
    - name: workspace-git
      targetPath: /
      type: git
    params:
    - name: dockerfile
      description: The path to the dockerfile to build
      default: ./Dockerfile
    - name: verifyTLS
      description: Verify registry certificates
      default: "true"
  outputs:
    resources:
    - name: image
      type: image
  containerTemplate:
    image: quay.io/openshift-pipeline/buildah:testing
    command:
      - buildah
    volumeMounts:
    - name: libcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
  steps:
  - name: build
    args: 
      - bud
      - --layers
      - --tls-verify=${inputs.params.verifyTLS}
      - -f
      - ${inputs.params.dockerfile}
      - -t
      - ${outputs.resources.image.url}
      - .
  - name: push
    args: 
      - push
      - --tls-verify=${inputs.params.verifyTLS}
      - ${outputs.resources.image.url}
  volumes:
    - name: libcontainers
      emptyDir: {}
```
