### ISSUE TITLE
 SSL error

### ISSUE THREAD

**Issue by objectiveous** [tektoncd/pipeline#828]
# Expected Behavior

In the context of an enterprise rollout of tekton using github enterprise and an internal docker registry,  I want to know how to configure tekton to work with my systems. 

For example, I need to make something like the following work: 

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: gitssh
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.CORP.com/XX/xx.git
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-ciborg
spec:
  inputs:
    resources:
      - name: workspace
        type: git
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "pass"
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  #generateName: tool-job-
  name: test-run-02
spec:
  serviceAccount: build-bot
  taskRef:
    name: build-ciborg
  inputs:
    resources:
      - name: workspace
        resourceRef:
          name: gitssh


```

# Actual Behavior

The build step git-source-gitssh-7777777 throws an SSL error: 

```SSL certificate problem: self signed certificate in certificate chain```
```
"github.com/tektoncd/pipeline/pkg/git.run
  workspace/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:36
  github.com/tektoncd/pipeline/pkg/git.Fetch
    workspace/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:91
    main.main\n\t/workspace/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:36
    runtime.main
      /usr/local/go/src/runtime/proc.go:200
```
I'd like to know how a human operator is expected to configure tekton. 

# Steps to Reproduce the Problem

# Additional Info
```
{"level":"error",
"ts":1556900217.1834462,
"logger":"fallback-logger",
"caller":"git/git.go:36",
"msg":"Error running git [fetch --depth=1 --recurse-submodules=yes origin master]: exit status 128\nfatal: unable to access 'https://github.CORP.com/XX/xxx.git/': SSL certificate problem: self signed certificate in certificate chain\n",
"stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\t/workspace/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:36\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\t/workspace/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:91\nmain.main\n\t/workspace/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:36\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}
```
