### ISSUE TITLE
The build task pod probabilistic cannot be generated

### ISSUE THREAD

**Issue by fjzcxs** [tektoncd/pipeline#8467]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

Hello, at present, I am using the tekton 0.7.0 version, after running for half a year, I found that when the pod CPU of tekton-pipelines-controller reaches 70% and the memory reaches more than 50%, there will be a situation where the pod of the build task cannot be generated, and it is a probabilistic problem, and it is not completely impossible to generate the build task, the service will return to normal after the pod of the controller is restarted, and it is initially suspected that it is a problem of coroutine leakage, I guess you should have fixed this problem.,I want to know what the root cause of this problem is.,Please let me know.,Thank you.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.29.1
Server Version: v1.24.6-aliyun.1
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
This label is not visible in the pod's labels for the time being
  labels:
    app: tekton-pipelines-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: tekton-pipelines
    pod-template-hash: 6fdbdf4d45
```
