### ISSUE TITLE
Settle mismatch between k8s approach to templating + Tekton approach

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#850]
# Expected Behavior

Kubernetes was intentionally designed to not provide templating capabilities because templating makes configuration harder to understand and reason about ([see this Kubernetes design proposal for more details](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/declarative-application-management.md#configuration-using-rest-api-resource-specifications)).

Plus providing “templating” functionality implies the possibility of [significant additional functionality](https://en.wikipedia.org/wiki/Template_processor#Typical_features) beyond just variable replacement, which we want to avoid adding at the level of Tekton types. 

# Actual Behavior

Tekton Pipelines currently provides a variety of templating for [Tasks and Pipelines](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#templating), and has plans to expand the scope (for [step images](https://github.com/tektoncd/pipeline/issues/639), for [paths to mounted PipelineResources](https://github.com/tektoncd/pipeline/issues/626)). The reason for this is to provide a way for a Task’s contextual information to be used when defining the Task.

For example:

```yaml
- image: gcr.io/example-builders/build-example
  command: ["echo"]
  args: ["${inputs.resources.params.pathToDockerFile}"]
```
In templating you can use values from:
* Attributes of input and output resources
* Params

You can apply these to:
* Step arguments
* Names of volumes and volumeMounts

# Additional Info

The most promising solution so far is  to make this experience better align with [the k8s syntax](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#use-environment-variables-to-define-arguments), which requires defining environment variables for every value that can be “templated”.

In this solution we could inject the environment variables for all exportable values and users could use the `$()` syntax to access the values, e.g.:

```yaml
    - image: gcr.io/example-builders/build-example
      command: ["echo"]
      args: ["$(inputs_resources_params_pathtodockerfile)"]
```

As an added “bonus”, users could also use this syntax to template with any of their own defined environment variables also.

[See this design doc for more details and alternative proposals](https://docs.google.com/document/d/1h_3vSApIsuiwGkrqSiegi4NVaYG4oVzBquGAhIN6qGM/edit#)
