### ISSUE TITLE
Dependabot for *active* release branches

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#8572]
We are using `dependabot` on the `main` branch to track dependencies update *and* bugfixes.
We should aim to also configure it for *active* release branches (`release-v*`) for bugfixes only most likely.

It seems like it should be doable according to the [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependabot-prs#targeting-pull-requests-against-a-non-default-branch). 

It might make the configuration verbose. If that's the case, we can look into generating it.

**Comment by Apoorvgarg-creator** [comment]
Hi,
I would like to work on the issue.

**Comment by vdemeester** [comment]
Adding some specifics to make this easier to pick up.

## File to edit

[`.github/dependabot.yml`](https://github.com/tektoncd/pipeline/blob/main/.github/dependabot.yml)

## Current active release branches

As of March 2026, the active release branches are:
- `release-v1.10.x`
- `release-v1.9.x`
- `release-v1.7.x`

(Check with `git branch -r | grep "upstream/release-v" | sort -V | tail -5` for the latest list)

## What to do

Add entries in `dependabot.yml` targeting each active release branch. The key is `target-branch`. Example for one branch:

```yaml
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "release-v1.10.x"
    schedule:
      interval: "weekly"  # less aggressive than main's "daily"
    labels:
      - "ok-to-test"
      - "dependencies"
      - "release-note-none"
      - "kind/misc"
    ignore:
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      # For release branches, also ignore minor bumps for most deps (bugfixes/patches only)
    open-pull-requests-limit: 5
```

The config will get verbose with multiple branches × multiple directories. As noted in the issue, if it becomes too large, a generation script in `hack/` could produce it.

## Considerations

- Use `"weekly"` interval for release branches (vs `"daily"` on main) to reduce noise
- Consider `open-pull-requests-limit` to avoid flooding
- Only `patch` version updates make sense for release branches — use `ignore` rules to skip major/minor bumps
- The `tools/` and `test/custom-task-ctrls/` directories from the main config may not need entries for release branches

## How to verify

- Open a PR, check that dependabot picks up the new config (it usually runs within 24h)
- Verify with `dependabot check` if available, or just review the YAML structure matches [GitHub docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch)
