### ISSUE TITLE
Update doc to remove taskSpec as an alternative to pipelineRef in a pipelineRun

### ISSUE THREAD

**Issue by steveodonovan** [tektoncd/pipeline#869]
# Expected Behavior

Documentation [here](https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#syntax) should reflect that a pipelineRun needs a pipelineRef.

# Actual Behavior

Documentation indicates that an alternative to a pipelineRef is to supply a taskSpec which will fail.

# Steps to Reproduce the Problem

1. View documentation [here](https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#syntax) 

# Additional Info

Sample broken pipelineRun

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: refless-pipeline-run-1
spec:
  taskSpec:
    steps:
    - name: test
      image: ubuntu
      command: ["/bin/bash"]
      args: ['-c', 'echo test']
  serviceAccount: 'default'
```
