### ISSUE TITLE
Allow embedding specs in Pipeline and PipelineRun instead of referencing.

### ISSUE THREAD

**Issue by cjwagner** [tektoncd/pipeline#872]
# Expected Behavior
I see that the `TaskRun` spec allow `Task`s and `PipelineResource`s to be embedded into the spec via the `taskSpec` and `resourceSpec` fields. ([Docs](https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#example-with-embedded-specs), [Issue](https://github.com/tektoncd/pipeline/issues/313))  Creating just the `TaskRun` is simpler than creating all the CRDs and avoids the need to clean up ephemeral `Tasks` and `PipelineResources` that are only needed for the individual `TaskRun`. (ref https://github.com/tektoncd/pipeline/issues/544)

It would be great if `PipelineRun`s could expose a similar embedding mechanism so that the `Task`s, `Pipeline`, and `PipelineResource`s could all be embedded into the `PipelineRun` spec. Here is a simple example of what I would expect a fully embedded `PipelineRun` to look like (snipped together from other examples):
```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: do-the-thing
spec:
  resources:
    - name: source-repo
      resourceSpec:
        type: git
        params:
          - name: url
            value: https://github.com/pivotal-nader-ziada/gohelloworld
  pipelineSpec:
    resources:
      - name: source-repo
        type: git
    tasks:
      - name: skaffold-unit-tests
        taskSpec:
          inputs:
            resources:
              - name: workspace
                type: git
          steps:
            - name: build-and-push
              image: gcr.io/kaniko-project/executor
              command:
                - /kaniko/executor
              args:
                - --destination=gcr.io/my-project/gohelloworld
        resources:
          inputs:
            - name: workspace
              resource: source-repo
```
# Additional Info
The context for this is running ProwJobs as Tekton Pipelines.
Prow now has a controller that can run ProwJobs that define a `PipelineRun` spec, but currently the referenced `Pipeline` and `PipelineResource`s must already exist in the cluster. It would be neat if a ProwJob could specify all the needed information in the `PipelineRun` spec instead of having to reference other CRDs that must be separately managed by our automation.
