### ISSUE TITLE
Extend HTTP Resolver spec to support optional hash field

### ISSUE THREAD

**Issue by aThorp96** [tektoncd/pipeline#8759]
### Feature request

Add an optional `hash`, `digest`, or more appropriately named field to the HTTP resolver spec in which a user provides a hash of the content at the URL. If the field is populated, http resolver would enforce that the http response's content hashes to the same value. 

The http resolver could also have a configuration setting to require this field. 

### Use case

As a security-minded Tekton user, I prefer using resolvers which have some security guarantees. The git resolver provides guarantees via git hashes and the bundles resolver provides similar guarantees via the bundle digest. However in some cases the http resolver is necessary, but as of right now there are no mechanisms to guarantee the content received from the http request is the content I expect. Further, in order to better secure the pipelines I would like to enforce that anyone authoring pipelineruns in my cluster are using secure practices.

**Comment by aThorp96** [comment]
CC @lcarva

**Comment by afrittoli** [comment]
@aThorp96 Thanks! Shall we mark this as "help wanted" or is this something you're going to work on yourself?

**Comment by aThorp96** [comment]
@afrittoli I may work on this in the next few months but it could be a little bit before I can get around to it. No objection to the `help wanted` label

**Comment by zakisk** [comment]
can someone please assign it to me? I wanna work on it.

**Comment by aThorp96** [comment]
@lcarva @arewm From Tekton Chains and SLSA perspectice, what would be an acceptable hashing algorithm here? Would sha1 or sha256 suffice, or it there another best-practice hashing algorithm to use?

I'm wondering too if the algorithm should be the field name as well, instead of an ambiguous name like `hash`. For example if sha256 is used:
```
taskRef:
    resolver: http
    params:
      - name: url
        value: https://raw.githubusercontent.com/tektoncd-catalog/git-clone/main/task/git-clone/git-clone.yaml
      - name: sha256sum
        value: 2ba5253270551c0ab46dd164a3d00173c784142bcdc761a6340054854e3c3fec
```

**Comment by lcarva** [comment]
sha1 is probably not ok. The remaining support for that is basically to support git commit IDs. sha256 and sha512 both work. I'm not seeing any recommendation from SLSA Provenance perspective, but I do see that the [ResourceDescriptor](https://slsa.dev/spec/v1.1/provenance) has these:

```
    "digest": {
        "sha256": string,
        "sha512": string,
        "gitCommit": string,
        [string]: string,
    },
```

That implies support for multiple digest algorithms. I like your suggestion of using the `name` for this.

**Comment by zakisk** [comment]
Thanks! @lcarva & @aThorp96, I will go with the solution Andrew suggested and will do:

```
taskRef:
    resolver: http
    params:
      - name: url
        value: https://raw.githubusercontent.com/tektoncd-catalog/git-clone/main/task/git-clone/git-clone.yaml
      - name: [sha256sum | sha512sum]
        value: 2ba5253270551c0ab46dd164a3d00173c784142bcdc761a6340054854e3c3fec
```

**Comment by vdemeester** [comment]
@zakisk @aThorp96 any reason for not doing something like the following ?

```
taskRef:
    resolver: http
    params:
      - name: url
        value: https://raw.githubusercontent.com/tektoncd-catalog/git-clone/main/task/git-clone/git-clone.yaml
      - name: digest
        value: sha512:2ba5253270551c0ab46dd164a3d00173c784142bcdc761a6340054854e3c3fec
```
