### ISSUE TITLE
Documentation in correct for pipelinerun taskRunSpecs

### ISSUE THREAD

**Issue by jwitrick** [tektoncd/pipeline#8770]
# Expected Behavior

Specifically this section: https://tekton.dev/docs/pipelines/compute-resources/#configure-task-level-compute-resources

The documentation does not have any information about the breaking changes to the pipelinerun schema between v1beta1 and v1.

In V1beta1 the schema for overriding task step level compute resources is:

```
kind: PipelineRun
spec:
  taskRunSpecs:
    - pipelineTaskName: foo
      stepOverrides:
        - name: foo 
          resources:
            requests:
              cpu: 1 
      computeResources:
        requests:
          cpu: 2
``` 

BUT in v1 the schema is:

```
kind: PipelineRun
spec:
  taskRunSpecs:
    - pipelineTaskName: foo
      stepSpecs:
        - name: foo 
          computeResources:
            requests:
              cpu: 1 
```

No where the docs is this information specified. Also (not sure if this is a bug) in each taskrunspec item I am unable to specify both `stepSpecs` AND `computerResources`. This could be a bug or a feature.. but either way its NOT documented.
