### ISSUE TITLE
Enable `golangci-lint` linter `usetesing` context checks for go >= 1.24.

### ISSUE THREAD

**Issue by twoGiants** [tektoncd/pipeline#8805]
## Description

Since go version 1.24 `golangci-lint` linter `usetesing` performs checks if `context.Background()` and `context.TODO()` are used in tests and if so returns errors. Instead `T.Context` should be used as the [go 1.24 release docs](https://tip.golang.org/doc/go1.24#testingpkgtesting) propose. We deactivated those checks in #8803 and the issue for this pull request is here #8804.

This issue proposes to re-enable the checks and open a PR with an update to all the tests. The change would be: 

- [x] remove this lines from `.golangci.yaml`:
  ```yaml
      usetesting:
        context-background: false
        context-todo: false
  ``` 
- [x] update affected tests: replace `context.Background()` and `context.TODO()` with `T.Context`
