### ISSUE TITLE
Failed to parse image ${inputs.params.DOCKER_IMAGE}: could not parse reference

### ISSUE THREAD

**Issue by cmoulliard** [tektoncd/pipeline#885]
## Error

The following task when processed generates this error

```
Message:               
References a Task kube-system/s2i-jdk8 that doesn't exist:  couldn't create redirected TaskSpec: 
failed to add entrypoint to steps of TaskRun s2i-springboot-example: Failed to fetch remote image
${inputs.params.DOCKER_IMAGE}: Failed to parse image ${inputs.params.DOCKER_IMAGE}: could not 
parse reference
```

## Config

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: s2i-jdk8
spec:
  inputs:
    params:
      - name: GIT_URL
        default: https://github.com/snowdrop/rest-http-example
      - name: BUILDER_IMAGE
        description: The location of the builder image.
        default: docker.io/kbaig/s2i
      - name: S2I_IMAGE
        description: The location of the s2i builder image.
        default: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
      - name: BUILDAH_IMAGE
        description: The location of the s2i builder image.
        default: quay.io/openshift-pipeline/buildah
      - name: DOCKER_IMAGE
        description: The location of the docker client image.
        default: gcr.io/cloud-builders/docker
      - name: TLSVERIFY
        description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
        default: "true"
      - name: BUILD_IMAGE
        default: quay.io/snowdrop/spring-boot-example
  steps:
    - name: s2ibuild
      image: ${inputs.params.BUILDER_IMAGE}
      command:
      - s2i
      args:
      - build
      - ${inputs.params.GIT_URL}
      - ${inputs.params.S2I_IMAGE}
      - ${inputs.params.BUILD_IMAGE}
      volumeMounts:
      - name: docker-sock-volume
        mountPath: /var/run/docker.sock
      securityContext:
        privileged: true

    - name: docker-push
      image: ${inputs.params.DOCKER_IMAGE}
      args:
      - push
      - ${inputs.params.BUILD_IMAGE}
      volumeMounts:
      - name: docker-sock-volume
        mountPath: /var/run/docker.sock

  volumes:
    - name: docker-sock-volume
      hostPath:
        path: /var/run/docker.sock
```
