### ISSUE TITLE
Why does the input resource name have to show up in pathToDockerFile and pathToContext 

### ISSUE THREAD

**Issue by houshengbo** [tektoncd/pipeline#888]
This is the example used at the page: https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#task-inputs-and-outputs to create a task:
```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/docker-source/Dockerfile
      - name: pathToContext
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/docker-source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/builder/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=${outputs.resources.builtImage.url}
        - --context=${inputs.params.pathToContext}
```
It took me hours to figure out we have to keep the input resource name, like "docker-source" as defined in this example, in pathToDockerFile and pathToContext as part of the prefix "/workspace/docker-source", then continue the REAL path to dockerfile or context. Why is it implemented like this? 
The input resource name actually has nothing to do with pathToDockerFile and pathToContext.
