### ISSUE TITLE
Variable substitution in PipelineResource definition

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#914]
Recently, I try to implement demo for event triggered Pipelinerun, one thing bothers me,
The pipelineResource definition depends on the content of event, in my solution, I use placeholder like “event.foo” and replace them when pipelineReousrce loaded.
Then I realized in tekton, there is variable substitution solution: Pipelinerun.params

So could we replace the placeholders in PipelineResources with the params defined in PipelineRun.

**Comment by bobcatfish** [comment]
> So could we replace the placeholders in PipelineResources with the params defined in PipelineRun.

Could you give an example of what this might look like in the PipelineRun and the PipelineResource @vincent-pli ?

I'm not sure if you have seen https://github.com/tektoncd/experimental/tree/master/tekton-listener#eventbinding which @iancoffey is working on but in the example there, you can use values from the triggering event to build the eventual `PipelineResources`:

```yaml
  resourceTemplates:
   - name: gitTemplate
     template:
       metadata:
       spec:
         type: git
         params:
         - name: revision
           valueFrom:
             fieldName: event.repo.revision
         - name: url
           valueFrom:
             fieldName: event.repo.name
```

**Comment by vincent-pli** [comment]
@bobcatfish 
I mean we can define the PipelineSource like this:
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-git
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: ${params.repoAddress}
```
And the placeholder will be replaced by params defined in Pipelinerun or Taskrun.
With the ability, we have a PipelineResource template.

Actually, I keep tracking the `eventbinding` from @iancoffey, I like that project.
with the PipelineResource template, the `eventbinding` only need binding the event with the params defined in Pipelinerun, one entry.
