### ISSUE TITLE
invalid input resources: TaskRun's declared resources didn't match usage in Task: Didn't provide required values

### ISSUE THREAD

**Issue by sarnaudova** [tektoncd/pipeline#929]
# Expected Behavior
This pipeline should run without problems. In fact with separate taskrun outside of the pipeline it succeed, but put into the pipeline, the pipelinerun throw an error about input resource usage. I am following the doc and examples from the doc and couldn't figure why it is not working. Can someone take a look and help.

# Actual Behavior
invalid input resources: TaskRun's declared resources didn't match usage in Task: Didn't provide required values: [docker-source]
# Steps to Reproduce the Problem

1. tekton v 0.3.1
2. Adding the pipeline:
```yaml
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: my-golang-app-image
spec:
  type: image
  params:
  - name: url
    value: lm-sjc-11012820.corp.ebay.com:5000/my-golang-app-image
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: my-golang-app-git
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.corp.ebay.com/sarnaudova/kaniko
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/docker-source/Dockerfile
      - name: pathToContext
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/docker-source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      env:
        - name: "DOCKER_CONFIG"
          value: "/builder/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=${outputs.resources.builtImage.url}
        - --context=${inputs.params.pathToContext}
        - --insecure
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: demo-deploy-kubectl
spec:
  inputs:
    resources:
    - name: git-source
      type: git
    - name: image
      type: image
    params:
    - name: path
      description: Path to the manifest to apply
    - name: yqArg
      description: Okay this is a hack, but I didn't feel right hard-codeing `-d1` down below
    - name: yamlPathToImage
      description: The path to the image to replace in the yaml manifest (arg to yq)
    clusters:
    - name: targetCluster
      description: Not yet used, kubectl command below should use this cluster
  steps:
  - name: replace-image
    image: mikefarah/yq
    command: ['yq']
    args:
    - "w"
    - "-i"
    - "${inputs.params.yqArg}"
    - "${inputs.params.path}"
    - "${inputs.params.yamlPathToImage}"
    - "${inputs.resources.image.url}"
  - name: run-kubectl
    image: lachlanevenson/k8s-kubectl
    command: ['kubectl']
    args:
    - 'apply'
    - '-f'
    - '${inputs.params.path}'
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: app-image
      type: image    
  tasks:
  - name: build-app
    taskRef:
      name: build-docker-image-from-git-source
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: app-image 
      params:
        - name: pathToDockerFile
          value: /workspace/docker-source/workspace/Dockerfile
        - name: pathToContext
          value: /workspace/docker-source/workspace #configure: may change according to your source
  - name: deploy-app
    runAfter: [build-app]
    taskRef:
      name: demo-deploy-kubectl
      resources:
        inputs:
          - name: git-source
            resource: source-repo
          - name: image
            resource: app-image
            from:
            - build-app
      params:
      - name: path
        value: /workspace/git-source/workspace/Deployment.yaml
      - name: yqArg
        value: "-d1"
      - name: yamlPathToImage
        value: "spec.template.spec.containers[0].image"
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: demo-pipeline-run-1
spec:
  trigger:
    type: manual
  serviceAccount: build-bot
  pipelineRef:
    name: demo-pipeline
  resources:
  - name: source-repo
    resourceRef:
      name: my-golang-app-git
  - name: app-image
    resourceRef:
      name: my-golang-app-image
``` 

# Additional Info

**Comment by bobcatfish** [comment]
Hey @sarnaudova ! That's super weird, are you 100% sure that's the right error?

```
invalid input resources: TaskRun's declared resources didn't match usage in Task: Didn't provide required values: [docker-source]
```

This error talks about a `TaskRun`, but you're saying the `PipelineRun` is what is failing, is there any chance the `PipelineRun` itself has a different error? Maybe you could paste in complete status of the `PipelineRun` after you create it, e.g. `kubectl get pipelinerun demo-pipeline-run-1 -o yaml`?

**Comment by sarnaudova** [comment]
Hi @bobcatfish thanks for looking into it. This is the result of running the command below:
```
kubectl get pipelinerun demo-pipeline-run-1 -o yaml
```
I used to run the task with TaskRun, butI delete all task runs and  currently "kubectl get taskrun" return "No resource found". I am running in local minikube. 

```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1alpha1","kind":"PipelineRun","metadata":{"annotations":{},"name":"demo-pipeline-run-1","namespace":"default"},"spec":{"pipelineRef":{"name":"demo-pipeline"},"resources":[{"name":"source-repo","resourceRef":{"name":"my-golang-app-git"}},{"name":"app-image","resourceRef":{"name":"my-golang-app-image"}}],"serviceAccount":"build-bot","trigger":{"type":"manual"}}}
  creationTimestamp: "2019-05-29T04:03:26Z"
  generation: 1
  name: demo-pipeline-run-1
  namespace: default
  resourceVersion: "190968"
  selfLink: /apis/tekton.dev/v1alpha1/namespaces/default/pipelineruns/demo-pipeline-run-1
  uid: b5a05935-81c6-11e9-8987-ce76df3bb53c
spec:
  pipelineRef:
    name: demo-pipeline
  resources:
  - name: source-repo
    resourceRef:
      name: my-golang-app-git
  - name: app-image
    resourceRef:
      name: my-golang-app-image
  serviceAccount: build-bot
  trigger:
    type: manual
status:
  completionTime: "2019-05-29T04:03:26Z"
  conditions:
  - lastTransitionTime: "2019-05-29T04:03:26Z"
    message: 'invalid input resources: TaskRun''s declared resources didn''t match
      usage in Task: Didn''t provide required values: [docker-source]'
    reason: PipelineValidationFailed
    status: "False"
    type: Succeeded
  startTime: "2019-05-29T04:03:26Z"
```

**Comment by bobcatfish** [comment]
> Could it be some that there are some un-cleaned references to taskrun objects referencing the same tasks ?

:thinking: the PipelineRun controller [_should_ be adding a randomly generated suffix to any TaskRuns it creates](https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go#L277) so i'm not sure that's it

It sounds like the PipelineRun controller is creating TaskRuns that don't match the spec of the reference Task :thinking:  Ideas for what coule be happening:

* One (or both) of the `Tasks` applied to the cluster has a different spec than the one you pasted above (e.g. maybe it's an old or new version?)
* Same thing but it's the `Pipeline` (different from what you pasted above)
* The controller version is old and needs to be updated? (a bit of a stretch maybe :sweat_smile: )
* Maybe you didn't change the name of the `PipelineRun` before applying it and you're actually looking at the results of a previous run? (`PipelineRun` names have to be unique so you need to either change the name between runs or delete the `PipelineRun` before applying it)
* ???

One way to figure out what's going on (or at least fix it) would be to delete all Pipelines, Tasks, PipelineRuns, TaskRuns and start over (maybe re-install the controller also).

**Comment by sarnaudova** [comment]
@bobcatfish thank you for your suggestions it was really helpful. I started deleting all the objects that I have previously created in my cluster- Tasks, TaskRuns, Pipeline, Pipelineruns, PipelineResources, but I was still seeing the same error. Then I decided to create a new cluster + install the latest tekton (pre-released v0.4.0) - still the same error. Then after looking into the pipeline spec I realized that I've wrongly put "params" section of Pipeline spec after "resources", which apparently was causing this problem. The pipeline validation failure was correct just the error message was a little confusing. 
I will close the issue as a user error :).
Appreciate your help.

**Comment by bobcatfish** [comment]
Oh great! I'm glad you got it working @sarnaudova !! :D

Is there any chance you could paste in the `Pipeline` definition that _does_ work? Looking at your Pipeline it still seems like it _should_ work - the order of the sections _shouldn't_ matter :crossed_fingers:  (I wonder if there was an indentation issue?)

**Comment by sarnaudova** [comment]
@bobcatfish below is the working version of the pipeline. I am not really sure why this one works, but it does :)
 
```yaml
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: my-golang-app-image
spec:
  type: image
  params:
  - name: url
    value: lm-sjc-11012820.corp.ebay.com:5000/my-golang-app-image
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: my-golang-app-git-1
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.corp.ebay.com/sarnaudova/kaniko
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-app-task
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/source/Dockerfile
      - name: pathToContext
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      env:
        - name: "DOCKER_CONFIG"
          value: "/builder/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=${outputs.resources.builtImage.url}
        - --context=${inputs.params.pathToContext}
        - --insecure
---        
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-app-task
spec:
  inputs:
    resources:
    - name: git-source
      type: git
    - name: image
      type: image
    params:
    - name: path
      description: Path to the manifest to apply
    - name: yqArg
      description: Okay this is a hack, but I didn't feel right hard-codeing `-d1` down below
    - name: yamlPathToImage
      description: The path to the image to replace in the yaml manifest (arg to yq)
    clusters:
    - name: targetCluster
      description: Not yet used, kubectl command below should use this cluster
  steps:
  - name: replace-image
    image: mikefarah/yq
    command: ['yq']
    args:
    - "w"
    - "-i"
    - "${inputs.params.yqArg}"
    - "${inputs.params.path}"
    - "${inputs.params.yamlPathToImage}"
    - "${inputs.resources.image.url}"
  - name: run-kubectl
    image: lachlanevenson/k8s-kubectl
    command: ['kubectl']
    args:
    - 'apply'
    - '-f'
    - '${inputs.params.path}'        
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline2
spec:
  resources:
  - name: source-repo
    type: git
  - name: app-image
    type: image
  tasks:
  - name: build-app
    taskRef:
      name: build-app-task
    params:
      - name: pathToDockerFile
        value: /workspace/source/workspace/Dockerfile
      - name: pathToContext
        value: /workspace/source/workspace      
    resources:
      inputs:
      - name: source
        resource: source-repo
      outputs:
      - name: builtImage
        resource: app-image
  - name: deploy-app
    runAfter: [build-app]
    taskRef:
      name: deploy-app-task
    params:
      - name: path
        value: /workspace/git-source/workspace/Deployment.yaml
      - name: yqArg
        value: "-d1"
      - name: yamlPathToImage
        value: "spec.template.spec.containers[0].image"
    resources:
      inputs:
      - name: git-source
        resource: source-repo
      - name: image
        resource: app-image
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipeline2-run
spec:
  trigger:
    type: manual
  serviceAccount: build-bot
  pipelineRef:
    name: pipeline2
  resources:
  - name: source-repo
    resourceRef:
      name: my-golang-app-git-1
  - name: app-image
    resourceRef:
      name: my-golang-app-image
```
