### ISSUE TITLE
PipelineRun keeps "running" although all tasks seem completed

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/pipeline#960]
Hi,

I´m using tekton for the first time hand have the following simple pipeline definition:

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: say-hello
spec:
  steps:
    - name: say-hello
      image: ubuntu
      command:
        - echo
      args: ['Hello World!']
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  tasks:
    - name: hello-task
      taskRef:
        name: say-hello
```

When I create a PipelineRun for it, I can see that a pod is created and also that the pod finishes with the status Completed. The dashboard however still displays the PipelineRun with the status "Not all Tasks in the Pipeline have finished executing". A kubectl describe pipelinerun also shows the event

```
 Warning  PipelineRunFailed  116s (x3 over 118s)  pipeline-controller  PipelineRun failed to update
```

Do you have any hint for me what is going wrong here?

Thanks!
