### ISSUE TITLE
operator extensible pipeline credentials (-creds-image)

### ISSUE THREAD

**Issue by objectiveous** [tektoncd/pipeline#989]
## Background 

Tekton currently has support for the provisioning of ```Build Tooling Configuration```. For example,  we have support for docker config (/builder/home/.docker/config.json) and git credentials (/builder/home/.ssh, /builder/home/..git-credentials, etc) but the provisioning mechanism is not extensible to Tekton operators (the human kind, not controllers). 

By way of example, consider the use of gradle with an onprem artifact repository that requires credentials. In this scenario, gradle requires the existence of ```/builder/home/.gradle/gradle.properties```: 

```
artifactory_user=$USER
artifactory_password=$TOKEN
artifactory_contextUrl=https://artifacts.corp.com
```

## Enhancement Request 

Please consider making the provisioning of tooling configuration an extension point of tekton. 

## Proposed Design 

TBD

**Comment by vdemeester** [comment]
This is also a bit related to #238 as it would be nice to have a extensiblitiy mecanisms for initializer too

/kind feature
/kind design

**Comment by sbwsg** [comment]
This issue relates to, and is perhaps superceded by, https://github.com/tektoncd/pipeline/issues/2343 which is a more recent proposal for making credentials a declarable part of a Task's description.

**Comment by jlpettersson** [comment]
This can be done as by mounting the secret in a [projected volume](https://kubernetes.io/docs/concepts/storage/volumes/#projected)

Create a secret from your `gradle.properties`

```
kubectl create secret generic gradle-secret --from-file=gradle.properties
```

A "dummy-task", as an example how to access the `gradle.properties` file in a Task

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gradle-dummy-task
spec:
  steps:
  - name: print-gradle-secret
    image: ubuntu
    script: cat /builder/home/.gradle/gradle.properties
    volumeMounts:
    - mountPath: /builder/home/.gradle
      name: gradle-properties
  volumes:
  - name: gradle-properties
    projected:
      sources:
      - secret:
          name: gradle-secret
          items:
          - key: gradle.properties
            path: gradle.properties
```
