### ISSUE TITLE
Unable to push image to private docker registry if URL is not using the default 443 port

### ISSUE THREAD

**Issue by hollisc** [tektoncd/pipeline#992]
# Expected Behavior
Built image to be pushed to private docker registry.

# Actual Behavior
The "build-step-build-and-push" step fails in the TaskRun of the tutorial (https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md) if using a private docker registry using a different port than 443.  From the error message, it appears to be complaining about the `:` in the image URL. 

The error from the step is: 

```
error pushing image: getting tag for destination: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: /<IP of Private Registry>:8500/tekton-pipelines/leeroy-web
```

# Steps to Reproduce the Problem

1. Install Tekton on an existing Kubernetes cluster (https://github.com/tektoncd/pipeline/blob/master/docs/install.md). 
2. Run through tutorial to build and push an image (https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#pipeline) to a private docker registry.  When creating the TaskRun resource, run fails on the "build-step-build-and-push" step.

Here is the yaml of the PipelineResource for Image resource: 

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-image-leeroy-web
spec:
  type: image
  params:
    - name: url
      value: https://<IP Address>:8500/tekton-pipelines/leeroy-web
```
