### ISSUE TITLE
Tasks/pipelines/containers have the wrong time

### ISSUE THREAD

**Issue by AdityaGupta1** [tektoncd/pipeline#998]
# Expected Behavior

When I apply a `PipelineRun` and run `kubectl get` on it, it should say it started at the same time as I applied it (in this case, approximately `2019-06-20T18:31:04Z`).

# Actual Behavior

I applied a `PipelineRun` just now and ran `kubectl get`, and the start date was listed as `2019-06-15T17:00:41Z`, which is five days before now.

# Steps to Reproduce the Problem

Make a `TaskRun` as follows

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: test
spec:
  taskSpec:
    steps:
      - name: test
        image: ubuntu
        command: ["date"]
```

Apply it, and once it's finished, see the logs and the time should be some days before the current time.

# Additional Info

I made a `Task` to make a change to a Git repository then commit it, and the commits showed up as from five days ago.
